SELECT
	P.ID,
	P.CONTATO,
	CAST (P.DATACADASTRO AS DATE) AS CADASTRO,
	CAST (P.DATANASCIMENTO AS DATE) AS NASCIMENTO,	
	P.CPF_CNPJ AS CNPJ_CNPF,
	CASE WHEN P.RG = '' OR P.RG IS NULL THEN P.INSCRICAOESTADUAL ELSE P.RG END AS IE_RG,
	P.INSCRICAOMUNICIPAL AS IM,
	P.NOMEFANTASIA AS FANTASIA,
	P.RAZAOSOCIAL AS NOME,
	P.OBSERVACAO AS OBSERVACOES,
	P.SEXO,
	P.PROFISSAO,
	P.EMAIL,
	U.SIGLA AS UF,
	CONCAT (E.COMPLEMENTO,' - ',E.REFERENCIA) AS COMPLEMENTO,
	E.NUMERO,
	B.NOME AS BAIRRO,
	C.CEP,
	CI.NOME AS CIDADE,
	R.NOME AS ENDERECO,
	T.NUMERO AS TELEFONE,
--	CA.NOMEPESSOA AS CONTATO,
	CA.NUMEROTELEFONE AS CELULAR
--	CA.EMAIL 
FROM
	PESSOA P
LEFT JOIN UF U ON U.ID = P.IDUFIE
LEFT JOIN ENDERECOPESSOA EP ON EP.IDPESSOA = P.ID 
LEFT JOIN ENDERECO E ON E.ID = EP.IDENDERECO 
LEFT JOIN BAIRRO B ON B.ID = E.IDBAIRRO 
LEFT JOIN CEP C ON C.ID = E.IDCEP 
LEFT JOIN CIDADE CI ON CI.ID = E.IDCIDADE 
LEFT JOIN RUA R ON R.ID = E.IDRUA 
LEFT JOIN TELEFONE T ON T.IDPESSOA = P.ID 
LEFT JOIN CONTATOSADICIONAIS CA ON CA.IDPESSOA = P.ID 
