SELECT
	I.NCOD___ITPROD AS CODIGO,
	I.VDESCR_ITPROD AS DESCRICAO,	
	DATE(I.DREGISTITPROD) AS DATA_CADASTRO,		
	I.NPESO__ITPROD AS PESO,
	I.NTIPO__ITPROD AS PERSONAL1,
	I.vrefer_itprod as PERSONAL2,
	I.VCODFABITPROD AS FORNECEDOR,
	I.VNCM___NCMPRD AS COD_NCM,
	G.VDESCR_GRITPR AS GRUPO,
	U.VSIGLA_UNIDAD AS UND,
	M.VDESCR_MARCAS AS FAMILIA,
	B.VCODBARITBARC AS BARRAS,
	P.NPRAZO_PRECIF AS PERSONAL4,
	P.NVISTA_PRECIF AS PRECO_VENDA,
	P.NMRGVSTPRECIF AS MARGEM_LUCRO,
	P.NCUSTO_PRECIF AS PRECO_CUSTO,
	EF.VCOD___ITFORN AS COD_FABRICANTE,
	E.nqtdestestqit as QTD,
	E.nqtdcrtestqit as QTD_IDEAL
FROM
	ESTQ.ITPROD I
LEFT JOIN ESTQ.GRITPR G ON G.NID____GRITPR = I.NID____GRITPR AND G.CSITUACREGSIN = 'A'
LEFT JOIN ESTQ.UNIDAD U ON U.NID____UNIDAD = I.NID____UNIDAD AND U.CSITUACREGSIN = 'A'
LEFT JOIN ESTQ.MARCAS M ON M.NID____MARCAS = I.NID____MARCAS AND M.CSITUACREGSIN = 'A'
LEFT JOIN ESTQ.ITBARC B ON B.NID____ITPROD = I.NID____ITPROD --AND G.CSITUACREGSIN = 'A'
LEFT JOIN ESTQ.PRECIF P ON P.NID____ITPROD = I.NID____ITPROD AND P.CSITUACREGSIN = 'A'	
LEFT JOIN ESTQ.ITFORN EF ON EF.NID____ITPROD = I.NID____ITPROD AND EF.CSITUACREGSIN = 'A'	
left join ESTQ.estqit e on E.nid____itprod  = I.NID____ITPROD AND E.CSITUACREGSIN = 'A'
WHERE I.CSITUACREGSIN = 'A'
ORDER BY I.NCOD___ITPROD