SELECT
    PRODUTOS.CODPROD AS COD_FABRICANTE,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.CODBARRAS AS BARRAS,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.QUANT AS QTD,
    PRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
    PRODUTOS.MARCA AS CARACTERISTICAS,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.CUSTOUNIT AS PRECO_CUSTO,
    PRODUTOS.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARLUCRVISTA AS MARGEM_LUCRO,
    PRODUTOS.PRECO AS PRECO_VENDA,
    PRODUTOS.OBSERVACOES AS OBSERVACOES,
    PRODUTOS.DATA AS DATA_CADASTRO,
    PRODUTOS.ULTVENDA AS ULTIMA_VENDA,
    PRODUTOS.ULTENTRADA AS ULTIMA_COMPRA,
    PRODUTOS.ALIQIPI AS ALIQ_IPI,
    CASE PRODUTOS.INATIVO WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS situacao,
    PRODUTOS.CST AS ST,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    GRUPOS.DESCRICAO AS GRUPO,
    CAD_GERAL.RAZAO AS fornecedor
    FROM PRODUTOS
LEFT JOIN grupos ON GRUPOS.codgrupo = PRODUTOS.grupo
LEFT JOIN CAD_GERAL ON CAD_GERAL.CODCAD = PRODUTOS.FORNECEDOR 
