SELECT
PRODUTOS.ID_PRODUTO AS CODIGO,
PRODUTOS.DESCRICAO,
UNIDADES.CODIGO AS UND,
PRODUTOS.CODIGO_BARRA AS BARRAS,
PRODUTOS.CUSTO_UNITARIO AS PRECO_CUSTO,
PRODUTOS.PC_MARGEM_LUCRO_1 AS MARGEM_LUCRO,
PRODUTOS.PRECO_VENDA_1 AS PRECO_VENDA,
PRODUTOS.DT_ALTERACAO AS ALTERACAO_PRECO,
PRODUTOS.CODIGO_FABRICANTE AS COD_FABRICANTE,
PRODUTOS.CEST AS PERSONAL6,
TABELA_NCM.NCM AS COD_NCM,
GRUPOS.DESCRICAO AS GRUPO,
HISTORICO_ESTOQUE.SALDO
FROM PRODUTOS
LEFT JOIN UNIDADES ON PRODUTOS.ID_UNIDADE=UNIDADES.ID_UNIDADE
LEFT JOIN TABELA_NCM ON PRODUTOS.ID_NCM=TABELA_NCM.ID_NCM
LEFT JOIN GRUPOS ON PRODUTOS.ID_GRUPO_PRODUTO=GRUPOS.ID_GRUPO
LEFT JOIN HISTORICO_ESTOQUE ON PRODUTOS.ID_PRODUTO= HISTORICO_ESTOQUE.ID_HISTORICO_ESTOQUE





