SELECT
	CLIENTECODIGO AS CODIGO,
	CLIENTENOME AS NOME,
	CLIENTEFANTASIA AS FANTASIA,
	CLIENTEENDERECO AS ENDERECO,
	CLIENTEBAIRRO AS BAIRRO,
	CLIENTECEP AS CEP,
	CLIENTECIDADE AS CIDADE,
	CLIENTEESTADO AS UF,
	CLIENTEFONE AS TELEFONE,
	CASE WHEN CLIENTECGC = '' THEN CLIENTE.CLIENTECPF ELSE CLIENTE.CLIENTECGC END AS CNPJ_CNPF,
	CLIENTEINSCRICAO AS IE_RG,
	CLIENTECONTATO AS CONTATO,
	CLIENTEFAX AS FAX,
	CLIENTEEMAIL AS EMAIL
FROM CLIENTE
