SELECT
	FORNECEDORCODIGO AS CODIGO,
	FORNECEDORNOME AS NOME,
	FORNECEDORENDERECO AS ENDERECO,
	FORNECEDORBAIRRO AS BAIRRO,
	FORNECEDORCEP AS CEP,
	FORNECEDORCIDADE AS CIDADE,
	FORNECEDORESTADO AS UF,
	FORNECEDORFONE AS TELEFONE,
	FORNECEDORFAX AS FAX,
	FORNECEDORCGC AS CNPJ_CNPF,
	FORNECEDORINSCRICAO AS IE_RG,
	FORNECEDOREMAIL AS EMAIL
FROM FORNECEDOR
