SELECT
    CODIGO AS CODIGO,
    RAZAO_SOCIAL AS NOME,
    NOME_FANTASIA AS FANTASIA,
    ENDERECO,
    ENDERECO_NRO AS NUMERO,
    ENDERECO_COMPLEMENTO AS COMPLEMETNO,
    BAIRRO,
    CIDADE,
    UF,
    CEP,
    CGC AS CNPJ_CNPF,
    IE AS IE_RG,
    DDD||FONE1 AS TELEFONE,
    FAX,
    EMAIL
FROM FORNECEDORES
