SELECT 
  P.COD_PRODUTO AS CODIGO
, P.SKU_ECOMMERCE AS BARRAS
, P.NOME_PRODUTO AS DESCRICAO
, P.REF_VENDA AS COD_FABRICANTE
-- , P.COD_PRODUTO_FORNECEDOR AS COD_FABRICANTE
, P.QTDE_ESTOQUE AS QTD
, P.VR_CUSTO AS PRECO_CUSTO
, CASE P.STATUS_ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.UNIDADE AS UND
, P.PERC_IPI AS ALIQ_IPI_VENDA
, P.VR_VENDA AS PRECO_VENDA
-- , P.VR_VENDA_PRAZO
, P.PERC_LUCRO AS MARGEM_LUCRO
, P.QTDE_ESTOQUE_MIN AS QTD_IDEAL
, P.DT_ULTIMA_COMPRA AS ULTIMA_COMPRA
, P.DT_ULTIMA_VENDA AS ULTIMA_VENDA
, P.LOCALIZACAO AS PERSONAL1
, P.PESO
, P.PERC_ICMS AS ELO
, P.PERC_COMISSAO AS COMISSAO
, P.TAMANHO
, P.DT_CADASTRO AS DATA_CADASTRO
, P.NOME_CATEGORIA AS CARACTERISTICAS
, P.QTDE_POR_UNIDADE AS FAT_CONV
, P.VR_CUSTO_MEDIO AS CUSTO_MEDIO
, P.ORIGEM_MERCADORIA AS OST
, P.QTDE_DIAS_DT_VALIDADE AS VALIDADE_DIAS
, P.CEST AS PERSONAL6
, P.OBSERVACAO AS OBSERVACOES
, P.IPPT
-- , P.CST_ICMS AS ST
, P.CST_CSOSN AS ST
, P.CST_IPI AS IPI_CODIGO_VENDA
, P.CST_PIS AS PIS_CODIGO
, P.CST_COFINS AS COFINS_CODIGO
, P.TABELA_ALIQUOTA_NOTA_IPI AS ALIQ_IPI_VENDA
, P.TABELA_ALIQUOTA_NOTA_PIS AS PIS_ALIQ_NOR
, P.TABELA_ALIQUOTA_NOTA_COFINS AS COFINS_ALIQ_NOR
-- , P.COD_CFOP_SAIDA_DE AS CF
-- , P.COD_ALIQUOTA
-- , P.COD_ST_CSOSN
-- , P.COD_ST_IPI
-- , P.COD_ST_PIS
-- , P.COD_ST_COFINS
-- , P.COD_SITUACAO_TRIBUTARIA
-- , P.COD_SUB_GRUPO_PRODUTO
, TN.DESCRICAO AS COD_NCM
, TTP.NOME_TIPO_PRODUTO AS FAMILIA
, TS.NOME_SETOR AS PERSONAL2
, TC.NOME_COR AS COR
, TGP.NOME_GRUPO_PRODUTO AS GRUPO
, TF.NOME_FORNECEDOR AS FORNECEDOR
FROM TAB_PRODUTO P
LEFT JOIN TAB_TIPO_PRODUTO TTP ON TTP.COD_TIPO_PRODUTO = P.TIPO_PRODUTO
LEFT JOIN TAB_NCM TN ON TN.COD_NCM = P.COD_NCM
LEFT JOIN TAB_SETOR TS ON TS.COD_SETOR = P.COD_SETOR
LEFT JOIN TAB_COR TC ON TC.COD_COR = P.COD_COR
LEFT JOIN TAB_GRUPO_PRODUTO TGP ON TGP.COD_GRUPO_PRODUTO = P.COD_GRUPO_PRODUTO
LEFT JOIN TAB_FORNECEDOR TF ON TF.COD_FORNECEDOR = P.COD_FORNECEDOR