SELECT CD_FORNECEDOR AS CODIGO,
       NM_FORNECEDOR AS NOME,
       NM_FANTASIA AS FANTASIA,
       ENDERECO AS ENDERECO,
       BAIRRO AS BAIRRO,
       CIDADE.NM_CIDADE AS CIDADE,
       CIDADE.UF AS UF,
       CEP AS CEP,
       FONE AS TELEFONE,
       FAX AS FAX,
       PESSOA_CONTATO AS CONTATO,
       CNPJ AS CNPJ_CNPF,
       INSCRICAO AS IE_RG,
       E_MAIL AS EMAIL,
       CELULAR AS CELULAR,
       NUMERO AS NUMERO,
       COMPLEMENTO AS COMPLEMENTO
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.CD_CIDADE = FORNECEDOR.CD_CIDADE
