SELECT PRODUTO.CD_PRODUTO AS CODIGO,
       PRODUTO.NM_PRODUTO AS DESCRICAO,
       GRUPROD.NM_GRUPROD AS GRUPO,
       PRODUTO.UN_MEDIDA AS UND,
       PRODUTO.PESO_LIQUIDO AS PESO,
       PRODUTO.QT_ESTOQUE_MIN AS IDEAL,
       PRODUTO.QT_ESTOQUE AS QTD,
       TABELA_PRECO_PRODUTO.PRECO_VENDA,
       SUBSTRING (TRIBUTACAO_GRUPO.NM_TRIBUTACAO_GRUPO FROM 1 FOR 1) AS ST,
       PRODUTO_CLASS_FISCAL.NM_CLASS_FISCAL AS COD_NCM,
       CEST.CEST AS PERSONAL6,
       PRODUTO.UN_COMPRA AS UND_COMPRA,
       PRODUTO.DT_CADASTRO AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN PRODUTO_CLASS_FISCAL ON PRODUTO_CLASS_FISCAL.CD_CLASS_FISCAL = PRODUTO.CD_CLASS_FISCAL
LEFT JOIN CEST ON CEST.CD_CEST = PRODUTO_CLASS_FISCAL.CD_CEST
LEFT JOIN TABELA_PRECO_PRODUTO ON TABELA_PRECO_PRODUTO.CD_PRODUTO = PRODUTO.CD_PRODUTO
LEFT JOIN GRUPROD ON GRUPROD.CD_GRUPROD = PRODUTO.CD_GRUPROD
LEFT JOIN TRIBUTACAO_GRUPO ON TRIBUTACAO_GRUPO.ID_TRIBUTACAO_GRUPO = PRODUTO.ID_TRIBUTACAO_GRUPO
