SELECT
    C.IDCLIENTE AS CODIGO,
    C.NOME AS NOME,
    C.FANTASIA AS FANTASIA,
    DC.CONTATO AS CONTATO,
    C.CGCMF AS CNPJ_CNPF,
    case when C.IDENTIDADE = '' or C.IDENTIDADE is null then C.CGCICM else C.IDENTIDADE END AS IE_RG,
    C.CGCICM AS IM,
    DC.ENDERECO AS ENDERECO,
    DC.END_NRO AS NUMERO,
    DC.END_COMPLEMENTO AS COMPLEMENTO,
    B.DESCRICAO AS BAIRRO,
    CD.DESCRICAO AS CIDADE,
    CD.ESTADO AS UF,
    replace(DC.CEP,'-','') AS CEP,
    replace (replace (replace (replace(DC.FONE,'(',''),')',''),'-',''),' ','') AS TELEFONE,
    replace (replace (replace (replace(DC.FAX,'(',''),')',''),'-',''),' ','') AS FAX,
    replace (replace (replace (replace(DC.CELULAR,'(',''),')',''),'-',''),' ','') AS CELULAR,
    DC.EMAIL1 AS EMAIL,
    DC.NOMEPAI AS PAI,
    DC.NOMEMAE AS MAE,
    DC.LIMITECREDITO AS LIMITE_CREDITO,
    DC.ESTADOCIVIL AS EST_CIVIL,
    C.SEXO AS SEXO,
    C.NASCIMENTO AS NASCIMENTO,
    C.DTCADASTRO AS CADASTRO,
    case when DC.SITUACAO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
FROM CLIENTES AS C
LEFT JOIN DADOSCLI DC ON C.IDCLIENTE = DC.IDCLIENTE
LEFT JOIN BAIRROS B ON DC.IDBAIRRO = B.IDBAIRRO
LEFT JOIN CIDADES CD ON DC.IDCIDADE = CD.IDCIDADE
WHERE C.TIPO = 'CLIENTE'