SELECT 
  FOR_ID as CODIGO
, FOR_NOME_FANTASIA as FANTASIA
, FOR_RAZAO_SOCIAL as NOME
, FOR_CNPJ as CNPJ_CNPF
, FOR_IE as IE_RG
, FOR_EMAIL as EMAIL
, FOR_OBS as OBSERVACOES
, FOR_TELEFONE1 as TELEFONE
, FOR_TELEFONE1CON as CELULAR
, FOR_TELEFONE2 as FAX
, FOR_ENDERECO as ENDERECO
, FOR_NUMERO as NUMERO
, FOR_BAIRRO as BAIRRO
, FOR_CIDADE as CIDADE
, FOR_CEP as CEP
, UF_NOME as UF
--, FOR_ESTADO
FROM FORNECEDOR
--WHERE LOJ_ID = '1'
