SELECT 
  P.PRO_ID as CODIGO
, P.PRO_CODIGO_BARRAS as BARRAS
, P.PRO_CODIGO_ORIGINAL as COD_FABRICANTE
--, P.PRO_COD_FABRICANTE
--, P.PRO_CODIGO_DO_FORNECEDOR
, P.PRO_NOME as DESCRICAO
, P.FOR_RAZAO_SOCIAL as  FORNECEDOR
, P.PRO_QTD as QTD
, P.PRO_QTD_POR_CAIXA as FAT_CONV
, P.PRO_EST_MINIMO as QTD_IDEAL
, P.PRO_PRECO as PRECO_CUSTO
, P.PRO_MARGEM_LUCRO as MARGEM_LUCRO
, P.PRO_PRECO_VENDA as PRECO_VENDA
, P.PRO_MINIMO_PRECO_VENDA as ATACADO
, P.PRO_OBS as OBSERVACOES
, LEFT (P.PRO_UNI,3) as UND
, P.PRO_UNI as PERSONAL4
, P.LIN_NOME as CARACTERISTICAS
, GP.GPR_NOME as GRUPO
--, SG.SUBGP_NOME as FAMILIA
, P.PRO_NCM_SH as COD_NCM
, P.PRO_CEST as PERSONAL6
, P.PRO_CST as ST
--, P.PRO_CST_ICMS
--, P.PRO_ICMS_MOD_BC_ICMS
--, P.PRO_ALIQ_ICMS
, LEFT (P.PRO_CFOP,3) as ELO
, P.PRO_PESO as PESO
, P.PRO_REFERENCIA as PERSONAL1
, P.PRO_LOTE as PERSONAL2
, P.PRO_TAMANHO as TAMANHO
, P.PRO_COR as COR
, P.PRO_COMIS_VENDEDOR_PORC as COMISSAO
, P.PRO_IPI_PORCENTAGEM as ALIQ_IPI
, P.PRO_ALIQ_IPI as ALIQ_IPI_VENDA
, P.PRO_CST_IPI as IPI_CODIGO_VENDA
, P.PRO_ALIQ_PIS as PISE_ALIQ_NOR
, P.PRO_ALIQ_COFINS as COFINSE_ALIQ_NOR
, P.PRO_PIS as PISE_CODIGO
, P.PRO_COFINS as COFINS_CODIGO
--, P.PRO_CST_PIS
--, P.PRO_CST_COFINS
, P.PRO_PIS_PORC_ALIQ as PIS_ALIQ_NOR
, P.PRO_COFINS_PORC_ALIQ as COFINS_ALIQ_NOR
, P.PIS as PIS_CODIGO
, P.COFINS as COFINS_CODIGO
--, CASE P.PRO_DESATIVADO WHEN 0 THEN 'Ativo' ELSE 'Inativo' END as SITUACAO
, CASE P.PRO_ATIVO WHEN 1 THEN 'Ativo' ELSE 'Inativo' END as SITUACAO
,   convert(DATE, P.PRO_DATA,103) as DATA_CADASTRO 
,   convert(DATE, P.PRO_DATA_ULT_COMPRA,103) as ULTIMA_COMPRA
,   convert(DATE, P.PRO_DATA_ULT_VENDA,103) as ULTIMA_VENDA
FROM PRODUTO P
LEFT JOIN GRUPO_PRODUTOS GP ON GP.GPR_ID = P.GPR_ID 
--LEFT JOIN SUB_GRUPO_PRODUTOS_OK SG ON SG.SUBGP_ID = P.SUBGP_ID  
--WHERE LOJ_ID = '1'
