SELECT
    CAST (R.RECCOD AS INTEGER) AS ID,
    replace (replace (replace (cast(R.RECCOD as integer),'/',''),'.',''),'-','') ||''|| R.RECDOCUMENTO AS HISTORICO,
    substring (cast (R.RECCOD as integer) ||''|| R.RECDOCUMENTO from 2 for 14) AS DOCUMENTO,
    --R.RECDOCUMENTO AS DOCUMENTO,
    C.CLICOD AS COD_CLIENTE,
    SUBSTRING (C.CLINOME FROM 1 FOR 60) AS NOM_CLIENTE,
    C.CLICNPJ AS CNPJ,
    CAST (R.RECDTLANCAMENTO AS DATE) AS EMISSAO,
    CAST (R.RECDTVENCIMENTO AS DATE) AS VENCIMENTO,
    CAST (R.RECDTPAGAMENTO AS DATE) AS RECEBIMENTO,
    R.RECVALORORIGINAL AS VALOR_DUP,
    R.RECDESCONTO AS VALOR_DES,
    R.RECJUROS AS VALOR_JUR,
    R.RECVALORRECEBIDO AS VALOR_REC,
    R.RECPARCELA AS NUM_PARCELAS,
    R.RECOBS AS OBSERVACOES,
    CAST (R.RECCOD AS INTEGER) AS NUM_CONTA,
    1 AS TIPO_DOC,
    1 AS PORTADOR,
    R.RECDOCREFERENCIA,
    R.RECDETALHEDOC,
    R.ULTALTERA,
    R.RECNUMNOTA
FROM RECEBER AS R
LEFT JOIN CLIENTE C ON R.RECCLIENTE = C.CLICOD
--WHERE R.RECDOCUMENTO = ''
