SELECT
       CODIGO AS CODIGO
      ,RAZAO AS NOME
      ,NOME AS FANTASIA
      ,CONTATO AS CONTATO
      ,CGC_CPF AS CNPJ_CNPF
      ,INS_RG AS IE_RG
      ,INSC_MUNICIPAL AS IM
      ,ENDERECO AS ENDERECO
      ,NUMERO_END AS NUMERO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,ESTADO AS UF
      ,CEP AS CEP
      ,FONE AS TELEFONE
      ,CELULAR AS CELULAR
      ,FAX AS FAX
      ,EMAIL AS EMAIL
      ,N_PAI AS PAI
      ,N_MAE AS MAE
      ,CAST (DATA_NASC AS DATE) AS NASCIMENTO
      ,CAST (ULT_MOV AS DATE) AS ULTIMA_VENDA
      ,CAST (DATA_CAD AS DATE) AS CADASTRO
      ,EST_CIVIL AS EST_CIVIL
      ,CONJUGE AS COJUGE
      ,LIMITE_CR AS LIMITE_CREDITO
      ,SEXO AS SEXO
  FROM DESTINO.dbo.CLIENTES
  WHERE CODIGO > '0'
