SELECT 
  produto.CDPRO AS CODIGO,
  produto.CODI AS BARRAS,
  produto.NOME AS DESCRICAO,
  produto.UNID AS UND,
  produto.UCOMPRA AS UND_COMPRA,
  produto.SITB AS ST,
  produto.PESO AS PESO,
  produto.REFER AS COD_FABRICANTE,
  FORNEC.NOME AS FORNECEDOR,
  produto.ESTOQUE AS QTD,
  produto.MINIMO AS QTD_IDEAL,
  produto.CUSTO AS PRECO_CUSTO,
  produto.MEDIO AS CUSTO_MEDIO,
  produto.LUCROV AS MARGEM_LUCRO,
  produto.VENDA AS PRECO_VENDA,
  produto.ATACADO AS PRECO_ATACADO,
  produto.OBSPRO AS OBSERVACOES,
  produto.NCM AS COD_NCM,
  produto.CEST AS PERSONAL6,
  produto.DTCAD AS DATA_CADASTRO
FROM produto
LEFT JOIN FORNEC ON FORNEC.CODI = produto.CDFOR