SELECT 
    PESSOA.idpessoa AS CODIGO,
    TAB_MUNICIPIOS.NOME AS CIDADE,
    PESSOA.bairro AS BAIRRO,
    PESSOA.razaosocial AS NOME,
    PESSOA.fantasia AS FANTASIA,
    PESSOA.cnpjcpf AS CNPJ_CNPF,
    PESSOA.ierg AS IE_RG,
    PESSOA.endereco AS ENDERECO,
    REPLACE (PESSOA.cep, '-' , '') AS CEP,
    PESSOA.numero AS NUMERO,
    PESSOA.complendereco AS COMPLEMENTO,
    PESSOA.fone1 AS TELEFONE,
    PESSOA.cel1 AS CELULAR,
    PESSOA.fax1 AS FAX,
    PESSOA.email AS EMAIL,
    PESSOA.nomecontato AS CONTATO,
    PESSOA.uf AS UF
FROM PESSOA
LEFT JOIN TAB_MUNICIPIOS ON TAB_MUNICIPIOS.ID = PESSOA.IDCIDADE
WHERE PESSOA.fornecedor = 'S'
