select CLIENTE.DOCTOCLIENTE AS CNPJ_CNPF,
CLIENTE.NOMECLIENTE AS NOME,
CLIENTE.ENDERECO,
CLIENTE.NUMERO,
CLIENTE.CIDADE,
CLIENTE.COMPLEMENTO,
CLIENTE.BAIRRO,
CLIENTE.UF,
CLIENTE.CEP,
CLIENTE.TELEFONES AS TELEFONE,
CLIENTE.NOMEFANTASIA AS FANTASIA,
CLIENTE.INSCRICAOESTADUAL AS IE_RG,
CLIENTE.IDCLIENTE AS CODIGO,
CLIENTE.EMAIL
FROM CLIENTE
WHERE CLIENTE.IDCLIENTE IS NOT NULL


