SELECT FORNECEDOR.IDFORNECEDOR AS CODIGO,
FORNECEDOR.NOMEFANTASIA AS FANTASIA,
FORNECEDOR.NOMEFORNECEDOR AS NOME,
FORNECEDOR.ENDERECO,
FORNECEDOR.NUMERO,
FORNECEDOR.COMPLEMENTO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CIDADE,
FORNECEDOR.CEP,
FORNECEDOR.TELEFONE AS TELEFONE,
FORNECEDOR.EMAIL,
FORNECEDOR.CGC AS CNPJ_CNPF,
FORNECEDOR.INSCRESTADUAL AS IE_RG,
FORNECEDOR.CONTATO,
FORNECEDOR.UF
FROM FORNECEDOR

