SELECT PESSOA.CODPESSOA AS CODIGO,
PESSOA.NOME,
PESSOA.CPFCGC AS CNPJ_CNPF,
PESSOA.RG AS IE_RG,
PESSOA.NOMEFANTAZIA AS FANTASIA,
PESSOA.CEP_1 AS CEP,
PESSOA.LOGRADOURO_1 AS ENDERECO,
PESSOA.BAIRRO_1 AS BAIRRO,
PESSOA.CIDADE_1 AS CIDADE,
PESSOA.UF_1 AS UF,
PESSOA.NUMERO_1 AS NUMERO,
PESSOA.COMPLEMENTO_1 AS COMPLEMENTO,
PESSOA.EMAIL,
PESSOA.FONE AS TELEFONE
FROM PESSOA
WHERE PESSOA.CODPESSOA>0
AND PESSOA.TIPOPESSOA='Cliente'




