SELECT
    TB_CLIFORN.COD_CLIFORN AS CODIGO,
    TB_CLIFORN.DT_CAD AS CADASTRO,
    TB_CLIFORN.NOME_RAZAO AS NOME,
    TB_CLIFORN.FANTASIA,
    TB_CLIFORN.ENDERECO,
    TB_CLIFORN.NUMERO,
    TB_CLIFORN.COMPLEM AS COMPLEMENTO,
    TB_CLIFORN.BAIRRO,
    TB_CLIFORN.CEP,
    TB_CLIFORN.TELEFONE,
    TB_CLIFORN.FAX,
    TB_CLIFORN.CELULAR,
    TB_CLIFORN.EMAIL,
    TB_CLIFORN.CNPJ AS CNPJ_CNPF,
    TB_CLIFORN.INSCRICAO_E AS IE_RG,
    TB_CIDADES.nome_cid AS CIDADE
FROM TB_CLIFORN
LEFT JOIN TB_CIDADES ON TB_CLIFORN.COD_CID = TB_CIDADES.COD_CID