SELECT
    PESSOA.PESCODIGO AS CODIGO,
    PESSOA.PESNOME AS NOME,
    PESJURIDICA.PJUFANTASIA,
    PESSOA.PESCONTATO AS CONTATO,
    PESSOA.PESCPFCNPJ AS CNPJ_CNPF,
    case when PESFISICA.PFIRG = '' or PESFISICA.PFIRG is null then PESJURIDICA.PJUINSESTA else PESFISICA.PFIRG END AS IE_RG,
    PESSOA.PESENDERECO AS ENDERECO,
    PESSOA.PESNUMERO AS NUMERO,
    PESSOA.PESCOMPLEMENTO AS COMPLEMENTO,
    PESSOA.PESBAIRRO AS BAIRRO,
    PESSOA.PESCEP AS CEP,
    CIDADE.CIDNOME AS CIDADE,
    CIDADE.CIDUF AS UF,
    PESSOA.PESEMAIL AS EMAIL,
    PESSOA.PESTELCOM AS TELEFONE,
    PESSOA.PESTELFAX AS FAX,
    PESSOA.PESTELCEL AS CELULAR,
    PESSOA.PESOBS AS OBSERVACOES,
    PESFISICA.PFIDTNASC AS NASCIMENTO,
    PESFISICA.PFIESTCIVIL AS EST_CIVIL,
    PESFISICA.PFIPAI AS PAI,
    PESFISICA.PFIMAE AS MAE,
    PESSOA.PESDTCAD AS CADASTRO,
    PESSOA.PESTIPO
FROM PESSOA 
LEFT JOIN CIDADE ON CIDADE.cidcodigo = PESSOA.CIDCODIGO
LEFT JOIN pesfisica ON PESFISICA.pfispcodigo = PESSOA.PESCODIGO
LEFT JOIN pesjuridica ON PESJURIDICA.pescodigo = PESSOA.PESCODIGO
WHERE PESSOA.PESTIPO = '2' --CLIENTES
