SELECT
    PRODUTO.PROCODIGO AS CODIGO,
    PRODUTO.PRONOME AS DESCRICAO,
    UNIDADE.uninome AS UND,
    GRUSUB.GSUNOME AS FAMILIA,
    GRUPO.GRUNOME AS GRUPO, 
    PRODUTO.PROPESLIQ AS PESO,
    PRODUTO.PROQTDMIN AS QTD_IDEAL,
    PRODUTO.PROESTOQUE AS QTD,
    SUBSTRING (PRODUTO.STRCODIGO FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.STRCODIGO FROM 2 FOR 3) AS ST,
    PRODUTO.PROVLRCUSTO AS PRECO_CUSTO,
    PROPRECO.PPRVALOR AS PRECO_VENDA,
    PROPRECO.PPRMARGEM AS MARGEM_LUCRO,
    PRODUTO.PROOBS AS OBSERVACOES,
    PRODUTO.PROREFFABR AS COD_FABRICANTE,
    PRODUTO.PROCODNCM AS COD_NCM, 
    PRODUTO.PROCEST AS PERSONAL6,
    PROPRECO.PPRDTAALT AS ALTERACAO_PRECO,
    PRODUTO.PRODTCAD AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.GRUCODIGO = PRODUTO.GRUCODIGO
LEFT JOIN GRUSUB ON GRUSUB.GRUCODIGO = PRODUTO.GSUCODIGO
LEFT JOIN UNIDADE ON UNIDADE.unicodigo = PRODUTO.UNICODIGO
LEFT JOIN PROPRECO ON PROPRECO.procodigo = PRODUTO.PROCODIGO
