SELECT
  PRODUTO.CODI AS CODIGO,
  PRODUTO.CODALT AS BARRAS,
  PRODUTO.REFERENCIA AS COD_FABRICANTE,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.UN AS UND,
  ESTOQUE.QNTPRD AS QTD,
  GRUPO.DESCRICAO AS GRUPO,
  PRODUTO.NCMSH AS COD_NCM,
  PRODUTO.CSOSN AS ST
FROM PRODUTO
LEFT JOIN ESTOQUE ON PRODUTO.CODI = ESTOQUE.ID_PRODUTO
LEFT JOIN GRUPO ON PRODUTO.GRUPO = GRUPO.CODI