SELECT
    PRODUTOS.ID_PRODUTO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.COD_BARRA AS BARRAS,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.GRUPO AS GRUPO,
    PRODUTOS.EST_MINIMO AS QTD_IDEAL,
    ESTOQUE.ESTOQUE AS QTD,
    FORNECEDOR.RAZAO_SOC AS FORNECEDOR,
    PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.PRECO AS PRECO_VENDA,
    SUBSTRING (PRODUTOS.CST FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.CST FROM 2 FOR 3) AS ST,
    PRODUTOS.CFOP AS CF,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.ULTIMO_REAJUSTE AS ALTERACAO_PRECO,
    PRODUTOS.DATA AS DATA_CADASTRO,
    PRODUTOS.ULTIMA_VENDA AS ULTIMA_VENDA
FROM PRODUTOS
LEFT JOIN FORNECEDOR ON FORNECEDOR.ID_FORNECEDOR = PRODUTOS.ID_FORNECEDOR
LEFT JOIN ESTOQUE ON ESTOQUE.COD_PRODUTO = PRODUTOS.CODIGO