SELECT
    SRQFOR.COD_FOR AS CODIGO,
    SRQFOR.NOME_FOR AS NOME,
    SRQFOR.FANTAS_FOR AS FANTASIA,
    case when SRQFOR.CPF_FOR = '' or SRQFOR.CPF_FOR is null then SRQFOR.CGC_FOR else SRQFOR.CPF_FOR END AS CNPJ_CNPF,
    SRQFOR.INSCRI_FOR AS IE_RG,
    SRQFOR.INSCRI_MUNICIPAL AS IM,
    SRQFOR.ENDERE_FOR AS ENDERECO,
    SRQFOR.NRO_ENDERECO_FOR AS NUMERO,
    SRQFOR.COMPLEMENTO_ENDER_FOR AS COMPLEMENTO,
    SRQFOR.BAIRRO_FOR AS BAIRRO,
    SRQFOR.CEP_FOR AS CEP,
    SRQFOR.CIDADE_FOR AS CIDADE,
    SRQFOR.UF_FOR AS UF,
    SRQFOR.FONE1_FOR AS TELEFONE,
    SRQFOR.FONE2_FOR AS CELULAR,
    SRQFOR.FAX_FOR AS FAX,
    SRQFOR.EMAIL_FOR AS EMAIL
FROM SRQFOR
