SELECT
    SRQPRO.ID_PRO AS CODIGO,
    SRQPRO.DESC_PRO AS DESCRICAO,
    SRQPRO.UNID_PRO AS UND,
    SRQPRO.PESO_PRO AS PESO,
    SRQPRO.OBS AS OBSERVACOES,
    SRQPRO.CLAFIS_PRO AS COD_NCM,
    SRQPRO.CEST_PRO AS PERSONAL6,
    SRQPRO.CBENEF,
    SRQPRO.IPPT,
    SRQPRO.SIT_PRO AS PERSONAL1,
    SRQPRO.ID_ALIQUOTA AS PERSONAL2, 
    SRQPRO.ALICOT_PRO, 
    SRQPRO.PESO_PRO AS PESO,    
    SRQPRO.CST_IPI_ENTRADA AS IPI_CODIGO,
    SRQPRO.CST_PIS_ENTRADA AS PISE_CODIGO,
    SRQPRO.CST_COFINS_ENTRADA AS COFINSE_CODIGO,
    SRQPRO.CST_IPI_PRO AS IPI_CODIGO_VENDA,     
    SRQPRO.CST_PIS_PRO AS PIS_CODIGO,  
    SRQPRO.CST_COFINS_PRO AS COFINS_CODIGO,
    SRQPRO.ALIQ_IPI_ENTRADA AS ALIQ_IPI,
	SRQPRO.ALIQ_PIS_ENTRADA AS PISE_ALIQ_NOR,
	SRQPRO.ALIQ_COFINS_ENTRADA AS COFINSE_ALIQ_NOR,    
    SRQPRO.ALQIPI_PRO AS ALIQ_IPI_VENDA,  
    SRQPRO.ALIQPIS_PRO AS PIS_ALIQ_NOR,
    SRQPRO.ALIQCOFINS_PRO AS COFINS_ALIQ_NOR,  
    TBLESTOQUE.ESTOQUE AS QTD,    
    TBLESTOQUE.ORIGEM AS OST,
    COALESCE(CAST (TBLESTOQUE.DATA_ESTOQUE AS DATE), CURRENT_DATE) AS DATA_CADASTRO,
    CAST (TBLDADOSPRO.DT_ULTCOMPRA AS DATE) AS ULTIMA_COMPRA,
    TBLDADOSPRO.CUSTO AS PRECO_CUSTO,
    TBLDADOSPRO.MARGEM AS MARGEM_LUCRO,
    TBLDADOSPRO.PRECO AS PRECO_VENDA,  
    TBLDADOSPRO.EST_MIN AS QTD_IDEAL,
    TBLDADOSPRO.COMISSAO,
    CASE TBLDADOSPRO.STATUS_ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,   
    TBLCODIGOPRO.COD_PRO AS BARRAS,
    TBLFORNECPRO.COD_FABRICANTE AS COD_FABRICANTE,  
    SUBSTRING (ALIQUOTAS.SIT_TRIBUTARIA_NOTA FROM 2 FOR 4) AS ST,
	LEFT (NAT_OP.NAT_COD,3) AS ELO
    FROM SRQPRO
LEFT JOIN TBLCODIGOPRO ON TBLCODIGOPRO.FK_ID_PRO = SRQPRO.ID_PRO
LEFT JOIN TBLDADOSPRO ON TBLDADOSPRO.FK_ID_PRO = SRQPRO.ID_PRO
LEFT JOIN TBLESTOQUE ON TBLESTOQUE.FK_ID_DADOSPRO = SRQPRO.ID_PRO 
LEFT JOIN TBLFORNECPRO ON TBLFORNECPRO.FK_ID_PRO = SRQPRO.ID_PRO
LEFT JOIN ALIQUOTAS ON ALIQUOTAS.ID_ALIQUOTAS = SRQPRO.ID_ALIQUOTA 
LEFT JOIN NAT_OP ON NAT_OP.COD_NAT = ALIQUOTAS.FK_COD_NAT_NAT_OP 
