SELECT
    NOME AS NOME,
    NOME_FANT AS FANTASIA,
    NOMERUA AS ENDERECO,
    NUMRUA AS NUMERO,
    BAIRRO,
    CIDADE,
    ID_UF AS UF,
    CEP,
    CEL AS CELULAR,
    CONTATO,
    CPFCGC AS CNPJ_CNPF,
    RGIE AS IE_RG,
    EMAIL,
    FONE_COM1 AS TELEFONE,
    FAX,
    CELULAR,
    COMPLEMENTO,
    DATA_INC AS CADASTRO
FROM CLIFOR
WHERE CF = 'C'
