SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.NOME AS DESCRICAO,
    PRODUTOS.NOMECURTO AS CARACTERISTICAS,
    PRODUTOS.CODBARRA AS BARRAS,
    PRODUTOS.UNID AS UND,
    PRODUTOS.ESTMINIMO AS QTD_IDEAL,
    SALDOS.SALDO AS QTD,
    PRODUTOS.CODFABRI AS COD_FABRICANTE,
    FORNECEDORES.RAZAOSOCIAL AS FORNECEDOR,
    GRUPOS.NOME AS GRUPO,
    PRODUTOS.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTOS.PCOCUSTO AS PRECO_CUSTO,
    PRODUTOS.PCOSUGERIDO AS PRECO_ATACADO,
    PRODUTOS.PCOVENDA AS PRECO_VENDA,
    PRODUTOS.PESOL AS PESO,
    PRODUTOS.SITB AS ST,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.COD_NCM AS COD_NCM,
    PRODUTOS.COD_ANP AS COD_ANP,
    PRODUTOS.ULTENTRADA AS ULTIMA_COMPRA,
    PRODUTOS.ULTSAIDA AS ULTIMA_VENDA,
    PRODUTOS.DATA_ATU AS ALTERACAO_PRECO,
    PRODUTOS.DATA_CAD AS DATA_CADASTRO,  
    PRODUTOS.HISTORICO AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN SALDOS ON SALDOS.CODPRO = PRODUTOS.CODIGO
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = PRODUTOS.CODFORNE
LEFT JOIN GRUPOS ON GRUPOS.CODIGO = PRODUTOS.CODGRU