SELECT PRODUTOS.ID_PRODUTO AS CODIGO,
PRODUTOS.GRUPO,
PRODUTOS.REFERENCIA AS COD_FABRICANTE,
PRODUTOS.DESCRICAO,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.PRECO AS PRECO_VENDA,
FORNECEDOR.RAZAO_SOC AS FORNECEDOR,
PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
PRODUTOS.CUSTO_MEDIO,
PRODUTOS.CST AS ST,
PRODUTOS.QUANTIDADE AS QTD,
PRODUTOS.NCM AS COD_NCM,
PRODUTOS.UND_COMPRA,
PRODUTOS.DATA_CADASTRO,
PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDOR ON PRODUTOS.ID_FORNECEDOR=FORNECEDOR.ID_FORNECEDOR

