SELECT 
  P.CODIGO
, P.DESCRICAO
, P.PRECOCUSTO AS PRECO_CUSTO
, P.PRECOVISTA AS PRECO_VENDA
, P.ULTIMACOMPRA AS ULTIMA_COMPRA
, P.ULTIMAVENDA AS ULTIMA_VENDA
, P.ETIQUETA_1 AS OBSERVACOES
, P.ETIQUETA_2 AS CARACTERISTICAS
--, P.PRECOPRAZO
, P.SALDO AS QTD
--, S.SALDO AS QTD
, G.DESCRICAO AS GRUPO
FROM PRODUTOS P
LEFT JOIN GRUPOS G ON G.CODIGO = P.GRUPO
--LEFT JOIN SALDOSPRODUTOS s ON s.PRODUTO = p.CODIGO AND s.EMPRESA = '1'  --AJUSTAR AQUI CODIGO DA EMPRESA