SELECT TBL_PRODUTOS.CodProd AS CODIGO,
TBL_PRODUTOS.DescProd AS DESCRICAO,
TBL_PRODUTOS.CODBARRA AS COD_FABRICANTE,
TBL_PRODUTOS.CodTipoUnidade AS UND,
TBL_GRUPOS.DESCGRUPO AS GRUPO,
TBL_PRODUTOS.CodProdNcm AS COD_NCM,
TBL_PRODUTOS_EMPRESA.ESTOQUE AS QTD,
TBL_PRODUTOS_EMPRESA.PRCUSTO AS PRECO_CUSTO,
TBL_PRODUTOS_EMPRESA.PRMEDIO AS CUSTO_MEDIO,
TBL_PRODUTOS_EMPRESA.PRUNIT AS PRECO_VENDA,
TBL_PRODUTOS_EMPRESA.CodCest AS PERSONAL6
FROM TBL_PRODUTOS 
LEFT JOIN TBL_GRUPOS ON TBL_PRODUTOS.CodGrupo=TBL_GRUPOS.CodGrupo
LEFT JOIN TBL_PRODUTOS_EMPRESA ON TBL_PRODUTOS.CodProd=TBL_PRODUTOS_EMPRESA.CodProd AND TBL_PRODUTOS_EMPRESA.CodEmpresa=1
