SELECT
  ESTOQUE.PROCOD AS BARRAS,
  ESTOQUE.PRODES AS DESCRICAO,
  ESTOQUE.PROUNI AS UND,
  ESTOQUE.PROBS AS OBSERVACOES,
  ESTOQUE.PROCEST AS PERSONAL6,
  PRODUTOS.PL_PROCOD AS COD_FABRICANTE,
  PRODUTOS.PROPDV AS PRECO_VENDA,
  PRODUTOS.COMISSAO AS COMISSAO,
  PRODUTOS.PROCUS AS PRECO_CUSTO,
  ESTOQUE.PROCLF AS COD_NCM,
  PRODUTOS.PROCSOSN AS ST,
  QTD_PRODUTOS.QTDE AS QTD
FROM ESTOQUE
LEFT JOIN PRODUTOS ON PRODUTOS.PL_PROCOD = ESTOQUE.PROCOD
LEFT JOIN QTD_PRODUTOS ON QTD_PRODUTOS.PROD = ESTOQUE.PROCOD
