SELECT
  ITEMESTOQ.UND AS UND,
  ITEMESTOQ.CODIGO AS BARRAS,
  replace(ITEMESTOQ.CODIGOANTERIOR,' ','') AS CODIGO,
  ITEMESTOQ.CODIGOANTERIOR AS COD_FABRICANTE,
  --ITEMESTOQ.DESCRICAOABREV AS CARACTERISTICAS,
  ITEMESTOQ.DESCRICAO AS DESCRICAO,
  ESTOQUE.QUANTIDADE AS QTD,
  ESTOQUE.ESTOQUEMIN AS QTD_IDEAL,
  ESTOQUE.CUSTOMEDIO AS CUSTO_MEDIO,
  ITEMESTOQ.DTINCLUSAO AS DATA_CADASTRO,
  ITEMESTOQ.PRECOCUSTO AS PRECO_CUSTO,
  ITEMESTOQ.PESO AS PESO,
  ITEMESTOQ.CST AS ST,
  ITEMESTOQ.NCM AS COD_NCM,
  ITEMESTOQ.PRECOVENDA AS PRECO_VENDA,
  ITEMESTOQ.DT_ULT_COMPRA AS ULTIMA_COMPRA,
  ITEMESTOQ.DT_ULT_VENDA AS ULTIMA_VENDA
FROM ITEMESTOQ
LEFT JOIN ESTOQUE ON ESTOQUE.IDITEM = ITEMESTOQ.ID
