SELECT
    P.PROCOD AS CODIGO,
    P.GTIN AS BARRAS,
    P.PRODES AS DESCRICAO,
    P.PROUNID AS UND,
    GP.GRPDES AS GRUPO,
    E.ESTATU AS QTD,
    P.PROESTMIN AS QTD_IDEAL,
    F.FORDES AS FORNECEDOR,
    P.PROPRCCST AS PRECO_CUSTO,
    P.PROMRGLUC AS MARGEM_LUCRO,
    P.PROPRCVDA AS PRECO_VENDA,
    T.TRBTABB AS ST,
    P.PRODATCAD AS DATA_CADASTRO,
    P.PRODATALT AS ALTERACAO_PRECO,
    P.NCM AS COD_NCM 
FROM PRODUTO AS P
LEFT JOIN GRUPO GP ON P.GRPCOD = GP.GRPCOD
LEFT JOIN FORNECEDOR F ON P.FORCOD = F.FORCOD
LEFT JOIN TRIBUTACAO T ON P.TRBID = T.TRBID
LEFT JOIN ESTOQUE E ON P.PROCOD = E.PROCOD