SELECT
    NOME,
    ENDERECO,
    BAIRRO,
    CIDADE,
    CEP,
    EMAIL,
    COALESCE(RG,'') || COALESCE(IE,'') AS IE_RG,
    UF,
    CPF||CNPJ AS CNPJ_CNPF,
    FONE1 AS TELEFONE,
    FAX,
    CONTATO,
    INSCRMUN AS IM,
    FANTASIA,
    CELULAR,
    COMPLEMENTO_ENDER AS COMPLEMENTO,
    NUMERO_RUA AS NUMERO
FROM CLIENTES
