SELECT
    CODIGO,
    NOME,
    ENDERECO,
    BAIRRO,
    CIDADE,
    CEP,
    UF,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    EMAIL,
    FONE1 AS TELEFONE,
    FAX,
    CONTATO,
    FANTASIA,
    CELULAR,
    COMPLEMENTO_ENDER AS COMPLEMENTO,
    NUMERO_RUA AS NUMERO
FROM FORNECEDORES
