SELECT
    FORNECEDORES.COD_FORN AS CODIGO,
    FORNECEDORES.NOME_FOR AS NOME,
    CIDADES.NOME_CID AS CIDADE,
    CIDADES.UF_CID AS UF,
    FORNECEDORES.ENDERECO,
    FORNECEDORES.NUMERO,
    FORNECEDORES.COMPLEMENTO,
    FORNECEDORES.BAIRRO,
    FORNECEDORES.CEP,
    FORNECEDORES.FONE1 AS TELEFONE,
    FORNECEDORES.FAX,
    FORNECEDORES.CELULAR,
    FORNECEDORES.CONTATO,
    FORNECEDORES.CGCCPF AS CNPJ_CNPF,
    FORNECEDORES.EMAIL,
    FORNECEDORES.IE AS IE_RG,
    FORNECEDORES.FANTASIA
FROM FORNECEDORES
LEFT JOIN CIDADES ON FORNECEDORES.COD_CID = CIDADES.COD_CID
