SELECT
    PRODFILHO.CODPRODFILHO AS CODIGO,
    PRODUTO.CODPRODUTO AS COD_FABRICANTE,
    PRODUTO.DESCRICAO,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODFILHO.PRECOPRATICADO1 AS PRECO_VENDA,
    PRODFILHO.DTULTMAVENDA AS ULTIMA_VENDA,
    PRODFILHO.DTULTMACOMPRA AS ULTIMA_COMPRA,
    UNIDADE.SIGLA AS UND,
    PRODFILHO.ESTQATUAL AS QTD,
    PRODFILHO.CUSTO0 AS PRECO_CUSTO,
    PRODFILHO.CSTPIS AS PIS_CODIGO,
    PRODFILHO.CSTCOFINS AS COFINS_CODIGO,
    PRODFILHO.CLASSFISCAL AS COD_NCM,
    PRODFILHO.PRDF_CST_TRIBICMS AS ST
FROM PRODUTO
LEFT JOIN PRODFILHO ON PRODUTO.CODPRODUTO = PRODFILHO.CODPRODUTO
LEFT JOIN UNIDADE ON PRODFILHO.CODUNIDADE = UNIDADE.CODUNIDADE
LEFT JOIN SUBGRUPO ON PRODUTO.CODSUBGRUPO = SUBGRUPO.CODSUBGRUPO
LEFT JOIN GRUPO ON PRODUTO.CODGRUPO = GRUPO.CODGRUPO