SELECT
FORNECEDOR.FORCOD AS CODIGO,
FORNECEDOR.FORDES AS NOME,
FORNECEDOR.FOREND AS ENDERECO,
FORNECEDOR.FORBAI AS BAIRRO,
FORNECEDOR.FORCID AS CIDADE,
FORNECEDOR.FOREST AS UF,
FORNECEDOR.FORTEL AS TELEFONE,
FORNECEDOR.FORFAX AS FAX,
FORNECEDOR.FORCEP AS CEP,
FORNECEDOR.FORNUM AS NUMERO,
FORNECEDOR.FORCMP AS COMPLEMENTO,
FORNECEDOR.FOROBS AS OBSERVACOES,
FORNECEDOR.FORFAN AS FANTASIA,
FORNECEDOR.FORCGC AS CNPJ_CNPF,
FORNECEDOR.FORCGF AS IE_RG,
FORNECEDOR.FOREMAIL AS EMAIL
FROM FORNECEDOR
where forcod > 0
