select clientes.`CodCli` as codigo,
clientes.`NomCli` as nome,
clientes.`RazSoc` as fantasia,
clientes.`TelRes` as telefone,
clientes.`TelCel` as celular,
clientes.`TelFax` as fax,
-- clientes.`DataCadastro` as cadastro,
clientes.rua as endereco,
clientes.numero as numero,
clientes.`Comple` as complemento,
clientes.bairro as bairro,
clientes.`Cidade` as cidade,
clientes.cep as cep,
clientes.`Estado` as uf,
case when clientes.cpf is null or clientes.cpf='' then clientes.`Cnpj`
else clientes.cpf end as cnpj_cnpf,
clientes.`InscEst` as ie_rg,
clientes.`DtNascto` as nascimento,
clientes.`Observ` as observacoes,
clientes.`email`,
clientes.`NomePai` as pai,
clientes.`NomeMae` as mae,
clientes.contato
from clientes
