SELECT
    PESSOA.CODIGO AS CODIGO,
    PESSOA.NOME AS NOME,
    PESSOA.CNPJCPF AS CNPJ_CNPF,
    PESSOA.IE AS IE_RG,
    PESSOA.IM AS IM,
    PESSOA.ENDERECO AS ENDERECO,
    PESSOA.NUMERO AS NUMERO,
    PESSOA.COMPLEMENTO AS COMPLEMENTO,
    PESSOA.BAIRRO AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    PESSOA.CEP AS CEP,
    PESSOA.CONTATO AS CONTATO,
    PESSOA.DATAAPPEND AS CADASTRO
FROM PESSOA
LEFT JOIN CIDADE ON CIDADE.CODIGO = PESSOA.CIDADE
LEFT JOIN CLIENTE ON CLIENTE.PESSOA = PESSOA.CODIGO
WHERE CLIENTE.PESSOA = PESSOA.CODIGO
