SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.CODIGO AS COD_FABRICANTE,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTOEAN.CODIGOBARRA AS BARRAS,
    GRUPO.NOME AS GRUPO,
    PRODUTO.UNIDADE AS UND,
    SUBSTRING (PRODUTO.CSTICMS FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.CSTICMS FROM 2 FOR 3) AS ST,
    PRODUTO.POSICAO AS COD_NCM,
    PRODUTO.ESTOQUEATUAL AS QTD,
    PRODUTO.ESTOQUEIDEAL AS QTD_IDEAL,
    PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
    MAX (ESTOQUE.UNITARIO) AS PRECO_VENDA,
    PRODUTO.PESOLIQUIDO AS PESO,
    PRODUTO.DATAAPPEND AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN PRODUTOEAN ON PRODUTOEAN.PRODUTO = PRODUTO.CODIGO 
LEFT JOIN ESTOQUE ON ESTOQUE.PRODUTO = PRODUTO.CODIGO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,14,15
