SELECT 
  CODIGO
, CPF AS CNPJ_CNPF
, RG AS IE_RG
, NOME
, NOME_FANTASIA AS FANTASIA
, ENDERECO
, END_NUMERO AS NUMERO
, ENDER_COMPLEMENTO AS COMPLEMENTO
, BAIRRO
, CIDADE
, ESTADO AS UF
, CEP
, TELEFONE
, CONTATO
, DATANASC AS NASCIMENTO
, UCOMPRA AS ULTIMA_VENDA
, LIMITE AS LIMITE_CREDITO
, OBS AS OBSERVACOES
, EMAIL
, CASE SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, COALESCE(CADASTRO, CURRENT_DATE) AS CADASTRO
, MAE
, PAI
, LOCAL_TRAB AS LOCTRA
, REFERENCIAS AS PERSONAL1
, ENDERECOCOB AS COB_ENDERECO
, BAIRROCOB AS COB_BAIRRO
, CIDADECOB AS COB_CIDADE
, ESTADOCOB AS COB_UF
, CEPCOB AS COB_CEP
, CONJ_NOME AS CONJUGE
, SEXO
, ESTADO_CIVIL AS EST_CIVIL
FROM CLIENTE 
