SELECT 
  P.CODIGO 
, P.DESCRICAO
, P.UN AS UND
, P.CUSTO AS PRECO_CUSTO
, P.MARGEM AS MARGEM_LUCRO
, P.PRECO AS PRECO_VENDA
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.SALDOA AS QTD
, P.CBARRA AS BARRAS
--, P.SIT_TRIB AS ST
, P.CSOSN AS ST
, P.PESO
, P.IPI AS ALIQ_IPI
, P.COMISSAO
, P.LOCALIZACAO AS PERSONAL1
, P.FABR_CODIGO AS COD_FABRICANTE
--, P.FORN_CODIGO AS COD_FABRICANTE
--, P.COD_REFERENCIA AS COD_FABRICANTE
, COALESCE(P.DATA_CAD, CURRENT_DATE) AS DATA_CADASTRO
, P.NCM AS COD_NCM
, CASE P.INATIVO WHEN 'T' THEN 'Inativo' ELSE 'Ativo' END AS SITUACAO
, LEFT(P.CFOP,3) AS ELO
, P.CFOP AS CF
, P.PIS, P.COFINS, P.V_IPI, P.SIT_TRIB_IPI
, P.QTD_EMBAL AS FAT_CONV 
, P.CST_PIS AS PIS_CODIGO
, P.CST_COFINS AS COFINS_CODIGO
, P.ALIQ_PIS AS PIS_ALIQ_NOR
, P.ALIQ_COFINS AS COFINS_ALIQ_NOR
, P.CST_PIS_ENT AS PISE_CODIGO
, P.ALIQ_PIS_ENT AS PISE_ALIQ_NOR
, P.CST_COFINS_ENT AS COFINSE_CODIGO
, P.ALIQ_COFINS_ENT AS COFINSE_ALIQ_NOR
, P.ANP AS COD_ANP
, P.CEST AS PERSONAL6
, P.PRD_OBS AS OBSERVACOES
, G.DESCRICAO AS GRUPO
FROM PROD P
--LEFT JOIN TRIB T ON T.CODIGO = P.TRIB
LEFT JOIN GRUPO G ON G.CODIGO = P.GRUPO AND G.SEC_COD = 4
LEFT JOIN SUBGRU S ON S.SUBG_ID = P.SUBG_ID AND S.GRU_COD = G.CODIGO 
