SELECT CAST(CLIENTE.CODCLI AS INTEGER) AS CODIGO,
CLIENTE.NOMECLI AS NOME,
CLIENTE.ENDERECO,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.ESTADO AS UF,
CLIENTE.CEP,
CLIENTE.TELEFONE,
CLIENTE.FAX,
CASE WHEN CLIENTE.CNPJ IS NULL THEN CLIENTE.CPF
ELSE CLIENTE.CNPJ END AS CNPJ_CNPF,
CLIENTE.CONTATO,
CLIENTE.INSCR AS IE_RG,
CLIENTE.DATNASC AS NASCIMENTO,
CASE WHEN CLIENTE.DATCAD IS NULL THEN CURRENT_DATE
ELSE CLIENTE.DATCAD END AS CADASTRO,
CLIENTE.EMAIL,
CLIENTE.OBS AS OBSERVACOES,
CLIENTE.CONJFANTASIA AS FANTASIA
FROM CLIENTE

