SELECT 
  SUBSTRING (CODIGO FROM 3 FOR 6) AS CODIGO
, RAZ_SOC AS NOME
, NOM_FANT AS FANTASIA
, CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
, CASE WHEN IDENT = '' OR IDENT IS NULL THEN INC_EST ELSE IDENT END AS IE_RG
, ENDERECO
, NUMERO
, ENDERECO_COMPL ||' - '||PONTO_REF AS COMPLEMENTO
, BAIRRO
, NOM_CIDADE AS CIDADE
, ESTADO AS UF
, CEP
, TELEFONE
, CELULAR
, FAX
, EMAIL
, CONTATO
, OBS_CLI AS OBSERVACOES
FROM CAD01
WHERE TIPO='F'
