SELECT CLIFOR.ID_GTOT AS CODIGO,
CLIFOR.RAZAOSOCIAL AS NOME,
CLIFOR.NOMEFANTASIA AS FANTASIA,
CLIFOR.CGC_CPF AS CNPJ_CNPF,
CLIFOR.INSCRICAO_CI AS IE_RG,
CLIFOR_ENDERECO.ENDERECO,
MAX(CLIFOR_ENDERECO.CEP) AS CEP,
CLIFOR_ENDERECO.OBS AS COMPLEMENTO,
CLIFOR_ENDERECO.ENDERECO_NRO AS NUMERO,
CLIFOR_ENDERECO.BAIRRO,
CIDADE.NOMECIDADE as cidade,
CIDADE.ESTADO as uf,
MAX(CLIFOR_FONE.DDD||CLIFOR_FONE.NUMEROFONE) AS TELEFONE
FROM CLIFOR
LEFT JOIN CLIFOR_ENDERECO ON CLIFOR.ID_GTOT=CLIFOR_ENDERECO.ID_GTOT
LEFT JOIN CIDADE ON CLIFOR_ENDERECO.CODCIDADE=CIDADE.ID_CODIGOCIDADE
LEFT JOIN CLIFOR_FONE ON CLIFOR.ID_GTOT=CLIFOR_FONE.ID_GTOT
WHERE CLIFOR.ID_GTOT>0
GROUP BY 1,2,3,4,5,6,8,9,10,11,12


