SELECT MERCADORIA.ID_GTOT AS CODIGO,
MERCADORIA.REFERENCIA AS COD_FABRICANTE,
MERCADORIA.DESCRICAO,
MERCADORIA.DESCRICAO AS OBSERVACOES,
MERCADORIA_GRUPO.DESCRICAO AS GRUPO,
MERCADORIA.CODIGODEBARRAS AS BARRAS,
MERCADORIA.MERC_UNIDADE_VENDA AS UND,
MERCADORIA.SITUACAOTRIBUTARIA_ORIGEM AS OST,
MERCADORIA_STTRIBUTACAO.MERCSTT_SIMBOLO AS ST,
MERCADORIA.MERC_CUSTO_PCONSUMIDOR AS PRECO_VENDA,
MERCADORIA.MERC_CUSTO_MEDIO AS CUSTO_MEDIO,
MERCADORIA.MERC_ULTIMA_VENDA AS ULTIMA_VENDA,
MERCADORIA.MERC_PAF_ESTOQUE AS QTD,
MERCADORIA.MERC_CEST AS PERSONAL6,
MERCADORIA_NCM.MNCM_CODIGO AS COD_NCM
FROM MERCADORIA
LEFT JOIN MERCADORIA_GRUPO ON MERCADORIA.GRUPO=MERCADORIA_GRUPO.ID_CODIGO
LEFT JOIN MERCADORIA_NCM ON MERCADORIA.MERC_ID_NCM=MERCADORIA_NCM.MNCM_ID_NCM
LEFT JOIN MERCADORIA_STTRIBUTACAO ON MERCADORIA.SITUACAOTRIBUTARIA_TRIBUT=MERCADORIA_STTRIBUTACAO.ID_CODIGO
WHERE MERCADORIA.ID_GTOT>0



