SELECT
	EP.IDPRODUTO AS CODIGO,
	EP.NOME AS DESCRICAO,
	EP.CODBARRAS AS BARRAS,
	EP.CODPESQUISA AS PERSONAL1,
	EP.CODFABRICANTE AS COD_FABRICANTE,
	EP.MODELO AS PERSONAL2,
	EP.MARCA AS FAMILIA,
	EP.TIPOITEM AS TIPO_ITEM,
	EP.UNIDADEE AS UND_COMPRA,
	EP.UNIDADES AS UND,
	EP.FATORE AS FAT_CONV,
	EP.APLICACOES AS CARACTERISTICAS,
	EP.VALIDADE AS VALIDADE_DIAS,
	EP.PESOBRUTO AS PESO,
	EP.CLASSFISCAL AS COD_NCM,
	EP.CODCEST AS PERSONAL6,
	EP.CODANP AS COD_ANP,
	EP.CODBENEF AS CBENEF,
	EP.OBSERVACOES,
	DATE (EP.DATAINC) AS DATA_CADASTRO,
	CASE EP.STATUS WHEN '0' THEN 'Ativo' WHEN '1' THEN 'Inativo' END AS SITUACAO,
	EE.ESTMINIMO AS QTD_IDEAL,
	EE.ESTATUAL AS QTD,
	PF.NOME	AS FORNECEDOR,
	PC.NOME AS PERSONAL4,
	PG.NOME AS GRUPO,
--	EFI.CSOSN AS ST,
	EFI.CST AS ST,
	EFI.ALIQICMS AS ELO,
	PRE.VALORVENDA AS PRECO_VENDA,
	EPP.VALORFINAL AS PRECO_CUSTO
FROM
	EST_PRO EP
LEFT JOIN EST_EST EE ON EE.IDPRODUTO = EP.IDPRODUTO AND EE.IDEMPRESA = '1'
LEFT JOIN EST_PRO_FAB PF ON PF.IDFABRICANTE = EP.IDFABRICANTE
LEFT JOIN EST_PRO_CAT PC ON PC.IDCATEGORIA = EP.IDCATEGORIA 
LEFT JOIN EST_PRO_GRU PG ON PG.IDGRUPO = EP.IDGRUPO 
LEFT JOIN EST_FIS_ICM EFI ON EFI.IDGRUPOICMS = EP.IDGRUPOICMSS 
LEFT JOIN EST_PRO_PRE_TAB PRE ON PRE.IDPRODUTO = EP.IDPRODUTO AND PRE.IDEMPRESA = '1' AND PRE.IDTABPRECO = '6'
LEFT JOIN EST_PRO_PRE EPP ON EPP.IDPRODUTO = EP.IDPRODUTO AND EPP.IDEMPRESA = '1'