SELECT
    PRODUTOS.ID AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.EAN13 AS BARRAS,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.PRECO_COMPRA AS PRECO_CUSTO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.CSOSN_INTERNO AS ST,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    PRODUTOS.COD_CEST AS PERSONAL6,
    PRODUTOS.UNIDADE AS UND
FROM PRODUTOS
LEFT JOIN GRUPO ON PRODUTOS.GRUPO = GRUPO.ID
LEFT JOIN SUBGRUPO ON PRODUTOS.SUBGRUPO = SUBGRUPO.ID
