SELECT 
  C.COD_CLIENTE AS CODIGO
, C.DT_CADASTRO AS CADASTRO
, C.SEXO
, C.NOME_CLIENTE AS FANTASIA
, C.RAZAO_SOCIAL AS NOME
, C.ENDERECO
, C.NUMERO
, C.COMPLEMENTO
, C.CEP
, C.TELEFONE_1 AS TELEFONE
, C.TELEFONE_2 AS CELULAR
, C.TELEFONE_3 AS FAX
-- , C.DOC_FEDERAL AS CNPJ_CNPF
, CASE WHEN C.CPF = '' OR C.CPF = '00000000000' OR C.CPF IS NULL THEN C.CNPJ ELSE C.CPF END AS CNPJ_CNPF
, CASE WHEN C.RG = '' OR C.RG IS NULL THEN C.IE ELSE C.RG END AS IE_RG
, C.CONTATO
, C.EMAIL
, C.DT_NASCIMENTO AS NASCIMENTO
, C.NOME_PAI AS PAI
, C.NOME_MAE AS MAE
, C.LOCAL_TRABALHO AS LOCTRA
, C.CARGO_TRABALHO AS PROFISSAO
, C.ESTADO_CIVIL AS EST_CIVIL
, C.NOME_CONJUGE AS CONJUGE
, C.LIMITE_CLIENTE AS LIMITE_CREDITO
, C.OBSERVACAO AS OBSERVACOES
, C.NF_INDIEDEST AS INDIEDEST
, C.DT_ULTIMA_VENDA AS ULTIMA_VENDA
, TC.NOME_CIDADE AS CIDADE
, TE.SIGLA_ESTADO AS UF
, TB.NOME_BAIRRO AS BAIRRO
FROM TAB_CLIENTE C
LEFT JOIN TAB_CIDADE TC ON TC.COD_CIDADE = C.COD_CIDADE  
LEFT JOIN TAB_ESTADO TE ON TE.COD_ESTADO = TC.COD_ESTADO 
LEFT JOIN TAB_BAIRRO TB ON TB.COD_BAIRRO = C.COD_BAIRRO 