SELECT 
  TF.COD_FORNECEDOR AS CODIGO
, TF.NOME_FORNECEDOR AS FANTASIA
, TF.RAZAO_SOCIAL AS NOME
, TF.ENDERECO
, TF.NUMERO
, TF.COMPLEMENTO
, TF.CEP
, TF.TELEFONE_1 AS TELEFONE
, TF.TELEFONE_2 AS CELULAR
, TF.FAX
, TF.TELEFONE_3 AS PERSONAL1
, TF.TELEFONE_4 AS PERSONAL2
, CASE WHEN TF.CPF = '' OR TF.CPF = '00000000000' OR TF.CPF IS NULL THEN TF.CNPJ ELSE TF.CPF END AS CNPJ_CNPF
, CASE WHEN TF.RG = '' OR TF.RG IS NULL THEN TF.IE ELSE TF.RG END AS IE_RG
, TF.CONTATO
, TF.EMAIL
, TC.NOME_CIDADE AS CIDADE
, TE.SIGLA_ESTADO AS UF
, TB.NOME_BAIRRO AS BAIRRO
FROM TAB_FORNECEDOR TF 
LEFT JOIN TAB_CIDADE TC ON TC.COD_CIDADE = TF.COD_CIDADE  
LEFT JOIN TAB_ESTADO TE ON TE.COD_ESTADO = TC.COD_ESTADO 
LEFT JOIN TAB_BAIRRO TB ON TB.COD_BAIRRO = TF.COD_BAIRRO 