SELECT
    PRODUTO.CODIGO_INTERNO AS CODIGO,
    PRODUTO.GTIN AS BARRAS,
    UNIDADE_PRODUTO.NOME AS UND,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO_GRUPO.DESCRICAO AS GRUPO,
    PRODUTO_SUB_GRUPO.descricao AS FAMILIA,
    PRODUTO.QTD_ESTOQUE AS QTD,
    PRODUTO.ESTOQUE_MIN AS QTD_IDEAL,
    PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO.PERCENTUAL_LUCRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_VENDA AS PRECO_VENDA,
    PRODUTO.CSOSN AS ST,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.DATA_ALTERACAO AS ALTERACAO_PRECO,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.id = PRODUTO.ID_GRUPO
LEFT JOIN PRODUTO_SUB_GRUPO ON PRODUTO_SUB_GRUPO.id = PRODUTO.ID_SUB_GRUPO
LEFT JOIN UNIDADE_PRODUTO ON UNIDADE_PRODUTO.id = PRODUTO.ID_UNIDADE_PRODUTO
