SELECT FORNECEDOR.FORNICOD AS CODIGO,
FORNECEDOR.FORNA60RAZAOSOC AS NOME,
FORNECEDOR.FORNA60NOMEFANT AS FANTASIA,
FORNECEDOR.FORNA60CONTATO AS CONTATO,
FORNECEDOR.FORNA14CGC AS CNPJ_CNPF,
FORNECEDOR.FORNA20IE AS IE_RG,
FORNECEDOR.FORNA60END AS ENDERECO,
FORNECEDOR.FORNA60BAI AS BAIRRO,
FORNECEDOR.FORNA60CID AS CIDADE,
FORNECEDOR.FORNA2UF AS UF,
FORNECEDOR.FORNA8CEP AS CEP,
FORNECEDOR.FORNA15FONE1 AS TELEFONE,
FORNECEDOR.FORNA15FAX AS FAX,
FORNECEDOR.FORNA5NROEND AS NUMERO
FROM FORNECEDOR

