SELECT
	CT.CODIGO,
	CT.NOME,
	CT.FANTASIA,	
	CT.DT_NASCIMENTO AS NASCIMENTO,
	CT.CPF_CNPJ AS CNPJ_CNPF,
	CASE WHEN CT.RG = '' OR CT.RG IS NULL THEN CT.RG_INSCESTADUAL ELSE CT.RG END AS IE_RG,
	CT.ESTADO_CIVIL AS EST_CIVIL,
	CT.SEXO,
	CT.ENDERECO,
	CT.NRO_ENDERECO AS NUMERO,	
	CT.COMPLEMENTO,
	CT.BAIRRO,
	CT.CEP,
	CT.EMAIL,
	CT.DATA_INC AS CADASTRO,
	CT.OBSERVACOES,
	CT.DT_ULT_VENDA AS ULTIMA_VENDA,
	CM.NOME AS CIDADE, 
	CM.UF,
	CTC.CARGO AS PROFISSAO,
	CTC.PAI,
	CTC.MAE,
	CTC.CONJUGE,
	CTC.LOCAL_TRABALHO AS LOCTRA, 
	CTC.LIMITE_CREDITO 
FROM
	CAD_TERCEIROS CT
LEFT JOIN CAD_MUNICIPIOS CM ON CM.CODIGO = CT.MUNICIPIO  
LEFT JOIN CAD_TERCEIROS_CLIENTES CTC ON CTC.CODIGO = CT.CODIGO -- MUDAR PARA RIGHT JOIN PARA PEGAR SÓ CLIENTES
