SELECT
	CADPRODUTO.PRO_CODIGO AS CODIGO,
	CADGRUPOPRODUTO.GRP_DESCRICAO AS GRUPO,
	CADPRODUTO.PRO_DESCRICAO AS DESCRICAO,
	CADPRODUTO.PRO_UNIDADE AS UND,
	CASE
		CADPRODUTO.PRO_ATIVO WHEN 'S' THEN 'Ativo'
		ELSE 'Inativo'
	END AS SITUACAO,
--  CADPRODUTO.PRO_DESCRESUMIDA AS CARACTERISTICA,
	CADPRODUTO.OCS_CODIGO AS OST,
	CADPRODUTO.CSO_CODIGO AS ST,
	CADPRODUTO.PIS_CST AS PIS_CODIGO, 
	CADPRODUTO.COF_CST AS COFINS_CODIGO, 
	CADPRODUTO.PRO_ALIPIS AS PIS_ALIQ_NOR, 
	CADPRODUTO.PRO_ALICOFINS AS COFINS_ALIQ_NOR,
--	CADPRODUTO.PRO_ESTOQUE AS QTD, 
	CADPRODUTO.PRO_DESCRICAODETALHADA AS OBSERVACOES,
	CADPRODUTO.LEG_CODIGOPRODPRINC AS COD_FABRICANTE,
	CADPRODUTO.PRO_CEST AS PERSONAL6,
	CADCLASSIFICACAO.CLA_DESCRICAO AS FAMILIA,
	RCADPRODUTO.PRO_CODBARRA AS BARRAS,
	RCADPRODUTO.PRO_CFOP AS CF, 
	LEFT (RCADPRODUTO.PRO_CFOP,3) AS ELO,
	RCADPRODUTO.PRO_NCM AS COD_NCM,
	CADPRODUTONIVEL.PNI_VALOR AS PRECO_VENDA
FROM
	CADPRODUTO
LEFT JOIN CADGRUPOPRODUTO ON CADGRUPOPRODUTO.GRP_CODIGO = CADPRODUTO.GRP_CODIGO
LEFT JOIN CADCLASSIFICACAO ON CADCLASSIFICACAO.CLA_CODIGO = CADPRODUTO.CLA_CODIGO 
LEFT JOIN RCADPRODUTO ON RCADPRODUTO.PRO_CODIGO = CADPRODUTO.PRO_CODIGO
LEFT JOIN CADPRODUTONIVEL ON CADPRODUTONIVEL.PRO_CODIGO = CADPRODUTO.PRO_CODIGO
