SELECT
    N2CODFOR AS CODIGO,
    C2RAZSOC AS NOME,
    C2ENDER AS ENDERECO,
    C2BAIRRO AS BBAIRRO,
    C2CIDADE AS CIDADE,
    C2UF AS UF,
    C2CEP AS CEP,
    C2FONE AS TELEFONE,
    C2FONE2 AS CELULAR,
    C2CONTATO AS CONTATO,
    C2CNPJ AS CNPJ_CNPF,
    C2EMAIL AS EMAIL,
    C2RG AS IE_RG
FROM FORNECEDOR 
