SELECT
    PRODUTOS.N3CODPRO AS CODIGO,
    PRODUTOS.C3DESCRI AS DESCRICAO,
    PRODUTOS.C3TIPEMB AS UND,
    FORNECEDOR.C2RAZSOC AS FORNECEDOR,
    PRODUTOS.C3CODFAB AS COD_FABRICANTE,
    GRUPO_PRODUTO.DESCRGRUPO AS GRUPO,
    PRODUTOS.N3ESTMIN AS QTD_IDEAL,
    SUM (ESTOQUE.ESTOQATUAL) AS QTD,
    PRODUTOS.C3CODBARRA AS BARRAS,
    PRODUTOS.N3PESO AS PESO,
    PRODUTOS.C3NCM AS COD_NCM,
    PRODUTOS.N3PERCLUC AS MARGEM_LUCRO,
    SUBSTRING (PRODUTOS.C3CODSITTRIB FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.C3CODSITTRIB FROM 2 FOR 3) AS ST,
    PRODUTOS.N3PRCUSTO AS PRECO_CUSTO,
    PRODUTOS.N3PRVENDA AS PRECO_VENDA,
    PRODUTOS.N3PRPROM AS PRECO_ATACADO,
    PRODUTOS.D3DTCADASTRO AS DATA_CADASTRO,
    PRODUTOS.D3DTULVENDA AS ULTIMA_VENDA,
    PRODUTOS.D3DTULALTER AS ALTERACAO_PRECO,
    PRODUTOS.C3COD_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPO_PRODUTO ON GRUPO_PRODUTO.CODGRUPO = PRODUTOS.N3GRUPO
LEFT JOIN FORNECEDOR ON FORNECEDOR.N2CODFOR = PRODUTOS.N3CODFOR
LEFT JOIN ESTOQUE ON ESTOQUE.CODPROD = PRODUTOS.N3CODPRO
GROUP BY 1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21
