SELECT
    ID AS CODIGO,
    NOME AS NOME,
    NOME_FANT AS FANTASIA,
    NOMERUA AS ENDERECO,
    NUMRUA AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ID_UF AS UF,
    CEP AS CEP,
    COALESCE (DDD,'') || COALESCE (TELEFONE, '') AS TELEFONE,
    COALESCE (DDD,'') || COALESCE (CEL, '') AS CELULAR,
    CONTATO AS CONTATO,
    CPFCGC AS CNPJ_CNPF,
    RGIE AS IE_RG,
    EMAIL AS EMAIL
FROM CLIENTE