SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    GRUPO.NOME AS GRUPO,
    FORNECE.NOME AS FORNECEDOR,
    PRODUTO.P_CUSTO AS PRECO_CUSTO,
    PRODUTO.P_VENDA AS PRECO_VENDA,
    PRODUTO.EST_DISP AS QTD,
    PRODUTO.COD_BARRA1 AS BARRAS,
    PRODUTO.COD_NCM AS COD_NCM
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.ID_GRUPO = GRUPO.ID
LEFT JOIN FORNECE ON PRODUTO.ID_FORNECE = FORNECE.ID