SELECT
    CODCLIFOR AS CODIGO,
    NOME_RAZAO AS NOME,
    NOME_FANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    CNPJ_CPF AS CNPJ_CNPF,
    RG_IE AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    CELULAR AS CELULAR,
    ENDEMAIL AS EMAIL
FROM CLIEFORNE
WHERE TIPO_CADASTRO = 'F'