SELECT
    PRODUTOS.PRODUTO AS CODIGO,
    PRODUTOS.CODBARRA AS BARRAS,
    PRODUTOS.NOMEPRODU AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.MARCA AS CARACTERISTICAS,
    GRUPOSTQ.DESCRICAO AS GRUPO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    CLIEFORNE.NOME_RAZAO AS FORNECEDOR,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    PRODUTOS.CODIGO_CST AS ST,
    PRODUTOS.QTD_ESTOQUE AS QTD,
    PRODUTOS.VLR_CUSTO AS PRECO_CUSTO,
    PRODUTOS.VLR_VENDA AS PRECO_VENDA,
    PRODUTOS.PESO_LIQUI AS PESO,
    PRODUTOS.DATA_INCLU AS DATA_CADASTRO,
    PRODUTOS.COD_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPOSTQ ON GRUPOSTQ.GRUPO = PRODUTOS.GRUPO
LEFT JOIN CLIEFORNE ON CLIEFORNE.CODCLIFOR = PRODUTOS.CODCLIFOR