SELECT
    TBFICHA.COD AS CODIGO,
    TBFICHA.DESCRI AS DESCRICAO,
    TBFICHA.P_CUSTO AS PRECO_CUSTO,
    TBFICHA.P_VENDA AS PRECO_VENDA,
    TBFICHA.OBS AS OBSERVACOES,
    TBFICHA.COD_BARRAS AS BARRAS,
    TBFICHA.ICMS_CST AS ST,
    TBFICHA.NCM AS COD_NCM,
    TBFICHA.UND AS UND,
    TBFICHA.CEST AS PERSONAL6
FROM TBFICHA
WHERE TBFICHA.DESCRI IS NOT NULL