SELECT
    CLIFOR.CODIGO AS CODIGO,
    CLIFOR.RAZAOSOCIAL AS NOME,
    CLIFOR.FANTASIA AS FANTASIA,
    CLIFOR.CNPJCPF AS CNPJ_CNPF,
    CLIFOR.IERG AS IE_RG,
    CLIFOR.ENDERECO AS ENDERECO,
    CLIFOR.NUMERO AS NUMERO,
    CLIFOR.BAIRRO AS BAIRRO,
    CLIFOR.COMPLEMENTO AS COMPLEMENTO,
    SUBSTRING(CIDADE.CIDADE FROM 1 FOR POSITION('(' IN CIDADE.CIDADE || '(') - 1) AS CIDADE,
    CIDADE.UF AS UF,
    replace(CLIFOR.CEP,'-','') AS CEP,
    replace (replace (replace(CLIFOR.TELEFONE,'(',''), ')',''), ' ','') AS TELEFONE,
    replace (replace (replace(CLIFOR.CELULAR,'(',''), ')',''), ' ','') AS CELULAR,
    CLIFOR.EMAIL AS EMAIL,
    case when CLIFOR.ATIVO = '1' then 'Ativo' else 'Inativo' end as SITUACAO
FROM CLIFOR
LEFT JOIN  CIDADE ON CIDADE.CHAVE = CLIFOR.CHAVECIDADE
WHERE CLIFOR.FORNECEDOR = 'S' 
