SELECT cliente_id AS CODIGO,
nome AS NOME,
fantasia AS FANTASIA,
endereco AS ENDERECO,
numero AS NUMERO,
complemento AS COMPLEMENTO,
bairro AS BAIRRO,
municipio AS CIDADE,
estado AS UF,
cep AS CEP,
ddd  || ' ' || telefone_1 AS TELEFONE,
ddd  || ' ' || fax AS FAX,
cnpj AS CNPJ_CNPF,
inscricao AS IE,
contato AS CONTATO,
dt_ficha AS CADASTRO,
email AS email,
nascimento AS NASCIMENTO
FROM CLIENTES
