SELECT
	CODIGO_FORNECEDOR AS CODIGO,
	DESCRICAO AS NOME,
	RAZAO_SOCIAL AS FANTASIA,
	ENDERECO AS ENDERECO,
	BAIRRO AS BAIRRO,
	CIDADE AS CIDADE,
	ESTADO AS UF,
	CEP AS CEP,
	CPF_CNPJ AS CNPJ_CNPF,
	INSCRICAO_ESTADUAL AS IE_RG,
	CONTATO AS CONTATO,
	TELEFONE AS TELEFONE,
	FAX AS FAX,
	CELULAR AS CELULAR,
	EMAIL AS EMIAL,
	NUMERO AS NUMERO
FROM FORNECEDORES