SELECT
    CADFOR.CODFOR AS CODIGO,
    CADFOR.NOMFOR AS NOME,
    CADFOR.ENDFOR AS ENDERECO,
    CADFOR.BAIFOR AS BAIRRO,
    CADFOR.CIDFOR AS CIDADE,
    CADFOR.ESTFOR AS UF,
    CADFOR.CEPFOR AS CEP,
    CADFOR.FONFOR AS TELEFONE,
    CADFOR.FAXFOR AS FAX,
    CADFOR.CELFOR AS CELULAR,
    CADFOR.CPFFOR AS CNPJ_CNPF,
    CADFOR.NSCFOR AS IE_RG,
    CADFOR.EMAFOR AS EMAIL,
    CADFOR.OBSFOR AS OBSERVACOES,
    CADFOR.CMPFOR AS COMPLEMENTO,
    CADFOR.NUMFOR AS NUMERO
FROM CADFOR