SELECT
    replace(PRODUTOS.CODIGO,' ',''),
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.COMPLEMENTO AS CARACTERISTICAS,
    PRODUTOS.NUMFABRICANTE AS COD_FABRICANTE,
    PRODUTOS.UNIMED AS UND,
    PRODUTOS.PESOLIQUIDO AS PESO,
    PRECOPR.PRECO2 AS PRECO_VENDA,
    PRODUTOS.CODTRIBUTACAO AS ST,
    replace (PRODUTOS.CLASFISCAL,'.','') AS COD_NCM,
    PRODUTOS.DATACADASTRO AS DATA_CADASTRO,
    PRODUTOS.ESTOQMINIMO AS QTD_IDEAL,
    PRODUTOS.CODBAR AS BARRAS,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN PRECOPR ON PRECOPR.CODPRODUTO = PRODUTOS.CODIGO
