SELECT
    CLIENTE.CLIENTE AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLIENTE.FANTASIA AS FANTASIA,
    CLIENTE.CONTATO AS CONTATO,
    CLIENTE.CNPJCPF AS CNPJ_CNPF,
    CLIENTE.IERG AS IE_RG,
    CLIENTE.IM AS IM,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,
    BAIRRO.NOME AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    CLIENTE.CEP AS CEP,
    CLIENTE.TELEFONE1 AS TELEFONE,
    CLIENTE.TELEFONE2 AS CELULAR,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.OBS AS OBSERVACOES,
    CLIENTE.CONJUGE AS CONJUGE,
    CLIENTE.PAI AS PAI,
    CLIENTE.MAE AS MAE,
    CLIENTE.CIVIL AS EST_CIVIL,
    CLIENTE.NASCIMENTO AS NASCIMENTO,
    CLIENTE.DATACAD AS CADASTRO
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.CIDADE = CLIENTE.CIDADE
LEFT JOIN BAIRRO ON BAIRRO.BAIRRO = CLIENTE.BAIRRO
