SELECT
    PRODUTO.PRODUTO AS CODIGO,
    PRODUTO.CODIGO AS COD_FABRICANTE,
    PRODUTO.CODIGOBARRA AS BARRAS,
    PRODUTO.VOLUME AS UND,
    PRODUTO_ESTOQUE.QUANTIDADE AS QTD,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.PESOLIQUIDO AS PESO,
    GRUPO.NOME AS GRUPO,
    PRODUTO.VL_VENDA AS PRECO_VENDA,
    PRODUTO.VL_CUSTO AS PRECO_CUSTO,
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.NCM AS COD_NCM,
    SUBSTRING (TRIBUTACAO.NOME FROM 12 FOR 1) AS ST,
    PRODUTO.DATACAD AS DATA_CADASTRO,
    CEST.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.GRUPO = PRODUTO.GRUPO
LEFT JOIN PRODUTO_ESTOQUE ON PRODUTO_ESTOQUE.PRODUTO = PRODUTO.PRODUTO 
LEFT JOIN PRODUTO_TRIBUTACAO ON PRODUTO_TRIBUTACAO.PRODUTO = PRODUTO.PRODUTO
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.TRIBUTACAO = PRODUTO_TRIBUTACAO.TRIBUTACAO
LEFT JOIN CEST ON CEST.ID = PRODUTO.CEST
