SELECT CADFORNEC.COD AS CODIGO,
CADFORNEC.NOME,
CADFORNEC.CID AS CIDADE,
CADFORNEC.FONE AS TELEFONE,
CADFORNEC.CGC_CPF AS CNPJ_CNPF,
CADFORNEC.INSC AS IE_RG,
CADFORNEC.EMAIL,
CADFORNEC.CONTATO,
CADFORNEC.UF
FROM CADFORNEC

