SELECT CADPROD.COD AS CODIGO,
CADPROD.DESCR AS DESCRICAO,
CADPROD.UND,
CASE WHEN CADPROD.TRIB=0 THEN '102'
     WHEN CADPROD.TRIB=2 THEN '500'
END AS ST,
CADPROD.CUSTO_F AS PRECO_CUSTO,
CADPROD.PR_UNIT AS PRECO_VENDA,
CADPROD.SALDO_F AS QTD,
CADSETOR.DESCR AS GRUPO,
CADPROD.CODBAR AS BARRAS,
CADPROD.LOG_A AS COD_NCM,
CADPROD.COD_REF AS COD_FABRICANTE
FROM CADPROD
LEFT JOIN CADSETOR ON CADPROD.SETOR=CADSETOR.COD


