SELECT
    CLIENTE.CLIENTE AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLI_COMP.RAZAO AS FANTASIA,
    CLIENTE.CPF AS CNPJ_CNPF,
    case when CLI_COMP.RG = '' or CLI_COMP.RG is null then CLI_COMP.IE else CLI_COMP.RG END AS IE_RG,
    CLIENTE.IM AS IM,
    CLI_COMP.CONTATO AS CONTATO,
    CLI_ENDE.ENDERECO AS ENDERECO,
    CLI_ENDE.NRO AS NUMERO,
    BAIRRO.NOME AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    CLI_ENDE.CEP AS CEP,
    CLI_ENDE.TELEFONE AS TELEFONE,
    CLI_COMP.EMAIL AS EMAIL,
    CLI_COMP.NASCIMENTO AS NASCIMENTO,
    CLI_COMP.CIVIL AS EST_CIVIL,
    CLI_COMP.CONJUGE AS CONJUGE,
    CLI_COMP.PAI AS PAI,
    CLI_COMP.MAE AS MAE,
    CLI_COMP.OBS AS OBSERVACOES,
    CLIENTE.DATSIS AS CADASTRO
FROM CLIENTE
LEFT JOIN CLI_COMP ON CLI_COMP.CLIENTE = CLIENTE.CLIENTE
LEFT JOIN CLI_ENDE ON CLI_ENDE.CLIENTE = CLIENTE.CLIENTE
LEFT JOIN BAIRRO ON BAIRRO.BAIRRO = CLI_ENDE.BAIRRO
LEFT JOIN CIDADE ON CIDADE.CIDADE = CLI_ENDE.CIDADE
