SELECT
    ID_FORNECEDOR AS CODIGO,
    FONECEDOR AS NOME,
    FANTASIA AS FANTASIA,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    TEL AS TELEFONE,
    FAX AS FAX,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    CEP AS CEP,
    EMAIL AS EMAIL
FROM FORNECEDORES
