SELECT
  TCLIENTES.CODIGO AS CODIGO,
  TCLIENTES.NOME AS NOME,
  TCLIENTES.ENDERECO AS ENDERECO,
  TCLIENTES.BAIRRO AS BAIRRO,
  TCIDADES.CIDADE AS CIDADE,
  TCIDADES.ESTADO AS UF,
  TCIDADES.CEP AS CEP,
  TCLIENTES.EMAIL AS EMAIL,
  TCLIENTES.CPFCNPJ AS CNPJ_CNPF,
  TCLIENTES.CIIE AS IE_RG,
  TCLIENTES.DATA AS CADASTRO,
  TCLIENTES.PROFISSAO AS PROFISSAO,
  TCLIENTES.ESTCIVIL AS EST_CIVIL,
  TCLIENTES.FONE AS TELEFONE,
  TCLIENTES.CELULAR AS CELULAR,
  TCLIENTES.CONJUGE AS CONJUGE,
  TCLIENTES.COMPLEMENTO AS COMPLEMENTO,
  TCLIENTES.LIMITE AS LIMITE_CREDITO
FROM TCLIENTES
LEFT JOIN TCIDADES ON TCIDADES.CODIGO = TCLIENTES.CIDADE
WHERE TCLIENTES.CODIGO > '0'
