SELECT
    CLIENTES.CODIGO AS CODIGO,
    CLIENTES.NOME AS NOME,
    CLIENTES.FANTASIA AS FANTASIA,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.BAIRRO AS BAIRRO,
    CLIENTES.CIDADE AS CIDADE,
    CLIENTES.UF AS UF,
    CLIENTES.CEP AS CEP,
    case when CLIENTES.CNPJ = '' or CLIENTES.CNPJ is null then CLIENTES.CPF else CLIENTES.CNPJ END as CNPJ_CNPF,
    case when CLIENTES.INSC = '' or CLIENTES.INSC is null then CLIENTES.CI else CLIENTES.INSC END as IE_RG,
    CLIENTES.FONE AS TELEFONE,
    CLIENTES.CONTATO AS CONTATO,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.DATA AS CADASTRO,
    CLIENTES.OBSERVACAO AS OBSERVACOES,
    CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.NUMERO AS NUMERO
FROM CLIENTES