SELECT 
ESTOQUE.CODIGO,
ESTOQUE.DESCRICAO,
GRUPOS.descrio AS GRUPO,
ESTOQUE.UNIDADE AS UND,
ESTOQUE.ESTOQUE AS QTD,
ESTOQUE.PRECOCUSTO AS PRECO_CUSTO,
ESTOQUE.VALOR AS PRECO_VENDA,
ESTOQUE.REFER AS BARRAS,
ESTOQUE.ALTERACAO AS ALTERACAO_PRECO,
ESTOQUE.NCM AS COD_NCM,
ESTOQUE.TRIBSIMPLES AS ST,
ESTOQUE.CEST AS PERSONAL6
FROM ESTOQUE
LEFT JOIN GRUPOS ON GRUPOS.codigo = ESTOQUE.grupo