SELECT
  --PRODUTO.PRO_CODIGO AS CODIGO,
  PRODUTO.PRO_CODIGO AS COD_FABRICANTE,
  --PRODUTO.PRO_CODFABRICANTE AS COD_FABRICANTE,
  PRODUTO.PRO_NOME AS DESCRICAO,
  PRODUTO.PRO_VALOR AS PRECO_VENDA,
  PRODUTO.PRO_UNIDADE AS UND,
  PRODUTO_QTD.PRO_QTD AS QTD,
  FORNECEDORES.FOR_NOME AS FORNECEDOR,
  PRODUTO.PRO_CUSTO AS PRECO_CUSTO,
  PRODUTO.PRO_OBS AS OBSERVACOES,
  PRODUTO.PRO_COM_LUCRO AS MARGEM_LUCRO,
  PRODUTO.PRO_CODBARRAS as BARRAS,
  PRODUTO.PRO_NCM AS COD_NCM,
  PRODUTO.PRO_CSOSN AS ST,
  PRODUTO.FLAG_DATAALT AS ALTERACAO_PRECO,
  PRODUTO.PRO_CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN FORNECEDORES ON FORNECEDORES.FOR_CODIGO = PRODUTO.FOR_CODIGO
LEFT JOIN PRODUTO_QTD ON PRODUTO_QTD.PRO_CODIGO = PRODUTO.PRO_CODIGO


