SELECT
    PRODUTOS.PRO_CODIGO AS COD_FABRICANTE,
    ESTOQUE.codigobarras AS BARRAS,
    PRODUTOS.PRO_CODIGO || ' - ' || PRODUTOS.PRO_DESCRICAO AS DESCRICAO,
    PRODUTOS.PRO_UNIDADE AS UND,
    ESTOQUE.estoque2r AS QTD,
    PRODUTOS.PRO_PESOLIQUIDO AS PESO,
    FORNECEDOR.for_razaosocial AS FORNECEDOR,
    GESTOQUE.gru_nomegrupoestoque AS GRUPO,
    SGESTOQUE.sgru_nomesgrupoestoque AS FAMILIA,
    PRODUTOS.PRO_VALORCUSTO1N AS PRECO_CUSTO,
    PRODUTOS.PRO_MARGEMLUCRO1V AS MARGEM_LUCRO,
    PRODUTOS.PRO_PRVENDAVISTA AS PRECO_VENDA,
    PRODUTOS.PRO_PRVENDAPROMO AS PRECO_ATACADO,
    PRODUTOS.PRO_ST_NF AS ST,
    PRODUTOS.PRO_CAMPOOBS AS OBSERVACOES,
    PRODUTOS.PRO_DATACADASTRO AS DATA_CADASTRO,
    PRODUTOS.PRO_ULTIMOREAJUSTE AS ALTERACAO_PRECO,
    ESTOQUE.dataultvenda AS ULTIMA_VENDA,
    PRODUTOS.PRO_COD_NBMSH AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN fornecedor ON FORNECEDOR.for_codigo = PRODUTOS.pro_codfornecedor
LEFT JOIN GESTOQUE ON GESTOQUE.gru_codigo = PRODUTOS.pro_codgrupo
LEFT JOIN SGESTOQUE ON SGESTOQUE.sgru_codigo = PRODUTOS.pro_codsubgrupo
LEFT JOIN ESTOQUE ON ESTOQUE.codigoproduto = PRODUTOS.pro_codigo
WHERE ESTOQUE.EMPRESA = '1'
