SELECT 
       EMPRESA.EMP_Id AS CODIGO
      ,ENDERECO.END_Logradouro AS ENDERECO
      ,ENDERECO.END_Numero AS NUMERO
      ,ENDERECO.END_Complemento AS COMPLEMENTO
      ,ENDERECO.END_CEP AS CEP
      ,CIDADE.CID_Nome AS CIDADE
      ,ESTADO.EST_Nome AS UF
      ,EMPRESA.EMP_NomeFantasia AS FANTASIA
      ,EMPRESA.EMP_RazaoSocial AS NOME
      ,EMPRESA.EMP_CNPJ AS CNPJ_CNPF
      ,EMPRESA.EMP_InscricaoEstadual AS IE_RG
      ,EMPRESA.EMP_InscricaoMunicipal AS IM
      ,EMPRESA.EMP_Telefone AS TELEFONE
      ,EMPRESA.EMP_Email AS EMAIL
      ,EMPRESA.EMP_Contato AS CONTATO
  FROM APPTA.dbo.EMPRESA
  LEFT JOIN APPTA.dbo.ENDERECO ON ENDERECO.END_Id = EMPRESA.EMP_END_IdEndereco
  LEFT JOIN APPTA.dbo.CIDADE ON CIDADE.CID_Codigo = ENDERECO.END_CID_IdCidade
  LEFT JOIN APPTA.dbo.ESTADO ON ESTADO.EST_Codigo = ENDERECO.END_EST_IdEstado
