SELECT
	P.ID AS CODIGO,
	P.EAN AS BARRAS,
--	P.GTIN AS BARRAS,
	P.DSCR AS DESCRICAO,
	P.FABPT AS IPPT,
	CASE P.STTS WHEN 'A' THEN 'Ativo' WHEN 'I' THEN 'Inativo' END AS SITUACAO,
	P.DTCA AS DATA_CADASTRO,
	SG.SBCT AS FAMILIA,
	G.CT AS GRUPO,
	M.MARCFB AS CARACTERISTICAS,
	N.CNCM AS COD_NCM,
	N.CCEST AS PERSONAL6,
	C.ORIG AS OST,
	C.CST AS ST,
	E.QP AS QTD,
	E.UNV AS UND,
	E.CV AS PRECO_CUSTO,
	E.VV AS PRECO_VENDA,
	E.LVP AS MARGEM_LUCRO
FROM
	PRO P
LEFT JOIN SBCTG SG ON SG.ID = P.IDSBC 
LEFT JOIN CTG G ON G.ID = SG.IDCTG  
LEFT JOIN MARCA M ON M.ID = P.IDMARC 
LEFT JOIN NCM N ON N.ID = P.IDNCM 
LEFT JOIN CLAFISC C ON C.ID = P.IDCLAF 
LEFT JOIN EST E ON E.IDPRO = P.ID 