SELECT
  PRODUTOS.ID AS CODIGO,
  PRODUTOS.CODIGO_BARRA AS BARRAS,
  PRODUTOS.DESCRICAO,
  CATEGORIA.DESCRICAO AS GRUPO,
  PRODUTOS.CUSTO_UNITARIO AS PRECO_CUSTO,
  PRODUTOS.ESTOQUE_ATUAL AS QTD,
  PRODUTOS.SITUACAO_TRIBUTARIA AS ST,
  PRODUTOS.UNIDADE_MEDIDA AS UND,
  PRODUTOS.CODIGO_ATALHO AS COD_FABRICANTE,
  PRODUTOS.codigo_ncm AS COD_NCM,
  PRODUTOS.codCEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN CATEGORIA ON PRODUTOS.CODIGO_CATEGORIA = CATEGORIA.ID