SELECT
    CLIE_DADOS.ID_CLIENTE AS CODIGO,
    CLIE_DADOS.TIPO_CLIE,
    CLIE_DADOS.TIPO_FORN,
    CLIE_DADOS.NOME_RAZAO AS NOME,
    CLIE_DADOS.FANTASIA AS FANTASIA,
    CLIE_DADOS.ENDERECO AS ENDERECO,
    CLIE_DADOS.NUMERO AS NUMERO,
    CLIE_DADOS.ENDCOMPLMTO AS COMPLEMENTO,
    CLIE_DADOS.BAIRRO AS BAIRRO,
    CLIE_DADOS.CIDADE AS CIDADE,
    CLIE_DADOS.UF AS UF,
    REPLACE (REPLACE (CLIE_DADOS.CEP, '-' , ''),'.','') AS CEP,
    CLIE_DADOS.CNPJ_CPF AS CNPJ_CNPF,
    CLIE_DADOS.IE_RG AS IE_RG,
    CLIE_DADOS.FONE1 AS TELEFONE,
    CLIE_DADOS.FONE2 AS CELULAR,
    CLIE_DADOS.FONE3 AS FAX,
    CLIE_DADOS.EMAIL AS EMAIL,
    CLIE_DADOS.CONTATO AS CONTATO,
    CLIE_DADOS.DATA_CADASTRO AS CADASTRO,
    CLIE_DADOS.DATA_NASCIMENTO AS NASCIMENTO,
    CLIE_DADOS.SEXO AS SEXO,
    CLIE_DADOS.OBS_MEMO AS OBSERVACOES,
    CLIE_DADOS.INSCR_MUNICIPAL AS IM
FROM CLIE_DADOS
WHERE CLIE_DADOS.TIPO_CLIE = 'S'
AND CLIE_DADOS.TIPO_FORN = 'N'
