SELECT
    CLIENTES.ID AS CODIGO,
    CLIENTES.NOME AS NOME,
    COALESCE (CLIENTES.CNPJ, '') || COALESCE (CLIENTES.CPF,'') AS CNPJ_CNPF,
    COALESCE (CLIENTES.INSCRICAO_ESTADUAL, '') || COALESCE(CLIENTES.RG_NUMERO, '') AS IE_RG,
    CLIENTES.RESIDENCIA_CLIENTE_CEP AS CEP,
    CLIENTES.RESIDENCIA_CLIENTE_ENDERECO AS ENDERECO,
    CLIENTES.RESIDENCIA_CLIENTE_NUMERO AS NUMERO,
    CLIENTES.RESIDENCIA_CLIENTE_COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.RESIDENCIA_CLIENTE_BAIRRO AS BAIRRO,
    CIDADES.NOME AS CIDADE,
    CIDADES.ESTADO AS UF,
    CLIENTES.TELEFONE1 AS TELEFONE,
    CLIENTES.CELULAR1 AS CELULAR,
    CLIENTES.DATA_CADASTRO AS CADASTRO,
    CLIENTES.EMAIL1 AS EMAIL,
    CLIENTES.OBS AS OBSERVACOES
FROM CLIENTES
LEFT JOIN CIDADES ON CLIENTES.RESIDENCIA_CLIENTE_ID_CIDADE = CIDADES.ID
