SELECT
    FORNECEDORES.ID AS CODIGO,
    FORNECEDORES.CNPJ AS CNPJ_CNPF,
    FORNECEDORES.INSCRICAO_ESTADUAL AS IE_RG,
    FORNECEDORES.RAZAO_SOCIAL AS NOME,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    CIDADES.NOME AS CIDADE,
    CIDADES.ESTADO AS UF,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.EMAIL AS EMAIL
FROM FORNECEDORES
LEFT JOIN CIDADES ON FORNECEDORES.ID_CIDADE = CIDADES.ID
