SELECT
    PESSOA.ID_PESSOA AS CODIGO,
    PESSOA.NOME AS NOME,
    PESSOA.CEP,
    PESSOA.LOGRADOURO AS ENDERECO,
    PESSOA.NUMERO,
    PESSOA.BAIRRO,
    PESSOA.TELEFONE1 AS TELEFONE,
    PESSOA.CPF_CNPJ AS CNPJ_CNPF,
    PESSOA.EMAIL,
    MUNICIPIO.NOME AS CIDADE,
    MUNICIPIO.UF AS UF,
    PESSOA.RG AS IE_RG,
    PESSOA.COMPLEMENTO,
    PESSOA.CELULAR1 AS CELULAR
FROM PESSOA
LEFT JOIN municipio ON PESSOA.id_municipio = MUNICIPIO.id_municipio
WHERE PESSOA.id_pessoa > 0
