SELECT
    FORNECEDOR.IDFORNECEDOR AS CODIGO,
    FORNECEDOR.RAZAOSOCIAL AS NOME,
    FORNECEDOR.NOMEFANTASIA AS FANTASIA,
    FORNECEDOR.INSCEST AS IE_RG,
    FORNECEDOR.CNPJ AS CNPJ_CNPF,
    ENDERECOSFORNECEDOR.RUA AS ENDERECO,
    ENDERECOSFORNECEDOR.NUMERO AS NUMERO,
    ENDERECOSFORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    ENDERECOSFORNECEDOR.BAIRRO AS BAIRRO,
    ENDERECOSFORNECEDOR.CEP AS CEP,
    MUNICIPIO.NOME AS CIDADE,
    MUNICIPIO.UF AS UF,
    FORNECEDOR.TELEFONE AS TELEFONE,
    FORNECEDOR.CELULAR AS CELULAR,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBSERVACOES AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN ENDERECOSFORNECEDOR ON ENDERECOSFORNECEDOR.IDFORNECEDOR = FORNECEDOR.IDFORNECEDOR
LEFT JOIN MUNICIPIO ON MUNICIPIO.CODCMUN = ENDERECOSFORNECEDOR.CODCMUN
