SELECT
    CLIENTE.CODIGO AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLIENTE.NOMEFANTASIA AS FANTASIA,
    CLIENTE.CONTATO AS CONTATO,
    CLIENTE.CPF AS CNPJ_CNPF,
    case when CLIENTE.RG = '' or CLIENTE.RG is null then CLIENTE.IE else CLIENTE.RG END AS IE_RG,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.BAIRRO AS BAIRRO,
    CLIENTE.CEP AS CEP,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    CLIENTE.TELEFONE AS TELEFONE,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.OBS AS OBSERVACOES,
    CLIENTE.CREDITO AS LIMITE_CREDITO,
    CLIENTE.NASC AS NASCIMENTO,
    CLIENTE.DATA_REG AS CADASTRO
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.CODIGO = CLIENTE.COD_CIDADE
