SELECT
    CODIGO AS CODIGO,
    NOME AS DESCRICAO,
    COD_BARRAS AS BARRAS,
    UNIDADE AS UND,
    SALDO AS QTD,
    FABRICANTE AS CARACTERISTICAS,
    VVENDA AS PRECO_VENDA,
    VCOMPRA AS PRECO_CUSTO,
    OBS AS OBSERVACOES,
    NCM AS COD_NCM,
    STICMS AS ST,
    DATA_REG AS DATA_CADASTRO
FROM PRODUTO
