SELECT
	C.CODIGO,
	C.CPFCNPJ AS CNPJ_CNPF,
	CASE
		WHEN C.RGPR = ''
		OR C.RGPR IS NULL THEN C.RGIE
		ELSE C.RGPR
	END AS IE_RG,
	C.INSCRICAOMUNICIPAL AS IM,	
	C.ORGAOEXPEDIDOR AS PERSONAL1,
	C.NOME,
	C.FANTASIA,
	C.ENDERECO,
	C.NUMEROENDERECO AS NUMERO,	
	C.COMPLEMENTO,
	C.BAIRRO,
	C.CEP,
	C.FONE AS TELEFONE,
	C.FAX,
	C.FONECELULAR AS CELULAR,	
	C.EMAIL,
	C.ENDERECOCOB AS COB_ENDERECO,
	C.NUMEROENDERECOCOB AS COB_NUMERO,	
	C.COMPLCOBRANCA AS COB_COMPLEMENTO,
	C.BAIRROCOB AS COB_BAIRRO,
	C.CEPCOB AS COB_CEP,
	C.DATACADASTRO AS CADASTRO,
	C.LIMITE AS LIMITE_CREDITO,
	C.CODIGOSUFRAMA AS SUFRAMA,
	C.OBS AS OBSERVACOES,
	T.DATAULTCOMPRA AS ULTIMA_VENDA,
	CASE
		T.ATIVO WHEN 'S' THEN 'Ativo'
		ELSE 'Inativo'
	END AS SITUACAO,
	CI.NOME AS CIDADE,
	CI.ESTADO AS UF,
	CIC.NOME AS COB_CIDADE,
	CIC.ESTADO AS COB_UF,
	PF.DATANASC AS NASCIMENTO,
	PF.SEXO,
	PF.ESTADOCIVIL AS EST_CIVIL,
	PF.NOMEMAE AS MAE,
	PF.NOMEPAI AS PAI, 
	PF.NOMECONJUGE AS CONJUGE,
	PF.LOCALTRABALHO AS LOCTRA,
	PF.CARGO AS PROFISSAO,
	PF.CONTATO
FROM
	TRECCLIENTEGERAL C
LEFT JOIN TRECCLIENTE T ON T.CODIGO = C.CODIGO  
LEFT JOIN TGERCIDADE CI ON CI.CODIGO = C.CIDADE 
LEFT JOIN TGERCIDADE CIC ON CIC.CODIGO = C.CIDADE 
LEFT JOIN TRECPFISICA PF ON PF.CODIGO = C.CODIGO  