SELECT
    FORNECEDOR.ID AS CODIGO,
    FORNECEDOR.RAZAO_SOCIAL AS NOME,
    FORNECEDOR.NOME_FANTASIA AS FANTASIA,
    FORNECEDOR.CNPJ AS CNPJ_CNPF,
    FORNECEDOR.INSC_EST AS IE_RG,
    FORNECEDOR.INSC_MUN AS IM,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.END_NUMERO AS NUMERO,
    FORNECEDOR.END_COMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    UF.UF AS UF,
    MUNICIPIOS.NOME_MUNICIPIO AS CIDADE,
    TELEFONES.NUMERO AS TELEFONE,
    FORNECEDOR.CONTATO AS CONTATO,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.ID = FORNECEDOR.ID_MUNICIPIO
LEFT JOIN UF ON UF.ID = FORNECEDOR.ID_UF
LEFT JOIN TELEFONES ON TELEFONES.ID = FORNECEDOR.ID
