SELECT
    ESTOQUE.NOME AS DESCRICAO,
    ESTOQUE.CODIGO AS BARRAS,
    ESTOQUE.UNIDADE AS UND,
    ESTOQUE.MINIMO AS QTD_IDEAL,
    ESTOQUE.FISICO AS QTD,
    GRUPO.NOME AS GRUPO,
    SUBGRUPO.NOME AS FAMILIA,
    ESTOQUE.PESO AS PESO,
    ESTOQUE.CUSTO AS PRECO_CUSTO,
    ESTOQUE.LUCRO AS MARGEM_LUCRO,
    ESTOQUE.VENDA AS PRECO_VENDA,
    ESTOQUE.ATACADO AS PRECO_ATACADO,
    TRIBUTACOES.TRB_CST AS ST,
    ESTOQUE.OBS AS OBSERVACOES,
    ESTOQUE.NCM AS COD_NCM,
    ESTOQUE.CEST AS PERSONAL6,
    ESTOQUE.REFERENCIA AS COD_FABRICANTE
FROM ESTOQUE
LEFT JOIN TRIBUTACOES ON TRIBUTACOES.TRB_ID = ESTOQUE.TRIBUTACAO
LEFT JOIN GRUPO ON GRUPO.CODIGO = ESTOQUE.CDGRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CODIGO = ESTOQUE.CDSUBGRUPO
