SELECT
    FORNECEDOR.FOR_ID AS CODIGO,
    FORNECEDOR.FOR_RAZAO_SOCIAL AS NOME,
    FORNECEDOR.FOR_NOME_FANTASIA AS FANTASIA,
    FORNECEDOR.FOR_CNPJ AS CNPJ_CNPF,
    FORNECEDOR.FOR_INSCRICAO_ESTADUAL AS IE_RG,
    FORNECEDOR.FOR_ENDERECO AS ENDERECO,
    FORNECEDOR.FOR_BAIRRO AS BAIRRO,
    CIDADE.CID_NOME AS CIDADE,
    CIDADE.UFA_ID AS UF,
    FORNECEDOR.FOR_CEP AS CEP,
    FORNECEDOR.FOR_FONE_COMERCIAL AS TELEFONE,
    FORNECEDOR.FOR_FAX AS FAX,
    FORNECEDOR.FOR_EMAIL AS EMAIL
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.CID_ID = FORNECEDOR.CID_ID
