SELECT
    PRODUTO.ID AS CODIGO,
    UNIDADE_PRODUTO.NOME AS UND,
    PRODUTO.GTIN AS BARRAS,
    PRODUTO.CODIGO_INTERNO,
    PRODUTO.NOME AS DESCRICAO,
    GRUPO_PRODUTO.nome AS GRUPO,
    SUBGRUPO_PRODUTO.nome as familia,
    PRODUTO.VALOR_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_VENDA AS PRECO_VENDA,
    PRODUTO.QTD_ESTOQUE AS QTD,
    PRODUTO.ESTOQUE_MIN AS QTD_IDEAL,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CST AS ST,
    PRODUTO.DATA_CADASTRO AS DATA_CADASTRO,
    PRODUTO.DATA_ULTIMA_ALTERACAO AS ULTIMA_ALTERACAO,
    PRODUTO.PESO_LIQUIDO AS PESO,
    PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN grupo_produto ON grupo_produto.id = PRODUTO.id_grupo_produto
LEFT JOIN subgrupo_produto ON subgrupo_produto.id = PRODUTO.id_subgrupo_produto
left join unidade_produto on unidade_produto.id = produto.id_unidade_produto
