SELECT
    FORNECEDORES.CODIGO AS CODIGO,
    FORNECEDORES.NOME AS NOME,
    FORNECEDORES.NOMEFAN AS FANTASIA,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.CPF AS CNPJ_CNPF,
    FORNECEDORES.RG AS IE_RG,
    FORNECEDORES.ENDER AS ENDERECO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.ESTADO AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.FONE1 AS TELEFONE,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.OBS AS OBSERVACOES
FROM FORNECEDORES