SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    FORNECEDOR.RAZAO AS NOME,
    FORNECEDOR.FANTAZIA AS FANTASIA,
    case when FORNECEDOR.CPF = '' or FORNECEDOR.CPF is null then FORNECEDOR.CNPJ else FORNECEDOR.CPF END AS CNPJ_CNPF,
    case when FORNECEDOR.RG = '' or FORNECEDOR.RG is null then FORNECEDOR.IE else FORNECEDOR.RG END AS IE_RG,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.NUMERO AS NUMERO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    CIDADES.NOME AS CIDADE,
    CIDADES.ESTADO AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.FONE AS TELEFONE,
    FORNECEDOR.CELULAR AS CELULAR,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN CIDADES ON CIDADES.CODIGO = FORNECEDOR.CIDADE