SELECT 
  CODIGO
, NOME
, FANTASIA
, ENDERECO
, COMPLEMENTO 
, NUMERO 
, BAIRRO
, CASE WHEN CPF = '' OR CPF IS NULL THEN CGC ELSE CPF END AS CNPJ_CNPF
, CASE WHEN RG = '' OR RG IS NULL THEN IE ELSE RG END AS IE_RG
, IM
, CIDADE
, UF
, CEP
, TELEFONE
, CELULAR
, FAX
, LIMITECREDITO AS LIMITE_CREDITO
, DATANASCTO AS NASCIMENTO
, COALESCE(DATACADASTRO, CURRENT_DATE) AS CADASTRO
, DATAULTCOMPRA AS ULTIMA_VENDA
, EMAIL
, ONDETRABALHA AS LOCTRA
, FUNCAO AS PROFISSAO
, ESTADOCIVIL AS EST_CIVIL
, CONJUGUE
, NOMEPAI AS PAI
, NOMEMAE AS MAE
, OBS AS OBSERVACOES
FROM CLIENTE
