SELECT 
  FORID AS CODIGO
, FORNOMERAZAO AS NOME
, FORNOMEFANTASIA AS FANTASIA
, FORENDERECO AS ENDERECO
, FORBAIRRO AS BAIRRO
, FORCEP AS CEP
, FORCIDADE AS CIDADE
, FORUF AS UF
, FORFONE01 AS TELEFONE
, FORFONE02 AS FAX
, FORCPFCNPJ AS CNPJ_CNPF
, FORCGF AS IE_RG
FROM FORNECEDORES