SELECT 
  P.PROID AS CODIGO
, P.PRONOME AS DESCRICAO
, P.PROVALORCUSTO AS PRECO_CUSTO
, P.PROVALORVENDA AS PRECO_VENDA
--, P.PROVALORVENDA2 
, P.PROLUCRATIVIDADE AS MARGEM_LUCRO
, P.PROQTDESTOQUE AS QTD -- ver em futuras conversões se quantidade não fica na tabela LOCAISESTOQUEPRODUTO
, P.PROQTDESTOQUEMINIMO AS QTD_IDEAL
, P.PROREFERENCIA AS COD_FABRICANTE
, CASE WHEN P.PRODESATIVADO = '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
--, PROQTDEMBALAGEM
, P.PROEMBALAGEMQTDENTRADA AS FAT_CONV
, P.PROCOMISSAO AS COMISSAO
, P.PRODATACADASTRO AS DATA_CADASTRO
, P.PRONCM AS COD_NCM
, P.PROOBS AS OBSERVACOES
, P.PROCUSTOMEDIO AS CUSTO_MEDIO
, P.PROIPI AS ALIQ_IPI
, P.PROCSTPIS AS PISE_CODIGO
, P.PROCSTCOFINS AS COFINSE_CODIGO
, P.PROPERCPIS AS PISE_ALIQ_NOR
, P.PROPERCCOFINS AS COFINSE_ALIQ_NOR
, P.PROCEST AS PERSONAL6
, P.PRODATAULTIMAVENDA AS ULTIMA_VENDA
, P.PROQTDDIASVALIDADE AS VALIDADE_DIAS
--, P.PROICMSDENTRO
--, P.SITID AS ELO
--, P.PROCLASSIFICACAOFISCAL AS ELO
, GS.GSUNOME AS GRUPO
, G.GRUDESCRICAO AS FAMILIA
, U.UNIDESCREDUZIDA AS UND
, F.FORNOMERAZAO AS FORNECEDOR
, F2.FABNOMERAZAO AS CARACTERISTICAS
, LEFT (FF.NATID,3) AS ELO
, FF.FIGCSTB AS ST
, FF.FIGCST_IPI AS IPI_CODIGO_VENDA
, FF.FIGCST_PIS AS PIS_CODIGO
, FF.FIGCST_COFINS AS COFINS_CODIGO
, FF.FIGPERC_IPI AS ALIQ_IPI_VENDA
, FF.FIGPERC_PIS AS PIS_ALIQ_NOR
, FF.FIGPERC_COFINS AS COFINS_ALIQ_NOR
, PB.PCBCODIGOBARRAS AS BARRAS
FROM PRODUTOS P
LEFT JOIN GRUPOS G ON G.GRUID = P.GRUID
LEFT JOIN GRUPOSUPERIOR GS ON GS.GSUID = G.GSUID 
LEFT JOIN UNIDADES U ON U.UNIID = P.PROUNIDADE
LEFT JOIN FORNECEDORES F ON F.FORID = P.FORID
LEFT JOIN FABRICANTES F2 ON F2.FABID = P.FABID 
LEFT JOIN CLASSIFICACAOFISCAL C ON C.CLAID = P.CLAID 
LEFT JOIN FIGURAFISCAL FF ON FF.CLAID = C.CLAID AND FF.NFCE = 1
LEFT JOIN PRODUTOSCODIGOBARRAS PB ON PB.PROID = P.PROID