SELECT 
       P.PK_GE_PESSOA_ID AS CODIGO
      ,P.GE_PESSOA_NOME AS NOME
      ,P.GE_PESSOA_SOBRENOME AS FANTASIA
      ,P.GE_PESSOA_CPF AS CNPJ_CNPF
      ,P.GE_PESSOA_RG AS IE_RG
      ,F.GE_FONE_CONTATO AS CONTATO
      ,E.GE_ENDERECO_LOGRADOURO AS ENDERECO
      ,E.GE_ENDERECO_NUMERO AS NUMERO
      ,E.GE_ENDERECO_COMPLEMENTO AS COMPLEMENTO
      ,E.GE_ENDERECO_BAIRRO AS BAIRRO
      ,CID.GE_CIDADE_NOME AS CIDADE
      ,EST.GE_ESTADO_UF AS UF
      ,C.GE_CEP_CEP AS CEP
      ,F.GE_FONE_NUMERO AS TELEFONE
      ,CAST (P.GE_PESSOA_DATANASCIMENTO AS DATE) AS NASCIMENTO
      ,CAST (P.GE_PESSOA_DATACADASTRO AS DATE) AS CADASTRO
  FROM OMLAS_23.dbo.TB_GE_PESSOA AS P
  LEFT JOIN OMLAS_23.dbo.TB_GE_PESSOAENDERECO PE ON P.PK_GE_PESSOA_ID = PE.PK_GE_PESSOAENDERECO_GE_PESSOA_ID
  LEFT JOIN OMLAS_23.dbo.TB_GE_ENDERECO E ON PE.GE_PESSOAENDERECO_GE_ENDERECO_ID = E.PK_GE_ENDERECO_ID
  LEFT JOIN OMLAS_23.dbo.TB_GE_CEP C ON E.FK_GE_ENDERECO_GE_CEP_ID = C.PK_GE_CEP_ID
  LEFT JOIN OMLAS_23.dbo.TB_GE_CIDADE CID ON C.FK_GE_CEP_GE_CIDADE_ID = CID.PK_GE_CIDADE_ID
  LEFT JOIN OMLAS_23.dbo.TB_GE_ESTADO EST ON CID.FK_GE_CIDADE_GE_ESTADO_ID = EST.PK_GE_ESTADO_ID 
  LEFT JOIN OMLAS_23.dbo.TB_GE_PESSOAFONE PF ON P.PK_GE_PESSOA_ID = PF.PK_GE_PESSOAFONE_GE_PESSOA_ID
  LEFT JOIN OMLAS_23.dbo.TB_GE_FONE F ON PF.PK_GE_PESSOAFONE_GE_FONE_ID = F.PK_GE_FONE_ID
