SELECT 
       --I.IT_ITEM_CODIGO AS CODIGO
        I.IT_ITEM_CODIGO AS COD_FABRICANTE
      ,I.IT_ITEM_NOME AS DESCRICAO
      ,IP.IT_PRODUTO_CEAN AS BARRAS
      ,UM.GE_UNIDADEMEDIDA_SIGLA AS UND
      ,P.IT_PRECOS_CUSTORS AS PRECO_CUSTO
      ,P.IT_PRECOS_LUCRATIVIDADEAJUSTADA AS MARGEM_LUCRO
      ,P.IT_PRECOS_VALOR AS PRECO_VENDA
      ,INC.IT_NCM_CODIGO AS COD_NCM
      ,INC.IT_NCM_CEST AS PERSONAL6
      ,case when I.IT_ITEM_ATIVO = '1' then 'Ativo' else 'Inativo' end as situacao
      ,CAST (I.IT_ITEM_DATACADASTRO AS DATE) AS DATA_CADASTRO
  FROM OMLAS_23.dbo.TB_IT_ITEM AS I
  LEFT JOIN OMLAS_23.dbo.TB_IT_PRECOS P ON I.PK_IT_ITEM_ID = P.FK_IT_PRECOS_IT_ITEM_ID
  LEFT JOIN OMLAS_23.dbo.TB_IT_PRODUTO IP ON I.PK_IT_ITEM_ID = IP.PK_IT_PRODUTO_ID 
  LEFT JOIN OMLAS_23.dbo.TB_IT_NCM INC ON IP.FK_IT_PRODUTO_IT_NCM_ID = INC.PK_IT_NCM_ID
  LEFT JOIN OMLAS_23.dbo.TB_GE_UNIDADEMEDIDA UM ON IP.FK_GE_UNIDADEMEDIDA_ID = UM.PK_GE_UNIDADEMEDIDA_ID
  WHERE P.FK_IT_PRECOS_IT_TABELAPRECOS_ID = '2' ---ID - 2 'A VISTA - 3 A PRAZO'
  ORDER BY I.IT_ITEM_NOME ASC
