SELECT
    TBCLIENT.CLICODIGO AS CODIGO,
    TBCLIENT.CLIFANTAS AS FANTASIA,
    TBCLIENT.CLIRAZSOC AS NOME,
    TBCIDADE.CIDCIDADE AS CIDADE,
    TBCIDADE.CIDESTADO AS UF,
    TBCLIENT.CLIENDERE AS ENDERECO,
    TBCLIENT.CLINUMERO AS NUMERO,
    TBCLIENT.CLIBAIRRO AS BAIRRO,
    TBCLIENT.CLICEP AS CEP,
    TBCLIENT.CLICOMPLE AS COMPLEMENTO,
    TBCLIENT.CLITELEF1 AS TELEFONE,
    TBCLIENT.CLIFAX AS FAX,
    TBCLIENT.CLIEMAIL AS EMAIL,
    COALESCE(TBCLIENT.CLICPF,'')|| COALESCE(CLICNPJ,'') AS CNPJ_CNPF,
    TBCLIENT.CLIIE AS IE_RG,
    TBCLIENT.CLIPESCON AS CONTATO
FROM TBCLIENT
LEFT JOIN TBCIDADE ON TBCLIENT.CIDCODIGO = TBCIDADE.CIDCODIGO
