select
  recno as codigo,
  nome as nome,
  fantasia as fantasia,
  case when cpf = '' or cpf is null then cgc else cpf END AS CNPJ_CNPF,
  case when identidade = '' or identidade is null then inscricaoestadual else identidade END AS IE_RG,
  endereco as endereco,
  referencia as complemento,
  bairro as bairro,
  cidade as cidade,
  uf as uf,
  replace(cep ,'-','') as cep,
  foneresidencial as telefone,
  fonecomercial as celular,
  fax as fax,
  email as email,
  pai as pai,
  mae as mae,
  Conjuge as conjuge,
  sexo as sexo,
  limitecredito as limite_credito,
  nascimento as nascimento,
  historico as observacoes
from cliente