SELECT
SUBSTRING (CLIENTE.CLICOD FROM 10 FOR 15) AS CODIGO,
CLIENTE.CLIDES AS NOME,
CLIENTE.CLIEND AS ENDERECO,
CLIENTE.CLICPFCGC AS CNPJ_CNPF,
CLIENTE.CLIBAI AS BAIRRO,
CLIENTE.CLITEL AS TELEFONE,
CLIENTE.CLICEP AS CEP,
CLIENTE.CLICID AS CIDADE,
CLIENTE.CLINUM AS NUMERO,
CLIENTE.CLICMP AS COMPLEMENTO,
CLIENTE.CLIEST AS UF,
CLIENTE.CLIFAN AS FANTASIA,
CLIENTE.CLIRGCGF AS IE_RG,
CASE WHEN CLIENTE.CLIDTCAD IS NULL THEN CURRENT_DATE ELSE
CAST(CLIENTE.CLIDTCAD AS DATE) END AS CADASTRO,
CAST(CLIENTE.CLIDTNAS AS DATE) AS NASCIMENTO,
CLIENTE.CLIPAI AS PAI,
CLIENTE.CLIEMAIL AS EMAIL,
CLIENTE.CLIMAE AS MAE
FROM CLIENTE
WHERE CLIENTE.CLICOD<>'000000'
AND CLIENTE.CLIDES IS NOT NULL
