SELECT PESSOAS.PESSOAS_ID AS CODIGO,
       PESSOAS.PESSOA_NASCIMENTO AS NASCIMENTO,
       PESSOAS.PESSOA_NOME1 AS NOME,
       PESSOAS.PESSOA_NOME2 AS FANTASIA,
       PESSOAS.PESSOA_CONTATO AS CONTATO,
       PESSOAS.PESSOA_CPF_CNPJ AS CNPJ_CNPF,
       PESSOAS.PESSOA_RG_IE AS IE_RG,
       PESSOAS.PESSOA_IM AS IM,
       ENDERECO.LOGRADOURO AS ENDERECO,
       ENDERECO.COMPLEMENTO AS COMPLEMENTO,
       ENDERECO.BAIRRO AS BAIRRO,
       ENDERECO.CEP AS CEP,
       ENDERECO.NUMERO AS NUMERO,
       MUNICIPIOS.MUNICIPIO_NOME AS CIDADE,
       ESTADOS.ESTADO_SIGLA AS UF,
       PESSOAS.PESSOA_EMAIL AS EMAIL,
       PESSOAS.PESSOA_TELEFONE AS TELEFONE,
       PESSOAS.PESSOA_CELULAR AS CELULAR,
       PESSOAS.PESSOA_PAI AS PAI,
       PESSOAS.PESSOA_MAE AS MAE,
       PESSOAS.PESSOA_OBSERVACAO AS OBSERVACOES,
       PESSOAS.PESSOA_LIMITE_CREDITO AS LIMITE_CREDITO,
       PESSOAS.PESSOA_CADASTRO AS CADASTRO
FROM PESSOAS
LEFT JOIN ENDERECO ON ENDERECO.ID = PESSOAS.PESSOAS_ID
LEFT JOIN DISTRITOS ON DISTRITOS.DISTRITOS_ID = ENDERECO.DISTRITOS_ID
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.MUNICIPIOS_ID = DISTRITOS.MUNICIPIOS_ID
LEFT JOIN ESTADOS ON ESTADOS.ESTADOS_ID = MUNICIPIOS.ESTADOS_ID
WHERE PESSOAS.PESSOA_CLIENTE = '-1'
