SELECT PRODUTOS.PRODUTOS_ID AS COD_FABRICANTE,
       PRODUTOSREFERENCIAS.PRODUTO_REFERENCIA AS BARRAS,
       PRODUTOS.PRODUTO_NOME AS DESCRICAO,
       DEPARTAMENTOS.DEPARTAMENTO_NOME AS GRUPO,
       UNIDADES.UNIDADE_SIGLA AS UND,
       PRODUTOS.PRODUTO_PRECO_CUSTO AS PRECO_CUSTO,
       PRODUTOS.PRODUTO_PRECO_VENDA AS PRECO_VENDA,
       PRODUTOS.PRODUTO_ESTOQUE_MINIMO AS QTD_IDEAL,
       PRODUTOS.PRODUTO_ESTOQUE_DISPONIVEL AS QTD,
       REPLACE(PRODUTOS.NCM_ID, '.', '') AS COD_NCM,
       REPLACE(PRODUTOS.CEST_ID, '.', '') AS PERSONAL6
FROM PRODUTOS
     LEFT JOIN PRODUTOSREFERENCIAS ON PRODUTOSREFERENCIAS.PRODUTOS_ID =
     PRODUTOS.PRODUTOS_ID
     LEFT JOIN DEPARTAMENTOS ON DEPARTAMENTOS.DEPARTAMENTOS_ID =
     PRODUTOS.DEPARTAMENTOS_ID
     LEFT JOIN UNIDADES ON UNIDADES.UNIDADES_ID = PRODUTOS.UNIDADES_ID
