select fornecedor.cd_fornecedor as codigo,
fornecedor.nome,
fornecedor.cgc as cnpj_cnpf,
fornecedor.insc_est as ie_rg,
fornecedor.contato,
fornecedor.cep,
fornecedor.endereco,
fornecedor.uf, 
fornecedor.bairro,
fornecedor.cidade,
fornecedor.telefone,
fornecedor.fax,
fornecedor.celular,
fornecedor.email,
fornecedor.obs as observacoes,
fornecedor.complemento,
fornecedor.fantasia,
fornecedor.numero
from fornecedor
