SELECT 
PESSOA.NOME,
PESSOA.RAZAO_SOCIAL AS FANTASIA,
CONTATO.NOMEPESSOA AS CONTATO,
CASE
WHEN CONTATO.TIPOCONTATOID = 1
THEN CONTATO.VALOR END "TELEFONE",
CASE WHEN CONTATO.TIPOCONTATOID = 3
THEN CONTATO.VALOR END "EMAIL",
CASE
WHEN PESSOA.FISICAJURIDICA ='J' THEN PESSOA.CNPJ ELSE
PESSOA.CPF END "CNPJ_CNPF",
PESSOA.DATA_NASCIMENTO AS NASCIMENTO,
CASE
WHEN PESSOA.FISICAJURIDICA = 'F' THEN PESSOA.RG ELSE
PESSOA.IE END "IE_RG",
PESSOA.NOME_PAI AS PAI,
PESSOA.NOME_MAE AS MAE,
ENDERECO.CEP,
BAIRRO.NOME AS BAIRRO,
ENDERECO.NUMERO,
LOGRADOURO.NOME AS ENDERECO,
MUNICIPIO.NOME AS CIDADE,
ESTADO.SIGLA AS UF
FROM FORNECEDOR
LEFT JOIN PESSOA ON FORNECEDOR.PESSOAID = PESSOA.PESSOAID
LEFT JOIN CONTATO ON FORNECEDOR.PESSOAID = CONTATO.PESSOAID
LEFT JOIN ENDERECO ON FORNECEDOR.PESSOAID = ENDERECO.PESSOAID
LEFT JOIN BAIRRO ON ENDERECO.BAIRROID = BAIRRO.BAIRROID
LEFT JOIN LOGRADOURO ON ENDERECO.LOGRADOUROID = LOGRADOURO.LOGRADOUROID
LEFT JOIN MUNICIPIO ON ENDERECO.MUNICIPIOID = MUNICIPIO.MUNICIPIOID
LEFT JOIN ESTADO ON MUNICIPIO.ESTADOID = ESTADO.ESTADOID



