SELECT
  p.ID AS COD_FABRICANTE,
  p.CODBARRA AS BARRAS,
  p.PRODUTO AS DESCRICAO,
  p.UNIDADE AS UND,
  NULL AS UND_COMPRA,
  NULL AS FAMILIA,
  g.GRUPO AS GRUPO,
  sg.SUBGRUPO AS SUBGRUPO,
  NULL AS CARACTERISTICAS,
  NULL AS FORNECEDOR,
  NULL AS QTD,
  pc.CUSTO_COMPRA,
  pc.PRECO_VENDA,
  CASE
    WHEN pc.PRECO_VENDA > 0 THEN ROUND(((pc.PRECO_VENDA - pc.CUSTO_COMPRA) / pc.PRECO_VENDA) * 100, 2)
    ELSE NULL
  END AS MARGEM_LUCRO,
  p.SITUACAO_TRIBUTARIA AS ST,
  p.CFOP AS CF,
  NULL AS COD_FABRICANTE,
  REPLACE(p.NCM, '.', '') AS COD_NCM,
  p.cest AS PERSONAL6
FROM
  produtos p
LEFT JOIN
  grupos g ON p.ID_GRUPO = g.ID
LEFT JOIN
  subgrupos sg ON p.ID_SUBGRUPO = sg.ID
LEFT JOIN
  prdcustos pc ON p.ID = pc.ID_PRD;