SELECT
    replace(COD_PRODUTO,'.','') AS CODIGO,
    DESCRICAO AS DESCRICAO,
    CODIGO_DE_BARRAS AS BARRAS,
    UNIDADE AS UND,
    ESTOQUE AS QTD,
    ESTOQUE_MINIMO AS QTD_IDEAL,
    VALOR_CUSTO AS PRECO_CUSTO,
    VALOR_VENDA AS PRECO_VENDA,
    SIT_TRIB AS ST,
    NCM AS COD_NCM,
    CEST AS PERSONAL6,
    DATA_CADASTRO AS DATA_CADASTRO,
    OBSERVACOES AS OBSERVACOES,
    COD_FABRICANTE AS COD_FABRICANTE
FROM PRODUTOS