SELECT 
--TBL_MATERIAIS.CD_MATERIAL AS CODIGO,
TBL_MATERIAIS.CD_MATERIAL AS COD_FABRICANTE,
TBL_MATERIAIS_UNIDADE.DS_ABREVIATURA as und,
TBL_MATERIAIS.CD_CODBARRA AS BARRAS,
TBL_MATERIAIS.CD_NCM as cod_ncm,
TBL_MATERIAIS.DS_MATERIAL AS DESCRICAO,
TBL_MATERIAIS.DS_OBS AS OBSERVACOES,
TBL_MATERIAIS_CONTAGEM_ESTOQUE_ITENS.NR_ESTOQUE_ATUAL AS QTD,
TBL_MATERIAIS.VL_VENDA AS PRECO_VENDA,
TBL_MATERIAIS.CD_CEST AS COD_CEST
FROM TBL_MATERIAIS 
LEFT JOIN TBL_MATERIAIS_UNIDADE ON TBL_MATERIAIS.CD_UNIDADE=TBL_MATERIAIS_UNIDADE.CD_UNIDADE
LEFT JOIN TBL_MATERIAIS_CONTAGEM_ESTOQUE_ITENS ON TBL_MATERIAIS_CONTAGEM_ESTOQUE_ITENS.CD_MATERIAL = TBL_MATERIAIS.CD_MATERIAL
