SELECT
    ESTOQUE.CODIGO_PRODUTO AS CARACTERISTICAS,
    ESTOQUE.CODIGO_FABRICANTE AS COD_FABRICANTE,
    ESTOQUE_VINCULO.codigo_barra AS BARRAS,
    ESTOQUE.DESCRICAO_PRODUTO AS DESCRICAO,
    GRUPOS.DESCRICAO_GRUPO AS GRUPO,
    ESTOQUE_SALDO.SALDO AS QTD,
    ESTOQUE.UNIDADE AS UND,
    FORNECEDORES.NOME_FORNECEDOR AS FORNECEDOR,
    SUBSTRING(ESTOQUE.CST FROM 1 FOR 1) AS OST,
    SUBSTRING(ESTOQUE.CST FROM 2 FOR 3) AS ST,
    ESTOQUE.PRECO_CUSTO AS PRECO_CUSTO,
    ESTOQUE.CUSTO_MEDIO AS CUSTO_MEDIO,
    ESTOQUE.PRECO_VENDA AS PRECO_VENDA,
    ESTOQUE.ULT_ENTRADA_DATA AS ULTIMA_COMPRA,
    ESTOQUE.ULT_SAIDA_DATA AS ULTIMA_VENDA,
    ESTOQUE.DATA_ULTIMO_REAJUSTE AS ALTERACAO_PRECO,
    ESTOQUE.OBSERVACOES AS OBSERVACOES,
    ESTOQUE.PESO AS PESO, 
    ESTOQUE.NCM AS COD_NCM,
    ESTOQUE.CEST AS PERSONAL6
FROM ESTOQUE
LEFT JOIN FORNECEDORES ON FORNECEDORES.codigo_fornecedor = ESTOQUE.fornecedor
LEFT JOIN grupos ON GRUPOS.codigo_grupo = ESTOQUE.grupo
LEFT JOIN estoque_saldo ON ESTOQUE_SALDO.codigo_produto = ESTOQUE.codigo_produto
LEFT JOIN ESTOQUE_VINCULO ON ESTOQUE_VINCULO.codigo_produto = ESTOQUE.codigo_produto
