SELECT CLIENTES.CODIGO,
CLIENTES.NOME,
CLIENTES.FANTASIA,
CLIENTES.CGC_CNPJ AS CNPJ_CNPF,
CLIENTES.IE AS IE_RG,
ENDERECO.ENDERECO,
ENDERECO.BAIRRO,
ENDERECO.UF,
ENDERECO.CEP,
ENDERECO.NUMERO,
ENDERECO.COMPLEMENTO,
CIDADE.NOME AS CIDADE,
CIDADE.UF
FROM CLIENTES
LEFT JOIN ENDERECO ON CLIENTES.ENDERECO=ENDERECO.CODIGO
LEFT JOIN CIDADE ON ENDERECO.CIDADE=CIDADE.CODIGO
WHERE CLIENTES.CODIGO>0



