SELECT
  CLIENTES.COD_CLIENTE AS CODIGO,
  CLIENTES.DSC_NOME AS NOME,
  CLIENTES.DSC_APELIDO AS FANTASIA,
  CLIENTES.DSC_ENDERECO AS ENDERECO,
  CLIENTES.DSC_NUMERO AS NUMERO,
  CLIENTES.DSC_COMPLEMENTO AS COMPLEMENTO,
  CLIENTES.DSC_BAIRRO AS BAIRRO,
  CLIENTES.DSC_CIDADE AS CIDADE,
  CLIENTES.DSC_UF AS UF,
  CLIENTES.DSC_CEP AS CEP,
  CLIENTES.DSC_TELEFONE AS TELEFONE,
  CLIENTES.DSC_FAX AS FAX,
  CLIENTES.DSC_CELULAR AS CELULAR,
  CLIENTES.DSC_CPF_CNPJ AS CNPJ_CNPF,
  CLIENTES.DSC_IE AS IE_RG,
  CLIENTES.DSC_EMAIL AS EMAIL,
  CLIENTES.DAT_NASCIMENTO AS NASCIMENTO,
  CLIENTES.NUM_LIMITE_CREDITO AS LIMITE_CREDITO,
  CLIENTES.DSC_NOME_PAI AS PAI,
  CLIENTES.DSC_NOME_MAE AS MAE
FROM CLIENTES
WHERE CLIENTES.COD_CLIENTE > '0'
AND CLIENTES.NUM_TIPO = '0'
