SELECT 
       PESSOAS.COD_PESSOA AS CODIGO
      ,PESSOAS.NOME AS FANTASIA
      ,PESSOAS.RAZAO_SOCIAL AS NOME
      ,PESSOAS.SEXO AS SEXO
      ,PESSOAS.DATA_NASC AS NASCIMENTO
      ,case when PESSOAS.INSCRICAO_ESTADUAL ='' then PESSOAS.RG
       else PESSOAS.INSCRICAO_ESTADUAL end as IE_RG
      ,PESSOAS.EMAIL1 AS EMAIL
      ,PESSOAS.CONJUGE AS CONJUGE
      ,PESSOAS.ESTADO_CIVIL AS EST_CIVIL
      ,PESSOAS.INSCRICAO_MUNICIPAL AS IM
      ,PESSOAS.CPF_CNPJ AS CNPJ_CNPF
      ,PESSOAS_ENDERECOS.NUMERO AS NUMERO
      ,PESSOAS_ENDERECOS.COMPLEMENTO AS COMPLEMENTO
      ,PESSOAS_TELEFONES.TELEFONE AS TELEFONE
      ,LOCALIZACAO.CEP AS CEP
      ,LOCALIZACAO.RUA AS ENDERECO
      ,LOCALIZACAO.BAIRRO AS BAIRRO
      ,LOCALIZACAO.UF AS UF
      ,MUNICIPIOS.DESCRICAO_MUNICIPIO AS CIDADE
  FROM DBPacWin32.dbo.PESSOAS
LEFT JOIN DBPacWin32.dbo.CLIENTES ON CLIENTES.COD_CLIENTE = PESSOAS.COD_PESSOA
LEFT JOIN DBPacWin32.dbo.PESSOAS_ENDERECOS ON PESSOAS_ENDERECOS.COD_PESSOA = PESSOAS.COD_PESSOA
LEFT JOIN DBPacWin32.dbo.LOCALIZACAO ON LOCALIZACAO.COD_LOCALIZACAO = PESSOAS_ENDERECOS.COD_LOCALIZACAO
LEFT JOIN DBPacWin32.dbo.MUNICIPIOS ON MUNICIPIOS.COD_MUNICIPIO = LOCALIZACAO.COD_MUNICIPIO
LEFT JOIN DBPacWin32.dbo.PESSOAS_TELEFONES ON PESSOAS_TELEFONES.COD_PESSOA = PESSOAS.COD_PESSOA
  WHERE DBPacWin32.dbo.PESSOAS.RAZAO_SOCIAL <> '' 
