SELECT 
       PRODUTOS.COD_PRODUTO AS CODIGO
      ,PRODUTOS.DESCRICAO AS DESCRICAO
      ,GRUPOS.NOME AS GRUPO
      ,PRODUTOS.TAMANHO AS TAMANHO
      ,PRODUTOS.CODIGO_INTERNO AS COD_FABRICANTE
      ,PRODUTOS.CODIGO_NCM AS COD_NCM
      ,PRODUTOS.CUSTO_ULTIMA_COMPRA AS PRECO_CUSTO
      ,PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO
      ,PRODUTOS.CODIGO_CEST AS PERSONAL6
      ,PRODUTOS_X_EMPRESAS.CST AS ST
      ,PRODUTOS_ESTOQUE.QUANTIDADE_ESTOQUE AS QTD
  FROM DBPacWin32.dbo.PRODUTOS
  LEFT JOIN DBPacWin32.dbo.GRUPOS ON GRUPOS.COD_GRUPO = PRODUTOS.COD_GRUPO
  LEFT JOIN DBPacWin32.dbo.PRODUTOS_X_EMPRESAS ON PRODUTOS_X_EMPRESAS.COD_PRODUTO = PRODUTOS.COD_PRODUTO
  LEFT JOIN DBPacWin32.dbo.PRODUTOS_ESTOQUE ON PRODUTOS_ESTOQUE.COD_PRODUTO = PRODUTOS.COD_PRODUTO
