SELECT 
    SUBSTRING (CLIENTES.CODIGO FROM 5 for 8) AS CODIGO,
    CLIENTES.NOME AS NOME,
    CLIENTES.CONTATO AS CONTATO,
    CLIENTES.CPF_CNPJ AS CNPJ_CNPF,
    CLIENTES.RG AS IE_RG,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.NUMERO AS NUMERO,
    CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.BAIRRO AS BAIRRO,
    MUNICIPIOS.descricao AS CIDADE,
    CLIENTES.UF AS UF,
    CLIENTES.CEP AS CEP,
    CLIENTES.FONE1 AS TELEFONE,
    CLIENTES.FONE2 AS CELULAR,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.OBSERVACAO AS OBSERVACOES,
    CLIENTES.DT_CADASTRO AS CADASTRO,
    CLIENTES.DT_NASCIMENTO AS NASCIMENTO,
    CLIENTES.PAI AS PAI,
    CLIENTES.MAE AS MAE,
    CLIENTES.LIM_CREDITO_CV AS LIMITE_CREDITO
FROM CLIENTES
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.codigo = CLIENTES.cod_municipio
