SELECT 
    FORNECEDORES.CODIGO AS CODIGO,
    FORNECEDORES.RAZAO_SOCIAL AS NOME,
    FORNECEDORES.NOME_FANTASIA AS FANTASIA,
    FORNECEDORES.CPF_CNPJ AS CNPJ_CNPF,
    FORNECEDORES.CGF AS IE_RG,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CEP AS CEP,
    MUNICIPIOS.descricao AS CIDADE,
    FORNECEDORES.UF AS UF,
    FORNECEDORES.FONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.codigo = FORNECEDORES.cod_municipio
