SELECT 
    --PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.CODIGO AS COD_FABRICANTE,
    PRODUTOS.COD_BARRAS AS BARRAS,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    UNIDADES.SIMBOLO AS UND,
    MIN (PRODUTOS_ESTOQUE.SALDO_ATUAL) AS QTD,
    PRODUTOS_EMPRESA.ESTOQUE_MINIMO AS QTD_IDEAL,
    GRUPOS.DESCRICAO AS GRUPO,
    SUBGRUPOS.DESCRICAO AS FAMILIA,
    FORNECEDORES.razao_social AS FORNECEDOR,
    PRODUTOS_EMPRESA.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS_EMPRESA.PRECO AS PRECO_VENDA,
    PRODUTOS_EMPRESA.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.COD_NCM AS COD_NCM,
    PRODUTOS.OBSERVACAO AS OBSERVACOES,
    PRODUTOS.COD_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.codigo = PRODUTOS.cod_grupo
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.codigo = PRODUTOS.cod_subgrupo
LEFT JOIN UNIDADES ON UNIDADES.codigo = PRODUTOS.cod_unidade
LEFT JOIN PRODUTOS_ESTOQUE ON PRODUTOS_ESTOQUE.cod_produto = PRODUTOS.CODIGO
LEFT JOIN PRODUTOS_EMPRESA  ON PRODUTOS_EMPRESA.cod_produto = PRODUTOS.CODIGO
LEFT JOIN FORNECEDORES ON FORNECEDORES.codigo = PRODUTOS_EMPRESA.cod_fornecedor
where produtos_empresa.cod_empresa = '01'
GROUP BY 1,2,3,4,6,7,8,9,10,11,12,13,14,15
