SELECT PRODUTOS.PROCODIGO AS CODIGO,
PRODUTOS.PROEAN AS BARRAS,
PRODUTOS.PRODESCRICAO AS DESCRICAO,
PRODUTOS.PROSIGLAUNMED AS UND,
PRODUTOS.PRONCM AS COD_NCM,
PRODUTOS.PROCSOSN AS ST,
PRODUTOS.PROVALOR AS PRECO_VENDA,
PRODUTOS.PROCODCEST AS PERSONAL6
FROM PRODUTOS
