SELECT
  PRODUTO.cod AS COD_FABRICANTE,
  PRODUTO.prod AS DESCRICAO,
  --PRODUTO.ref AS COD_FABRICANTE,
  PRODUTO.codba AS BARRAS,
  TAB_GRUPO.DESCRICAO AS GRUPO,
  PRODUTO.custo AS PRECO_CUSTO,
  PRODUTO.margem AS MARGEM_LUCRO,
  PRODUTO.venda AS PRECO_VENDA,
  PRODUTO.estoque AS QTD,
  PRODUTO.cmedio AS CUSTO_MEDIO,
  PRODUTO.ncm AS COD_NCM,
  PRODUTO.cest AS PERSONAL6,
  PRODUTO.cst_icms AS ST,
  PRODUTO.cst_pis AS PIS_CODIGO,
  PRODUTO.cst_cofins AS COFINS_CODIGO,
  PRODUTO.cst_pis_entrada AS PISE_CODIGO,
  PRODUTO.cst_cofins_entrada AS COFINSE_CODIGO
FROM PRODUTO
LEFT JOIN TAB_GRUPO ON PRODUTO.GRUPO = TAB_GRUPO.CODIGO
