SELECT
 PESSOAS.idPessoa AS CODIGO,
  CIDADES.CIDADE AS CIDADE,
  CIDADES.UF AS UF,
  PESSOAS.razaoSocial AS NOME,
  PESSOAS.nomeFantasia AS FANTASIA,
  PESSOAS.cpfCnpj AS CNPJ_CNPF,
  PESSOAS.rgIe AS IE_RG,
  PESSOAS.bairro AS BAIRRO,
  PESSOAS.logradouro AS ENDERECO,
  PESSOAS.numero AS NUMERO,
  PESSOAS.complemento AS COMPLEMENTO,
  PESSOAS.cep AS CEP,
  PESSOAS.tel AS TELEFONE,
  PESSOAS.cel AS CELULAR,
  PESSOAS.email AS EMAIL
FROM PESSOAS
LEFT JOIN CIDADES ON PESSOAS.CODCIDADE = CIDADES.CODCIDADE
WHERE PESSOAS.TPCLIENTE = 'S'
