SELECT 
  P.CODIGO
, P.NOME AS DESCRICAO
, P.SLD_ATUAL AS QTD
, P.COMPOSTO_POR AS UND
, P.PRECO_CUSTO_UNITARIO AS PRECO_CUSTO
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.PRECO_VEND AS PRECO_VENDA
, COALESCE (P.DATA_CAD, CURRENT_DATE) AS CADASTRO
, P.CODPROD AS BARRAS
, P.COD_EAN AS COD_FABRICANTE
, P.CSOSN AS ST
, P.NCM_SH AS COD_NCM
, P.CFOP_ESTADO AS CF
, SUBSTRING (P.CFOP_ESTADO FROM 1 FOR 3) AS ELO
, P.OBS AS OBSERVACOES
, P.CEST AS PERSONAL6
, P.UN_COMP AS UND_COMPRA
, P.Q_UN_COMP AS FAT_CONV
, F.NOME AS FORNCEDOR
, G.NOME AS GRUPO
, T.PERCENTUAL AS PERSONAL1
FROM PRODUTOS P
LEFT JOIN FORNECEDOR F ON F.CODIGO = P.CODFORN
LEFT JOIN GRUPO G ON G.GRUPO_COD = P.CODGRUPO
LEFT JOIN TRIBUTADO T ON T.CODIGO = P.CODTRIB
