SELECT TB_CADCLIENTEFORNEC.CODIGO,
TB_CADCLIENTEFORNEC.NOME,
TB_CADCLIENTEFORNEC.FANTASIA,
TB_CADCLIENTEFORNEC.CONTATO,
TB_CADCLIENTEFORNEC.CGC AS CNPJ_CNPF,
TB_CADCLIENTEFORNEC.ENDERECO,
TB_CADCLIENTEFORNEC.NUMERO,
TB_CADCLIENTEFORNEC.BAIRRO,
TB_CADCLIENTEFORNEC.COMPLEMENTO,
TB_CADCLIENTEFORNEC.CEP,
TB_CADMUNICIPIO.DESCRICAO AS CIDADE,
TB_CADMUNICIPIO.UF,
TB_CADCLIENTEFORNEC.FONE AS TELEFONE,
TB_CADCLIENTEFORNEC.CELULAR,
TB_CADCLIENTEFORNEC.FAX,
TB_CADCLIENTEFORNEC.EMAIL,
TB_CADCLIENTEFORNEC.OBSERVACOES,
TB_CADCLIENTEFORNEC.IERG AS IE_RG,
TB_CADCLIENTEFORNEC.ULTIMACOMPRA AS ULTIMA_COMPRA,
TB_CADCLIENTEFORNEC.DATACADASTRO AS CADASTRO
FROM TB_CADCLIENTEFORNEC
LEFT JOIN TB_CADMUNICIPIO ON TB_CADCLIENTEFORNEC.CODCIDADE=TB_CADMUNICIPIO.CODIGO
WHERE TB_CADCLIENTEFORNEC.TIPO=2


