SELECT
    ESTOQUE.CODIGO,
    ESTOQUE.DESCRICAO,
    grupos_produtos.DESCRICAO AS GRUPO,
    --ESTOQUE.ULTIMA_COMPRA,
    ESTOQUE.PRECO_CUSTO,
    ESTOQUE.BARRAS,
    ESTOQUE.QTD,
    ESTOQUE.QTD_IDEAL,
    ESTOQUE.OBSERVACOES,
    UNIDADE.DESCRICAO AS UND,
    ESTOQUE.PRECO_VENDA,
    ESTOQUE.CARACTERISTICA,
    ESTOQUE.COD_FABRICANTE,
    ESTOQUE.ST,
    NCM.NCM AS COD_NCM,
    ESTOQUE. PERSONAL6

FROM ESTOQUE

LEFT JOIN grupos_produtos ON ESTOQUE.PERSONAL1 = grupos_produtos.CODIGO
LEFT JOIN UNIDADE ON ESTOQUE.personal2 = UNIDADE.CODIGO
LEFT join NCM ON ESTOQUE.PERSONAL3 = NCM.cod_ncm
