SELECT
TABPRO.CODPRO AS COD_FABRICANTE,
TABPRO.DESCPRO AS DESCRICAO,
--TABFAB.NOMFAB AS CARACTERISTICAS,
TABFAB.NOMFAB AS FAMILIA,
tabpro.codbarun as barras,
TABGRU.NOMGRU AS GRUPO,
TABPRO.UNIDADE AS UND,
TABPRO.CLASFISCAL AS COD_NCM,
TABPRO.CEST AS PERSONAL6,
TABPRO.CST AS ST,
TABPROFIL.QTDPRO AS QTD,
TABPROFIL.PRVAPRO AS PRECO_VENDA,
--TABPROFIL.PRCUPRO AS PRECO_CUSTO
TABPROFIL.PRCOMPRAVA AS PRECO_CUSTO
FROM TABPRO
LEFT JOIN TABGRU ON TABPRO.GRUPRO=TABGRU.CODGRU
LEFT JOIN TABPROFIL ON TABPRO.CODPRO=TABPROFIL.CODPRO
LEFT JOIN TABFAB ON TABFAB.codfab = TABPRO.FABPRO
where TABPROFIL.codfil = '1'




