SELECT
  --M.MAT_CODI AS CODIGO,
  C.MAUX_CODI AS BARRAS,
  M.MAT_DESC AS DESCRICAO,
  M.MAT_UNID AS UND,
  M.MAT_EMBALAGEM AS UND_COMPRA,
  M.MAT_CDGR AS FAMILIA,
  M.MAT_CDSG AS GRUPO,
  M.MAT_MARC AS CARACTERISTICAS,
  F.FOR_RAZA AS FORNECEDOR,
  COALESCE(E.EL1_QTD, 0) AS QTD_ESTOQUE,
  V.VW_PRECO AS PRECO_VENDA,
  --M.MAT_PVAR AS CUSTO_MEDIO,
  --M.MAT_PATA AS PRECO_CUSTO,
  --M.MAT_TXPV AS MARGEM_LUCRO,
  U.MUF_CST AS ST,  -- Valor do CST vindo de TB_MAT_UF
  M.MAT_REFE AS COD_FABRICANTE,
  M.MAT_NCM AS COD_NCM,
  M.MAT_CEST AS PERSONAL6
FROM
  TB_MATE M
LEFT JOIN
  TB_MAT_CDAUX C ON C.MAUX_CDMT = M.MAT_REFE
LEFT JOIN
  TB_FORN F ON F.FOR_CODI = M.MAT_CDFR
LEFT JOIN
  VW_PROD_PREC V ON V.VW_CODI = M.MAT_CODI
LEFT JOIN
  TB_ESTLOCAL1 E ON E.EL1_PRODUTO = M.MAT_CODI
LEFT JOIN
  TB_MAT_UF U ON U.MUF_CDMT = M.MAT_CODI
-- Se necessário, adicione uma condição específica de UF:
-- AND U.MUF_UF = 'SP'
;