SELECT
    PRODUTO.CODIGO,
    PRODUTO.DESCRICAO,
    ESTOQUE.ETOTAL AS QTD,
    PRODUTO.PRECO1 AS PRECO_VENDA,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO.CODNCM AS COD_NCM
FROM PRODUTO
LEFT JOIN ESTOQUE ON PRODUTO.CODIGO = ESTOQUE.CODPRODUTO
WHERE ESTOQUE.CODLOJA = '1'
