SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    GRUPO.DESCRICAO AS GRUPO,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.PRECOMPRA AS PRECO_CUSTO,
    PRODUTO.PRECOVENDA AS PRECO_VENDA,
    PRODUTO.ESTOQUE AS QTD,
    PRODUTO.ESTOMINI AS QTD_IDEAL,
    FORNECEDOR.RAZAO AS FORNECEDOR,
    CAST (PRODUTO.DATACADAS AS DATE) AS DATA_CADASTRO,
    CAST (PRODUTO.DULTCOMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (PRODUTO.DULTVENDA AS DATE) AS ULTIMA_VENDA,
    PRODUTO.PERLUCRO AS MARGEM_LUCRO,
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6,
    PRODUTO.MARCA AS CARACTERISTICAS,
    case when PRODUTO.STATUS = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTO.FORNECEDOR
WHERE PRODUTO.DESCRICAO IS NOT NULL or PRODUTO.DESCRICAO <> ''
