SELECT
	CODIGO AS CODIGO,
	FANTASIA AS FANTASIA,
	RAZAO AS NOME,
	ENDERECO AS ENDERECO,
	CIDADE AS CIDADE,
	BAIRRO AS BAIRRO,
	CEP AS CEP,
	ESTADO AS UF,
	CONTATO AS CONTATO,
	TELEFONE AS TELEFONE,
	FAX AS FAX,
	case when CPF = '' or CPF is null then CNPJ else CPF END AS CNPJ_CNPF,
	INSC_EST AS IE,
	EMAIL AS EMAIL,
	NUMERO AS NUMERO,
	OBSERVACAO AS OBSERVACOES
FROM FORNEC
