SELECT
	PRO.CODIGO AS CODIGO,
	PRO.DESCRICAO AS DESCRICAO,
	PRO.REFERENCIA AS FAMILIA,
	PRO.UNIDADE AS UND,
	PRO.BARRAS AS BARRAS,
	GP.DESCRICAO AS GRUPO,
	SB.DESCRICAO AS CARACTERISTICAS,
	FORNEC.RAZAO AS FORNECEDOR,
	PRO.PR_CUSTO AS PRECO_CUSTO,
	PRO.PR_VEND AS PRECO_VENDA,
	PRO.MARGEM_L AS MARGEM_LUCRO,
	PRO.ULT_COMP AS ULTIMA_COMPRA,
	PRO.ULT_VENDA AS ULTIMA_VENDA,
	PRO.ESTOQUE AS QTD,
	ALIQUOTAS.CST AS ST,
	ALIQUOTAS.INDICE AS ELO,
	PRO.OBS AS OBSERVACOES,
	PRO.NCM AS COD_NCM,
	PRO.PISCOFINS AS PIS_CODIGO,
	PRO.PISCOFINS AS COFINS_CODIGO,
	PRO.CEST AS PERSONAL6,
	PRO.UNDCOMPRA AS UND_COMPRA
FROM PRODUTOS PRO
LEFT JOIN GRUPOS GP ON GP.CODIGO=PRO.GRUPO 
LEFT JOIN SUBGRUPOS SB ON SB.CODIGO=PRO.SUBGRUPO 
LEFT JOIN FORNEC ON FORNEC.CODIGO=PRO.FORNEC 
LEFT JOIN ALIQUOTAS  ON ALIQUOTAS.ALIQUOTA=PRO.ALIQ
