SELECT
  PRODUTOS.COD AS CODIGO,
  PRODUTOS.NOME AS DESCRICAO,
  PRODUTOS.COD_BARRAS AS BARRAS,
  PRODUTOS.UNIDADE AS UND,
  CATEGPROD.NOME AS GRUPO,
  MAX(ESTOQUE.QUANT) AS QTD,
  PRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
  PRODUTOS.PRECOCOMPRA AS PRECO_CUSTO,
  PRODUTOS.PRECOMEDIO AS CUSTO_MEDIO,
  PRODUTOS.PRECO AS PRECO_VENDA,
  PRODUTOS.DATAALTER AS ALTERACAO_PRECO,
  PRODUTOS.CSOSN AS ST,
  PRODUTOS.PAF_NCM AS COD_NCM,
  PRODUTOS.CEST AS PERSONAL6,
  PRODUTOS.OBSMODOPREPARO AS OBSERVACOES
FROM produtos
LEFT JOIN CATEGPROD ON CATEGPROD.COD = PRODUTOS.CATEGORIA
LEFT JOIN ESTOQUE ON ESTOQUE.CODPROD = PRODUTOS.COD
WHERE PRODUTOS.NOME <> ''
GROUP BY 1,2,3,4,5,7,8,9,10,11,12,13,14,15
