SELECT
    FORNECEDOR.FORNECEDOR AS CODIGO,
    FORNECEDOR.NOME AS NOME,
    FORNECEDOR.CONTATO AS CONTATO,
    FORNECEDOR.CPF AS CNPJ_CNPF,
    FORNECEDOR.IE AS IE_RG,
    FORNECEDOR.IM AS IM,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    BAIRRO.NOME AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.TELEFONE AS TELEFONE,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN BAIRRO ON BAIRRO.BAIRRO = FORNECEDOR.BAIRRO
LEFT JOIN CIDADE ON CIDADE.CIDADE = FORNECEDOR.CIDADE
