SELECT
    PRODUTO.PRODUTO AS CODIGO,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.COMPLEMENTO AS COD_FABRICANTE,
    PRODUTO.VOLUME AS UND,
    PRODUTO.PESOBRU AS PESO,
    PRODUTO.COR,
    PRODUTO.TAMANHO,
    PRODUTO.GTIN AS BARRAS,
    PRODUTO.ORIGEMMERCADORIA AS OST, 
    PRODUTO.OBS AS OBSERVACOES,
    CASE PRODUTO.SITUACAO WHEN 'I' THEN 'Inativo' ELSE 'Ativo' END AS SITUACAO,	
    TRIBUTACAO.CST AS ST,
    IPI.CSTINV AS IPI_CODIGO,
    IPI.CST AS IPI_CODIGO_VENDA,
    IPI.ALIQ AS ALIQ_IPI_VENDA, 
    PIS.CSTINV AS PISE_CODIGO, 
    PIS.CST AS PIS_CODIGO,     
    PIS.ALIQUOTA AS PIS_ALIQ_NOR,
    COFINS.CSTINV AS COFINSE_CODIGO, 
    COFINS.CST AS COFINS_CODIGO,     
    COFINS.ALIQUOTA AS COFINS_ALIQ_NOR,
    GRUPO.NOME AS GRUPO,
    ESTOQUE.ESTMIN AS QTD_IDEAL,  
    ESTOQUE.COMISS AS COMISSAO,
    ESTOQUE.VRCUST AS PRECO_CUSTO,
    ESTOQUE.VRVEND AS PRECO_VENDA,
    ESTOQUE.QTDESTOQUE AS QTD,
    IBPT.NCM AS COD_NCM, 
    IBPT.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.TRIBUTACAO = PRODUTO.TRIBUTACAO
LEFT JOIN ESTOQUE ON ESTOQUE.PRODUTO = PRODUTO.PRODUTO AND ESTOQUE.DEPOSITO = '1' -- AJUSTAR O CÓDIGO/EMPRESA DO DEPOSITO AQUI
LEFT JOIN GRUPO ON GRUPO.GRUPO = PRODUTO.GRUPO
LEFT JOIN IPI ON IPI.IPI = PRODUTO.IPI
LEFT JOIN PIS ON PIS.PIS = PRODUTO.PIS  
LEFT JOIN COFINS ON COFINS.COFINS = PRODUTO.COFINS  
LEFT JOIN IBPT ON IBPT.IBPT = PRODUTO .IBPT 
