SELECT 
       MIN(ESTOQUE.COD_ABREV) AS BARRAS
      ,MIN(ESTOQUE.PRODUTO) AS DESCRICAO
      --,MIN(PRODUTOS.COD_PROD) AS BARRAS
      ,ESTOQUE.UNIDADE AS UND
      ,ESTOQUE.QTD_MIN AS QTD_IDEAL
      ,ESTOQUE.QTD AS QTD
      ,ESTOQUE.CUSTO AS PRECO_CUSTO
      ,ESTOQUE.CUSTO_MEDIO AS CUSTO_MEDIO 
      ,ESTOQUE.MARGEM AS MARGEM_LUCRO
      ,ESTOQUE.PRECO AS PRECO_VENDA
      ,ESTOQUE.GRUPO AS GRUPO
      ,ESTOQUE.SUB_GRUPO AS FAMILIA
      ,ESTOQUE.DT_REAJUSTE AS ALTERACAO_PRECO
      ,ESTOQUE.REFERENCIA AS CODIGO
      ,ESTOQUE.S_TRIBUT AS ST    
      ,ESTOQUE.OBS AS OBSERVACOES 
      ,MIN(PRODUTOS.NCM) AS COD_NCM
      ,MIN(PRODUTOS.CEST) AS PERSONAL6
  FROM EZ_COMSQL.dbo.ESTOQUE
  LEFT JOIN EZ_COMSQL.dbo.PRODUTOS ON EZ_COMSQL.dbo.PRODUTOS.CODIGO = ESTOQUE.COD_PROD
  GROUP BY
       ESTOQUE.UNIDADE
      ,ESTOQUE.QTD_MIN
      ,ESTOQUE.QTD
      ,ESTOQUE.CUSTO
      ,ESTOQUE.CUSTO_MEDIO
      ,ESTOQUE.MARGEM
      ,ESTOQUE.PRECO
      ,ESTOQUE.GRUPO
      ,ESTOQUE.SUB_GRUPO
      ,ESTOQUE.DT_REAJUSTE
      ,ESTOQUE.REFERENCIA
      ,ESTOQUE.S_TRIBUT
      ,ESTOQUE.OBS
