SELECT
    P.ID_PRODUTO AS CODIGO,
    P.CODIGO AS BARRAS,
    --P.CODBARRAS,
    P.DESCRICAO AS DESCRICAO,
    P.UN AS UND,
    G.DESCRICAO AS GRUPO,
    P.QUANTIDADE AS QTD,
    P.MINIMO AS QTD_IDEAL,
    P.PRECO_CUSTO AS PRECO_CUSTO,
    P.PRECOVENDA AS PRECO_VENDA,
    P.ST AS ST,
    P.REFERENCIA AS COD_FABRICANTE,
    P.DATAINICIAL AS DATA_CADASTRO,
    P.NCM AS COD_NCM,
    P.CEST AS PERSONAL6
FROM PRODUTOS AS P
LEFT JOIN GRUPOPROD G ON P.ID_GRUPOPROD = G.ID_GRUPOPROD
