SELECT
    TBPRODUTO.CODIGO AS CODIGO,
    TBPRODUTO.PRODUTO AS DESCRICAO,
    TBPRODUTO.UN AS UND,
    TBESTOQUE.saldo AS QTD,
    TBPRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
    TBPRODUTO.VRUNIT AS PRECO_VENDA,
    TBPRODUTO.GRUPO AS GRUPO,
    TBPRODUTO.CODIGOBARRA AS BARRAS,
    TBFORNECEDOR.fornecedor AS FORNECEDOR,
    TBPRODUTO.CLASSEFISCAL AS COD_NCM,
    TBPRODUTO.PESO AS PESO,
    substring (TBPRODUTO.CLASS_TRIB from 1 for 3) AS ST,
    TBPRODUTO.CEST AS PERSONAL6
FROM TBPRODUTO
LEFT JOIN tbestoque ON TBESTOQUE.codigo = TBPRODUTO.codigo
LEFT JOIN TBFORNECEDOR ON TBFORNECEDOR.codigo = TBPRODUTO.CODFORNECEDOR
WHERE TBPRODUTO.PRODUTO <> '' OR TBPRODUTO.PRODUTO IS NOT NULL
