SELECT
    SUBSTRING (FORNECEDORES.CODIGO FROM 5 FOR 10) AS CODIGO,
    FORNECEDORES.NOME AS NOME,
    FORNECEDORES.RAZAO AS FANTASIA,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.ESTADO AS UF,
    FORNECEDORES.CONTATO AS CONTATO,
    case when FORNECEDORES.CPF = '' or FORNECEDORES.CPF is null then FORNECEDORES.CNPJ else FORNECEDORES.CPF END AS CNPJ_CNPF,
    case when FORNECEDORES.RG = '' or FORNECEDORES.RG is null then FORNECEDORES.IE else FORNECEDORES.RG END AS IE_RG,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.OBS AS OBSERVACOES,
    FORNECEDORES.EMAIL AS EMAIL
FROM FORNECEDORES
