SELECT
    PRODUTOS.codigo AS CODIGO,
    PRODUTOS.nomepro AS DESCRICAO,
    SECOES.NOMESEC AS FAMILIA,
    GRUPOS.NOMEGRUPO AS GRUPO,
    PRODUTOS.unidade AS UND,
    PRODUTOS.qtdeprod AS QTD,
    PRODUTOS.preco AS PRECO_VENDA,
    PRODUTOS.custo1 AS PRECO_CUSTO,
    PRODUTOS.cst AS ST,
    PRODUTOS.cean AS BARRAS,
    PRODUTOS.ncm AS COD_NCM
FROM PRODUTOS
LEFT JOIN SECOES ON PRODUTOS.CODSEC = SECOES.CODSEC
LEFT JOIN GRUPOS ON PRODUTOS.CODGRU = GRUPOS.CODGRU