SELECT
    P.PES_COD       AS CODIGO,
    P.PES_RAZ       AS NOME,
    P.PES_FAN       AS FANTASIA,
    P.PES_CON       AS CONTATO,
    P.PES_INF       AS CNPJ_CNPF,
    P.PES_RGI       AS IE_RG,
    NULL            AS IM,
    E.END_END       AS ENDERECO,
    E.END_NRO       AS NUMERO,
    E.END_COP       AS COMPLEMENTO,
    E.END_BAI       AS BAIRRO,
    M.MUN_NOM       AS CIDADE,
    M.MUN_EST       AS UF,
    E.END_CEP       AS CEP,
    COALESCE('(' || P.PES_DDD || ') ', '') || COALESCE(P.PES_FOP, '') AS TELEFONE,
    COALESCE('(' || P.PES_DDS || ') ', '') || COALESCE(P.PES_FOS, '') AS CELULAR,
    P.PES_EMA       AS EMAIL,
    P.PES_OBS       AS OBSERVACOES,
    CASE 
        WHEN C.CLI_PES IS NOT NULL AND F.FOR_PES IS NOT NULL THEN 'CLIENTE E FORNECEDOR'
        WHEN C.CLI_PES IS NOT NULL THEN 'CLIENTE'
        WHEN F.FOR_PES IS NOT NULL THEN 'FORNECEDOR'
        ELSE NULL
    END             AS TIPO_PESSOA

FROM
    PESSOA P
LEFT JOIN
    ENDERECO E ON E.END_INT = P.PES_COD
LEFT JOIN
    MUNICIPIO M ON M.MUN_COD = E.END_MUN
LEFT JOIN
    CLIENTE C ON C.CLI_PES = P.PES_COD
INNER JOIN
    FORNECEDOR F ON F.FOR_PES = P.PES_COD;
