SELECT
    TBPRODUTO.PROD_IDPRODUTO AS CODIGO,
    TBPRODUTO.PROD_DESCRICAO AS DESCRICAO,
    TBPRODUTO.PROD_IDUNIDADE AS UND,
    TBPRODUTO.PROD_VLRCOMPRA AS PRECO_CUSTO,
    TBPRODUTO.PROD_VLRUNITARIO AS PRECO_VENDA,
    TBPRODUTO.PROD_VLRMARGEM AS MARGEM_LUCRO,
    TBPRODUTO.PROD_CODNCM AS COD_NCM,
    TBPRODUTO.PROD_CSOSN AS ST,
    TBPRODUTO.PROD_ESTMINIMO AS QTD_IDEAL,
    MAX (TBESTOQUE.EST_QUANTIDADE) AS QTD,
    TBPRODUTO.PROD_DTCADASTRO AS DATA_CADASTRO,
    TBPRODUTO.PROD_OBSERVACAO AS OBSERVACOES,
    TBPRODUTO.PROD_ULTIMACOMPRA AS ULTIMA_COMPRA,
    TBPRODUTO.PROD_ULTIMAVENDA AS ULTIMA_VENDA,
    TBSECAO.SEC_DESCRICAO AS GRUPO,
    TBPRODUTO.PROD_REFERENCIA AS COD_FABRICANTE,
    TBPRODUTO.PROD_VLRCUSTOMEDIO AS CUSTO_MEDIO,
    CAST (TBPRODUTO.PROD_ALTERACAO_PRECO_DATA AS DATE) AS ALTERACAO_PRECO,
    TBPRODUTO.PROD_CEST AS PERSONAL6,
    TBPRODUTO.PROD_PESOLIQ AS PESO
FROM TBPRODUTO
LEFT JOIN TBSECAO ON TBSECAO.SEC_IDSECAO = TBPRODUTO.PROD_IDSECAO
LEFT JOIN TBESTOQUE ON TBESTOQUE.EST_IDPRODUTO = TBPRODUTO.PROD_IDPRODUTO
--WHERE EST_IDTIPOMOVIMENTO = '3'
GROUP BY 1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20
