SELECT PESSOA.ID AS CODIGO,
PESSOA.NOME,
PESSOA.FANTASIA,
PESSOA.EMAIL,
PESSOA.CPF_CNPJ AS CNPJ_CNPF,
PESSOA.INSCRICAO_ESTADUAL AS IE_RG,
PESSOA.CONTATO,
PESSOA.FONE1 AS TELEFONE,
PESSOA.CELULAR,
PESSOA.LIMITE_CREDITO,
PESSOA_ENDERECO.LOGRADOURO AS ENDERECO,
PESSOA_ENDERECO.NUMERO,
PESSOA_ENDERECO.COMPLEMENTO,
PESSOA_ENDERECO.CEP,
PESSOA_ENDERECO.BAIRRO,
PESSOA_ENDERECO.CIDADE,
PESSOA_ENDERECO.UF
FROM PESSOA
LEFT JOIN PESSOA_ENDERECO ON PESSOA.ID=PESSOA_ENDERECO.ID_PESSOA
WHERE PESSOA.CLIENTE='S'

