SELECT
    ID_ITEM AS CODIGO,
    DESCRICAO,
    UNIDADE AS UND,
    PRECO1 AS PRECO_VENDA,
    COD_BARRA AS BARRAS,
    NCM AS COD_NCM,
    CST_PIS AS PIS_CODIGO,
    CST_COFINS AS COFINS_CODIGO,
    CSOSN_SAI AS ST
FROM ITEM