SELECT
    PRODUTO.CD_PROD AS COD_FABRICANTE,
    PRODUTO.DSC_PROD AS DESCRICAO,
CODIGO_BARRA.CD_BRR AS BARRAS,
SUBGRUPO.DSC_SUBGRUPO AS FAMILIA,
MAX(PRODUTO_PRECO_VENDA.CST_PROD) AS PRECO_CUSTO,
MAX(PRODUTO_PRECO_VENDA.PRC_VENDA) AS PRECO_VENDA,
    PRODUTO.CD_NCM AS COD_NCM,
    MAX(FISC_TABELA_FISCAL_DETALHE.CST) AS ST,
    --PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_PRECO_VENDA ON PRODUTO.CD_PROD = PRODUTO_PRECO_VENDA.CD_PROD
LEFT JOIN CODIGO_BARRA ON PRODUTO.CD_PROD = CODIGO_BARRA.CD_PROD
LEFT JOIN SUBGRUPO ON PRODUTO.CD_SUB_GRUPO = SUBGRUPO.CD_SUBGRUPO
LEFT JOIN FISC_TABELA_FISCAL_DETALHE ON PRODUTO.CD_TAB_FISC = FISC_TABELA_FISCAL_DETALHE.CD_TAB_FISC
GROUP BY 
    PRODUTO.CD_PROD,
    PRODUTO.DSC_PROD,
CODIGO_BARRA.CD_BRR,
SUBGRUPO.DSC_SUBGRUPO,
    PRODUTO.CD_NCM,
    PRODUTO.CD_TAB_FISC,
   --PRODUTO.REFERENCIA,
    PRODUTO.CEST
