SELECT
    PRODUTOS.ID AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.EAN13 AS BARRAS,
    PRODUTOS.UNIDADE AS UND,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    PRODUTOS.PRECO_COMPRA AS PRECO_COMPRA,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    SUBSTRING (PRODUTOS_CLASSIFICACAO.INDICEA FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS_CLASSIFICACAO.INDICEA FROM 2 FOR 2) AS ST,
    PRODUTOS.OBS AS OBSERVACOES,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    CAST (PRODUTOS.DATA_ULT_ALTERACAO AS DATE) AS ALTERACAO_PRECO
FROM PRODUTOS
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.ID = PRODUTOS.SUBGRUPO1
LEFT JOIN PRODUTOS_CLASSIFICACAO ON PRODUTOS_CLASSIFICACAO.ID = PRODUTOS.CLASIFICACAO_FISCAL 
