SELECT CLIEN.COD_CLIE AS CODIGO,
CLIEN.DAT_CAD AS CADASTRO,
CLIEN.NOME,
CLIEN.CPF_CNPJ AS CNPJ_CNPF,
CLIEN.NUMERO,
CLIEN.ENDERECO,
CLIEN.COMPLEMENTO,
CLIEN.BAIRRO,
CLIEN.CIDADE,
CLIEN.UF,
CLIEN.CEP,
CLIEN.TELEFONE,
CLIEN.FAX,
CLIEN.CELULAR,
CLIEN.EMAIL,
CLIEN.APELIDO AS FANTASIA
FROM CLIEN


