SELECT 
  F.FORNECEDOR_ID AS CODIGO
, F.FORNECEDOR_NOME AS NOME
, F.FORNECEDOR_FANTASIA AS FANTASIA
, F.FORNECEDOR_DOCUMENTO AS CNPJ_CNPF
, F.FORNECEDOR_RG_IE AS IE_RG
, F.FORNECEDOR_LOGRADOURO AS ENDERECO
, F.FORNECEDOR_BAIRRO AS BAIRRO
, F.FORNECEDOR_NUMERO AS NUMERO
, F.FORNECEDOR_COMPLEMENTO AS COMPLEMENTO
, F.FORNECEDOR_CEP AS CEP
, F.FORNECEDOR_TELEFONE AS TELEFONE
, F.FORNECEDOR_CELULAR AS CELULAR
, F.FORNECEDOR_EMAIL AS EMAIL
, F.FORNECEDOR_OBSERVACOES AS OBSERVACOES
, CI.CIDADE_NOME AS CIDADE
, CI.CIDADE_UF AS UF
FROM FORNECEDORES F
LEFT JOIN CIDADES CI ON CI.CIDADE_ID = F.FORNECEDOR_CIDADE