SELECT 
  P.PRODUTO_CODIGO AS COD_FABRICANTE
  , P.PRODUTO_BARRAS AS BARRAS
  , P.PRODUTO_DESCRICAO AS DESCRICAO
  , P.PRODUTO_MARCA AS CARACTERISTICAS
  , P.PRODUTO_LOCALIZACAO AS PERSONAL1
  , P.PRODUTO_MODELO AS PERSONAL2
  , P.PRODUTO_ESTOQUE AS QTD
  , P.PRODUTO_ESTOQUE_MIN AS QTD_IDEAL
  , P.PRODUTO_NCM AS COD_NCM
  , P.PRODUTO_CEST AS PERSONAL6
  , P.PRODUTO_COMISSAO AS COMISSAO
  , P.PRODUTO_CUSTO_ATUAL AS PRECO_CUSTO
  , P.PRODUTO_VAL_VENDA AS PRECO_VENDA
  , P.PRODUTO_ALIQ_PIS AS PIS_ALIQ_NOR
  , P.PRODUTO_ALIQ_COFINS AS PISE_ALIQ_NOR
  , P.PRODUTO_ALIQ_IPI AS ALIQ_IPI_VENDA
  , CASE P.PRODUTO_ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
  , P.PRODUTO_VENCIMENTO_DIAS AS VALIDADE_DIAS
  , P.PRODUTO_APLICACAO AS OBSERVACOES
  , P.PRODUTO_QNT_CAIXA AS FAT_CONV
  , P.PRODUTO_PESO AS PESO
  , PG.PRODUTO_GRUPO_DESCR AS GRUPO
  , PS.PRODUTO_SUBGRUPO_DESCR AS FAMILIA
  , PU.PRODUTO_UN_SIGLA AS UND
  , PC.PRODUTO_CST_VALOR AS ST
  , SUBSTRING (PC2.PRODUTO_CFOP_VALOR FROM 1 FOR 3) AS ELO
  , PMP.PRODUTO_MOD_PIS_VALOR AS PIS_CODIGO
  , PMC.PRODUTO_MOD_COFINS_VALOR AS COFINS_CODIGO
  , PMI.PRODUTO_MOD_IPI_VALOR AS IPI_CODIGO_VENDA
FROM PRODUTOS P
LEFT JOIN PRODUTOS_GRUPOS PG ON PG.PRODUTO_GRUPO_ID = P.PRODUTO_GRUPO
LEFT JOIN PRODUTOS_SUBGRUPOS PS ON PS.PRODUTO_SUBGRUPO_ID = P.PRODUTO_SUBGRUPO AND PG.PRODUTO_GRUPO_ID = PS.PRODUTO_GRUPO_ID
LEFT JOIN PRODUTOS_UNIDADES PU ON PU.PRODUTO_UN_ID = P.PRODUTO_UND
LEFT JOIN PRODUTOS_CST PC ON PC.PRODUTO_CST_ID = P.PRODUTO_CST
LEFT JOIN PRODUTOS_CFOP PC2 ON PC2.PRODUTO_CFOP_ID = P.PRODUTO_CFOP
LEFT JOIN PRODUTOS_MOD_PIS PMP ON PMP.PRODUTO_MOD_PIS_ID = P.PRODUTO_MOD_PIS 
LEFT JOIN PRODUTOS_MOD_COFINS PMC ON PMC.PRODUTO_MOD_COFINS_ID = P.PRODUTO_MOD_COFINS
LEFT JOIN PRODUTOS_MOD_IPI PMI ON PMI.PRODUTO_MOD_IPI_ID = P.PRODUTO_MOD_IPI