SELECT
    CLIENTE.CLI_ID AS CODIGO,
    CLIENTE.CLI_RAZAO_SOCIAL AS NOME,
    CLIENTE.CLI_NOME_FANTASIA AS FANTASIA,
    CLIENTE.CLI_CNPJ_CPF AS CNPJ_CNPF,
    CLIENTE.CLI_INSCRICAO_ESTADUAL_RG AS IE_RG,
    CLIENTE.CLI_ENDERECO AS ENDERECO,
    CLIENTE.CLI_BAIRRO AS BAIRRO,
    CIDADE.CID_NOME AS CIDADE,
    CIDADE.UFA_ID AS UF,
    CLIENTE.CLI_CEP AS CEP,
    CLIENTE.CLI_FONE_RESIDENCIAL AS TELEFONE,
    CLIENTE.CLI_FONE_CELULAR AS CELULAR,
    CLIENTE.CLI_FAX AS FAX,
    CLIENTE.CLI_EMAIL AS EMAIL,
    CLIENTE.CLI_LIMITE_CREDITO AS LIMITE_CREDITO,
    CLIENTE.CLI_INFORMACAO AS OBSERVACOES,
    CAST (CLIENTE.CLI_DATA_NASCIMENTO AS DATE) AS NASCIMENTO,
    CAST (CLIENTE.CLI_DATA_CADASTRO AS DATE) AS CADASTRO
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.CID_ID = CLIENTE.CID_ID
