SELECT
  PESSOA.CODIGOPESSOA AS CODIGO,
  PESSOA.NOME AS NOME,
  PESSOA.APELIDO AS FANTASIA,
  PESSOA.CPF AS CNPJ_CNPF,
  PESSOA.RG AS IE_RG,
  PESSOA.ENDERECO AS ENDERECO,
  PESSOA.NUMERO AS NUMERO,
  PESSOA.COMPLEMENTO AS COMPLEMENTO,
  PESSOA.BAIRRO AS BAIRRO,
  PESSOA.CEP AS CEP,
  MAX (PCT.CONTATO) AS TELEFONE,
  MAX(PCC.CONTATO) AS CELULAR,
  MAX (PCE.CONTATO) AS EMAIL,
  PESSOA_CIDADE.NOME AS CIDADE,
  PESSOA_CIDADE_UF.SIGLA AS UF,
  PESSOA.OBS AS OBSERVACOES
FROM PESSOA
LEFT JOIN PESSOA_CIDADE ON PESSOA_CIDADE.CODIGOCIDADE = PESSOA.CODIGOCIDADE
LEFT JOIN PESSOA_CIDADE_UF ON PESSOA_CIDADE_UF.CODIGOUF = PESSOA_CIDADE.CODIGOUF
--LEFT JOIN PESSOA_CONTATO ON PESSOA_CONTATO.CODIGOPESSOA = PESSOA.CODIGOPESSOA
LEFT JOIN PESSOA_CONTATO PCT ON PESSOA.CODIGOPESSOA = PCT.CODIGOPESSOA AND PCT.CODIGOTIPO = '2'
LEFT JOIN PESSOA_CONTATO PCC ON PESSOA.CODIGOPESSOA = PCC.CODIGOPESSOA AND PCC.CODIGOTIPO = '3'
LEFT JOIN PESSOA_CONTATO PCE ON PESSOA.CODIGOPESSOA = PCE.CODIGOPESSOA AND PCE.CODIGOTIPO = '4'
WHERE PESSOA.CODIGOTIPO = '3'
GROUP BY 1,2,3,4,5,6,7,8,9,10,14,15,16
