SELECT
  PRODUTO_BASE.CODIGOBASEPRODUTO AS CODIGO,
  PRODUTO_BASE.NOME AS DESCRICAO,
  PRODUTO_BASE.CODIGOBARRAS_PADRAO AS BARRAS,
  PRODUTO_UN.NOMEUN AS UND,
  PRODUTO.PESO AS PESO,
  PRODUTO_GRUPO.NOMEGRUPO AS GRUPO,
  PESSOA.NOME AS FORNECEDOR,
  PRODUTO_ESTOQUE.ESTOQUE AS QTD,
  PRODUTO_ESTOQUE.PRECOCUSTO AS PRECO_CUSTO,
  PRODUTO_ESTOQUE.CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTO_ESTOQUE_TABELA_PRECO.PRECO_VENDA AS PRECO_VENDA,
  substring (PRODUTO_ORIGEM.CODIGOORIGEM from 1 for 1) AS OST,
  PRODUTO_TRIBUTO.CSOSN AS ST,
  PRODUTO_BASE.OBS AS OBSERVACOES,
  PRODUTO_FORN_MERC.CODIGOPRODUTOFORNECEDOR AS COD_FABRICANTE,
  PRODUTO_BASE.NCM AS COD_NCM,
  PRODUTO_NCM_CEST.CEST AS PERSONAL6,
  CAST (PRODUTO.DATAHORACADASTRO AS DATE) AS DATA_CADASTRO
FROM PRODUTO_BASE
LEFT JOIN PRODUTO_ESTOQUE ON PRODUTO_ESTOQUE.CODIGOPRODUTO = PRODUTO_BASE.CODIGOBASEPRODUTO
LEFT JOIN PRODUTO ON PRODUTO.CODIGOPRODUTO = PRODUTO_BASE.CODIGOBASEPRODUTO
LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.CODIGOGRUPO = PRODUTO_BASE.CODIGOGRUPO
LEFT JOIN PRODUTO_NCM_CEST ON PRODUTO_NCM_CEST.CODIGOCEST = PRODUTO_BASE.CODIGOCEST
LEFT JOIN PRODUTO_ORIGEM ON PRODUTO_ORIGEM.CODIGOORIGEM = PRODUTO_BASE.CODIGOORIGEM
LEFT JOIN PRODUTO_TRIBUTO ON PRODUTO_TRIBUTO.CODIGOTRIBUTO = PRODUTO_BASE.CODIGOTRIBUTO
LEFT JOIN PRODUTO_FORN_MERC ON PRODUTO_FORN_MERC.CODIGOMERCADORIA = PRODUTO_BASE.CODIGOBASEPRODUTO
LEFT JOIN PRODUTO_UN ON PRODUTO_UN.CODIGOUN = PRODUTO_BASE.CODIGOUN
LEFT JOIN PRODUTO_ESTOQUE_TABELA_PRECO ON PRODUTO_ESTOQUE_TABELA_PRECO.CODIGO_MERCADORIA = PRODUTO_BASE.CODIGOBASEPRODUTO
LEFT JOIN PESSOA ON PESSOA.CODIGOPESSOA = PRODUTO_BASE.CODIGOFORNECEDOR
WHERE PRODUTO_ESTOQUE.codigoempresa = '1' and PRODUTO_ESTOQUE_TABELA_PRECO.CODIGO_TABELA_PRECO = '1'
--where PRODUTO_BASE.CODIGOBASEPRODUTO = '010576'