select
    COD_CLIENTE AS CODIGO,
    NOM_CLIENTE AS NOME,
    NOM_ENDERECO AS ENDERECO,
    NOM_COMPLEMENTOENDERECO AS COMPLEMENTO,
    NUM_CEP AS CEP,
    NUM_FONE AS TELEFONE,
    NOM_CIDADE AS CIDADE,
    NOM_UF AS UF,
    NUM_CIC_CGC AS CNPJ_CNPF,
    NOM_EMAIL AS EMAIL,
    NOM_BAIRRO AS BAIRRO,
    COALESCE(NUM_DDDCEL,'') ||COALESCE(NUM_FONECELULAR,'') AS CELULAR,
    NUM_ENDERECO AS NUMERO
FROM CLIENTE
