SELECT
    FORNECEDOR.CODFORNECEDOR AS CODIGO,
    FORNECEDOR.STRRAZAOSOCIAL AS NOME,
    FORNECEDOR.STRNOMEFANTASIA AS FANTASIA,
    FORNECEDOR.STRCPFCNPJ AS CNPJ_CNPF,
    FORNECEDOR.STRENDERECO AS ENDERECO,
    FORNECEDOR.INTNUMERO AS NUMERO,
    CIDADE.STRCIDADE AS CIDADE,
    BAIRRO.STRBAIRRO AS BAIRRO,
    FORNECEDOR.STRCOMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.STRCEP AS CEP,
    FORNECEDOR.STRFONE1 AS TELEFONE,
    FORNECEDOR.STRCONTATO AS CONTATO,
    FORNECEDOR.STREMAIL AS EMAIL,
    FORNECEDOR.STRINSCRICAOESTADUAL AS IE_RG
FROM FORNECEDOR
LEFT JOIN CIDADE ON FORNECEDOR.CODCIDADE = CIDADE.CODCIDADE
LEFT JOIN BAIRRO ON FORNECEDOR.CODBAIRRO = BAIRRO.CODBAIRRO
