SELECT
	C.CLIENTE_ID AS CODIGO,
	C.NOME_FANTASIA AS FANTASIA,
	C.RAZAO_SOCIAL AS NOME,
	C.CNPJ_CPF AS CNPJ_CNPF,
	C.IE_RG,
	C.IE_SUF AS SUFRAMA,
	C.ENDERECO,
	C.NUMERO,
	C.COMPLEMENTO,
	C.BAIRRO,
	C.CEP,
	C.TELEFONE1 AS TELEFONE,
	C.TELEFONE2 AS CELULAR,
	C.EMAIL,
	CAST (C.DATA_CADASTRO AS DATE) AS CADASTRO,
	C.DATA_NASCIMENTO AS NASCIMENTO,
	C.OBSERVACAO AS OBSERVACOES,
	C.CREDITO AS LIMITE_CREDITO,
	C.PONTO_REFERENCIA AS PERSONAL1,
	M.NOME AS CIDADE,
	M.UF 	
FROM
	CLIENTE C
LEFT JOIN MUNICIPIO M ON M.MUNICIPIO_ID = C.CODIGO_MUNICIPIO  		
	