SELECT 
  CLI_ID as CODIGO
,   case when CLI_CPF = '' or CLI_CPF is null then CLI_A_CNPJ_CPF else CLI_CPF END AS CNPJ_CNPF
,   case when CLI_RG = '' or CLI_RG is null then CLI_IE else CLI_RG END AS IE_RG
, CLI_NOME as NOME
, CLI_FANTASIA as FANTASIA
,   convert(DATE, CLI_DATA ,103) as CADASTRO
,   convert(DATE, CLI_NAS ,103) as NASCIMENTO
, CLI_TELEFONE1 as TELEFONE
, CLI_TELEFONE1CON as CELULAR
, CLI_TELEFONE2 as FAX
, CLI_ENDERECO as ENDERECO
, CLI_COMPLEMENTO as COMPLEMENTO
, CLI_BAIRRO as BAIRRO
, CLI_NUMERO as NUMERO
, CLI_CIDADE as CIDADE
, CLI_ESTADO as UF
, CLI_CEP as CEP
, CLI_EMAIL as EMAIL
, CLI_PROFISSAO as PROFISSAO
, CLI_LOCAL_DE_TRABALHO as LOCTRA
, CLI_CONJUGUE as CONJUGE
, CLI_NOME_DO_PAI as PAI
, CLI_NOME_DA_MAE as MAE
, CLI_OBSERVACOES as OBSERVACOES
, CLI_LIMITE_CREDITO as LIMITE_CREDITO
FROM CLIENTES
--WHERE LOJ_ID = '1'
