SELECT 
       CLIENTES.CODIGO AS CODIGO
      ,CAST (CLIENTES.DATA AS DATE) AS CADASTRO
      ,CLIENTES.NOME AS NOME
      ,CLIENTES.FANTASIA AS FANTASIA
      ,CLIENTES.CPF AS CNPJ_CNPF
      ,CLIENTES.RG AS IE_RG
      --,CLIENTES.NASC AS NASCIMENTO
      ,CLIENTES.SEXO AS SEXO
      ,CLIENTES.ENDERECO AS ENDERECO
      ,CLIENTES.NRO AS NUMERO
      ,CLIENTES.BAIRRO AS BAIRRO
      ,CLIENTES.CIDADE AS CIDADE
      ,CLIENTES.ESTADO AS UF
      ,CLIENTES.CEP AS CEP
      ,CLIENTES.TEL1 AS TELEFONE
      ,CLIENTES.FAX AS FAX
      ,CLIENTES.CELULAR AS CELULAR
      ,CLIENTES.EMAIL AS EMAIL
      ,CLIENTES.OBS AS OBSERVACOES
  FROM EZ_COMSQL.dbo.CLIENTES
  WHERE CLIENTES.CODIGO > '0';
