SELECT
       FORNECEDORES.CODIGO AS CODIGO
      ,FORNECEDORES.NOME AS NOME
      ,FORNECEDORES.FANTASIA AS FANTASIA
      ,FORNECEDORES.CPF AS CNPJ_CNPF
      ,FORNECEDORES.RG AS IE_RG
      ,FORNECEDORES.ENDERECO AS ENDERECO
      ,FORNECEDORES.NRO AS NUMERO
      ,FORNECEDORES.BAIRRO AS BAIRRO
      ,FORNECEDORES.CIDADE AS CIDADE
      ,FORNECEDORES.ESTADO AS UF
      ,FORNECEDORES.CEP AS CEP
      ,FORNECEDORES.TEL1 AS TELEFONE
      ,FORNECEDORES.FAX AS FAX
      ,FORNECEDORES.CELULAR AS CELULAR
      ,FORNECEDORES.EMAIL AS EMAIL
      ,FORNECEDORES.OBS AS OBSERVACOES
FROM EZ_COMSQL.dbo.FORNECEDORES
