SELECT
	CODPRO AS CODIGO,
	CODFABRICANTE AS COD_FABRICANTE,
	UNIPRO AS UND,
	NOMPRO AS DESCRICAO,
	GRUPO.NOMGRU AS GRUPO,
    SUBGRUPO.NOMSUB AS FAMILIA,
	"LOCAL" AS PERSONAL1,
	CODBARRAS AS BARRAS,
	PRECUSTO AS PRECO_CUSTO,
	MARGEMLUCRO AS MARGEM_LUCRO,
	PREVENDA AS PRECO_VENDA,
	SALDOEST AS QTD,
	FABRICANTE AS PERSONAL2,
	PESO AS PESO,
	SITTRIB AS ST,
	replace(RELACAO_NCM.CD_NCM, '.','') AS COD_NCM,
	CARACTERISTICAS AS CARACTERISTICAS,
	PRECUSTOMEDIO AS CUSTO_MEDIO,
	ID_PIS AS PIS_CODIGO,
	ID_COFINS AS COFINS_CODIGO,
	DT_CADASTRO AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN RELACAO_NCM ON PRODUTO.ID_NCM = RELACAO_NCM.ID_NCM 
LEFT JOIN GRUPO ON PRODUTO.CODGRU = GRUPO.CODGRU 
LEFT JOIN SUBGRUPO ON PRODUTO.CODSUB = SUBGRUPO.CODSUB 
