SELECT
  CLIEFORN.CODI AS CODIGO,
  CLIEFORN.NOME AS NOME,
  case when CLIEFORN.CNPJ ='' then CLIEFORN.CPF
  else CLIEFORN.CNPJ end as CNPJ_CNPF,
  case when CLIEFORN.INSC = '' or CLIEFORN.INSC is null then CLIEFORN.RG else CLIEFORN.INSC END AS IE_RG,
  CLIEFORN.ENDE AS ENDERECO,
  CLIEFORN.FONE AS TELEFONE,
  CLIEFORN.BAIR AS BAIRRO,
  CLIEFORN.CIDA AS CIDADE,
  CLIEFORN.UF AS UF,
  CLIEFORN.CEP AS CEP,
  CLIEFORN.MAIL AS EMAIL,
  CLIEFORN.OBS AS OBSERVACOES,
  CLIEFORN.COMP AS COMPLEMENTO,
  CLIEFORN.FONE2 AS CELULAR,
  CLIEFORN.FAX AS FAX,
  CLIEFORN.NOME_FANT AS FANTASIA,
  CLIEFORN.NOME_CONTATO AS CONTATO
FROM CLIEFORN
WHERE CLIEFORN.TIPOCAD = 'F'
