SELECT
    EMPRESAS.EMP_ID AS CODIGO,
    EMPRESAS.EMP_DOCUMENTO01 AS CNPJ_CNPF,
    EMPRESAS.EMP_DOCUMENTO02 AS IE_RG,
    EMPRESAS.EMP_NOME01 AS NOME,
    EMPRESAS.EMP_NOME02 AS FANTASIA,
    EMPRESAS.EMP_ENDERECO AS ENDERECO,
    EMPRESAS.EMP_NUMERO AS NUMERO,
    EMPRESAS.EMP_BAIRRO AS BAIRRO,
    EMPRESAS.EMP_COMPLEMENTO AS COMPLEMENTO,
    CIDADES.CID_NOME AS CIDADE,
    CIDADES.CID_ESTADO AS UF,
    EMPRESAS.EMP_CEP AS CEP,
    EMPRESAS.EMP_TELEFONE AS TELEFONE,
    EMPRESAS.EMP_EMAIL AS EMAIL
FROM EMPRESAS
LEFT JOIN CIDADES ON CIDADES.CID_ID = EMPRESAS.EMP_IDCIDADE
