SELECT
    PRO_ID AS CODIGO,
    PRO_UNIDADE AS UND,
    PRO_CODIGOBARRAS AS BARRAS,
    PRO_DESCRICAO AS DESCRICAO,
    PRO_NCM AS COD_NCM,
    PRO_CEST AS PERSONAL6,
    PRO_ORIGEM AS OST,
    PRO_SITTRIB AS ST,
    PRO_VALORCUSTO AS PRECO_CUSTO,
    PRO_VALORVISTA AS PRECO_VENDA,
    PRO_ESTOQUE AS QTD
FROM PRODUTOS
