SELECT
  PRODUTOS.PRO_CODIGO AS COIGO,
  PRODUTOS.PRO_BARRAS AS BARRAS,
  PRODUTOS.PRO_DESCRI AS DESCRICAO,
  PRODUTOS.PRO_UN AS UND,
  PRODUTOS.PRO_PESO AS PESO,
  SECOES.SEC_DESCRI AS GRUPO,
  MARCAS.MAR_DESCRI AS CARACTERISTICAS,
  PRODUTOS.PRO_PRECO1 AS PRECO_VENDA,
  PRODUTOS.PRO_ESTOQUE0 AS QTD,
  PRODUTOS.PRO_EST_MIN AS QTD_IDEAL,
  PRODUTOS.PRO_DT_ULT_C AS ULTIMA_COMPRA,
  PRODUTOS.PRO_DT_ULT_V AS ULTIMA_VENDA,
  FORNECEDORES.FOR_NOME AS FORNECEDOR,
  PRODUTOS.PRO_CADASTRO AS DATA_CADASTRO,
  PRODUTOS.PRO_CODSITTRIB AS ST,
  PRODUTOS.PRO_CODNCM AS COD_NCM,
  PRODUTOS.PRO_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON FORNECEDORES.FOR_CODIGO = PRODUTOS.pro_fornecedor
LEFT JOIN SECOES ON SECOES.SEC_CODIGO = PRODUTOS.PRO_SECAO
LEFT JOIN MARCAS ON MARCAS.MAR_CODIGO = PRODUTOS.PRO_MARCA
