SELECT PAR.PLAPAR AS CODIGO,
PAR.NM1PAR AS NOME,
PAR.NM2PAR AS FANTASIA,
PAR.DC1PAR AS CNPJ_CNPF,
PAR.DC2PAR AS IE_RG,
PAR.ENDPAR AS ENDERECO,
PAR.NUMPAR AS NUMERO,
PAR.BAIPAR AS BAIRRO,
PAR.CPLPAR AS COMPLEMENTO,
PAR.CEPPAR AS CEP,
CID.NOMCID AS CIDADE,
EST.SIGEST AS UF,
PAR.TELPAR AS TELEFONE,
PAR.CELPAR AS CELULAR,
PAR.FAXPAR AS FAX,
PAR.EMLPAR AS EMAIL,
CAST(PAR.DTCPAR AS DATE) AS CADASTRO
FROM PAR
LEFT JOIN CID ON PAR.CIDPAR=CID.CODCID
LEFT JOIN EST ON CID.ESTCID=EST.CODEST
JOIN FRN ON PAR.PLAPAR=FRN.PARFRN
WHERE PAR.PLAPAR >0
