sELECT
  CLIENTE.XCODIGO AS CODIGO,
  CLIENTE.XNOME AS NOME,
  CLIENTE.XNOMEUSUAL AS FANTASIA,
  CLIENTE.XCPF_CNPJ AS CNPJ_CNPF,
  CLIENTE.XRG_IE AS IE_RG,
  CLIENTE.XLOGRADOURO AS ENDERECO,
  CLIENTE.XNUMIMOVEL AS NUMERO,
  CLIENTE.XCOMPENDERECO AS COMPLEMENTO,
  CLIENTE.XBAIRRO AS BAIRRO,
  LOCALIDADE.NOME AS CIDADE,
  UF.SIGLA AS UF,
  CLIENTE.XCEP AS CEP,
  CLIENTE.XTELEFONE AS TELEFONE,
  CLIENTE.XFAX AS FAX,
  CLIENTE.XCELULAR AS CELULAR,
  CLIENTE.XEMAIL AS EMAIL,
  CLIENTE.XDATANASC AS NASCIMENTO,
  CLIENTE.XSEXO AS SEXO,
  CLIENTE.XPAI AS PAI,
  CLIENTE.XMAE AS MAE,
  CLIENTE.XESTCIVIL AS EST_CIVIL,
  CLIENTE.XCONJUGE AS CONJUGE,
  CLIENTE.XLIMITE AS LIMITE_CREDITO,
  CLIENTE.XOBS AS OBSERVACOES,
  CLIENTE.XDATACAD AS CADASTRO
FROM CLIENTE
LEFT JOIN LOCALIDADE ON LOCALIDADE.ID = CLIENTE.xLOCALIDADE_ID
LEFT JOIN UF ON UF.ID = LOCALIDADE.UF_ID
