SELECT
    FORNECEDOR.XCODIGO AS CODIGO,
    FORNECEDOR.XNOME AS NOME,
    FORNECEDOR.XNOMEUSUAL AS FANTASIA,
    FORNECEDOR.XCPF_CNPJ AS CNPJ_CNPF,
    FORNECEDOR.XRG_IE AS IE_RG,
    FORNECEDOR.XLOGRADOURO AS ENDERECO,
    FORNECEDOR.XNUMIMOVEL AS NUMERO,
    FORNECEDOR.XCOMPENDERECO AS COMPLEMENTO,
    FORNECEDOR.XBAIRRO AS BAIRRO,
    LOCALIDADE.NOME AS CIDADE,
    UF.SIGLA AS UF,
    FORNECEDOR.XCEP AS CEP,
    FORNECEDOR.XTELEFONE AS TELEFONE,
    FORNECEDOR.XFAX AS FAX,
    FORNECEDOR.XCELULAR AS CELULAR,
    FORNECEDOR.XEMAIL AS EMAIL
FROM FORNECEDOR
LEFT JOIN LOCALIDADE ON LOCALIDADE.ID = FORNECEDOR.xLOCALIDADE_ID
LEFT JOIN UF ON UF.ID = LOCALIDADE.UF_ID
