select
    cliente.codigo as codigo,
    cliente.nome as fantasia,
    cliente.razao as nome,
    cliente.contato as contato,
    cliente.endereco as endereco,
    cliente.complemento as complemento,
    cliente.numero_logradouro as numero,
    cliente.bairro as bairro,
    cliente.cidade as cidade,
    cliente.estado as uf,
    cliente.cep as cep,
    cliente.fone as telefone,
    cliente.fax as fax,
    cliente.celular as celular,
    cliente.email as email,
    case when cliente.rg = '' or cliente.rg is null then cliente.inscest else cliente.rg END AS IE_RG,
    case when cliente.cpf = '' or cliente.cpf is null then cliente.cnpj else cliente.cpf END AS CNPJ_CNPF,
    --cliente.data_cadastro as cadastro,
    cliente.limite_credito as limite_credito,
    cliente.nascimento as nascimento,
    cliente.pai as pai,
    cliente.mae as mae,
    cliente.observacao as observacoes
from cliente
