SELECT 
  C.ID AS CODIGO
, C.RAZAO_SOCIAL AS NOME
, C.NOME_FANTASIA AS FANTASIA
, CASE WHEN C.CPF = '' OR C.CPF IS NULL THEN C.CPF_CNPJ ELSE C.CPF END AS CNPJ_CNPF
, C.IE_RG
, C.RUA AS ENDERECO
, C.COMPLEMENTO
, C.NUMERO
, C.BAIRRO
, C.TELEFONE
, C.CELULAR
, C.EMAIL
, C.CEP
, C.LIMITE_VENDA AS LIMITE_CREDITO
, C.NASCIMENTO
, C.OBSERVACAO AS OBSERVACOES
, C.RUA_COBRANCA AS COB_ENDERECO
, C.NUMERO_COBRANCA AS COB_NUMERO
, C.BAIRRO_COBRANCA AS COB_BAIRRO
, C.CEP_COBRANCA AS COB_CEP
, CI.NOME AS CIDADE
, CI.UF
, CID.NOME AS COB_CIDADE
, CID.UF AS COB_UF
FROM CLIENTES C
LEFT JOIN CIDADES CI ON CI.ID = C.CIDADE_ID
LEFT JOIN CIDADES CID ON CID.ID = C.CIDADE_COBRANCA_ID
