 SELECT
    CLIENTES.CODIGO AS CODIGO,
    CLIENTES.NOME AS NOME,
    CLIENTES.RAZAO_SOCIAL AS FANTASIA,
    CLIENTES.CPF AS CNPJ_CNPF,
    CLIENTES.RG AS IE_RG,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.NUMERO AS NUMERO,
    CLIENTES.BAIRRO AS BAIRRO,
    CIDADES.nome AS CIDADE,
    CIDADES.uf AS UF,
    CLIENTES.CEP AS CEP,
    CLIENTES.TELEFONE AS TELEFONE,
    CLIENTES.CELULAR AS CELULAR,  
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.LIMITE AS LIMITE_CREDITO,
    CLIENTES.OBS AS OBSERVACOES,
    CLIENTES.PAI AS PAI,
    CLIENTES.MAE AS MAE,
    CLIENTES.CONJUGE AS CONJUGE, 
    CLIENTES.SEXO AS SEXO, 
    CLIENTES.DATANASC AS NASCIMENTO
FROM CLIENTES
LEFT JOIN CIDADES ON CIDADES.codigo = CLIENTES.COD_CIDADE
