SELECT 
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.NOME AS DESCRICAO,
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.MINIMO AS QTD_IDEAL,
    PRODUTOS.CUSTO AS PRECO_CUSTO,
    PRODUTOS.MARGENS AS MARGEM_LUCRO,
    PRODUTOS.VENDA AS PRECO_VENDA,
    PRODUTOS.PRECO_PROMOCAO AS PRECO_ATACADO,
    PRODUTOS.CST AS ST,
    CLASSE.nome AS GRUPO,
    PRODUTOS.DATA_CADATRO AS DATA_CADASTRO,
    PRODUTOS.DATA_UTLALTERAC AS ALTERACAO_PRECO,
    PRODUTOS.DATA_UTLVENDA AS ULTIMA_VENDA,
    PRODUTOS.DATA_ULTCOMPRA AS ULTIMA_COMPRA,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN CLASSE ON CLASSE.tipo = PRODUTOS.classe
