SELECT
  CADFOR.CODFOR AS CODIGO,
  CADFOR.IE AS IE_RG,
  CADFOR.RAZAO AS NOME,
  CADFOR.NOMEFANTASIA AS FANTASIA,
  CADFOR.ENDERECO AS ENDERECO,
  CADFOR.BAIRRO AS BAIRRO,
  CADFOR.PTREFERENCIA AS COMPLEMENTO,
  CADFOR.CEP AS CEP,
  CADFOR.CIDADE AS CIDADE,
  CADFOR.TELEFONE AS TELEFONE,
  CADFOR.FAX AS FAX,
  CADFOR.ESTADO AS UF,
  CADFOR.EMAIL AS EMAIL,
  CADFOR.OBS AS OBSERVACOES,
  CADFOR.CELULAR AS CELULAR,
  CADFOR.CGC AS CNPJ_CNPF,
  CADFOR.CONTATO AS CONTATO
FROM CADFOR
