SELECT 
       CLIENTE.COD_CLIENTE AS CODIGO
      ,CAST (CLIENTE.DTA_CADASTRO AS DATE) AS CADASTRO
      ,CLIENTE.RAZAO_SOCIAL_NOME AS NOME
      ,CLIENTE.NOME_FANTASIA_APELIDO AS FANTASIA
      ,CLIENTE.CNPJ_CPF AS CNPJ_CNPF
      ,case when CLIENTE.INSC_ESTADUAL = '' or CLIENTE.INSC_ESTADUAL is null then CLIENTE.RG else CLIENTE.INSC_ESTADUAL END AS IE_RG
      ,CLIENTE.LOGRADOURO AS ENDERECO
      ,CLIENTE.NRO_LOGRADOURO AS NUMERO
      ,CLIENTE.CPL_LOGRADOURO AS COMPLEMENTO
      ,CLIENTE.BAIRRO AS BAIRRO
      ,MUNICIPIO.MUNICIPIO AS CIDADE
      ,MUNICIPIO.UF AS UF
      ,CLIENTE.CEP AS CEP
      ,CLIENTE.FONE1 AS TELEFONE
      ,CLIENTE.CELULAR_FAX AS CELULAR
      ,CLIENTE.EMAIL AS EMAIL
      ,CLIENTE.OBS AS OBSERVACOES
      ,CLIENTE.CONTATO AS CONTATO
  FROM DATAMANAGER.dbo.CLIENTE
LEFT JOIN DATAMANAGER.dbo.MUNICIPIO ON MUNICIPIO.COD_LOCALIDADE = CLIENTE.COD_LOCALIDADE