SELECT 
       FORNECEDOR.COD_FORNECEDOR AS CODIGO
      ,FORNECEDOR.RAZAO_SOCIAL_NOME AS NOME
      ,FORNECEDOR.NOME_FANTASIA_APELIDO AS FANTASIA
      ,FORNECEDOR.CNPJ_CPF AS CNPJ_CNPF
      ,case when FORNECEDOR.INSC_ESTADUAL = '' or FORNECEDOR.INSC_ESTADUAL is null then FORNECEDOR.RG else FORNECEDOR.INSC_ESTADUAL END AS IE_RG
      ,FORNECEDOR.LOGRADOURO AS ENDERECO
      ,FORNECEDOR.NRO_LOGRADOURO AS NUMERO
      ,FORNECEDOR.CPL_LOGRADOURO AS COMPLEMENTO
      ,FORNECEDOR.BAIRRO AS BAIRRO
      ,MUNICIPIO.MUNICIPIO AS CIDADE
      ,MUNICIPIO.UF AS UF
      ,FORNECEDOR.CEP AS CEP
      ,FORNECEDOR.FONE AS TELEFONE
      ,FORNECEDOR.FAX AS FAX
      ,FORNECEDOR.EMAIL AS EMAIL
      ,FORNECEDOR.OBS AS OBSERVACOES
  FROM DATAMANAGER.dbo.FORNECEDOR
  LEFT JOIN DATAMANAGER.dbo.MUNICIPIO ON MUNICIPIO.COD_LOCALIDADE = FORNECEDOR.COD_LOCALIDADE