SELECT 
       PRODUTOS.COD_PRODUTO AS CODIGO
      ,PRODUTOS.COD_BARRA AS BARRAS
      ,PRODUTOS.DESCRICAO AS DESCRICAO
      ,CATEGORIA.DESCRICAO AS GRUPO
      ,SUBCATEGORIA.DESCRICAO AS FAMILIA
      ,MARCAS.DESCRICAO AS CARACTERISTICAS
      ,PRODUTOS.COD_GRUPO_PRODUTO
      ,UNIDADE.SIGLA AS UND
      ,UNIDADE.SIGLA AS UND_COMPRA
      ,PRODUTOS.ESTOQUE_MIN AS QTD_IDEAL
      ,PRODUTOS.ESTOQUE AS QTD
      ,PRODUTOS.PC_CUSTO AS PRECO_CUSTO
      ,PRODUTOS.IND_LUCRO_LIQ AS MARGEM_LUCRO
      ,PRODUTOS.PC_VENDA AS PRECO_VENDA
      ,PRODUTOS.PC_ATACADO AS PRECO_ATACADO
      ,PRODUTOS.CSOSN AS ST
      ,PRODUTOS.NCM AS COD_NCM
      ,PRODUTOS.CEST AS PERSONAL6
      ,CAST (PRODUTOS.DAT_CADASTRO AS DATE) AS DATA_CADASTRO
      ,CAST (PRODUTOS.DTA_ULT_COMPRA AS DATE) AS ULTIMA_COMPRA
      ,CAST (PRODUTOS.DTA_ULT_VENDA AS DATE) AS ULTIMA_VENDA
  FROM DATAMANAGER.dbo.PRODUTOS
  LEFT JOIN DATAMANAGER.dbo.SUBCATEGORIA ON SUBCATEGORIA.COD_SUBCATEGORIA = PRODUTOS.COD_SUB_CATEGORIA 
  LEFT JOIN DATAMANAGER.dbo.CATEGORIA ON CATEGORIA.COD_CATEGORIA = SUBCATEGORIA.COD_CATEGORIA 
  LEFT JOIN DATAMANAGER.dbo.MARCAS ON MARCAS.CODIGO = PRODUTOS.COD_MARCA
  LEFT JOIN DATAMANAGER.dbo.UNIDADE ON UNIDADE.COD_UNIDADE = PRODUTOS.COD_UNIDADE