SELECT
    SUBSTRING(CODCFO FROM 2 FOR 6) AS CODIGO,
    NOMEFANTASIA AS FANTASIA,
    NOME AS NOME,
    CGCCFO AS CNPJ_CNPF,
    INSCRESTADUAL AS IE_RG,
    RUA AS ENDERECO,
    NUMERO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    CODETD AS UF,
    CEP,
    TELEFONE,
    FAX,
    EMAIL
    from FCFO
WHERE TIPO = 'F'
