SELECT
    FLAN.IDLAN || ' '||    FLAN.NUMERODOCUMENTO AS DOCUMENTO,
    SUBSTRING(FLAN.CODCFO from 2 FOR 6) AS COD_CLIENTE,
    FCFO.nome AS NOM_CLIENTE,
    FLAN.PARCELA AS NUM_PARCELA,
    FLAN.PAGREC,
    FLAN.DATAVENCIMENTO AS VENCIMENTO,
    FLAN.DATAEMISSAO AS EMISSAO,
    FLAN.DATABAIXA AS RECEBIMENTO,
    FLAN.HISTORICO,
    FLAN.VALORORIGINAL AS VALOR_DUP,
    FLAN.VALORBAIXADO AS VALOR_REC,
    FCFO.cgccfo AS CNPJ
FROM FLAN
LEFT JOIN FCFO ON FLAN.codcfo = FCFO.codcfo
WHERE FLAN.PAGREC = 'R'
