SELECT CADASTRO.a06_codig AS CODIGO,
CADASTRO.a06_dm AS CADASTRO,
CADASTRO.a06_NOME AS NOME,
CADASTRO.A06_FANTA AS FANTASIA,
CASE WHEN CADASTRO.a06_cnpj='' THEN CADASTRO.a06_cpf 
ELSE CADASTRO.a06_cnpj END AS CNPJ_CNPF,
CADASTRO.A06_IE AS IE_RG,
CADASTRO.a06_fone AS TELEFONE,
CADASTRO.A06_CEL AS CELULAR,
CADASTRO.A06_FAX AS FAX,
CADASTRO.A06_EMAIL AS EMAIL,
CADASTRO.a06_end AS ENDERECO,
CADASTRO.a06_bairr AS BAIRRO,
cidade.b03_nome AS CIDADE,
CIDADE.b03_uf AS UF,
CADASTRO.A06_CEP AS CEP,
CADASTRO.a06_numero AS NUMERO
FROM CADASTRO
LEFT JOIN cidADE ON CADASTRO.a06_cid=CIDADE.b03_codig
WHERE CADASTRO.a06_cli='S'




