SELECT
  CONTATOS.CODIGO AS CODIGO,
  CONTATOS.NOME AS NOME,
  CONTATOS.FONEPRINCIPAL AS TELEFONE,
  CONTATOS.FONECELULAR AS CELULAR,
  CONTATOS.ENDERECO AS ENDERECO,
  CONTATOS.BAIRRO AS BAIRRO,
  CONTATOS.CIDADE AS CIDADE,
  CONTATOS.CEP AS CEP,
  CONTATOS.UF AS UF,
  CONTATOS.EMAIL AS EMAIL,
  CONTATOS.CNPJOUCPF AS CNPJ_CNPF,
  CONTATOS.RGOUIE AS IE_RG,
  CONTATOS.DATANASCIMENTO AS NASCIMENTO,
  CONTATOS.SEXO AS SEXO,
  CONTATOS.COMPLEMENTO AS COMPLEMENTO,
  CONTATOS.NUMERO AS NUMERO
FROM CONTATOS
