SELECT
    CODIGO AS CODIGO,
    NOME AS FANTASIA,
    FONEPRINCIPAL AS TELEFONE,
    ENDERECO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    CEP,
    UF,
    EMAIL,
    CNPJOUCPF AS CNPJ_CNPF,
    RGOUIE AS IE_RG,
    NUMERO,
    RAZAOSOCIAL AS NOME
FROM FORNECEDORES
