SELECT
    ESTOQUE.ID AS CODIGO,
    ESTOQUE.EAN13 AS BARRAS,
    ESTOQUE.DESCRICAO AS DESCRICAO,
    CATEGORIA.DESCRICAO AS GRUPO,
    ESTOQUE.UNIDADE AS UND,
    ESTOQUE.QUANTIDADE AS QTD,
    ESTOQUE.FORNECEDOR AS FORNECEDOR,
    ESTOQUE.CUSTO AS PRECO_CUSTO,
    ESTOQUE.CUSTOMEDIO AS CUSTO_MEDIO,
    ESTOQUE.PERCENTUAL AS MARGEM_LUCRO,
    ESTOQUE.VALOR AS PRECO_VENDA,
    ESTOQUE.CODIGO AS COD_FABRICANTE,
    ESTOQUE.DATA_INC AS DATA_CADASTRO,
    ESTOQUE.DATA_ALT AS ALTERACAO_PRECO,
    ESTOQUE.NCM AS COD_NCM,
    ESTOQUE.CSOSN AS ST, 
    ESTOQUE.CEST AS PERSONAL6
FROM ESTOQUE
LEFT JOIN CATEGORIA ON CATEGORIA.ID = ESTOQUE.CATEGORIA
