SELECT
    CR.C_RECEBER_ID AS ID,
    CR.DOC AS DOCUMENTO,
    CR.C_RECEBER_ID || CR.DOC AS HISTORICO,
    CAST (CR.DT_VENC AS DATE) AS VENCIMENTO,
    FC.DESCRICAO AS TIPO_DOC,
    P.COD_PESSOA AS COD_CLIENTE,
    P.NOME AS NOM_CLIENTE,
    CR.VALOR AS VALOR_DUP,
    MAX (CRM.DESCONTO) AS VALOR_DES,
    MAX (CRM.JUROS) AS VALOR_JUR,
    CR.TOTAL_PAGAMENTOS AS VALOR_REC,
    CAST (CR.DT_LANCAMENTO AS DATE) AS RECEBIMENTO,
    FC.DESCRICAO AS ESPECIE,
    CR.COD_PLANO,
    CR.OBS AS OBSERVACOES,
    1 AS NUM_CONTA,
    1 AS NUM_PARCELA
FROM C_RECEBER AS CR
LEFT JOIN FORMAS_REC FC ON CR.COD_FORMA_REC = FC.COD_FORMA_REC
LEFT JOIN PESSOA P ON CR.COD_PESSOA = P.COD_PESSOA
LEFT JOIN C_REC_MOV CRM ON CR.C_RECEBER_ID = CRM.C_RECEBER_ID
WHERE CR.DOC <> ''
GROUP BY 1,2,3,4,5,6,7,8,11,12,13,14,15,16,17
