SELECT
    CLIENTES.CLI_CODIGO AS CODIGO,
    MAX(CLIENTES.CLI_NOME) AS NOME,
    MAX(CLIENTES.CLI_NOME_FANTASIA) AS FANTASIA,
    MAX(CLIENTES.CLI_TELEFONE) AS TELEFONE,
    MAX(CLIENTES.CLI_ENDERECO) AS ENDERECO,
    MAX(CLIENTES.CLI_CIDADE) AS CIDADE,
    MAX(CLIENTES.CLI_DATA_NASC::DATE) AS NASCIMENTO,
    MAX(ESTADO.DESCRICAO) AS UF,
    MAX(CLIENTES.CLI_BAIRRO) AS BAIRRO,
    MAX(CLIENTES.CLI_CEP) AS CEP,
    MAX(CLIENTES.CLI_CNPJ_CPF) AS CNPJ_CNPF,
    MAX(CLIENTES.CLI_INSC_EST) AS IE_RG,
    MAX(CLIENTES.CLI_COMPLEMENTO) AS COMPLEMENTO,
    MAX(CLIENTES.CLI_EMAIL) AS EMAIL,
    MAX(CLIENTES.CLI_CELULAR) AS CELULAR,
    MAX(CLIENTES.CLI_NUMERO) AS NUMERO
FROM CLIENTES
LEFT JOIN ESTADO ON CLIENTES.ES_CODIGO = ESTADO.ES_CODIGO
GROUP BY CLIENTES.CLI_CODIGO;