SELECT 
  FORNECEDOR.FOR_CODIGO AS CODIGO
, MAX(FORNECEDOR.FOR_NOMEFANTASIA) AS FANTASIA
, MAX(FORNECEDOR.FOR_NOME) AS NOME
, MAX(FORNECEDOR.FOR_TELEFONE) AS TELEFONE
, MAX(FORNECEDOR.FOR_FAX) AS FAX
, MAX(FORNECEDOR.FOR_ENDERECO) AS ENDERECO
, MAX(FORNECEDOR.FOR_NUMERO) AS NUMERO
, MAX(FORNECEDOR.FOR_BAIRRO) AS BAIRRO
, MAX(FORNECEDOR.FOR_CEP) AS CEP 
, MAX(FORNECEDOR.FOR_CNPJ) AS CNPJ_CNPF
, MAX(FORNECEDOR.FOR_INSCRICAO) AS IE_RG
, MAX(FORNECEDOR.FOR_CIDADE) AS CIDADE
, MAX(FORNECEDOR.FOR_COMPLEMENTO) AS COMPLEMENTO
, MAX(ESTADO.DESCRICAO) AS UF
FROM FORNECEDOR
LEFT JOIN ESTADO ON FORNECEDOR.ES_CODIGO = ESTADO.ES_CODIGO
GROUP BY FORNECEDOR.FOR_CODIGO;