select TB_MERCADORIA.CD_MERCADORIA as codigo,
TB_GRUPO.DS_GRUPO as grupo,
TB_MERCADORIA.DS_MERCADORIA as descricao,
TB_MERCADORIA.DS_MARCA as caracteristicas,
TB_MERCADORIA.DS_REFERENCIA as cod_fabricante,
TB_MERCADORIA.CD_UNIDADE_COMPRA as und_compra,
TB_MERCADORIA.CD_UNIDADE_VENDA as und,
TB_MERCADORIA.CD_BARRAS as barras,
TB_MERCADORIA.OBSERVACAO as observacoes,
TB_MERCADORIA.CD_SITUACAO_TRIBUTARIA as st,
TB_MERCADORIA.DS_NCM as cod_ncm,
TB_MERCADORIA.CEST as personal6,
tb_estoque.NR_QTDE_ESTOQUE as qtd,
TB_LIVRO_PRECOS.VL_CUSTO_AQUISICAO as preco_custo,
TB_LIVRO_PRECOS.VL_PRECO_VENDA as preco_venda
from TB_MERCADORIA
left join tb_grupo on TB_MERCADORIA.CD_GRUPO=tb_grupo.CD_GRUPO
left join tb_estoque on TB_MERCADORIA.CD_MERCADORIA=tb_estoque.CD_MERCADORIA
left join TB_LIVRO_PRECOS on TB_MERCADORIA.CD_MERCADORIA=TB_LIVRO_PRECOS.CD_MERCADORIA
