SELECT 
  E.ID_EMPRESA AS CODIGO
, E.NOME
, E.NOME_FANTASIA AS FANTASIA
, E.CNPJ AS CNPJ_CNPF
, IM
, CASE WHEN RG = '' OR RG IS NULL THEN IE ELSE RG END AS IE_RG
, E.ENDERECO
, E.ENDERECO_COMPLEMENTO AS COMPLEMENTO
, E.ENDERECO_NUMERO AS NUMERO
, E.BAIRRO
, E.CEP
, E.TELEFONE
, E.TELEFONE2 AS PERSONAL1
, E.FAX
, E.EMAIL
, E.CELULAR
, E.CONTATO
, E.OBSERVACOES
, C.CIDADE 
, C.UF 
FROM TEMPRESAS E
LEFT JOIN TCIDADES C ON C.ID_CIDADE = E.ID_CIDADE
WHERE E.ID_EMPRESA <> 0
