SELECT
    TPRODUTOS.CODIGO AS COD_FABRICANTE,
    TPRODUTOS.CODIGO_BARRAS AS BARRAS,
    TPRODUTOS.DESCRICAO AS DESCRICAO,
    TPRODUTOS.UNIDADE AS UND,
    TGRUPOS_PRODUTOS.DESCRICAO AS GRUPO,
    TPRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    TPRODUTOS.ESTOQUE AS QTD,
    TPRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    TPRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    TPRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    TPRODUTOS.OBSERVACAO AS OBSERVACOES,
    TPRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    TPRODUTOS.NCM AS COD_NCM,
    TPRODUTOS.ORIGEM_MERCADORIA AS OST,
    CASE WHEN TPRODUTOS.CSOSN = '' OR TPRODUTOS.CSOSN IS NULL THEN TPRODUTOS.CST ELSE TPRODUTOS.CSOSN END AS ST,
    TPRODUTOS.CEST AS PERSONAL6,
    TPRODUTOS.CST_PIS AS PIS_CODIGO,
    TPRODUTOS.CST_COFINS AS COFINS_CODIGO,
    TPRODUTOS.PIS AS PIS_ALIQ_NOR,
    TPRODUTOS.COFINS AS COFINS_ALIQ_NOR,
    LEFT (TCFOP.CODIGO,3) AS ELO,
    CASE  TPRODUTOS.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
FROM TPRODUTOS 
LEFT JOIN TGRUPOS_PRODUTOS ON TGRUPOS_PRODUTOS.ID_GRUPO_PRODUTO = TPRODUTOS.ID_GRUPO_PRODUTO
LEFT JOIN TCFOP ON TCFOP.ID_CFOP =  TPRODUTOS.ID_CFOP 
