SELECT
	P.PRO_CODIGO AS CODIGO,
	P.PRO_CODIGO AS PERSONAL1,	-- ADICIONADO CÓDIGO AO PERSONAL1 A PEDIDO DO CLIENTE
	P.PRO_NOME AS DESCRICAO,
	P.PRO_QUANTIDADE AS QTD,
	P.PRO_PRECOCUSTO AS PRECO_CUSTO,
	P.PRO_MARGEM AS MARGEM_LUCRO,	
	P.PRO_PRECOVENDA AS PRECO_VENDA,
	P.PRO_ESTOQUEMIN AS QTD_IDEAL,
	CAST (P.PRO_DATACADASTRO AS DATE) AS DATA_CADASTRO,
	P.PRO_CODIGOBARRA AS BARRAS,
	P.PRO_TAMANHO AS TAMANHO,
	P.PRO_COMISSAO AS COMISSAO,
	P.TIPOPRODUTO AS PERSONAL2,
	G.GRU_DESCRICAO AS GRUPO,
	SG.SG_DESCRICAO AS FAMILIA,
	U.UNI_DESCRICAO AS UND,
	M.MAR_DESCRICAO AS PERSONAL4,
	F.FOR_RAZAOSOCIAL AS FORNECEDOR,
	C.CAT_DESCRICAO AS CARACTERISTICAS
FROM
	PRODUTOS P
	LEFT JOIN GRUPO G ON G.GRU_CODIGO = P.PRO_GRUPO 
	LEFT JOIN SUBGRUPO SG ON SG.SG_CODIGO = P.PRO_SUBGRUPO AND G.GRU_CODIGO = SG.SG_GRUPO 
	LEFT JOIN UNIDADES U ON U.UNI_CODIGO = P.PRO_UNIDADE 
	LEFT JOIN MARCAS M ON M.MAR_CODIGO = P.PRO_MARCA 
	LEFT JOIN FORNECEDORES F ON F.FOR_CODIGO = P.PRO_FORNECEDOR 
	LEFT JOIN CATEGORIA C ON C.CAT_CODIGO = P.PRO_CATEGORIA 
