SELECT
    TPRODUTO.CODIGO AS CODIGO,
    TPRODUTO.DESCRICAO AS DESCRICAO,
    TGRUPO.DESCRICAO AS GRUPO,
    TPRODUTO.UNIDADE AS UND,
    TPRODUTO.VALORVENDA AS PRECO_VENDA,
    TPRODUTO.VALORCOMPRA AS PRECO_CUSTO,
    TPRODUTO.SAIDAESTOQUE AS QTD,
    TPRODUTO.ALIQUOTA AS ST,
    TPRODUTO.OBSERVACAO AS OBSERVACOES,
    TPRODUTO.CODFABRICANTE AS COD_FABRICANTE,
    TPRODUTO.CODBARRA AS BARRAS,
    TPRODUTO.ESTMINIMO AS QTD,
    TPRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    TNCM.ID AS COD_NCM
FROM TPRODUTO
LEFT JOIN TNCM ON TNCM.CODIGO = TPRODUTO.NCM
LEFT JOIN TGRUPO ON TGRUPO.ID = TPRODUTO.GRUPO