SELECT 
  H.ID_HOSPEDE AS CODIGO
, H.NOME
, H.CPF AS CNPJ_CNPF
, H.RG AS IE_RG
, H.ENDERECO
, H.ENDERECO_COMPLEMENTO AS COMPLEMENTO
, H.ENDERECO_NUMERO AS NUMERO
, H.BAIRRO
, H.CEP
, H.TELEFONE
, H.FAX
, H.EMAIL
, H.CELULAR
, H.ESTADO_CIVIL AS EST_CIVIL
, H.CONJUGE
, H.PROFISSAO
, H.OBSERVACOES
, H.DATA_NASCIMENTO AS NASCIMENTO
--, H.DATA_CADASTRO AS CADASTRO
, H.SEXO
, H.LIMITE_CREDITOS
, C.CIDADE 
, C.UF 
FROM THOSPEDES H
LEFT JOIN TCIDADES C ON C.ID_CIDADE = H.ID_CIDADE
WHERE H.ID_HOSPEDE <> 0
