SELECT
  PRODUTOS.NPROD AS CODIGO,
  PRODUTOS.CODBARRAS AS BARRAS,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  PRODUTOS.MARCA AS CARACTERISTICAS,
  PRODUTOS.GRUPO AS GRUPO,
  PRODUTOS.SUBGRUPO AS FAMILIA,
  PRODUTOS.UNVENDA AS UND,
  PRODUTOS.UNCOMPRA AS UND_COMPRA,
  PRODUTOS.PRECOCUSTO AS PRECO_CUSTO,
  PRODUTOS.PRECOVENDA AS PRECO_VENDA,
  PRODUTOS.QTDEDISP AS QTD,
  PRODUTOS.QTDEMIN AS QTD_IDEAL,
  PRODUTOS.DATACAD AS DATA_CADASTRO,
  PRODUTOS.NCMSH AS COD_NCM,
  PRODUTOS.DATAALT AS ALTERACAO_PRECO
FROM PRODUTOS