SELECT
    CLIENTES_ID AS CODIGO,
    CLIENTE_NOME AS NOME,
    CLIENTE_CPF_CNPJ AS CNPJ_CNPF,
    CLIENTE_RG_IE AS IE_RG,
    CLIENTE_CONTATO AS CONTATO,
    CLIENTE_ENDERECO AS ENDERECO,
    CLIENTE_BAIRRO AS BAIRRO,
    LOCALIDADE_CEP AS CEP,
    CLIENTE_EMAIL AS EMAIL,
    CLIENTE_TELEFONE AS TELEFONE,
    CLIENTE_TELEFONE1 AS CELULAR,
    CLIENTE_CADASTRO AS CADASTRO,
    CLIENTE_NUMERO AS NUMERO,
    CLIENTE_COMPLEMENTO AS COMPLEMENTO
FROM CLIENTES
