SELECT
    FORNECEDORES_ID AS CODIGO,
    FORNECEDOR_NOME AS NOME,
    FORNECEDOR_CPF_CNPJ AS CNPJ_CNPF,
    FORNECEDOR_RG_IE AS IE_RG,
    FORNECEDOR_CONTATO AS CONTATO,
    FORNECEDOR_ENDERECO AS ENDERECO,
    FORNECEDOR_BAIRRO AS BAIRRO,
    LOCALIDADE_CEP AS CEP,
    FORNECEDOR_EMAIL AS EMAIL,
    FORNECEDOR_TELEFONE AS TELEFONE,
    FORNECEDOR_TELEFONE1 AS CELULAR,
    FORNECEDOR_NUMERO AS NUMERO,
    FORNECEDOR_COMPLEMENTO AS COMPLEMENTO
FROM FORNECEDORES
