SELECT
    COD_CLI AS CODIGO,
    RAZAO AS NOME,
    NOME_FAN AS FANTASIA,
    FONE_RES AS TELEFONE,
    ENDERECO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    CEP,
    UF,
    FONE_CEL AS CELULAR,
    EMAIL,
    CGC AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    NUMERO_ENDERECO AS NUMERO
FROM CLIENTES
