SELECT
    P.ID AS CODIGO,
    P.CODPRO AS BARRAS,
    -- P.CODBAR AS BARRAS,
    P.NOMPRO AS DESCRICAO,
    P.NOMFOR AS FORNECEDOR,
    P.UN AS UND,
    P."REF" AS COD_FABRICANTE,
    P.IPI_E AS ALIQ_IPI,
    CAST(P.DH_CAD AS DATE) AS DATA_CADASTRO,
    P.DT_UVENDA AS ULTIMA_VENDA,
    P.DT_UCOMPRA AS ULTIMA_COMPRA,
    P.LUCRO1 AS MARGEM_LUCRO,
    P.PVENDA AS PRECO_VENDA,
    P.PCUSTOB AS PRECO_CUSTO,
    P.PCUSTOM AS CUSTO_MEDIO,
    P.ESTOQUE AS QTD,
    P.ESTMIN AS QTD_IDEAL,
    P.ALIQUOTA AS ELO,
    P.OBSERVACAO AS OBSERVACOES,
    P.CST AS ST,
    P.NCM AS COD_NCM, 
    P.TIPO AS PERSONAL1,
    P.IPPT,
    CASE 
        WHEN P.ATIVO = 'True' THEN 'Ativo'
        WHEN P.ATIVO = 'False' THEN 'Inativo'
    END AS SITUACAO,
    P.ORIG AS OST,
    P.COD_BALANCA AS PERSONAL2,
    P.PESO_BRUTO AS PESO,
    P.CEST AS PERSONAL6,
    P.VALIDADE_DIAS,
    P.CST_IPI AS IPI_CODIGO_VENDA,
    G.NOMGRU AS GRUPO,
    M.DESCRICAO AS FAMILIA,
    S.NOME AS CARACTERISTICAS,
    PC.PIS_CST AS PIS_CODIGO, 
    PC.PIS_ALIQ AS PIS_ALIQ_NOR, 
    PC.COFINS_CST AS COFINS_CODIGO, 
    PC.COFINS_ALIQ AS COFINS_ALIQ_NOR
FROM
    PRODUTOS P
LEFT JOIN GRUPOS G ON G.CODGRU = P.CODGRU 
LEFT JOIN MARCAS M ON M.ID = P.ID_MARCAS 
LEFT JOIN SECAO S ON S.ID = P.ID_SECAO    
LEFT JOIN PIS_COFINS PC ON PC.ID = P.ID_PIS_COFINS