SELECT
  PRODUTOS.CODIGO_PRODUTO AS CODIGO,
  GRUPOS_PRODUTO.DESCRICAO AS GRUPO,
  SUBGRUPOS_PRODUTO.DESCRICAO AS FAMILIA,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  PRODUTOS.ESPECIFICACAO AS OBSERVACOES,
  PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
  PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTOS_SALDO.SALDO_ATUAL AS QTD,
  PRODUTOS.UNIDADE_ENTRADA AS UND_COMPRA,
  PRODUTOS.UNIDADE_SAIDA AS UND,
  PRODUTOS.ULTIMO_REAJUSTE AS ALTERACAO_PRECO,
  PRODUTOS.PESO AS PESO,
  PRODUTOS.CODIGO_BARRA AS BARRAS,
  PRODUTOS.REFERENCIA AS COD_FABRICANTE,
  PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
  PRODUTOS.CST AS ST,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN PRODUTOS_SALDO ON PRODUTOS_SALDO.CODIGO_PRODUTO = PRODUTOS.CODIGO_PRODUTO
LEFT JOIN GRUPOS_PRODUTO ON GRUPOS_PRODUTO.CODIGO_GRUPO = PRODUTOS.CODIGO_GRUPO
LEFT JOIN SUBGRUPOS_PRODUTO ON SUBGRUPOS_PRODUTO.ID_SUBGRUPO = PRODUTOS.CODIGO_SUBGRUPO
