SELECT
  FORNECEDOR.ID_FORNECEDOR AS CODIGO,
  FORNECEDOR.RAZAO_SOC AS NOME,
  FORNECEDOR.NOME_FANTA AS FANTASIA,
  FORNECEDOR.CGC AS CNPJ_CNPF,
  FORNECEDOR.INSC_EST AS IE_RG,
  FORNECEDOR.ENDERECO AS ENDERECO,
  FORNECEDOR.BAIRRO AS BAIRRO,
  FORNECEDOR.CIDADE AS CIDADE,
  FORNECEDOR.CEP AS CEP,
  FORNECEDOR.UF AS UF,
  FORNECEDOR.TELEFONE AS TELEFONE,
  FORNECEDOR.FAX AS FAX,
  FORNECEDOR.REPRESENTANTE AS CONTATO
FROM FORNECEDOR
