SELECT
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.EAN AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.PESO AS PESO,
    PRODUTO.CODIGO AS CARACTERISTICAS,
    PRODUTO.IDEAL AS QTD_IDEAL,
    MAX (KARDEXF.QUANTIDADE) AS QTD,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.PRECO AS PRECO_VENDA,
    PRODUTO.PRECO_ATA AS PRECO_ATACADO,
    SUBSTRING (TRIBUTO.SIT FROM 1 FOR 1) AS OST,
    SUBSTRING (TRIBUTO.SIT FROM 2 FOR 3) AS ST,
    TRIBUTO.CFOP AS CF,
    PRODUTO.GRUPO AS GRUPO,
    PRODUTO.REF AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6,
    PRODUTO.CADASTRO AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN TRIBUTO ON TRIBUTO.CODTRI = PRODUTO.CODTRI
LEFT JOIN KARDEXF ON KARDEXF.CODIGO = PRODUTO.CODIGO
WHERE PRODUTO.DESCRICAO <> ''
GROUP BY 1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19
