SELECT
    FORNECEDOR.FORNECEDOR AS CODIGO,
    FORNECEDOR.NOME AS NOME,
    FORNECEDOR.CONTATO AS CONTATO,
    FORNECEDOR.CPF AS CNPJ_CNPF,
    FORNECEDOR.IE AS IE_RG,
    FORNECEDOR.IM AS IM,
    FORNECEDOR.ENDERECO AS ENDERECO,
    BAIRRO.NOME AS BAIRRO,
    FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.NRO AS NUMERO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.TELEFONE AS TELEFONE,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN BAIRRO ON BAIRRO.bairro = FORNECEDOR.bairro
LEFT JOIN CIDADE ON CIDADE.cidade = FORNECEDOR.CIDADE