SELECT CAST(CLIENTE.CODCLIENTE AS INTEGER) as codigo,
CIDADES.CIDADE,
CLIENTE.NOME,
CLIENTE.NOMEFANTASIA AS FANTASIA,
CLIENTE.ENDERECO,
CLIENTE.NUMERO,
CLIENTE.BAIRRO,
CLIENTE.ESTADO AS UF,
CLIENTE.CEP,
CLIENTE.CGCCPF AS CNPJ_CNPF,
CLIENTE.INSCEST AS IE_RG,
CLIENTE.CONTATO,
CLIENTE.FONE AS TELEFONE,
CLIENTE.FAX,
--CAST(CLIENTE.DT_CADASTRO AS DATE) AS CADASTRO,
CLIENTE.EMAIL,
CLIENTE.OBSERVACAO AS OBSERVACOES,
CLIENTE.CELULAR
FROM CLIENTE
left join cidades on CLIENTE.CODCIDADE=CIDADES.CODCIDADE
WHERE CLIENTE.CODCLIENTE>'00000000'
