SELECT
PRODUTO.CODPROD AS CODIGO,
GRUPROD.DESCRICAO AS GRUPO,
SUBGRUP.DESCRICAO AS FAMILIA,
PRODUTO.REFERENCIA AS BARRAS,
PRODUTO.REFFABRICANTE AS COD_FABRICANTE,
PRODUTO.DESCRICAO,
CLASFISC.CODIGONCM AS COD_NCM,
SUBSTRING (PRODUTO.CODTRIBUT00 FROM 2 FOR 3) AS ST,
PRODUTO.UNIDADESAIDA AS UND,
PRODUTO.PRECO AS PRECO_VENDA,
PRODUTO.OBSERVACAO AS OBSERVACOES,
SUM (COMPPROD.estoque) as qtd,
sum (COMPPROD.precocusto) as preco_custo,
PRODUTO.CODCEST AS PERSONAL6
FROM PRODUTO
left join gruprod on PRODUTO.CODGRUPO=GRUPROD.CODGRUPO
left join SUBGRUP on GRUPROD.CODGRUPO=SUBGRUP.CODGRUPO AND PRODUTO.CODSUBGRUPO=SUBGRUP.CODSUBGRUPO
LEFT JOIN CLASFISC ON PRODUTO.CODCLASFIS=CLASFISC.CODCLASFIS
left join COMPPROD on produto.codprod = COMPPROD.codprod
where compprod.codempresa='00'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,14
