SELECT 
       PRO_00.PRO_CODIGO AS CODIGO
      ,PRO_00.PRO_DESCRICAO AS DESCRICAO
      ,PRO_00_05.PRO_PRECOPEDIDO AS PRECO_VENDA
      ,GRP_00.GRP_DESCRICAO AS GRUPO
      ,SGP_00.SGP_DESCRICAO AS FAMILIA
      ,PRO_00.SGM_CODIGO AS UND
      ,NCM_00.CST_CODIGO AS ST
      ,PRO_00.CLF_CODIGO AS COD_NCM
      ,MAR_00.MAR_NOME AS CARACTERISTICAS
      ,SUBSTRING (PRO_00_03.PRO_CODIGOFORNECEDOR, 4,19) AS COD_FABRICANTE
    --,PRO_00.PRO_REFERENCIAINTERNA AS COD_FABRICANTE
      ,MAX (ETQ_00.ETQ_ESTOQUEFILIAL) AS QTD
      ,MAX (ETQ_00.ETQ_VALORCUSTOCOMPRA) AS PRECO_CUSTO
      ,PRO_00.PRO_CEST AS PERSONAL6
  FROM NESKI_EXPRESS_DB.dbo.PRO_00
LEFT JOIN NESKI_EXPRESS_DB.dbo.GRP_00 ON PRO_00.GRP_CODIGO = GRP_00.GRP_CODIGO
LEFT JOIN NESKI_EXPRESS_DB.dbo.SGP_00 ON PRO_00.GRP_CODIGO = SGP_00.SGP_CODIGO
left join NESKI_EXPRESS_DB.dbo.ETQ_00 on PRO_00.PRO_CODIGO = ETQ_00.PRO_CODIGO
LEFT JOIN NESKI_EXPRESS_DB.dbo.PRO_00_05 ON PRO_00.PRO_CODIGO = PRO_00_05.PRO_CODIGO
LEFT JOIN NESKI_EXPRESS_DB.dbo.NCM_00 ON NCM_00.NCM_CODIGO = PRO_00.NCM_CODIGO
LEFT JOIN NESKI_EXPRESS_DB.dbo.MAR_00 ON MAR_00.MAR_CODIGO = PRO_00.MAR_CODIGO
LEFT JOIN NESKI_EXPRESS_DB.dbo.PRO_00_03 ON PRO_00_03.PRO_CODIGO = PRO_00.PRO_CODIGO
group by 
       PRO_00.PRO_CODIGO
      ,PRO_00.PRO_DESCRICAO
      ,PRO_00_05.PRO_PRECOPEDIDO
      ,GRP_00.GRP_DESCRICAO
      ,SGP_00.SGP_DESCRICAO
      ,PRO_00.SGM_CODIGO
      ,NCM_00.CST_CODIGO
      ,PRO_00.CLF_CODIGO
      ,MAR_00.MAR_NOME
      ,PRO_00_03.PRO_CODIGOFORNECEDOR
    --,PRO_00.PRO_REFERENCIAINTERNA
    --,ETQ_00.ETQ_ESTOQUEFILIAL
    --,ETQ_00.ETQ_VALORCUSTOCOMPRA
      ,PRO_00.PRO_CEST
order by PRO_00.PRO_DESCRICAO desc