SELECT
    CADASTRO.ID AS CODIGO,
    CADASTRO.RAZAO_SOCIAL AS NOME,
    CADASTRO.FANTASIA AS FANTASIA,
    CADASTRO_ENDERECO.CONTATO,
    CADASTRO.CNPJ_CPF AS CNPJ_CNPF,
    CADASTRO.INSCRICAO_RG AS IE_RG,
    CADASTRO.INSCRICAO_MUNICIPAL AS IM,
    CADASTRO_ENDERECO.LOGRADOURO AS ENDERECO,
    CADASTRO_ENDERECO.NUMERO AS NUMERO,
    CADASTRO_ENDERECO.COMPLEMENTO,
    CADASTRO_ENDERECO.BAIRRO,
    CADASTRO_ENDERECO.CIDADE,
    CADASTRO_ENDERECO.UF,
    CADASTRO_ENDERECO.CEP AS CEP,
    CADASTRO_ENDERECO.FONE AS TELEFONE,
    CADASTRO_ENDERECO.FAX AS FAX,
    CADASTRO_ENDERECO.CELULAR,
    CADASTRO.E_MAIL AS EMAIL,
    CADASTRO_ENDERECO.OBSERVACAO AS OBSERVACOES
FROM CADASTRO
LEFT JOIN CADASTRO_ENDERECO ON CADASTRO_ENDERECO.FK_CADASTRO = CADASTRO.ID
WHERE CADASTRO.CHK_FORNECEDOR = 'S'
