SELECT 
CODIGO_CLI AS CODIGO, 
CGCCPF_CLI AS CNPJ_CNPF, 
NOME_CLI AS NOME, 
ENDER_CLI AS ENDERECO, 
NUMER_CLI AS NUMERO, 
COMPL_CLI AS COMPLEMENTO, 
BAIRRO_CLI AS BAIRRO, 
CIDADE_CLI AS CIDADE, 
CEP_CLI AS CEP, 
ESTADO_CLI AS UF, 
INSCR_CLI AS IE_RG, 
CONCAT (DDD_CLI, ' ', TELEF_CLI) AS TELEFONE,      
BD_CLI AS PERSONAL2,  
BM_CLI AS PERSONAL1, 
OBSERVACOES AS OBSERVACOES
FROM F001.DBO.ACLIENGE
