 SELECT 
  AU_ITE AS CODIGO,
  AA_ITE AS COD_FABRICANTE, 
  AB_ITE AS DESCRICAO, 
  AC_ITE AS GRUPO,
  CE_PRODUTOS_ADICIONAIS.PRECOVENDAMIN AS PRECO_VENDA,
  CE_PRODUTOS_ADICIONAIS.PRECOCOMPRA  AS PRECO_CUSTO,
  CE_PRODUTOS_ADICIONAIS.CUSTOMEDIO AS CUSTO_MEDIO,
  CE_PRODUTOS_IMPOSTOS.NCM AS COD_NCM,
  CE_PRODUTOS_IMPOSTOS.CSTSAIDAS AS ST,
  CE_PRODUTOS_IMPOSTOS.ALIQUOTAICMS AS ELO,
  CE_PRODUTOS_IMPOSTOS.CFOP AS CF,
  CE_PRODUTOS_IMPOSTOS.CSTPISCOFINSSAIDA AS PIS_CODIGO,
  CE_PRODUTOS_IMPOSTOS.CSTPISCOFINSSAIDA AS COFINS_CODIGO,
  CE_PRODUTOS_IMPOSTOS.CEST AS PERSONAL6,  
  AH_ITE AS UND,   
  BO_ITE AS BARRAS  
FROM F001.DBO.CE_PRODUTO
LEFT JOIN CE_PRODUTOS_ADICIONAIS ON CE_PRODUTO.AU_ITE =CE_PRODUTOS_ADICIONAIS.CODREDUZIDO 
LEFT JOIN CE_PRODUTOS_IMPOSTOS ON CE_PRODUTO.AU_ITE=CE_PRODUTOS_IMPOSTOS.CODREDUZIDO
