SELECT 
       CLIENTE AS CODIGO
      ,NOME AS NOME
      ,FANTASIA AS FANTASIA
      ,SEXO AS SEXO
      ,ESTADOCIVIL AS EST_CIVIL
      ,ENDERECO AS ENDERECO
      ,ENDERECOCOMPL AS COMPLEMENTO
      ,ENDERECONUMERO AS NUMERO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,ESTADO AS UF
      ,CEP AS CEP
      ,FONE AS TELEFONE
      ,FAX AS FAX
      ,CELULAR AS CELULAR
      ,IDENTIDADE AS IE_RG
      ,CPF AS CNPJ_CNPF
      ,NATURAL AS NATURALIDADE
      ,PAI AS PAI
      ,MAE AS MAE
      ,CONJUGE AS CONJUGE
      ,DTABERTURA AS CADASTRO
      ,LIMITE_CREDITO AS LIMITE_CREDITO
      ,E_MAIL AS EMAIL
  FROM Empresario.dbo.CADCLI
  WHERE CLIENTE <> '999999'