SELECT
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.GTIN AS BARRAS,
    PRODUTO.VOLUME AS UND,
    GRUPO.NOME AS GRUPO,
    PRODUTO.PESOLIQ AS PESO,
    ESTOQUE.ESTMIN AS QTD_IDEAL,
    ESTOQUE.QTDESTOQUE AS QTD,
    ESTOQUE.VRUCOM AS PRECO_CUSTO,
    ESTOQUE.VRVEND AS PRECO_VENDA,
    SUBSTRING (TRIBUTACAO.NOME FROM 1 FOR 1) AS ST,
    PRODUTO.OBS AS OBSERVACOES,
    ESTOQUE.ATREPO AS ALTERACAO_PRECO,
    ESTOQUE.ATUCOM AS ULTIMA_COMPRA,
    ESTOQUE.ATVEND AS ULTIMA_VENDA,
    PRODUTO.PRODUTO AS COD_FABRICANTE,
    IBPT.NCM AS COD_NCM,
    IBPT.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.TRIBUTACAO = PRODUTO.TRIBUTACAO
LEFT JOIN GRUPO ON GRUPO.GRUPO = PRODUTO.GRUPO
LEFT JOIN ESTOQUE ON ESTOQUE.PRODUTO = PRODUTO.PRODUTO
LEFT JOIN IBPT ON IBPT.IBPT = PRODUTO.IBPT
WHERE ESTOQUE.DEPOSITO = '1'
