SELECT
PRODUTOS.CODIGO,
PRODUTOS.REFERENCIA AS COD_FABRICANTE,
PRODUTOS.DESCRICAO,
GRUPOS.NOME_GRUPO AS GRUPO,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.PRCUSTO AS PRECO_CUSTO,
PRODUTOS.PRVENDA AS PRECO_VENDA,
PRODUTOS.SITUACAO_TRIBUTARIA AS ST,
PRODUTOS.IPI AS ALIQ_IPI_VENDA,
PRODUTOS.CODIGO_BARRA AS BARRAS,
case when PRODUTOS.CODIGO_BARRA = '' or PRODUTOS.CODIGO_BARRA is null then PRODUTOS.REFERENCIA else PRODUTOS.CODIGO_BARRA END AS BARRAS,
PRODUTOS.DT_CADASTRO AS CADASTRO,
PRODUTOS.CODIGONCM AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6,
sum (ESTOQUE.ESTOQUE) AS QTD
FROM PRODUTOS
LEFT JOIN ESTOQUE ON PRODUTOS.CODIGO=ESTOQUE.CODIGO
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO=GRUPOS.CODIGO
WHERE PRODUTOS.DESCRICAO IS NULL OR PRODUTOS.DESCRICAO <> ''
group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14
