SELECT
	P.CODIGO_PRODUTO AS CODIGO,
	P.DESCRICAO AS DESCRICAO,
	GP.DESCRICAO AS GRUPO,
	TP.DESCRICAO AS FAMILIA,
	PS.SALDO_ATUAL AS QTD,
	PS.LOCALIZACAO AS OBSERVACOES,
	P.REFERENCIA AS COD_FABRICANTE,
	P.PRECO_VENDA AS PRECO_VENDA,
	P.CUSTO_MEDIO AS CUSTO_MEDIO,
	P.CUSTO_ATUAL AS PRECO_CUSTO,
	P.UNIDADE_SAIDA AS UND,
	P.REFERENCIA2 AS PERSONAL1,
	P.CODIGO_BARRA AS BARRAS,
	P.REFERENCIA3 AS PERSONAL2,
	CASE WHEN P.STATUS = '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	P.CST AS ST,
	P.PIS AS PIS_ALIQ_NOR,
	P.CST_PIS AS PIS_CODIGO,
	P.CST_COFINS AS COFINS_CODIGO,
	P.COFINS COFINS_ALIQ_NOR,
	P.CST_IPI AS  IPI_CODIGO,
	P.NCM AS COD_NCM,
	P.DATA_CADASTRO AS DATA_CADASTRO,
	P.CEST AS PERSONAL6
FROM PRODUTOS P
LEFT JOIN GRUPOS_PRODUTO GP ON P.CODIGO_GRUPO=GP.CODIGO_GRUPO
LEFT JOIN TIPOS_PRODUTO TP ON P.CODIGO_TIPOPRODUTO=TP.CODIGO_TIPOPRODUTO 
LEFT JOIN PRODUTOS_SALDO PS ON P.CODIGO_PRODUTO=PS.CODIGO_PRODUTO 