SELECT
  cad_cli0.cli_codigo AS CODIGO,
  cad_cli0.cli_sexo AS SEXO,
  cad_cli0.cli_fan AS FANTASIA,
  cad_cli0.cli_razao AS NOME,
  cad_cli0.cli_end AS ENDERECO,
  cad_cli0.cli_comple AS COMPLEMENTO,
  cad_cli0.cli_bairro AS BAIRRO,
  cad_cli0.cli_cidade AS CIDADE,
  cad_cli0.cli_numend AS NUMERO,
  cad_cli0.cli_uf AS UF,
  cad_cli0.cli_cep AS CEP,
  case when cad_cli0.cli_cgc = '' or cad_cli0.cli_cgc is null then cad_cli0.cli_cpf else cad_cli0.cli_cgc END as CNPJ_CNPF,
  case when cad_cli0.cli_insc = '' or cad_cli0.cli_insc is null then cad_cli0.cli_ident else cad_cli0.cli_insc END as IE_RG,
  cad_cli0.cli_insmun AS IM,
  cad_cli0.cli_tel1 AS TELEFONE,
  cad_cli0.cli_tel2 AS CELULAR,
  cad_cli0.cli_cont AS CONTATO,
  cad_cli0.cli_obs AS OBSERVACOES,
  cad_cli0.cli_nompai AS PAI,
  cad_cli0.cli_nommae AS MAE,
  cad_cli0.cli_nomconj AS CONJUGE,
  cad_cli0.cli_email AS EMAIL
  FROM cad_cli0
