SELECT CLIENTE.CCODIGO AS CODIGO,
CLIENTE.CLIENTE AS NOME,
CLIENTE.APELIDO AS FANTASIA,
CLIENTE.DTANASC AS NASCIMENTO,
CLIENTE.LOGRADOURO AS ENDERECO,
CLIENTE.NUMERO,
CLIENTE.COMPLEMENTO,
CLIENTE.BAIRRO,
CLIENTE.CEP,
CLIENTE.FONE AS TELEFONE,
CLIENTE.EMAIL,
CLIENTE.IDENTIDADE_IE AS IE_RG,
CLIENTE.CPFCNPJ AS CNPJ_CNPF,
CIDADE.CIDADE,
CIDADE.UF
FROM CLIENTE
LEFT JOIN CIDADE ON CLIENTE.LK_CIDADE=CIDADE.CCODIGO

