SELECT FORNEC.FCODIGO AS CODIGO,
FORNEC.RAZAO_SOCIAL AS NOME,
FORNEC.NFANTASIA AS FANTASIA,
FORNEC.CNPJ AS CNPJ_CNPF,
FORNEC.IE AS IE_RG,
FORNEC.ENDERECO,
FORNEC.NUMERO,
FORNEC.COMPLEMENTO,
FORNEC.BAIRRO,
FORNEC.CIDADE,
FORNEC.UF,
CIDADE.CIDADE,
CIDADE.UF,
FORNEC.CEP,
FORNEC.FONE AS TELEFONE,
FORNEC.EMAIL,
FORNEC.CONTATO,
FORNEC.OBS AS OBSERVACOES
FROM FORNEC
LEFT JOIN CIDADE ON FORNEC.LK_CIDADE=CIDADE.CCODIGO


