SELECT 
  C.TBL_CLI_ID AS CODIGO
, C.TBL_CLI_RAZAO AS NOME
, C.TBL_CLI_FANTAZIA AS FANTASIA
, C.TBL_CLI_END AS ENDERECO
, C.TBL_CLI_COMPLEMENTO AS COMPLEMENTO
, C.TBL_CLI_NR_RESIDE AS NUMERO
, C.TBL_CLI_BAIRRO AS BAIRRO
, C.TBL_CLI_CEP AS CEP
, CI.CID_NOME AS CIDADE
, CI.EST_UF AS UF
, C.TBL_CLI_FONE1 AS TELEFONE
, C.TBL_CLI_FONE_FAX AS FAX
, C.TBL_CLI_CELULAR AS CELULAR
, C.TBL_CLI_FONE2 AS PERSONAL1
, C.TBL_CLI_DTA_NASC AS NASCIMENTO
, C.TBL_CLI_CPF_CGC AS CNPJ_CNPF
, C.TBL_CLI_RG_INSC AS IE_RG
, C.TBL_CLI_PAI AS PAI
, C.TBL_CLI_MAE AS MAE
, C.TBL_CLI_EMAIL AS EMAIL
, C.TBL_CLI_DESDE AS CADASTRO
, C.TBL_CLI_CONTATO AS CONTATO
, TCO.OBS1 AS OBSERVACOES
FROM TBL_CLIENTE C
LEFT JOIN TBL_CIDADE CI ON CI.CID_CODIGO = C.TBL_CLI_CID_CODIGO
LEFT JOIN TBL_CLI_OBSERVACOES TCO ON TCO.TBL_CLI_ID = C.TBL_CLI_ID 