SELECT 
  P.PROD_CODIGO AS CODIGO
, P.PROD_DESC AS DESCRICAO
, CASE P.PROD_SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.PROD_COD_FISCAL
, P.PROD_QTD_CAIXA AS FAT_CONV
, P.PROD_CLASSE_FISCAL AS COD_NCM
, RIGHT (P.PROD_ST,3) AS ST
, P.PROD_PERCENT_IPI AS ALIQ_IPI_VENDA
, P.PROD_PESO_BRUTO AS PESO
, P.PROC_PERCENT_COMISSAO AS COMISSAO
, P.PROD_DTA_CAD AS DATA_CADASTRO
-----, P.PROD_UNID_COD
, TEP.EST_MINIMO AS QTD_INICIAL
, TEP.EST_ATUAL AS QTD
, TFP.CUSTO_COMERCIAL AS PRECO_CUSTO
, TFP.MARGEM_LUCRO AS MARGEM_LUCRO
, TFP.PRECO_VDA AS PRECO_VENDA
, TS.SECAO_DESC AS GRUPO
, TSS.SUB_SECAO_DESC AS FAMILIA
, TUM.UNID_SIGLA AS UND
, MAX (TPE.PROD_EAN_CODIGO_BARRAS) AS BARRAS
FROM TBL_PRODUTOS P
LEFT JOIN TBL_SECAO TS ON TS.SECAO_CODIGO = P.PROD_SECAO 
LEFT JOIN TBL_SUB_SECAO TSS ON TSS.SUB_SECAO_COD = P.PROD_SUB_SECAO AND TSS.SECAO_CODIGO = TS.SECAO_CODIGO 
LEFT JOIN TBL_UNIDADES_MEDIDAS TUM ON TUM.CODIGO = P.PROD_UNID_MEDIDAS_CODIGO 
LEFT JOIN TBL_PROD_EAN TPE ON TPE.PROD_EAN_CODIGO_PRODUTO = P.PROD_CODIGO
LEFT JOIN TBL_FORMACAO_PRECO TFP ON TFP.PROD_CODIGO = P.PROD_CODIGO 
LEFT JOIN TBL_ESTOQUE_PROD TEP ON TEP.PROD_CODIGO = P.PROD_CODIGO 
GROUP BY 
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19