SELECT
TB_PRODUTO.PRD_ID AS CODIGO,
MAX (TB_PROD_CODIGO_BARRAS.PRDC_COD_BARRAS) AS BARRAS,
TB_PRODUTO.PRD_DESCRICAO AS DESCRICAO,
TB_PROD_GRUPO.PGRU_DESCRICAO AS GRUPO,
TB_PRODUTO.PRD_PRECO_CUSTO AS PRECO_CUSTO,
TB_PRODUTO.PRD_UN_VENDA AS UND,
TB_PRODUTO.PRD_PRECO_VENDA AS PRECO_VENDA,
TB_PRODUTO.PRD_NCM AS COD_NCM,
TB_PESSOA.pes_rsocial_nome AS FORNECEDOR,
TB_PRODUTO.PRD_DT_CADASTRO AS DATA_CADASTRO,
TB_PRODUTO_ESTOQUE.PRDE_ESTOQUE_NF AS QTD,
TB_PRODUTO_TRIBUTO.PRDT_ICMS_CST AS ST,
TB_PRODUTO_TRIBUTO.PRDT_CONFINS_CST_SAI AS COFINS_CODIGO,
TB_PRODUTO_TRIBUTO.PRDT_PIS_CST_SAI AS PIS_CODIGO,
case when TB_PRODUTO.PRD_STATUS = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
FROM TB_PRODUTO
LEFT JOIN TB_PROD_GRUPO ON TB_PRODUTO.PRD_GRUPO=TB_PROD_GRUPO.PGRU_ID
LEFT JOIN TB_PRODUTO_TRIBUTO ON TB_PRODUTO.PRD_ID=TB_PRODUTO_TRIBUTO.PRDT_PRODUTO
LEFT JOIN TB_PROD_CODIGO_BARRAS ON TB_PROD_CODIGO_BARRAS.PRDC_PRODUTO = TB_PRODUTO.PRD_ID
LEFT JOIN TB_PRODUTO_ESTOQUE ON TB_PRODUTO_ESTOQUE.PRDE_PRODUTO = TB_PRODUTO.PRD_ID
LEFT JOIN TB_PESSOA ON TB_PESSOA.pes_id = TB_PRODUTO.prd_fornecedor
GROUP BY 1,3,4,5,6,7,8,9,10,11,12,13,14,15
