SELECT
	FOR_IDCODIGO AS CODIGO,
	FOR_NOME AS NOME,
	FOR_FANTASIA AS FANTASIA,
	FOR_ENDE AS ENDERECO,
	FOR_NRO AS NUMERO,
	FOR_BAIRRO AS BAIRRO,
	FORCD_CEP AS CEP,
	FOR_CIDADE AS CIDADE,
	FOR_UF AS UF,
	CASE WHEN FORNECES.FOR_CPF = '' OR FORNECES.FOR_CPF IS NULL THEN FORNECES.FOR_CNPJ ELSE FORNECES.FOR_CPF END CNPJ_CNPF,
	FOR_IE AS IE_RG,
	FOR_FONE AS TELEFONE,
	FOR_FAX AS FAX,
	FOR_EMAIL AS EMAIL
FROM FORNECES