SELECT
	PRO_IDCODIGO AS CODIGO,
	PRO_CODREF AS COD_FABRICANTE,
	PRO_CODBAR AS BARRAS,
	PRO_NOME AS DESCRICAO,
	M.MCA_NOME AS FAMILIA,
	PROCOD_UNID AS UND,
	F.FOR_NOME AS FORNECEDOR,
	G.GPP_NOME AS GRUPO,
	S.SGP_NOME AS CARACTERISTICAS,
	MD.MLO_NOME AS PERSONAL1,
	PRO_ICMSS AS ELO,
	PRO_ESTOQUE AS QTD,
	PRO_CREAL AS PRECO_CUSTO,
	PRO_CMEDIO AS CUSTO_MEDIO,
	PRO_PVENDA AS PRECO_VENDA,
	PRO_UENT AS ULTIMA_COMPRA,
	PRO_USAI AS ULTIMA_VENDA,
	PRO_DATACD AS DATA_CADASTRO,
	PRO_OBS AS OBSERVACOES,
	PRO_NCM AS COD_NCM
FROM PRODUTOS
LEFT JOIN MARCASPROD M ON PRODUTOS.PROCOD_MARCA=M.MCA_IDCODIGO 
LEFT JOIN FORNECES F ON PRODUTOS.PROCOD_FORN=F.FOR_IDCODIGO 
LEFT JOIN GRUPOSPRO G ON PRODUTOS.PROCOD_GRUPO=G.GPP_IDCODIGO 
LEFT JOIN SGRUPOSPRO S ON PRODUTOS.PROCOD_SGRUPO=S.SGP_IDCODIGO 
LEFT JOIN MODELOSP MD ON PRODUTOS.PROCOD_MODELO=MD.MLO_IDCODIGO 