SELECT
  TFORNECEDORES.CODIGO AS CODIGO,
  TFORNECEDORES.NOME AS NOME,
  TFORNECEDORES.REPRESENTANTE AS CONTATO,
  TFORNECEDORES.TELEFONE1 AS TELEFONE,
  TFORNECEDORES.TELEFONE2 AS CELULAR
FROM TFORNECEDORES
