SELECT
  TPRODUTOS.CODIGO AS CODIGO,
  TPRODUTOS.DESCRICAO AS DESCRICAO,
  TGRUPOS.DESCRICAO AS GRUPO,
  TPRODUTOS.NCMSH AS COD_NCM,
  TPRODUTOS.UNMEDIDA AS UND,
  TFORNECEDORES.NOME AS FORNECEDOR,
  TPRODUTOS.CODBARRAS AS BARRAS,
  TPRODUTOS.REFERENCIA AS COD_FABRICANTE,
  TPRODUTOS.PESO AS PESO,
  TPRODUTOS.COMPLEM AS CARACTERISTICAS,
  SUBSTRING (TPRODUTOS.PERICMS FROM 1 FOR 2) AS ST,
  TPRODUTOS.ESTOQUE AS QTD,
  TPRODUTOS.CUSTO AS PRECO_CUSTO,
  TPRODUTOS.VENDA AS PRECO_VENDA
FROM TPRODUTOS
LEFT JOIN TFORNECEDORES ON TFORNECEDORES.CODIGO = TPRODUTOS.FORNECEDOR
LEFT JOIN TGRUPOS ON TGRUPOS.CODIGO = TPRODUTOS.GRUPO
