SELECT 
  CODFOR AS CODIGO
, NOMEFOR AS NOME
, NOMEFANTASIA AS FANTASIA
, ENDFOR AS ENDERECO
, NUMEND AS NUMERO
, COMPLEMENTO
, CIDADEFOR AS CIDADE
, BAIRROFOR AS BAIRRO
, CEPFOR AS CEP
, ESTADOFOR AS UF
, CASE WHEN CPFFOR = '' OR CPFFOR IS NULL THEN CGCFOR ELSE CPFFOR END AS CNPJ_CNPF
, CASE WHEN RGFOR = '' OR RGFOR IS NULL THEN INSCFOR ELSE RGFOR END AS IE_RG
, INSMUNICIPAL AS IM
, CONTATO
, CONCAT(DDDFOR, FONEFOR)
, CONCAT(DDDFAX, FONEFAX)
, CONCAT(DDDCEL, CEL)
, E_MAIL AS EMAIL
, OBS AS OBSERVACOES
FROM FORNEC