SELECT 
  P.CODPROD AS CODIGO
, P.DESCRICAO
, P.CODBARRAS AS BARRAS
-- , P.EAN AS BARRAS
, P.CTULTCP AS PRECO_CUSTO
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.MARGEM AS MARGEM_LUCRO
, P.PRVENDA AS PRECO_VENDA
, P.PRECOATAC AS PRECO_ATACADO
, P.QTDETOTAL AS QTD
, P.MINIMO AS QTD_IDEAL
, P.PESOBRUTO AS PESO
, P.COR
, P.UNIDADE AS UND
, P.IPI AS ALIQ_IPI
, P.LOCALIZACAO AS PERSONAL1
, P.NUMFABRICANTE AS COD_FABRICANTE
-- , P.CODFABR
-- , P.CODIGOFABR
, P.COMISSAO
, P.OBS AS OBSERVACOES
, CASE P.STATUS WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, LEFT (P.CFOP_SAIDA_DENTRO_DA_UF,3) AS ELO
, P.CF AS COD_NCM
, P.DTULTIMAVENDA AS ULTIMA_VENDA
, P.FATCONV AS FAT_CONV
, P.DIASVALID AS VALIDADE_DIAS
, P.CEST AS PERSONAL6
-- , P.CLASSIFICAO
-- , P.TRIBUTACAO
-- , P.ICMS
-- , P.CLASTRIB 
, M.DESC_MARCA AS CARACTERISTICAS
, G.NOMEGRU AS GRUPO
, D.NOMEDEP AS FAMILIA
FROM PROFILIA P
LEFT JOIN MARCA M ON M.ID_CODIGO = P.MARCA
LEFT JOIN GRUPO G ON G.CODGRU = P.CODGRU
LEFT JOIN DEPAR D ON D.CODDEP = P.CODDEP