SELECT 
  CODTRANS AS CODIGO
, NOMETRANS AS RAZAO_SOCIAL
, CONCAT(ENDTRANS,', ', BAIRROTRAN,', ', CEPTRANS) AS ENDERECO
, CIDTRANS AS CIDADE
, ESTADOTRAN AS UF
, CGCTRANS AS CNPJ
, INSCTRANS AS IE 
, CONCAT(DDDTRANS, FONETRANS) AS TELEFONE
, EMAIL 
, RNTC AS RNTRC
FROM TRANS