SELECT
    COD AS CODIGO,
    NOME AS NOME,
    CPF AS CNPJ_CNPF,
    ENDER AS ENDERECO,
    FONE AS TELEFONE,
    RG AS IE_RG,
    OBSCLIE AS OBSERVACOES,
    CID AS CIDADE,
    UF AS UF,
    CEP AS CEP
FROM CADCLIE
ORDER BY 1