SELECT
	PARTCODINTEGRACAO AS CODIGO,
	PARTICIPANTE AS NOME,
	PARTFANT AS FANTASIA,
	PARTEND AS ENDERECO,
	PARTCID AS CIDADE,
	PARTBAI AS BAIRRO,
	PARTNRO AS NUMERO,
	PARTCEP AS CEP,	
	PARTCOMPLEMENTO AS COMPLEMENTO,
	PARTUF AS UF,
	CASE WHEN PARTCPF = '' OR PARTCPF IS NULL THEN PARTCNPJ ELSE PARTCPF END AS CNPJ_CNPF,
	CASE WHEN PARTRG = '' OR PARTRG IS NULL THEN PARTIE ELSE PARTRG END AS IE_RG,
	PARTTEL1 AS TELEFONE,
	PARTTEL2 AS CELULAR,
	PARTEMAIL AS EMAIL,
	PARTLIMITECREDVALOR AS LIMITE_CREDITO,
	CAST(DNASCIMENTO AS DATE) AS NASCIMENTO,
	CAST(DCADASTRO AS DATE) AS CADASTRO
FROM
	CAD_PARTICIPANTE
WHERE PARTTIPOID = '1'	