SELECT
	--P.PRODUTOID AS CODIGO,
	P.CODINTEGRACAOID AS CODIGO,
	P.PRODUTO AS DESCRICAO,
	P.NCM AS COD_NCM,
	P.CODBARRAS AS BARRAS,
	P.IPPT,
	P.PRECOCUSTOEMPRESA AS PRECO_CUSTO,
	P.PRECOVENDA AS PRECO_VENDA,
	P.PRECOVENDA2 AS PRECO_ATACADO,
	P.PRECOVENDA3 AS PERSONAL1,
	P.QTDATUAL AS QTD,
	P.QTDMINIMA AS QTD_IDEAL,
	CAST(P.DCADASTRO AS DATE) AS DATA_CADASTRO,
	PG.GRUPO,
	PU.UNIDADE AS UND,
	ICM.ORIGEM AS OST,
	ICM.ST_ICMS_CSOSN AS ST,
	LEFT (ICM.PALIQICMS,3) AS ELO,
	I.ST_IPI_SAIDA AS IPI_CODIGO_VENDA,
	I.PALIQIPI_SAIDA AS ALIQ_IPI_VENDA,
	I.ST_IPI_ENTRADA AS IPI_CODIGO,
	I.PALIQIPI_ENTRADA AS ALIQ_IPI,
	PC.ST_PIS_SAIDA AS PIS_CODIGO,
	PC.PALIQPIS_SAIDA AS PIS_ALIQ_NOR,
	PC.ST_PIS_ENTRADA AS PISE_CODIGO,
	PC.PALIQPIS_ENTRADA AS PISE_ALIQ_NOR,
	PC.ST_COFINS_SAIDA AS COFINS_CODIGO,
	PC.PALIQCOFINS_SAIDA AS COFINS_ALIQ_NOR,
	PC.ST_COFINS_ENTRADA AS COFINSE_CODIGO,
	PC.PALIQCOFINS_ENTRADA AS COFINSE_ALIQ_NOR
FROM
	PRD_PRODUTO P
	LEFT JOIN PRD_GRUPO PG ON PG.GRUPOID = P.GRUPOID  
	LEFT JOIN PRD_UNIDADE PU ON PU.UNIDADEID = P.UNIDADEID 
	LEFT JOIN CAD_TRIBUTACAOESTADUAL_ICMS ICM ON ICM.TRIBUTESTADUALICMSID = P.TRIBUTESTADUALICMSID 
	LEFT JOIN CAD_TRIBUTACAOFEDERAL_IPI I ON I.TRIBUTFEDERALIPIID = P.TRIBUTFEDERALIPIID
	LEFT JOIN CAD_TRIBUTACAOFEDERAL_PIS_COFINS PC ON PC.TRIBUTFEDERAPISCOFINSID = P.TRIBUTFEDERAPISCOFINSID
