SELECT  
  C.CODIGO_CLIENTE AS CODIGO
, C.NOME
, C.FANTASIA
, C.CNPJ_CPF AS CNPJ_CNPF
, case when C.RG = '' OR C.RG = 'ISENTO' or C.RG is null then C.IE else C.RG END AS IE_RG
, C.ENDERECO
, C.COMPLEMENTO
, C.NUMERO
, C.BAIRRO
, CI.NOME AS CIDADE
, CI.UF
, C.CEP
, C.IM
, C.TELEFONE1 AS TELEFONE
, C.TELEFONE2 AS CELULAR
, C.TELEFONE3 AS FAX
, C.EMAIL
, C.OBSERVACAO AS OBSERVACOES
, C.LIMITE_CREDITO
, C.CONTATO
, C.DATA_CAD AS CADASTRO
, C.DATA_NASCIMENTO AS NASCIMENTO
, C.NOME_CONJUGUE AS CONJUGUE
, C.PAI
, C.MAE
, C.SEXO 
FROM CLIENTE C
LEFT JOIN CIDADE CI ON (CI.CODIGO_CIDADE = C.CODIGO_CIDADE)
