SELECT 
  F.CODIGO_FORNECEDOR AS CODIGO
, F.NOME
, F.FANTASIA
, F.CNPJ_CPF AS CNPJ_CNPF
, F.IE AS IE_RG
, F.IM
, F.ENDERECO
, F.COMPLEMENTO
, F.NUMERO
, F.BAIRRO
, CI.NOME AS CIDADE
, CI.UF
, F.CEP
, F.TELEFONE1 AS TELEFONE
, F.TELEFONE2 AS CELULAR
, F.TELEFONE3 AS FAX
, F.EMAIL
, F.OBSERVACAO AS OBSERVACOES
, F.CONTATO
FROM FORNECEDOR F
LEFT JOIN CIDADE CI ON (CI.CODIGO_CIDADE = F.CODIGO_CIDADE)
