SELECT 
   P.CODIGO_PRODUTO AS CODIGO
,  P.DATA_CAD AS DATA_CADASTRO
, CASE P.SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.DESCRICAO
, P.CODIGO_BARRA AS BARRAS
, P.PRECO_CUSTO_COMPRA AS PRECO_CUSTO
--, P.MARGEM_LUCRO
--, P.VALOR_LUCRO_PERCENTUAL
, P.PRECO_VENDA AS PRECO_VENDA
, P.ESTOQUE_MINIMO AS QTD_IDEAL
, P.ORIGEM_MERCADORIA AS OST
, P.PESO_BRUTO AS PESO
, P.CST_ICMS_VENDA AS ST
, LEFT (P.CFOP_VENDA_DENTRO,3) AS ELO
, P.CST_PIS_VENDA AS PIS_CODIGO
, P.PIS_VENDA AS PIS_ALIQ_NOR
, P.CST_COFINS_VENDA AS COFINS_CODIGO
, P.COFINS_VENDA AS COFINS_ALIQ_NOR
, P.CST_PIS_COMPRA AS PISE_CODIGO
, P.PIS_COMPRA AS PISE_ALIQ_NOR
, P.CST_COFINS_COMPRA AS COFINSE_CODIGO
, P.COFINS_COMPRA AS COFINSE_ALIQ_NOR
, P.REFERENCIA AS COD_FABRICANTE
, P.OBSERVACAO AS OBSERVACOES
, LEFT(PC.DESCRICAO,14) AS COR
, PT.DESCRICAO AS TAMANHO
, PU.ABREVIACAO AS UND
, N.NUMERO AS COD_NCM
, PG.DESCRICAO AS GRUPO
, PE.QUANTIDADE AS QTD
FROM PRODUTO P
LEFT JOIN PRODUTO_TAMANHO PT ON PT.CODIGO = P.CODIGO_PRODUTO_TAMANHO  
LEFT JOIN PRODUTO_COR PC ON PC.CODIGO = P.CODIGO_PRODUTO_COR 
LEFT JOIN PRODUTO_UNIDADE PU ON PU.CODIGO = P.CODIGO_UNIDADE 
LEFT JOIN NCM N ON N.CODIGO = P.CODIGO_NCM 
LEFT JOIN PRODUTO_GRUPO PG ON PG.CODIGO = P.CODIGO_GRUPO 
LEFT JOIN PRODUTO_ESTOQUE PE ON PE.CODIGO_PRODUTO = P.CODIGO 
