SELECT
MATERPDV.MFCODIGO AS COD_FABRICANTE,
MATERPDV.NOME AS DESCRICAO,
MATERPDV.UNCODIGO AS UND,
MATERPDV.PRECOVEN AS PRECO_VENDA,
MATERPDV.CODINTERN AS BARRAS,
MATERPDV.QTDESTOQ AS QTD,
MATERPDV.PRCCUMED AS CUSTO_MEDIO,
MATERPDV.PRECOCUS AS PRECO_CUSTO,
FORNECED.NOME AS FORNECEDOR,
REPLACE (MATERPDV.CLASFISC, '.' , '') AS COD_NCM,
MATERPDV.UNCODENT AS UND_COMPRA,
MATERPDV.CODIGOCEST AS PERSONAL6,
AGRUPAME.NOME AS GRUPO
FROM MATERPDV
LEFT JOIN FORNECED ON MATERPDV.FOCODIGO=FORNECED.FOCODIGO
LEFT JOIN AGRUPAME ON MATERPDV.AGCODIGO=AGRUPAME.AGCODIGO
