SELECT 
  C.ID_CLIENTE AS CODIGO
, CASE C.ID_TIPO_CONTRIBUINTE 
	WHEN '1' THEN 'C'
	WHEN '2' THEN 'I'
	WHEN '9' THEN 'N'
  END AS INDIEDEST
, C.RAZAOSOCIAL AS NOME
, C.NOMEFANTASIA AS FANTASIA
, CASE WHEN C.CPF_CNPJ = '' OR C.CPF_CNPJ IS NULL THEN C.CPF_CNPJ_EX ELSE C.CPF_CNPJ END AS CNPJ_CNPF
, C.IE_RG
, C.IM
, C.ENDERECO
, C.NUMERO
, C.COMPLEMENTO ||' - '|| C.PONTO_DE_REFERENCIA AS COMPLEMENTO
, C.BAIRRO
, C.CEP
, C.ID_CIDADES_UF AS UF
, C.TELEFONEFIXO AS TELEFONE
, C.CELULAR
, C.TELEFONETRABALHO AS FAX
, C.EMAIL
, C.CONTATO
, C.ESTADOCIVIL AS EST_CIVIL
, C.CONJUGE
, C.MAE
, C.PAI
, C.OBSERVACOES
, CAST(C.CADASTRO_DATA AS DATE) AS CADASTRO
, C.LIMITE_CREDITO
, CI.DESCRICAO AS CIDADE
FROM CLIENTES C
LEFT JOIN CIDADES CI ON CI.ID_CIDADES_IBGE = C.ID_CIDADES_IBGE