SELECT 
  F.ID AS CODIGO
, F.RAZAOSOCIAL AS NOME
, F.NOMEFANTASIA AS FANTASIA
, CASE WHEN F.CNPJ = '' OR F.CNPJ IS NULL THEN F.CNPJ_EX ELSE F.CNPJ END AS CNPJ_CNPF
, F.EI_ESTADUAL AS IE_RG
, F.EI_MUNICIPAL AS IM
, F.ENDERECO
, F.NUMERO
, F.COMPLEMENTO
, F.BAIRRO
, F.ID_CIDADES_UF AS UF
, F.CEP
, F.REPRESENTANTE AS CONTATO
, F.FONE_REPRESENTANTE AS PERSONAL1
, F.CEL_REPRESENTANTE AS PERSONAL2
, F.EMAIL_REPRESENTANTE AS PERSONAL3
, F.FONE_DOIS AS PERSONAL4
, F.FONE_UM AS TELEFONE
, F.CELULAR_EMPRESA AS CELULAR
, F.FAX
, F.EMAIL_EMPRESA AS EMAIL
, F.OBS AS OBSERVACOES
, CI.DESCRICAO AS CIDADE
FROM FORNECEDORES F
LEFT JOIN CIDADES CI ON CI.ID_CIDADES_IBGE = F.ID_CIDADES_IBGE