SELECT 
  P.ID_CODIGO AS CODIGO
, P.CODIGO_DE_BARRAS AS BARRAS
--, P.CODIGO_INTERNO AS COD_FABRICANTE
, P.REFERENCIA AS COD_FABRICANTE
, P.TIPO_ITEM AS PERSONAL1
, P.DESCRICAO
, P.PRECO_CUSTO 
, P.PRECO_VENDA
--, P.MARGEMLUCRO AS MARGEM_LUCRO
, P.MARKUP AS MARGEM_LUCRO
, P.QT_ESTOQUE AS QTD
, P.ESTOQUE_MINIMO AS QTD_IDEAL
, P.VL_ATACADO AS PRECO_ATACADO
, P.QT_ATACADO AS QTD_PRECO_ATACADO
, CASE P.SITUACAO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
--, , , , , , P.ID_GRADE, P.ID_IMP_RC
, P.NCM AS COD_NCM
, P.CEST AS PERSONAL6
, P.UN_COM AS UND_COMPRA
--, P.UN_TRIB AS UND
, P.ORIGEM AS OST
--, P.SIMPLES_CSOSN AS ST
--, LEFT (P.SIMPLES_ICMS_ALIQUOTA,3) AS ELO
--, P.NORMAL_CST AS ST
--, LEFT (P.NORMAL_ICMS_ALIQUOTA,3) AS ELO
, CAST(P.DATA_CADASTRO AS DATE) AS DATA_CADASTRO
, P.COD_BALANCA AS PERSONAL2
, F.RAZAOSOCIAL AS FORNECEDOR
, M.DESCRICAO_MARCA AS PERSONAL4
, C.DESCRICAO_CATEGORIA AS GRUPO
, S.DESCRICAO_SUBCATEGORIA AS FAMILIA
, UM.SIGLA AS UND
, TB.NFCE_CFOP AS CF
, LEFT (TB.NFCE_CFOP,3) AS ELO
, TB.NFCE_CSOSN AS ST
, TB.IPI_CST AS IPI_CODIGO_VENDA
, TB.IPI_ALIQUOTA AS ALIQ_IPI_VENDA
, TB.PIS_CST AS PIS_CODIGO
, TB.PIS_ALIQUOTA AS PIS_ALIQ_NOR
, TB.COFINS_CST AS COFINS_CODIGO
, TB.COFINS_ALIQUOTA AS COFINS_ALIQ_NOR
FROM PRODUTOS P
LEFT JOIN FORNECEDORES F ON F.ID = P.ID_FORNECEDOR
LEFT JOIN MARCA M ON M.ID = P.ID_MARCA
LEFT JOIN CATEGORIAS C ON C.ID = P.ID_CATEGORIA
LEFT JOIN SUBCATEGORIAS S ON S.ID = P.ID_SUBCATEGORIA AND S.ID_CATEGORIA = C.ID
LEFT JOIN UNIDADES_MEDIDAS UM ON UM.ID = P.ID_UNIDADE_MEDIDA
LEFT JOIN TF_REGRAS_TRIB TB ON TB.ID = P.ID_MATRIZ_TRIB