SELECT
MERCADORIA.COD_MERCADORIA AS CODIGO,
MERCADORIA.COD_UNIDADE AS UND,
MERCADORIA.DES_MERCADORIA AS DESCRICAO,
ESTOQUE.qtd_real_estoque AS QTD,
FORNECEDOR.nom_fornecedor AS FORNECEDOR,
ESTOQUE.VAL_PRECO_VENDA AS PRECO_VENDA,
MERCADORIA.VAL_PRECO_CUSTO AS PRECO_CUSTO,
' 00' AS ST,
'63090010' AS COD_NCM,
MAX(CODIGO_BARRAS.COD_BARRA) AS BARRAS
FROM MERCADORIA
LEFT JOIN ESTOQUE ON MERCADORIA.COD_MERCADORIA=ESTOQUE.COD_MERCADORIA
LEFT JOIN CODIGO_BARRAS ON MERCADORIA.COD_MERCADORIA=CODIGO_BARRAS.COD_MERCADORIA
LEFT JOIN FORNECEDOR ON FORNECEDOR.cod_fornecedor = MERCADORIA.cod_fornecedor
GROUP BY 1,2,3,4,5,6,7