SELECT 
  CODCLIENTE AS CODIGO
, NOMECLIENTE AS NOME
, NOMEFANTASIA AS FANTASIA
, CNPJCPF AS CNPJ_CNPF
, INSCRICAO_ESTADUAL AS IE_RG
, INSCRICAO_MUNICIPAL AS IM
, ENDERECO
, NUMERO
, COMPLEMENTO
, BAIRRO
, CIDADE
, ESTADO AS UF
, CEP
, DATANASCIMENTO AS NASCIMENTO
, TELEFONE
, CELULAR
, EMAIL
, CONTATO
, OBSERVACAO AS OBSERVACOES
, WHATSAPP AS FAX
, SEXO
, LIMITECREDITO AS LIMITE_CREDITO
FROM CLIENTE