SELECT 
  CODFORNECEDOR AS CODIGO
, NOMEFORNECEDOR AS NOME
, NOMEFANTASIA AS FANTASIA
, CNPJCPF AS CNPJ_CNPF
, INSCRICAO_ESTADUAL AS IE_RG
, INSCRICAO_MUNICIPAL AS IM
, ENDERECO
, NUMERO
, COMPLEMENTO
, BAIRRO
, CIDADE
, ESTADO AS UF
, CEP
, TELEFONE
, CELULAR
, EMAIL
, CONTATO
FROM FORNECEDOR
