SELECT 
  P.CODPRODUTO AS CODIGO
, P.PRODUTO AS DESCRICAO
, CASE P.STATUS WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.CODIGODEBARRA AS BARRAS
, P.CEANTRIB AS PERSONAL1
, P.CODIGONCM AS COD_NCM
, P.CODIGOFABRICANTE AS COD_FABRICANTE
, P.CODIGOREFERENCIA AS PERSONAL2
, P.LOCALPRODUTO AS PERSONAL4
, P.PESOBRUTO AS PESO
, P.ULTIMADATACOMPRA AS ULTIMA_COMPRA
--, RIGHT (P.CSTICMS,2) AS ST
, P.CSOSN AS ST
, P.QUANTIDADEATUAL AS QTD
, P.QUANTIDADEMIM AS QTD_IDEAL
, P.PRECOCOMPRA AS PRECO_CUSTO
--, P.CUSTOPRODUTO AS PRECO_CUSTO
, P.PRECOVENDA AS PRECO_VENDA
, P.MARGEMLUCRO AS MARGEM_LUCRO
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.CFOPNFE AS CF
, LEFT (P.CFOPNFE,3) AS ELO
--, P.CFOPNFCE AS CF
, P.IPI AS ALIQ_IPI_VENDA
, P.PIS AS PIS_ALIQ_NOR
, P.COFINS AS COFINS_ALIQ_NOR
, P.CSTIPI AS IPI_CODIGO_VENDA
, P.CSTPIS AS PIS_CODIGO
, P.CSTCOFINS AS COFINS_CODIGO
, P.CEST AS PERSONAL6
, P.ORIGEMPRODUTO AS OST
, P.PRECOVENDAATACADO AS PRECO_ATACADO
, P.COMISSAOPORCENTAGEM AS COMISSAO
, G.PRODUTO AS GRUPO
, S.PRODUTO AS FAMILIA
, U.ABREVEATURA AS UND
FROM PRODUTO P
LEFT JOIN GRUPOPRODUTO G ON G.ID = P.GRUPO
LEFT JOIN SUBGRUPOPRODUTO S ON S.ID = P.SUBGRUPO
LEFT JOIN UNIDADE U ON U.CODIGOUNID = P.CODIGOUNID