SELECT
    PRODUTO.ID AS COD_FABRICANTE,
    PRODUTO.NOME AS DESCRICAO,
    FAMILIA.nome AS GRUPO,
    CLIFOR.nome AS FORNECEDOR,
    SUM (ESTOQUE.quant_tot) AS QTD,
    PRODUTO.PRECO_VENDA1 AS PRECO_VENDA,
    PRODUTO.PRECO_CUSTO1 AS PRECO_CUSTO,
    PRODUTO.EAN13 AS BARRAS,
    PRODUTO.CST AS ST,
    PRODUTO.UNIDADE_VENDA AS UND,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN CLIFOR ON PRODUTO.ID_FORN = CLIFOR.id
LEFT JOIN FAMILIA ON PRODUTO.ID_FAMI = FAMILIA.id
LEFT JOIN ESTOQUE ON PRODUTO.ID = ESTOQUE.id_produto
GROUP BY
    PRODUTO.ID,
    PRODUTO.NOME,
    FAMILIA.nome,
    CLIFOR.nome,
    PRODUTO.PRECO_VENDA1,
    PRODUTO.PRECO_CUSTO1,
    PRODUTO.EAN13,
    PRODUTO.CST,
    PRODUTO.UNIDADE_VENDA,
    PRODUTO.NCM,
    PRODUTO.CEST
