SELECT
    PRODUTO.ID AS CODIGO,
    UNIDADE_PRODUTO.nome AS UND,
    PRODUTO.GTIN AS BARRAS,
    PRODUTO.CODIGO_INTERNO AS COD_FABRICANTE,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.REFERENCIA AS CARACTERISTICA,
    PRODUTO.QTD_ESTOQUE AS QTD,
    PRODUTO.ESTOQUE_MIN AS QTD_IDEAL,
    PRODUTO.PESO_LIQUIDO AS PESO,
    SUBSTRING (PRODUTO.CSOSN FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.CSOSN FROM 2 FOR 4) AS ST,
    PRODUTO.VALOR_MEDIO AS CUSTO_MEDIO,
    PRODUTO.VALOR_COMPRA AS PRECO_CUSTO,
    PRODUTO.VALOR_VENDA AS PRECO_VENDA,
    PRODUTO.OBSERVACAO AS OBSERVACOES,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6, 
    PRODUTO.DATA_ATUALIZA_PRECO AS ALTERACAO_PRECO,
    CAST (PRODUTO.DATA_CADASTRO AS DATE) AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN UNIDADE_PRODUTO ON UNIDADE_PRODUTO.id = PRODUTO.ID_UNIDADE_PRODUTO