SELECT 
    EST_PRODUTOS.ID_PRODUTO AS BARRAS,
    EST_PRODUTOS.NOME_PRODUTO AS DESCRICAO,
    EST_PRODUTOS.NOME_REDUZIDO AS CARACTERISTICAS,
    EST_GRUPOS.NOME_GRUPO AS GRUPO,
    EST_PRODUTOS.UNM_FI AS ELO,
    EST_PRODUTOS.PIS_COFINS AS PIS_CODIGO,
    EST_PRODUTOS.PIS_COFINS AS COFINS_CODIGO,
    CLIE_DADOS.nome_razao AS FORNECEDOR,
    EST_PRODUTOS.UNM AS UND,
    EST_ATUAL.est_atual AS QTD,
    EST_PRODUTOS.PESO_LIQUIDO AS PESO,
    EST_PRODUTOS.CEST AS PERSONAL6,
    REPLACE (EST_PRODUTOS.NCM,'.','') AS COD_NCM,
    EST_PRECOS.EPCUSTO AS PRECO_CUSTO,
    EST_PRECOS.EPMARKUP AS MARGEM_LUCRO,
    EST_PRECOS.EPVENDA AS PRECO_VENDA,
    EST_PRECOS.EPPROMOCAO AS PRECO_ATACADO,
    EST_PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    EST_PRECOS.EPUSUA_ALTERACAO AS ALTERACAO_PRECO,
    EST_PRODUTOS.PERC_COMISSAO AS COMISSAO,
    EST_PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    EST_PRODUTOS.ID_PRODUTO AS COD_FABRICANTE,
    EST_PRODUTOS.OBSERVACAO AS OBSERVACOES,
   SUBSTRING (EST_PRODUTOS.CSOSN FROM 2 FOR 4) AS ST
FROM EST_PRODUTOS
LEFT JOIN EST_GRUPOS ON EST_GRUPOS.ID_GRUPOS = EST_PRODUTOS.GRUPOS
LEFT JOIN CLIE_DADOS ON CLIE_DADOS.id_cliente = EST_PRODUTOS.cod_fornecedor
LEFT JOIN EST_ATUAL ON EST_ATUAL.ID_PRODUTO = EST_PRODUTOS.ID_PRODUTO
LEFT JOIN EST_PRECOS ON EST_PRECOS.ID_PRODUTO = EST_PRODUTOS.ID_PRODUTO
WHERE EST_ATUAL.ID_LOJA = '1' AND EST_PRECOS.ID_LOJA = '1'
