SELECT TPRODUTOS.PROCOD AS COD_FABRICANTE,
TPRODUTOS.PRODESCRICAO AS DESCRICAO,
TGRUPO.GRPNOME AS GRUPO,
TPRODUTOS.PROUNIVDA AS UND,
TPRODUTOS.PROESTATU AS QTD,
TPRODUTOS.PROBARRASUNI AS BARRAS,
TPRODUTOS.PROPRECOVD1 AS PRECO_VENDA,
TPRODUTOS.PROCUSTOATUUNI AS PRECO_CUSTO,
TPRODUTOS.PROCEST AS PERSONAL6
FROM TPRODUTOS
LEFT JOIN TGRUPO ON TPRODUTOS.PROGRUPO=TGRUPO.GRPCOD
