SELECT 
  CODIGO
, NOME
, FANTASIA
, BAIRRO
, CELULAR
, CEP
, CIDADE
, UF
, EMAIL
, ENDERECO
, PONT_REF AS COMPLEMENTO
, FAX
, TEL AS TELEFONE
, CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
, OBS_DATA1 AS OBSERVACOES
, INSC_RG AS IE_RG
, CONTATO
, CEL_REP AS CELULAR
FROM FORNECEDO
