SELECT 
  CODIGO
, MARCA AS CARACTERISTICAS
, DATA_INC AS DATA_CADASTRO
, NOME AS DESCRICAO
, NOMEGRUPO AS GRUPO
, P_CUSTO AS PRECO_CUSTO
, MARGEM_LUCRO
, CUSTO_MEDIO
, P_VENDA1 AS PRECO_VENDA
, P_VENDA2 AS PERSONAL1
--, FORNECEDOR
--, PESO_BRUTO AS PESO
, REFERENCIA AS COD_FABRICANTE
--, COD_FORN
, CODIGO_BARRA AS BARRAS
, ESTOQUE_MINIMO AS QTD_IDEAL
, COMISSAO
, ESTOQUE1 AS QTD
, TIPO_UND_COMPRA AS UND_COMPRA
, TIPO_UND_VENDA AS UND
--, DATAULTCOMP AS ULTIMA_COMPRA
--, DATAULTVENDA AS ULTIMA_VENDA
, NCM AS COD_NCM
, LEFT (REPLACE (CFOP_VENDAS, '.', ''), 3) AS ELO
, TRIBUTADA_SAIDA AS ST
, COD_CEST AS PERSONAL6
--, IPI_SAIDA 
--, SITUACAO_IPI_ENTRADA
--, SITUACAO_IPI_SAIDA
--, IPI_ENTRADA
--, NOME_IPI_ENTRADA
FROM ITEM
