SELECT PRODUTOS.CODIGO,
PRODUTOS.COD_BARRA AS BARRAS,
PRODUTOS.NOME AS DESCRICAO,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.UNID_COMPRA AS UND_COMPRA,
PRODUTOS.CUSTO AS PRECO_CUSTO,
PRODUTOS.PRECO_VENDA,
PRODUTOS.POS_ESTOQUE AS QTD,
PRODUTOS.DATA AS DATA_CADASTRO
FROM PRODUTOS



