SELECT
    PRODUTOS.COD_PRODUTO AS CODIGO,
    GRUPOS.DESCRICAO AS GRUPO,
    SUBGRUPOS.DESCRICAO AS FAMILIA,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.UNITARIO AS PRECO_VENDA,
    PRODUTOS.CUSTO_PRODUTO AS PRECO_CUSTO,
    SUBSTRING (PRODUTOS.CL_FISCAL FROM 1 FOR 10) AS COD_NCM,
    CLASSIFICACOES_FISCAIS.CEST AS PERSONAL6,
    CLASSIFICACOES_FISCAIS.ST_ICMS AS ST,
    PRODUTOS.COD_PROD_NO_FORNECEDOR AS BARRAS,
    PRODUTOS.DATA_ULTIMA_ALTERACAO AS ALTERACAO_PRECO,
    case when PRODUTOS.ATIVO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO,
    PRODUTOS.ATIVO,
    PRODUTOS.COD_CLASSIFICACAO,
    PRODUTOS.OBSERVACOES AS OBSEFVACOES,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO
FROM PRODUTOS
LEFT JOIN CLASSIFICACOES_FISCAIS ON CLASSIFICACOES_FISCAIS.COD_CLASSIFICACAO = PRODUTOS.COD_CLASSIFICACAO
LEFT JOIN GRUPOS ON GRUPOS.COD_GRUPO = PRODUTOS.COD_GRUPO_PRODUTO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.COD_SUBGRUPO = PRODUTOS.COD_SUBGRUPO
