SELECT
  PROD.CODI AS CARACTERISTICAS,
  PROD.COBA AS BARRAS,
  PROD.NOMA AS DESCRICAO,
  PROD.UNME AS UND,
  PROD.CMED AS CUSTO_MEDIO,
  PROD.VVEN AS PRECO_VENDA,
  PROD.QEST AS QTD,
  PROD.DUEN AS ULTIMA_COMPRA,
  GRUP.NOME AS GRUPO,
  SUBG.NOME AS FAMILIA,
  PROD.FOR1 AS FORNECEDOR,
  PROD.CODI AS COD_FABRICANTE,
  PROD.DTCA AS DATA_CADASTRO,
  PROD.CLFI AS COD_NCM,
  CLFI.CEST AS PERSONAL6
FROM PROD
LEFT JOIN CLFI ON CLFI.CODI = PROD.CLFI
LEFT JOIN GRUP ON GRUP.CODI = PROD.GRUP
LEFT JOIN SUBG ON SUBG.CODI = PROD.SUBG
