SELECT 
  C.ID_CLIENTE as CODIGO
, C.NOME
, C.NOME_CARTAO as FANTASIA
, C.CNPJ_CPF as CNPJ_CNPF
, case when C.INSCRICAO_ESTADUAL = ''
		or C.INSCRICAO_ESTADUAL = 'ISENTO'
		or C.INSCRICAO_ESTADUAL is null
		then C.IE_RG
		else C.INSCRICAO_ESTADUAL 
		END as IE_RG
, C.NOME_CONJUGE as CONJUGE
, C.ENDERECO
, C.NUMERO
, C.COMPLEMENTO
, C.BAIRRO
, C.CIDADE
, C.UF
, C.CEP
, C.FONE_RESIDENCIAL as TELEFONE
, C.CONTATO_FONE as CONTATO
, C.FONE_CELULAR as CELULAR
, C.EMAIL
, C.ENDERECO_COBRANCA as COB_ENDERECO
, C.COMPLEMENTO_COBRANCA as COB_COMPLEMENTO
, C.CIDADE_COBRANCA as COB_CIDADE
, C.BAIRRO_COBRANCA as COB_BAIRRO
, C.CEP_COBRANCA as COB_CEP
, C.DATA_INCLUSAO as CADASTRO
, C.OBSERVACAO as OBSERVACOES
, C.PROFISSAO
, C.LIMITE as LIMITE_CREDITO
, C.DATA_ULTIMA_COMPRA as ULTIMA_VENDA
, C.NOME_PAI as PAI
, C.NOME_MAE as MAE
, C.DATA_NASCIMENTO as NASCIMENTO 
FROM GEN_CLIENTES C
