SELECT 
  F.ID_FORNECEDOR as CODIGO
, F.NOME
, F.DESCRICAO as FANTASIA
, F.CNPJ as CNPJ_CNPF
, F.INSCRICAO_ESTADUAL as IE_RG
, F.ESTADO as UF
, F.CIDADE
, F.ENDERECO
, F.NUMERO
, F.BAIRRO
, REPLACE(F.CEP, '.', '') as CEP
, F.TELEFONE
, F.TELEFONE2 as CELULAR
, F.FAX
, F.EMAIL
, F.CONTATO
, F.OBSERVACAO as OBSERVACOES
, F.REPRESENTANTE as PERSONAL1
, F.FONE_REPRESENTANTE as PERSONAL2
FROM GEN_FORNECEDOR F
