SELECT
       PRODUTOS.PR_CODIGO AS CODIGO,
       PRODUTOS.PR_CODIGO AS COD_FABRICANTE,
       PRODUTOS.PR_CODBARRA AS BARRAS,
       PRODUTOS.PR_NOME AS DESCRICAO,
       GRUPOS.GR_NOME AS GRUPO,
       SUBGRUPOS.SG_NOME AS FAMILIA,
       SUBSTRING (TRIBUTACAO.TR_NOME FROM 1 FOR 1) AS ST,
       PRODUTOS.PR_UNIDADE AS UND,
       SUM (PRODFILIAL.PF_ATUAL) AS QTD,
       PRODUTOS.PR_NCM AS COD_NCM,
       PRODUTOS.PR_PRECOCUST AS PRECO_CUSTO,
       PRODUTOS.PR_PRECOVEND AS PRECO_VENDA,
       PRODUTOS.PR_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.TR_CODIGO = PRODUTOS.PR_TRIBUT
LEFT JOIN GRUPOS ON GRUPOS.GR_CODIGO = PRODUTOS.PR_GRUPO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.SG_CODIGO = PRODUTOS.PR_SUBGRUPO
LEFT JOIN PRODFILIAL ON PRODFILIAL.PF_PRODUTO = PRODUTOS.PR_CODIGO
GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13
