SELECT 
    TRANSPORTADORAS.TR_CODIGO AS CODIGO,
    TRANSPORTADORAS.TR_NOME AS RAZAO_SOCIAL,
    TRANSPORTADORAS.TR_ENDERECO AS ENDERECO,
    TRANSPORTADORAS.TR_CIDADE AS CIDADE,
    TRANSPORTADORAS.TR_UF AS UF,
    case when TRANSPORTADORAS.TR_CPF = '' or TRANSPORTADORAS.TR_CPF is null then TRANSPORTADORAS.TR_CGC else TRANSPORTADORAS.TR_CPF END AS CNPJ,
    TRANSPORTADORAS.TR_INSCRICAO AS IE,
    TRANSPORTADORAS.TR_FONE AS TELEFONE,
    TRANSPORTADORAS.TR_EMAIL AS EMAIL
FROM TRANSPORTADORAS
