SELECT PRODUTO.CODBARRA AS BARRAS,
PRODUTO.DESCRICAO AS DESCRICAO,
PRODUTO.UNITARIO AS PRECO_VENDA,
PRODUTO.UNIDADE AS UND,
PRODUTO.CUSTO AS PRECO_CUSTO,
PRODUTO.NCM AS COD_NCM,
PRODUTO.ID_PRODUTO AS COD_FABRICANTE
FROM PRODUTO

