SELECT
	C.CAD_IDCADASTRO AS CODIGO,
	C.CAD_NOME AS NOME,
	C.CAD_NOMEFANTASIA AS FANTASIA,
	C.CAD_CPFCNPJ AS CNPJ_CNPF,
	C.CAD_RG_INSC AS IE_RG,
	C.CAD_INSCMUNICIPAL AS IM,
	COALESCE(C.CAD_DDD, '')||COALESCE(C.CAD_TELEFONE, '') AS TELEFONE,
	C.CAD_NUMEROCASA AS NUMERO,
	C.CAD_COMPLEMENTO AS COMPLEMENTO,
	C.CAD_EMAIL AS EMAIL,
	C.CNH AS PERSONAL1,
	C.CAD_APELIDO AS CONTATO,
	C.NUMEROCARTAOIDENTIFID AS PERSONAL2,
	C.CAD_CRC AS PERSONAL3,
	C.CAD_CPF AS PERSONAL4,
	C.CAD_CNPJ AS PERSONAL5,
	C.TELEFONEWATSAP AS PERSONAL6,
	CE.END_LOGRADOURO AS ENDERECO,
	CE.END_BAIRRO AS BAIRRO,
	CE.END_CEP AS CEP,
	CE.END_UF AS UF,
	CI.CID_NOME AS CIDADE,
	C3.OBS_OBSERVACAO AS OBSERVACOES
FROM
	CADASTRO C
LEFT JOIN CADASTROENDERECO CE ON CE.END_IDCADASTRO = C.CAD_IDCADASTRO 
LEFT JOIN CADASTROCIDADE CI ON CI.CID_IDCIDADE = CE.END_IDCIDADE
LEFT JOIN CADASTROOBSERVACAO C3 ON C3.OBS_IDCADASTRO = C.CAD_IDCADASTRO 
WHERE CAD_TIPO = 'F'