SELECT
  CLIENTES.CODCLIENTE AS PERSONAL2,
  CLIENTES.NOME AS NOME,
  CLIENTES.FANTASIA AS FANTASIA,
  CLIENTES.ENDERECO AS ENDERECO,
  BAIRROS.DESCRICAO AS BAIRRO,
  CLIENTES.END_NRO AS NUMERO,
  CLIENTES.END_COMPL ||' - '|| CLIENTES.END_APTO AS COMPLEMENTO,
  CIDADES.CIDADE AS CIDADE,
  CIDADES.UF AS UF,
  REPLACE (CLIENTES.CEP, '.' , '') AS CEP,
  CLIENTES.FONE AS TELEFONE,
  CLIENTES.CELULAR  AS CELULAR,
  CLIENTES.FAX AS FAX,
  CLIENTES.CNPJ AS CNPJ_CNPF,
  CLIENTES.IE AS IE_RG,
  CLIENTES.EMAIL AS EMAIL,
  CLIENTES.CONTATO AS CONTATO,
  CLIENTES.DATACADASTRO AS CADASTRO,
  CLIENTES.OBS AS OBSERVACOES,
  CLIENTES.SEXO AS SEXO,
  CLIENTES.CONJNOME AS CONJUGE,
  CLIENTES.NOME_PAI AS PAI,
  CLIENTES.NOME_MAE AS MAE
FROM CLIENTES
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = CLIENTES.CODCIDADE
LEFT JOIN BAIRROS ON BAIRROS.CODBAIRRO = CLIENTES.CODBAIRRO