SELECT
  FORNECEDORES.CODFORNEC AS PERSONAL2,
  FORNECEDORES.NOME AS NOME,
  FORNECEDORES.FANTASIA AS FANTASIA,
  FORNECEDORES.ENDERECO AS ENDERECO,
  BAIRROS.DESCRICAO AS BAIRRO,
  CIDADES.CIDADE AS CIDADE,
  CIDADES.UF AS UF,
  REPLACE (FORNECEDORES.CEP, '.' , '') AS CEP,
  FORNECEDORES.CNPJ AS CNPJ_CNPF,
  FORNECEDORES.IE AS IE_RG,
  FORNECEDORES.FONE AS TELEFONE,
  FORNECEDORES.FAX AS FAX,
  FORNECEDORES.FONE1 AS CELULAR,
  FORNECEDORES.CONTATO1 AS CONTATO,
  FORNECEDORES.EMAIL AS EMAIL,
  FORNECEDORES.OBS AS OBSERVACOES,
  FORNECEDORES.IM AS IM,
  FORNECEDORES.COMPL AS COMPLEMENTO,
  FORNECEDORES.ENDERECO_NRO AS NUMERO
FROM FORNECEDORES
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = FORNECEDORES.CODCIDADE
LEFT JOIN BAIRROS ON BAIRROS.CODBAIRRO = FORNECEDORES.CODBAIRRO