SELECT
  PRODUTOS.CODPRODUTO AS COD_FABRICANTE,
  PRODUTOS.PRODUTO AS DESCRICAO,
  FORNECEDORES.NOME AS FORNECEDOR,
  PRODUTOS.PRECOTABELA AS PRECO_VENDA,
  PRODUTOS.UN AS UND,
  PRODUTOS.CODNCM AS COD_NCM,
  PRODUTOS.CODSITTRIB AS ST,
  PRODUTOS.CODBARRAS AS BARRAS,
  PRODUTOS.REFERENCIA AS CARACTERISTICAS,
  PRODUTOS.DATA_ATUALIZACAO AS ALTERACAO_PRECO,
  PRODUTOS.PESO AS PESO,
  PRODUTOS.NROSEQUENCIAL AS CODIGO,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODFORNEC = PRODUTOS.CODFORNEC