SELECT 
  F.FRN_CODIGO AS CODIGO
, F.FRN_REPRESENTANTE AS CONTATO
, F.FRN_RAZAOSOCIAL AS NOME
, F.FRN_NOMEFANTASIA AS FANTASIA
, F.FRN_ENDERECO AS ENDERECO
, F.FRN_LOGRADOURO AS PERSONAL1
, F.FRN_NUMERO AS NUMERO
, F.FRN_COMPLEMENTO AS COMPLEMENTO
, F.FRN_BAIRRO AS BAIRRO
, F.FRN_TELEFONE AS TELEFONE
, F.FRN_CEP AS CEP
, CASE WHEN F.FRN_CPF = '' OR F.FRN_CPF IS NULL THEN F.FRN_CNPJ ELSE F.FRN_CPF END AS CNPJ_CNPF
, CASE WHEN F.FRN_RG = '' OR F.FRN_RG IS NULL THEN F.FRN_INSCRICAO ELSE F.FRN_RG END AS IE_RG
, F.FRN_EMAIL AS EMAIL
, F.FRN_NOMEREPRESENTANTE AS PERSONAL2
, F.FRN_FONEREPRESENT AS PERSONAL3
, F.FRN_FAXREPRESENT AS FAX
, F.FRN_EMAILREPRESENT AS PERSONAL4
, F.FRN_INFCOMPLEMENTARES AS OBSERVACOES
, CI.CID_NOME AS CIDADE
, CI.CID_UF AS UF
FROM FORNECEDORES F
LEFT JOIN CIDADES CI ON CI.CID_CODIGO = F.FRN_CID_CODIGO 
