SELECT
    CP.DOCUMENTO || CP.PARCELA AS DOCUMENTO,
    CP.DATALANC AS EMISSAO,
    CP.DATAVENC AS VENCIMENTO,
    CP.DATAPGTO AS PAGAMENTO,
    CP.TIPODOCTO AS TIPO_DOC,
    CP.VALOR AS VALOR_DUP,
    CP.VALORPAGO AS VALOR_PAG,
    CP.OBSERVAC AS OBSERVACOES,
    CP.CENTRO AS CTO_CUSTO,
    CP.PARCELA ||'/'||CP.DOCFOR ||'/'|| CP.IDTITULO AS HISTORICO,
    CAST (CF.CODIGO AS VARCHAR (6)) AS COD_FORNECEDOR,
    SUBSTRING (CF.RAZAO FROM 1 FOR 60) AS NOM_FORNECEDOR,
    CF.CNPJ AS CNPJ
FROM CPAGAR AS CP
LEFT JOIN CADFOR CF ON CP.CODFORN = CF.CODIGO