SELECT
    replace(P.CODIGO,'-','') AS CODIGO,
    --SUBSTRING (P.CODIGO FROM 1 FOR 5) AS CODIGO,
    P.DESCRICAO AS DESCRICAO,
    P.MARCA AS CARACTERISTICAS,
    P.REFERENC AS COD_FABRICANTE,
    P.UNIDADE AS UND,
    GRUPOS.DESCRICAO AS GRUPO,
    SUBGRUPOS.descricao AS FAMILIA,
    P.PRECOCUS AS PRECO_CUSTO,
    P.PRECOVDA AS PRECO_VENDA,
    P.ESTOQUE AS QTD,
    P.DTULTVDA AS ULTIMA_VENDA,
    P.DATACAD AS DATA_CADASTRO,
    case when P.SITUACAO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO,
    P.CODBARRAS AS BARRAS,
    P.PRECOREVENDA AS PRECO_ATACADO,
    P.CUSTOMEDIO AS CUSTO_MEDIO,
    P.DTUCOMPRA AS ULTIMA_COMPRA,
    P.SITTRIB AS ST,
    P.CFOPDE AS CF,
    P.ESTMINIMO AS QTD_IDEAL,
    P.CLASSIFICACAO AS COD_NCM,
    MAX (CADCEST.CEST) AS PERSONAL6,
    P.ANOTACOES AS OBSERVACOES,
    CAST (P.DTALTERACAO AS DATE) AS ALTERACAO_PRECO,
    P.PESOLIQUIDO AS PESO,
    P.GTIN_CODBARRAS AS PERSONAL4
FROM CADPRO AS P
LEFT JOIN GRUPOS ON CAST(GRUPOS.CODIGO AS VARCHAR (5)) = P.GRUPO
LEFT JOIN SUBGRUPOS ON CAST (SUBGRUPOS.codigo AS VARCHAR (5)) = P.subgrupo AND SUBGRUPOS.grupo = GRUPOS.codigo
LEFT JOIN CADCEST ON CADCEST.ncm = P.CLASSIFICACAO
WHERE P.CODIGO > '00000'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26