SELECT
    CR.DOCUMENTO || CR.PARCELA AS DOCUMENTO,
    CR.PARCELA AS NUM_PARCELA,
    CAST (CC.CODIGO AS VARCHAR (6)) AS COD_CLIENTE,
    SUBSTRING (CC.RAZAO FROM 1 FOR 60) AS NOM_CLIENTE,
    CC.CNPJ AS CNPJ,
    CR.DATALANC AS EMISSAO,
    CR.DATAVENC AS VENCIMENTO,
    CR.DATARECTO AS RECEBIMENTO,
    CR.TIPODOCTO AS TIPO_DOC,
    CR.VALOR AS VALOR_DUP,
    CR.VALORPAGO AS VALOR_REC,
    CR.DESCONTO AS VALOR_DES,
    CR.ACRESCIMO AS VALOR_JUR,
    CR.OBSERVAC AS OBSERVACOES,
    CR.CENTRO AS CTO_CUSTO,
    CR.NOSSONUMERO AS NOSSO_NUM,
    CR.IDTITULO ||'/'||CR.PARCELA AS HISTORICO
FROM CRECEB AS CR
LEFT JOIN CADCLI CC ON CR.CODCLIE = CC.CODIGO