SELECT 
       CLIENTES.CODIGO AS CODIGO
      ,CLIENTES.NOME AS FANTASIA
      ,CLIENTES.RAZAO AS NOME
      ,CLIENTES.FONE AS TELEFONE
      ,CLIENTES.CELULAR AS CELULAR
      ,CLIENTES.FAX AS FAX
      ,CLIENTES.CONTATO AS CONTATO
      ,CLIENTES.EMAIL AS EMAIL
      ,CLIENTES.ENDERECO AS ENDERECO
      ,CLIENTES.CEP AS CEP
      ,CLIENTES.BAIRRO AS BAIRRO
      ,CLIENTES.CIDADE AS CIDADE
      ,CLIENTES.ESTADO AS UF
      ,CLIENTES.INS_RG AS IE_RG
      ,CLIENTES.CGC_CPF AS CNPJ_CNPF
      ,CLIENTES.N_PAI AS PAI
      ,CLIENTES.N_MAE AS MAE
      ,CLIENTES.NATURALID AS NATURALIDADE
      ,CAST (CLIENTES.DATA_NASC AS DATE) AS NASCIMENTO
      ,CAST (CLIENTES.DATA_CAD AS DATE) AS CADASTRO
      ,CLIENTES.EST_CIVIL AS EST_CIVIL
      ,CLIENTES.CONJUGE AS CONJUGE
      ,CLIENTES.NUMERO_END AS NUMERO
      ,CLIENTES.INSC_MUNICIPAL AS IM
      ,CLIENTES.SEXO AS SEXO
  FROM SCEVET.dbo.CLIENTES
  WHERE CLIENTES.CODIGO > '0'
