SELECT 
       PRODUTOS.CODIGO AS CODIGO
      ,PRODUTOS.NOME AS DESCRICAO
      ,MARCAS.NOME AS CARACTERISTICAS
      ,GRUPOS.NOME AS GRUPO
      ,SUB_GRUPOS.NOME AS FAMILIA
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.ALTERNATI AS COD_FABRICANTE
      ,PRODUTOS.CBARRA AS BARRAS
     ,PRODLOJAS.EST_MINIM AS QTD_IDEAL
      ,PRODLOJAS.PCO_COMPRA AS PRECO_CUSTO    
      ,PRODLOJAS.PCO_VENDA AS PRECO_VENDA   
      ,PRODLOJAS.EST_ATUAL AS QTD
     ,PRODUTOS.COD_CSTORIGEM AS OST
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.PESO_LIQ AS PESO
      ,PRODUTOS.UNIDADE_COMPRA AS UND_COMPRA
      ,PRODUTOS.CODIGO_NCM AS COD_NCM
      ,PRODUTOS.COD_CEST AS PERSONAL6
  FROM SCEVET.dbo.PRODUTOS
  LEFT JOIN SCEVET.dbo.GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO
  LEFT JOIN SCEVET.dbo.SUB_GRUPOS ON SUB_GRUPOS.CODIGO = PRODUTOS.SUBG
  LEFT JOIN SCEVET.dbo.MARCAS ON MARCAS.CODIGO = PRODUTOS.MARCA
  LEFT JOIN SCEVET.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = PRODUTOS.CODIGO