Select PAGAR.*
, FORNECEDOR.CNPJ_CNPF
, NFE_TOTAL.VALOR_TOTAL
, NFE_IDENTIFICACAO.DATA_EMISSAO
, NFE_IDENTIFICACAO.DATA_SAIDA_ENTRADA
, pc.descricao as DESC_PLACONTA
, c.descricao as DESC_CUSTO
from PAGAR
left join FORNECEDOR on FORNECEDOR.CODIGO = PAGAR.COD_FORNECEDOR
left join DOCUMENTO on DOCUMENTO.ID = PAGAR.ID_DOCUMENTO
left join NFE on NFE.ID_DOCUMENTO = DOCUMENTO.ID
left join NFE_IDENTIFICACAO on NFE_IDENTIFICACAO.ID = NFE.ID_NFE_IDENTIFICACAO
left join NFE_TOTAL on NFE_TOTAL.ID = NFE.ID_NFE_TOTAL
left join placonta pc on pc.codigo = pagar.num_conta
left join ctocusto c on c.codigo =  pagar.cto_custo
