SELECT
  PRODUTOS.id_produto AS CODIGO,
  PRODUTOS.descr_item AS DESCRICAO,
  PRODUTOS.cod_barra AS BARRAS,
  GRUPOS.DESCRICAO AS GRUPO,
  --PRODUTOS.saldo AS QTD,
  PRODUTOS.custo AS PRECO_CUSTO,
  PRODUTOS.pr_avista AS PRECO_VENDA,
  PRODUTOS.cod_ncm AS COD_NCM,
  PRODUTOS.cest AS PERSONAL6,
  PRODUTOS.cst_icms AS ST,
  PRODUTOS.unidade AS UND,
  PRODUTOS.margem AS MARGEM_LUCRO,
  PRODUTOS.codfor AS COD_FABRICANTE,
  PRODUTOS.marca AS CARACTERISTICAS
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO = GRUPOS.CODIGO
