SELECT
  PRODUTOS.ProdutoID AS CODIGO,
  PRODUTOS.ProdutoNome AS DESCRICAO,
  PRODUTOS.CodigoBarra AS BARRAS,
  PRODUTOS.Referencia AS COD_FABRICANTE,
  UNIDADES.UNIDADESIGLA AS UND,
  PRODUTOS.ValorCusto AS PRECO_CUSTO,
  PRODUTOS.ValorVenda AS PRECO_VENDA,
  PRODUTOS.Estoque AS QTD,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.CEST AS PERSONAL6,
  PRODUTOS.CSOSN AS ST
FROM PRODUTOS
LEFT JOIN UNIDADES ON PRODUTOS.UNIDADE = UNIDADES.UNIDADEID