SELECT
  PRODUTO.CODIGO AS CODIGO,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.DESCRICAORESUMIDA AS CARACTERISTICAS,
  PRODUTO.MEDIDA AS UND,
  PRODUTO.REFERENCIA AS COD_FABRICANTE,
  GRUPO.DESCRICAO AS GRUPO,
  SUBGRUPO.DESCRICAO AS FAMILIA,
  PRODUTO_LOJA.CUSTO AS PRECO_CUSTO,
  PRODUTO_LOJA.LUCROPORC AS MARGEM_LUCRO,
  PRODUTO_LOJA.VENDA AS PRECO_VENDA,
  PRODUTO_LOJA.OBSERVACAO AS OBSERVACOES,
  PRODUTO_LOJA.QUANTIDADE AS QTD,
  SUBSTRING(PRODUTO.CST FROM 1 FOR 1) AS OST,
  SUBSTRING(PRODUTO.CST FROM 2 FOR 3) AS ST,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.CEST AS PERSONAL6,
  PRODUTO.CODIGO_BARRAS AS BARRAS
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.CODGRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CODIGO = PRODUTO.CODSUBGRUPO
LEFT JOIN PRODUTO_LOJA ON PRODUTO_LOJA.CODPROD = PRODUTO.CODIGO