SELECT
	F.CODIGO AS CODIGO,
	F.NOME AS NOME,
	F.CONTATO AS CONTATO,
	F.ENDERECO AS ENDERECO,
	F.BAIRRO AS BAIRRO,
	F.CEP AS CEP,
	F.CNPJ AS CNPJ_CNPF,
	F.TELEFONE AS TELEFONE,
	F.FAX AS FAX,
	F.RAZAOSOCIAL AS FANTASIA,
	F.IE AS IE_RG,
	F.EMAIL AS EMAIL,
	F.OBSERVACAO AS OBSERVACOES,
	F.NUMERO AS NUMERO,
	F.IM AS IM,
	F.COMPLEMENTO AS COMPLEMENTO,
	CI.CIDADE AS CIDADE,
	CI.UF AS UF
FROM FORNECEDORES F
LEFT JOIN CIDADES CI ON F.CODCIDADE = CI.CODCIDADE 
