SELECT
  CADASTROFORNECEDOR.CODIGO AS CODIGO,
  CADASTROFORNECEDOR.NOMEFORNECEDOR AS NOME,
  case when CADASTROFORNECEDOR.CPF ='' then CADASTROFORNECEDOR.CNPJ else   CADASTROFORNECEDOR.CPF end as CNPJ_CNPF,
  CADASTROFORNECEDOR.ENDERECO AS ENDERECO,
  CADASTROFORNECEDOR.BAIRRO AS BAIRRO,
  CADASTROFORNECEDOR.CIDADE AS CIDADE,
  CADASTROFORNECEDOR.ESTADO AS UF,
  CADASTROFORNECEDOR.NUMERO AS NUMERO,
  CADASTROFORNECEDOR.IE AS IE_RG,
  CADASTROFORNECEDOR.REPRESENTANTE AS CONTATO,
  CADASTROFORNECEDOR.FONE1 AS TELEFONE,
  CADASTROFORNECEDOR.FONE2 AS CELULAR,
  CADASTROFORNECEDOR.FAX AS FAX,
  CADASTROFORNECEDOR.CEP AS CEP,
  CADASTROFORNECEDOR.EMAIL AS EMAIL,
  CADASTROFORNECEDOR.OBS AS OBSERVACOES
FROM CADASTROFORNECEDOR
