SELECT 
  P.IDPRODUTO
, P.CODIGOBARRA AS BARRAS  
, P.ESTOQUEATUAL AS QTD
, P.OBS AS OBSERVACOES
, P.LOCALIZACAO AS PERSONAL1
, F.RAZAO_SOCIAL AS FORNECEDOR
, P.REFERENCIA AS COD_FABRICANTE
, M.DESCRICAO ||' - '|| C.DESCRICAO || '/' || T.DESCRICAO AS DESCRICAO
, M.CLASSIFICACAO AS COD_NCM
, P.STATUS
, CASE P.STATUS WHEN 'I' THEN 'Inativo' ELSE 'Ativo' END AS SITUACAO
, M.PESOBRUTO AS PESO
--, P.UNIDADE AS UND
, M.UNIDADE AS UND
, M.PRECO AS PRECO_VENDA
--, P.CUSTOPRODUTO AS PRECO_CUSTO
, M.CUSTO_VLR_CUSTO AS PRECO_CUSTO
, M.CODGTIN AS PERSONAL2
, M.CEST AS PERSONAL6
, M.NFCE_IPI AS ALIQ_IPI_VENDA
, M.NFCE_PIS AS PIS_ALIQ_NOR
, M.NFCE_COFINS AS COFINS_ALIQ_NOR
, M.NFCE_CSTPIS AS PIS_CODIGO
, M.NFCE_CSTCOFINS AS COFINS_CODIGO
--, M.NFCE_CST AS ST
, M.NFCE_CSOSN AS ST
--, P.ESTOQUEMIN AS QTD_IDEAL
, M.ESTOQUEMINIMO AS QTD_IDEAL 
, G.DESCRICAO AS GRUPO
, S.DESCRICAO AS FAMILIA
, T.DESCRICAO AS TAMANHO
, T.DESCRICAO AS PERSONAL5
, C.DESCRICAO AS COR
FROM PRODUTO P
LEFT JOIN PESSOA F ON F.IDPESSOA = IDFORNECEDOR
LEFT JOIN MERCADORIA M ON M.IDMERCADORIA = P.IDMERCADORIA 
LEFT JOIN GRUPO G ON G.IDGRUPO = M.IDGRUPO 
LEFT JOIN SUBGRUPO S ON S.IDSUBGRUPO = M.IDSUBGRUPO 
LEFT JOIN TAMANHO T ON T.IDTAMANHO = P.IDTAMANHO 
LEFT JOIN CORES C ON C.IDCORES = P.IDCORES
