SELECT
  PRODUTOS.CODIGO AS CODIGO,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  GRUPOS.NOME AS GRUPO,
  PRODUTOS.UNIDADE AS UND,
  PRODUTOS.CUSTO AS PRECO_CUSTO,
  PRODUTOS.VENDA AS PRECO_VENDA,
  SUBSTRING (PRODUTOS.SITUACAOTRIBUTARIA FROM 2 FOR 3) AS ST,
  PRODUTOS.OBSERVACOES AS OBSERVACOES,
  CAST (PRODUTOS.ULTIMACOMPRA  AS DATE) AS ULTIMA_COMPRA,
  CAST (PRODUTOS.ULTIMAVENDA  AS DATE) AS ULTIMA_VENDA,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.PESO AS PESO,
  PRODUTOS.FORNECEDOR AS FORNECEDOR,
  CAST (PRODUTOS.DATA_ALT AS DATE) AS ALTERACAO_PRECO,
  PRODUTOS.CUSTOMEDIO AS CUSTO_MEDIO,
  PRODUTOS.CODIGO_BARRAS AS BARRAS,
  PRODUTOS.CODFABRICA AS COD_FABRICANTE,
  PRODUTOS.CEST AS PERSONAL6,
  case when PRODUTOS.desativado = 'N' then 'Ativo' else 'Inativo' end as situacao
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO
