SELECT
    P.PRO_CODIGO AS CODIGO,
    P.PRO_COD_BARRA AS BARRAS,
    P.PRO_NOME AS DESCRICAO,
    U.UNI_ABREV AS UND,
    P.PRO_ESTMIN AS QTD_IDEAL,
    E.EST_QTDE AS QTD,
    P.PRO_PRECUSTO AS PRECO_CUSTO,
    P.PRO_MARGEM AS MARGEM_LUCRO,
    P.PRO_PREVENDA AS PRECO_VENDA,
    FP.FAM_DESCRICAO AS GRUPO,
    T.TRB_SIM AS ST,
    P.PRO_OBS AS OBSERVACOES,
    P.PRO_REFERENCIA AS COD_FABRICANTE,
    P.CREATE_DATE AS DATA_CADASTRO,
    case when P.PRO_INATIVO = 'N' then 'Ativo' else 'Inativo' end as situacao
FROM PRODUTO AS P
LEFT JOIN TRIBUTACAO T ON P.TRB_CODIGO = T.TRB_CODIGO
LEFT JOIN FAMILIA_PROD FP ON P.FAM_CODIGO = FP.FAM_CODIGO 
LEFT JOIN UNIDADE U ON P.UNI_CODIGO = U.UNI_CODIGO
LEFT JOIN ESTOQUE E ON P.PRO_CODIGO = E.PRO_CODIGO