SELECT
    TBPRODUTOS.CODIGO AS CODIGO,
    TBPRODUTOS.DESCRICAO AS DESCRICAO,
    TBPRODUTOS.UN AS UND,
    TBPRODUTOS.CODIGOBARRA AS BARRAS,
    TBPRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
    TBPRODUTOS.ESTOQUEATUAL AS QTD,
    TBPRODUTOS.PESOLIQUIDO AS PESO,
    TBPRODUTOS.NOMEFORNECEDOR AS FORNECEDOR,
    TBGRUPOS.DESCRICAO AS GRUPO,
    TBGRUPOS.DESCRICAO AS FAMILIA,
    TBPRODUTOS.VALORCOMPRA AS PRECO_CUSTO,
    TBPRODUTOS.PRECOVENDA AS PRECO_VENDA,
    TBPRODUTOS.MARGEMLUCRO AS MARGEM_LUCRO,
    --SUBSTRING (TBICMS.ALIQUOTA_ECF FROM 1 FOR 1) AS OST,
    --SUBSTRING (TBICMS.ALIQUOTA_ECF FROM 2 FOR 3) AS ST,
    TBPRODUTOS.CST AS ST,
    TBPRODUTOS.CODIGOFORNECEDOR AS COD_FABRICANTE,
    TBPRODUTOS.DATA_ULT_COMPRA AS ULTIMA_COMPRA,
    TBPRODUTOS.DATA_ULT_SAIDA AS ULTIMA_VENDA,
    TBPRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    TBPRODUTOS.DATA_ALTERACAO AS ALTERACAO_PRECO,
    TBPRODUTOS.OBSERVACAO AS OBSERVACOES,
    TBPRODUTOS.NCM AS COD_NCM,
    TBPRODUTOS.CEST AS PERSONAL6
FROM TBPRODUTOS
LEFT JOIN TBICMS ON TBICMS.CODIGO = TBPRODUTOS.ICMS
LEFT JOIN TBGRUPOS ON TBGRUPOS.CODIGO = TBPRODUTOS.GRUPO
LEFT JOIN TBSUBGRUPO ON TBSUBGRUPO.CODIGO = TBPRODUTOS.SUBGRUPO
