SELECT
    NOME,
    FANTASIA,
    ENDERECO,
    NUMERO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    ESTADO,
    CEP,
    IE AS IE_RG,
    TEL1 AS TELEFONE,
    OBSERVACAO AS OBSERVACOES,
    EMAILS AS EMAIL,
    CONTATOS AS CONTATO
FROM FABRICANTE
