SELECT 
  ID_PSS AS CODIGO
, CASE WHEN CPF_PSS = '' OR CPF_PSS IS NULL THEN CNPJ_PSS ELSE CPF_PSS END AS CNPJ_CNPF
, CASE WHEN RG_PSS = '' OR RG_PSS IS NULL THEN IE_PSS ELSE RG_PSS END AS IE_RG
, IM_PSS AS IM
, NOME_PSS AS NOME
, APELIDO_PSS AS FANTASIA
, CEP_PSS AS CEP
, ENDERECO_PSS AS ENDERECO
, NUMERO_ENDERECO_PSS AS NUMERO
, COMPLEMENTO_ENDERECO_PSS AS COMPLEMENTO
, BAIRRO_PSS AS BAIRRO
, UF_PSS AS UF
, TELEFONE1_PSS AS TELEFONE
, TELEFONE2_PSS AS FAX
, CELULAR1_PSS AS CELULAR
, EMAIL1_PSS AS EMAIL
, CASE STATUS_PSS WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, LIMITE_PSS AS LIMITE_CREDITO
, DATA_ULTIMACOMPRA_PSS AS ULTIMA_VENDA
, CAST (DATA_CADASTRO_PSS AS DATE) AS CADASTRO
, SEXO_PSS AS SEXO
, ISENTO_ICMS_PSS AS INDIEDEST
, DATA_NASCIMENTO_PSS AS NASCIMENTO
, NOME_PAI_PSS AS PAI
, NOME_MAE_PSS AS MAE
, OBSERVACOES_PSS AS OBSERVACOES
, CONTATO_PSS AS CONTATO
, NOME_CONJUGUE_PSS AS CONJUGE
, C.NOME_CDD AS CIDADE 
FROM PESSOAS P
LEFT JOIN CIDADES C ON C.ID_CDD = P.ID_CDD  
WHERE TIPO_PSS = 'C'
