SELECT EMPRESAS.CODIGO,
EMPRESAS.EMPRESA AS NOME,
EMPRESAS.LOGRADOURO AS ENDERECO,
EMPRESAS.NUMERO,
EMPRESAS.COMPLEMENTO,
EMPRESAS.CIDADE,
EMPRESAS.BAIRRO,
EMPRESAS.UF,
EMPRESAS.CEP,
EMPRESAS.TELEFONE,
EMPRESAS.CNPJ AS CNPJ_CNPF,
EMPRESAS.INSC_ESTADUAL AS IE_RG
FROM EMPRESAS


