SELECT
  MIN (PESSOA.CODIGO) AS CODIGO,
  PESSOA.NOME AS NOME,
  PESSOA.NOMEUSUAL AS CONTATO,
  PESSOA.CPF_CNPJ AS CNPJ_CNPF,
  PESSOA.IE AS IE_RG,
  PESSOA.IM AS IM,
  PESSOA.LOGRADOURO AS ENDERECO,
  PESSOA.NUMIMOVEL AS NUMERO,
  PESSOA.COMPENDERECO AS COMPLEMENTO,
  PESSOA.BAIRRO AS BAIRRO,
  PESSOA.CEP AS CEP,
  LOCALIDADE.NOME AS CIDADE,
  UF.SIGLA AS UF,
  PESSOA.CLIENTE,
  PESSOA.FORNECEDOR,
  PESSOA.TRANSPORTADOR,
  PESSOA.OBS AS OBSERVACOES,
  PESSOA.DATACAD AS CADASTRO,
  PESSOA.TELEFONE AS TELEFONE,
  PESSOA.EMAIL AS EMAIL
FROM PESSOA
LEFT JOIN LOCALIDADE ON LOCALIDADE.ID = PESSOA.LOCALIDADE_ID
LEFT JOIN UF ON UF.ID = LOCALIDADE.UF_ID
WHERE PESSOA.CLIENTE = '1' 
GROUP BY 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
