SELECT
  PRODUTO.ID AS CODIGO,
  PRODUTO.CODIGO AS COD_FABRICANTE,
  PRODUTO.CODIGOBARRAS AS BARRAS,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.UNIDADE AS UND,
  FABRICANTE.NOME AS CARACTERISTICAS,
  GRUPOPRODUTO .NOME AS GRUPO,
  PRODUTO.ST AS ST,
  PRODUTO.PESOLIQUIDO AS PESO,
  PRODUTO.ESTOQUE AS QTD,
  PRODUTO.ESTOQUEMIN AS QTD_IDEAL,
  PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
  PRODUTO.PRECOVENDA AS PRECO_VENDA,
  NCM.CODIGO AS COD_NCM,
  CEST.CODIGO AS PERSONAL6,
  PRODUTO.PERCLUCRO AS MARGEM_LUCRO
 FROM PRODUTO
 LEFT JOIN FABRICANTE ON FABRICANTE.ID = PRODUTO.FABRICANTE_ID
 LEFT JOIN CEST ON CEST.ID = PRODUTO.CEST_ID
 LEFT JOIN NCM ON NCM.ID = PRODUTO.NCM_ID
 LEFT JOIN GRUPOPRODUTO ON GRUPOPRODUTO.ID = PRODUTO.GRUPOPRODUTO_ID
