SELECT PRODUTO.CODIGO
      ,PRODUTO.DESCRICAO
      ,PRODUTO.CODIGOBARRA AS BARRAS
      ,PRODUTO.VALOR_COMPRA AS PRECO_CUSTO
      ,PRODUTO.VALOR_VENDA AS PRECO_VENDA
      ,PRODUTO.ESTOQUE AS QTD
      ,FORNECEDOR.NOME AS FORNECEDOR
      ,CATEGORIA.DESCRICAO AS GRUPO
      ,PRODUTO.VALOR_VENDA_ATACADO AS PRECO_ATACADO
      ,PRODUTO.NCMSH AS COD_NCM
      ,PRODUTO.CST AS ST
      ,PRODUTO.CEST AS PERSONAL6
  FROM SYSMARKET.dbo.PRODUTO
LEFT JOIN SYSMARKET.dbo.CATEGORIA ON PRODUTO.CATEGORIA = CATEGORIA.CODIGO
LEFT JOIN SYSMARKET.dbo.FORNECEDOR ON PRODUTO.FORNECEDOR = FORNECEDOR.CODIGO
