SELECT
  FORNEDECOR.ID AS CODIGO,
  FORNEDECOR.FANTASIA AS FANTASIA,
  FORNEDECOR.RAZAO AS NOME,
  FORNEDECOR.CNPJ AS CNPJ_CNPF,
  FORNEDECOR.IE AS IE_RG,
  case when FORNEDECOR.REPRESENTANTE = '' or FORNEDECOR.REPRESENTANTE is null then FORNEDECOR.CONTATO else FORNEDECOR.REPRESENTANTE END as CONTATO,
  FORNEDECOR.ENDERECO AS ENDERECO,
  FORNEDECOR.BAIRRO AS BAIRRO,
  FORNEDECOR.CIDADE AS CIDADE,
  FORNEDECOR.UF AS UF,
  FORNEDECOR.CEP AS CEP,
  FORNEDECOR.TELEFONE AS TELEFONE,
  FORNEDECOR.FAX AS FAX,
  FORNEDECOR.EMAIL AS EMAIL,
  FORNEDECOR.OBS AS OBSERVACOES
FROM FORNEDECOR
