SELECT
  PRODUTO.CODIGO AS CODIGO,
  PRODUTO.CODBARRA AS BARRAS,
  PRODUTO.CODFABRICA AS COD_FABRICANTE,
  PRODUTO.DESCRICAO AS DESCRICAO,
  FORNEDECOR.RAZAO AS FORNECEDOR,
  GRUPO.GRUPO AS GRUPO,
  SUBGRUPO.SUBGRUPO AS FAMILIA,
  PRODUTO.UNIDADEVENDA AS UND,
  PRODUTO.TRIBUTACAO AS ST,
  PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
  PRODUTO.MARGEM AS MARGEM_LUCRO,
  PRODUTO.PRECOVENDA AS PRECO_VENDA,
  PRODUTO.ESTOQUEMINIMO AS QTD_IDEAL,
  CAST (PRODUTO.ULTIMACOMPRA AS DATE) AS ULTIMA_COMPRA,
  CAST (PRODUTO.ULTIMAVENDA AS DATE) AS ULTIMA_VENDA,
  CAST (PRODUTO.ULTALTERA AS DATE) AS ALTERACAO_PRECO,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.ESTDISPONIVEL AS QTD
FROM PRODUTO
LEFT JOIN FORNEDECOR ON FORNEDECOR.ID = PRODUTO.FORNECEDOR
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTO.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.ID = PRODUTO.SUBGRUPO
WHERE PRODUTO.DESCRICAO <> '' AND PRODUTO.DESCRICAO IS NOT NULL
