SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    FANTA AS FANTASIA,
    CONTATO AS CONTATO,
    CGC AS CNPJ_CNPF,
    INSEST AS IE_RG,
    replace (replace(DDD ||''|| FONES,'-',''),'/','') AS TELEFONE,
    replace (replace(DDD_FONE_CEL ||''|| FONE_CEL,'-',''),'/','') AS CELULAR,
    ENDERE AS ENDERECO,
    COMPLEMENTO AS COMPLEMENTO,
    NUMEND AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    E_MAIL AS EMAIL,
    OBS AS OBSERVACOES
FROM ADPES
WHERE EHFOR = 'T' --- FORNECEDORES
