SELECT  
  P.ID_PRODUTOS AS CODIGO
, P.CODIGOPRODUTO AS COD_FABRICANTE 
, P.NOMEPRODUTO AS DESCRICAO
, P.UNIDADE AS UND
--, P.CODIGOBARRAPRODUTO
, P.ORIGEMPRODUTO AS OST
, P.MARGEMLUCRO AS MARGEM_LUCRO
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.QTDETOTAL AS QTD
, CAST (COALESCE(P.DATACADASTRO, GETDATE()) AS DATE) AS DATA_CADASTRO
, CASE P.ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.QTDEENTRADA AS FAT_CONV
, P.CODIGOANP AS COD_ANP
, P.NCM AS COD_NCM
--, P.TIPOTRIBUTACAO AS ST
, P.CSOSN AS ST
, P.ALIQUOTAIPI AS ALIQ_IPI
--, P.PIS_COFINS AS PIS_CODIGO
--, P.PIS_COFINS AS COFINS_CODIGO
, P.PERCSTPISCOFINS AS PIS_ALIQ_NOR
, P.PERCSTPISCOFINS AS COFINS_ALIQ_NOR
, P.NATREC AS PERSONAL2
--, P.CST_PIS_ENT AS PISE_CODIGO
--, P.CST_COFINS_ENT AS COFINSE_CODIGO
, P.ALIQPIS AS PISE_ALIQ_NOR
, P.ALIQCOFINS AS COFINSE_ALIQ_NOR
, P.CEST AS PERSONAL6
, G.NOMEGRUPOPRODUTOS AS GRUPO
, M.NOMEMARCA AS FAMILIA
, E.NOMEENTIDADE AS FORNECEDOR
, L.NOMELOCALVENDAS AS PERSONAL1
, S.QTDETOTAL AS PERSONAL4
, S.VLRUNITARIO AS PRECO_VENDA
, REPLACE (C.CFOP,'.','') AS CF
, LEFT (REPLACE (C.CFOP,'.',''),3) AS ELO
, max (PB.CODIGOBARRAPRODUTO) AS BARRAS
FROM PRODUTOS P
LEFT JOIN GRUPOPRODUTOS G ON G.ID_GRUPOPRODUTOS = P.ID_GRUPOPRODUTOS
LEFT JOIN MARCAS M ON M.ID_MARCAS = P.ID_MARCAS
LEFT JOIN ENTIDADES E ON E.ID_ENTIDADE = P.ID_ENTIDADE
LEFT JOIN LOCALVENDAS L ON L.ID_LOCALVENDAS = P.ID_LOCALVENDAS
LEFT JOIN SALDOSPRODUTOS S ON S.ID_PRODUTOS = P.ID_PRODUTOS 
LEFT JOIN PRODUTOSCODBAR PB ON PB.ID_PRODUTOS = P.ID_PRODUTOS
LEFT JOIN CFOP C ON C.ID_CFOP = P.ID_CFOPSAIDA
GROUP BY 
  P.ID_PRODUTOS,
  P.CODIGOPRODUTO,
  P.NOMEPRODUTO,
  P.UNIDADE,
  P.ORIGEMPRODUTO,
  P.MARGEMLUCRO,
  P.CUSTOMEDIO,
  P.QTDETOTAL,
  CAST(COALESCE(P.DATACADASTRO, GETDATE()) AS DATE),
  CASE P.ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END,
  P.QTDEENTRADA,
  P.CODIGOANP,
  P.NCM,
  P.CSOSN,
  P.ALIQUOTAIPI,
  --P.PIS_COFINS,
  --P.PIS_COFINS,
  P.PERCSTPISCOFINS,
  P.PERCSTPISCOFINS,
  P.NATREC,
  --P.CST_PIS_ENT,
  --P.CST_COFINS_ENT,
  P.ALIQPIS,
  P.ALIQCOFINS,
  P.CEST,
  G.NOMEGRUPOPRODUTOS,
  M.NOMEMARCA,
  E.NOMEENTIDADE,
  L.NOMELOCALVENDAS,
  S.QTDETOTAL,
  S.VLRUNITARIO,
  REPLACE(C.CFOP,'.',''),
  lEFT (REPLACE (C.CFOP,'.',''),3)