SELECT
       substring (CADPARCEIRO.CODIGOPARCEIRO, 2 ,6) AS CODIGO
      ,CADPARCEIRO.DESCRICAO AS NOME
      ,CADPARCEIRO.NOMEFANTASIA AS FANTASIA
      ,CADPARCEIRO.CONTATO AS CONTATO
      ,CADPARCEIRO.CPFCGC AS CNPJ_CNPF
      ,case when CADPARCEIRO.RG = '' or CADPARCEIRO.RG is null then CADPARCEIRO.INSCRICAOESTADUAL else CADPARCEIRO.RG END AS IE_RG
      ,CADPARCEIRO.INSCRICAOMUNICIPAL AS IM
      ,CADPARCEIRO.ENDERECO AS ENDERECO
      ,CADPARCEIRO.BAIRRO AS BAIRRO
      ,CADPARCEIRO.NUMEROLOGRADOURO AS NUMERO
      ,CADPARCEIRO.COMPLEMENTOLOGRADOURO AS COMPLEMENTO
      ,CADPARCEIRO.CIDADE AS CIDADE
      ,CADPARCEIRO.ESTADO AS UF
      ,CADPARCEIRO.CEP AS CEP
      ,CADPARCEIRO.EMAIL AS EMAIL
      ,CADPARCEIRO.FONE1 AS TELEFONE
      ,CADPARCEIRO.FONE2 AS CELULAR
      ,CADPARCEIRO.FAX AS FAX
      ,CADPARCEIRO.OBSERVACAO AS OBSERVACOES
  FROM SantoAngelus.dbo.CADPARCEIRO
  where CADPARCEIRO.DESCRICAO <> 'CLIENTES' AND CADPARCEIRO.CODIGOPARCEIRO like 'C%'