SELECT
    CADASTRODESCRICAO.CODIGO AS CODIGO,
    CADASTRODESCRICAO.DESCRICAO AS DESCRICAO,
    CADASTRODESCRICAO.CODIGOBARRAS AS BARRAS,
    CADASTRODESCRICAO.UN AS UND,
    CADASTRODESCRICAO.PESELIQUIDO AS PESO,
    CADASTRODESCRICAO.ESTOQUEMINIMO AS QTD_IDEAL,  
    CADASTRODESCRICAO.ESTOQUE AS QTD,
    CADASTRODESCRICAO.MARGEMLUCRO AS MARGEM_LUCRO,
    CADASTRODESCRICAO.PRECOCOMPRA AS PRECO_CUSTO,
    CADASTRODESCRICAO.PRECO AS PRECO_VENDA,
    CADASTRODESCRICAO.PRECOATACADO AS PRECO_ATACADO,
    CADASTRODESCRICAO.REFERENCIA AS COD_FABRICANTE,
    CADASTRODESCRICAO.DATA AS DATA_CADASTRO
FROM CADASTRODESCRICAO
