SELECT
    SUBSTRING (CAD_ENTIDADES_BASICO.ID_ENTIDADE FROM 5 FOR 10) AS CODIGO,
    CAD_ENTIDADES_BASICO.NOME AS NOME,
    CAD_ENTIDADES_BASICO.FANTASIA AS FANTASIA,
    CAD_ENTIDADES_BASICO.CONTATO AS CONTATO,
    CAD_ENTIDADES_BASICO.CNPJ_CNPF AS CNPJ_CNPJ,
    case when CAD_ENTIDADES_BASICO.IDENTIDADE = '' or CAD_ENTIDADES_BASICO.IDENTIDADE is null then CAD_ENTIDADES_BASICO.INSC_EST else CAD_ENTIDADES_BASICO.IDENTIDADE END AS IE_RG,
    CAD_ENTIDADES_BASICO.INSC_MUN AS IM,
    CAD_ENTIDADES_BASICO.ENDERECO AS ENDERECO,
    CAD_ENTIDADES_BASICO.NRO_ENDERECO AS NUMERO,  
    CAD_ENTIDADES_BASICO.COMPLEMENTO AS COMPLEMENTO,
    CAD_ENTIDADES_BASICO.BAIRRO AS BAIRRO,
    CAD_ENTIDADES_BASICO.MUNICIPIO AS CIDADE,
    CAD_ENTIDADES_BASICO.UF AS UF,
    CAD_ENTIDADES_BASICO.CEP AS CEP,
    CAD_ENTIDADES_BASICO.TELEFONE AS TELEFONE,
    CAD_ENTIDADES_BASICO.CELULAR AS CELULAR,
    CAD_ENTIDADES_BASICO.FAX AS FAX,
    CAD_ENTIDADES_BASICO.E_MAIL AS EMAIL
FROM CAD_ENTIDADES_BASICO
WHERE CAD_ENTIDADES_BASICO.FORNECEDOR = 'S'
