SELECT
    CAD_ITENS.ID_ITEM AS COD_FABRICANTE,
    CAD_GRUPOS_ITENS.DESCRICAO AS GRUPO,
    CAD_SUBGRUPOS_ITENS.DESCRICAO AS FAMILIA,
    CAD_ITENS.ID_UNID_MED AS UND,
    CAD_ITENS.DESCRICAO AS DESCRICAO,
    REL_LOCAL_ARMAZ_ITENS.ESTOQ_DISPON AS QTD,
    CAD_ESTOQUE_ITEM.PRECO_COMPRA AS PRECO_CUSTO, 
    CAD_ESTOQUE_ITEM.CUSTO_MED_ITEM AS CUSTO_MEDIO, 
    CAD_ESTOQUE_ITEM.PERC_LUCRO AS MARGEM_LUCRO, 
    CAD_ESTOQUE_ITEM.PRECO_VENDA_A AS PRECO_VENDA,
    REL_ALIQ_ICMS_UF_ITEM.SIT_TRIB_ICMS AS ST,
    CAD_ESTOQUE_ITEM.DT_ULT_COMPRA AS ULTIMA_COMPRA,
    CAD_ITENS.DT_IMPLANT AS DATA_CADASTRO,
    CAD_ITENS.PESO_LIQ AS PESO,
    CAD_ITENS.COD_NCM AS COD_NCM,
    CAD_ITENS.COD_CEST AS PERSONAL6,
    CAD_ITENS.COD_BARRAS AS BARRAS
FROM CAD_ITENS
LEFT JOIN CAD_GRUPOS_ITENS ON CAD_GRUPOS_ITENS.ID_GRUPO_ITEM = CAD_ITENS.ID_GRUPO_ITEM
LEFT JOIN CAD_SUBGRUPOS_ITENS ON CAD_SUBGRUPOS_ITENS.ID_SUBGRUPO_ITEM = CAD_ITENS.ID_SUBGRUPO_ITEM
LEFT JOIN CAD_ESTOQUE_ITEM ON CAD_ESTOQUE_ITEM.ID_ITEM = CAD_ITENS.ID_ITEM
LEFT JOIN REL_ALIQ_ICMS_UF_ITEM ON REL_ALIQ_ICMS_UF_ITEM.ID_ITEM = CAD_ITENS.ID_ITEM
LEFT JOIN REL_LOCAL_ARMAZ_ITENS ON REL_LOCAL_ARMAZ_ITENS.ID_ITEM = CAD_ITENS.ID_ITEM
