SELECT
       PRODUTO.PRD_Id AS CODIGO,
       PRODUTO.PRD_Codigo AS COD_FABRICANTE,
       GRUPO_PRODUTO.GRP_DESCRICAO AS GRUPO,
       SUBGRUPO_PRODUTO.SGP_Descricao AS FAMILIA,
       PRODUTO_CODIGOBARRA.PRC_CodigoBarra AS BARRAS,
       PRODUTO_UNIDADE.PRU_Preco AS PRECO_VENDA,
       PRODUTO_UNIDADE.PRU_EstoqueAtual AS QTD,
       PRODUTO_UNIDADE.PRU_PrecoCusto AS PRECO_CUSTO,
       PRODUTO_UNIDADE.PRU_PrecoAtacado AS PRECO_ATACADO,
       PRODUTO_UNIDADE.PRU_MargemLucro AS MARGEM_LUCRO,
       EMPRESA.EMP_RazaoSocial AS FORNECEDOR,
       SUBSTRING(PRODUTO_UNIDADE.PRU_CSOSN, 2, 4) AS ST,
       PRODUTO.PRD_Descricao AS DESCRICAO,
       CAST(PRODUTO.PRD_DataCadastro AS DATE) AS DATA_CADASTRO,
       PRODUTO.PRD_NCM AS COD_NCM,
       PRODUTO.PRD_Peso AS PESO,
       NCM_CEST.NCE_CES_CodigoCEST AS PERSONAL6,
       UNIDADE_PRODUTO.UNP_Sigla AS UND
FROM APPTA.dbo.PRODUTO
LEFT JOIN APPTA.dbo.GRUPO_PRODUTO ON GRUPO_PRODUTO.GRP_CODIGO = PRODUTO.PRD_GPR_IdGrupoProduto
LEFT JOIN APPTA.dbo.SUBGRUPO_PRODUTO ON SUBGRUPO_PRODUTO.SGP_Codigo = PRODUTO.PRD_SGP_IdSubGrupoProduto
LEFT JOIN APPTA.dbo.PRODUTO_CODIGOBARRA ON PRODUTO_CODIGOBARRA.PRC_PRD_IdProduto = PRODUTO.PRD_Id
LEFT JOIN APPTA.dbo.PRODUTO_UNIDADE ON PRODUTO_UNIDADE.PRU_PRD_IdProduto = PRODUTO.PRD_Id
LEFT JOIN APPTA.dbo.PRODUTO_FORNECEDOR ON PRODUTO_FORNECEDOR.PRF_PRD_IdProduto = PRODUTO.PRD_Id
LEFT JOIN APPTA.dbo.EMPRESA ON EMPRESA.EMP_Id = PRODUTO_FORNECEDOR.PRF_FOR_IdFornecedor
LEFT JOIN APPTA.dbo.NCM_CEST ON NCM_CEST.NCE_NCM_CodigoNCM = PRODUTO.PRD_NCM
LEFT JOIN APPTA.dbo.UNIDADE_PRODUTO ON UNIDADE_PRODUTO.UNP_Codigo = PRODUTO.PRD_UNP_IdUnidadeProduto
GROUP BY 
       PRODUTO.PRD_Id,
       PRODUTO.PRD_Codigo,
       GRUPO_PRODUTO.GRP_DESCRICAO,
       PRODUTO_CODIGOBARRA.PRC_CodigoBarra,
       PRODUTO_UNIDADE.PRU_Preco,
       PRODUTO_UNIDADE.PRU_EstoqueAtual,
       PRODUTO_UNIDADE.PRU_PrecoCusto,
       PRODUTO_UNIDADE.PRU_PrecoAtacado,
       PRODUTO_UNIDADE.PRU_MargemLucro,
       EMPRESA.EMP_RazaoSocial,
       SUBSTRING(PRODUTO_UNIDADE.PRU_CSOSN, 2, 4),
       PRODUTO.PRD_Descricao,
       CAST(PRODUTO.PRD_DataCadastro AS DATE),
       PRODUTO.PRD_NCM,
       PRODUTO.PRD_Peso,
       SUBGRUPO_PRODUTO.SGP_Descricao,
       NCM_CEST.NCE_CES_CodigoCEST,
       UNIDADE_PRODUTO.UNP_Sigla;