SELECT
  PRODUTOS.PRODCODIGO AS CODIGO,
  PRODUTOS.PRODNOME AS DESCRICAO,
  PRODUTOS.PRODUNIDADE AS UND,
  PRODUTOS.PRODPRECOVENDA AS PRECO_VENDA,
  GRUPO.GRUPNOME AS GRUPO,
  PRODUTOS.PRODPRECOCUSTO AS PRECO_CUSTO,
  PRODUTOS.PRODCOMISSAO AS COMISSAO,
  PRODUTOS.PRODMARGEM AS MARGEM_LUCRO,
  SUBSTRING(PRODUTOS.PRODST FROM 2 FOR 3) AS ST,
  PRODUTOS.PRODCODIGOBARRA AS BARRAS,
  PRODUTOS.PRODCUSTOMEDIO AS CUSTO_MEDIO,
  PRODUTOS.PRODESTQMINIMO AS QTD_IDEAL,
  PRODUTOS.PRODFABRICANTE AS COD_FABRICANTE,
  PRODUTOS.DTALTERACAO AS ALTERACAO_PRECO,
  PRODUTOS.DTULTIMAVENDA AS ULTIMA_VENDA,
  PRODUTOS.DTULTIMACOMPRA AS ULTIMA_COMPRA,
  PRODUTOS.DTCADASTRO AS DATA_CADASTRO,
  PRODUTOS.PESOLIQUIDO AS PESO,
  PRODUTOS.NOMEREDUZIDO AS CARACTERISTICAS,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.OBS AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPO ON GRUPO.GRUPCODIGO = PRODUTOS.PRODGRUPO
