SELECT 
    PRODUTOS.ID AS CODIGO,
    FORNECEDORES.razao_social AS FORNECEDOR,
    GRUPOS.descricao AS GRUPO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.DESCRICAO_REDUZIDA AS CARACTERISTICAS,
    REPLACE (PRODUTOS_CODIGOSBARRAS.CODIGO_BARRA, '.' , '') AS BARRAS,
    PRODUTOS_ESTOQUE_NORMAL.estoque_atual AS QTD,
    PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    PRODUTOS.preco_varejo AS PRECO_VENDA,
    PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARGEM_APLIC_VAREJO AS MARGEM_LUCRO,
    PRODUTOS.ORIGEM AS OST,
    PRODUTOS.CST AS ST,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    PRODUTOS.DATA_ALTERACAO AS ALTERACAO_PRECO,
    PRODUTOS.ULTIMA_COMPRA AS ULTIMA_COMPRA,
    PRODUTOS.ULTIMA_VENDA AS ULTIMA_VENDA,
    PRODUTOS.CODIGO_INTERNO AS PERSONAL2,
    PRODUTOS.CODIGO_FABRICA AS COD_FABRICANTE,
    PRODUTOS.APLICACAO AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN PRODUTOS_CODIGOSBARRAS ON PRODUTOS_CODIGOSBARRAS.ID_PRODUTO = PRODUTOS.ID
LEFT JOIN PRODUTOS_ESTOQUE_NORMAL ON PRODUTOS_ESTOQUE_NORMAL.id_produto = PRODUTOS.id
LEFT JOIN FORNECEDORES ON FORNECEDORES.id = PRODUTOS.id_fornecedor
LEFT JOIN GRUPOS ON GRUPOS.id = PRODUTOS.id_grupo
