SELECT
    CLIENTES.CODCLIENTE AS CODIGO,
    CLIENTES.NOME AS NOME,                      
    CLIENTES.NOMEFANTASIA AS FANTASIA,               
    --CLIENTES.DATACADASTRO AS CADASTRO,                                     
    CLIENTES.DATANASC AS NASCIMENTO,                  
    CLIENTES.CPFCNPJ AS CNPJ_CNPF,                   
    CLIENTES.IE AS IE_RG,                       
    CLIENTES.EMAIL AS EMAIL,                      
    CLIENTES.NOMEPAI AS PAI,                    
    CLIENTES.NOMEMAE AS MAE,                  
    CLIENTES.FONERESID AS TELEFONE,                 
    CLIENTES.CELULAR AS CELULAR,                   
    CLIENTES.FAX AS FAX,                        
    CLIENTES.PROFISSAO AS PROFISSAO,
    CLIENTES.LIMITE AS LIMITE_CREDITO,
    CLIENTES_ENDERECOS.ENDERECO AS ENDERECO,
    CLIENTES_ENDERECOS.NUMERO AS NUMERO,
    CLIENTES_ENDERECOS.BAIRRO AS BAIRRO,
    CLIENTES_ENDERECOS.CEP AS CEP,
    CLIENTES_ENDERECOS.COMPLEMENTO,
    CIDADES.CIDADE AS CIDADE,
    CIDADES.UF AS UF,
    CLIENTES.ativo, 
    case when ATIVO = 'N' then 'Inativo' else 'Ativo' end as SITUACAO
FROM CLIENTES
LEFT JOIN CLIENTES_ENDERECOS ON CLIENTES.CODCLIENTE = CLIENTES_ENDERECOS.CODCLIENTE
LEFT JOIN CIDADES ON CLIENTES_ENDERECOS.CODCIDADE = CIDADES.CODCIDADE
WHERE CLIENTES_ENDERECOS.PRINCIPAL = 'S' AND CLIENTES.NOME <> '' AND CLIENTES.CODCLIENTE <> '0'
