SELECT
    FORNECEDORES.CODIGO AS CODIGO,
    FORNECEDORES.NOME AS NOME,
    FORNECEDORES.RAZAOSOCIAL AS FANTASIA,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.CNPJ AS CNPJ_CNPF,
    FORNECEDORES.IE AS IE_RG,
    FORNECEDORES.IM AS IM,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    CIDADES.CIDADE AS CIDADE,
    CIDADES.UF AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.OBSERVACAO AS OBSERVACOES 
FROM FORNECEDORES
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = FORNECEDORES.CODCIDADE
