SELECT
    PRODUTOS.CODIGO AS CODIGO,             
    PRODUTOS.GTIN AS BARRAS,
    PRODUTOS.IDBARRA AS COD_FABRICANTE,
    PRODUTOS.PRODUTO AS DESCRICAO,   
    PRODUTOS.CUSTO AS PRECO_CUSTO,                
    PRODUTOS.VALOR1 AS PRECO_VENDA,             
    GRUPOS.DESCRICAO AS GRUPO,
    PRODUTOS.CODSITUACAOTRIBUTARIA AS ST,  
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS_CEST.CEST AS PERSONAL6,                           
    PRODUTOS.CUSTOMEDIO AS CUSTO_MEDIO,                
    UNIDADES.UNIDADE AS UND,             
    PRODUTOS.PIS_CST AS PIS_CODIGO,                          
    PRODUTOS.COFINS_CST AS COFINS_CODIGO,
    PRODUTOS_ESTOQUE.DISPONIVEL AS QTD,
    PRODUTOS.INATIVO,
    case when INATIVO = 'S' then 'Inativo' else 'Ativo' end as SITUACAO
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.CODGRUPO = GRUPOS.CODGRUPO
LEFT JOIN UNIDADES ON PRODUTOS.CODUNIDADE = UNIDADES.CODUNIDADE
LEFT JOIN PRODUTOS_CEST ON PRODUTOS.CODCEST = PRODUTOS_CEST.CODCEST
LEFT JOIN PRODUTOS_ESTOQUE ON PRODUTOS.CODIGO = PRODUTOS_ESTOQUE.CODPRODUTO
