SELECT
  CAD_PRODUTOS.COD AS CODIGO,
  CAD_PRODUTOS.COD_PRO AS BARRAS,
  CAD_PRODUTOS.DESCRICAO_PDV AS CARACTERISTICAS,
  CAD_PRODUTOS.DESCRICAO_COMPLE AS DESCRICAO,
  CAD_PRODUTOS.UNIDADE_ITEN AS UND,
  CAD_PRODUTOS.ESTOQUE_ATUAL AS QTD,
  CAD_PRODUTOS.ESTOQUE_ALERTA AS QTD_IDEAL,
  CAD_PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
  CAD_PRODUTOS.PRECO_COMPRA AS CUSTO_COMPRA,
  DEPART.DERPARTAMENTO AS GRUPO,
  CAD_PRODUTOS.DATA_ENTRADA AS ULTIMA_COMPRA,
  CAD_PRODUTOS.DATA_SAIDA AS ULTIMA_VENDA,
  CAD_PRODUTOS.PESO AS PESO,
  CAD_PRODUTOS.CUSTOMEDIO AS CUSTO_MEDIO,
  CAD_PRODUTOS.FORNECEDOR AS FORNECEDOR,
  CAD_PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
  CAD_PRODUTOS.ST AS ST
FROM CAD_PRODUTOS
LEFT JOIN DEPART ON DEPART.DERPARTAMENTO = CAD_PRODUTOS.DEPARTAMENTO
WHERE CAD_PRODUTOS.DESCRICAO_COMPLE IS NOT NULL
