SELECT
  PRODUTO.IDPRODUTO AS CODIGO,
  PRODUTO.NOME AS DESCRICAO,
  PRODUTO.DATAESTOQUE AS DATA_CADASTRO,
  PRODUTO.SALDOATUAL AS QTD,
  PRODUTO.OBS AS OBSERVACOES,
  GRUPO.NOME AS GRUPO,
  PRODUTO.ESTOQUEMIN AS QTD_IDEAL,
  PRODUTO.VLRVENDA AS PRECO_VENDA,
  PRODUTO.VLRCUSTO AS PRECO_CUSTO,
  PRODUTO.NUMCODBARRAS AS BARRAS,
  PRODUTO.REFERENCIA AS COD_FABRICANTE,
  FORNECEDOR.NOME AS FORNECEDOR,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.CODNCM AS COD_NCM,
  CSOSN.CODIGO AS ST
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.IDGRUPO = PRODUTO.IDGRUPO
LEFT JOIN FORNECEDOR ON FORNECEDOR.IDFORNECEDOR = PRODUTO.IDFORNECEDOR
LEFT JOIN CSOSN ON CSOSN.IDCSOSN = PRODUTO.IDCSOSN
