SELECT
    CODIGO,
    FANTASIA,
    CGC AS CNPJ_CNPF,
    FORNECEDOR AS NOME,
    INSCRICAO AS IE_RG,
    ENDERECO,
    BAIRRO,
    CIDADE,
    CEP,
    UF,
    FONE AS TELEFONE,
    FONE1 AS CELULAR,
    FONE_FAX AS FAX,
    EMAIL
FROM TBFORNECEDOR
