SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    MIN (PRODUTO_CODIGO_BARRA.CODIGO_BARRA) AS BARRAS,
    PRODUTO_UNIDADE.SIGLA AS UND,
    PRODUTO.PESO_LIQUIDO AS PESO,
    PRODUTO.QUANTIDADE AS QTD,
    PRODUTO_GRUPO.DESCRICAO AS GRUPO,
    PRODUTO_SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTO_PRECO.LUCRO AS MARGEM_LUCRO,
    PRODUTO_PRECO.VALOR AS PRECO_VENDA,
    PRODUTO_FISCAL.ICMS_CST_INTERNO AS ST,
    PRODUTO.OBSERVACAO AS OBSERVACOES,
    PRODUTO.DATA_CADASTRO AS DATA_CADASTRO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    CLASSIFICACAO_FISCAL.CLASSIFICACAO AS COD_NCM,
    replace(CEST.CODIGO,'.','') AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_FISCAL ON PRODUTO_FISCAL.FK_PRODUTO = PRODUTO.ID
LEFT JOIN PRODUTO_CODIGO_BARRA ON (PRODUTO_CODIGO_BARRA.FK_PRODUTO = PRODUTO.ID) AND (PRODUTO_CODIGO_BARRA.CODIGO_BARRA like '789%')
LEFT JOIN PRODUTO_UNIDADE ON PRODUTO_UNIDADE.ID = PRODUTO.FK_PRODUTO_UNIDADE
LEFT JOIN CEST ON CEST.ID = PRODUTO.FK_CEST
LEFT JOIN CLASSIFICACAO_FISCAL ON CLASSIFICACAO_FISCAL.ID = PRODUTO.FK_CLASSIFICACAO_FISCAL
LEFT JOIN PRODUTO_SUBGRUPO ON PRODUTO_SUBGRUPO.ID = PRODUTO.FK_PRODUTO_SUBGRUPO
LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.ID = PRODUTO_SUBGRUPO.FK_PRODUTO_GRUPO
LEFT JOIN PRODUTO_PRECO ON PRODUTO_PRECO.FK_PRODUTO = PRODUTO.ID
WHERE PRODUTO_PRECO.FK_TABELA_PRECO = '1'
GROUP BY 1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18