select 
estoque.[Código Produto] as cod_fabricante,
estoque.[Nome Produto] as descricao,
estoque.[Código Produto] as barras,
estoque.[Quantidade Estoque] as qtd,
estoque.[Quantidade Mínima] as QTD_IDEAL,
estoque.Unidade as und,
estoque.Grupo,
estoque.SubGrupo as familia,
estoque.[Preço Venda] as preco_venda,
estoque.[Preço Compra] as preco_custo,
estoque.Fornecedor,
estoque.[Unidade Compra] as und_compra,
estoque.[Peso Líquido] as peso,
left (estoque.CFOP_Venda,3) as elo,
estoque.IPPT,
estoque.TIPO_ITEM,
estoque.COD_NCM,
estoque.CST_PIS as PIS_CODIGO,
estoque.PIS as PIS_ALIQ_NOR,
estoque.CST_COFINS as COFINS_CODIGO,
estoque.COFINS as COFINS_ALIQ_NOR,
estoque.CSTIPI as IPI_CODIGO_VENDA,
estoque.IPI as ALIQ_IPI_VENDA,
estoque.CST_PIS_Entrada as PISE_CODIGO,
estoque.PIS_Per_Entrada as PISE_ALIQ_NOR,
estoque.CST_COFINS_Entrada as COFINSE_CODIGO,
estoque.COFINS_Per_Entrada as COFINSE_ALIQ_NOR,
estoque.CodigoBeneficioFiscal as CBENEF,
estoque.CST_CSOSN_Venda as st,
estoque.Cod_CEST as personal6
from estoque
