SELECT
	CÓDIGODOFORNECEDOR AS CODIGO,
	CGCCPF AS CNPJ_CNPF,
	INSCRG AS IE_RG,	
	DS_RAZAO_SOCIAL AS NOME,
	NOMEDOFORNECEDOR AS FANTASIA,
	NOMEDOCONTATO AS CONTATO,
	ENDEREÇO AS ENDERECO,
	NO_ENDERECO AS NUMERO,	
	NM_BAIRRO AS BAIRRO,	
	CIDADE,
	UF,
	CEP,
	TELEFONE,
	FAX,
	NO_CELULAR AS CELULAR,	
	OBS AS OBSERVACOES,
	EMAILDOFORNECEDOR AS EMAIL
FROM
	CES_ADM.DBO.FORNECEDORES
WHERE CÓDIGODOFORNECEDOR > '0'
