SELECT
	P.CÓDIGODEBARRA AS PERSONAL1,
	P.CÓDIGODAFÁBRICA AS COD_FABRICANTE,
	P.CEAN AS BARRAS,	
	P.NOMEDOPRODUTO AS DESCRICAO,
	P.DESCRIÇÃOCOMPLEMENTO AS OBSERVACOES,
	P.CUSTODOPRODUTO AS PRECO_CUSTO,
	P.CUSTOMÉDIODOPRODUTO AS CUSTO_MEDIO,
	P.MARGEMDOPRODUTO AS MARGEM_LUCRO,
	P.PREÇOUNITÁRIO AS PRECO_VENDA,
	P.ESTOQUE AS QTD,
	CAST(P.DATAULTIMACOMPRA AS DATE) AS ULTIMA_COMPRA,
	CAST(COALESCE(P.DT_CADASTRO, GETDATE()) AS DATE) AS DATA_CADASTRO,
	P.LOCALIZAÇÃO AS PERSONAL2,
	P.DIVISOR AS FAT_CONV,
	P.UNIDADE AS UND,
	P.EMBALAGEM AS UND_COMPRA,
	P.ORIGEMDOPRODUTO AS OST,
	P.CD_ANP AS COD_ANP,
	P.VALIDADE AS VALIDADE_DIAS,
	P.TAMANHO,
	P.NO_CODIGO_NCM AS COD_NCM,
	P.VL_PESO AS PESO,	
	P.NO_CEST AS PERSONAL6,	
	P.TRIBUTAÇÃOICMS AS ST,
--	P.TP_CSOSN AS ST,	
	P.VL_ALIQ_COFINS AS COFINS_ALIQ_NOR,
	P.VL_ALIQ_PIS AS PIS_ALIQ_NOR,
	P.TP_COFINS AS COFINS_CODIGO,
	P.CT_IPI_ENTRADA AS IPI_CODIGO,
	P.CT_IPI_SAIDA AS IPI_CODIGO_VENDA,
	F.NOMEDOFORNECEDOR AS FORNECEDOR,
	C.NOMEDACATEGORIA AS GRUPO,
	CS.NOMEDACATEGORIA_SUB AS FAMILIA,
	FA.NOMEDOFABRICANTE AS CARACTERISTICAS
FROM
	CES_ADM.DBO.PRODUTOS P
LEFT JOIN FORNECEDORES F ON F.CÓDIGODOFORNECEDOR = P.CÓDIGODOFORNECEDOR
LEFT JOIN CATEGORIAS C ON C.CÓDIGODACATEGORIA = P.CÓDIGODACATEGORIA 
LEFT JOIN CATEGORIAS_SUB CS ON CS.CÓDIGODACATEGORIA_SUB = P.CÓDIGODACATEGORIA_SUB AND CS.CD_CATEGORIA = C.CÓDIGODACATEGORIA 
LEFT JOIN FABRICANTES FA ON FA.CÓDIGODOFABRICANTE = P.CÓDIGODOFABRICANTE 