SELECT
    FORNECEDORES.CODIGO AS CODIGO,
    FORNECEDORES.NOME AS NOME,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.RG AS IE_RG,
    FORNECEDORES.CPF AS CNPJ_CNPF,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.UF AS UF,
    FORNECEDORES.TEL1 AS TELEFONE,
    FORNECEDORES.TEL2 AS CELULAR,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.OBS AS OBSERVACOES
FROM FORNECEDORES