SELECT 
  C.CODIGO
, C.CLIENTE AS NOME
--, C.NOME
, C.FANTASIA
, C.ENDERECO
, C.NUMERO
, C.COMPLEMENTO
, C.BAIRRO
, C.CEP
, C.FONE AS TELEFONE
, C.CELULAR
, C.FAX
, C.CPFCNPJ AS CNPJ_CNPF
, CASE WHEN C.RG = '' OR C.RG IS NULL THEN C.IE ELSE C.RG END AS IE_RG
, C.IM
, C.EMAIL
, C.CONTATO
, C.NASCIMENTO
, CAST (C.DTCAD AS DATE) AS CADASTRO
, C.OBS AS OBSERVACOES
, C.PROFISSAO
, C.LTRAB AS LOCTRA
, C.PAI
, C.MAE
, C.CONJUGE
, CI.CIDADE 
, ES.UF 
FROM CLIENTES C
LEFT JOIN CIDADES CI ON CI.CODIGO = C.CIDADE 
LEFT JOIN ESTADOS ES ON ES.CODIGO = CI.ESTADO 
