SELECT 
  P.CODIGO
, P.CODFAB AS COD_FABRICANTE
, P.CODREF AS PERSONAL2
, P.CODBAR AS BARRAS
, P.CLASSIFICACAO_FISCAL AS COD_NCM
, P.PRODUTO AS DESCRICAO
, CASE P.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUCAO
, P.DATACAD AS DATA_CADASTRO
, P.CUSTO AS PRECO_CUSTO
--, P.VALOR AS PRECO_VENDA
, P.PESO
--, P.ESTO AS QTD
, P.ESTOM AS QTD_IDEAL
, P.QTDEUNENT AS FAT_CONV
--, P.APLICACAO AS OBSERVACOES
, P.OBSERVACOES
, P.COMISSAOVENDAINTERNA AS COMISSAO
, P.CFOP_NO_ESTADO AS CF
, REPLACE (P.CEST,'.','') AS PERSONAL6
--, P.VENNOEST AS ST
, P.CSOSN AS ST
, P.CODIGO_AMP AS COD_ANP 
, P.CODIGO_PIS AS PIS_CODIGO
, P.CODIGO_COFINS AS COFINS_CODIGO
, P.CODIGO_PIS_COMPRAS AS PISE_CODIGO
, P.CODIGO_COFINS_COMPRAS AS COFINSE_CODIGO
, P.PCOFINS AS COFINS_ALIQ_NOR
, P.PPIS AS PIS_ALIQ_NOR
, P.CST_IPI AS IPI_CODIGO_VENDA
, P.IPI AS ALIQ_IPI_VENDA
, E.QTDE AS QTD
, UE.ABREV AS UND_COMPRA
, US.ABREV AS UND
, G.GRUPO 
, S.SUBGRUPO AS FAMILIA
, M.MARCA AS PERSONAL1
, PR.VALOR AS PRECO_VENDA
FROM PRODUTOS P
LEFT JOIN ESTOQUE E ON E.PRODUTO = P.CODIGO AND E.ALMOXARIFADO = '1'
LEFT JOIN UNIDADES UE ON UE.CODIGO = P.UNENT
LEFT JOIN UNIDADES US ON US.CODIGO = P.UNSAI 
LEFT JOIN GRUPOS G ON G.CODIGO = P.GRUPO 
LEFT JOIN SUBGRUPOS S ON S.CODIGO = P.SUBGRUPO AND S.GRUPO = G.CODIGO 
LEFT JOIN MARCAS M ON M.CODIGO = P.MARCA 
LEFT JOIN TABPREDET PR ON PR.PRODUTO = P.CODIGO AND PR.TABELA = '1' --SE NECESSÁRIO, VERIFICAR E AJUSTAR O CÓDIGO DA TABELA DE PREÇOS 
