SELECT
    FORCOD AS CODIGO,
    FORDES AS NOME,
    FORCPF AS CNPJ_CNPF,
    FORIE AS IE_RG,
    FOREND AS ENDERECO,
    FORBAI AS BAIRRO,
    FORCID AS CIDADE,
    FOREST AS UF,
    FORTEL AS TELEFONE,
    FORFAX AS FAX,
    FORCEP AS CEP,
    FORCON AS CONTATO,
    FOROBS AS OBSERVACOES
FROM FORNECEDOR