SELECT
    CLIENTE.COD_CLIENTE AS CODIGO,
    CLIENTE.NRO_CPF_CGC AS CNPJ_CNPF,
    CLIENTE.NRO_RG AS IE_RG,
    CLIENTE.NOM_CLIENTE AS NOME,
    CLIENTE.END_CLIENTE AS ENDERECO,
    CLIENTE.BAI_CLIENTE AS BAIRRO,
    CLIENTE.NRO_CEP_CLIENTE AS CEP,
    CLIENTE.CID_CLIENTE AS CIDADE,
    CLIENTE.UF_CLIENTE AS UF,
    CLIENTE.DDD_CLIENTE ||''|| CLIENTE.TELEFONE_RESIDENCIA_CLIENTE AS TELEFONE,
    CLIENTE.DDD_CLIENTE ||''|| CLIENTE.NRO_CELULAR_CLIENTE AS CELULAR,
    CLIENTE.NRO_CELULAR_CLIENTE,
    CLIENTE.NOM_PESSOA_CONTATO_CLIENTE AS CONTATO,
    CLIENTE.DES_EMAIL_CLIENTE AS EMAIL
FROM CLIENTE