SELECT
    FORNECEDOR.COD_FORNECEDOR AS CODIGO,
    FORNECEDOR.NRO_CGC_FORNECEDOR AS CNPJ_CNPF,
    FORNECEDOR.NOM_FORNECEDOR AS FANTASIA,
    FORNECEDOR.NOM_RAZAO_SOCIAL AS NOME,
    FORNECEDOR.END_FORNECEDOR AS ENDERECO,
    FORNECEDOR.BAI_FORNECEDOR AS BAIRRO,
    FORNECEDOR.CEP_FORNECEDOR AS CEP,
    FORNECEDOR.CID_FORNECEDOR AS CIDADE,
    FORNECEDOR.COD_UF_FORNECEDOR AS UF,
    FORNECEDOR.NRO_INSCRICAO_ESTADUAL AS IE_RG,
    FORNECEDOR.DDD_FORNECEDOR  ||''|| FORNECEDOR.NRO_TEL_FORNECEDOR AS TELEFONE,
    FORNECEDOR.DDD_FORNECEDOR  ||''|| FORNECEDOR.NRO_FAX_FORNECEDOR AS FAX,
    NOM_PESSOA_CONTATO AS CONTATO
FROM FORNECEDOR