SELECT FORNECEDOR.ID AS CODIGO,
FORNECEDOR.NOME_DO_FORNECEDOR AS NOME,
FORNECEDOR.NOME_FANTASIA AS FANTASIA,
FORNECEDOR.INSC_ESTADUAL AS CNPJ_CNPF,
FORNECEDOR.ENDERECO,
FORNECEDOR.NUMERO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CIDADE,
FORNECEDOR.CEP,
FORNECEDOR.ESTADO AS UF,
FORNECEDOR.TELEFONE,
FORNECEDOR.FAX,
FORNECEDOR.CELULAR,
FORNECEDOR.EMAIL,
FORNECEDOR.INSC_ESTADUAL AS IE_RG
FROM FORNECEDOR


