SELECT 
PRODUTOS.ID AS COD_FABRICANTE,
PRODUTOS.DATA_INCLUSAO AS CADASTRO,
PRODUTOS.CODIGO_DE_BARRAS AS BARRAS,
GRUPO_PRODUTO.NOME AS GRUPO,
PRODUTOS.DESCRICAO_DETALHADA AS DESCRICAO,
FORNECEDOR.NOME_DO_FORNECEDOR AS FORNECEDOR,
PRODUTOS.DATA_ULT_COMPRA AS ULTIMA_COMPRA,
PRODUTOS.LOCALIZACAO AS CARACTERISTICAS,
PRODUTOS.DATA_ULT_VENDA AS ULTIMA_VENDA,
PRODUTOS.VALOR_UNITARIO AS PRECO_CUSTO,
PRODUTOS.VALOR_VENDA AS PRECO_VENDA,
PRODUTOS.ESTOQUE_ATUAL AS QTD,
PRODUTOS.NBM AS COD_NCM,
TRIBUT_GRUPO.PAF_P_ST AS ST,
UNIDADE.SIGLA AS UND,
PRODUTOS.DATA_ALTERACAO AS ALTERACAO_PRECO,
PRODUTOS.CEST AS PERSONAL6,
PRODUTOS.DESCRICAO_DETALHADA AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPO_PRODUTO ON PRODUTOS.ID_GRUPO=GRUPO_PRODUTO.ID
LEFT JOIN FORNECEDOR ON PRODUTOS.ID_FORNECEDOR=FORNECEDOR.ID
LEFT JOIN TRIBUT_GRUPO ON PRODUTOS.ID_TRIBUTACAO=TRIBUT_GRUPO.ID
LEFT JOIN UNIDADE ON PRODUTOS.ID_UNIDADE_MEDIDA=UNIDADE.ID


