SELECT
       ESTOQUE.CODIGO AS CODIGO
      ,ESTOQUE.NOME AS DESCRICAO
      ,SUBGRUPO.NOME AS GRUPO
      ,ESTOQUE.ALTERADO AS ALTERACAO_PRECO
      ,ESTOQUE.UN AS UND
--,ESTQT.QTD AS QTD
      ,SUM(ESTQT.QTL) AS QTD
      ,ESTOQUE.CUSTO AS PRECO_CUSTO
      ,ESTOQUE.LUCRO AS MARGEM_LUCRO
      ,ESTOQUE.VENDA AS PRECO_VENDA
      ,ESTOQUE.DTULTVND AS ULTIMA_VENDA
      ,ESTOQUE.CADASTRO AS DATA_CADASTRO
      ,ESTOQUE.PESOL AS PESO
      ,ESTOQUE.TIPO AS ST
      ,ESTOQUE.CODNCM AS COD_NCM
      ,ESTOQUE.COMISSAO AS COMISSAO
      ,ESTOQUE.CODAUX1 AS COD_FABRICANTE
      ,ESTOQUE.OBS AS OBSERVACOES
      ,ESTOQUE.DTULTCO AS ULTIMA_COMPRA
      ,ESTOQUE.CODCEST AS PERSONAL6
FROM WN.dbo.ESTOQUE
left JOIN WN.dbo.SUBGRUPO ON SUBGRUPO.CODIGO = ESTOQUE.CODIGO
left JOIN WN.dbo.ESTQT ON ESTQT.CODPROD = ESTOQUE.CODIGO
--WHERE ESTQT.CODFIL = '1' OR ESTQT.CODFIL IS NULL
GROUP BY
ESTOQUE.CODIGO
      ,ESTOQUE.NOME
      ,SUBGRUPO.NOME
      ,ESTOQUE.ALTERADO
      ,ESTOQUE.UN
      ,ESTOQUE.CUSTO
      ,ESTOQUE.LUCRO
      ,ESTOQUE.VENDA
      ,ESTOQUE.DTULTVND
      ,ESTOQUE.CADASTRO
      ,ESTOQUE.PESOL
      ,ESTOQUE.TIPO
      ,ESTOQUE.CODNCM
      ,ESTOQUE.COMISSAO
      ,ESTOQUE.CODAUX1
      ,ESTOQUE.OBS
      ,ESTOQUE.DTULTCO
      ,ESTOQUE.CODCEST
