SELECT
  PESSOA.CD_PESSOA AS CODIGO,
  PESSOA.DS_PESSOA AS NOME,
  PESSOA_JURIDICA.NOME_FANTASIA AS FANTASIA,
  case when PESSOA_FISICA.CPF = '' or PESSOA_FISICA.CPF is null then PESSOA_JURIDICA.CNPJ else PESSOA_FISICA.CPF END AS CNPJ_CNPF,
  case when PESSOA_FISICA.RG = '' or PESSOA_FISICA.RG is null then PESSOA_JURIDICA.IE else PESSOA_FISICA.RG END AS IE_RG,
  PESSOA_JURIDICA.IM AS IM,
  ENDERECO.ENDERECO AS ENDERECO,
  BAIRRO.DS_BAIRRO AS BAIRRO,
  ENDERECO.COMPLEMENTO AS COMPLEMENTO,
  MUNICIPIO.DS_MUNICIPIO AS CIDADE,
  MUNICIPIO.CD_UF AS UF,
TELEFONES.DDD ||''|| TELEFONES.NUMERO_TELEFONE AS TELEFONE,
  ENDERECO.CEP AS CEP,
  PESSOA_FISICA.SEXO AS SEXO,
  CAST (PESSOA_FISICA.DT_NASCIMENTO AS DATE) AS NASCIMENTO,
  PESSOA_FISICA.CONJUGE AS CONJUGE,
  CAST (PESSOA.DT_CADASTRO AS DATE) AS CADASTRO,
  PESSOA.OBS AS OBSERVACOES
FROM PESSOA
LEFT JOIN PESSOA_FISICA ON PESSOA_FISICA.CD_PESSOA = PESSOA.CD_PESSOA
LEFT JOIN PESSOA_JURIDICA ON PESSOA_JURIDICA.CD_PESSOA = PESSOA.CD_PESSOA
LEFT JOIN ENDERECO ON ENDERECO.CD_PESSOA = PESSOA.CD_PESSOA
LEFT JOIN MUNICIPIO ON MUNICIPIO.CD_MUNICIPIO = ENDERECO.CD_MUNICIPIO
LEFT JOIN BAIRRO ON BAIRRO.CD_BAIRRO= ENDERECO.CD_BAIRRO
LEFT JOIN TELEFONES ON TELEFONES.CD_PESSOA = PESSOA.CD_PESSOA
WHERE PESSOA.TIPO_PESSOA = 'F'
