SELECT
    PESSOAS.PESSOAS_ID AS CODIGO,
    PESSOAS.PESSOA_NOME1 AS NOME,
    PESSOAS.PESSOA_CONTATO AS CONTATO,
ENDERECOS.LOGRADOURO AS ENDERECO,
ENDERECOS.COMPLEMENTO AS COMPLEMENTO,
ENDERECOS.BAIRRO AS BAIRRO,
ENDERECOS.CEP AS CEP,
ENDERECOS.NUMERO AS NUMERO,
MUNICIPIOS.MUNICIPIO_NOME AS CIDADE,
ESTADOS.ESTADO_SIGLA AS UF,
    PESSOAS.PESSOA_CPF_CNPJ AS CNPJ_CNPF,
    PESSOAS.PESSOA_RG_IE AS IE_RG,
    PESSOAS.PESSOA_EMAIL AS EMAIL,
    PESSOAS.PESSOA_TELEFONE AS TELEFONE,
    PESSOAS.PESSOA_CELULAR AS CELULAR
FROM PESSOAS
LEFT JOIN ENDERECOS ON PESSOAS.PESSOAS_ID = ENDERECOS.PESSOAS_ID
LEFT JOIN DISTRITOS ON ENDERECOS.DISTRITOS_ID = DISTRITOS.DISTRITOS_ID
LEFT JOIN MUNICIPIOS ON DISTRITOS.MUNICIPIOS_ID = MUNICIPIOS.MUNICIPIOS_ID
LEFT JOIN ESTADOS ON MUNICIPIOS.ESTADOS_ID = ESTADOS.ESTADOS_ID
