SELECT
  CADPRO.CODPRO AS CODIGO,
  CADPRO.NOME AS DESCRICAO,
  CADPRO.APLICACAO AS CARACTERISTICAS,
  CADFOR.RAZAO AS FORNECEDOR,
  CADGRU.NOME AS GRUPO,
  CADPRO.CODBARRA AS BARRAS,
  CADPRO.PRCCUSTO AS PRECO_CUSTO,
  CADPRO.PVENDA1 AS PRECO_VENDA,
  ESTQUE.QTDE AS QTD,
  CADPRO.ESTQMIN AS QTD_IDEAL,
  SUBSTRING(CADPRO.SITTRIBUTARIA FROM 2 FOR 3) AS ST,
  CADPRO.UNIDADE AS UND,
  CADPRO.PLUCRO AS MARGEM_LUCRO,
  CADPRO.PESO AS PESO,
  CADPRO.CODFAB AS COD_FABRICANTE,
  CADPRO.COMISSAO AS COMISSAO,
  CADPRO.CODNCM AS COD_NCM,
  CADPRO.DATACADASTRO AS DATA_CADASTRO,
  CADPRO.CEST AS PERSONAL6
FROM CADPRO
LEFT JOIN CADGRU ON CADGRU.CODGRU = CADPRO.CODGRU
LEFT JOIN CADFOR ON CADFOR.CODFOR = CADPRO.CODFOR
LEFT JOIN ESTQUE ON ESTQUE.CODPRO = CADPRO.CODPRO
WHERE CADPRO.NOME IS NOT NULL
