SELECT
  --CADTRANS.CODIGO AS CODIGO,
  CADTRANS.NOME AS RAZAO_SOCIAL,
  CADTRANS.ENDERECO AS ENDERECO,
  CADTRANS.CIDADE AS CIDADE,
  CADTRANS.ESTADO AS UF,
  CADTRANS.PLACA AS PLACA,
  CADTRANS.CGC AS CPPJ_CNPF,
  CADTRANS.INSCREST AS IE_RG,
  CADTRANS.TELEFONE AS TELEFONE,
  CADTRANS.RNTCR
FROM CADTRANS
WHERE CADTRANS.NOME IS NOT NULL