SELECT
    --IDPRODUTO AS CODIGO,
    NPROD AS CODIGO,
    DESCRICAO,
    MARCA AS CARACTERISTICAS,
    GRUPO AS GRUPO,
    UN AS UND,
    PRECOCOMPRA AS PRECO_CUSTO ,
    PRECOVENDA AS PRECO_VENDA,
    CODBARRAS AS BARRAS,
    QTDEDISP AS QTD,
    CST AS ST
FROM PRODUTOS
