SELECT
    CODIGO,
    NOME,
    RAZAO_SOCIAl AS FANTASIAL,
    ENDERECO,
    BAIRRO,
    CIDADE,
    CEP,
    ESTADO AS UF,
    FONE AS TELEFONE,
    CELULAR,
    CONTATO,
    CGC_CPF AS CNPJ_CNPF,
    INSCR_EST AS IE_RG,
    EMAIL,
    DATA AS CADASTRO
FROM CLIENTES
