SELECT
    CLIENTE.CODIGO AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLIENTE.RAZAO AS FANTASIA,
    CLIENTE.CONTATO AS CONTATO,
    case when CLIENTE.CPF = '' or CLIENTE.CPF is null then CLIENTE.CNPJ else CLIENTE.CPF END AS CNPJ_CNPF,
    case when CLIENTE.RG = '' or CLIENTE.RG is null then CLIENTE.IE else CLIENTE.RG END AS IE_RG,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,  
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.BAIRRO AS BAIRRO,
    CIDADES.NOME AS CIDADE,
    CIDADES.ESTADO AS UF,
    CLIENTE.CEP AS CEP,
    CLIENTE.FONE AS TELEFONE,
    CLIENTE.FAX AS FAX,
    CLIENTE.CELULAR AS CELULAR,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.NOMEPAI AS PAI,
    CLIENTE.NOMEMAE AS MAE,
    CLIENTE.ESTACIVIL AS EST_CIVIL,
    CLIENTE.SEXO AS SEXO,
    CLIENTE.CONJUGE AS CONJUGE,
    CLIENTE.OBS AS OBSERVACOES,
    CAST (CLIENTE.DNASCI AS DATE) AS NASCIMENTO,
    CAST (CLIENTE.DATACADAS AS DATE) AS CADASTRO
FROM CLIENTE
LEFT JOIN CIDADES ON CIDADES.CODIGO = CLIENTE.CIDADE
WHERE CLIENTE.NOME <> 'CONSUMIDOR'