SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.ESTOQUE AS QTD,
    PRODUTO.ESTOMINI AS QTD_IDEAL,
    FORNECEDOR. RAZAO AS FORNECEDOR,
    PRODUTO.PESOLIQUIDO AS PESO,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTO.PRECOMPRA AS PRECO_CUSTO,
    PRODUTO.PERLUCRO AS MARGEM_LUCRO,
    PRODUTO.PRECOVENDA AS PRECO_VENDA,
    PRODUTO.ALIQUOTA AS ST,
    CAST (PRODUTO.DULTCOMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (PRODUTO.DULTVENDA AS DATE) AS ULTIMA_VENDA,
    CAST (PRODUTO.DATAATUAL AS DATE) AS ALTERACAO_PRECO,
    CAST (PRODUTO.DATACADAS AS DATE) AS DATA_CADASTRO,
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.CPRODFORNECEDOR AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CODIGO = PRODUTO.SUBGRUPO
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTO.FORNECEDOR