SELECT
    COD_CLIENTE AS CODIGO,
    CLIENTE AS NOME,
    NOME_FANTASIA AS FANTASIA,
    CGC_CPF AS CNPJ_CNPF,
    COALESCE(INSC_ESTADUAL, '') || COALESCE (RG, '') AS IE_RG,
    CONTATO AS CONTATO,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CEP AS CEP,
    CIDADE AS CIDADE,
    UF AS UF,
    FONE AS TELEFONE,
    EMAIL AS EMAIL,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO
FROM CLIENTE