SELECT
    COD_FORNECEDOR AS CODIGO,
    NOME AS NOME,
    NOME_FANTASIA AS FANTASIA,
    CGC_CPF AS CNPJ_CNPF,
    INSC_ESTADUAL AS IE_RG,
    ENDERECO AS ENDERECO,
    CEP AS CEP,
    BAIRRO AS BAIRRO,
    MUNICIPIO AS CIDADE,
    UF AS UF,
    CONTATO AS CONTATO,
    FONE AS TELEFONE,
    EMAIL AS EMAIL,
    NUMERO AS NUMERO
FROM FORNECEDOR