SELECT
    COD_PRODUTO AS CODIGO,
    FORNECEDOR AS FORNECEDOR,
    DESCRICAO AS DESCRICAO,
    QUANTIDADE AS QTD,
    PRECO_COMPRA AS PRECO_CUSTO,
    PRECO_VENDA AS PRECO_VENDA,
    DOLAR AS PRECO_DOLAR,
    CATEGORIA AS GRUPO,
    UNIDADE AS UND,
    ST AS ST,
    BARRAS1 AS BARRAS,
    NCM AS COD_NCM,
    CEST AS PERSONAL6
FROM PRODUTO