SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.COD_BARRAS AS BARRAS,
    PRODUTO.DESCRICAO AS DESCRICAO,
    UNIDADE.UNIDADE AS UND,
    PRODUTO.EST_MIN AS QTD_IDEAL,
    PRODUTO.ESTOQUE AS QTD,
    PRODUTO.PESO_LIQ AS PESO,
    GRUPO.GRUPO AS GRUPO,
    SUBGRUPO.SUB_GRUPO AS FAMILIA,
    PRODUTO.PRECO_VENDA AS PRECO_VENDA,
    MAX (SIT_TRIBUTARIA.CODIGO) AS ST,
    PRODUTO.OBSERVACAO AS OBSERVACOES,
    PRODUTO.ULT_ALTERACAO AS ALTERACAO_PRECO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.PRODUTO_ID = PRODUTO.ID
LEFT JOIN SIT_TRIBUTARIA ON SIT_TRIBUTARIA.ID = TRIBUTACAO.SITUACAO
LEFT JOIN UNIDADE ON UNIDADE.ID = PRODUTO.UNIDADE
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTO.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.ID = PRODUTO.SUBGRUPO
GROUP BY 1,2,3,4,5,6,7,8,9,10,12,13,14,15,16
