SELECT
  cod_cliente         AS CODIGO,
  nome                AS NOME,
  nome_fantasia       AS FANTASIA,
  contato             AS CONTATO,
  COALESCE(cnpj, cpf) AS CNPJ_CNPF,
  COALESCE(inscr, rg) AS IE_RG,
  identidade          AS IM,
  ender               AS ENDERECO,
  numero_predio       AS NUMERO,
  complemento         AS COMPLEMENTO,
  bairro              AS BAIRRO,
  cidade              AS CIDADE,
  cod_municipio       AS ID_MUNICIPIO,
  estado              AS UF,
  cep                 AS CEP,
  fone1               AS TELEFONE,
  fone_contato        AS CELULAR,
  fax                 AS FAX,
  e_mail              AS EMAIL,
  salario             AS RENDA,
  limite_credito      AS LIMITE_CREDITO,
  observacao          AS OBSERVACOES,
  pai                 AS PAI,
  mae                 AS MAE,
  cidade              AS NATURALIDADE,
  profissao           AS PROFISSAO
FROM clientes;