SELECT 
       FORNECEDOR.FO_CODIGO AS CODIGO,
       ENDERECO.EN_CGCCPF AS CNPJ,
       ENDERECO.EN_UFSIGLA AS UF,
       ENDERECO.EN_ENDERECO AS ENDERECO,
       ENDERECO.EN_CIDADE AS CIDADE,
       ENDERECO.EN_TELEFONE AS TELEFONE,
       ENDERECO.EN_IERG AS IE,
       ENDERECO.EN_RASOCIAL AS RAZAO_SOCIAL,
       ENDERECO.EN_NUMERO AS NUMERO,
       ENDERECO.EN_EMAIL AS EMAIL
  FROM Megasul_SQL.dbo.FORNECEDOR
  INNER JOIN Megasul_SQL.dbo.ENDERECO ON ENDERECO.EN_CODIGO = FORNECEDOR.FO_ENCODIGO
  WHERE FORNECEDOR.FO_TRANSPORTADORA = 'S'
