SELECT
	P.Registro AS CODIGO,
	P.Codigo AS BARRAS,
	P.Descricao AS DESCRICAO,
	G.DESCRICAO AS GRUPO,
	P.Unidade AS UND,
	P.QUANTIDADE AS QTD,
	P.CONSUMIDOR AS PRECO_VENDA,
	P.CUSTO AS PRECO_CUSTO,
	P.NCM AS COD_NCM,
	P.CST AS ST,
	SUBSTRING(P.CFOP, 1,3) AS ELO,
	P.MARGEM AS MARGEM_LUCRO,
	P.CEST AS PERSONAL6
FROM Produtos P
LEFT JOIN GRUPOS G ON P.Grupo = G.CODIGO 