SELECT 
  P.PRO_CODIGO AS COD_FABRICANTE
, P.PRO_DESCRICAO AS DESCRICAO
, P.PRO_MARCA AS PERSONAL1 
, P.PRO_MODELO AS PERSONAL2
, RIGHT (P.PRO_CST,2) AS ST
--, P.LEFT (PRO_CST,1) AS OST
, P.PRO_NCM AS COD_NCM
, CASE P.PRO_ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.PRO_EST_MINIMO AS QTD_IDEAL
, P.PRO_QTD_CAIXA_COMP AS FAT_CONV
, P.PRO_PESO_UNIT AS PESO
--, P.PRO_CUSTO_TOTAL AS PRECO_CUSTO
, P.PRO_PRECO_COMPRA AS PRECO_CUSTO
, P.PRO_COMPRA_MEDIO AS CUSTO_MEDIO
, P.PRO_COMISSAO AS COMISSAO
, P.PRO_ORIGEM AS OST
, P.PRO_CEST AS PERSONAL6
, P.PRO_QTD_ATACADO AS QTD_PRECO_ATACADO
, P.PRO_DIAS_VALID_BAL AS VALIDADE_DIAS
, P.PRO_IPI AS IPI_CODIGO_VENDA 
, P.PRO_PERC_IPI AS ALIQ_IPI_VENDA
, P.PRO_CST_PIS_ENT AS PISE_CODIGO
, P.PRO_CST_PIS_SAI AS PIS_CODIGO
, P.PRO_CST_COFINS_ENT AS COFINSE_CODIGO
, P.PRO_CST_COFINS_SAI AS COFINS_CODIGO
, P.PRO_ALIQ_PIS_ENT AS PISE_ALIQ_NOR
, P.PRO_ALIQ_PIS_SAI AS PIS_ALIQ_NOR
, P.PRO_ALIQ_COFINS_ENT AS COFINSE_ALIQ_NOR
, P.PRO_ALIQ_COFINS_SAI AS COFINS_ALIQ_NOR
, U.UNI_SIGLA AS UND
, C.COR_DESCRICAO AS COR
, T.TAM_DESCRICAO AS TAMANHO
, PE.PES_NOME AS FORNECEDOR
, G.GRU_DESCRICAO AS GRUPO
, PB.PRE_EAN AS BARRAS
, ES.PRE_QUANTIDADE AS QTD
, PT.PRT_PRECO AS PRECO_VENDA
, SUBSTRING(TT.TTR_DESCRICAO FROM 1 FOR 3) AS ELO
FROM PRODUTOS P
LEFT JOIN UNIDADES U ON U.UNI_ID = P.UNI_ID_FK
LEFT JOIN CORES C ON C.COR_ID = P.COR_ID_FK
LEFT JOIN TAMANHOS T ON T.TAM_ID = P.TAM_ID_FK
LEFT JOIN PESSOAS PE ON PE.PES_ID = P.PES_ID_FK
LEFT JOIN GRUPOS G ON G.GRU_ID = P.GRU_ID_FK
LEFT JOIN PRODUTOS_EAN PB ON PB.PRO_ID_FK = P.PRO_ID AND PB.PRE_CONT <> 2
LEFT JOIN PRODUTOS_ESTOQUE ES ON ES.PRO_ID_FK = P.PRO_ID
LEFT JOIN PRODUTOS_TABELA PT ON PT.PRO_ID_FK = P.PRO_ID
LEFT JOIN TIPOS_TRIBUT TT ON TT.TTR_ID = P.TTR_ID_FK
