SELECT FORNECEDOR.CODIGO,
FORNECEDOR.NOME,
FORNECEDOR.FANTASIA,
FORNECEDOR.CGC_CNPJ AS CNPJ_CNPF,
FORNECEDOR.IE AS IE_RG,
ENDERECO.ENDERECO,
CIDADE.NOME AS CIDADE,
CIDADE.UF,
ENDERECO.BAIRRO,
ENDERECO.CEP,
ENDERECO.NUMERO,
ENDERECO.COMPLEMENTO,
FORNECEDOR.CONTATO,
FORNECEDOR.FONE AS TELEFONE,
FORNECEDOR.FAX,
FORNECEDOR.CELL AS CELULAR,
FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN ENDERECO ON FORNECEDOR.ENDERECO=ENDERECO.CODIGO
LEFT JOIN CIDADE ON ENDERECO.CIDADE=CIDADE.CODIGO
