SELECT 
  C.CB AS CODIGO
, C.NOME
, C.APELIDO AS FANTASIA
, C.CADASTRO
, C.NASCIMENTO
, C.CPF AS CNPJ_CNPF
, C.RG AS IE_RG
, C.MAE
, C.PAI
, C.TEL1 AS TELEFONE
, C.TEL2 AS FAX
, C.CONTATO1 AS CONTATO
, C.TELCONT1 AS CELULAR
, C.OBSERVACAO AS OBSERVACOES
, C.EMAIL
, C.LIMITE AS LIMITE_CREDITO
, C.CONJUGE
, C.EMPRESA AS LOCTRA
, C.ENDERECO
, C.PREF AS COMPLEMENTO
, C.CEP
, B.DESCRICAO AS BAIRRO
, CI.DESCRICAO AS CIDADE
, CI.UF 
FROM CADASTRO C
LEFT JOIN CIDADE CI ON CI.CODIGOCID = C.CODIGOCID
LEFT JOIN BAIRRO B ON B.CODIGOBAI = C.CODIGOBAI