SELECT 
  F.CODIGOFOR AS CODIGO
, F.CGC AS CNPJ_CNPF
, F.RAZAOSOCIAL AS NOME
, F.FANTASIA AS FANTASIA
, F.CONTATO1 AS CONTATO
, F.TELCONT1 AS CELULAR
, F.TEL1 AS TELEFONE
, F.TEL2 AS FAX
, F.EMAIL
, F.OBSERVACAO AS OBSERVACOES
, F.ENDERECO
, F.PREF AS COMPLEMENTO
, F.BAIRRO
, F.CEP
, F.CODIGOCID
, CI.DESCRICAO AS CIDADE
, CI.UF 
FROM FORNECEDORES F
LEFT JOIN CIDADE CI ON CI.CODIGOCID = F.CODIGOCID