SELECT 
  RIGHT(P.CODIGOPRO, 6) AS CODIGO  
, P.CODIGOPRO AS COD_FABRICANTE 
--, P.REFERENCIA 
, P.DESCRICAO
, P.UNIDADE AS UND
, P.QUANTIDADE AS QDT
, P.VL_CUSTO AS PRECO_CUSTO
, P.LUCRO AS MARGEM_LUCRO
, P.PRECO AS PRECO_VENDA
, P.VALORMINIMO AS PRECO_ATACADO
, P.MINIMO AS QTD_IDEAL
, RIGHT(P.ICMS, 3) AS ELO
, P.IPI AS ALIQ_IPI_VENDA
, P.DATAHORA AS DATA_CADASTRO
, P.FABRICANTE AS CARACTERISTICAS
, P.APLICACAO AS OBSERVACOES
, P.LOCALIZACAO AS PERSONAL1
, P.COMISSAO
, P.TAMANHO
--, P.CODIGOMAR
-- , CODIGOGRU
, G.DESCRICAO AS GRUPO
, M.DESCRICAO AS FAMILIA
FROM PRODUTO P
LEFT JOIN GRUPO G ON G.CODIGOGRU = P.CODIGOGRU 
LEFT JOIN MARCA M ON M.CODIGOMAR = P.CODIGOMAR