SELECT
  CLIENTES.CODCLIENTE AS CODIGO,
  CLIENTES.NOME AS NOME,
  CLIENTES.NOMEFANTASIA AS FANTASIA,
  CLIENTES.DATACADASTRO,
  CLIENTES.SEXO AS SEXO,
  CLIENTES.ESTADOCIVIL AS EST_CIVIL,
  CLIENTES.DATANASC AS NASCIMENTO,
  CLIENTES.CPFCNPJ AS CNPJ_CNPF,
  CASE WHEN CLIENTES.RG = '' or CLIENTES.RG IS NULL THEN CLIENTES.IE ELSE CLIENTES.RG END AS IE_RG,
  CLIENTES_ENDERECOS.ENDERECO AS ENDERECO,
  CLIENTES_ENDERECOS.NUMERO AS NUMERO,
  CLIENTES_ENDERECOS.BAIRRO AS BAIRRO,
  CLIENTES_ENDERECOS.COMPLEMENTO AS COMPLEMENTO,
  CLIENTES_ENDERECOS.CEP AS CEP,
  CIDADES.CIDADE AS CIDADE,
  CIDADES.UF AS UF,
  CLIENTES.EMAIL AS EMAIL,
  CLIENTES.NOMEPAI AS PAI,
  CLIENTES.NOMEMAE MAE,
  CLIENTES.FONERESID AS TELEFONE,
  CLIENTES.CELULAR AS CELULAR,
  CLIENTES.FAX AS FAX,
  CLIENTES.OBSERVACAOINTERNA AS OBSERVACOES,
  CLIENTES.PROFISSAO AS PROFISSAO
FROM CLIENTES
LEFT JOIN CLIENTES_ENDERECOS ON CLIENTES_ENDERECOS.CODCLIENTE = CLIENTES.CODCLIENTE
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = CLIENTES_ENDERECOS.CODCIDADE
where clientes_enderecos.principal = 'S';
