SELECT
    CG.CODCAD AS CODIGO,
    CG.RAZAO AS NOME,
    CG.FANTASIA,
    CG.CONTATO,
    CG.ENDERECO,
    CG.BAIRRO,
    COALESCE (CG."DATA", CURRENT_DATE) AS CADASTRO,
    CG.FAX,
    CG.FONE AS TELEFONE,
    CG.CELULAR,
    CG.CNPJ AS CNPJ_CNPF,
    CG.IE AS IE_RG,
    CG.INSCRIMUN AS IM,
    CG.EMAIL,
    CG.LIMCRED AS LIMITE_CREDITO,
--    CG.OBSERVACOES,
    CG.OBS,    
    CG.PAI,
    CG.MAE,
    CG.DATANASC AS NASCIMENTO,
    CG.ESTCIVIL AS EST_CIVIL,
    CG.CONJUGE,
    CG.EMPRESA AS LOCTRA,
    C.NOME AS CIDADE,
    E.UF,
    cG.cep,
  -- SUBSTRING (C.CEP from 1 For 2) || SUBSTRING (C.CEP from 4 For 7) AS cep,
    U.NOME AS PERSONAL1
FROM CAD_GERAL CG
LEFT JOIN CIDADE C ON C.cod_ibge = CG.cidade_ibge
LEFT JOIN USUARIO U ON U.CODUSU = CG.VENDEDOR
LEFT JOIN estados E ON C.cod_uf = E.coduf
WHERE FORN = '1'