SELECT
	FOFORNEC AS PERSONAL1,
	FORAZSOC AS NOME,
	FONOMFAN AS FANTASIA,
	FOCGCCPF AS CNPJ_CNPF,
	FOINSEST AS IE_RG,
	FOENDERE AS ENDERECO,
	FOCIDADE AS CIDADE,
	FOUNIFED AS UF,
	FOCODEND AS CEP,
	FOTELEFO AS TELEFONE,
	FONUMFAX AS FAX,
	FOENDELE AS EMAIL,
	FOOBSCON AS OBSERVACOES
FROM
	CPGA02
