SELECT
    ID AS DOCUMENTO,
    ID_FORNECE AS CODIGO,
    NOME_FORNECE AS NOM_FORNECEDOR,
    NR_DOCUM AS HISTORICO,
    VLR_PARCEL AS VALOR_DUP,
    DATA_VENC AS VENCIMENTO,
    DATA_INC AS EMISSAO,
'' AS CNPJ
FROM CONTAS_APAGAR
