SELECT
    CLIENTES.RAZSOC AS NOME,
    CLIENTES.NOMFANT AS FANTASIA,
    CLIENTES.NUMERO AS CNPJ_CNPF,
    case when CLIFISIC.RG= '' or CLIFISIC.RG is null then CLIJURID.IE else CLIFISIC.RG END AS IE_RG,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.BAIRRO AS BAIRRO,
    CLIENTES.CID AS CIDADE,
    CLIENTES.CEP AS CEP,
    CLIENTES.EST AS UF,
    CLIENTES.TEL AS TELEFONE,
    MAX (CLITEL.DDD ||''|| CLITEL.FONE) AS CELULAR,
    CLIENTES.FAX AS FAX,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.OBS ||' / '|| CLIENTES.COMP1 AS OBSERVACOES,
    CLIENTES.DTCAD AS CADASTRO,
    CLIENTES.LIMITECREDITO AS LIMITE_CREDITO
FROM CLIENTES
LEFT JOIN CLIFISIC ON CLIFISIC.NUMERO = CLIENTES.NUMERO 
LEFT JOIN CLIJURID ON CLIJURID.NUMERO = CLIENTES.NUMERO 
LEFT JOIN CLITEL ON CLITEL.NUMEROCLI = CLIENTES.NUMERO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17
