SELECT
    FORNEC.RAZSOC AS NOME,
    FORNEC.NOMFANT AS FANTASIA,
    FORNEC.NUMERO AS CNPJ_CNF,
    CLIJURID.IE AS IE_RG,
    FORNEC.ENDERECO AS ENDERECO,
    FORNEC.COMPLEMENTO AS COMPLEMENTO,
    FORNEC.BAIRRO AS BAIRRO,
    FORNEC.CID AS CIDADE,
    FORNEC.CEP AS CEP,
    FORNEC.EST AS UF,
    FORNEC.FONE AS TELEFONE,
    MAX (CLITEL.DDD ||''|| CLITEL.FONE) AS CELULAR,
    FORNEC.FAX AS FAX,
    FORNEC.EMAIL AS EMAIL,
    FORNEC.OBS AS OBSERVACOES
FROM FORNEC
LEFT JOIN CLIJURID ON CLIJURID.NUMERO = FORNEC.NUMERO
LEFT JOIN CLITEL ON CLITEL.NUMEROCLI = FORNEC.NUMERO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,13,14,15