SELECT
  FORNECEDOR.CD_FORNECEDOR AS CODIGO,
  FORNECEDOR.NM_FORNECEDOR AS NOME,
  FORNECEDOR.NM_FANTASIA AS FANTASIA,
  FORNECEDOR.ENDERECO AS ENDERECO,
  FORNECEDOR.BAIRRO AS BAIRRO,
  CIDADE.NM_CIDADE AS CIDADE,
  CIDADE.UF AS UF,
  FORNECEDOR.CEP AS CEP,
  FORNECEDOR.FONE AS FONE,
  FORNECEDOR.FAX AS FAX,
  FORNECEDOR.PESSOA_CONTATO AS CONTATO,
  FORNECEDOR.CNPJ AS CNPJ_CNPF,
  FORNECEDOR.INSCRICAO AS IE_RG,
  FORNECEDOR.OBSERVACAO_FORNECEDOR AS OBSERVACOES,
  FORNECEDOR.E_MAIL AS EMAIL,
  FORNECEDOR.CELULAR AS CELULAR,
  FORNECEDOR.NUMERO AS NUMERO,
  FORNECEDOR.COMPLEMENTO AS COMPLEMENTO
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.CD_CIDADE = FORNECEDOR.CD_CIDADE
