SELECT
	CT.CODIGO,
	CT.NOME,
	CT.FANTASIA,	
	CT.CPF_CNPJ AS CNPJ_CNPF,
	CASE WHEN CT.RG = '' OR CT.RG IS NULL THEN CT.RG_INSCESTADUAL ELSE CT.RG END AS IE_RG,
	CT.ENDERECO,
	CT.NRO_ENDERECO AS NUMERO,	
	CT.COMPLEMENTO,
	CT.BAIRRO,
	CT.CEP,
	CT.EMAIL,
	CT.OBSERVACOES,
	CM.NOME AS CIDADE, 
	CM.UF
FROM
	CAD_TERCEIROS CT
LEFT JOIN CAD_MUNICIPIOS CM ON CM.CODIGO = CT.MUNICIPIO  
RIGHT JOIN CAD_TERCEIROS_FORNECEDORES CTF ON CTF.CODIGO = CT.CODIGO 
