SELECT
	CP.CODIGO,
	CP.NOME AS DESCRICAO,
	CP.DATA_INC AS DATA_CADASTRO,
	CP.REFERENCIA AS COD_FABRICANTE,
	CP.QTD_MINIMA AS QTD_IDEAL,
	CP.BARRAS,
	CP.IPI AS ALIQ_IPI,
	CASE CP.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	CP.OBSERVACAO AS OBSERVACOES,
	CP.PESO_BRUTO AS PESO,	
	CP.NCM AS COD_NCM,
	CP.TIPO_ITEM_SPED AS PERSONAL1,
	CP.PROD_DIAS_VALIDADE AS VALIDADE_DIAS,	
	CP.ALIQUOTA_COMISSAO_VENDAS AS COMISSAO,
	CP.COD_CEST AS PERSONAL6,
	EE.QTD_EMPRESA AS QTD,
	C.CUSTO_BRUTO AS PRECO_CUSTO,
	P.PERC AS MARGEM_LUCRO, 
	P.PRECO AS PRECO_VENDA,
	CC.NOME AS GRUPO,
	S.NOME AS FAMILIA,
	M.NOME AS CARACTERISTICAS,
	CU.NOME_REDUZIDO AS UND,
	TT.NOME,
	TD.ST
FROM
	CAD_PRODUTOS CP
LEFT JOIN EST_ESTOQUES EE ON EE.PRODUTO = CP.CODIGO 
LEFT JOIN CAD_PRODUTOS_CUSTOS C ON C.EMPRESA = CP.EMPRESA AND C.CODIGO = CP.CODIGO AND C.ESTABELEC = CP.ESTABELEC
LEFT JOIN CAD_PRODUTOS_PRECOS P ON P.CODIGO = CP.CODIGO 
LEFT JOIN CAD_SETORES S ON S.EMPRESA = CP.EMPRESA AND S.CODIGO = CP.SETOR
LEFT JOIN CAD_MARCAS M ON M.EMPRESA = CP.EMPRESA AND M.CODIGO = CP.MARCA
LEFT JOIN CAD_UNIDADES CU ON CU.CODIGO = CP.UNIDADE AND CU.EMPRESA = CP.EMPRESA
LEFT JOIN CAD_CATEGORIAS CC ON CC.CODIGO = CP.CODIGO_CATEGORIA  
LEFT JOIN CAD_ESTABELECIMENTOS CE ON CE.CODIGO = CP.ESTABELEC 
LEFT JOIN CAD_MUNICIPIOS CM ON CM.CODIGO = CE.MUNICIPIO 
LEFT JOIN CAD_PRODUTOS_TAB_TRIB ICMS ON ICMS.CODIGO = CP.CODIGO
LEFT JOIN CAD_TABELA_TRIBUTARIA TT ON TT.CODIGO = ICMS.TAB_TRIB 
LEFT JOIN CAD_TAB_TRIB_DETALHE TD ON TD.CODIGO = TT.CODIGO AND TD.UF = CM.UF 
