SELECT GPCLIENTE.CD_CLIENTE AS CODIGO,
GPCLIENTE.NM_CLIENTE AS NOME,
GPCLIENTE.ES_PROFISSAO AS PROFISSAO,
GPCLIENTE.ES_DOCUMENTO AS CNPJ_CNPF,
GPCLIENTE.ES_ENDERECO AS ENDERECO,
GPCLIENTE.ES_BAIRRO AS BAIRRO,
GPCLIENTE.ES_CIDADE AS CIDADE,
GPCLIENTE.ES_CEP AS CEP,
GPCLIENTE.ES_ESTADO AS UF,
GPCLIENTE.ES_TELEFONE1 AS TELEFONE,
GPCLIENTE.ES_EMAIL AS EMAIL,
GPCLIENTE.TX_OBS AS OBSERVACOES
FROM GPCLIENTE
WHERE GPCLIENTE.CD_CLIENTE>0

