SELECT GPMATERIAL.CD_MATERIAL AS CODIGO,
GPMATERIAL.SG_MATERIAL AS BARRAS,
GPMATERIAL.SG_MATERIAL AS COD_FABRICANTE,
GPUNIDADE.SG_UNIDADE AS UND,
GPMATERIAL.DS_MATERIAL AS DESCRICAO,
GPGRUPOMATERIAL.DS_GRUPOMATERIAL AS GRUPO,
GPMATERIAL.VL_PRECO AS PRECO_VENDA,
GPMATERIAL.VL_CUSTO AS PRECO_CUSTO,
GPESTOQUE.QT_ESTOQUE AS QTD
FROM GPMATERIAL
LEFT JOIN GPUNIDADE ON GPMATERIAL.CD_UNIDADE=GPUNIDADE.CD_UNIDADE
LEFT JOIN GPGRUPOMATERIAL ON GPMATERIAL.CD_GRUPOMATERIAL=GPGRUPOMATERIAL.CD_GRUPOMATERIAL
LEFT JOIN GPESTOQUE ON GPMATERIAL.CD_MATERIAL=GPESTOQUE.CD_MATERIAL


