SELECT
	C.CODIGO,
	C.RAZAO_SOCIAL AS NOME,
	C.NOME_FANTASIA AS FANTASIA,
	C.ENDERECO,
	C.NUMERO,	
	C.BAIRRO,
	C.CEP,
	C.PONTO_REFERENCIA AS COMPLEMENTO,
	C.TELEFONE,
	C.FAX,
	C.EMAIL,
	CASE
		WHEN C.IDENTIDADE = ''
		OR C.IDENTIDADE IS NULL THEN C.INSCRICAO_ESTADUAL
		ELSE C.IDENTIDADE
	END AS IE_RG,	
	C.CGC_CPF AS CNPJ_CNPF,
	C.INSCRICAO_MUNICIPAL AS IM,
	C.LIMITE_CREDITO,
	C.DATA_ULTIMA_COMPRA AS ULTIMA_VENDA,
	C.DATA_NASCIMENTO AS NASCIMENTO,
	C.OBSERVACAO AS OBSERVACOES,
	C.DATA_CADASTRO AS CADASTRO,
	CASE
		C.INDICADOR_IE_DESTINATARIO WHEN '9' THEN 'N'
		WHEN '2' THEN 'I'
		WHEN '1' THEN 'C'
	END AS INDIEDEST,
	CI.NOME AS CIDADE,
	E.SIGLA AS UF	
FROM
	CLIENTE C
LEFT JOIN CIDADE CI ON CI.CODIGO = C.CODIGO_CIDADE
LEFT JOIN ESTADO E ON E.CODIGO = CI.CODIGO_ESTADO
