SELECT
	I.CODIGO,
	I.DESCRICAO,	
--	I.CODIGO_BALANCA AS BARRAS,
	I.CODIGO_BARRA AS BARRAS,
	I.REFERENCIA AS COD_FABRICANTE,
	CASE I.ATIVO WHEN '-1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	I.ULTIMA_COMPRA,
	I.ULTIMA_VENDA,
	I.ULTIMO_CUSTO_REAL AS PRECO_CUSTO,
	I.CUSTO_MEDIO_REAL AS CUSTO_MEDIO,
	I.ESTOQUE AS QTD,
	I.ESTOQUE_MINIMO AS QTD_IDEAL,
	CAST(I.DATA_CADASTRO AS DATE),
	I.QUANTIDADE_EMBALAGEM AS FAT_CONV,
	I.CODIGO_NCM AS COD_NCM,
	I.CEST AS PERSONAL6,
	I.DIAS_VALIDADE AS VALIDADE_DIAS,
	I.CODIGO_PRODUTO_ANP AS COD_ANP,
	I.OBSERVAC_ADICIONAIS_ITEM_NF AS OBSERVACOES,
	GI.DESCRICAO AS GRUPO,
	IE.CSOSN AS ST,
	C.COMISSAO,
	TF.PIS AS PIS_ALIQ_NOR,
	TF.COFINS AS COFINS_ALIQ_NOR,
	TF.SITUACAO_TRIBUTARIA_PIS AS PIS_CODIGO,
	TF.SITUACAO_TRIBUTARIA_COFINS AS COFINS_CODIGO,
	TF.PIS_ENTRADA AS PISE_ALIQ_NOR, 
	TF.COFINS_ENTRADA AS COFINSE_ALIQ_NOR, 
	TF.SITUACAO_TRIBUT_PIS_ENT AS PISE_CODIGO,
	TF.SITUACAO_TRIBUT_COFINS_ENT AS COFINSE_CODIGO,
	F.RAZAO_SOCIAL AS FORNECEDOR,
	UE.ABREVIATURA AS UND_COMPRA,
	US.ABREVIATURA AS UND,
	M.DESCRICAO AS CARACTERISTICAS,
	CI.DESCRICAO AS PERSONAL1,
	IP.PRECO AS PRECO_VENDA
FROM
	ITEM I
LEFT JOIN GRUPO_ITEM GI ON GI.CODIGO = I.CODIGO_GRUPO 
LEFT JOIN ICMS IC ON IC.CODIGO = I.CODIGO_ICMS 
LEFT JOIN ICMS_ESTADO IE ON IE.CODIGO_ICMS = IC.CODIGO 
LEFT JOIN COMISSAO C ON C.CODIGO = I.CODIGO_COMISSAO 
LEFT JOIN TRIBUTO_FEDERAL TF ON TF.CODIGO = I.CODIGO_TRIBUTO 
LEFT JOIN FABRICANTE F ON F.CODIGO = I.CODIGO_FABRICANTE 
LEFT JOIN UNIDADE UE ON UE.CODIGO = I.UNIDADE_PADRAO_ENTRADA 
LEFT JOIN UNIDADE US ON US.CODIGO = I.UNIDADE_PADRAO_SAIDA 
LEFT JOIN MARCA M ON M.CODIGO = I.CODIGO_MARCA 
LEFT JOIN CATEGORIA_ITEM CI ON CI.CODIGO = I.CODIGO_CATEGORIA_ITEM 
LEFT JOIN ITEM_PRECO IP ON IP.CODIGO_ITEM = I.CODIGO 
