SELECT
    NOME AS NOME,
    NOME_FANTASIA AS FANTASIA,
    CNPJ_CPF AS CNPJ_CNPF,
    IE_RG,
    ENDERECO,
    ENDERECO_COMPLEMENTO AS COMPLEMENTO,
    ENDERECO_NUMERO AS NUMERO,
    BAIRRO,
    CEP,
    TELEFONE,
    EMAIL,
    CIDADE,
    ESTADO AS UF,
    CELULAR
FROM EMPRESAS
WHERE FORNECEDOR = 'S' AND NOME <> ''
