SELECT
    M.CODIGOMATERIAL AS OBSERVACOES,
	M.CODIGOAUXILIAR AS COD_FABRICANTE,
	M.DESCRICAO,	
	case M.STATUS when 'A' then 'Ativo' else 'Inativo' end as SITUACAO, 
--	M.CLASSIFICACAO,
	--M.OBSERVACAO AS OBSERVACOES,
	M.UNIDADEENTRADA AS UND_COMPRA,
	M.UNIDADESAIDA AS UND,
	M.PRECOVENDA1 AS PRECO_VENDA,
	M.PERCMARGEM AS MARGEM_LUCRO,	
--	M.PERCPIS,
--	M.PERCCOFINS,
	M.PERCIPI AS ALIQ_IPI_VENDA,
	M.PESOBRUTO AS PESO,
	M.DIASVALIDADE AS VALIDADE_DIAS,
	M.PERCCOMISSAO AS COMISSAO,
	--M.CODIGOFABRICANTE AS COD_FABRICANTE,
	M.CODIGOTIPOTRIBUTACAO AS ST,
--	M.CUSTOADM,
--	M.CUSTOINFORMADO,
--	M.SITUACAOTRIBUTARIA,
	CAST(M.DATACADASTRO AS DATE) AS DATA_CADASTRO,	
	M.CODIGONCM AS COD_NCM,
	M.SPEDTIPOITEM AS TIPO_ITEM,
--	M.CODIGOGENERO,
	M.CODIGOANP AS COD_ANP,
	M.CODIGOCEST AS PERSONAL6,
	T.CSTIPIENTRADA AS IPI_CODIGO,
	T.CSTIPISAIDA AS IPI_CODIGO_VENDA,
	T.CSTPISENTRADA AS PISE_CODIGO,
	T.CSTPIS AS PIS_CODIGO, 
	T.CSTCOFINSENTRADA AS COFINSE_CODIGO, 
	T.CSTCOFINS AS COFINS_CODIGO, 
	T.PERCPIS AS PIS_ALIQ_NOR, 
	T.PERCPISENTRADA AS PISE_ALIQ_NOR, 
	T.PERCCOFINS AS COFINS_ALIQ_NOR, 
	T.PERCCOFINSENTRADA AS COFINSE_ALIQ_NOR,
	B.CODIGOBARRA AS BARRAS, --QUANTIDADE
	U.FATOR AS FAT_CONV,
	AL.DISPONIVEL1 AS QTD,
--	AL.DISPONIVEL3,
	CAST(AL.DATAULTIMAENTRADA AS DATE) AS ULTIMA_COMPRA,
	CAST(AL.DATAULTIMASAIDA AS DATE) AS ULTIMA_VENDA,
	AL.ULTIMOCUSTO AS PRECO_CUSTO,
	AL.ULTIMOCUSTOMEDIO AS CUSTO_MEDIO
--	AL.PRECOVENDA1, 
--	C.DESCRICAO 
FROM
	CADMATERIAL M
	LEFT JOIN CADTIPOTRIBUTACAO T ON T.CODIGOTIPOTRIBUTACAO = M.CODIGOTIPOTRIBUTACAO 
	LEFT JOIN MATERIALCODIGOSBARRA B ON B.CODIGOMATERIAL = M.CODIGOMATERIAL 
	LEFT JOIN CADUNIDADE U ON U.NOMENCLATURA = M.UNIDADESAIDA 
	LEFT JOIN MATERIALALMOXARIFADO AL ON AL.CODIGOMATERIAL = M.CODIGOMATERIAL AND AL.CODIGOALMOXARIFADO = '0001'
--	LEFT JOIN MATERIALPARCEIRO F ON F.CODIGOMATERIAL = M.CODIGOMATERIAL -- CÓDIGO DO FORNECEDOR
--	LEFT JOIN CADPARCEIRO c ON C.CODIGOPARCEIRO = F.CODIGOPARCEIRO 
