SELECT
    PRODUTO.CODPRODUTO AS CODIGO,
    PRODUTO.PRO_CODPESQ_1 AS BARRAS,
    PRODUTO.PRO_DESCRICAO AS DESCRICAO,
    PRODUTO_GRUPO.prog_descricao AS GRUPO,
    PRODUTO_UNIDADE.prou_sigla AS UMD,
    PRODUTO.PRO_ESTQ_ATUAL AS QTD,
    PRODUTO.PRO_ESTQ_MIN AS QTD_IDEAL,
    PRODUTO.PRO_PRECO01 AS PRECO_VENDA,
    PRODUTO.CODFABRICANTE AS COD_FABRICANTE,
    PRODUTO.PRO_NCM AS COD_NCM,
    SUBSTRING(PRODUTO.PRO_CST FROM 2 FOR 3) AS ST,
    PRODUTO.PRO_DATA_ULT_COMPRA AS ULTIMA_COMPRA,
    PRODUTO.PRO_DATA_ULT_VENDA AS ULTIMA_VENDA,
    PRODUTO.PRO_CEST AS PERSONAL6
  FROM PRODUTO
  LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.codprodutogrupo = PRODUTO.CODPRODUTOGRUPO
  LEFT JOIN PRODUTO_UNIDADE ON PRODUTO_UNIDADE.codprodutounidade = PRODUTO.CODPRODUTOUNIDADE
