SELECT
    PESSOA.CODPESSOA AS CODIGO,
    PESSOA.PES_NOME AS RAZAO0_SOCIAL,
    PESSOA.PES_CPFCNPJ AS CNPJ,
    case when PESSOA.PES_IE = '' or PESSOA.PES_IE is null then PESSOA.PES_RG else PESSOA.PES_IE END AS IE,
    PESSOA.PES_ENDERECO AS ENDERECO,
    PESSOA.PES_CIDADE AS CIDADE,
    PESSOA.PES_UF AS UF,
    PESSOA.PES_TELEFONE_DDD ||' '|| PESSOA. PES_TELEFONE AS TELEFONE,
    PESSOA.PES_EMAIL AS EMAIL
FROM PESSOA
WHERE PESSOA.PES_CLASS_TRA = 'S'
