SELECT
    CODIGO_FORNECEDOR AS CODIGO,
    DESCRICAO AS NOME,
    RAZAO_SOCIAL AS FANTASIA,
    CONTATO AS CONTATO,
    CPF_CNPJ AS CNPJ_CNPF,
    INSCRICAO_ESTADUAL AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    CELULAR AS CELULAR,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES
