SELECT
    P.CODIGO_PRODUTO AS CODIGO,
    P.DESCRICAO AS DESCRICAO,
    P.CODIGO_BARRA AS BARRAS,
    P.UNIDADE_ENTRADA AS UND_COMPRA,
    P.UNIDADE_SAIDA AS UND,
    PS.SALDO_ATUAL AS QTD,
    P.PESO AS PESO,
    G.DESCRICAO AS GRUPO,
    SG.DESCRICAO AS FAMILIA,
    P.CUSTO_ATUAL AS PRECO_CUSTO,
    P.CUSTO_MEDIO AS CUSTO_MEDIO,
    P.PRECO_VENDA AS PRECO_VENDA,
    T.TIPO AS ST,
    P.REFERENCIA AS COD_FABRICFANTE,
    P.NCM AS COD_NCM,
    P.CEST AS PERSONAL6,
    PS.ULTIMA_ENTRADA AS ULTIMA_COMPRA,
    PS.ULTIMA_SAIDA AS ULTIMA_VENDA,
    P.ULTIMO_REAJUSTE AS ALTERACAO_PRECO,
    CAST (P.DATA_CADASTRO AS DATE) AS DATA_CADASTRO
FROM PRODUTOS AS P
LEFT JOIN PRODUTOS_SALDO PS ON P.CODIGO_PRODUTO = PS.CODIGO_PRODUTO
LEFT JOIN GRUPOS_PRODUTO G ON P.CODIGO_GRUPO = G.CODIGO_GRUPO
LEFT JOIN SUBGRUPOS_PRODUTO SG ON P.CODIGO_SUBGRUPO = SG.CODIGO_SUBGRUPO AND SG.CODIGO_GRUPO = G.CODIGO_GRUPO
LEFT JOIN TRIBUTOS T ON P.CODIGO_TRIBUTO = T.CODIGO_TRIBUTO
