SELECT
  IN01FRN.CDFRN AS CODIGO,
  IN01FRN.CGCCC AS CNPJ_CNPF,
  IN01FRN.CGFCC AS IE_RG,
  IN01FRN.NMFRN AS NOME,
  IN01FRN.NMFAN AS FANTASIA,
  IN01FRN.UFFRN AS UF,
  IN01FRN.CIDCC AS CIDADE,
  IN01FRN.BAICC AS BAIRRO,
  IN01FRN.ENDCC AS ENDERECO,
  IN01FRN.CEPCC AS CEP,
  IN01FRN.TELEF AS TELEFONE,
  IN01FRN.FXFRN AS FAX,
  IN01FRN.EMAIL AS EMAIL,
  IN01FRN.NUMCC AS NUMERO
--  IN01FRN.CONTATO AS CONTATO
FROM IN01FRN
