SELECT 
       --CLIENTE.CODIGO
       CLIENTE.NOME
      ,CLIENTE.ENDERECO
      ,CLIENTE.NUMERO
      ,CLIENTE.COMPLEM
      ,CLIENTE.BAIRRO
      ,CLIENTE.CEP
      ,CLIENTE.FONE1
      ,CLIENTE.FONE2
      ,CLIENTE.FAX
      ,CLIENTE.EMAIL
      ,CLIENTE.CPFCGC
      ,CLIENTE.INSCESTRG
      ,CIDADES.NOME
	  ,CIDADES.UF
  FROM EGI.dbo.CLIENTE
left join EGI.dbo.CIDADES ON CLIENTE.MUNICIPIO = CIDADES.CODIGO