SELECT 
    SUBSTRING ([Código Cliente],2,7) AS CODIGO,
    [Nome Cliente] AS NOME,
    [Apelido] AS FANTASIA,
    COALESCE(NULLIF([CNPJ], ''), [CPF]) AS CNPJ_CNPF,
    COALESCE(NULLIF([IE], ''), [RG]) AS IE_RG,
    [IM],
    [Endereço] AS ENDERECO,
    [Número] AS NUMERO,
    [Complemento],
    [Bairro],
    [Cidade],
    [Código Cidade] AS ID_MUNICIPIO,
    [Estado] AS UF,
    [CEP],
    [Telefone] AS TELEFONE,
    [Celular] AS CELULAR,
    [Fax] AS FAX,
    [Email] AS EMAIL,
    [Rendimentos] AS RENDA,
    [Limite Crédito] AS LIMITE_CREDITO,
    [Data Cadastro] AS CADASTRO,
    [Observações] AS OBSERVACOES,
    [Estado Civil] AS EST_CIVIL,
    [Nome Pai] AS PAI,
    [Nome Mãe] AS MAE,
    [Naturalidade],
    [Cargo] AS PROFISSAO,
    [Nome Cônjuge] AS CONJUGE
FROM 
    [WM_ShopEconomiaCentro].[dbo].[Clientes];