SELECT 
    CLIENTE.CLIENTE AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLI_COMP.CONTATO AS CONTATO,
    CLIENTE.CPF AS CNPJ_CNPF,
    case when CLI_COMP.RG = '' or CLI_COMP.RG is null then CLI_COMP.IE else CLI_COMP.RG END AS IE_RG,
    CLIENTE.IM AS IM,
    CLI_ENDE.ENDERECO AS ENDERECO,
    BAIRRO.nome AS BAIRRO,
    CIDADE.nome AS CIDADE,
    CIDADE.uf AS UF,
    CLI_ENDE.CEP AS CEP,
    CLI_ENDE.NRO AS NUMERO,
    CLI_COMP.EMAIL AS EMAIL,
    CLI_ENDE.TELEFONE AS TELEFONE,
    CLI_COMP.NASCIMENTO AS NASCIMENTO,
    CLI_COMP.NATURALI AS NATURALIDADE,
    CLI_COMP.CONJUGE AS CONJUGE,
    CLI_COMP.PAI AS PAI,
    CLI_COMP.MAE AS MAE,
    CLI_COMP.PROFISSAO AS PROFISSAO,
    CLI_COMP.OBS AS OBSERVACOES,
    CAST (CLIENTE.INCALT AS DATE) AS CADASTRO
FROM CLIENTE
LEFT JOIN CLI_COMP ON CLI_COMP.cliente = CLIENTE.CLIENTE
LEFT JOIN CLI_ENDE ON CLI_ENDE.cliente = CLIENTE.CLIENTE
LEFT JOIN BAIRRO ON BAIRRO.bairro = CLI_ENDE.bairro
LEFT JOIN CIDADE ON CIDADE.cidade = CLI_ENDE.CIDADE