SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    SECOES.descricao AS GRUPO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.COD_FABRICANTE AS COD_FABRICANTE,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.PCOMPRA AS PRECO_CUSTO,
    PRODUTOS.DATAULTCOMPRA AS ULTIMA_COMPRA,
    PRODUTOS.PVISTA AS PRECO_VENDA,
    PRODUTOS.DATAULTVENDA AS ULTIMA_VENDA,
    PRODUTOS.CODIGO_BARRAS AS BARRAS,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.PESOLIQ AS PESO,
    PRODUTOS.OBSERVACOES AS OBSERVACOES,
    PRODUTOS.PMEDIO AS CUSTO_MEDIO,
    PRODUTOS.CSOSN AS ST,
    PESSOAS.nome_razaosocial AS FORNECEDOR
FROM PRODUTOS
left join PESSOAS ON PESSOAS.codigo = PRODUTOS.FORNECEDOR
LEFT JOIN secoes ON SECOES.codigo = PRODUTOS.SECAO