SELECT TCLIENTE.CLICOD AS CODIGO,
TCLIENTE.CLINOME AS NOME,
TCLIENTE.CLIENDERECO AS ENDERECO,
TCLIENTE.CLIBAIRRO,
TCIDADE.CIDNOME AS CIDADE,
TCIDADE.CIDUF AS UF,
TCLIENTE.CLICEP AS CEP,
TCLIENTE.CLIFONE AS TELEFONE,
TCLIENTE.CLIFAX AS FAX,
TCLIENTE.CLIMAIL AS EMAIL,
COALESCE(TCLIENTE.CLICPF,TCLIENTE.CLICNPJ) AS CNPJ_CNPF,
COALESCE(TCLIENTE.CLIRG,TCLIENTE.CLIINSCRICAO) AS IE_RG,
TCLIENTE.CLIOBS AS OBSERVACOES,
TCLIENTE.CLIRAZAO AS FANTASIA,
TCLIENTE.CLICELULAR AS CELULAR,
TCLIENTE.CLINUMERO AS NUMERO
FROM TCLIENTE
LEFT JOIN TCIDADE ON TCLIENTE.CLICIDADE=TCIDADE.CIDCOD

