SELECT 
  CODIGO
, FORNECEDOR AS NOME
, FANTASIA
, ENDERECO
, COMPL AS COMPLEMENTO
, NUMERO
, BAIRRO
, CIDADE
, UF
, CEP
, CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
, IE AS IE_RG
, TELEFONE
, FAX
, REPRESENTANTE AS CONTATO
FROM FORNECEDORES