SELECT 
  P.CODIGO
, P.CODBARRAS
, P."DESCRICAO" AS DESCRICAO
, P.UNIDADE AS UND
, P.SALDO AS QTD
--, P.SALDO_LOJA AS QTD
, P.ESTMIN AS QTD_IDEAL
, P.PRECOCUSTO AS PRECO_CUSTO
, P.PRECOVENDA AS PRECO_VENDA
, P.PRECODOLAR AS PRECO_DOLAR
, P.MARGEM AS MARGEM_LUCRO
, P.PRECOATACADO AS PRECO_ATACADO
, P.QTD_ATACADO AS QTD_PRECO_ATACADO
, P.NCM AS COD_NCM
, P.QTDCAIXA AS FAT_CONV
, P.PESOCAIXA AS PESO
, P.IPI AS ALIQ_IPI_VENDA
, P.IPI_SIT AS IPI_CODIGO_VENDA
, LEFT (P.CFOP_SAIDA_DENTRO,3) AS ELO
--, P.CST AS ST
, P.CSOSN AS ST
, P.COD_PIS AS PIS_CODIGO
, P.ALIQ_PIS AS PIS_ALIQ_NOR
, P.COD_COFINS AS COFINS_CODIGO
, P.ALIQ_COFINS AS COFINS_ALIQ_NOR
, P.ORIGEM AS OST
, P.PRATELEIRA AS PERSONAL1
, CASE P.STATUS WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.MODELO AS PERSONAL2
, P.DATA_ULT_COMPRA AS ULTIMA_COMPRA
, P.MARCA AS CARACTERISTICAS
, P."OBS" AS OBSERVACOES
, P.DIAS_VALIDADE AS VALIDADE_DIAS
, G.NOMEGRUPO AS GRUPO
, F.FAMILIA
, F2.FORNECEDOR
FROM PRODUTOS P
LEFT JOIN TBGRUPOS G ON G.CODGRUPO = P.CODGRUPO
LEFT JOIN FAMILIA F ON F.CODFAMLIA = P.CODFAMILIA
LEFT JOIN FORNECEDORES F2 ON F2.CODIGO = P.COD_FORN_ULTIMA