SELECT CLIENTE.CODIGO,
CLIENTE.CLIENTE AS NOME,
CLIENTE.ENDERECO,
CASE WHEN CLIENTE.CNPJ='' THEN CLIENTE.CPF
ELSE CLIENTE.CNPJ END AS CNPJ_CNPF,
CASE WHEN CLIENTE.IDENTIDADE='' THEN CLIENTE.INSCR_ESTADUAL
ELSE CLIENTE.IDENTIDADE END AS IE_RG,
CLIENTE.NASCIMENTO,
CLIENTE.PAI,
CLIENTE.MAE,
CLIENTE.CEP,
CLIENTE.NUMERO,
CLIENTE.COMPLEMENTO,
CLIENTE.NOME_BAIRRO AS BAIRRO,
CLIENTE.NOME_FANTASIA AS FANTASIA,
CLIENTE.DATA_CRIACAO AS CADASTRO,
CIDADE.CIDADE,
ESTADO.UF
FROM CLIENTE
LEFT JOIN CIDADE ON CLIENTE.CODIGO_IBGE=CIDADE.CODIGO_IBGE
LEFT JOIN ESTADO ON CIDADE.CODIGO_ESTADO=ESTADO.CODIGO
WHERE CLIENTE.CODIGO<>'00000'



