SELECT FORNECEDORES.CODIGO,
FORNECEDORES.CEP,
FORNECEDORES.FORNECEDOR AS NOME,
FORNECEDORES.ENDERECO,
FORNECEDORES.NUMERO,
FORNECEDORES.COMPLEMENTO,
FORNECEDORES.CNPJ AS CNPJ_CNPF,
FORNECEDORES.INSCR_ESTADUAL AS IE_RG,
FORNECEDORES.NOME_BAIRRO AS BAIRRO,
CIDADE.CIDADE,
ESTADO.UF
FROM FORNECEDORES
LEFT JOIN CIDADE ON FORNECEDORES.CODIGO_IBGE=CIDADE.CODIGO_IBGE
LEFT JOIN ESTADO ON CIDADE.CODIGO_ESTADO=ESTADO.CODIGO



