SELECT 
  CLI_001 AS CODIGO
, CLI_002 AS NOME
, CLI_003 AS FANTASIA
, CLI_007 AS COMPLEMENTO
, CLI_008 AS NUMERO
, CEP_004 AS ENDERECO
, CEP_003 AS BAIRRO
, CLI_009 AS PERSONAL1
, CLI_012 AS TELEFONE
, CIDADE_DESC AS CIDADE
, UF
, CEP_002 AS CEP
, DAT_001_1 ::DATE AS CADASTRO
, OBSERVACAO AS OBSERVACOES
, CELULAR1 AS CELULAR
, CELULAR2 AS FAX
, LIMITE_CREDITO
, FILIACAO_MAE AS MAE
, FILIACAO_PAI AS PAI
, NOME_CONJUGE AS CONJUGE
, PROFISSAO 
, ESTADO_CIVIL AS EST_CIVIL
, SEXO 
, DATA_NASCIMENTO AS NASCIMENTO
, EMAIL
, FILIACAO_MAE AS MAE
, FILIACAO_PAI AS PAI
, NOME_CONJUGE AS CONJUGE
FROM CLIENTES