SELECT 
  F.ID_FORNECEDOR AS CODIGO
, F.NOME_FANTASIA AS FANTASIA
, F.ENDERECO_LOGRADOURO AS ENDERECO
, F.ENDERECO_NUMERO AS NUMERO
, F.ENDERECO_BAIRRO AS BAIRRO
, F.ENDERECO_CIDADE AS CIDADE
, F.ENDERECO_UF AS UF
, F.ENDERECO_CEP AS CEP
, F.ENDERECO_COMPLEMENTO AS COMPLEMENTO
, F.TELEFONE1 AS TELEFONE
, F.TELEFONE2 AS FAX
, F.CELULAR1 AS CELULAR
, F.EMAIL
, F.CNPJ AS CNPJ_CNPF
, F.NOME_CONTATO1 AS CONTATO
, F.INSCRICAO_ESTADUAL AS IE_RG
, F.INSCRICAO_MUNICIPAL AS IM
, F.OBSERVACOES
, C.CID_002 AS CIDADE  
FROM FORNECEDOR F
LEFT JOIN CIDADES C ON C.CID_001 = F.ID_CIDADE
