SELECT 
  M.MAT_001 AS CODIGO
, M.MAT_003 AS DESCRICAO
, M.DAT_001_1 ::DATE AS DATA_CADASTRO
, M.MAT_012 AS PRECO_CUSTO
, M.MAT_018 AS MARGEM_LUCRO
, M.MAT_008 AS PRECO_VENDA
, M.IPI AS ALIQ_IPI_VENDA
, M.PIS AS PIS_ALIQ_NOR
, M.COFINS AS COFINS_ALIQ_NOR
, M.PIS_CODIGO_ENTRADA AS PISE_CODIGO
, M.PIS_CODIGO_SAIDA AS PIS_CODIGO
-- , M.PIS_CODIGO AS PIS_CODIGO
-- , M.ICMS
-- , M.CST_CONSUMIDOR
-- , M.CST_REVENDEDOR
, M.COF_CODIGO_ENTRADA AS COFINSE_CODIGO
, M.COF_CODIGO_SAIDA AS COFINS_CODIGO
, M.NCM AS COD_NCM
, M.CSO_CODIGO AS ST
, M.TIPO_PRODUCAO AS IPPT
, M.CEST AS PERSONAL6
, M.VALOR_ATACADO AS PRECO_ATACADO
, F.RAZAO_SOCIAL AS FORNECEDOR
, U.UNI_003 AS UND
, C.CAT_002 AS GRUPO
, SEM.QUANTIDADE AS QTD
FROM MATERIAIS M
LEFT JOIN FORNECEDOR F ON F.ID_FORNECEDOR = M.ID_FORNECEDOR  
LEFT JOIN UNIDADES U ON U.UNI_001 = M.UNI_001 
LEFT JOIN CATEGORIA C ON C.CAT_001 = M.CAT_001 
LEFT JOIN SETOR_ESTOQUE_MATERIAL SEM ON SEM.ID_MATERIAL = M.MAT_001 
