SELECT
       RAZAO AS NOME
      ,FANTA AS FANTASIA
      ,RESPO AS CONTATO
      ,CGC AS CNPJ_CNPF
      ,INSCR AS IE_RG
      ,ENDER AS ENDERECO
      ,NUMER AS NUMERO
      ,COMPL AS COMPLEMENTO
      ,BAIRR AS BAIRRO
      ,MUNIC AS CIDADE
      ,UF AS UF
      ,CEP AS CEP
      ,EMAIL AS EMAIL
      ,REPLACE (CONCAT (DDD, FONE1),' ','') AS TELEFONE
      ,REPLACE (CONCAT (DDD, FONE2),' ','') AS CELULAR
      ,OBSER AS OBSERVACOES
  FROM EasyLinx.dbo.CADFOR