SELECT 
       CLIENTES.cdCliente AS CODIGO
      ,CLIENTES.nmRazaoSocial AS NOME
      ,CLIENTES.ieCliente AS IE_RG
      ,CLIENTES.cgcCliente AS CNPJ_CNPF
      ,LOGRADOUROS.NMLOGRADOURO AS ENDERECO
      ,LOGRADOUROS.CEPLOGRADOURO AS CEP
      ,CLIENTES.numLogradouro AS NUMERO
      ,CLIENTES.compLogradouro AS COMPLEMENTO
      ,BAIRROS.NMBAIRRO AS BAIRRO
      ,CIDADES.NMCIDADE AS CIDADE
      ,UF.NMUF AS UF
      ,CLIENTES.fone1Cliente AS TELEFONE
      ,CLIENTES.fone2Cliente AS CELULAR
      ,CLIENTES.emailCliente AS EMAIL
  FROM BOMPRECO3.dbo.Clientes
left join BOMPRECO3.dbo.BAIRROS ON CLIENTES.CDBAIRRO = BAIRROS.CDBAIRRO
LEFT JOIN BOMPRECO3.dbo.CIDADES ON CLIENTES.CDCIDADE = CIDADES.CDCIDADE
LEFT JOIN BOMPRECO3.dbo.LOGRADOUROS ON CLIENTES.CDLOGRADOURO = LOGRADOUROS.CDLOGRADOURO
LEFT JOIN BOMPRECO3.dbo.UF ON CLIENTES.CDUF = UF.CDUF