SELECT 
       PRODUTOS.cdProduto AS CODIGO
      ,UNIDADESMEDIDA.SIGLAUNIDADEMEDIDA AS UND
      ,PRODUTOS.nmProduto AS DESCRICAO
      ,PRODUTOS.cbProduto AS BARRAS
      ,PRODUTOS.vlCompra AS PRECO_CUSTO
      ,PRODUTOS.vlpLucro AS MARGEM_LUCRO
      ,PRODUTOS.vlVenda AS PRECO_VENDA
      ,PRODUTOS.vlAtacado AS PRECO_ATACADO
      ,PRODUTOS.qtEstoque AS QTD
  FROM BOMPRECO3.dbo.Produtos
left join BOMPRECO3.dbo.UNIDADESMEDIDA ON PRODUTOS.CDUNIDADEMEDIDA = UNIDADESMEDIDA.CDUNIDADEMEDIDA