SELECT
    CLI_CODIGO AS CODIGO,
    NOME AS NOME,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    FONE AS TELEFONE,
    CONTATO AS CONTATO,
    CGC AS CNPJ_CNPF,
    INSC AS IE_RG,
    ENDERECO AS ENDERECO,
    FANTASIA AS FANTASIA,
    EMAIL AS EMAIL,
    NUMERO_ENDERECO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO
FROM CLIENTES
