SELECT
    CLIENTES.COD_CLI AS CODIGO,
    CLIENTES.NOME_CLI AS NOME,
    CLIENTES.CONTATO,
    CLIENTES.ENDERECO,
    CLIENTES.NUMERO,
    CLIENTES.COMPLEMENTO,
    CLIENTES.BAIRRO,
    CLIENTES.CEP,
    CIDADES.NOME_CID AS CIDADE,
    CIDADES.UF_CID AS UF,
    CLIENTES.FONE_RES AS TELEFONE,
    CLIENTES.FAX,
    CLIENTES.CELULAR,
    CLIENTES.CPF AS CNPJ_CNPF,
    CLIENTES.RG AS IE_RG,
    CLIENTES.EMAIL,
    CLIENTES.NOME_FANTASIA AS FANTASIA
FROM CLIENTES
LEFT JOIN CIDADES ON CLIENTES.COD_CID = CIDADES.COD_CID
