SELECT PESSOA.COD_PESSOA AS CODIGO,
PESSOA.DATA_CAD AS CADASTRO,
PESSOA.IDENTIDADE AS IE_RG,
PESSOA.CPF AS CNPJ_CNPF,
PESSOA.TIPO_RUA||' '||PESSOA.RUA AS ENDERECO,
PESSOA.NUMERO_RUA AS NUMERO,
PESSOA.COMPLEMENTO,
PESSOA.BAIRRO,
PESSOA.CIDADE,
PESSOA.UF,
PESSOA.CEP,
PESSOA.TELEFONE1 AS TELEFONE,
PESSOA.TELEFONE2 AS CELULAR,
PESSOA.CONTATO,
PESSOA.EMAIL,
PESSOA.NOME,
PESSOA.RAZAO_SOCIAL AS FANTASIA
FROM PESSOA
WHERE PESSOA.COD_PESSOA_TIPO=4
