SELECT 
PESSOA.ID AS CODIGO,
PESSOA.NOME,
CASE WHEN PESSOA.CPF IS NULL OR PESSOA.CPF='' THEN PESSOA.CNPJ ELSE PESSOA.CPF END AS CNPJ_CNPF,
CASE WHEN PESSOA.INSCRICAOESTADUAL IS NULL OR PESSOA.INSCRICAOESTADUAL='' THEN PESSOA.RG ELSE PESSOA.INSCRICAOESTADUAL END AS IE_RG,
PESSOA.NASCIDOEM AS NASCIMENTO,
PESSOA.NOMEFANTASIA AS FANTASIA,
PESSOA_EMAIL.EMAIL,
PESSOA_ENDERECO.LOGRADOURO AS ENDERECO,
PESSOA_ENDERECO.NUMERO,
PESSOA_ENDERECO.BAIRRO,
PESSOA_ENDERECO.CEP,
PESSOA_ENDERECO.COMPLEMENTO,
CIDADE.NOME AS CIDADE,
CIDADE.SIGLAUF AS UF
FROM FUSIONADM.DBO.PESSOA
LEFT JOIN FUSIONADM.DBO.PESSOA_EMAIL ON PESSOA.ID=PESSOA_EMAIL.PESSOA_ID
LEFT JOIN FUSIONADM.DBO.PESSOA_ENDERECO ON PESSOA.ID=PESSOA_ENDERECO.PESSOA_ID
LEFT JOIN FUSIONADM.DBO.CIDADE ON PESSOA_ENDERECO.CIDADE_ID=CIDADE.ID
WHERE PESSOA.ID IN (SELECT FUSIONADM.DBO.PESSOA_CLIENTE.PESSOA_ID FROM FUSIONADM.DBO.PESSOA_CLIENTE)
--AND PESSOA.TIPO = 'F'



