SELECT 
PRODUTO.ID AS CODIGO,
CASE PRODUTO.ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
PRODUTO.NOME AS DESCRICAO,
--PRODUTO.CODIGOBALANCA AS BARRAS,
PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
PRODUTO.MARGEMLUCRO AS MARGEM_LUCRO,
PRODUTO.PRECOVENDA AS PRECO_VENDA,
PRODUTO.TABELANCM_ID AS COD_NCM,
PRODUTO.CODIGOCEST AS PERSONAL6,
PRODUTO.ORIGEMMERCADORIA AS OST,
-- PRODUTO.ALIQUOTAICMS,
PRODUTO.SITUACAOTRIBUTARIAPIS_ID AS PIS_CODIGO,
PRODUTO.ALIQUOTAPIS AS PIS_ALIQ_NOR,
PRODUTO.SITUACAOTRIBUTARIACOFINS_ID AS COFINS_CODIGO,
PRODUTO.ALIQUOTACOFINS AS COFINS_ALIQ_NOR,
PRODUTO.SITUACAOTRIBUTARIAIPI_ID AS IPI_CODIGO_VENDA,
PRODUTO.ALIQUOTAIPI AS ALIQ_IPI_VENDA,
PRODUTO.REFERENCIA AS CARACTERISTICAS,
PRODUTO.OBSERVACAO AS OBSERVACOES,
CONVERT (DATE, PRODUTO.CADASTRADOEM) AS DATA_CADASTRO,
PRODUTO_ESTOQUE.ESTOQUE AS QTD,
PRODUTO_ALIAS.ALIAS AS  BARRAS,
PRODUTO_UNIDADE.SIGLA AS UND,
PRODUTO_GRUPO.NOME AS GRUPO,
--REGRA_TRIBUTACAO_SAIDA.SITUACAOTRIBUTARIAICMS_ID AS ST,
REGRA_TRIBUTACAO_SAIDA.SITUACAOTRIBUTARIACSOSN_ID AS ST,
SUBSTRING(REGRA_TRIBUTACAO_SAIDA.NFCECFOP_ID,1,3) AS ELO
FROM FUSIONADM.DBO.PRODUTO
LEFT JOIN FUSIONADM.DBO.PRODUTO_GRUPO ON PRODUTO.PRODUTOGRUPO_ID=PRODUTO_GRUPO.ID
LEFT JOIN FUSIONADM.DBO.PRODUTO_UNIDADE ON PRODUTO.PRODUTOUNIDADE_ID=PRODUTO_UNIDADE.ID
LEFT JOIN FUSIONADM.DBO.REGRA_TRIBUTACAO_SAIDA ON PRODUTO.REGRATRIBUTACAOSAIDA_ID=REGRA_TRIBUTACAO_SAIDA.ID
LEFT JOIN FUSIONADM.DBO.PRODUTO_ESTOQUE ON PRODUTO.ID=PRODUTO_ESTOQUE.PRODUTO_ID
LEFT JOIN [FUSIONADM].[DBO].[PRODUTO_ALIAS] ON PRODUTO.ID = [PRODUTO_ALIAS].PRODUTO_ID
ORDER BY PRODUTO.ID ASC
