SELECT 
  P.ID_PESSOA AS CODIGO
, P.CNPJ_CPF AS CNPJ_CNPF
, P.NOME_RAZAO AS NOME
, P.NOMEFANTASIA AS FANTASIA
, P.CONTATO
, P.IE_RG
, P.IM
, P.INFORMACAO AS OBSERVACOES
, CONCAT (PT.DDD,PT.NUMEROTELEFONE) AS TELEFONE
, CONCAT (PT1.DDD,PT1.NUMEROTELEFONE) AS CELULAR
, PE.LOGRADOURO AS ENDERECO
, PE.NUMEROENDERECO AS NUMERO
, PE.COMPLEMENTO
, PE.BAIRRO 
, PE.CEP 
, PE2.EMAIL 
, M.DESCRICAO AS CIDADE
, U.SIGLA AS UF
FROM PESSOA P
INNER JOIN PESSOAFORNECEDOR PF ON PF.ID = P.ID_PESSOA AND P.TIPOPESSOA = 3 
LEFT JOIN PESSOATELEFONE PT ON PT.ID_PESSOA = P.ID_PESSOA AND PT.TIPOPESSOA = 3 AND PT.TIPOTELEFONE =16 AND PT.PRINCIPALTELEFONE =1
LEFT JOIN PESSOATELEFONE PT1 ON PT1.ID_PESSOA = P.ID_PESSOA AND PT1.TIPOPESSOA = 3 AND PT1.TIPOTELEFONE =17 AND PT1.PRINCIPALTELEFONE =1
LEFT JOIN PESSOAENDERECO PE ON PE.ID_PESSOA = P.ID_PESSOA  AND PE.TIPOPESSOA = 3 AND PE.PRINCIPALENDERECO =1
LEFT JOIN PESSOAEMAIL PE2 ON PE2.ID_PESSOA = P.ID_PESSOA AND PE2.TIPOPESSOA = 3 AND PE2.PRINCIPALEMAIL =1 
LEFT JOIN MUNICIPIOS M ON M.ID = PE.ID_MUNICIPIO 
LEFT JOIN UF U ON U.ID_UF = M.ID_UF
