SELECT
    ARECEBER.AREORI AS DOCUMENTO,
    ARECEBER.ARENUM AS historico,
    ARECEBER.ARECLI AS CODCLI,
    ARECEBER.ARECL1 AS NOM_CLIENTE,
    ARECEBER.ARECAD AS EMISSAO,
    ARECEBER.AREVEN AS VENCIMENTO,
    ARECEBER.AREVLR AS VALOR_DUP,
    ARECEBER.AREREC AS RECEBIMENTO,
    ARECEBER.AREJUR AS VALOR_JUR, 
    ARECEBER.AREDES AS VALOR_DES,
    ARECEBER.ARETOT AS VALORTOTAL,
    CLIENTES.CLICPF AS CNPJ
FROM ARECEBER

LEFT JOIN CLIENTES ON ARECEBER.ARECLI = CLIENTES.CLICOD
WHERE ARECEBER.AREORI IS NOT NULL
