select  
        TCLIENTE.CONTROLE AS CODIGO
,       TCLIENTE.CLIENTE AS NOME
,       TCLIENTE.FANTASIA
,       TCLIENTE.ENDERECO AS ENDERECO
,       TCLIENTE.NUMERO
,       TCLIENTE.COMPLEMENTO
,       TCLIENTE.BAIRRO
,       TCLIENTE.CIDADE
,       TCLIENTE.UF
,       TCLIENTE.CEP
,       TCLIENTE.NATURALIDADE
,   CASE WHEN CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
,   CASE WHEN IE IS NULL THEN RG ELSE IE END AS IE_RG
,      CAST(TCLIENTE.DATAHORACADASTRO AS DATE) AS CADASTRO
,      TCLIENTE.DATANASCIMENTO AS NASCIMENTO
,      TCLIENTE.PAI
,      TCLIENTE.MAE
,      TCLIENTE.TELEFONE
,      TCLIENTE.CELULAR
,      TCLIENTE.EMAIL
,      TCLIENTE.OBS AS OBSERVACOES
,      TCLIENTE.NOMECONTATOJURIDICA AS CONTATO
from TCLIENTE
WHERE TCLIENTE.ATIVO='SIM'
