SELECT 
       TFORNECEDOR.CONTROLE AS CODIGO
,      TFORNECEDOR.RAZAOSOCIAL AS NOME
,      TFORNECEDOR.NOMECONTATOJURIDICA AS CONTATO
,      TFORNECEDOR.NOMEFANTASIA AS FANTASIA
,      TFORNECEDOR.ENDERECO
,      TFORNECEDOR.NUMERO
,      TFORNECEDOR.BAIRRO
,      TFORNECEDOR.CIDADE
,      TFORNECEDOR.UF
,      TFORNECEDOR.CEP
,      CASE WHEN CNPJ IS NULL THEN CPF ELSE CNPJ END AS CNPJ_CNPF
,      CASE WHEN IE IS NULL THEN RG ELSE IE END AS IE_RG
,      TFORNECEDOR.COMPLEMENTO
,      TFORNECEDOR.TELEFONE
,      TFORNECEDOR.CELULAR
,      TFORNECEDOR.EMAIL
,      TFORNECEDOR.OBS AS OBSERVACOES
FROM TFORNECEDOR
WHERE TFORNECEDOR.ATIVO='SIM'
