SELECT
    CLIENTE.CD_CLIENTE AS CODIGO,
    CLIENTE.NM_CLIENTE AS NOME,
    CLIENTE.NM_FANTASIA AS FANTASIA,
    CLIENTE.ED_CLIENTE AS ENDERECO,
    CLIENTE.BA_CLIENTE AS BAIRRO,
    CIDADE.nm_cidade AS CIDADE,
    CIDADE.uf_estado AS uf, 
    CLIENTE.NR_CEP AS CEP,
    CLIENTE.NR_CNPJ AS CNPJ_CNPF,
    CLIENTE.NR_IE AS IE_RG,
    CLIENTE.NR_IM  AS IM,
    CLIENTFONE.nr_telefone AS TELEFONE,
    CLIENTE.ED_EMAIL AS EMAIL,
    CLIENTE.DT_CADASTRO AS CADASTRO,
    CLIENTE.NR_ENDERECO AS NUMERO,
    CLIENTE.NM_CONTATO AS CONTATO
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.cd_cidade = CLIENTE.CD_CIDADE
LEFT JOIN CLIENTFONE ON CLIENTFONE.cd_cliente = CLIENTE.CD_CLIENTE