SELECT
  FORNECED.CODIGO AS CODIGO,
  FORNECED.RAZAO AS NOME,
  FORNECED.FANTASIA AS FANTASIA,
  case when FORNECED.CGC = '' or FORNECED.CGC is null then FORNECED.CPF else FORNECED.CGC END as CNPJ_CNPF,
  FORNECED.UF AS UF,
  FORNECED.BAIRRO AS BAIRRO,
  FORNECED.TIPOEND ||' '|| FORNECED.ENDERECO AS ENDERECO,
  FORNECED.NUMEND AS NUMERO,
  FORNECED.CEP AS CEP,
  FORNECED.DDDFONE ||' '|| FORNECED.FONE AS TELEFONE,
  FORNECED.DDDFAX ||' '|| FORNECED.FAX AS FAX,
  FORNECED.INSCEST AS IE_RG,
  FORNECED.CONTATO AS CONTATO,
  FORNECED.OBS AS OBSERVACOES,
  CIDADE.DESCRICAO AS CIDADE,
  FORNECED.EMAIL AS EMAIL
FROM FORNECED
LEFT JOIN CIDADE ON CIDADE.CODIGO = FORNECED.CIDADE
