SELECT
  PRODUTO.CODIGO AS CODIGO,
  PRODUTO.COD_FAB AS COD_FABRICANTE,
  PRODUTO.COD_BARRA AS BARRAS,
  PRODUTO.DESC_ENTR AS DESCRICAO,
  PRODUTO.TIPO_LOCALIZ AS CARACTERISTICAS,
  PRODUTO.QTDE AS QTD,
  GRUPO.DESCRICAO AS GRUPO,
  SUBGRUPO.DESCRICAO AS FAMILIA,
  PRODUTO.VALOR_COMPRA AS PRECO_CUSTO,
  PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO,
  PRODUTO.VALOR_VENDA AS PRECO_VENDA,
  PRODUTO.COMISSAO AS COMISSAO,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.VAL_ATACADO AS PRECO_ATACADO,
  PRODUTO.DTA_ULTCOMPRA AS ULTIMA_COMPRA,
  PRODUTO.OBS ||' -- '|| PRODUTO.APLICACAO AS OBSERVACOES,
  PRODUTO.PESO_LIQUIDO AS PESO,
  PRODUTO.CSOSN AS ST
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CODIGO = PRODUTO.SUBGRUPO
