SELECT
  TB_CLIENTE.FD_ID AS CODIGO,
  TB_CLIENTE.FD_DATACAD AS CADASTRO,
  TB_CLIENTE.FD_NOME AS NOME,
  TB_CLIENTE.FD_FANTASIA AS FANTASIA,
  TB_CLIENTE.FD_CNPJCPF AS CNPJ_CNPF,
  TB_CLIENTE.FD_IERG AS IE_RG,
  TB_CLIENTE.FD_ENDERE AS ENDERECO,
  TB_CLIENTE.FD_COMPLEMENTO AS COMPLEMENTO,
  TB_CLIENTE.FD_NUMERO AS NUMERO,
  TB_CLIENTE.FD_BAIRRO AS BAIRRO,
  TB_CLIENTE.FD_CEP AS CEP,
  TB_ESTADOS_IBGE.SIGLA AS UF,
  TB_MUNICIPIOS_IBGE.NOME AS CIDADE,
  TB_CLIENTE.FD_CELULAR AS CELULAR,
  TB_CLIENTE.FD_FONE AS TELEFONE,
  TB_CLIENTE.FD_FAX AS FAX,
  TB_CLIENTE.FD_CONTATO AS CONTATO,
  TB_CLIENTE.FD_EMAIL AS EMAIL,
  TB_CLIENTE.FD_DATANASC AS NASCIMENTO,
  TB_CLIENTE.FD_LIMITE_CRED AS LIMITE_CREDITO,
  TB_CLIENTE.FD_NOME_PAI AS PAI,
  TB_CLIENTE.FD_NOME_MAE AS MAE,
  TB_CLIENTE.FD_OBS AS OBSERVACOES
FROM TB_CLIENTE
LEFT JOIN TB_MUNICIPIOS_IBGE ON TB_MUNICIPIOS_IBGE.CODIGO = TB_CLIENTE.FD_MUNICI_ID
LEFT JOIN TB_ESTADOS_IBGE ON TB_ESTADOS_IBGE.CODIGO = TB_CLIENTE.FD_ESTADO_ID
