SELECT
  TB_FORNECE.FD_ID AS CODIGO,
  TB_FORNECE.FD_NOME AS NOME,
  TB_FORNECE.FD_FANTASIA AS FANTASIA,
  TB_FORNECE.FD_CNPJ AS CNPJ_CNP,
  TB_FORNECE.FD_IE AS IE_RG,
  TB_FORNECE.FD_ENDERE AS ENDERECO,
  TB_FORNECE.FD_NUMERO AS NUMERO,
  TB_FORNECE.FD_BAIRRO AS BAIRRO,
  TB_FORNECE.FD_CEP AS CEP,
  TB_ESTADOS_IBGE.SIGLA AS UF,
  TB_MUNICIPIOS_IBGE.NOME AS CIDADE,
  TB_FORNECE.FD_FONE AS TELEFONE,
  TB_FORNECE.FD_FAX AS FAX,
  TB_FORNECE.FD_EMAIL1 AS EMAIL,
  TB_FORNECE.FD_CONTATO AS CONTATO,
  TB_FORNECE.FD_OBS AS OBSERVACOES
FROM TB_FORNECE
LEFT JOIN TB_MUNICIPIOS_IBGE ON TB_MUNICIPIOS_IBGE.CODIGO = TB_FORNECE.FD_MUNICI_ID
LEFT JOIN TB_ESTADOS_IBGE ON TB_ESTADOS_IBGE.CODIGO = TB_FORNECE.FD_ESTADO_ID
