SELECT
  TB_PRODUTO.FD_ID AS CODIGO,
  TB_PRODUTO.FD_CODIGO_BR AS BARRAS,
  TB_PRODUTO.FD_REFEREN AS COD_FABRICANTE,
  TB_PRODUTO.FD_DESCRI AS DESCRICAO,
  TB_PRODUTO.FD_UNIDADE AS UND,
  TB_CLASSES.FD_NOME AS GRUPO,
  TB_SUBCLASSES.FD_NOME AS FAMILIA,
  TB_FORNECE.FD_NOME AS FORNECEDOR,
  TB_PRODUTO.FD_PRECO_COMPRA AS PRECO_CUSTO,
  TB_PRODUTO.FD_CUSTO_MED_COMERC AS CUSTO_MEDIO,
  TB_PRODUTO.FD_PRECO_VAREJO AS PRECO_VENDA,
  TB_PRODUTO.FD_PRECO_ATACADO AS PRECO_ATACADO,
  TB_PRODUTO.FD_MARGEM_LUCRO_VAREJO AS MARGEM_LUCRO,
  TB_PRODUTO.FD_ESTOQUE_MINIMO AS QTD_IDEAL,
  TB_PRODUTO.FD_ESTOQUE_LOJA AS QTD,
  TB_PRODUTO.FD_OBS AS OBSERVACOES,
  TB_PRODUTO.FD_NCM_SH AS COD_NCM,
  TB_PRODUTO.FD_MARCA_NOME AS CARACTERISTICAS,
  TB_PRODUTO.FD_DATA_ESTOQUE AS DATA_CADASTRO,
  TB_PRODUTO.FD_CEST AS PERSONAL6,
  TB_PRODUTO.FD_CSON AS ST
FROM TB_PRODUTO
LEFT JOIN TB_FORNECE ON TB_FORNECE.FD_ID = TB_PRODUTO.FD_FORNECE_ID
LEFT JOIN TB_CLASSES ON TB_CLASSES.FD_ID = TB_PRODUTO.FD_CLASSE_ID
LEFT JOIN TB_SUBCLASSES ON TB_SUBCLASSES.FD_ID = TB_PRODUTO.FD_SUBCLASSE_ID
