SELECT
  PRODUTO AS CODIGO,
  DESCRICAO AS DESCRICAO,
  CUSTO AS PRECO_CUSTO,
  PRECOVENDA AS PRECO_VENDA,
  REFERENCIA AS COD_FABRICANTE,
  CBARRA AS BARRAS,
  UNIDADE AS UND,
  CF AS COD_NCM,
  ST AS ST,
  QTD AS QTD,
  CSTPIS AS PIS_CODIGO,
  CSTCOFINS AS COFINS_CODIGO,
  CEST AS PERSONAL6
FROM PRODUTOS