
SELECT
       ESTOQUE.CODIGO AS CODIGO
      ,ESTOQUE.NOME AS DESCRICAO
      ,SUBGRUPO.NOME AS GRUPO
      ,ESTOQUE.UN AS UND
      ,ESTOQUE.QUANTM AS QTD
      ,ESTOQUE.CUSTO AS PRECO_CUSTO
      ,ESTOQUE.LUCRO AS MARGEM_LUCRO
      ,ESTOQUE.VENDA AS PRECO_VENDA
      ,ESTOQUE.CODNCM AS COD_NCM
      ,ESTOQUE.CODAUX1 AS COD_FABRICANTE
      ,ESTOQUE.CODCEST AS PERSONAL6
  FROM EGI.dbo.ESTOQUE
left join EGI.dbo.SUBGRUPO on estoque.subgrupo = subgrupo.codigo