SELECT 
MERCADORIAS.CODIGO AS CODIGO, 
MERCADORIAS.DESCRICAO AS DESCRICAO,
MAX (MERCADORIAS.CODIGOGERAL) AS BARRAS,
CASE MERCADORIAS.INATIVO WHEN TRUE THEN 'Inativo' ELSE 'Ativo' END AS SITUACAO ,
MERCADORIAS.PRECOCUSTOUNITARIO AS PRECO_CUSTO,
MERCADORIAS.QTDITENSEMBALAGEM AS QTD_IDEAL,
LEFT ((MERCADORIAS.ALIQUOTAICMS::TEXT) ,3) AS ELO,
MERCADORIAS.CSTICMS AS ST,
MERCADORIAS.CSTPISCOFINS AS PIS_CODIGO,
MERCADORIAS.CSTPISCOFINS AS COFINS_CODIGO,
MERCADORIAS.CBENEF AS CBENEF,
MERCADORIAS.OBSERVACOES AS OBSERVACOES,
MERCADORIAS.ORIGEM AS OST,
MERCADORIAS.CEST AS PERSONAL6,
MERCADORIAS.DEOLHONOIMPOSTO AS COD_NCM,
MERCADORIAS.SALDOORCADO AS QTD,
TABELASPRECOMERCADORIA.PRECOVENDAUNITARIO AS PRECO_VENDA,
UNIDADES.DESCRICAO AS UND
FROM MERCADORIAS
LEFT JOIN UNIDADES ON UNIDADES.CODIGO = MERCADORIAS.UNIDADEINDIVIDUAL
LEFT JOIN TABELASPRECOMERCADORIA ON TABELASPRECOMERCADORIA.MERCADORIA = MERCADORIAS.CODIGO
GROUP BY 1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18