SELECT
	ID_EMPRESA AS CODIGO,
	"NOME",
	NOME_FANTASIA AS FANTASIA,
	CNPJ_CPF AS CNPJ_CNPF,
	IE_RG,
	IM,
	ENDERECO,
	ENDERECO_COMPLEMENTO AS COMPLEMENTO,
	ENDERECO_NUMERO AS NUMERO,
	"BAIRRO",
	CEP,
	"TELEFONE",
	TELEFONE2 AS FAX,
	CELULAR,
	CONTATO,	
	"EMAIL",
	CIDADE,
	ESTADO AS UF,
	"OBSERVACAO" AS OBSERVACOES
FROM
	EMPRESAS
WHERE FORNECEDOR = 'S'
