SELECT
    I.ID_ITEM AS CODIGO,
    --I.CODIGO AS CODIGO,
    I.CODIGO AS COD_FABRICANTE,
    I.REFERENCIA_ID AS PERSONAL4,    
    I.DESCRICAO,
    I.CODIGO_BARRAS AS BARRAS,
    I."UNIDADE" AS UND,
    I.TIPO AS PERSONAL1,
    I.NCM AS COD_NCM,
    I.CEST AS PERSONAL6,
    I.PRECO_CUSTO,
    I.PRECO_VENDA,
    I.MARGEM_LUCRO,
    CASE I.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
    I.CODIGO_ANP AS COD_ANP,
    I.ESTOQUE_MINIMO AS QTD_IDEAL,
    I.ESTOQUE AS QTD,
--    I.ESTOQUE_DISPONIVEL AS QTD,    
    I.DATA_ULTIMA_COMPRA AS ULTIMA_COMPRA,
    I.DATA_CADASTRO,
    I."OBSERVACAO" AS OBSERVACOES,
    I.VALIDADE_DIAS,
    I.COMISSAO,
    G.DESCRICAO AS GRUPO,
    E."NOME" AS FORNECEDOR,
--    IM.CSOSN AS ST,
    IM.CST_ICMS AS ST,    
    IM.CST_PIS AS PIS_CODIGO,
    IM.CST_COFINS AS COFINS_CODIGO,
    IM.CST_IPI AS IPI_CODIGO_VENDA,
    IM.PIS AS PIS_ALIQ_NOR,
    IM.COFINS AS COFINS_ALIQ_NOR,
    IM.IPI AS ALIQ_IPI_VENDA,    
    IM.CST_PIS_ENTRADA AS PISE_CODIGO,
    IM.CST_COFINS_ENTRADA AS COFINSE_CODIGO,
    IM.CST_IPI_ENTRADA AS IPI_CODIGO,    
    IM.ORIGEM_MERCADORIA AS OST,    
    C.CFOP AS CF,
    LEFT (C.CFOP,3) AS ELO
FROM
    ITENS I
LEFT JOIN GRUPOS G ON G.ID_GRUPO = I.ID_GRUPO 
LEFT JOIN EMPRESAS E ON E.ID_EMPRESA = I.ID_FORNECEDOR 
LEFT JOIN ITENS_IMPOSTOS IM ON IM.ID_ITEM = I.ID_ITEM 
LEFT JOIN CFOP C ON C.ID_CFOP = IM.ID_CFOP 
WHERE I.EXCLUIDO = 'N';
