SELECT
  TBPRODUTO.CODPRODUTO AS CODIGO,
  TBPRODUTO.DESCRIPTION AS DESCRICAO,
  TBPRODUTO.DATACOMPRA AS ULTIMA_COMPRA,
  TBPRODUTO.ONHAND AS QTD,
  TBPRODUTO.COST AS PRECO_CUSTO,
  TBPRODUTO.LISTPRICE AS PRECO_VENDA,
  TBPRODUTO.FORNECEDOR AS FORNECEDOR,
  TBPRODUTO.SECAO AS GRUPO,
  TBPRODUTO.ESTOQUEMINIMO AS QTD_IDEAL,
  replace(TBPRODUTO.PARTNO,'.','') AS COD_FABRICANTE,
  replace(TBPRODUTO.PARTNO,'.','') AS BARRAS,
  TBPRODUTO.CODIGO_TEXTO AS OBSERVACOES,
  TBPRODUTO.VR_FORNECEDOR AS PRECO_ATACADO,
  TBPRODUTO.M_LUCRO AS MARGEM_LUCRO
FROM TBPRODUTO
