SELECT
  FORNECEDORES.FOR_COD_A AS CODIGO,
  FORNECEDORES.FOR_NOME_A AS NOME,
  FORNECEDORES.FOR_RSOCIAL_A AS FANTASIA,
  FORNECEDORES.TELEFONE AS TELEFONE,
  FORNECEDORES.FAX AS FAX,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.BAIRRO AS BAIRRO,
  FORNECEDORES.CIDADE AS CIDADE,
  FORNECEDORES.ESTADO AS UF,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.OBS AS OBSERVACOES,
  FORNECEDORES.CONTATO AS CONTATO,
  case when fornecedores.cgc = '' then fornecedores.cpf else fornecedores.cgc end as cnpj_cnpf,
  case when fornecedores.inscest = '' then fornecedores.rg else fornecedores.inscest end as ie_rg,
  FORNECEDORES.CELULAR_VENDEDOR AS CELULAR,
  FORNECEDORES.EMAIL_VENDEDOR AS EMAIL,
  FORNECEDORES.NUMERO_ENDERECO AS NUMERO
FROM FORNECEDORES
