SELECT
  PRODUTOS.CODPRO AS CODIGO,
  PRODUTOS.NOMPRO AS DESCRICAO,
  GRUPOS.GRUPO AS GRUPO,
  PRODUTOS.UNI AS UND,
  PRODUTOS.CODBAR AS BARRAS,
  PRODUTOS.QTDEAT AS QTD,
  PRODUTOS.VALVENDA AS PRECO_VENDA,
  PRODUTOS.CUSTO AS PRECO_CUSTO,
  PRODUTOS.REFERENCIA AS COD_FABRICANTE,
  FORNECEDORES.FOR_NOME_A AS FORNECEDOR,
  PRODUTOS.DATA_CADASTRAMENTO AS DATA_CADASTRO,
  PRODUTOS.PESO AS PESO,
  PRODUTOS.ULTIMAVENDA AS ULTIMA_VENDA,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.OBSERVACAO AS OBSERVACOES,
  PRODUTOS.CSOSN AS ST
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.CODI = PRODUTOS.CODGRU
LEFT JOIN FORNECEDORES ON FORNECEDORES.FOR_COD_A = PRODUTOS.CODFOR
