SELECT 
PRODUTOS.CODIGO AS COD_FABRICANTE,
PRODUTOS.ITEM AS GRUPO,
PRODUTOS.DESCRICAO,
PRODUTOS.NCM AS COD_NCM,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.PRECO1 AS PRECO_VENDA,
PRODUTOS.ATUAL AS QTD
FROM PRODUTOS



