SELECT
    ID_FORNECEDOR AS CODIGO,
    RAZAO_SOC AS NOME,
    NOME_FANTA AS FANTASIA,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    replace (replace(CEP,'-',''),'.','') AS CEP,
    UF AS UF,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    REPRESENTANTE AS CONTATO,
    OBS AS OBSERVACOES,
    EMAIL AS EMAIL,
    CELULAR AS CELULAR
FROM FORNECEDOR