SELECT
    CODCLI AS CODIGO,
    NOMECLI AS NOME,
    FANTCLI AS FANTASIA,
    ENDERCLI AS ENDERECO,
    BAIRROCLI AS BAIRRO,
    CIDADECLI AS CIDADE,
    UFCLI AS UF,
    CEPCLI AS CEP,
    FONE1CLI AS TELEFONE,
    FONE2CLI AS CELULAR,
    FAXCLI AS FAX,
    EMAILCLI AS EMAIL,
    CPFCNPJCLI AS CNPJ_CNPF,
    CIDINSCCLI AS IE_RG,
    CONTATOCLI AS CONTATO,
    DATANASCCLI AS NASCIMENTO,
    PROFISSAOCLI AS PROFISSAO,
    NOMEPAICLI AS PAI,
    NOMEMAECLI AS MAE,
    NOMECONJCLI AS CONJUGE,
    SEXOCLI AS SEXO,
    LIMITECREDITOCLI AS LIMITE_CREDITO,
   -- DATACADASTROCLI AS CADASTRO,
    OBSERVACAOCLI AS OBSERVACOES,
    NUMENDCLI AS NUMERO,
    COMPENDCLI AS COMPLEMENTO,
    INSCMUNCLI AS IM
FROM T01_001




