SELECT
    replace (replace(PRODUTOS.CODPROD,'.',''), ' ','') AS CODIGO,
    GRUPOS.DESCR AS GRUPO,
    SUBGRUPOS.DESCR AS FAMILIA,
    PRODUTOS.DESCRED AS DESCRICAO,
    PRODUTOS.UNDENT AS UND_COMPRA,
    PRODUTOS.UNDSAI AS UND,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.CODBAR AS BARRAS,
    PRODUTOS.VALMED AS CUSTO_MEDIO,
    PRODUTOS.QTEATU AS QTD,
    PRODUTOS.ESTMIN AS QTD_IDEAL,
    PRODUTOS.CODREF  AS COD_FABRICANTE,
    PRODUTOS.MARGEMLUCRO AS MARGEM_LUCRO,
    PRODUTOS.CARACTERISTICA AS CARACTERISTICAS,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.VALOR_UNITARIO AS PRECO_CUSTO,
    PRODUTOS.DT_CADASTRO AS DATA_CADASTRO,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.OBS_PRODUTO AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.GRUPO = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.SUBGRUPO = PRODUTOS.SUBGRUPO  and GRUPOS.GRUPO = subgrupos.GRUPO
