SELECT
    PRODUTOS.LOJA,
    --PRODUTOS.COD_PRODUTO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.COD_BARRA AS BARRAS,
    PRODUTOS.VENDA1 AS PRECO_VENDA,
    PRODUTOS.CST_GERENCIAL AS PRECO_CUSTO,
    PRODUTOS.ST AS ST,
    PRODUTOS.FABRICANTE AS COD_FABRICANTE,
    PRODUTOS.MARCA AS CARACTERISTICAS,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.QTD_GERENCIAL AS QTD,
    PRODUTOS.QTD_MINIMA AS QTD_IDEAL,
    max (GRUPOS.DESCRICAO) AS GRUPO,
    max (SUBGRUPOS.DESCRICAO) AS FAMILIA,
    CAST (PRODUTOS.ULTIMA_VENDA AS DATE) AS ULTIMA_VENDA,
    CAST (PRODUTOS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
    FORNECEDORES.RAZAO_SOCIAL AS FORNECEDOR,
    PRODUTOS.CLAS_FISCAL AS PERSONAL6,
    PRODUTOS.NBM AS COD_NCM
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.GRUPO = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.SUBGRUPO = PRODUTOS.SUBGRUPO
LEFT JOIN FORNECEDORES ON FORNECEDORES.COD_FORNECEDOR = PRODUTOS.FORNECEDOR
group by 1,2,3,4,5,6,7,8,9,10,11,12,15,16,17,18,19