SELECT
  TERCEIROS.ID AS CODIGO,
  TERCEIROS.RazaoSocial AS NOME, 
  TERCEIROS.NomeFantasia AS FANTASIA,
  TERCEIROS.CEP AS CEP,
  TERCEIROS.Logradouro AS ENDERECO,
  TERCEIROS.Numero AS NUMERO,
  TERCEIROS.Complemento AS COMPLEMENTO,
  TERCEIROS.Bairro AS BAIRRO,
  TERCEIROS.Fone1 AS TELEFONE,
  TERCEIROS.Fone2 AS CELULAR,
  TERCEIROS.Fax AS FAX,
  TERCEIROS.Email AS EMAIL,
  TERCEIROS.Documento AS CNPJ_CNPF,
  case when TERCEIROS.IE = '' or TERCEIROS.IE is null then TERCEIROS.RG else TERCEIROS.IE END AS IE_RG,
  IM AS IM, 
  TERCEIROS.Obs AS OBSERVACOES
FROM TERCEIROS
WHERE TERCEIROS.Aplicabilidade_Cliente <> '1'