SELECT
	P.PRO_PKN_CODIGO AS CODIGO,
	P.PRO_A_DESCRICAO AS DESCRICAO,
	P.PRO_A_UNIDADE AS UND,
	P.PRO_A_REFERENCIA AS COD_FABRICANTE,
	CASE P.PRO_A_STATUS WHEN 'ATIVADO' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	P.PRO_A_CODREL AS PERSONAL1,
	P.PRO_N_CODIGO_RELACIONA,
	P.PRO_N_EST_MINIMO AS QTD_IDEAL,
	P.PRO_N_PESO AS PESO,
	P.PRO_N_UN_EMBALAGEM AS UND_COMPRA,
	P.PRO_N_PERC_COMISSAO AS COMISSAO,
	P.PRO_N_PRECO_CUSTO AS PRECO_CUSTO,
	P.PRO_N_PRECO_VENDA AS PERSONAL2,
	P.PRO_N_PRECO_VENDA_01 AS PERSONAL4,
	P.PRO_N_PRECO_VENDA_02 AS PERSONAL5,
	P.PRO_N_CUSTO_MEDIO AS CUSTO_MEDIO,
	P.PRO_N_PRECO_FISCAL_SAIDA AS PRECO_VENDA,
	P.PRO_N_FATOR AS FAT_CONV,
	P.PRO_A_INF_ADICIONAL AS OBSERVACOES,
	P.PRO_N_MARGEM_LUCRO AS MARGEM_LUCRO,
	P.PRO_A_NCM AS COD_NCM,
	P.PRO_A_CODIGO_ANP AS COD_ANP,
	P.PRO_A_CEST AS PERSONAL6,
	F.PAR_A_RAZAOSOCIAL AS FORNECEDOR,
	G.GRU_A_DESCRICAO AS GRUPO,
--	T.TRI_A_SITUACAO_A AS ST,
	T.TRI_A_SITUACAO_B AS ST,
--	LEFT (T.TRI_A_CFOP_DENTRO,3) AS ELO, 
	T.TRI_A_CST_PIS AS PIS_CODIGO,
	T.TRI_A_CST_COFINS AS COFINS_CODIGO,
	T.TRI_A_CST_IPI AS IPI_CODIGO_VENDA,
	B.BAR_A_CODIGO AS BARRAS,
	ES.EST_N_REAL_SALDO_01 AS QTD
--	ES.EST_N_FISCAL_SALDO_01 AS QTD
FROM
	TB_PRO_PRODUTO P
LEFT JOIN TB_PAR_PARTICIPANTE F ON F.PAR_PKN_CODIGO = P.PAR_PKN_CODIGO 
LEFT JOIN TB_GRU_GRUPO G ON G.GRU_PKN_CODIGO = P.GRU_PKN_CODIGO 
LEFT JOIN TB_TRI_TRIBUTACAO T ON T.TRI_PKN_CODIGO = P.TRI_PKN_CODIGO 
LEFT JOIN TB_BAR_CODIGO_BARRA B ON B.PRO_PKN_CODIGO = P.PRO_PKN_CODIGO 
LEFT JOIN TB_EST_ESTOQUE ES ON ES.PRO_PKN_CODIGO = P.PRO_PKN_CODIGO
