SELECT
  PRODUTOS.ID_PRODUTO AS CODIGO,
  PRODUTOS.CODIGO AS BARRAS,
  PRODUTOS.CODBARRAS AS COD_FABRICANTE,
  GRUPOPROD.DESCRICAO AS GRUPO,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  PRODUTOS.UN AS UND,
  PRODUTOS.QUANTIDADE AS QTD,
  PRODUTOS.MINIMO AS QTD_IDEAL,
  PRODUTOS.DATAINICIAL AS DATA_CADASTRO,
  PRODUTOS.PRECOVENDA AS PRECO_VENDA,
  PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
  PRODUTOS.MARGEM1 AS MARGEM_LUCRO,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.OBSERVACAO AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPOPROD ON GRUPOPROD.ID_GRUPOPROD = PRODUTOS.ID_GRUPOPROD