SELECT  
  CADFORN.codforn02 AS CODIGO,
  CADFORN.razforn02 AS NOME,
  CADFORN.endforn02 AS ENDERECO,
  CADFORN.Cgcforn02 AS CNPJ_CNPF,
  CADFORN.insforn02 AS IE_RG,
  TABMUN.NOME AS CIDADE,
  TABMUN.UF AS UF,
  CADFORN.cepforn02 AS CEP,
  CADFORN.fonefor02 AS TELEFONE,
  CADFORN.nomecon02 AS CONTATO,
  CADFORN.Bairro02 AS BAIRRO,
  CADFORN.emailfor02 AS EMAIL,
  CADFORN.numender02 AS NUMERO,
  CADFORN.compleme02 AS COMPLEMENTO
FROM CADFORN
LEFT JOIN TABMUN ON TABMUN.codigo = CADFORN.codmunic02
