SELECT
    left (TPAGAR.CONTROLE||'/'||TPAGAR.DOCUMENTO,14) AS DOCUMENTO
   ,TPAGAR.DESCRICAOLANCAMENTO AS HISTORICO
   ,TPAGAR.CODFORNECEDOR AS COD_FORNECEDOR
   ,left (TPAGAR.FORNECEDOR,60) AS NOM_FORNECEDOR
   ,CAST(TPAGAR.DATAHORACADASTRO AS DATE) AS EMISSAO
   ,TPAGAR.DATAVENCIMENTO AS VENCIMENTO
   ,TPAGAR.VALORORIGINAL AS VALOR_DUP
   ,TPAGAR.DATAPAGAMENTO AS PAGAMENTO
   ,TPAGAR.VALORPAGO AS VALOR_PAG
   ,TPAGAR.VALORJUROAPAGAR AS VALOR_JUR
   ,TPAGAR.VALORDESCONTO AS VALOR_DES
   ,TPAGAR.ESPECIE AS PORTADOR
   ,TPAGAR.DESCRICAOLANCAMENTO AS OBSERVACOES
   ,CASE WHEN TFORNECEDOR.CNPJ IS NULL THEN TFORNECEDOR.CPF ELSE TFORNECEDOR.CNPJ END AS CNPJ
FROM TPAGAR
LEFT JOIN TFORNECEDOR ON TFORNECEDOR.CONTROLE = TPAGAR.CODFORNECEDOR
