SELECT
    left (TRECEBER.DOCUMENTO||'/'||TRECEBER.controle,14) AS DOCUMENTO
   ,TRECEBER.DESCRICAOLANCAMENTO AS HISTORICO
   ,TRECEBER.CODCLIENTE AS COD_CLIENTE
   ,left (TRECEBER.CLIENTE, 60) AS NOM_CLIENTE
   ,CAST (TRECEBER.DATAHORACADASTRO AS DATE) AS EMISSAO
   ,TRECEBER.DATAVENCIMENTO AS VENCIMENTO
   ,TRECEBER.VALORORIGINAL AS VALOR_DUP
   ,TRECEBER.DATARECEBIMENTO AS RECEBIMENTO
   ,TRECEBER.VALORPAGO AS VALOR_REC
   ,TRECEBER.VALORJUROARECEBER AS VALOR_JUR
   ,TRECEBER.VALORDESCONTO AS VALOR_DES
   ,TRECEBER.ESPECIE
   ,TRECEBER.NOSSONUMERO AS NOSSO_NUM
   ,TRECEBER.NPARCELA AS NUM_PARCELA
   ,TRECEBER.DESCRICAOLANCAMENTO AS OBSERVACOES
   , CASE WHEN TCLIENTE.CPF IS NULL THEN  TCLIENTE.CNPJ ELSE TCLIENTE.CPF END AS CNPJ
FROM TRECEBER
LEFT JOIN TCLIENTE ON TCLIENTE.CONTROLE = TRECEBER.CODCLIENTE
