SELECT
    ESTOQUE.CODIGO AS CODIGO,
    ESTOQUE.REFERENCIA AS COD_FABRICANTE,
    ESTOQUE.DESCRICAO AS DESCRICAO,
    ESTOQUE.NOME AS GRUPO,
    ESTOQUE.FORNECEDOR AS FORNECEDOR,
    ESTOQUE.MEDIDA AS UND,
    ESTOQUE.PRECO AS PRECO_VENDA,
    ESTOQUE.CUSTOCOMPR AS PRECO_CUSTO,
    ESTOQUE.CUSTOMEDIO AS CUSTO_MEDIO,
    ESTOQUE.MARGEMLB AS MARGEM_LUCRO,
    ESTOQUE.QTD_ATUAL AS QTD,
    ESTOQUE.QTD_MINIM AS QTD_IDEAL,
    ESTOQUE.PESO AS PESO,
    ESTOQUE.CF AS COD_NCM,
    case when ESTOQUE.CST = '' or ESTOQUE.CST is null then ESTOQUE.ST else ESTOQUE.CST END AS ST,
    ESTOQUE.OBS AS OBSERVACOES
FROM ESTOQUE
