SELECT
	PRODUTO.CODIGO AS CODIGO,
	PRODUTO.GTIN AS PERSONAL1,
	PRODUTO.DESCRICAO AS DESCRICAO,
	PRODUTO.CODBARRA AS BARRAS,
	PRODUTO.DATULTCOMP AS ULTIMA_COMPRA,
	UNIDADE.DESCRICAO AS UND,
	PRODUTO.SITTRIBUTARIA AS ST,
	PRODUTO.NCM AS COD_NCM,
	PRODUTO.SITTRIBUTARIAIPI AS IPI_CODIGO,
	PRODUTO.SITTRIBUTARIAPIS AS PIS_CODIGO,
	PRODUTO.SITTRIBUTARIACOFINS AS COFINS_CODIGO,
	PRODUTO.CEST AS PERSONAL6,
	PRODUTO.DATACADASTRO AS DATA_CADASTRO,
	--SALDO.ESTOQUE AS QTD,
   (select top 1 SALDO.ESTOQUE from SALDO where PRODUTO.CODIGO = SALDO.PRODUTO order by SALDO.DATULTALT desc) AS QTD,
   (select top 1 PRODUTOREGIAO.PRCCOMPRA from PRODUTOREGIAO where PRODUTO.CODIGO = PRODUTOREGIAO.PRODUTO order by PRODUTOREGIAO.DATULTALT desc) AS PRECO_CUSTO,
   (select top 1 PRODUTOREGIAO.PRCVENDA from PRODUTOREGIAO where PRODUTO.CODIGO = PRODUTOREGIAO.PRODUTO order by PRODUTOREGIAO.DATULTALT desc) AS PRECO_VENDA,
   (select top 1 PRODUTOREGIAO.LUCRO from PRODUTOREGIAO where PRODUTO.CODIGO = PRODUTOREGIAO.PRODUTO order by PRODUTOREGIAO.DATULTALT desc) AS MARGEM_LUCRO
FROM PRODUTO
LEFT JOIN UNIDADE ON PRODUTO.UNIDADE =UNIDADE.CODIGO 
--LEFT JOIN SALDO ON SALDO.PRODUTO=PRODUTO.CODIGO 
