SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    MARCASPRODUTOS.nome AS CARACTERISTICAS,
    PRODUTOS.EAN AS BARRAS,
    PRODUTOS.PESOLIQUIDO AS PESO,
    SUM (ESTOQUES.quantidade) AS QTD,
    PRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
    UNIDADESMEDIDA.sigla AS UND,
    LISTASPRECOSPRODUTOS.VALOR AS PRECO_VENDA,
    PRODUTOSEMPRESAS.PRECOCOMPRA AS PRECO_CUSTO,
    LISTASPRECOSPRODUTOS.PERMARGEMVENDA AS MARGEM_LUCRO,
    PRODUTOSEMPRESAS.CUSTOMEDIO AS CUSTO_MEDIO,
    CAST (LISTASPRECOSPRODUTOS.DTULTIMOREAJUSTE AS DATE) AS ALTERACAO_PRECO,
    CLASSIFICACAOFISCAL.classificacaofiscal AS COD_NCM,
    CEST.codigocest AS PERSONAL6
FROM PRODUTOS
LEFT JOIN MARCASPRODUTOS ON MARCASPRODUTOS.idmarcasprodutos = PRODUTOS.IDMARCASPRODUTOS
LEFT JOIN PRODUTOSEMPRESAS ON PRODUTOSEMPRESAS.idprodutos = PRODUTOS.IDPRODUTOS
LEFT JOIN UNIDADESMEDIDA ON UNIDADESMEDIDA.idunidadesmedida = PRODUTOSEMPRESAS.IDUNIDADESMEDIDA
LEFT JOIN CLASSIFICACAOFISCAL ON CLASSIFICACAOFISCAL.idclassificacaofiscal = PRODUTOSEMPRESAS.IDCLASSIFICACAOFISCAL
LEFT JOIN CEST ON CEST.idcest = PRODUTOSEMPRESAS.IDCEST
LEFT JOIN ESTOQUES ON ESTOQUES.idprodutos = PRODUTOS.IDPRODUTOS
LEFT JOIN LISTASPRECOSPRODUTOS ON LISTASPRECOSPRODUTOS.idprodutos = PRODUTOS.IDPRODUTOS
GROUP BY 1,2,3,4,5,6,8,9,10,11,12,13,14,15,16