SELECT
  ACPRODUTO.CODPRODUTO,
  ACSUBGRUPO.DESCRICAO AS FAMILIA,
  SUBSTRING (ACSITUACAOTRIBUTARIA.COFSITUACAOTRIBUTARIA FROM 2 FOR 3) AS ST,
  ACGRUPO.DESCRICAO AS GRUPO,
  ACCLASSIFICACAOFISCAL.NUMERO AS COD_NCM,
  ACCLASSIFICACAOFISCAL.CODIGO_CEST AS PERSONAL6,
  ACPRODUTO.BARRAS AS BARRAS,
  ACPRODUTO.UNIDADE AS UND,
  ACPRODUTO.CUSTO AS PRECO_CUSTO,
  ACPRODUTO.APLICACAO AS CARACTERISTICAS,
  ACPRODUTO.MARGEM AS MARGEM_LUCRO,
  ACPRODUTO.VENDA AS PRECO_VENDA,
  ACPRODUTO.ESTOQUEATUAL AS QTD,
  ACPRODUTO.ESTOQUEMINIMO AS QTD_IDEAL,
  ACPRODUTO.OBSERVACAO AS OBSERVACOES,
  ACPRODUTO.DATA_ALTERACAO AS ALTERACAO_PRECO,
  ACPRODUTO.PESO_LIQUIDO AS PESO,
  ACPRODUTO.DESCRICAO AS DESCRICAO,
  ACPRODUTO.DATA_INCLUSAO AS DATA_CADASTRO,
  ACPRODUTO.REFERENCIA AS COD_FABRICANTE,
  ACPRODUTO.CUSTOMEDIO AS CUSTO_MEDIO
FROM ACPRODUTO
LEFT JOIN ACGRUPO ON ACGRUPO.CODGRUPO = ACPRODUTO.CODGRUPO
LEFT JOIN ACSUBGRUPO ON ACSUBGRUPO.CODSUBGRUPO = ACPRODUTO.CODSUBGRUPO
LEFT JOIN ACSITUACAOTRIBUTARIA ON ACSITUACAOTRIBUTARIA.CODSITUACAOTRIBUTARIA = ACPRODUTO.CODSITUACAOTRIBUTARIA
LEFT JOIN ACCLASSIFICACAOFISCAL ON ACCLASSIFICACAOFISCAL.CODCLASSIFICACAO = ACPRODUTO.CODCLASSIFICACAOFISCAL
