SELECT
    PRODUTO.CODIGO_PRODUTO AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    replace(PRODUTO.CODIGO_BARRAS,'.','') AS BARRAS,
    replace(PRODUTO.CODIGO_CFOP,'.','') AS CF,
    PRODUTO.CODIGO_UNIDADE_MEDIDA AS UND,
    PRODUTO.PRECO_UNITARIO_VENDA AS PRECO_VENDA,
    replace(PRODUTO.CODIGO_NCM,'.','') AS COD_NCM,
    PRODUTO.ORIGEM_MERCADORIA AS OST,
    PRODUTO.CODIGO_ICMS AS ST,  
    GRUPO_PRODUTO.DESCRICAO AS GRUPO,
    PRODUTO.QUANTIDADE_ESTOQUE AS QTD
FROM PRODUTO
LEFT JOIN GRUPO_PRODUTO ON GRUPO_PRODUTO.CODIGO_GRUPO = PRODUTO.CODIGO_GRUPO_PRODUTO