select
    CL.CLIENTE_COD AS CODIGO,
    EST.uf_SIGLA AS uf,
    CL.CLIENTE_NOME AS NOME,
    CL.CLIENTE_ENDER_RUA AS ENDERECO,
    CL.CLIENTE_BAIRRO AS BAIRRO,
    CID.CIDADE_NOME AS cidade,
    CL.CLIENTE_CEP AS CEP,
    CL.CLIENTE_FONE AS TELEFONE,
    CL.CLIENTE_FAX AS FAX,
    CL.CLIENTE_EMAIL AS EMAIL,
    CL.CLIENTE_DT_CAD AS CADASTRO,
    CL.CLIENTE_DT_NASC AS NASCIMENTO,
    case when CL.CLIENTE_CGC = '' or CL.CLIENTE_CGC is null then CL.CLIENTE_CIC else CL.CLIENTE_CGC END as CNPJ_CNPF,
    case when CL.CLIENTE_IDENT = '' or CL.CLIENTE_IDENT is null then CL.CLIENTE_IE else CL.CLIENTE_IDENT END as IE_RG,
    CL.CLIENTE_IM AS IM,
    CL.CLIENTE_OBS AS OBSERVACOES,
    CL.CLIENTE_FANTASIA AS FANTASIA,
    CL.CLIENTE_CELULAR  AS CELULAR
    from CLIENTE AS CL
    LEFT JOIN UF EST ON CL.CLIENTE_UF_COD = EST.uf_COD
    LEFT JOIN cidade CID ON CL.CLIENTE_CIDADE_COD = CID.cidade_COD

