SELECT
    F.FORNEC_COD AS CODIGO,
    F.FORNECEDOR_NOME AS NOME,
    F.FORNECEDOR_ENDER_RUA AS ENDERECO,
    F.FORNECEDOR_BAIRRO AS BAIRRO,
    CID.CIDADE_NOME AS cidade,
    EST.uf_SIGLA AS uf,
    F.FORNECEDOR_CEP AS CEP,
    F.FORNECEDOR_FONE AS TELEFONE,
    F.FORNECEDOR_FAX AS FAX,
    F.FORNECEDOR_EMAIL AS EMAIL,
    F.FORNECEDOR_DT_CAD AS CADASTRO,
    F.FORNECEDOR_IM AS IM,
    F.FORNECEDOR_CGC AS CNPJ_CNPF,
    F.FORNECEDOR_IE AS IE_RG,
    F.FORNECEDOR_OBS_PADRAO AS OBSERVACOES,
    F.FORNECEDOR_FANTASIA AS FANTASIA,
    F.FORNECEDOR_ENDER_NUMERO AS NUMERO,
    F.FORNECEDOR_ENDER_COMPLEMENTO AS COMPLEMENTO
    FROM FORNECEDOR AS F
    LEFT JOIN UF EST ON F.FORNECEDOR_UF_COD = EST.uf_COD
    LEFT JOIN cidade CID ON F.FORNECEDOR_CIDADE_COD = CID.cidade_COD