SELECT CLIENTES.CODIGO,
CLIENTES.NOME,
CLIENTES.RAZAO AS FANTASIA,
CLIENTES.FONE AS TELEFONE,
CLIENTES.CELULAR,
CLIENTES.FAX,
CLIENTES.CONTATO,
CLIENTES.EMAIL,
CLIENTES.ENDERECO,
CLIENTES.CEP,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.ESTADO AS UF,
CLIENTES.INS_RG AS IE_RG,
CLIENTES.CGC_CPF AS CNPJ_CNPF,
CLIENTES.DATA_CAD AS CADASTRO,
CLIENTES.OBJS AS OBSERVACOES,
CLIENTES.NUMERO_END AS NUMERO
FROM SUPERSCE43.dbo.CLIENTES
WHERE CLIENTES.CODIGO <> '0' AND CLIENTES.JF = 'F'



