SELECT
       TRANSP.CODIGO AS CODIGO
      ,TRANSP.NOME AS RAZAO_SOCIAL
      ,TRANSP.CGC AS CNPJ
      ,TRANSP.IES AS IE
      ,TRANSP.ENDERECO AS ENDERECO
      ,TRANSP.CIDADE AS CIDADE
      ,TRANSP.ESTADO AS UF
      ,TRANSP.FONE1 AS TELEFONE
      ,TRANSP.EMAIL AS EMAIL
      ,TRANSP.CEP AS CEP
  FROM SUPERSCE43.dbo.TRANSP
  WHERE TRANSP.NOME <> '';
