SELECT
    ESTOQUEI.CODIGO AS CODIGO,
    ESTOQUEI.DESCRICAO AS DESCRICAO,
    ESTOQUEI.COD_BARRAS AS BARRAS,
    ESTMARCA.NOME AS CARACTERISTICAS,
    ESTOQUEI.UNIDADE AS UND,
    ESTOQUEI.EST_MINIMO AS QTD_IDEAL,
    SUM (ESTOQUE_S.QTDE_ENTRADAS - ESTOQUE_S.QTDE_SAIDAS) AS QTD,
    ESTOQUEI.PESO AS PESO,
    FAMILIA.NOME AS FAMILIA,
    ESTGRUPO.DESCRICAO AS GRUPO,
    --FORNECEDOR,
    ESTOQUEI.VL_CUSTO AS PRECO_CUSTO,
    ESTOQUEI.CMEDIO AS CUSTO_MEDIO,
    ESTOQUEI.PRECO_01 AS PRECO_VENDA,
    CLFISCAL.COD_ORIGEM AS OST,
    CLFISCAL.COD_CST AS ST,
    ESTOQUEI.COD_NCM AS COD_NCM,
    ESTOQUEI.REFERENCIA AS COD_FABRICANTE,
    ESTOQUEI.DATA_COMP AS ULTIMA_COMPRA,
    ESTOQUEI.DATACADAST AS DATA_CADASTRO,
    ESTOQUEI.COD_CEST AS PERSONAL6
FROM ESTOQUEI
LEFT JOIN ESTMARCA ON ESTMARCA.CODIGO = ESTOQUEI.MARCA
LEFT JOIN ESTGRUPO ON ESTGRUPO.GRUPO = ESTOQUEI.GRUPO
LEFT JOIN FAMILIA ON FAMILIA.CODIGO = ESTOQUEI.FAMILIA
LEFT JOIN CLFISCAL ON CLFISCAL.CODIGO = ESTOQUEI.CL_FISCAL
LEFT JOIN ESTOQUE_S ON ESTOQUE_S.PRODUTO = ESTOQUEI.CODIGO
GROUP BY 1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20