SELECT
  TAB_PESSOA.COD_PESSOA AS COIGO,
  TAB_PESSOA.NOM_PESSOA AS NOME,
  TAB_PESSOA.NOM_FANTASIA AS FANTASIA,
  TAB_PESSOA.NUM_CNPJ_CPF AS CNPJ_CNPF,
  TAB_PESSOA.NUM_IE_RG AS IE_RG,
  TAB_PESSOA.ENDERECO AS ENDERECO,
  TAB_PESSOA.BAIRRO AS BAIRRO,
  TAB_PESSOA.CEP AS CEP,
  TAB_CIDADE.NOM_CIDADE AS CIDADE,
  TAB_CIDADE.SGL_UF AS UF,
  TAB_PESSOA.TELEFONE1 AS TELEFONE,
  TAB_PESSOA.TELEFONE2 AS CELULAR,
  TAB_PESSOA.CONTATO AS CONTATO,
  TAB_PESSOA.OBSERVACAO AS OBSERVACOES,
  TAB_PESSOA.EMAIL1 AS EMAIL,
  TAB_PESSOA.COMPLEMENTO AS COMPLEMENTO
FROM TAB_PESSOA
LEFT JOIN TAB_CIDADE ON TAB_CIDADE.COD_CIDADE = TAB_PESSOA.COD_CIDADE
WHERE TAB_PESSOA.IND_FORNECEDOR = 'S'