SELECT
    CLIENTE.CODIGO AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLIENTE.CPF AS CNPJ_CNPF,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.numero AS NUMERO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,
    CLIENTE.BAIRRO AS BAIRRO,
    CLIENTE.CIDADE AS CIDADE,
    CLIENTE.UF AS UF,
    CLIENTE.CEP AS CEP,
    CLIENTE.OBS AS OBSERVACOES,
    CLIENTE.LIMITE AS LIMITE_CREDITO
FROM CLIENTE
