SELECT
    COD_PRODUTO AS CODIGO,
    COD_BARRAS AS BARRAS,
    NOM_PRODUTO AS DESCRICAO,
    PRECO_VENDA AS PRECO_VENDA,
    UNIDADE AS UND,
    PRECO_CUSTO AS PRECO_CUSTO,
    QTDE AS QTD
FROM ESTOQUE

