SELECT FORNECEDOR.CODIGO,
FORNECEDOR.NOME AS FANTASIA,
FORNECEDOR.RAZAOSOCIAL AS NOME,
FORNECEDOR.ENDERECO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CIDADE,
FORNECEDOR.UF,
FORNECEDOR.CNPJ AS CNPJ_CNPF,
FORNECEDOR.INSC AS IE_RG,
FORNECEDOR.FONE1 AS TELEFONE,
FORNECEDOR.CEP,
FORNECEDOR.EMAIL
FROM FORNECEDOR
