SELECT
    CAST (CLIENTES.CODIGOCLIENTE AS VARCHAR (6)) AS CODIGO,
    CLIENTES.NOMECLIENTE AS NOME,
    CLIENTES.APELIDO AS FANTASIA,
    replace(CLIENTES.CPFCNPJ,'-','') AS CNPJ_CNPF,
    CLIENTES.RGIE AS IE_RG,
    CEPS.ENDERECO AS ENDERECO,
    BAIRROS.NOME AS BAIRRO,
    CEPS.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.NUMERO AS NUMERO,
    replace (replace(CEPS.NUM_CEP,'-',''),'.','') AS CEP,
    CIDADES.NOMECIDADE AS CIDADE,
    CIDADES.UF AS UF,
    CLIENTES.TELEFONE AS TELEFONE,
    CLIENTES.CELULAR AS CELULAR,
    CLIENTES.E_MAIL AS EMAIL,
    --CLIENTES.NASCIMENTO AS NASCIMENTO,
    CLIENTES.PAI AS PAI,
    CLIENTES.MAE AS MAE,
    CLIENTES.LIMITE AS LIMITE_CREDITO,
    CLIENTES.E_CIVIL AS EST_CIVIL,
    CLIENTES.SEXO AS SEXO,
    CLIENTES.OBSERVACAO AS OBSERVACOES
FROM CLIENTES
LEFT JOIN CEPS ON CEPS.IDCEP = CLIENTES.IDCEP
LEFT JOIN BAIRROS ON BAIRROS.IDBAIRRO = CEPS.IDBAIRRO
LEFT JOIN CIDADES ON CIDADES.IDCIDADE = BAIRROS.IDCIDADE
WHERE CLIENTES.CODIGOCLIENTE > '0'
