SELECT
C.ID AS CODIGO,
C.DATA AS CADASTRO,
C.NOME,
C.FANTASIA,
C.SEXO,
C.CNPJ_CPF AS CNPJ_CNPF,
C.IE AS IE_RG,
C."END" AS ENDERECO,
C.COMPLEM AS COMPLEMENTO,
C.REFERENCIA AS PERSONAL1,
B.nome AS BAIRRO,
C.CEP,
CI.nome AS CIDADE,
CI.uf AS UF,
C.FONE_RES AS TELEFONE,
C.FONE_COM AS PERSONAL2,
C.FAX,
C.CELULAR,
C.NASC AS NASCIMENTO,
C.OBS AS OBSERVACOES,
C.NOME_PAI AS PAI,
C.NOME_MAE AS MAE,
C.LIMITE AS LIMITE_CREDITO,
C.EMAIL,
C.CONTATO,
C.NR_END AS NUMERO
FROM cliente C
LEFT JOIN bairro b ON B.id = C.id_bairro
LEFT JOIN cidade CI ON CI.id = C.id_cidade
where C.tipo = 'CLIENTE';