SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    FANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    case when CPF = '' or CPF is null then CGC else CPF END AS CNPJ_CNPF,
    case when RG = '' or RG is null then INSC_EST else RG END AS IE_RG,
    ENDERECO AS ENDERECO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    CELULAR AS CELULAR,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR
