select
    CD_PRODUTO AS CODIGO,
    CODIGO AS COD_FABRICANTE,
    DESCRICAO,
    UNIDADE AS UND,
    CUSTO AS PRECO_CUSTO,
    LUCRO AS MARGEM_LUCRO,
    VENDA AS PRECO_VENDA,
    QUANTIDADE AS QTD,
    --CODIGO_BARRA AS BARRAS,
    CODIGO_PDV AS BARRAS,
    GRUPO AS GRUPO
    --NCM AS COD_NCM,
    --CEST AS PERSONAL6
    from produtos
