select
    codigo as codigo,
    nome as nome,
    fantasia as fantasia,
    case when cpf = '' or cpf is null then cnpj else cpf END AS cnpj_cnpf,
    case when rg = '' or rg is null then ie else rg END AS ie_rg,
    inscricao_municipal as im,
    endereco as endereco,
    numero as numero,
    bairro as bairro,
    nome_cidade as cidade,
    nome_estado as uf,
    complemento as complemento,
    cep as cep,
    telefone as telefone,
    celular as celular,
    email as email,
    filiacao1 as pai,
    filiacao2 as mae,
    nome_conjuge as conjuge,
    estado_civil as est_civil,
    sexo as sexo,
    obs as observacoes,
    limite as limite_credito,
    ultima_compra as ultima_venda,
    nascimento as nascimento,
    data_cadastro as cadastro,
    case when ativo = 'true' then 'Ativo' else 'Inativo' end as SITUACAO
from clientes
