SELECT 
       PRODUTOS.CODIGO AS CODIGO,
       PRODUTOS.CODBARRAS AS BARRAS,
       PRODUTOS.CODIGONCM AS COD_NCM,
       PRODUTOS.DESCRICAO AS DESCRICAO,
       PRODUTOS.UNIDADE AS UND,
       PRODUTOS.QUANTIDADE AS QTD,
       FORNECEDORES.RAZAO AS FORNECEDOR,
       --FORNECEDORES.RAZAO AS FAMILIA,
       GRUPOS.NOME AS GRUPO,
       PRODUTOS.PRECOVENDA AS PRECO_VENDA,
       PRODUTOS.MINIMO AS QTD_IDEAL,
       PRODUTOS.PRECOCUSTO AS PRECO_CUSTO,
       PRODUTOS.PRECOMEDIO AS CUSTO_MEDIO,
       PRODUTOS.LOCALIZACAO AS PERSONAL2,
       PRODUTOS.REFERENCIA AS COD_FABRICANTE,
       PRODUTOS.CEST AS CEST,
       ALIQUOTAS.CSOSNDENTROUF AS ST
FROM PRODUTOS
LEFT JOIN ALIQUOTAS ON ALIQUOTAS.CODIGO = PRODUTOS.CODALIQUOTA
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = PRODUTOS.CODFORNECEDOR
LEFT JOIN GRUPOS ON GRUPOS.CODIGO = PRODUTOS.CODGRUPO
