SELECT
  TCPRO.CODPROD AS CODIGO,
  TCPRO.DESCRPRODUTO AS DESCRICAO,
  TCGRP.DESCRGRUPO AS GRUPO,
  TCPRO.COMPLEMENTO AS CARACTERISTICAS,
  TCPRO.CODVOL AS UND,
  TCPRO.CODBARRA AS BARRAS,
  TCPRO.REFERENCIA AS COD_FABRICANTE,
  TCPRO.PRECOVENDA AS PRECO_VENDA,
  TCPRO.MARCA AS OBSERVACOES,
  TCPRO.ESTMIN AS QTD_IDEAL,
  TCPRO.ORIGEMPRODUTO AS OST,
  case when TCPRO.COSN = '' or TCPRO.COSN is null then TCPRO.CST else TCPRO.COSN END as ST,
  TCPRO.NCMSH AS COD_NCM,
  TCPRO.PESOLIQUIDO AS PESO,
  TCPRO.CEST AS PERSONAL6,
  TCPRO.ESTOQUEATUAL AS QTD
FROM TCPRO
LEFT JOIN TCGRP ON TCGRP.CODGRUPOPROD = TCPRO.CODGRUPROPROD
