SELECT
    FORCOD AS CODIGO,
    FORNOM AS NOME,
    FORRED AS FANTASIA,
    FORCON AS CONTATO,
    FORINS AS IE_RG,
    FORCGC AS CNPJ_CNPF,
    FORRUA AS ENDERECO,
    FORBAI AS BAIRRO,
    FORCID AS CIDADE,
    FOREST AS UF,
    FORCEP AS CEP,
    FORTEL AS TELEFONE,
    FORFAX AS FAX,
    FOREMA AS EMAIL,
    FOROBS AS OBSERVACOES
FROM FORNECEDORES
