 SELECT
    PRODUTOS.CODIGO_PRODUTO AS CODIGO,
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    PRODUTOS.CODIGO_FABRICANTE AS COD_FABRICANTE,
    LINHAS.descricao AS GRUPO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.REFERENCIA AS CARACTERISTICAS,
    PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.LUCRO_PERCENTUAL AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.ULTIMA_COMPRA AS ULTIMA_COMPRA,
    PRODUTOS.ULTIMA_VENDA AS ULTIMA_VENDA,
    PRODUTOS.DATA_CAD AS DATA_CADASTRO,
    PRODUTOS.SITUACAO_TRIBUTARIA AS ST,
    PRODUTOS.OBS AS OBSERVACOES,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.PESO_LIQUIDO AS PESO,
    PRODUTOS.PRECO_ATACADO AS PRECO_ATACADO,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN LINHAS ON LINHAS.codigo_linha = PRODUTOS.codigo_linha
