SELECT
    COD_FOR AS CODIGO,
    RAZAO AS NOME,
    LOGRADOURO AS ENDERECO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    CEP,
    UF,
    FONE AS TELEFONE,
    FAX,
    EMAIL,
    CGC AS CNPJ_CNPF,
    INSCRICAO AS IE_RG
FROM FORNECEDOR
