SELECT
    COD_MER AS CODIGO,
    DESCRICAO,
    PRECO AS PRECO_VENDA,
    PRECO_C AS PRECO_CUSTO,
    COD_BARRA AS BARRAS,
    UN AS UND,
    ST AS ST,
    CLAFISCAL AS COD_NCM,
    ESTOQUE AS QTD,
    COD_CEST AS PERSONAL6
FROM MERCADORIAS
