SELECT
	C.CODCLI AS CODIGO,
	C.CLIENTE AS NOME,
	C.NOM_FANT AS FANTASIA,
	C.ENDERECO,
	RIGHT (REPLACE(C.ENDERECO, ',', ''),4) AS NUMERO,
	C.BAIRRO,
	C.ESTADO AS UF,
	REPLACE (C.CEP,'.','') AS CEP,
	C.TELEX AS CELULAR,
	C.TELEFONE,
	C.CONTATO,
	C.CGC AS CNPJ_CNPF,
	CASE
		WHEN C.IDENTIDADE = ''
		OR C.IDENTIDADE IS NULL THEN C.INSCRICAO
		ELSE C.IDENTIDADE
	END AS IE_RG,
	C.NASC_CLI AS NASCIMENTO,
	C.OBS AS OBSERVACOES,
	C.SEXO,
	COALESCE(NULLIF(C.DATA_CAD, ''), CURRENT_DATE) AS CADASTRO,
	C.EMAIL,
	CASE
		C.CONTRIB WHEN 'S' THEN 'C'
		WHEN 'N' THEN 'N'
	END AS INDIEDEST,
	CI.DESCRICAO AS CIDADE
FROM
	CLI01 C
LEFT JOIN CID01 CI ON CI.CODIGO = C.CIDADE
WHERE CODCLI <> '00000'
