SELECT
	CODFOR AS CODIGO,
	FORNECEDOR AS NOME,
	NOME_FAN AS FANTASIA,
	ENDERECO,
	BAIRRO,
	CIDADE,
	ESTADO AS UF,
	REPLACE (CEP,'.','') AS CEP,
	TELEX AS CELULAR,
	TELEFONE,
	CONCAT (CONTATO,'-',REPRES) AS CONTATO,
	CGC AS CNPJ_CNPF,
	INSCRICAO AS IE_RG,
	OBS AS OBSERVACOES,
	TELEFOR AS FAX,
	TELEFIN AS PERSONAL1
FROM
	FOR01 
