SELECT
	P.COD_PROD AS PERSONAL1,
	P.COD_BARRA AS CODIGO,
	P.DESC_PROD AS DESCRICAO,
	P.COMP_1 AS PERSONAL2,
	P.COMP_2 AS PERSONAL4,
	P.EST_MIN AS QTD_IDEAL,
	P.PRECO_CUS AS PRECO_CUSTO,
	P.PRECO_VEN AS PRECO_VENDA,
	P.PRECO_MED AS CUSTO_MEDIO,
	REPLACE (P.SIT_TRIB,'.','') AS ST,	
	P.ICMS AS ELO,
	P.OBS AS OBSERVACOES,
	P.FABRICA AS CARACTERISTICAS,
	P.CLASFIS AS COD_NCM,
	P.PESO_BRU AS PESO,
	P.UNIDADE AS UND,
	P.BARRA AS PERSONAL5,
	P.IPI AS ALIQ_IPI_VENDA,
	P.IPI_ENT AS ALIQ_IPI,
	P.CST_IE AS IPI_CODIGO,
	P.CST_IS AS IPI_CODIGO_VENDA,	
	P.CST_PE AS PISE_CODIGO,
	P.ALIQ_PE AS PISE_ALIQ_NOR,
	P.CST_PS AS PIS_CODIGO,
	P.ALIQ_PS AS PIS_ALIQ_NOR,
	P.CST_CE AS COFINSE_CODIGO,
	P.ALIQ_CE AS COFINSE_ALIQ_NOR,
	P.CST_CS AS COFINS_CODIGO,
	P.ALIQ_CS AS COFINS_ALIQ_NOR,
	P.NDIAS AS VALIDADE_DIAS,
	P.ANP AS COD_ANP,
	P.`REF` AS BARRAS,
	F.FORNECEDOR,
	G.DESC_GRUP AS GRUPO,
            -- SG.DESC_SUB AS FAMILIA,
	P2.QTD,
	P2.COR,
	P2.TAMANHO,
                P.FABRICA AS COD_FABRICANTE
            -- P2.COD_EAN AS COD_FABRICANTE
FROM
	PROD01 P
LEFT JOIN FOR01 F ON F.CODFOR = P.CODFOR 
LEFT JOIN GRU01 G ON G.GRUPO = P.GRUPO
-- LEFT JOIN GRU02 SG ON SG.SUB_GRUPO = P.SUB_GRUPO AND SG.GRUPO = G.GRUPO
LEFT JOIN PROD02 P2 ON P2.COD_PROD = P.COD_PROD