SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    FORNECEDOR.RAZAO AS NOME,
    FORNECEDOR.FANTASIA AS FANTASIA,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.CEP AS CEP,
    CIDADES.nome AS CIDADE,
    CIDADES.uf AS UF,
    FORNECEDOR.INSCRICAO AS IE_RG,
    FORNECEDOR.CNPJ AS CNPJ_CNPF,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.TELEFONE AS TELEFONE,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.NUMCASA AS NUMERO
FROM FORNECEDOR
LEFT JOIN CIDADES ON CIDADES.codigo = FORNECEDOR.CODCIDADE
