SELECT
  TRANSPORTADORA.TRA_CODIGO AS CODIGO,
  TRANSPORTADORA.TRA_NOME AS RAZAO_SOCIAL,
  TRANSPORTADORA.TRA_PLACAVEICULO AS PLACA,
  TRANSPORTADORA.TRA_UFVEICULO AS UFV,
  TRANSPORTADORA.TRA_CNPJ_CPF AS CNPJ,
  TRANSPORTADORA.TRA_ENDERECO AS ENDERECO,
  TRANSPORTADORA.TRA_MUNICIPIO AS CIDADE,
  TRANSPORTADORA.TRA_UF AS UF,
  TRANSPORTADORA.TRA_IE AS IE,
  TRANSPORTADORA.TRA_FONE1 AS TELEFONE,
  TRANSPORTADORA.TRA_RNTC AS RNTRC
FROM TRANSPORTADORA
