SELECT
    replace(CODPRODUTO,'.',''),
    DESCRIPTION AS DESCRICAO,
    ESTOQUEMINIMO AS QTD_IDEAL,
    ONHAND AS QTD,
    COST AS PRECO_CUSTO,
    MEDIA AS CUSTO_MEDIO,
    M_LUCRO AS MARGEM_LUCRO,
    LISTPRICE AS PRECO_VENDA,
    OBS AS OBSERVACOES,
    REFERENCIA AS COD_FABRICANTE,
    DATACOMPRA AS ULTIMA_COMPRA,
    SUBSTRING (CLASSIFICAOFISCAL FROM 1 FOR 1) AS ST,
    NCM AS COD_NCM,
    CEST AS PERSONAL6
FROM TBPRODUTO
