SELECT
    --TBITEM.CODITEM AS CODIGO,
    TBITEM.CODBARRA AS BARRAS,
    TBITEM.DESCRICAO AS DESCRICAO,
    TBUNI.UNI AS UND,
    TBITEM.QTDEST AS QTD,
    TBITEM.QDTMIN AS QTD_IDEAL,
    TBITEM.PESOLIQUIDO AS PESO,
    TFOR.razaosocial AS FORNECEDOR,
    TBGRUPO.descr AS GRUPO,
    TBSUBGRUPO.descr AS FAMLIA,
    TBITEM.CODITEM AS COD_FABRICANTE,
    --TBITEM.FABRICANTE AS COD_FABRICANTE,
    TBITEM.CMEDIO AS CUSTO_MEDIO,
    TBITEM.CUSTO AS PRECO_CUSTO,
    TBITEM.LUCRO AS MARGEM_LUCRO,
    TBITEM.VALOR AS PRECO_VENDA,
    TBITEM.CST AS ST,
    TBITEM.CPROD AS COD_NCM,
    TBITEM.DESCABREV AS OBSERVACOES,
    CAST (TBITEM.DTCADASTRO AS DATE) AS DATA_CADASTRO,
    CAST (TBITEM.DTULTREAG AS DATE) AS ALTERACAO_PRECO,
    CAST (TBITEM.DTULTCOMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (TBITEM.DTULTVENDA AS DATE) AS ULTIMA_VENDA,
    TBITEM.CEST AS PERSONAL6
FROM TBITEM
LEFT JOIN TBUNI ON TBUNI.coduni = TBITEM.UNI
LEFT JOIN TBGRUPO ON TBGRUPO.codgrupo = TBITEM.codgrupoi
LEFT JOIN TFOR ON TFOR.codfor =  TBITEM.CODFORI
LEFT JOIN TBSUBGRUPO ON TBSUBGRUPO.codsubgrupoi = TBITEM.CODSUBGRUPO
