SELECT CLIENTE.CODCLI AS CODIGO,
CLIENTE.NOME,
CLIENTE.ENDERECO,
CLIENTE.TELEFONE,
CLIENTE.FAX,
CLIENTE.CELULAR,
CLIENTE.EMAIL,
CLIENTE.OBS AS OBSERVACOES,
CLIENTE.CONTATO,
CLIENTE.CEP,
CLIENTE.CIDADE,
CASE WHEN CLIENTE.CNPJ='00000000000000' THEN CLIENTE.CPF
ELSE CLIENTE.CNPJ END AS CNPJ_CNPF,
CLIENTE.IE AS IE_RG,
CLIENTE.BAIRRO,
CLIENTE.ESTADO AS UF,
CLIENTE.DATACADASTRO AS CADASTRO,
CLIENTE.FANTASIA
FROM CLIENTE