SELECT
 PRODUTO.CODPRO AS CODIGO,
PRODUTO.NOME AS DESCRICAO,
PRODUTO.VALOR AS PRECO_VENDA,
PRODUTO.CUSTO AS PRECO_CUSTO,
GRUPO.NOME AS GRUPO,
PRODUTO.UNIT AS UND,
PRODUTO.CODBAR AS BARRAS,
PRODUTO.DATA_INSERT AS DATA_CADASTRO,
PRODUTO.NCM AS COD_NCM,
ESTOQUEFILIAL.FILIAL1 AS QTD
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.CODGRUPO=GRUPO.COD
LEFT JOIN ESTOQUEFILIAL ON PRODUTO.CODPRO=ESTOQUEFILIAL.CODPRO