SELECT
    PRODUTOS.NCODIGO AS CODIGO,
    PRODUTOS.CODBARRAS AS BARRAS,
    PRODUTOS.CODNCM AS COD_NCM,
    PRODUTOS.CODCEST AS PERSONAL6,
    PRODUTOS.CODREFER AS COD_FABRICANTE,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE_VEN AS UND,
    PRODUTOS.PISCOFINS AS PIS_CODIGO,
    PRODUTOS.COFINS AS COFINS_CODIGO,
    PRODESTOQ.TRIBUTO AS ST,
    PRODESTOQ.PCO_VENDA1 AS PRECO_VENDA,
    PRODESTOQ.CUSTO_REAL AS PRECO_CUSTO,
    PRODESTOQ.EST_ATUAL AS QTD
FROM PRODUTOS
LEFT JOIN PRODESTOQ ON PRODUTOS.NCODIGO = PRODESTOQ.CODPROD
