SELECT
  PESSOA.PESCOD AS CODIGO,
  PESSOA.PESNOM AS NOME,
  PESSOA.PESNOMFAN AS FANTASIA,
  PESSOA.PESCPFCNPJ AS CNPJ_CNPF,
  CASE WHEN PESSOA.PESIE IS NULL OR PESSOA.PESIE ='' THEN PESSOA.PESRG ELSE PESSOA.PESIE END AS IE_RG,
  PESSOA.PESCEP AS CEP,
  PESSOA.PESFON1 AS TELEFONE,
  PESSOA.PESCEL AS CELULAR,
  PESSOA.PESFAX AS FAX,
  PESSOA.PESEND AS ENDERECO,
  PESSOA.PESENDNUM AS NUMERO,
  PESSOA.PESENDCOM AS COMPLEMENTO,
  PESSOA.PESBAI AS BAIRRO,
  CIDADE.CIDNOM AS CIDADE,
  CIDADE.CIDESTCOD AS UF,
  PESSOA.PESEMA AS EMAIL,
  PESSOA.PESOBS AS OBSERVACOES
FROM PESSOA
LEFT JOIN CIDADE ON CIDADE.CIDCOD = PESSOA.PESCIDCOD
WHERE PESTIP = 'F'
