SELECT CLIENTES.IdCliente AS CODIGO,
CLIENTES.NomeCliente AS NOME,
CLIENTES.NomeFantasia AS FANTASIA,
CLIENTES.Cnpj AS CNPJ_CNPF,
CLIENTES.InscEst AS IE_RG,
CLIENTES.Cep,
CONCAT(CLIENTES.DDD,CLIENTES.TELEFONE) AS TELEFONE,
CONCAT(CLIENTES.DDD_Cel,CLIENTES.Celular)AS CELULAR,
CLIENTES.FAX,
CLIENTES.CONTATO,
coalesce(CLIENTES.DataCadastro,CAST(getdate() AS date)) AS CADASTRO,
CLIENTES.Email,
CLIENTES.Endereco,
CLIENTES.NUMERO,
CLIENTES.Complemento,
CLIENTES.Bairro,
CLIENTES.CIDADE,
CLIENTES.EstadO
from clientes



