SELECT
    P.IDPRODUTO AS PERSONAL5,
    P.DESCRICAO ||' - '|| P.IDPRODUTO AS DESCRICAO,
    P.CEAN AS BARRAS,
    P.UNIDADE AS UND,
    M.DESCRICAO AS CARACTERISTICAS,
    F.DESCRICAO AS FAMILIA,
    P.PESO AS PESO,
    PE.QUANTIDADE AS QTD,
    PE.CMU AS CUSTO_MEDIO,
    PE.PRECO AS PRECO_VENDA,
    SUBSTRING (I.DESCRICAO FROM 1 FOR 1) AS ST,
    P.REFERENCIA AS COD_FABRICANTE,
    P.IDNCM AS COD_NCM,
    P.IDCEST AS CEST,
    P.CBENEF AS CBENEF,
    P.DTCADASTRO AS DATA_CADASTRO,
    PE.ULTCOMPRA AS ULTIMA_COMPRA,
    PE.ULTVENDA AS ULTIMA_VENDA,
    P.DTULTALT AS ALTERACAO_PRECO,
    case when P.INATIVO = 'N' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PRODUTOS AS P
LEFT JOIN FAMILIAS F ON P.IDFAMILIA = F.IDFAMILIA
LEFT JOIN MARCAS M ON P.IDMARCA = M.IDMARCA
LEFT JOIN ICM I ON P.IDICM = I.IDICM
LEFT JOIN PRODUTOS_ESTOQUE PE ON P.IDPRODUTO = PE.IDPRODUTO