SELECT
  C.CODIGO
, C.NOME AS FANTASIA
, C.RAZAO_SOCIAL AS NOME
, CASE WHEN C.CPF = '' OR C.CPF ='   .   .   -' OR C.CPF IS NULL THEN C.CNPJ ELSE C.CPF END AS CNPJ_CNPF
, C.IE AS IE_RG
, C.RUA AS ENDERECO
, C.NUMERO
, C.BAIRRO
, C.FONE AS TELEFONE
, C.OBSERVACAO AS OBSERVACOES
, COALESCE (C.DATACAD, CURRENT_DATE) AS CADASTRO
, C.ESTADO_CIVIL AS EST_CIVIL
, C.PAI
, C.MAE
, C.CONJUGE
, C.EMAIL
, CI.NOME AS CIDADE
, CI.UF
, CI.CEP
FROM CLIENTE C
LEFT JOIN CIDADE CI ON CI.CODIGO = C.CODCID
