SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    CPF AS CNPJ_CNPF,
    ID AS IE_RG,
    DATA_NASC AS NASCIMENTO,
    PAI,
    MAE,
    ENDERECO,
    BAIRRO,
    CEP,
    CIDADE,
    ESTADO AS UF,
    TEL_RESIDENCIA AS TELEFONE,
    TEL_CELULAR AS CELULAR,
    COMPLEMENTO,
    NUMERO,
    EMAIL1 AS EMAIL,
    FANTASIA
FROM TB_CLI
WHERE NOME <> ''
