SELECT
    PESSOA.COD_PESSOA AS CODIGO,
    PESSOA.NOME AS NOME,
    PESSOA.NOME_FANTASIA AS FANTASIA,
    PESSOA.CGC AS CNPJ_CNPF,
    PESSOA.INSC_ESTADUAL AS IE_RG,
    PESSOA.INSC_MUNICIPAL AS IM,
    PESSOA.ENDERECO1 AS ENDERECO,
    PESSOA.END_NUM1 AS NUMERO,
    BAIRROS.BAIRRO AS BAIRRO,
    PESSOA.COMPLEMENTO1 AS COMPLEMENTO,
    replace (replace(PESSOA.CEP1,'.',''),'-','') AS CEP,
    CIDADES.CIDADE AS CIDADE,
    CIDADES.ESTADO AS UF,
    PESSOA.FONES_EMPRESA AS TELEFONE,
    PESSOA.EMAIL AS EMAIL,
    PESSOA.OBS AS OBSERVACOES
FROM PESSOA
LEFT JOIN BAIRROS ON BAIRROS.COD_BAIRRO = PESSOA.COD_BAIRRO1
LEFT JOIN CIDADES ON CIDADES.COD_CIDADE = BAIRROS.COD_CIDADE
WHERE PESSOA.TIPO = 'B' --FORNECEDORES
