SELECT
    PRODUTOS.COD_PRODUTO AS CODIGO,
    PRODUTOS.CODIGO_BARRAS AS BARRAS,
    PRODUTOS.PRODUTO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    SUB_GRUPO.SUB_GRUPO AS GRUPO,
    PRODUTOS.REFERENCIA AS CARACTERISTICAS,
    PRODUTOS.PESO_LIQUIDO AS PESO,
    PROD_MOV.QDE_ATUAL AS QTD,
    SUBSTRING (TRIBUTARIA_SITUACOES.CODIGO FROM 1 FOR 1) AS OST,
    SUBSTRING (TRIBUTARIA_SITUACOES.CODIGO FROM 2 FOR 3) AS ST,
    PRODUTOS.VALOR_COMPRA AS PRECO_CUSTO,
    PRODUTOS.LUCRO AS MARGEM_LUCRO,
    PRODUTOS.VALOR_VENDA AS PRECO_VENDA,
    PRODUTOS.COD_FABRICANTE AS COD_FABRICANTE,
    PRODUTOS.OBSERVACAO AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN SUB_GRUPO ON SUB_GRUPO.COD_SUB_GRUPO = PRODUTOS.COD_SUB_GRUPO
LEFT JOIN PROD_MOV ON PROD_MOV.COD_PRODUTO = PRODUTOS.COD_PRODUTO
LEFT JOIN CFOPS ON CFOPS.CFOP = PRODUTOS.COD_CFOP_IMP_FISCAL
LEFT JOIN TRIBUTARIA_SITUACOES ON TRIBUTARIA_SITUACOES.COD_TRIBUTARIA_SIT = CFOPS.COD_TRIB_SITUA
