SELECT
    C_RECEBER.C_RECEBER_ID AS DOCUMENTO,
    C_RECEBER.DOC AS HISTORICO,
    C_RECEBER.COD_SEGURANCA,
    FORMAS_REC.DESCRICAO AS ESPECIE,
    PESSOA.COD_PESSOA AS COD_CLIENTE,
    PESSOA.NOME AS NOM_CLIENTE,
    PESSOA.CGC AS CNPJ,
    C_RECEBER.VALOR AS VALOR_DUP,
    C_RECEBER.TOTAL_PAGAMENTOS AS VALOR_REC,
    C_RECEBER.DT_VENC AS VENCIMENTO,
    C_RECEBER.DT_LANCAMENTO AS EMISSAO,
    C_RECEBER.OBS AS OBSERVACOES
FROM C_RECEBER
LEFT JOIN PESSOA ON PESSOA.COD_PESSOA = C_RECEBER.COD_PESSOA
LEFT JOIN FORMAS_REC ON FORMAS_REC.COD_FORMA_REC = C_RECEBER.COD_FORMA_REC
