SELECT
    CONTA.CONTAID AS CODIGO,
    CONTA.NOME_FANTASIA AS FANTASIA,
    CONTA.NOME,
    CONTA.CEP,
    CIDADE.descricao AS CIDADE,
    CONTA.UF,
    CONTA.ENDERECO,
    CONTA.COMPLEMENTO,
    CONTA.BAIRRO,
    CONTA.CNPJ_CPF AS CNPJ_CNPF,
    CONTA.CGF_RG AS IE_RG,
    CONTA.NUMERO 
FROM CONTA
LEFT JOIN CIDADE ON CONTA.cidade = CIDADE.CODIGO
WHERE CONTA.CONTAID > 0
