SELECT 
  P.COD_INTERNO AS CODIGO
, P.COD_PRODUTO AS COD_FABRICANTE
, P.COD_PRODUTO AS BARRAS
--, P.COD_FABRICANTE 
, P.DESCRICAO
, P.BRUTO AS PESO
, P.ESTOQUE AS QTD
, P.COMPRA AS PRECO_CUSTO
--, p.PRECO_ULT_COMPRA AS PRECO_CUSTO
, P.VENDA AS PRECO_VENDA
, LEFT (P.ST,1) AS OST
, RIGHT (P.ST,3) AS ST
, P.UNIDADE AS UND 
, P.MINIMO AS QTD_IDEAL
, P.COMISSAO
, P.DATA_ULTCOMPRA AS ULTIMA_COMPRA
, P.DATA_CADASTRO AS DATA_CADASTRO
, P.QTD_EMBALAGEM AS FAT_CONV
--, P.COD_BARRA_EMBALAGEM AS BARRAS
, P.COD_NCM AS COD_NCM
, CASE P.INATIVO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.ALI_IPI AS ALIQ_IPI_VENDA
, P.CSTIPI AS IPI_CODIGO_VENDA
, LEFT (P.CFOP_IN,3) AS ELO
, P.CSTPC_ENTRADA AS PISE_CODIGO
, P.CSTPC_ENTRADA AS COFINSE_CODIGO
, P.ALI_PIS_CREDITO AS PIS_ALIQ_NOR
, P.ALI_PIS_DEBITO AS PISE_ALIQ_NOR
, P.ALI_COFINS_CREDITO AS COFINS_ALIQ_NOR
, P.ALI_COFINS_DEBITO AS COFINSE_ALIQ_NOR
, P.CEST AS PERSONAL6
, P.COR
, P.TAMANHO
, G.DESCRICAO AS GRUPO
, SG.DESCRICAO AS FAMILIA
FROM PRODUTO P
LEFT JOIN GRUPO_PROD G ON G.COD_GRUPO = P.COD_GRUPO 
LEFT JOIN SUBGRUPO_PROD SG ON SG.COD_SUBGRUPO = P.COD_SUBGRUPO 
-- WHERE EMPRESA = '0' --- AJUSTAR CASO UTILIZE MULTILOJAS
