SELECT
    CD_PRODUTO AS CODIGO,
    CD_barras as BARRAS,
    DS_PRODUTO AS DESCRICAO,
    CD_UNIDADE AS UND,
    VL_PRECO_CUSTO AS PRECO_CUSTO,
    VL_PRECO_VENDA AS PRECO_VENDA,
    CD_NUMERICO AS COD_FABRICANTE,
    QT_ESTOQUE AS QTD,
    FL_SITRIBUTARIA AS ST,
    CD_NCM AS COD_NCM,
    CD_CEST AS PERSONAL6
FROM PRODUTO
WHERE DS_PRODUTO <>''
