SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    APELIDO AS FANTASIA,
    CPF AS CNPJ_CNPF,
    CI AS IE_RG,
    ENDERECO,
    NUMERO,
    BAIRRO,
    CIDADE,
    UF,
    CEP,
    TELEFONE,
    CELULAR,
    EMAIL
FROM CLIENTES

WHERE CADCLI = 'S' AND CODIGO > 0