SELECT
    CODIGO,
    DESCRICAO,
    CODBARRAS AS BARRAS,
    UNIDADE AS UND,
    QUANTIDADE AS QTD,
    PCUSTO AS PRECO_CUSTO,
    PRECO1 AS PRECO_VENDA,
    NOME_FORNECEDOR AS FORNECEDOR,
    NCM AS COD_NCM,
    CSOSN AS ST,
    CEST AS PERSONAL6
FROM PRODUTO