SELECT PRODUTO.ID AS CODIGO,
UNIDADE_PRODUTO.NOME AS UND,
PRODUTO.GTIN AS BARRAS,
PRODUTO.CODIGO_INTERNO AS COD_FABRICANTE,
PRODUTO.NOME AS DESCRICAO,
PRODUTO.VALOR_VENDA AS PRECO_VENDA,
PRODUTO.QTD_ESTOQUE AS QTD,
PRODUTO.NCM AS COD_NCM,
PRODUTO.DATA_ESTOQUE AS DATA_CADASTRO,
PRODUTO.CSOSN AS ST,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN UNIDADE_PRODUTO ON PRODUTO.ID_UNIDADE_PRODUTO=UNIDADE_PRODUTO.ID
