SELECT
       PRODFILHO.CODPRODFILHO AS CODIGO,
       PRODFILHOCODBARRA.CODPRODFILHOCODBARRA AS BARRAS,
       UNIDADE.SIGLA AS UND,
       PRODFILHO.DESCRICAO AS DESCRICAO,
       PRODFILHO.ESTOQUE AS QTD,
       PRODFILHO.PRECOPRATICADO1 AS PRECO_VENDA,
       --PRODFILHO.PRECOFORNEC AS PRECO_CUSTO,
       --PRODFILHO.CUSTOMEDIO AS CUSTO_MEDIO,
       PRODFILHO.NCM_CODIGO AS COD_NCM,
       PRODFILHO.PRDF_CST_TRIBICMS AS ST,
       PRODFILHO.CODPESQ1 AS COD_FABRICANTE,
       PRODFILHO.CODIGOCEST AS PERSONAL6
       --GRUPO.DESCRICAO AS GRUPO
FROM PRODFILHO
     --LEFT JOIN PRODUTO ON PRODUTO.CODPRODUTO = PRODFILHO.CODPRODUTO
     --LEFT JOIN GRUPO ON GRUPO.CODGRUPO = PRODUTO.CODGRUPO
     LEFT JOIN PRODFILHOCODBARRA ON PRODFILHOCODBARRA.CODPRODFILHO = PRODFILHO.CODPRODFILHO
     LEFT JOIN UNIDADE ON PRODFILHO.CODUNIDADE=UNIDADE.CODUNIDADE
