SELECT 
CLIENTES.ID_CLIENTE AS CODIGO,
CLIENTES.CLIENTE AS NOME,
CLIENTES.RAZ_SOCIAL AS FANTASIA,
CLIENTES.CPF_CNPJ AS CNPJ_CNPF,
CLIENTES.IE_RG AS IE_RG,
CLIENTES.LOGRADOURO AS ENDERECO,
CLIENTES.NUMERO,
CLIENTES.COMPLEMENTO,
CLIENTES.BAIRRO,
CLIENTES.MUNICIPIO AS CIDADE,
CLIENTES.UF,
CLIENTES.CEP,
CLIENTES.FONE AS TELEFONE,
CLIENTES.CELULAR,
CLIENTES.PAI,
CLIENTES.MAE,
--CLIENTES.DT_CADASTRO AS CADASTRO,
CLIENTES.EMAIL
FROM CLIENTES
WHERE CLIENTES.ID_CLIENTE<>0
