SELECT
    E.COD_REDUZ AS CODIGO,
    E.NOME1 AS DESCRICAO,
    E.GTIN_CEAN AS BARRAS,
    E.UNID_PAD AS UND,
    E.PESO AS PESO,
    E.MARCA AS CARACTERISTICAS,
    CF.NOME AS FORNECEDOR,
    E.QTD_FIS AS QTD,
    E.QTD_MIN AS QTD_IDEAL,
    E.PRECO_ENTR AS PRECO_CUSTO,
    E.CUSTOMEDIO AS CUSTIO_MEDIO,
    E.PRECO_VEND AS PRECO_VENDA,
    E.SUBST_TRIB AS ST,
    E.REFERENCIA AS COD_FABRICANTE,
    E.OBSERV1 AS OBSERVACOES,
    E.CLAS_FISC AS COD_NCM,
    E.CEST AS PERSONAL6,
    E.DATACADASTRO AS DATA_CADASTRO,
    E.DATA_ENTR AS ULTIMA_COMPRA,
    E.DATA_VEND AS ULTIMA_VENDA,
(SELECT FIRST 1 ESTPROMANOMESFORNEC.CODPRODUTOFORNEC from ESTPROMANOMESFORNEC where ESTPROMANOMESFORNEC.COD_REDUZ = E.COD_REDUZ order by ESTPROMANOMESFORNEC.COD_REDUZ) AS PERSONAL4
FROM ESTPROMA AS E
LEFT JOIN CLIFOR CF ON E.COD_FOR1 = CF.COD_CLIFOR
