select
    CLIENTES.CODIGO,
    CLIENTES.NOME,
    CLIENTES.RAZAO_SOCIAL AS FANTASIA,
    CLIENTES.ENDERECO,
    CLIENTES.ENDERECO_NRO AS NUMERO,
    CLIENTES.ENDERECO_COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.BAIRRO,
    TAB_MUNICIPIOS.NOME AS CIDADE,
    CLIENTES.UF,
    CLIENTES.CEP,
    CLIENTES.CNPJ_CPF AS CNPJ_CNPF,
    CLIENTES.IE_RG,
    CLIENTES.DDD||FONE1 AS TELEFONE
from clientes 
LEFT JOIN TAB_MUNICIPIOS ON CLIENTES.CIDADE = TAB_MUNICIPIOS.ID
