SELECT
  FORNECEDOR.CODIGO AS CODIGO,
  FORNECEDOR.CNPJ_CPF AS CNPJ_CNPF,
  FORNECEDOR.NOME AS NOME,
  FORNECEDOR.INSCRICAO AS IE_RG,
  FORNECEDOR.FANTASIA AS FANTASIA,
  FORNECEDOR.ENDERECO AS ENDERECO,
  FORNECEDOR.NUMERO AS NUMERO,
  FORNECEDOR.BAIRRO AS BAIRRO,
  FORNECEDOR.CIDADE AS CIDADE,
  FORNECEDOR.UF AS UF,
  FORNECEDOR.CEP AS CEP,
  FORNECEDOR.TELEFONE1 AS TELEFONE,
  FORNECEDOR.FAX AS FAX,
  FORNECEDOR.REPRESENTANTE AS CONTATO,
  FORNECEDOR.CELULAR AS CELULAR,
  FORNECEDOR.OBSERVACAO AS OBSERVACOES,
  FORNECEDOR.EMAIL AS EMAIL
FROM FORNECEDOR
