SELECT PRODUTOS.PRODUTO AS CODIGO,
PRODUTOS.EAN AS BARRAS,
PRODUTOS.DESCRICAO,
PRODUTOS.UNIDADE AS UND,
FORNECEDORES.NOME AS FORNECEDOR,
GRUPOS.DESCRICAO AS GRUPO,
MIN (SUBSTRING(TRIBUTACAO.CSOSN FROM 2 FOR 5)) AS ST,
PRODUTOS.CUSTO AS PRECO_CUSTO,
PRODUTOS.VENDA AS PRECO_VENDA,
PRODUTOS.DATA_INCLUI AS DATA_CADASTRO,
PRODUTOS.NCM AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON PRODUTOS.FORNECEDOR=FORNECEDORES.FORNECEDOR
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO=GRUPOS.GRUPO
LEFT JOIN TRIBUTACAO ON PRODUTOS.TRIBUTACAO=TRIBUTACAO.CODIGO
GROUP BY 1,2,3,4,5,6,8,9,10,11,12


