SELECT
    CAD_CLIENTES.CODIGO AS CODIGO,
    CAD_CLIENTES.CPF_CNPJ AS CNPJ_CNPF,
    CAD_CLIENTES.NOME AS NOME,
    CAD_CLIENTES.RG_IE AS IE_RG,
    CAD_CLIENTES.NOME_FANTASIA AS FANTASIA,
    CAD_CLIENTES.CONTATO AS CONTATO,
    CAD_CLIENTES.CEP AS CEP,
    CAD_CLIENTES.ENDERECO AS ENDERECO,
    CAD_CLIENTES.NUMERO AS NUMERO,
    CAD_CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CAD_CLIENTES.BAIRRO AS BAIRRO,
    CAD_CLIENTES.NOMECIDADE AS CIDADE,
    CAD_CLIENTES.UF AS UF,
    CAD_CLIENTES.DDD_FONE ||''|| CAD_CLIENTES.FONE AS TELEFONE,
    CAD_CLIENTES.DDD_FAX ||''|| CAD_CLIENTES.FAX AS FAX,
    CAD_CLIENTES.DDD_CELULAR ||''|| CAD_CLIENTES.CELULAR AS CELULAR,
    CAD_CLIENTES.EMAIL AS EMAIL,
    CAD_CLIENTES.OBSERVACAO AS OBSERVACOES
    FROM CAD_CLIENTES
    WHERE CAD_CLIENTES.TIPO = 'FORNECEDOR'
