SELECT
    CAD_PRODUTOS.CODIGO AS CODIGO,
    CAD_PRODUTOS.DATA AS DATA_CADASTRO,
    CAD_PRODUTOS.REFERENCIA AS CARACTERISTICAS,
    CAD_PRODUTOS.DESCRICAO AS DESCRICAO,
    CAD_PRODUTOS.UNIDADE AS UND,
    CAD_PRODUTOS.CODIGO_BARRA AS BARRAS,
    CAD_GRUPO.descricao AS GRUPO,
    CAD_SUBGRUPO.descricao AS FAMILIA,
    CAD_PRODUTOS.CODIGO_FABRICANTE AS COD_FABRICANTE,
    CAD_PRODUTOS.FORNECEDOR,
    CAD_PRODUTOS.PRC_CUSTO AS PRECO_CUSTO,
    CAD_PRODUTOS.PRC_VENDA AS PRECO_VENDA,
    CAD_PRODUTOS.MG_LUCRO AS MARGEM_LUCRO,
    CAD_PRODUTOS.ESTOQUESALDO AS QTD,
    CAD_PRODUTOS.IDNCM AS COD_NCM,
    CAD_PRODUTOS.IDCEST AS PERSONAL6,
    CAD_PRODUTOS.IDCSTORIGEM AS OST,
    CAD_PRODUTOS.IDCSOSNICMS AS ST,
    CAD_PRODUTOS.DT_ULTIMA_COMPRA AS ULTIMA_COMPRA,
    CAD_PRODUTOS.DT_ULTIMA_VENDA AS ULTIMA_VENDA,
    CAD_PRODUTOS.PESO_LIQUIDO AS PESO
FROM CAD_PRODUTOS
LEFT JOIN CAD_GRUPO ON CAD_GRUPO.codigo = CAD_PRODUTOS.grupo
LEFT JOIN CAD_SUBGRUPO ON CAD_SUBGRUPO.codigo = CAD_PRODUTOS.subgrupo
