SELECT 
  C.COD_CLIFOR AS CODIGO
, C.NOME
, C.FANTASIA
, C.CGC AS CNPJ_CNPF
, C.INSC_EST AS IE_RG
, C.CIDADE
, C.ESTADO AS UF
, C.COD_CEPEND AS CEP
, C.ENDERECO
, C.COMPLEMENTO
, C.BAIRRO
, C.NUMERO
, C.EST_COB AS COB_UF
, C.COD_CEPCOB AS COB_CEP
, C.END_COB AS COB_ENDERECO
, C.COMPLCOB AS COB_COMPLEMENTO
, C.BAICOB AS COB_BAIRRO
, C.CID_COB AS COB_CIDADE
, C.NUM_COB AS COB_NUMERO
, C.DDDFAX || FAX AS FAX
, C.DDDFONE1 || C.TELEFONE1 AS TELEFONE
, C.DDDFONE2 || C.TELEFONE2 AS CELULAR
, C.NOM_CONTAT AS CONTATO
, C.LIMITCRED AS LIMITE_CREDITO
, C.OBSERVACAO AS OBSERVACOES
, C.DATA_CAD AS CADASTRO
, C.DATA_ULTC AS ULTIMA_VENDA
, C.E_MAIL AS EMAIL
FROM CLIFOR C
WHERE C.SISTEMA = '0'
