SELECT
  COD_REDUZ AS CODIGO
, NOME1 AS DESCRICAO
, CLAS_FISC AS COD_NCM
, PESO
, QTD_FIS AS QTD
, QTD_MIN AS QTD_IDEAL
, PER_COMIS1 AS COMISSAO
, CASE SITUACAO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, LOCALIZA AS PERSONAL1
, MARCA AS CARACTERISTICAS
, OBSERV1 AS OBSERVACOES
, DATACADASTRO AS DATA_CADASTRO
, GTIN_CEAN AS BARRAS
, CST_PISCOFINS AS PIS_CODIGO
, CST_PISCOFINS AS COFINS_CODIGO
, CEST AS PERSONAL6
, PRECO_VEND AS PRECO_VENDA
, LISTA1 AS PRECO_CUSTO
, REFERENCIA AS COD_FABRICANTE
--, COD_ULT_CL
, SUBST_TRIB AS ST
FROM ESTPROMA
