SELECT
                  '*' ||''||TB_CONTA_RECEBER.id_ctarec AS DOCUMENTO
                 ,TB_CONTA_RECEBER.HISTORICO 
                 ,TB_CLIENTE.ID_CLIENTE AS COD_CLIENTE
                 ,TB_CLIENTE.NOME AS NOM_CLIENTE
                 ,TB_CONTA_RECEBER.DT_EMISSAO AS EMISSAO
                 ,TB_CONTA_RECEBER.DT_VENCTO AS VENCIMENTO
                 ,TB_CONTA_RECEBER.VLR_CTAREC AS VALOR_DUP
                 ,TB_CTAREC_BAIXA.DT_BAIXA AS RECEBIMENTO
                 ,TB_CTAREC_BAIXA.VLR_RECEB AS VALOR_REC
                 ,TB_CTAREC_BAIXA.VLR_JURO AS VALOR_JUR
                 ,TB_CTAREC_BAIXA.VLR_DESC AS VALOR_DES
                 ,TB_CONTA_PORTADOR.DESCRICAO AS PORTADOR
                 ,TB_CONTA_RECEBER.DOCUMENTO AS OBSERVACOES
                 ,tb_cli_pf.cpf AS CNPJ
             FROM TB_CONTA_RECEBER
             LEFT JOIN TB_CLIENTE ON TB_CONTA_RECEBER.ID_CLIENTE=TB_CLIENTE.ID_CLIENTE
              left join tb_cli_pf  on TB_CLIENTE.id_cliente = tb_cli_pf.id_cliente
             LEFT JOIN TB_CTAREC_BAIXA ON TB_CONTA_RECEBER.ID_CTAREC=TB_CTAREC_BAIXA.ID_CTAREC 
             LEFT JOIN TB_CONTA_PORTADOR ON TB_CONTA_RECEBER.ID_PORTADOR=TB_CONTA_PORTADOR.ID_PORTADOR
             WHERE TB_CONTA_RECEBER.ID_CLIENTE<>0 AND TB_CTAREC_BAIXA.DT_BAIXA IS NULL
