SELECT
  PROD.COD_ESTQ AS COIGO,
  PROD.CODBAR_PROD AS BARRAS,
  PROD.NOM_PROD AS DESCRICAO,
  PROD.OBS_PROD AS OBSERVACOES,
  PROD.DTENT_PROD AS ULTIMA_COMPRA,
  GRP.NOM_GRP AS GRUPO,
  PESSOAS.NOM_PESS AS FORNECEDOR,
  PROD.TIPI_PROD AS COD_NCM,
  CEST.COD_CEST AS PERSONAL6,
  PROD.CSOSN_PROD AS ST,
  PROD.CUSUNMED_PROD AS CUSTO_MEDIO,
  PROD.PRVENDA_PROD AS PRECO_VENDA,
  PROD.PESOLQKG_PROD AS PESO,
  PROD.ESTQMIN_PROD AS QTD_IDEAL,
  PROD.UNSD_PROD AS UND,
  PROD.ESTQUNSD_PROD AS QTD,
  PROD.DTINS_PROD AS DATA_CADASTRO
FROM PROD
LEFT JOIN CEST ON CEST.COD_NCM = PROD.TIPI_PROD
LEFT JOIN PESSOAS ON PESSOAS.COD_PESS = -PROD.COD_PESS
LEFT JOIN GRP ON PROD.COD_GRP=GRP.COD_GRP
