SELECT
	I.ID AS CODIGO,
	I.CODIGOFABRICA AS COD_FABRICANTE,
	I.CODIGOBARRAS AS BARRAS,
	I.DESCRICAO,
	I.NCM AS COD_NCM,
	I.DATAINCLUSAO AS DATA_CADASTRO,
	CASE
		WHEN I.DATAINATIVO IS NULL THEN 'Ativo'
		ELSE 'Inativo'
	END AS SITUACAO,
	I.QUANTIDADE AS QTD,
	I.ESTOQUEMINIMO AS QTD_IDEAL,
	I.PRECOCUSTO AS PRECO_CUSTO,
	I.PRECOVENDA AS PERSONAL4,
	I.PRECOAVISTA AS PRECO_VENDA,
	I.PERCENTUALLUCROAVISTA AS MARGEM_LUCRO,
	I.PERCENTUALLUCRO AS PERSONAL5,
	I.CEST AS PERSONAL6,
	I.UNIDADEVENDA AS UND,
	I.PESOBRUTO AS PESO,
	I.ANP AS COD_ANP,
	I.LOCALIZACAO AS PERSONAL1,
	I.CBENEF,
	I.SPED_TIPOITEM AS PERSONAL2,
	I.INFADIC AS OBSERVACOES,
	I.VALIDADE AS VALIDADE_DIAS,
	I.GRUPO,
	I.MARCA AS FAMILIA,
	REPLACE(C.CODIGO, '.', '') AS CF,
	LEFT(REPLACE(C.CODIGO, '.', ''),
	3) AS ELO,
	TU.ICMS_SITTRIB AS ST,
	TU.IPI_SITTRIB AS IPI_CODIGO_VENDA,
	TU.PIS_SITTRIB AS PIS_CODIGO,
	TU.COFINS_SITTRIB AS COFINS_CODIGO,
	TU.IPI_ALIQ AS ALIQ_IPI_VENDA,
	TU.PIS_ALIQ AS PIS_ALIQ_NOR,
	TU.COFINS_ALIQ AS COFINS_ALIQ_NOR
FROM
	ITEM I
LEFT JOIN CODIGOFISCAL C ON
	C.ID = I.CODIGOFISCALESTADO
LEFT JOIN TRIBUTACAO T ON
	T.ID = I.TRIBUTACAO
LEFT JOIN TRIBUTACAOUF TU ON
	TU.TRIBUTACAO = T.ID
	AND TU.CODIGOFISCAL = I.CODIGOFISCALESTADO
