SELECT 
PRODUTO.ID AS CODIGO,
PRODUTO.CODIGO AS COD_FABRICANTE,
PRODUTO.REFERENCIA AS PERSONAL1,
PRODUTO.CODIGO_BARRAS AS BARRAS,
PRODUTO.NOME AS DESCRICAO,
PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO,
PRODUTO.PRECO_VENDA AS PRECO_VENDA,
PRODUTO.COMISSAO,
PRODUTO.ESTOQUE_MINIMO AS QTD_IDEAL,
PRODUTO.PESO_BRUTO AS PESO,
PRODUTO.ORIGEM_PRODUTO AS OST,
CASE PRODUTO.ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO, 
PRODUTO.OBSERVACOES, 
PRODUTO.TRIB_IPISAIDA AS IPI_CODIGO_VENDA,
PRODUTO.TRIB_IPIALIQSAIDA AS ALIQ_IPI_VENDA,
PRODUTO.TRIB_PISSAIDA AS PIS_CODIGO,
PRODUTO.TRIB_PISALIQSAIDA AS PIS_ALIQ_NOR,
PRODUTO.TRIB_COFINSSAIDA AS COFINS_CODIGO,
PRODUTO.TRIB_COFINSALIQSAIDA AS COFINS_ALIQ_NOR,
DATE (PRODUTO.DATAHORA_CADASTRO) AS DATA_CADASTRO,
CFOP.CODIGOCFOP AS CF,
LEFT (CFOP.CODIGOCFOP,3) AS ELO,
CST.CODIGOTRIBUTARIO AS ST,
UNIDADE.DESCRICAO AS UND,
ESTOQUESALDO.QUANTIDADE AS QTD,
CATEGORIA.NOME AS GRUPO,
SUBCATEGORIA.NOME AS FAMILIA,
NCM.CODIGO AS COD_NCM,
CEST.CEST AS PERSONAL6,
FORNECEDOR.RAZAO_SOCIAL AS FORNECEDOR,
FABRICANTE.NOME AS PERSONAL2
FROM PRODUTO
LEFT JOIN CST ON PRODUTO.ID_CST=CST.ID
LEFT JOIN NCM ON PRODUTO.`ID_NCM`=NCM.ID
LEFT JOIN CEST ON PRODUTO.`ID_CEST`=CEST.ID
LEFT JOIN CATEGORIA ON PRODUTO.ID_CATEGORIA = CATEGORIA.ID
LEFT JOIN SUBCATEGORIA ON PRODUTO.ID_CATEGORIA = SUBCATEGORIA.ID AND SUBCATEGORIA.ID_CATEGORIA = CATEGORIA.ID
LEFT JOIN FORNECEDOR ON FORNECEDOR.ID = PRODUTO.ID_FORNECEDOR 
LEFT JOIN UNIDADE ON UNIDADE.`ID` = PRODUTO.ID_UNIDADE
LEFT JOIN ESTOQUESALDO ON ESTOQUESALDO.ID_PRODUTO = PRODUTO.ID 
LEFT JOIN CFOP ON CFOP.ID = PRODUTO.ID_CFOP 
LEFT JOIN FABRICANTE ON FABRICANTE.ID = PRODUTO.ID_FABRICANTE 
