SELECT 
  -- CONTAMOVIMENTO.ID_CONTABANCARIA AS CONTA_BANCARIA_ID,
  cliente.ID AS COD_CLIENTE,
  cliente.NOME AS NOME_CLIENTE,
  cliente.cpf_cnpj AS CNPJ,
  RECEBER.tipo AS ESPECIE,
  RECEBER.status AS TIPO_DOC,
  CONCAT (RECEBER.ID, '-',RECEBER.documento) AS DOCUMENTO,
  RECEBER.lancamento AS EMISSAO,
  RECEBER.vencimento AS VENCIMENTO,
  '1' AS NUM_PARCELA,
  RECEBER.valor_original AS VALOR_DUP,
  RECEBER.valor_rec AS VALOR_REC,
  RECEBER.data_rec AS RECEBIMENTO,
  RECEBER.juros_rec AS VALOR_JUR,
  RECEBER.valor_desconto AS VALOR_DES,
  CONTABANCARIA.BANCO AS PORTADOR,
  CONTABANCARIA.agencia AS AGENCIA,
  CONTABANCARIA.CONTA AS CONTA,
  CONTABANCARIA.CONTA AS NUM_CONTA,
  NULL AS COMP,
  NULL  CTO_CUSTO,
  RECEBER.historico AS HISTORICO,
  RECEBER.obs AS OBSERVACOES
FROM RECEBER
LEFT JOIN CLIENTE ON CLIENTE.ID = RECEBER.ID_CLIENTE
LEFT JOIN CONTAMOVIMENTO ON CONTAMOVIMENTO.ID = RECEBER.ID_CONTAMOVIMENTO
LEFT JOIN CONTABANCARIA ON CONTABANCARIA.ID = CONTAMOVIMENTO.ID_CONTABANCARIA  
ORDER BY `DOCUMENTO` ASC;
