SELECT
    CAD_PRODUTOS.ID AS CODIGO,  
    --CAD_PRODUTOS.GTIN_LINK AS BARRAS,
    CAD_PRODUTOS.GTIN AS BARRAS,
    CAD_PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    CAD_PRODUTOS.PRODUTO AS DESCRICAO,
    CAD_PRODUTOS.CARACTERISTICA AS CARACTERISTICAS,
    CAD_PRODUTOS.UNIDADE_COMERCIAL AS UND,
    CAD_PRODUTOS.PESO_LIQUIDO AS PESO,
    CAD_PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    CAD_PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    CAD_PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    CAD_PRODUTOS.PRECO_ATACADO AS PRECO_ATACADO,
    CAD_PRODUTOS.ESTOQUE_ATUAL AS QTD,
    CAD_PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    case when CAD_PRODUTOS.ICMS_CST = '' or CAD_PRODUTOS.ICMS_CST is null then CAD_PRODUTOS.ICMS_CSOSN else CAD_PRODUTOS.ICMS_CST END AS ST,
    CAD_PRODUTOS.OBSERVACAO AS OBSERVACOES,
    CAD_PRODUTOS.ULTIMA_ENTRADA AS ULTIMA_COMPRA,
    CAD_PRODUTOS.ULTIMA_SAIDA AS ULTIMA_VENDA,
    CAD_PRODUTOS.NCM AS COD_NCM,
    CAD_PRODUTOS.CEST AS PERSONAL6,
    CAD_GRUPO.grupo AS GRUPO,
    CAD_SUB_GRUPO.sub_grupo AS FAMILIA,
    CAD_PRODUTOS.DATA_INCLUSAO AS DATA_CADASTRO
 FROM CAD_PRODUTOS
 LEFT JOIN cad_grupo ON CAD_GRUPO.id =  CAD_PRODUTOS.ID_GRUPO
 LEFT JOIN CAD_SUB_GRUPO ON CAD_SUB_GRUPO.ID = CAD_PRODUTOS.ID_SUBGRUPO
