SELECT
    --PESSOA.CODPES AS CODIGO,
    PESSOA.NOMEPES AS NOME,
    PESSOA.ENDERECOPES AS ENDERECO,
    CIDADE.NOMECID AS CIDADE,
    PESSOA.BAIRROPES AS BAIRRO,
    PESSOA.FONEPES AS TELEFONE,
    PESSOA.EMAILNFPES AS EMAIL,
    PESSOA.CPFCNPJPES AS CNPJ_CNPF,
    PESSOA.RGIEPES AS IE_RG,
    PESSOA.DTNASCPES AS NASCIMENTO,
    PESSOA.DTCADASTROPES AS CADASTRO,
    PESSOA.CELULARPES AS CELULAR,
    PESSOA.NUMEROPES AS NUMERO,
    PESSOA.CEPPES AS CEP,
    PESSOA.COMPLEMENTOPES AS COMPLEMENTO,
    PESSOA.FAXPES AS FAX
FROM PESSOA
LEFT JOIN CIDADE ON PESSOA.CODCID = CIDADE.CODCID
WHERE FORNECEDOR = 'S'
