SELECT
    PRODUTO.CODPROD AS CODIGO,
    PRODUTO.NOMEPROD AS DESCRICAO,
    PRODUTO.CUSTOPROD AS PRECO_CUSTO,
    PRODUTO.REFERENCIAPROD AS COD_FABRICANTE,
    PRODUTO.SALDOATUAL AS QTD,
    NCM.NCM AS COD_NCM,
    UNIMED.UNIMED AS UND,
    PRODUTO.VLRVENDATABELAPADRAONOVA AS PRECO_VENDA,
    CEST.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN NCM ON PRODUTO.CODNCM = NCM.CODNCM
LEFT JOIN CEST ON PRODUTO.CODCEST = CEST.CODCEST
LEFT JOIN UNIMED ON PRODUTO.CODUNIMED = UNIMED.CODUNIMED
