SELECT
    CDFORNECEDOR AS CODIGO,
    RAZAOSOCIAL AS NOME,
    NOMEFANTASIA AS FANTASIA,
    CONTATO1 AS CONTATO,
    CGC AS CNPJ_CNPF,
    INSCRICAOESTADUAL AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR