SELECT PESSOAS.COD_PESSOA AS CODIGO,
MUNICIPIOS.NOME_MUNIC AS CIDADE,
MUNICIPIOS.UF,
PESSOAS.RAZAO_SOCIAL AS NOME,
PESSOAS.NOME_FANTASIA AS FANTASIA,
PESSOAS.CNPJ_CPF AS CNPJ_CNPF,
PESSOAS.DATA_CADASTRO AS CADASTRO,
PESSOAS.INSCR_ESTADUAL AS IE_RG,
PESSOAS.EMAIL,
PESSOAS_ENDERECOS.ENDERECO,
PESSOAS_ENDERECOS.NUMERO,
PESSOAS_ENDERECOS.COMPLEMENTO,
PESSOAS_ENDERECOS.BAIRRO,
PESSOAS_ENDERECOS.CEP,
PESSOAS_ENDERECOS.TELEFONE,
PESSOAS_ENDERECOS.FAX,
PESSOAS_ENDERECOS.CELULAR
FROM PESSOAS
LEFT JOIN PESSOAS_ENDERECOS ON PESSOAS.COD_PESSOA=PESSOAS_ENDERECOS.COD_PESSOA
LEFT JOIN MUNICIPIOS ON PESSOAS_ENDERECOS.COD_MUNIC=MUNICIPIOS.COD_MUNIC
WHERE PESSOAS.FLAG_FORNECEDOR=1
