SELECT
PRODUTOS.cod_produto AS COD_FABRICANTE,
PRODUTOS.DESC_PRODUTO AS DESCRICAO,
PRODUTOS.COD_CLASS AS COD_NCM,
CASE WHEN PRODUTOS.COD_IMPOSTO=1 THEN '102' WHEN PRODUTOS.COD_IMPOSTO=2 THEN '500' ELSE '102' END AS ST,
PRODUTOS.COD_CEST AS PERSONAL6,
PRODUTOS_CUSTO.PRECO_CUSTO,
PRODUTOS_SALDOS.ESTOQUE AS QTD,
PRODUTOS_TAB_PRECOS_PROD.PRECO AS PRECO_VENDA,
GRUPOS_PRODUTO.DESC_GRUPO AS GRUPO,
MAX(produtos_apelidos_prod.apelido) AS BARRAS
FROM PRODUTOS
LEFT JOIN  PRODUTOS_TAB_PRECOS_PROD ON (PRODUTOS.COD_PRODUTO=PRODUTOS_TAB_PRECOS_PROD.COD_PRODUTO)AND PRODUTOS_TAB_PRECOS_PROD.COD_TABELA='2'
LEFT JOIN GRUPOS_PRODUTO ON PRODUTOS.COD_GRUPO=GRUPOS_PRODUTO.COD_GRUPO
LEFT JOIN PRODUTOS_CUSTO ON PRODUTOS.COD_PRODUTO=PRODUTOS_CUSTO.COD_PRODUTO
LEFT JOIN PRODUTOS_SALDOS ON PRODUTOS.COD_PRODUTO=PRODUTOS_SALDOS.COD_PRODUTO
LEFT JOIN produtos_apelidos_PROD ON PRODUTOS.COD_PRODUTO=produtos_apelidos_prod.cod_produto
GROUP BY 1,2,3,4,5,6,7,8,9
