SELECT
    CLIENTE.idcliente AS CÓDIGO,
    CLIENTE.nome AS NOME,
    CLIENTE.endereco AS ENDERECO,
    CLIENTE.numero AS NUMERO,
    CLIENTE.complemento AS COMPLEMENTO,
    CLIENTE.bairro AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.FKESTADO AS UF,
    CLIENTE.cep AS CEP,
    CLIENTE.cnpj_cpf AS CNPJ_CNPF,
    CLIENTE.ie_rg AS IE_RG,
    CLIENTE.telefone AS TELEFONE,
    CLIENTE.fax AS FAX,
    CLIENTE.celular AS CELULAR,
    CLIENTE.e_mail AS EMAIL,
    CLIENTE.data_cadastro AS CADASTRO,
    CLIENTE.sexo AS SEXO,
    CLIENTE.observacao AS OBSERVACOES,
    CLIENTE.limite_compra AS LIMITE_CREDITO,
    CLIENTE.inscricao_municipal AS IM,
    CLIENTE.contato AS CONTATO
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.IDCIDADE = CLIENTE.FKCIDADE
