SELECT
    FORNECEDOR.idfornecedor AS CODIGO,
    FORNECEDOR.nome AS FANTASIA,
    FORNECEDOR.razao_social AS NOME,
    FORNECEDOR.endereco AS ENDERECO,
    FORNECEDOR.numero AS NUMERO,
    FORNECEDOR.complemento AS COMPLEMENTO,
    CIDADE.NOME AS CIDADE,
    CIDADE.FKESTADO AS UF,
    FORNECEDOR.telefone AS TELEFONE,
    FORNECEDOR.fax AS FAX,
    FORNECEDOR.celular AS CELULAR,
    FORNECEDOR.e_mail AS EMAIL,
    FORNECEDOR.contato AS CONTATO,
    FORNECEDOR.cnpj_cpf AS CNPJ_CNPF,
    FORNECEDOR.ie_rg AS IE_RG,
    FORNECEDOR.observacao AS OBSERVACOES,
    FORNECEDOR.cep AS CEP,
    FORNECEDOR.bairro AS BAIRRO
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.IDCIDADE = FORNECEDOR.FKCIDADE
