SELECT FORNECEDORES.CODIGO,
FORNECEDORES.RAZAO AS NOME,
FORNECEDORES.FANTASIA,
FORNECEDORES.ENDERECO,
FORNECEDORES.NUMERO,
FORNECEDORES.BAIRRO,
FORNECEDORES.CNPJCPF AS CNPJ_CNPF,
FORNECEDORES.IERG AS IE_RG,
MUNICIPIOS.NOME AS CIDADE,
FORNECEDORES.UF,
FORNECEDORES.DDDFONE||FORNECEDORES.FONE AS TELEFONE,
FORNECEDORES.DDDCEL||FORNECEDORES.CEL AS CELULAR,
FORNECEDORES.CEP,
FORNECEDORES.DDDFAX||FORNECEDORES.FAX AS FAX,
FORNECEDORES.EMAIL,
FORNECEDORES.COMPENDERECO AS COMPLEMENTO
FROM FORNECEDORES
LEFT JOIN MUNICIPIOS ON FORNECEDORES.MUNICIPIO=MUNICIPIOS.CODIGOIBGE

