SELECT PRODUTOS.CODIGO,
PRODUTOS.CODBAR AS BARRAS,
PRODUTOS.DESCR AS DESCRICAO,
PRODUTOS.UNID AS UND,
PRODUTOS.REFERENCIA AS COD_FABRICANTE,
PRODUTOS.PRCCUS AS PRECO_CUSTO,
PRODUTOS.PRCVEN AS PRECO_VENDA,
PRODUTOS.ESTFIS AS QTD,
PRODUTOS.ESTMIN AS QTD_IDEAL,
PRODUTOS.DTALT AS ALTERACAO_PRECO,
PRODUTOS.DTCAD AS DATA_CADASTRO,
GRUPOS.DESCR AS GRUPO,
PRODUTOS.CODNCM AS COD_NCM,
PRODUTOS.OBSERV AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.CODGRU=GRUPOS.CODIGO


