SELECT
    CLIENTES.RAZSOC AS NOME,
    CLIENTES.NOMFANT AS FANTASIA,
    CLIENTES.NUMERO AS CNPJ_CNPF,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.BAIRRO AS BAIRRO,
    CLIENTES.CID AS CIDADE,
    CLIENTES.CEP AS CEP,
    CLIENTES.EST AS UF,
    CLITELF.DDD ||''|| CLITELF.FONE AS TELEFONE,
    CLITELC.DDD ||''|| CLITELC.FONE AS CELULAR,
    CLIENTES.FAX AS FAX,
    CLIENTES.OBS AS OBSERVACOES,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.LIMITECREDITO AS LIMITE_CREDITO,
    CLIENTES.DTCAD AS CADASTRO,
    CLIENTES.DTULTCP AS ULTIMA_COMPRA
FROM CLIENTES
LEFT JOIN CLITEL CLITELF ON CLIENTES.NUMERO = CLITELF.NUMEROCLI AND CLITELF.TIPO = 'F'
LEFT JOIN CLITEL CLITELC ON CLIENTES.NUMERO = CLITELC.NUMEROCLI AND CLITELC.TIPO = 'C'
