SELECT 
  E.ID_ENTIDADE AS CODIGO
, E.NOMEENTIDADE AS NOME
, E.RAZAOSOCIALENTIDADE AS FANTASIA
, E.ENDERECO
, E.NUMERO
, E.BAIRRO
, E.CEP
, E.CNPJCPF AS CNPJ_CNPF
, E.IERG AS IE_RG
, E.FONE AS TELEFONE
, E.CELULAR
, E.FAX
, E.EMAIL
, E.CONTATO
, E.OBS AS OBSERVACOES
, C.NOMECIDADE AS CIDADE 
, C.UF 
FROM ENTIDADES E
LEFT JOIN CIDADES C ON C.ID_CIDADES = E.ID_CIDADES
WHERE E.CLIENTE_FORNECEDOR = 1
