SELECT
  CLIFOR.RAZAOSOCIAL AS NOME,
  CLIFOR.N_FANTASIA AS FANTASIA,
  CLIFOR.CNPJ AS CNPJ_CNPF,
  CLIFOR.INSCESTADUAL AS IE_RG,
  CLIFOR.EMAIL AS EMAIL,
  ENDERECOS.LOGRADOURO AS ENDERECO,
  ENDERECOS.BAIRRO AS BAIRRO,
  ENDERECOS.UF AS UF,
  ENDERECOS.CEP AS CEP,
  ENDERECOS.OBSEND AS OBSERVACOES,
  TELEFONES.FONE AS TELEFONE,
  BAIRROS.DESCRI_BAIRRO AS BAIRRO,
  CIDADES.DESCRI_CIDADE AS CIDADE
FROM CLIFOR
LEFT JOIN ENDERECOS ON ENDERECOS.CODCLIFOR = CLIFOR.CODCHAVECLIFOR
LEFT JOIN TELEFONES ON TELEFONES.CODCLIFOR = CLIFOR.CODCHAVECLIFOR
LEFT JOIN BAIRROS ON BAIRROS.CODBAIRRO = ENDERECOS.CODBAIRRO
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = ENDERECOS.CODCIDADE
WHERE CLIFOR.CATEGORIA = 'F'
