SELECT
  PRODUTO_FINAL.CODPRODUTOFINAL AS CODIGO,
  PRODUTO_FINAL.DESCRICAO AS DESCRICAO,
  PRODUTO_GRUPO.DESCRICAO_GRUPO_PROD AS GRUPO,
  PRODUTO_FINAL.PRECO_VENDA AS PRECO_VENDA,
  PRODUTO_FINAL.CUSTO AS PRECO_CUSTO,
  PRODUTO_FINAL.DESCRICAO_RESUMIDA AS CARACTERISTICAS,
  PRODUTO_FINAL.CODBARRA AS BARRAS,
  UNIDADES.DESCRICAO AS UND
--  PRODUTO_FINAL.NCM AS COD_NCM,
--  PRODUTO_FINAL.SITTRIB AS ST,
--  PRODUTO_FINAL.CEST AS PERSONAL6
FROM PRODUTO_FINAL
LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.CODINTERNOPRODGRUPO = PRODUTO_FINAL.CODGRUPO
LEFT JOIN UNIDADES ON UNIDADES.CODINTERNOUNIDADE = PRODUTO_FINAL.UNIDADE_PF
