SELECT
PRODUTOS.CODIGO,
PRODUTOS.REFERENCIA AS COD_FABRICANTE,
PRODUTOS.DESCRICAO,
GRUPOS.NOME_GRUPO AS GRUPO,
SUBGRUPO.NOMESUBGRUPO AS FAMILIA,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.PRCUSTO AS PRECO_CUSTO,
PRODUTOS.MARCA AS CARACTERISITICAS,
PRODUTOS.PRVENDA AS PRECO_VENDA,
PRODUTOS.SITUACAO_TRIBUTARIA AS ST,
PRODUTOS.IPI AS ALIQ_IPI_VENDA,
PRODUTOS.codigo_barra AS BARRAS,
--case when PRODUTOS.CODIGO_BARRA = '' or PRODUTOS.CODIGO_BARRA is null then PRODUTOS.REFERENCIA else PRODUTOS.CODIGO_BARRA END AS BARRAS,
PRODUTOS.DT_CADASTRO AS CADASTRO,
PRODUTOS.CODIGONCM AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6,
ESTOQUE.ESTOQUE AS QTD
FROM PRODUTOS
LEFT JOIN ESTOQUE ON PRODUTOS.CODIGO=ESTOQUE.CODIGO AND ESTOQUE.CODLOJA = '1'
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO=GRUPOS.GRUPO 
LEFT JOIN SUBGRUPO ON PRODUTOS.SUBGRUPO=SUBGRUPO.SUBGRUPO 
WHERE PRODUTOS.DESCRICAO IS NULL OR PRODUTOS.DESCRICAO <> ''
