SELECT
    CPAGAR.CODIGO AS DOCUMENTO,
    CPAGAR.DATA AS EMISSAO,
    CPAGAR.FKFORNECE AS COD_FORNECEDOR,
    PESSOA.RAZAO AS NOM_FORNECEDOR,
    CPAGAR.DOC AS TIPO_DOC,
    CPAGAR.VALOR AS VALOR_DUP,
    CPAGAR.DTVENCIMENTO AS VENCIMENTO,
    CPAGAR.HISTORICO AS HISTORICO,
    CPAGAR.DATA_PAGAMENTO AS PAGAMENTO,
    CPAGAR.DESCONTO AS VALOR_DES,
    CPAGAR.JUROS AS VALOR_JUR,
    CPAGAR.VLPAGO AS VALOR_PAG,
    PESSOA.cnpj
FROM CPAGAR
LEFT JOIN PESSOA ON CPAGAR.FKFORNECE = PESSOA.codigo
