SELECT
    CRECEBER.CODIGO AS DOCUMENTO,
    CRECEBER.DATA AS EMISSAO,
    CRECEBER.FKCLIENTE AS COD_CLIENTE,
    PESSOA.razao AS NOM_CLIENTE,
    CRECEBER.DOC AS TIPO_DOC,
    CRECEBER.VALOR AS VALOR_DUP,
    CRECEBER.DTVENCIMENTO AS VENCIMENTO,
    CRECEBER.HISTORICO,
    CRECEBER.DATA_RECEBIMENTO AS RECEBIMENTO,
    CRECEBER.DESCONTO AS VALOR_DES,
    CRECEBER.JUROS AS VALOR_JUR,
    CRECEBER.VRECEBIDO AS VALOR_REC,
    PESSOA.CNPJ
FROM CRECEBER
LEFT JOIN PESSOA ON CRECEBER.FKCLIENTE = PESSOA.codigo
WHERE PESSOA.razao IS NOT NULL AND CRECEBER.FKCLIENTE <> '0'
