SELECT
       PRODUTOS.CODIGO AS COD_FABRICANTE
      ,PRODUTOS.NOME AS DESCRICAO
      ,GRUPOS.NOME AS GRUPO
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.APLICACAO AS CARACTERISTICAS
      ,PRODUTOS.CBARRA AS BARRAS
      ,PRODUTOS.PESO_LIQ AS PESO
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.DATA_ALTERACAO AS ALTERACAO_PRECO
      ,PRODUTOS.COD_CEST AS COD_CEST
      ,CADFOR.NOME AS FORNECEDOR
      ,PRODLOJAS.EST_MINIM AS QTD_IDEAL
      ,PRODLOJAS.EST_ATUAL AS QTD
      ,PRODLOJAS.PCO_COMPRA AS PRECO_CUSTO
      ,PRODLOJAS.PCO_VENDA AS PRECO_VENDA
  FROM GERECIAL.dbo.PRODUTOS
LEFT JOIN GERECIAL.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = GERECIAL.dbo.PRODUTOS.CODIGO
LEFT JOIN GERECIAL.dbo.GRUPOS ON GRUPOS.CODIGO = GERECIAL.dbo.PRODUTOS.GRUPO
LEFT JOIN GERECIAL.dbo.CADFOR ON CADFOR.CODIGO = GERECIAL.dbo.PRODLOJAS.FORNECEDOR
