SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.COD_BARRA AS BARRAS,
    PRODUTO.DESCRICAO AS DESCRICAO,
    CATEGORIA_PROD.CATEGORIA AS GRUPO,
    FABRICANTE.NOME AS CARACTERISTICAS,
    FORNECEDOR.RAZAO_SOCIAL AS FORNECEDOR,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.VALOR_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.VALOR_VENDA AS PRECO_VENDA,
    PRODUTO.U_MEDIDA AS UND,
    PRODUTO.ULT_COMPRA AS ULTIMA_COMPRA,
    PRODUTO.ULT_VENDA AS ULTIMA_VENDA,
    PRODUTO.VALOR_ATACADO AS PRECO_ATACADO,
    PRODUTO.ESTOQUE AS QTD,
    PRODUTO.EST_MINIMO AS QTD_IDEAL,
    PRODUTO.DT_ALTERACAO AS ALTERACAO_PRECO,
    PRODUTO.OBS AS OBSERVACOES
FROM PRODUTO
LEFT JOIN CATEGORIA_PROD ON CATEGORIA_PROD.CODIGO = PRODUTO.COD_CATEGORIA
LEFT JOIN FABRICANTE ON FABRICANTE.CODIGO = PRODUTO.COD_FABRICANTE
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTO.COD_FORNECEDOR