SELECT
    CLIENTES.CODCLI AS CODIGO,
    CLIENTES.NOMCLI AS NOME,
    CLIENTES.FANTASIA AS FANTASIA,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.NUMERO AS NUMERO,
    BAIRROS.NOMBAI AS BAIRRO,
    CLIENTES.CEP AS CEP,
    CIDADES.NOMCID AS CIDADE,
    CIDADES.UF AS UF,
    CLIENTES.FONE AS TELEFONE,
    CLIENTES.CELULAR AS CELULAR,
    CLIENTES.FAX AS FAX,
    case when CLIENTES.CPF = '' or CLIENTES.CPF is null then CLIENTES.CNPJ else CLIENTES.CPF END AS CNPJ_CNPF,
    case when CLIENTES.RG = '' or CLIENTES.RG is null then CLIENTES.IE else CLIENTES.RG END AS IE_RG,
    CLIENTES.CONTATO AS CONTATO,
    CLIENTES.CADASTRO AS CADASTRO,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.DATNAS AS NASCIMENTO,
    CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.PAI AS PAI,
    CLIENTES.MAE AS MAE,
    CLIENTES.OBS1 AS OBSERVACOES,
    CLIENTES.LIMITE AS LIMITE_CREDITO,
    CLIENTES.IM AS IM
FROM CLIENTES
LEFT JOIN BAIRROS ON BAIRROS.CODBAI = CLIENTES.CODBAI
LEFT JOIN CIDADES ON CIDADES.CODCID = CLIENTES.CODCID
