SELECT
       PRODUTOS.PK AS CODIGO
      ,PRODUTOS.DESCRICAO AS DESCRICAO
      ,PRODUTOS.CODIGO_BARRA AS BARRAS
      ,FORNECEDORES.RAZAO_SOCIAL AS FORNECEDOR
      ,PRODUTOS.PESO AS PESO
      ,PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL
      ,PRODUTOS.ESTOQUE AS QTD
      ,PRODUTOS.UNIDADE AS UND
      ,GRUPOS.DESCRICAO AS GRUPO
      ,GRUPOS.DESCRICAO AS FAMILIA
      ,PRODUTOS.PRECO_COMPRA AS PRECO_COMPRA
      ,PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO
      ,PRODUTOS.PRECO_VENDA AS PRECO_VENDA
      ,PRODUTOS.CST AS ST
      ,PRODUTOS.OBS AS OBSERVACOES
      ,PRODUTOS.NCM AS COD_NCM
      ,PRODUTOS.REFERENCIA AS COD_FABRICANTE
      ,PRODUTOS.CEST AS PERSONAL6
      ,PRODUTOS.MARCA AS CARACTERISTICAS
      ,PRODUTOS.DATA_CADASTRO AS CADASTRO
  FROM JJ_CONTRUCOES.dbo.PRODUTOS
LEFT JOIN JJ_CONTRUCOES.dbo.GRUPOS ON GRUPOS.PK = PRODUTOS.FK_GRUPO
LEFT JOIN JJ_CONTRUCOES.dbo.SUBGRUPOS ON SUBGRUPOS.PK = PRODUTOS.FK_SUBGRUPO
LEFT JOIN JJ_CONTRUCOES.dbo.FORNECEDORES ON FORNECEDORES.PK = PRODUTOS.FK_FORNECEDOR
