  SELECT
  CLIENTE.NOME AS NOME,
  CLIENTE.CPFCNPJ AS CNPJ_CNPF,
  ENDERECO.LOGRADOURO AS ENDERECO,
  ENDERECO.NUMERO AS NUMERO,
  ENDERECO.COMPLEMENTO AS COMPLEMENTO,
  ENDERECO.BAIRRO AS BAIRRO,
  ENDERECO.MUNICIPIO AS CIDADE,
  ENDERECO.UF AS UF,
  ENDERECO.CEP AS CEP,
  CLIENTE.EMAIL AS EMAIL,
  CLIENTE.IE AS IE_RG,
  CLIENTE.OBS AS OBSERVACOES
FROM CLIENTE
LEFT JOIN ENDERECO ON ENDERECO.ID = CLIENTE.IDCLIENTE
