SELECT
    CADASTRO.ID_CADASTRO AS CODIGO,
    CADASTRO.CADASTRO_,
    CADASTRO.RAZAO AS NOME,
    CADASTRO.FANTASIA AS FANTASIA,
    CADASTRO.CONTATO AS CONTATO,
    CADASTRO.CGC AS CNPJ_CNPF,
    CADASTRO.IE AS IE_RG,
    CADASTRO.ENDER AS ENDERECO,
    CADASTRO.NUMERO AS NUMERO,
    CADASTRO.BAIRRO AS BAIRRO,
    CADASTRO.COMPLE AS COMPLEMENTO,
    CADASTRO.CEP AS CEP,
    CADASTRO.CIDADE AS CIDADE,
    CADASTRO.UF AS UF,
    CADASTRO.FONE AS TELEFONE,
    CADASTRO.CELULAR AS CELULAR,
    CADASTRO.FAX AS FAX,
    CADASTRO.EMAIL AS EMAIL,
    CADASTRO.OBS AS OBSERVACOES,
    CADASTRO.CIVIL AS EST_CIVIL,
    CADASTRO.CREDITO AS LIMITE_CREDITO,
    CADASTRO.DATA_NASC AS NASCIMENTO,
    CADASTRO.ULTIMA_COMPRA AS ULTIMA_COMPRA,
    case CADASTRO.prod_rural when 1 then 'PRODUTOR RURAL' when 0 then '' end as PROFISSAO,
    case CADASTRO.ativo when 1 then 'Ativo' when 0 then 'Inativo' end as SITUACAO
    --CADASTRO.CADASTRO AS CADASTRO
FROM CADASTRO
WHERE CADASTRO.CADASTRO_ is null or CADASTRO.CADASTRO_ = 'Cliente' or CADASTRO.CADASTRO_ = '' or CADASTRO.CADASTRO_ = 'Cliente/Fornecedor'
