SELECT
    PESSOAS.IDPESSOA AS CODIGO,
    PESSOAS.NOME AS NOME,
    PESSOAS.FANTASIA AS FANTASIA,
    PESSOAS.CNPJCPF AS CNPJ_CNPF,
    case when PESSOAS.RG = '' or PESSOAS.RG is null then PESSOAS.INSCR_EST else PESSOAS.RG END AS IE_RG,
    PESSOAS.INSCR_MUN AS IM,
    PESSOAS.FONE1 AS TELEFONE,
    PESSOAS.CELULAR AS CELULAR,
    PESSOAS.FAX AS FAX,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.PRI_ENDERECO AS ENDERECO,
    PESSOAS.PRI_COMPLEMENTO AS COMPLEMENTO,
    PESSOAS.PRI_CEP AS CEP,
    CIDADES.DESCRICAO AS CIDADE,
    CIDADES.UF AS uf, 
    PESSOAS.PRI_BAIRRO AS BAIRRO,
    PESSOAS.NOMEPAI AS PAI,
    PESSOAS.NOMEMAE AS MAE,
    PESSOAS.ESTADOCIVIL AS EST_CIVIL,
    PESSOAS.NOMECONJUGE AS CONJUGE,
    PESSOAS.SEXO AS SEXO,
    PESSOAS.DATANASCIMENTO AS NASCIMENTO,
    PESSOAS.DATA_ULT_COMPRA AS ULTIMA_COMPRA
    --PESSOAS.DATACADASTRO AS CADASTRO
FROM PESSOAS
LEFT JOIN CIDADES ON CIDADES.idcidade = PESSOAS.PRI_CIDADE
WHERE IDTIPO_PS = '1'   --CLIENTES
