SELECT
    FORNECEDOR.codfornecedor AS CODIGO,
    FORNECEDOR.nome,
    FORNECEDOR.endereco,
    FORNECEDOR.complemento,
    FORNECEDOR.cep,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    FORNECEDOR.cgccpf AS CNPJ_CNPF,
    FORNECEDOR.inscricaoestadual AS IE_RG,
    FORNECEDOR.fone AS TELEFONE,
    FORNECEDOR.bairro,
    FORNECEDOR.numero
FROM FORNECEDOR
LEFT JOIN CIDADE ON FORNECEDOR.CODCIDADE = CIDADE.CODCIDADE
WHERE FORNECEDOR.CODFORNECEDOR > 0
