SELECT CLIENTEFORN.COD_CLIENTE AS CODIGO,
CLIENTEFORN.RAZAOSOCIAL AS NOME,
CLIENTEFORN.NOMEFANT AS FANTASIA,
CLIENTEFORN.CNPJCPF AS CNPJ_CNPF,
CLIENTEFORN.DTCAD AS CADASTRO,
CLIENTEFORN.OBS AS OBSERVACOES,
CLIENTEFORN.FIL_NOME_PAI AS PAI,
CLIENTEFORN.FIL_NOME_MAE AS MAE,
ENDERECOGERAL.INSCESTF AS IE_RG,
ENDERECOGERAL.COMPLEMENTO,
ENDERECOGERAL.NUMERO,
ENDERECOGERAL.FONE1 as telefone,
ENDERECOGERAL.FAX,
ENDERECOGERAL.CELULAR,
ENDERECOGERAL.EMAIL,
ENDERECOGERAL.CONTATO,
MUNICIPIO.DESCRIC_MUN as cidade,
ESTADO.UF_EST as uf,
LOGRADOURO.DESCRICAO as endereco,
BAIRRO.DESCRICAO as bairro
from CLIENTEFORN
LEFT JOIN ENDERECOGERAL ON (CLIENTEFORN.COD_CLIENTE=ENDERECOGERAL.COD_ENDCAD1 and ENDERECOGERAL.TIPOEND='N')
LEFT JOIN MUNICIPIO ON ENDERECOGERAL.COD_MUNICIPIO=MUNICIPIO.COD_MUNICIPIO
left JOIN ESTADO ON MUNICIPIO.COD_EST=ESTADO.COD_EST
LEFT JOIN LOGRADOURO ON (ENDERECOGERAL.COD_LOGRADOURO=LOGRADOURO.COD_LOGRADOURO and ENDERECOGERAL.COD_BAIRRO=LOGRADOURO.COD_BAIRRO)
LEFT JOIN BAIRRO ON ENDERECOGERAL.COD_BAIRRO=BAIRRO.COD_BAIRRO
where CLIENTEFORN.TIPOCAD='C'



