SELECT
    CODIGO AS CODIGO,
    REFERENCIA,
    DESCRICAO AS DESCRICAO,
    CODBARRA AS BARRAS,
    UNIDADE AS UND,
    PESOLIQ AS PESO,
    ESTOQUE AS QTD,
    MINIMO AS QTD_IDEAL,
    PRECOVENDA AS PRECO_VENDA,
    --CST
    CSOSN AS ST,
    NCM AS COD_NCM,
    CODFABR AS COD_FABRICANTE,
    CAST(ULTIMAENTRADA AS DATE) AS ULTIMA_COMPRA,
    CAST(ULTIMASAIDA AS DATE) AS ULTIMA_VENDA,
    CAST(DATAMANUT AS DATE) AS ALTERACAO_PRECO
FROM PRODUTOS