SELECT
    NOME AS FANTASIA,
    RAZAO AS NOME,
    ENDERECO,
    BAIRRO,
    CIDADE,
    UF,
    CPF_CGC AS CNPJ_CNPF,
    RG_INSC AS IE_RG,
    TEL01 AS TELEFONE,
    TEL02 AS CELULAR,
    CEP,
    EMAIL
FROM CLIENTES 