SELECT
    NOME AS FANTASIA,
    RAZAO AS NOME,
    ENDERECO,
    BAIRRO,
    ESTADO AS UF,
    CEP,
    CGC AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    TEL_01 AS TELEFONE,
    TEL_02 AS CELULAR,
    CONTATO,
    CIDADE
FROM FORNEC