SELECT
    ID_PRODUTO AS CODIGO,
    CODIGO AS BARRAS,
    DESCRICAO AS DESCRICAO,
    NOMEFOR AS FORNECEDOR,
    DESCGRUPO AS GRUPO,
    QUANT AS QTD,
    CUSTO AS PRECO_CUSTO,
    VENDA AS PRECO_VENDA,
    UNIDADE AS UND,
    NOMEMARCA AS FAMILIA,
    NCM AS COD_NCM,
    CEST AS PERSONAL6,
    ST_CRT_SAIDA AS ST
FROM ESTOQUE