SELECT
    IDCLIENTE AS CODIGO,
    NOME AS NOME,
    APELIDO AS FANTASIA,
    PESSOACONTATO AS CONTATO,
    FONEPESSOA AS TELEFONE,
    FONECEL AS CELULAR,
    CPF AS CNPJ_CNPF,
    RG AS IE_RG,
    EMAIL AS EMAIL,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CEP AS CEP,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    DATACAD AS CADASTRO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO
FROM CLIENTES
