SELECT
    IDFORNECE AS CODIGO,
    RAZAOSOCIAL AS NOME,
    NOMEFANTASIA AS FANTASIA,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    END1 AS ENDERECO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    FONE AS TELEFONE,
    FAX AS FAX,
    PESSOACONT AS CONTATO,
    EMAIL AS EMAIL,
    BAIRRO AS BAIRRO,
    CEL AS CELULAR
FROM FORNECEDORES
