SELECT
	CODCLI AS CODIGO,
	NOMCLI AS NOME,
	ENDCLI AS ENDERECO,
	NUMERO AS NUMERO,
	BAICLI AS BAIRRO,
	MUNICIPIOS.NM_MUNICIPIO AS CIDADE, 
	UNIDADES_FEDERAIS.NM_SIGLA AS UF,
	CEPCLI AS CEP,
	FONCLI AS TELEFONE,
	CONCLI AS CONTATO,
	CASE WHEN CLIENTE.CGCCLI ='' THEN CLIENTE.CPFCLI ELSE CLIENTE.CGCCLI END AS CNPJ_CNPF,
	CASE WHEN CLIENTE.INSCLI ='' THEN CLIENTE.IDECLI ELSE CLIENTE.INSCLI END AS IE_RG,
	--DATCAD AS CADASTRO,
	OBSCLI AS OBSERVACOES,
	FAXCLI AS FAX,
	EMACLI AS EMAIL,
	FANTASIA AS FANTASIA,
	PAI AS PAI,
	MAE AS MAE,
	CELULAR AS CELULAR,
	COMPLEMENTO AS COMPLEMENTO
FROM CLIENTE
LEFT JOIN MUNICIPIOS ON CLIENTE.CODMUNICIPIO = MUNICIPIOS.ID_MUNICIPIO 
LEFT JOIN UNIDADES_FEDERAIS ON MUNICIPIOS.ID_UF = UNIDADES_FEDERAIS.ID_UF 
