SELECT
    ID AS CODIGO,
    NOME,
    RG AS IE_RG,
    CPF AS CNPJ_CNPF,
    ENDERECO AS ENDERECO,
    NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO,
    CEP,
    CIDADE,
    UF AS UF,
    TELEFONE AS TELEFONE,
    CELULAR,
    EMAIL
FROM CLIENTES
