SELECT
    ITENS.CODIGO AS CODIGO,
    ITENS.COD_BARRA AS BARRAS,
    ITENS.DESCRICAO AS DESCRICAO,
    UNIDADES.ID AS UND,
    ITENS_ESTOQUE.ESTOQUE AS QTD,
    ITENS_ESTOQUE.EST_MIN AS QTD_IDEAL,
    ITENS_PRECOS.PRE_COMPRA AS PRECO_CUSTO,
    ITENS_PRECOS.PRE_MEDIO AS CUSTO_MEDIO,
    ITENS_PRECOS.MARGEM_VENDA AS MARGEM_LUCRO,
    ITENS_PRECOS.PRE_VENDA AS PRECO_VENDA,
    ITENS_PRECOS.PRE_ATACADO AS PRECO_ATACADO,
    ITENS.REFERENCIA AS COD_FABRICANTE,
    ITENS.INFORMACOES AS OBSERVACOES,
    ITENS_ESTOQUE.DATA_ULT_ENTRADA AS ULTIMA_COMPRA,
    ITENS_ESTOQUE.DATA_ULT_SAIDA AS ULTIMA_VENDA,
    ITENS.CADASTRO AS DATA_CADASTRO,
    ITENS.NCM AS COD_NCM,
    MAX (TAB_CEST.CEST) AS PERSONAL6,
    case when ITENS.ATIVO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO
FROM ITENS
LEFT JOIN ITENS_ESTOQUE ON ITENS_ESTOQUE.ITEM = ITENS.CODIGO
LEFT JOIN ITENS_PRECOS ON ITENS_PRECOS.ITEM = ITENS.CODIGO
LEFT JOIN UNIDADES ON UNIDADES.CODIGO = ITENS.UNIDADE
LEFT JOIN TAB_CEST ON TAB_CEST.NCM = ITENS.NCM
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19