SELECT CLIENTES.CODIGO,
CLIENTES.NOME,
CLIENTES.APELIDO AS FANTASIA,
CLIENTES.ENDERECO,
CLIENTES.BAIRRO,
CIDADES.NOME AS CIDADE,
CIDADES.ESTADO AS UF,
CLIENTES.CEP,
CLIENTES.CNPJCPF AS CNPJ_CNPF,
CLIENTES.INSCEST AS IE_RG,
CLIENTES.FONE AS TELEFONE,
CLIENTES.CELULAR,
CLIENTES.OBS AS OBSERVACOES,
CLIENTES.EMAIL,
CLIENTES.CONTATO,
CLIENTES.END_NUMERO AS NUMERO,
CLIENTES.COMPLEMENTO,
CLIENTES.ULTIMO_MOVIMENTO AS ULTIMA_VENDA
FROM CLIENTES
LEFT JOIN CIDADES ON CLIENTES.CIDADE=CIDADES.CODIGO


