SELECT
    CD_CLIFOR AS CODIGO,
    NM_CLIFOR AS NOME,
    NM_REDU AS FANTASIA,
    NM_ENDERECO AS ENDERECO,
    NM_BAIRRO AS BAIRRO,
    NR_CEP AS CEP,
    NM_CIDADE AS CIDADE,
    NM_UF AS UF,
    NR_FONE AS TELEFONE,
    NR_FAX AS FAX,
    NR_CGC AS CNPJ_CNPF,
    NR_INSCESTADUAL AS IE_RG,
    NM_CONTATO1 AS CONTATO,
    NR_CELULAR1 AS CELULAR,
    DT_CADASTRO AS CADASTRO,
    DS_EMAIL AS EMAIL,
    DS_NROENDERECO AS NUMERO
FROM CLIFOR
WHERE FL_TIPO <> 'C'
