SELECT 
       ITENS.ITEM AS CARACTERISTICAS
      ,min (ITENS_FORNECEDORES.CODIGO_ITEM_FORNECEDOR) AS COD_FABRICANTE
      ,ITENS.DESCRICAO AS DESCRICAO
      ,ITENS.CUSTO_MEDIO AS CUSTO_MEDIO
      ,ITENS.PRECO AS PRECO_VENDA
      ,ITENS.QTD_MINIMA AS QTD_IDEAL
      ,ITENS_FICHA.QTD AS QTD
      ,ITENS.GRUPO AS GRUPO
      ,ITENS.UNIDADE_VENDA AS UND
      ,ITENS.NCM AS COD_NCM
      ,ITENS.CSOSN AS ST
      ,ITENS.CEST AS PERSONAL6
  FROM DiegoAndinoReta.dbo.ITENS
left join DiegoAndinoReta.dbo.ITENS_FICHA on ITENS_FICHA.ITEM = ITENS.ITEM
LEFT JOIN DiegoAndinoReta.dbo.ITENS_FORNECEDORES ON ITENS_FORNECEDORES.ITEM = ITENS.ITEM
group by       
       ITENS.ITEM
      ,ITENS.DESCRICAO
      ,ITENS.CUSTO_MEDIO
      ,ITENS.PRECO
      ,ITENS.QTD_MINIMA
      ,ITENS_FICHA.QTD
      ,ITENS.GRUPO
      ,ITENS.UNIDADE_VENDA
      ,ITENS.NCM
      ,ITENS.CSOSN
      ,ITENS.CEST
