SELECT 
       CDPRODUTOS.CODPROD AS CODIGO
      ,CDPRODUTOS.CODBARRA AS BARRAS
      ,CDPRODUTOS.DTCADAST AS DATA_CADASTRO
      ,CDPRODUTOS.DESCRICAO AS DESCRICAO
      ,CDPRODUTOS.DESCRNF AS CARACTERISTICAS
      ,CDPRODUTOS.UNIDADE AS UND
      ,CDPRODUTOS.UNDCOMPRA AS UND_COMPRA
      ,CDPRODUTOS.CODFABRIC AS COD_FABRICANTE
      ,MAX (CDGRUPOS.GRUPO) AS GRUPO
      ,CDPRODUTOS.ESTOATU AS QTD
      ,CDPRODUTOS.PRECOCUSTO AS PRECO_CUSTO
      ,CDPRODUTOS.PRECOMED AS CUSTO_MEDIO
      ,CDPRODUTOS.PRECOVEND AS PRECO_VENDA
      ,CDTRIBUTACAO.SITTRIB AS ST
      ,CDPRODUTOS.OBS AS OBSERVACOES
      ,CDPRODUTOS.DTALTERPRECO AS ALTERACAO_PRECO
      ,CDPRODUTOS.ESTOIDEAL AS QTD_IDEAL
      ,CDPRODUTOS.PESO_LIQUIDO AS PESO
      ,CDNCM.CODNCM AS COD_NCM
      ,CDCEST.CODCEST AS PERSONAL6
  FROM dbsolus.dbo.CDPRODUTOS
  LEFT JOIN dbsolus.dbo.CDTRIBUTACAO ON CDTRIBUTACAO.CODTRIB = CDPRODUTOS.CODTRIB
  LEFT JOIN dbsolus.dbo.CDGRUPOS ON CDGRUPOS.CODGRUPO = CDPRODUTOS.CODGRUPO
  LEFT JOIN dbsolus.dbo.CDNCM ON CDNCM.IDNCM = CDPRODUTOS.IDNCM
  LEFT JOIN dbsolus.dbo.CDCEST ON CDCEST.CODCEST = CDPRODUTOS.ID_CEST
  GROUP BY        
       CDPRODUTOS.CODPROD
      ,CDPRODUTOS.CODBARRA
      ,CDPRODUTOS.DTCADAST
      ,CDPRODUTOS.DESCRICAO
      ,CDPRODUTOS.DESCRNF
      ,CDPRODUTOS.UNIDADE
      ,CDPRODUTOS.UNDCOMPRA
      ,CDPRODUTOS.CODFABRIC
      ,CDPRODUTOS.ESTOATU
      ,CDPRODUTOS.PRECOCUSTO
      ,CDPRODUTOS.PRECOMED
      ,CDPRODUTOS.PRECOVEND
      ,CDTRIBUTACAO.SITTRIB
      ,CDPRODUTOS.OBS
      ,CDPRODUTOS.DTALTERPRECO
      ,CDPRODUTOS.ESTOIDEAL
      ,CDPRODUTOS.PESO_LIQUIDO
      ,CDNCM.CODNCM
      ,CDCEST.CODCEST
