SELECT
	CLIFOR.ID AS CODIGO,
	CLIFOR.NOME AS NOME,
	M.DESCRICAO AS CIDADE,
	CLIFOR.BAIRRO AS BAIRRO,
	CLIFOR.ENDERECO AS ENDERECO,
	CLIFOR.UF AS UF,
	CLIFOR.CEP AS CEP,
	CLIFOR.FONE AS TELEFONE,
	CLIFOR.FAX AS FAX,
	CLIFOR.CNPJCPF AS CNPJ_CNPF,
	CASE WHEN CLIFOR.RG = '' OR CLIFOR.RG IS NULL THEN CLIFOR.IE ELSE CLIFOR.RG END AS IE_RG,
	CLIFOR.OBSERVACAO AS OBSERVACOES,
	CLIFOR.E_MAIL AS EMAIL,
	CLIFOR.CONTATO AS CONTATO,
	CLIFOR.NUMERO_END AS NUMERO,
	CLIFOR.COMPLEMENTO_END AS COMPLEMENTO,
	CLIFOR.CELULAR AS CELULAR
FROM CLIFOR
LEFT JOIN MUNICIPIOS M ON CLIFOR.MUNICIPIO = M.ID
WHERE CLIFOR.CF = 'F'