SELECT
	EST_MERCADORIAS.ID AS COD_FABRICANTE,
	EST_MERCADORIAS.DESCRICAO AS DESCRICAO,
	EST_MERCADORIAS.UNIDADE AS UND,
	EM.EST_ATUAL AS QTD,
	ES.DESCRICAO AS GRUPO,
	EST_MERCADORIAS.MARCA AS FAMILIA,
	CASE WHEN EST_MERCADORIAS.ATIVO = 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	EST_MERCADORIAS.PESO_LIQ AS PESO,
	EST_MERCADORIAS.CUSTO_ULTIMO AS PRECO_CUSTO,
	EST_MERCADORIAS.CUSTO_MEDIO AS CUSTO_MEDIO,
	EST_MERCADORIAS.VENDA AS PRECO_VENDA,
	EST_MERCADORIAS.MARGEM AS MARGEM_LUCRO,
	EST_MERCADORIAS.NCM AS COD_NCM,
	EST_MERCADORIAS.DT_VENDA AS ULTIMA_VENDA,
	EST_MERCADORIAS.DT_COMPRA AS ULTIMA_COMPRA,
	--EST_MERCADORIAS.FABRICANTE AS COD_FABRICANTE,
	EST_MERCADORIAS.GTIN AS BARRAS,
	EST_MERCADORIAS.CST_IPI AS IPI_CODIGO,
	EST_MERCADORIAS.CST_PIS AS PIS_CODIGO,
	EST_MERCADORIAS.CST_COFINS AS COFINS_CODIGO,
	EST_MERCADORIAS.TIPO_ITEM AS TIPO_ITEM,
	EST_MERCADORIAS.CEST AS PERSONAL6,
	EST_MERCADORIAS.OBSERVACAO AS OBSERVACOES,
	EST_MERCADORIAS.DT_CADASTRO AS DATA_CADASTRO
FROM EST_MERCADORIAS
LEFT JOIN EST_MERCADORIAS_ESTOQUE EM ON EST_MERCADORIAS.ID = EM.MERCADORIA
LEFT JOIN EST_SUBGRUPOS ES ON EST_MERCADORIAS.SUBGRUPO = ES.ID