SELECT
    PRODUTOS.COD_PROD AS CODIGO,
    PRODUTOS.COD_BARRA AS BARRAS,
    PRODUTOS.NOME_PROD AS DESCRICAO,
    MARCAS.descricao AS GRUPO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.PRECO_CUST AS PRECO_CUSTO,
    PRODUTOS.C_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VEND AS PRECO_VENDA,
    PRODUTOS.QUANT_MIN AS QTD_IDEAL,
    ESTOQUEFILIAL.quantidade AS QTD,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.SITTRIBUTARIA AS ST,
    FORNEC.nome AS FORNECEDOR,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.DTATUALIZACAO AS ALTERACAO_PRECO,
    PRODUTOS.CLASFISCAL AS COD_NCM,
    PRODUTOS.DTCADASTRO AS DATA_CADASTRO,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.DTULTIMAVENDA AS ULTIMA_VENDA
FROM PRODUTOS
LEFT JOIN MARCAS ON MARCAS.codigo = PRODUTOS.cod_marca
LEFT JOIN FORNEC ON FORNEC.codigo = PRODUTOS.cod_fornec
LEFT JOIN ESTOQUEFILIAL ON ESTOQUEFILIAL.cod_prod = PRODUTOS.cod_prod
where estoquefilial.cod_filial = '1'
