SELECT
   id_cliente as codigo,
    CLIENTE.NOME AS NOME,
    CLIENTE.RAZAO_SOCIAL AS FANTASIA,
    CASE WHEN CLIENTE.CNPJ = '' OR CLIENTE.CNPJ IS NULL THEN CLIENTE.CPF ELSE CLIENTE.CNPJ END AS CNPJ_CNPF,
    CASE WHEN CLIENTE.INSC_ESTADUAL = '' OR CLIENTE.INSC_ESTADUAL IS NULL THEN CLIENTE.RG ELSE CLIENTE.INSC_ESTADUAL END AS IE_RG,
    CLIENTE.FONE AS TELEFONE,
    CLIENTE.OBS AS OBSERVACOES,
    CLIENTE.ID_CIDADE,
    CLIENTE.LOGRADOURO AS ENDERECO,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,
    CLIENTE.BAIRRO AS BAIRRO,
    CIDADE.DESCRICAO AS CIDADE,
    CIDADE.SIGLA_ESTADO AS UF,
    CLIENTE.CEP AS CEP,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.DATA_NASCIMENTO AS NASCIMENTO,
    CLIENTE.NOME_PAI AS PAI,
    CLIENTE.NOME_MAE AS MAE,
    CLIENTE.LIMITE_CREDITO AS LIMITE_CREDITO,
    CLIENTE.CONJUGE AS CONJUGE
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.ID_CIDADE = CLIENTE.ID_CIDADE
