SELECT
    CODIGO_FORNECEDOR AS CODIGO,
    NOME_FORNECEDOR AS NOME ,
    RAZAO_SOCIAL AS FANTASIA,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    replace(replace(CEP,'.',''),'-','') AS CEP,
    CIDADE AS CIDADE,
    UF AS UF,
    CNPJ AS CNPJ_CNPJ,
    INSC_ESTADUAL AS IE_RG,
    INSC_MUNICIPAL AS IM,
    TELEFONE_DDD_1 ||''|| TELEFONE_1 AS TELEFONE,
    TELEFONE_1,
    E_MAIL AS EMAIL,
    CONTATO_1 AS CONTATO,
    OBSERVACOES AS OBSERVACOES
FROM FORNECEDORES
