SELECT
    ESTOQUE.CODIGO_PRODUTO AS PERSONAL3,
    ESTOQUE.CODIGO_BARRA AS BARRAS,
    ESTOQUE.DESCRICAO_PRODUTO AS DESCRICAO,
    ESTOQUE.REFERENCIA_PRODUTO AS COD_FABRICANTE,
    ESTOQUE.MARCA_PRODUTO AS CARACTERISTICAS,
    FORNECEDORES.NOME_FORNECEDOR AS FORNECEDOR,
    MIN (GRUPOS.DESCRICAO_GRUPO) AS GRUPO,
    ESTOQUE.UNIDADE AS UND,
    ESTOQUE_SALDO.SALDO AS QTD,
    SUBSTRING (ESTOQUE.CST FROM 1 FOR 1) AS OST,
    SUBSTRING (ESTOQUE.CST FROM 2 FOR 3) AS ST,
    ESTOQUE.PRECO_CUSTO AS PRECO_CUSTO,
    ESTOQUE.CUSTO_MEDIO AS CUSTO_MEDIO,
    ESTOQUE.PRECO_VENDA AS PRECO_VENDA,
    ESTOQUE.ULT_ENTRADA_DATA AS ULTIMA_COMPRA,
    ESTOQUE.ULT_SAIDA_DATA AS ULTIMA_VENDA,
    ESTOQUE.DATA_ULTIMO_REAJUSTE AS ALTERACAO_PRECO,
    ESTOQUE.OBSERVACOES AS OBSERVACOES,
    ESTOQUE.PESO AS PESO,
    ESTOQUE.NCM AS COD_NCM,
    ESTOQUE.CEST AS PERSONAL6,
    ESTOQUE.DATA_CADASTRO AS DATA_CADASTRO
FROM ESTOQUE
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO_FORNECEDOR = ESTOQUE.FORNECEDOR
LEFT JOIN GRUPOS ON GRUPOS.CODIGO_GRUPO = ESTOQUE.GRUPO 
LEFT JOIN ESTOQUE_SALDO ON ESTOQUE_SALDO.CODIGO_PRODUTO = ESTOQUE.CODIGO_PRODUTO
WHERE ESTOQUE_SALDO.FILIAL = '1'
GROUP BY 1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
