SELECT 
  M.COD_RED AS CODIGO
, M.COD_BAR AS BARRAS
, M.NOM_MER AS DESCRICAO
, CASE M.PRO_ATIVO WHEN 'T' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, M.QTD_EST AS QTD
, M.QTD_MIN AS QTD_IDEAL
, M.UNI_MER AS UND
, M.VLR_VEN AS PRECO_VENDA
, M.LUCRO AS MARGEM_LUCRO
, M.VLR_CUS AS PRECO_CUSTO
, M.COD_NCM
, M.COD_CEST AS PERSONAL6
, M.DATA_ULTCOM AS ULTIMA_COMPRA
, M.DATA_ULTVEN AS ULTIMA_VENDA
, M.APLICACAO AS OBSERVACOES
, M.COMISSAO
, M.DATA_CAD AS DATA_CADASTRO
, M.PESO_BRU AS PESO
, T1.IPI AS ALIQ_IPI_VENDA
, T1.CST_IPI AS IPI_CODIGO_VENDA
, T2.PC_COMPRA AS PISE_CODIGO
, T2.PC_COMPRA AS COFINSE_CODIGO
, T2.ALIQ_PIS_C AS PISE_ALIQ_NOR
, T2.ALIQ_COFINS_C AS COFINSE_ALIQ_NOR
, SUBSTRING (T2.PC_ECF FROM 1 FOR 2) AS PIS_CODIGO
, SUBSTRING (T2.PC_ECF FROM 1 FOR 2) AS COFINS_CODIGO
, T2.ALIQ_PIS_V AS PIS_ALIQ_NOR
, T2.ALIQ_COFINS_V AS COFINS_ALIQ_NOR
, D.NOM_DEP AS GRUPO
, SUBSTRING (T1.CST FROM 2 FOR 4) AS ST 
, F.NOME AS FORNECEDOR
FROM MERCADORIAS M 
LEFT JOIN TRIBUTOS_ICM T1 ON T1.COD_TRIB = M.COD_TRI_NFCE 
LEFT JOIN TRIBUTOS_PC  T2 ON T2.COD_TRIB = M.COD_TRI_PC 
LEFT JOIN DEPARTAMENTOS D ON D.COD_DEP = M.DEP_MER 
LEFT JOIN FORNECEDORES F ON F.CODIGO = M.COD_FOR
