SELECT
  P.ICOD_PRODUTO                 AS CODIGO,
  P.VEAN1                        AS BARRAS,
  P.VDESCRICAO                   AS DESCRICAO,
  P.CCOD_UNIDADE                 AS UND,
  P.VULTIMO_FORNECEDOR           AS FORNECEDOR,
  P.NQUANTIDADE                  AS QTD,
  P.NQUANTIDADE_MIN              AS QTD_IDEAL,
  P.NPESO_BRUTO                  AS PESO,
  P.VCOD_CLASSE                  AS ID_GRUPO,
  P.NPRECO_CUSTO                 AS PRECO_CUSTO,
  P.NPRECO_CUSTO_MEDIO           AS CUSTO_MEDIO,
  P.NLUCRO_VAREJO                AS MARGEM_LUCRO,
  P.NVALOR_VAREJO                AS PRECO_VENDA,
  SUBSTRING(P.CST FROM 1 FOR 1)  AS OST,
  SUBSTRING(P.CST FROM 2 FOR 3)  AS ST,
  NULL                  AS COD_FABRICANTE,
  P.BOBS_PRO_NFE                 AS OBSERVACOES,
  CAST(P.TSULTIMA_MODIFICACAO AS DATE) AS CADASTRO,  -- Apenas a data
  P.VCOD_NCM                     AS COD_NCM,
  P.DULTIMA_COMPRA               AS ULTIMA_COMPRA,
  P.DULTIMA_SAIDA              AS ULTIMA_VENDA,
  CAST (P.TSULTIMA_MODIFICACAO AS DATE) AS ALTERACAO_PRECO,
  CASE
    WHEN P.CATIVO = 'A' THEN 'Ativo'
    WHEN P.CATIVO = 'I' THEN 'Inativo'
    ELSE 'Desconhecido'  -- Em caso de outro valor inesperado
  END AS SITUACAO,
  C.VDESCRICAO                   AS GRUPO,
  S.VDESCRICAO                   AS FAMILIA
FROM TBPRODUTOS P
LEFT JOIN TBCLASSES C ON P.VCOD_CLASSE = C.VCOD_CLASSE
LEFT JOIN TBSUBCLASSES S ON P.VCOD_SUBCLASSE = S.VCOD_SUBCLASSE;