SELECT
--	P.CODIGO,
	P.NOME,
	P.CNPJ_CPF AS CNPJ_CNPF,
	P.RG_IE AS IE_RG,
	P.SEXO,
	DATE (P.INCLUSAO) AS CADASTRO,
	P.ESTADO_CIVIL AS EST_CIVIL,
	P.NASCIMENTO_ABERTURA AS NASCIMENTO,
	P.LIMITE AS LIMITE_CREDITO,
	P.NOME_FANTASIA AS FANTASIA,
	P.FONE AS TELEFONE,
	P.INSCRICAO_MUNICIPAL AS IM,
	PE.ENDERECO, 
	PE.NUMERO, 
	PE.COMPLEMENTO,
	PE.CEP, 
	PE.UF, 
	PE.BAIRRO,
	PE.CIDADE_DESCRICAO AS CIDADE,
	PC1.CAMPO1 AS CONTATO,
	PC2.CAMPO1 AS PERSONAL1,
	PC3.CAMPO1 AS PERSONAL2,
	PC4.CAMPO1 AS CELULAR,
	PC5.CAMPO1 AS EMAIL,
	PC6.CAMPO1 AS PERSONAL3,
	PC7.CAMPO1 AS PERSONAL4,
	PC8.CAMPO1 AS PERSONAL5,
	PC9.CAMPO1 AS PERSONAL6,
	CONCAT(
	    IFNULL(PC10.CAMPO1, ''), ' ',
        IFNULL(PC11.CAMPO1, ''), ' ',
        IFNULL(PC12.CAMPO1, ''), ' ',
        IFNULL(PC13.CAMPO1, '')
        ) AS OBSERVACOES
FROM
	PESSOAS P
LEFT JOIN PESSOAS_ENDERECOS PE ON PE.CHAVE_PESSOA = P.CHAVE AND PE.PADRAO ='1'
LEFT JOIN PESSOAS_CONTATOS PC1 ON PC1.CHAVE_PESSOA = P.CHAVE AND PC1.TIPO = 'C1'
LEFT JOIN PESSOAS_CONTATOS PC2 ON PC2.CHAVE_PESSOA = P.CHAVE AND PC2.TIPO = 'C2'
LEFT JOIN PESSOAS_CONTATOS PC3 ON PC3.CHAVE_PESSOA = P.CHAVE AND PC3.TIPO = 'C3'
LEFT JOIN PESSOAS_CONTATOS PC4 ON PC4.CHAVE_PESSOA = P.CHAVE AND PC4.TIPO = 'CE'
LEFT JOIN PESSOAS_CONTATOS PC5 ON PC5.CHAVE_PESSOA = P.CHAVE AND PC5.TIPO = 'EM'
LEFT JOIN PESSOAS_CONTATOS PC6 ON PC6.CHAVE_PESSOA = P.CHAVE AND PC6.TIPO = 'F1'
LEFT JOIN PESSOAS_CONTATOS PC7 ON PC7.CHAVE_PESSOA = P.CHAVE AND PC7.TIPO = 'F2'
LEFT JOIN PESSOAS_CONTATOS PC8 ON PC8.CHAVE_PESSOA = P.CHAVE AND PC8.TIPO = 'FA'
LEFT JOIN PESSOAS_CONTATOS PC9 ON PC9.CHAVE_PESSOA = P.CHAVE AND PC9.TIPO = 'HO'
LEFT JOIN PESSOAS_CONTATOS PC10 ON PC10.CHAVE_PESSOA = P.CHAVE AND PC10.TIPO = 'IM'
LEFT JOIN PESSOAS_CONTATOS PC11 ON PC11.CHAVE_PESSOA = P.CHAVE AND PC11.TIPO = 'LE'
LEFT JOIN PESSOAS_CONTATOS PC12 ON PC12.CHAVE_PESSOA = P.CHAVE AND PC12.TIPO = 'PA'
LEFT JOIN PESSOAS_CONTATOS PC13 ON PC13.CHAVE_PESSOA = P.CHAVE AND PC13.TIPO IS NULL
-- WHERE SUBCATEGORIA NOT IN ('1','2','3','10') -- DIFERENTE DE FORNECEDORES
