SELECT
	P.CODIGO,
	P.DESCRICAO,
	DATE (P.INCLUSAO) AS DATA_CADASTRO,	
	P.QME AS QTD,
	CASE 
    	WHEN P.TIPO = 'M' THEN '00' 
    	WHEN P.TIPO = 'S' THEN '09' 
	END AS TIPO_ITEM,
	P.UNID_MED AS UND,
	P.EST_MINIMO AS QTD_IDEAL,
	P.CUSTO_MEDIO AS CUSTO_MEDIO,
	P.CUSTO_ATUAL AS PRECO_CUSTO,
	P.PRECO_VENDA AS PRECO_VENDA,
	P.PRECO_ATACADO AS PRECO_ATACADO,
	P.PRECO_VENDA1 AS PERSONAL1,
	DATE (P.ULT_VEN) AS ULTIMA_VENDA,	
	DATE (P.ULT_COMPRA) AS ULTIMA_COMPRA,		
	P.PESO,
	P.OBS AS OBSERVACOES,
	P.CLASSIFICACAO_FISCAL AS COD_NCM,
	P.AUXILIAR1 AS COD_FABRICANTE,
	P.QUANT_PRECO_ATACADO AS QTD_PRECO_ATACADO,
	CASE 
		WHEN P.INATIVO = '0' THEN 'Ativo'
		WHEN P.INATIVO = '1' THEN 'Inativo'
	END AS SITUACAO,
	LEFT(REPLACE (P.CFOP,'.',''),3) AS ELO,
	P.ALIQ_IPI AS ALIQ_IPI,
	P.CEST AS PERSONAL6,
	GI.ORIGEM AS OST,
	GI.SITUACAO_TRIBUTARIA AS ST,
--	GI.CSOSN AS ST,
--	GI.ALIQUOTA_ICMS AS ELO,
	GI.ALIQ_IPI AS ALIQ_IPI_VENDA,
	GI.SITUACAO_IPI AS IPI_CODIGO_VENDA,
	GI.ALIQ_PIS AS PIS_ALIQ_NOR,
	GI.SITUACAO_PIS AS PIS_CODIGO,
	GI.ALIQ_COFINS AS COFINS_ALIQ_NOR,
	GI.SITUACAO_COFINS AS COFINS_CODIGO,
	GI.ALIQ_PIS_COMPRA AS PISE_ALIQ_NOR,
	GI.ALIQ_COFINS_COMPRA AS COFINSE_ALIQ_NOR,
	GC.COMISSAO,
	F.NOME AS FORNECEDOR,
	G1.DESCRICAO AS GRUPO,
	G2.DESCRICAO AS FAMILIA,
	G3.DESCRICAO AS CARACTERISTICAS,
	GL.MARGEM AS MARGEM_LUCRO
FROM
	PRODUTOS P
LEFT JOIN GRUPOS_ICMS GI ON GI.CHAVE = P.G_ICMS 
LEFT JOIN GRUPOS_COMISSAO GC ON GC.CHAVE = P.G_COMISSAO
LEFT JOIN PESSOAS F ON F.CHAVE = P.FORNECEDOR
LEFT JOIN GRUPOS G1 ON G1.CHAVE = P.GRUPO1
LEFT JOIN GRUPOS G2 ON G2.CHAVE = P.GRUPO2
LEFT JOIN GRUPOS G3 ON G3.CHAVE = P.GRUPO3
LEFT JOIN GRUPOS_LUCRATIVIDADES GL ON GL.CHAVE = P.G_L
