SELECT
    CODIGO AS CODIGO,
    RAZAO AS NOME,
    FANTASIA AS FANTASIA,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    MUNICIPIO AS CIDADE,
    BAIRRO AS BAIRRO,
    UF AS UF,
    CEP AS CEP,
    FONE1 AS TELEFONE,
    CELULAR1 AS CELULAR,
    EMAIL1 AS EMAIL,
    OBS AS OBSERVACOES,
    case when ATIVO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PESSOA
WHERE FORN = 'S'
