SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.QTD_ATUAL AS QTD,
    PRODUTO.QTD_MIN AS QTD_IDEAL,
    PRODUTO.PESO AS PESO,
    GRUPO.DESCRICAO AS GRUPO,
    PRODUTO.PR_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.PR_VENDA AS PRECO_VENDA,
    PRODUTO.PRECO_ATACADO AS PRECO_ATACADO,
    SUBSTRING (PRODUTO.CSTICMS FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.CSTICMS FROM 2 FOR 3) AS ST,
    PRODUTO.CFOP AS CF,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6,
    --PRODUTO.ULT_COMPRA AS ULTIMA_COMPRA,
    PRODUTO.DT_CADASTRO AS DATA_CADASTRO,
    case when PRODUTO.ATIVO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
