SELECT
    ID AS CODIGO,
    FANTASIA AS NOME,
    RAZAO AS FANTASIA,
    CPFCNPJ AS CNPJ_CNPF,
    RG AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP
FROM FORNECEDOR
