SELECT
    CODCLIENTE AS CODIGO,
    NMECLIENTE AS NOME,
    case when CPF = '' or CPF is null then CGC else CPF END AS CNPJ_CNPF,
    INSCRESTADUAL AS IE_RG,
    --CAST (DTCADASTRO AS DATE) AS CADASTRO,
    EMAIL AS EMAIL,
    FANTASIA
FROM CLIENTES
