SELECT
    CODFORNECEDOR AS CODIGO,
    CNPJ AS CNPJ_CNPF,
    NMEEMPRESA AS NOME,
    NMEFANTASIA AS FANTASIA,
    INSCRESTADUAL AS IE_RG,
    LOGRADOURO AS ENDERECO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP
FROM FORNECEDORES
