SELECT
    CODPRODUTO AS CODIGO,
    NMEPRODUTO AS DESCRICAO,
    CODBARRAS AS BARRAS,
    PESOLIQUIDO AS PESO,
    UNIDADESAIDA AS UND,
    UNIDADEENTRADA AS UND_COMPRA,
    QTDMIN_ESTOQUE AS QTD_IDEAL,
    UNIDADESEMESTOQUE AS QTD,
    PRECOCUSTO AS PRECO_CUSTO,
    CUSTOMEDIO AS CUSTO_MEDIO,
    MARGEMPADRAO AS MARGEM_LUCRO,
    PRECOVENDA AS PRECO_VENDA,
    CSOSN AS ST,
    CODINTERNO AS COD_FABRICANTE,
    CLASSIPI AS COD_NCM,
    CEST AS PERSONAL6,
    OBS AS OBSERVACOES,
    CAST (DTULTSAIDA AS DATE) AS ULTIMA_VENDA,
    CAST (DTULTENT AS DATE) AS ULTIMA_COMPRA,
    CAST (DTULTATUALIZACAO AS DATE) AS ALTERACAO_PRECO,
    CAST (DTCADASTRO AS DATE) AS DATA_CADASTRO
FROM PRODUTOS
WHERE CODPRODUTO > 0
