SELECT 
ENTIDADE.codigo,
ENTIDADE.nome,
ENTIDADE.razaosocial AS FANTASIA,
ENTIDADE.cnpjcpf AS CNPJ_CNPF,
ENTIDADE.inscricaoestadual AS IE_RG,
ENTIDADE.ENDERECO,
ENTIDADE.numeroendereco AS NUMERO,
ENTIDADE.complemento,
ENTIDADE.bairro,
CIDADE.nome AS CIDADE,
ESTADO.CODIGO AS UF,
REPLACE (ENTIDADE.CEP, '-' , '') AS CEP,
ENTIDADE.telefone,
ENTIDADE.CELULAR,
ENTIDADE.FAX,
ENTIDADE.EMAIL,
ENTIDADE.NASCIMENTO,
ENTIDADE.observacao AS OBSERVACOES,
ENTIDADE.CONJUGE,
ENTIDADE.PAI,
ENTIDADE.MAE,
ENTIDADE.datacadastro AS CADASTRO
FROM ENTIDADE
LEFT JOIN CIDADE ON ENTIDADE.idcidade=CIDADE.id
LEFT JOIN ESTADO ON ENTIDADE.idestado=ESTADO.ID
WHERE  ENTIDADE.cliente = '1' and ENTIDADE.codigo <> '0'
