SELECT 
ENTIDADE.codigo AS CODIGO,
ENTIDADE.nome AS RAZAO_SOCIAL,
ENTIDADE.cnpjcpf AS CNPJ,
ENTIDADE.inscricaoestadual AS IE,
ENTIDADE.ENDERECO AS ENDERECO,
CIDADE.nome AS CIDADE,
ESTADO.CODIGO AS UF,
ENTIDADE.telefone AS TELEFONE,
ENTIDADE.EMAIL AS EMAIL
FROM ENTIDADE
LEFT JOIN CIDADE ON ENTIDADE.idcidade=CIDADE.id
LEFT JOIN ESTADO ON ENTIDADE.idestado=ESTADO.ID
WHERE ENTIDADE.transportadora = '1' and ENTIDADE.codigo <> 'entidade'
