SELECT
    PESSOAS.IDPESSOA AS CODIGO,
    PESSOAS.NOME_PESSOA AS NOME,
    PESSOAS.NOME_FANTASIA AS FANTASIA,
    PESSOAS.CONTATO AS CONTATO,
    PESSOAS.CNPJ_CPF AS CNPJ_CNPF,
    case when PESSOAS.RG = '' or PESSOAS.RG is null then PESSOAS.INSCRICAO_ESTADUAL else PESSOAS.RG END AS IE_RG,
    PESSOAS.INSCRICAO_MUNICIPAL AS IM,
    PESSOAS.ENDERECO AS ENDERECO,
    PESSOAS.ENDERECO_NUMERO AS NUMERO,
    PESSOAS.ENDERECO_COMPLEMENTO AS COMPLEMENTO,
    PESSOAS.BAIRRO AS BAIRRO,
    PESSOAS.CEP AS CEP,
    PESSOAS.CIDADE AS CIDADE,
    PESSOAS.UF AS UF,
    PESSOAS.FONES AS TELEFONE,
    PESSOAS.FONE_FAX AS FAX,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.OBS_PESSOA AS OBSERVACOES,
    case when PESSOAS.STATUS = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PESSOAS
WHERE PESSOAS.FORNECEDOR = 'S' ---- FORNECEDORES
