SELECT 
       PRODUTO.CDPRODUTO AS CODIGO
      ,PRODUTO.DESCRICAO AS DESCRICAO
      ,MIN (BARRA.BARRA) AS BARRAS
      ,MIN (BARRA.BARRA) AS COD_FABRICANTE
      ,MOVEST.QUANT AS QTD
      ,UNIDADE.DESCRICAO AS UND_COMPRA
      ,UNIDADE.DESCRICAO AS UND
      ,PRODUTO.MARCA AS FAMILIA
      ,CATEGORIA.DESCRICAO AS GRUPO
      ,PRODUTO.BASE AS PRECO_VENDA
      ,PRODUTO.MARGEM AS MARGEM_LUCRO
      ,PRODUTO.CUSTO AS PRECO_CUSTO
      ,PRODUTO.PRECO3 AS PRECO_IFOOD
      ,PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO 
      ,PRODUTO.PRECOMINIMO AS PRECO_ATACADO 
      ,CAST (PRODUTO.ALTERACAO AS DATE) AS ALTERACAO_PRECO
      ,PRODUTO.OBSERVACAO AS OBSERVACOES
      ,PRODUTO.CLASSIFICACAO AS COD_NCM
      ,SUBSTRING (PRODUTO.CST, 2,4) AS ST
      ,PRODUTO.PESOLIQ AS PESO
      ,FORNECEDOR.NOME AS FORNECEDOR
      ,PRODUTO.CEST AS PERSONAL6
  FROM PRODUTO
  LEFT JOIN UNIDADE ON UNIDADE.CDUND = PRODUTO.UNVENDA
  LEFT JOIN FORNECEDOR ON FORNECEDOR.CDFOR = PRODUTO.CDFAB
  LEFT JOIN MOVEST ON MOVEST.CDPROD = PRODUTO.CDPRODUTO
  LEFT JOIN BARRA ON BARRA.CDPRODUTO = PRODUTO.CDPRODUTO
  LEFT JOIN CATEGORIA ON PRODUTO.CDCAT = CATEGORIA.CDCAT
WHERE MOVEST.TIPO = '1'
GROUP BY
 PRODUTO.CDPRODUTO
,PRODUTO.DESCRICAO
,MOVEST.QUANT
,UNIDADE.DESCRICAO
,UNIDADE.DESCRICAO
,PRODUTO.MARCA
,CATEGORIA.DESCRICAO
,PRODUTO.BASE
,PRODUTO.MARGEM
,PRODUTO.CUSTO
,PRODUTO.PRECO3 
,PRODUTO.CUSTOMEDIO
,PRODUTO.PRECOMINIMO
,PRODUTO.ALTERACAO
,PRODUTO.OBSERVACAO
,PRODUTO.CLASSIFICACAO
,PRODUTO.CST
,PRODUTO.PESOLIQ
,FORNECEDOR.NOME
,PRODUTO.CEST
