SELECT
	C.CODPARC AS CODIGO,
	C.NOMPARC NOME,
	C.SOBPARC AS FANTASIA,
	C.CNPPARC AS CNPJ_CNPF,
	C.REGPARC AS IE_RG,
	C.OBSPARC AS OBSERVACOES,
	C.EMAPARC AS EMAIL,
	E.FONENDE AS TELEFONE,
	E.ENDENDE AS ENDERECO,
	E.REFEREN AS COMPLEMENTO,
	E.NUMENDE AS NUMERO,
	E.BAIENDE AS BAIRRO,
	E.CEPENDE AS CEP,
	E.CELENDE AS CELULAR,
	E.FAXENDE AS FAX, 
	E.NOMMUNI AS CIDADE,
	E.UF_ENDE AS UF
FROM
	TAB_PARC C
LEFT JOIN TAB_ENDE E ON E.CODPARC = C.CODPARC 
-- WHERE C.CTAFORN =  ---AJUSTAR PARA FILTRAR SÓ FORNECEDORES
