SELECT
  PRODUTOS.CODIGO,
  PRODUTOS.DESCRICAO,
  FORNECEDORES.EMPRESA AS FORNECEDOR,
  PRODUTOS.EMBALAGEM_VENDA AS UND,
  CAST (PRODUTOS.DATA AS DATE) AS DATA_CADASTRO,
  CAST (PRODUTOS.DATA_ALTERACAO AS DATE) AS ALTERACAO_PRECO,
  PRODUTOS.COD_BARRA AS BARRAS,
  SECAO.DESCRICAO AS GRUPO,
  PRODUTOS_EMPRESA.ESTOQUE_VENDA AS QTD,
  PRODUTOS_EMPRESA.PRECO_VENDA AS PRECO_VENDA,
  PRODUTOS_EMPRESA.CUSTO_COM_IMPOSTOS AS PRECO_CUSTO,
  PRODUTOS_EMPRESA.MARGEM AS MARGEM_LUCRO,
  PRODUTOS_EMPRESA.CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTOS_EMPRESA.TRIBUTACAO_SAI AS ST,
  PRODUTOS.PESO AS PESO,
  PRODUTOS.EMBALAGEM_COMPRA AS UND_COMPRA,
  'APLICACAO: '||PRODUTOS.APLICACAO || ' -->> '||'REF_AUXILIARES: '||PRODUTOS.REF_AUXILIARES AS OBSERVACOES,
  PRODUTOS.REFERENCIA AS COD_FABRICANTE
FROM PRODUTOS
LEFT JOIN SECAO ON SECAO.SECAO = PRODUTOS.SECAO
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = PRODUTOS.FORNECEDOR
LEFT JOIN PRODUTOS_EMPRESA ON PRODUTOS_EMPRESA.PRODUTO = PRODUTOS.CODIGO
