SELECT 
CM.ID_MERCADORIA AS CODIGO,
CM.CODIGO_BARRA AS BARRAS,
CM.DESCRICAO_COMPLETA AS DESCRICAO,
CMSB.DESCRICAO AS GRUPO,
CM.PRECO_CUSTO_REAL AS PRECO_CUSTO,
CM.PRECO_CUSTO_MEDIO AS CUSTO_MEDIO,
CMSP.PRECO_VENDA AS PRECO_VENDA,
CMSUM.`SIGLA` AS UNDEFINED,
CM.NCM AS CODIGO_NCM,
CM.CEST AS PERSONAL6,
ST.ICMS_CST_CSOSN AS ST
FROM CAD_MERCADORIA_SERVICO AS CM
LEFT JOIN `cad_mercadoria_servico_subgrupo` CMSB on CM.`ID_SUBGRUPO` = CMSB.ID_SUBGRUPO
LEFT JOIN cad_mercadoria_servico_preco CMSP ON CM.ID_MERCADORIA = CMSP.`ID_MERCADORIA`
LEFT JOIN `cad_mercadoria_servico_unidade_medida`CMSUM ON CMSP.`ID_UNIDADE_MEDIDA` = `CMSUM`.`ID_UNIDADE_MEDIDA`
LEFT JOIN `cfg_imposto_icms_iss` ST ON `CM`.`ID_ICMS_ISS` = `ST`.`ID_ICMS_ISS`