SELECT CLIENTE.CODIGO,
CLIENTE.NOME,
CLIENTE.FANTASIA,
CLIENTE.CPF_CNPJ AS CNPJ_CNPF,
CLIENTE.RG_IE AS IE_RG,
CLIENTE.NUMERO,
CLIENTE.ENDERECO,
CLIENTE.BAIRRO,
MUNICIPIO.NOME AS CIDADE,
MUNICIPIO.UF,
CLIENTE.CEP,
CLIENTE.FONE AS TELEFONE,
CLIENTE.FAX,
CLIENTE.CELULAR,
CLIENTE.EMAIL,
CLIENTE.DATACADASTRO AS CADASTRO,
CLIENTE.CONTATO
FROM CLIENTE
LEFT JOIN MUNICIPIO ON CLIENTE.MUNICIPIO=MUNICIPIO.CODIGO



