SELECT FORNECEDOR.CODIGO,
FORNECEDOR.NOME,
FORNECEDOR.FANTASIA,
FORNECEDOR.CPF_CNPJ AS CNPJ_CNPF,
FORNECEDOR.RG_IE AS IE_RG,
FORNECEDOR.ENDERECO,
FORNECEDOR.BAIRRO,
FORNECEDOR.NUMERO,
MUNICIPIO.NOME AS CIDADE,
MUNICIPIO.UF,
FORNECEDOR.CEP,
FORNECEDOR.FONE AS TELEFONE,
FORNECEDOR.FAX,
FORNECEDOR.CELULAR,
FORNECEDOR.EMAIL
FROM FORNECEDOR
LEFT JOIN MUNICIPIO ON FORNECEDOR.MUNICIPIO=MUNICIPIO.CODIGO

