SELECT
  produtos.CODIGO AS CODIGO,
  produtos.DESCRICAO AS DESCRICAO,
  SUBSTRING(produtos.COD_BARRA FROM 2 FOR 14) AS BARRAS,
  GRUPOS.DESCRICAO AS GRUPO,
  produtos.REFERENCIA AS COD_FABRICANTE,
  produtos.UNIDADE AS UND,
  produtos.SALDO AS QTD,
  produtos.PESO AS PESO,
  produtos.P_CUSTOMEDIO AS CUSTO_MEDIO,
  produtos.P_CUSTOCOMPRA AS PRECO_CUSTO,
  produtos.P_VENDA AS PRECO_VENDA,
  FORNECEDOR.NOME AS FORNECEDOR,
  produtos.ULT_ALT_PC AS ALTERACAO_PRECO,
  produtos.ULT_SAID ULTIMA_VENDA,
  SUBSTRING(produtos.CST FROM 2 FOR 3) AS ST,
  produtos.ULT_ENTR AS ULTIMA_COMPRA,
  produtos.PCO_ATACA AS PRECO_ATACADO,
  REPLACE (produtos.NCM, '.' , '') AS COD_NCM,
  produtos.CEST AS PERSONAL6,
  produtos.OBS AS OBSERVACOES
FROM produtos
LEFT JOIN FORNECEDOR ON FORNECEDOR.IDFORNECEDOR = PRODUTOS.LKFORNECEDOR
LEFT JOIN GRUPOS ON GRUPOS.IDGRUPO = PRODUTOS.LKGRUPO
