SELECT
    CLICODIGO AS CODIGO,
    CLINOME AS NOME,
    CLIRGIE AS IE_RG,
    CLICPFCNPJ AS CNPJ_CNPF,
    CLIFANTASIA AS FANTASIA,
    CLIBAIRRO AS BAIRRO,
    CLICEP AS CEP,
    CLIFONE AS TELEFONE,
    CLIDATACAD AS CADASTRO,
    CLICLELULAR AS CELULAR,
    CLIENDERECO AS ENDERECO,
    CLINUMERO AS NUMERO,
    CLIEMAIL AS EMAIL
FROM CLIENTE