SELECT
    PROCODIGO AS CODIGO, 
    PROUNID AS UND,
    PROCUSTOTOT AS PRECO_CUSTO,
    PROVLRVENDA AS PRECO_VENDA,
    PROESTOQUE AS QTD,
    PROCODBAR AS BARRAS,
    PRODESCRICAO AS DESCRICAO,
    PRONCM AS COD_NCM,
    PROCEST AS PERSONAL6
FROM PRODUTO