SELECT
    C.CLI_CODIGO AS CODIGO,
    C.CLI_NOME AS NOME,
    C.CLI_RAZAO AS FANTASIA,
    C.CLI_CPF_CNPJ AS CNPJ_CNPF,
    C.CLI_RG_IE AS IE_RG,
    CE.CE_ENDERECO AS ENDERECO,
    CE.CE_BAIRRO AS BAIRRO,
    CE.CE_CEP AS CEP,
    CE.CE_UF AS UF,
    CE.CE_NUMERO AS NUMERO,
    M.MUN_NOME AS CIDADE,
    C.CLI_EMAIL AS EMAIL,  
    MAX (CTR.TELEFONE) AS TELEFONE,
    MAX (CTC.TELEFONE) AS CELULAR,
    C.CLI_LIMITE AS LIMITE_CREDITO,
    C.CLI_DATACAD AS CADASTRO,
    C.CLI_DATANASC AS NASCIMENTO,
    C.CLI_CONJUGE AS CONJUGE,
    C.CLI_OBS AS OBSERVACOES,
    C.CLI_SEXO AS SEXO,
    C.CLI_PAI AS PAI,
    C.CLI_MAE AS MAE,
    EC.EST_NOME AS EST_CIVIL,
    C.CLI_DATA_ULTIMA_VENDA AS ULTIMA_VENDA,
    case when C.CLI_ATIVO = 'S' then 'Ativo' else 'Inativo' end as situacao
FROM CLIENTE AS C
LEFT JOIN ESTADO_CIVIL EC ON C.CLI_ESTCIVIL = EC.EST_CODIGO
LEFT JOIN CLIENTE_ENDERECO CE ON C.CLI_CODIGO = CE.CLI_CODIGO
LEFT JOIN MUNICIPIO M ON CE.MUN_CODIGO = M.MUN_CODIGO
LEFT JOIN CLIENTE_TELEFONE CTR ON C.CLI_CODIGO = CTR.CLI_CODIGO AND CTR.TT_CODIGO = '1'
LEFT JOIN CLIENTE_TELEFONE CTC ON C.CLI_CODIGO = CTC.CLI_CODIGO AND CTC.TT_CODIGO = '3'
WHERE C.CLI_NOME NOT LIKE 'CONSUM%'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,15,16,17,18,19,20,21,22,23,24,25