SELECT
    F.FOR_CODIGO AS CODIGO,
    F.FOR_NOME AS NOME,
    F.FOR_RAZAO AS FANTASIA,
    F.FOR_CONTATO AS CONTATO,
    F.FOR_CPF_CNPJ AS CNPJ_CNPF,
    F.FOR_RG_IE AS IE_RG,
    F.FOR_ENDERECO AS ENDERECO,
    F.FOR_NUMERO AS NUMERO,
    F.FOR_BAIRRO AS BAIRRO,
    M.MUN_NOME AS CIDADE,
    F.FOR_ESTADO AS UF,
    F.FOR_CEP AS CEP,
    F.FOR_EMAIL AS EMAIL,
    F.FOR_TELEFONE AS TELEFONE,
    F.FOR_OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR AS F
LEFT JOIN MUNICIPIO M ON F.MUN_CODIGO = M.MUN_CODIGO