SELECT
    P.PRO_CODIGO AS CODIGO,
    P.PRO_NOME AS DESCRICAO,
    P.PRO_BARRA AS BARRAS,
    UN.UN_SIGLA AS UND,
    P.PRO_PESO AS PESO,
    TP.TIPO_NOME AS GRUPO,
    P.PRO_ESTMINIMO AS QTD_IDEAL,
    P.PRO_QTDE AS QTD,
    P.PRO_CUSTO AS PRECO_CUSTO,
    P.PRO_MARGEM AS MARGEM_LUCRO,
    P.PRO_PRECO AS PRECO_VENDA,
    P.PRO_CST AS ST,
    P.PRO_NCM AS COD_NCM,
    P.PRO_CEST AS PERSONAL6,
    P.PRO_REFERENCIA AS COD_FABRICANTE,
    P.PRO_DT_ATUAL AS ALTERACAO_PRECO,
    P.PRO_DT_CAD AS DATA_CADASTRO,
    case when P.PRO_ATIVO = 'S' then 'Ativo' else 'Inativo' end as situacao
FROM PRODUTO AS P
LEFT JOIN UNIDADE UN ON P.UN_CODIGO = UN.UN_CODIGO
LEFT JOIN TIPO_PRODUTO TP ON P.TIPO_CODIGO = TP.TIPO_CODIGO