SELECT M3_CLIEPAF.CODIGO,
M3_CLIEPAF.NOME,
M3_CLIEPAF.FANTASIA,
CASE WHEN M3_CLIEPAF.CPF='' THEN M3_CLIEPAF.CNPJ ELSE M3_CLIEPAF.CPF
END AS CNPJ_CNPF,
M3_CLIEPAF.IE,
M3_CLIEPAF.LOGRADOURO AS ENDERECO,
M3_CLIEPAF.BAIRRO,
M3_CLIEPAF.CEP,
M3_CLIEPAF.CIDADE,
M3_CLIEPAF.TELEFONEPADRAO AS TELEFONE,
M3_UFPAF.SIGLA AS UF
FROM M3_CLIEPAF
LEFT JOIN M3_UFPAF ON M3_CLIEPAF.IDF_UF=M3_UFPAF.ID

