SELECT M3_PROSERPAF.CODIGO,
M3_PROSERPAF.DESCRICAO,
M3_PROSERPAF.UNIDADEPADRAO AS UND,
M3_PROSERPAF.SALDO AS QTD,
PC.PRECO AS PRECO_CUSTO,
PV.PRECO AS PRECO_VENDA,
M3_PROSERPAF.CODITEM AS BARRAS
FROM M3_PROSERPAF
LEFT JOIN M3_PRECOPAF PC ON M3_PROSERPAF.ID=PC.IDF_LISTAPRODSERV AND PC.IDF_TABPRE=5
LEFT JOIN M3_PRECOPAF PV ON M3_PROSERPAF.ID=PV.IDF_LISTAPRODSERV AND PV.IDF_TABPRE=1
