SELECT
    PESSOAS.CODIGO AS CODIGO,
    PESSOAS.NOME_RAZAOSOCIAL AS NOME,
    PESSOAS.APELIDO_FANTASIA AS FANTASIA,
    PESSOAS.CONTATO AS CONTATO,
    PESSOAS.CPF_CNPJ AS CNPJ_CNPF,
    PESSOAS.RG_IE AS IE_RG,
    PESSOAS.IM AS IM,
    ENDERECOS.LOGRADOURO AS ENDERECO,
    ENDERECOS.NUMERO AS NUMERO,
    ENDERECOS.COMPLEMENTO AS COMPLEMENTO,
    ENDERECOS.BAIRRO AS BAIRRO,
    CIDADES.CIDADE AS CIDADE,
    CIDADES.UF AS UF,
    ENDERECOS.CEP AS CEP,
    PESSOAS.TELEFONE AS TELEFONE,
    PESSOAS.CELULAR AS CELULAR,
    PESSOAS.FAX AS FAX,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.ESTADO_CIVIL AS EST_CIVIL,
    PESSOAS.DATA_NASCIMENTO AS NASCIMENTO,
    PESSOAS.DATA_CADASTRO AS CADASTRO,
    PESSOAS.OBSERVACOES AS OBSERVACOES
FROM PESSOAS
LEFT JOIN ENDERECOS ON ENDERECOS.ID = PESSOAS.ENDERECO
LEFT JOIN CIDADES ON CIDADES.CODIGO = ENDERECOS.CIDADE
RIGHT JOIN CLIENTES ON CLIENTES.CODIGO = PESSOAS.CODIGO 
--WHERE TIPO_PESSOA <> 'J'  ----CLIENTES
