SELECT
    MAX (NCM_CEST.CEST) AS PERSONAL6,
--    PRODUTOS.CODIGO  AS CODIGO,
    PRODUTOS.CODIGO  AS COD_FABRICANTE,
--    PRODUTOS.COD_FABRICANTE AS COD_FABRICANTE,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.ESTOQUE AS QTD,  
    PRODUTOS.PCUSTOR AS PRECO_CUSTO,
    PRODUTOS.DATAULTCOMPRA AS ULTIMA_COMPRA,
    PRODUTOS.PVISTA AS PRECO_VENDA,
    PRODUTOS.DATAULTVENDA AS ULTIMA_VENDA,
    PRODUTOS.CODIGO_BARRAS AS BARRAS,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.PESOBRUTO AS PESO,
    PRODUTOS.OBSERVACOES AS OBSERVACOES,
    PRODUTOS.ESTOQUEMIN AS QTD_IDEAL,
    PRODUTOS.PMEDIO AS CUSTO_MEDIO,
    PRODUTOS.CSOSN AS ST,
    PRODUTOS.TAMANHO,
    PRODUTOS.COR,    
    PRODUTOS.PIS_CST AS PIS_CODIGO,
    PRODUTOS.COFINS_CST AS COFINS_CODIGO, 
    PRODUTOS.IPI_CST AS IPI_CODIGO_VENDA, 
    PRODUTOS.COMISSAOP AS COMISSAO, 
    PRODUTOS.FATOR_UNIDADE AS FAT_CONV,
    CASE PRODUTOS.SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
    PESSOAS.NOME_RAZAOSOCIAL AS FORNECEDOR,
    SECOES.DESCRICAO AS GRUPO,
    MARCAS.DESCRICAO AS FAMILIA
FROM PRODUTOS
LEFT JOIN NCM_CEST ON NCM_CEST.NCM = PRODUTOS.NCM
LEFT JOIN PESSOAS ON PESSOAS.CODIGO = PRODUTOS.FORNECEDOR
LEFT JOIN SECOES ON SECOES.CODIGO = PRODUTOS.SECAO 
LEFT JOIN MARCAS ON MARCAS.CODIGO = PRODUTOS.MARCA 
group by 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
