SELECT
    CODIGO AS CODIGO,
    RAZAO AS NOME,
    FANTASIA AS FANTASIA,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    FONE1 AS TELEFONE,
    FONE2 AS CELULAR,
    FAX AS FAX,
    FOR_NUM AS NUMERO
FROM FORNECEDOR
