SELECT
    PESSOAS.PESSOA AS CODIGO,
    PESSOAS.NOME AS NOME,
    PESSOAS.APELIDO AS FANTASIA,
    PESSOAS.TIPO,
    PESSOAS.CPFCNPJ AS CNPJ_CNPF,
    PESSOAS.RG AS IE_RG,
    PESSOAS.INSCMUNICIPAL AS IM,
    PESSOAS.ENDERECO AS ENDERECO,
    PESSOAS.BAIRRO AS BAIRRO,
    CIDADES.NOME AS CIDADE,
    CIDADES.UF AS UF,
    PESSOAS.CEP AS CEP,
    PESSOAS.DDD || PESSOAS.TELEFONE AS TELEFONE,
    PESSOAS.DDD || PESSOAS.FAX AS FAX,
    PESSOAS.OBSERVACOES AS OBSERVACOES,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.LIMITE AS LIMITE_CREDITO,
    CAST (PESSOAS.DATANASC AS DATE) AS NASCIMENTO,
    CAST (PESSOAS.DATACADASTRO AS DATE) AS CADASTRO
FROM PESSOAS
LEFT JOIN CIDADES ON CIDADES.CIDADE = PESSOAS.CIDADE
WHERE PESSOAS.TIPO <> 'F'
