SELECT 
MERCADORIA.Id AS CODIGO,
substring (Mercadoria.CodigoBarra, 2 ,20) as BARRAS,
MERCADORIA.Descricao AS DESCRICAO,
UnidadeVenda.sigla AS UND,
Grupo.NomeGrupo AS GRUPO,
SubGrupo.Nome AS FAMILIA,
ICMS.SituacaoTributaria AS ST,
MERCADORIAESTOCAVELDADOSEMPRESA.PrecoCusto AS PRECO_CUSTO,
MERCADORIAESTOCAVELDADOSEMPRESA.PrecoCustoMedio AS CUSTO_MEDIO,
MAX (PRECO.PrecoCalculado) AS PRECO_VENDA,
MERCADORIA.ClassificacaoFiscalNCM AS COD_NCM,
MERCADORIA.Cest AS PERSONAL6
FROM CAD_MERcadoria MERCADORIA
INNER JOIN CAD_MercadoriaDadosEmpresa MERCADORIADADOSEMPRESA ON MERCADORIADADOSEMPRESA.IdMercadoria=MERCADORIA.Id
LEFT JOIN FIS_Imposto IMPOSTO ON IMPOSTO.Id = MERCADORIADADOSEMPRESA.IdImpostoICMS
LEFT JOIN FIS_ImpostoICMS ICMS ON ICMS.Id = IMPOSTO.Id
LEFT JOIN FIS_ImpostoPIS PIS ON PIS.Id = IMPOSTO.Id
LEFT JOIN FIS_ImpostoCOFINS COFINS ON COFINS.Id = IMPOSTO.Id
LEFT JOIN CAD_UnidadeVenda UNIDADEVENDA ON UNIDADEVENDA.Id = MERCADORIA.IdUnidadeVenda
LEFT JOIN CAD_UnidadeVenda UNIDADEFISCAL ON UNIDADEFISCAL.Id = MERCADORIADADOSEMPRESA.UnidadeTributavel
LEFT JOIN CAD_SubGrupoMercadoria SUBGRUPO ON SUBGRUPO.Id = MERCADORIA.IdSubGrupoMercadoria
left join CAD_GrupoMercadoria Grupo on Grupo.id = SubGrupo.IdGrupoMercadoria
LEFT JOIN CAD_MercadoriaEstocavelDadosEmpresa MERCADORIAESTOCAVELDADOSEMPRESA ON MERCADORIAESTOCAVELDADOSEMPRESA.IdMercadoria=MERCADORIA.Id
LEFT JOIN FAT_CodigoFiscal CODIGOFISCAL ON CODIGOFISCAL.TipoCodigoFiscal=MERCADORIADADOSEMPRESA.CodigoFiscal
LEFT JOIN CAD_PrecoMercadoria PRECO ON PRECO.IdMercadoriaDadosEmpresa=MERCADORIADADOSEMPRESA.Id
GROUP BY
MERCADORIA.Id,
Mercadoria.CodigoBarra,
MERCADORIA.Descricao,
UnidadeVenda.sigla,
Grupo.NomeGrupo,
SubGrupo.Nome,
ICMS.SituacaoTributaria,
MERCADORIAESTOCAVELDADOSEMPRESA.PrecoCusto,
MERCADORIAESTOCAVELDADOSEMPRESA.PrecoCustoMedio,
MERCADORIA.ClassificacaoFiscalNCM,
MERCADORIA.Cest
