SELECT
  PRODUTO.CODIGO AS CODIGO,
  PRODUTO.BARRAS AS BARRAS,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.REFERENCIA AS COD_FABRICANTE,
  PRODUTO.MARCA AS CARACTERISTICAS,
  PRODUTO.FORNECEDOR AS FORNECEDOR,
  PRODUTO.PRECO1 AS PRECO_VENDA,
  PRODUTO.ESTOQUE AS QTD,
  PRODUTO.LOTE AS PERSONAL2,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.DATA_ESTOQUE AS DATA_CADASTRO,
  PRODUTO.LUCRO_PERCENTUAL AS MARGEM_LUCRO,
  PRODUTO.CST AS ST,
  PRODUTO.OBS AS OBSERVACOES,
  PRODUTO.DATA_ALTERACAO AS ALTERACAO_PRECO
FROM PRODUTO
