SELECT 
       PES_00.PES_CODIGO AS CODIGO
      ,PES_00.PES_NOME AS NOME
      ,PES_00.PES_FANTASIA_OU_APELIDO AS FANTASIA
      ,PES_00.PES_ENDERECO AS ENDERECO
      ,PES_00.PES_NUMEROENDERECO AS NUMERO
      ,PES_00.PES_BAIRRO AS BAIRRO
      ,PES_00.PES_CIDADE AS CIDADE 
      ,PES_00.PES_UF AS UF
      ,PES_00.CEP_CODIGO AS CEP
      ,PES_00.PES_PONTOREFERENCIA AS COMPLEMENTO
      ,PES_00.PES_DDD_TELEFONE_1 AS TELEFONE
      ,PES_00.PES_DDD_CELULAR_1 AS CELULAR
      ,PES_00.PES_EMAIL AS EMAIL
      ,PES_00.PES_DATANASCIMENTO AS NASCIMENTO
      ,PES_00.PES_ESTADOCIVIL AS EST_CIVIL
      ,PES_CNPJ_CPF AS CNPJ_CNPF
      ,PES_IE_CI AS IE_RG     
      ,PES_00.PES_SEXO AS SEXO
      ,PES_00.PES_OBSERVACAO AS OBSERVACOES
      ,PES_00.PES_DATACADASTRO AS CADASTRO
  FROM NESKI_EXPRESS_DB.dbo.PES_00
where pes_00.pes_cliente = 'S'
