SELECT 
       ESTOQUE.CODG_PRODUTO AS CODIGO
      ,ESTGRUPO.NOME_GRUPO AS GRUPO
      ,ESTOQUE.CODIGO_PRODUTO AS COD_FABRICANTE
      ,ESTOQUE.CODIGO_EAN_PRODUTO AS BARRAS
      ,ESTOQUE.SITUACAO_TRIB_PRODUTO AS ST
      ,ESTOQUE.NOME_PRODUTO AS DESCRICAO
      ,ESTOQUE.QTDE_PRODUTO AS QTD
      ,ESTOQUE.UNIDADE_PRODUTO AS UND
      ,ESTOQUE.PRECO_CUSTO_PRODUTO AS PRECO_CUSTO
      ,ESTOQUE.PRECO_VAREJO_PRODUTO AS PRECO_VENDA
      ,ESTOQUE.PRECO_ATACADO_PRODUTO AS PRECO_ATACADO
      ,ESTOQUE.PRECO_MEDIO_PRODUTO AS CUSTO_MEDIO
      ,CAST (ESTOQUE.DATA_INCLUSAO_PRODUTO AS DATE) AS DATA_CADASTRO
      ,CAST (ESTOQUE.DATA_UTM_COMPRA_PRODUTO AS DATE) AS ULTIMA_COMPRA
      ,CAST (ESTOQUE.DATA_UTM_VENDA_PRODUTO AS DATE) AS ULTIMA_VENDA
      ,ESTOQUE.COMISSAO_PRODUTO AS COMISSAO
      ,ESTOQUE.NOME_FORNECEDOR_PRODUTO AS FORNECEDOR
      ,ESTOQUE.PESO_LIQUIDO_PRODUTO AS PESO
      ,ESTOQUE.REFERENCIA_PRODUTO AS CARACTERISTICAS
      ,ESTOQUE.OBS_PRODUTO AS OBSERVACOES
      ,ESTOQUE.CODIGO_MERCOSUL_PRODUTO AS COD_NCM
      ,ESTOQUE.CEST_PRODUTO AS PERSONAL6
      ,ESTOQUE.MARGEM_LUCRO_PRODUTO AS MARGEM_LUCRO
FROM ESTOQUE.dbo.ESTOQUE
LEFT JOIN ESTOQUE.dbo.ESTGRUPO ON ESTGRUPO.CODG_GRUPO = ESTOQUE.CODG_GRUPO_PRODUTO
