SELECT 
    PRODUTOS.ID AS COD_FABRICANTE,
    GRUPOS.descricao AS GRUPO,
    AGENTES.nome AS FORNECEDOR,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    VPRODS.ean AS BARRAS,
    ESTOQUE.qtde AS QTD,
    UNIMED.unidade AS UND,
    VALORESPROD.CUSTO AS PRECO_CUSTO,
    VALORESPROD.PRECO AS PRECO_VENDA,
    PRODST.cod_cest AS PERSONAL6,
    PRODUTOS.REF AS CARACTERISTICAS,
    CAST (PRODUTOS.DATACADASTRO AS DATE) AS DATA_CADASTRO,
    PRODUTOS.ESTQMIN AS QTD_MIN,
    SUBGRUPOS.descricao AS FAMILIA
FROM PRODUTOS
LEFT JOIN VALORESPROD ON VALORESPROD.idprod = PRODUTOS.ID
LEFT JOIN UNIMED ON UNIMED.ID = PRODUTOS.UNIDADE
LEFT JOIN PRODST ON PRODST.ID = PRODUTOS.ID
LEFT JOIN GRUPOS ON GRUPOS.id = PRODUTOS.grupo
LEFT JOIN ESTOQUE ON ESTOQUE.IDPROD = PRODUTOS.ID
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.ID = PRODUTOS.SUBGRUPO
LEFT JOIN FORNXFABR ON FORNXFABR.fabr = PRODUTOS.fabricante
LEFT JOIN AGENTES ON AGENTES.id = fornxfabr.forn
LEFT JOIN VPRODS ON VPRODS.id = PRODUTOS.ID
