SELECT TB_CLIENTE.ID_CLIENTE AS CODIGO,
TB_CLIENTE.DT_CADASTRO AS CADASTRO,
TB_CLIENTE.NOME,
TB_CLIENTE.END_CEP AS CEP,
TB_CLIENTE.END_NUMERO AS NUMERO,
TB_CLIENTE.END_TIPO||' '||TB_CLIENTE.END_LOGRAD AS ENDERECO,
TB_CLIENTE.END_BAIRRO AS BAIRRO,
TB_CLIENTE.END_COMPLE AS COMPLEMENTO,
TB_CLIENTE.CONTATO,
TB_CLIENTE.DDD_RESID||TB_CLIENTE.FONE_RESID AS TELEFONE,
TB_CLIENTE.DDD_CELUL||TB_CLIENTE.FONE_CELUL AS CELULAR,
TB_CIDADE_SIS.NOME AS CIDADE,
TB_CIDADE_SIS.SIGLA_UF AS UF,
COALESCE(TB_CLI_PF.CPF,TB_CLI_PJ.CNPJ) AS CNPJ_CNPF,
COALESCE(TB_CLI_PF.IDENTIDADE,TB_CLI_PJ.INSC_ESTAD) AS IE_RG
FROM TB_CLIENTE
LEFT JOIN TB_CIDADE_SIS ON TB_CLIENTE.ID_CIDADE=TB_CIDADE_SIS.ID_CIDADE
LEFT JOIN TB_CLI_PF ON TB_CLIENTE.ID_CLIENTE=TB_CLI_PF.ID_CLIENTE
LEFT JOIN TB_CLI_PJ ON TB_CLIENTE.ID_CLIENTE=TB_CLI_PJ.ID_CLIENTE
WHERE TB_CLIENTE.ID_CLIENTE>0





