SELECT TB_ESTOQUE.ID_ESTOQUE AS CODIGO,
TB_EST_PRODUTO.COD_BARRA AS BARRAS,
TB_EST_PRODUTO.REFERENCIA AS COD_FABRICANTE,
TB_EST_GRUPO.DESCRICAO AS GRUPO,
TB_ESTOQUE.DESCRICAO,
TB_ESTOQUE.DT_CADAST AS DATA_CADASTRO,
TB_ESTOQUE.PRC_VENDA AS PRECO_VENDA,
TB_ESTOQUE.PRC_CUSTO AS PRECO_CUSTO,
TB_ESTOQUE.ULT_VENDA AS ULTIMA_VENDA,
TB_ESTOQUE.UNI_MEDIDA AS UND,
TB_EST_PRODUTO.QTD_ATUAL AS QTD,
TB_EST_PRODUTO.COD_NCM,
TB_EST_PRODUTO.CSOSN AS ST,
TB_EST_PRODUTO.COD_CEST AS PERSONAL6,
TB_FORNECEDOR.NOME AS FORNECEDOR
FROM TB_ESTOQUE
LEFT JOIN TB_EST_PRODUTO ON TB_ESTOQUE.ID_ESTOQUE=TB_EST_PRODUTO.ID_IDENTIFICADOR
LEFT JOIN TB_EST_GRUPO ON TB_ESTOQUE.ID_GRUPO=TB_EST_GRUPO.ID_GRUPO
LEFT JOIN TB_FORNECEDOR ON TB_ESTOQUE.ULT_FORNEC=TB_FORNECEDOR.ID_FORNEC
WHERE TB_ESTOQUE.ULT_FORNEC IN (1,2,4)
