SELECT
    TB_ESTOQUE_RF.COD_ITEM AS CODIGO,
    TB_ESTOQUE_RF.NOME_ITEM AS DESCRICAO,
    TB_ESTOQUE_RF.NCM AS COD_NCM,
    TB_ESTOQUE_RF.CEST AS PERSONAL6,
    TB_ESTOQUE.est_atual AS QTD,
    TB_ESTOQUE.preco_1 AS PRECO_VENDA,
    TB_ESTOQUE.valor_custo AS PRECO_CUSTO,
    TB_ESTOQUE.custo_medio AS CUSTO_MEDIO,
    TB_ESTOQUE.cst AS ST,
    TB_ESTOQUE_IT.cod_ean  AS BARRAS
FROM TB_ESTOQUE_RF
LEFT JOIN tb_estoque ON TB_ESTOQUE_RF.cod_item = TB_ESTOQUE.cod_red
LEFT JOIN TB_ESTOQUE_IT ON TB_ESTOQUE_RF.cod_item = TB_ESTOQUE_IT.cod_item