SELECT
    P.PRO_CODIGO AS BARRAS,
    P.PRO_DESCRICAO AS DESCRICAO,
    G.GRU_DESCRICAO AS GRUPO,
    M.MAR_DESCRICAO AS CARACTERISTICAS,
    F.CRE_NOME AS FORNECEDOR,
    P.PRO_UNIDADE AS UND,
    P.PRO_PRCCUSTO AS PRECO_CUSTO,
    P.PRO_DATACADASTRO AS DATA_CADASTRO,
    P.PRO_DATAALTERACAO AS ALTERACAO_PRECO,
    case when P.PRO_SITUACAO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO,
    P.PRO_PESO AS PESO,
    P.PRO_NCM AS COD_NCM,
    MAX (CEST.CIS_CEST) AS PERSONAL6,
    --P.FAB_CODIGO AS COD_FABRICANTE,
    P.PRO_CODIGO AS COD_FABRICANTE,
    P.PRO_OBS AS OBSERVACOES,
    E.EST_APOIO AS QTD, 
    E.PRO_PRCMEDIO AS CUSTO_MEDIO,
    E.PRO_PRECO1 AS PRECO_VENDA,
    E.PRO_DTULTCOMPRA AS ULTIMA_COMPRA,
    E.PRO_DTULTVENDA AS ULTIMA_VENDA,
    E.ICM_CODIGO AS ST
FROM PRODUTOS AS P
LEFT JOIN ESTOQUE E ON E.PRO_CODIGO = P.PRO_CODIGO
LEFT JOIN GRUPOSPRO G ON G.GRU_CODIGO = P.GRU_CODIGO
LEFT JOIN MARCAS M ON M.MAR_CODIGO = P.MAR_CODIGO
LEFT JOIN TABELA_CEST CEST ON CEST.CIS_NCM = P.PRO_NCM
LEFT JOIN CREDORES F ON F.CRE_CODIGO = P.CRE_CODIGO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21
