select
  clientes.Codigo as codigo,
  clientes.Nome as nome,
  clientes.Apelido as fantasia,
  clientes.RG as ie_rg,
  clientes.CPF as cnpj_cnpf,
  clientes.Endereco as endereco,
  clientes.Complemento as complemento,
  clientes.Bairro as bairro,
  clientes.Num as numero,
  clientes.Cidade as cidade,
  clientes.UF as uf,
  clientes.CEP as cep,
  clientes.TelRes as telefone,
  clientes.TelCelular as celular,
  clientes.TelFax as fax,
  clientes.Email as email,
  clientes.Limite as limite_credito,
  clientes.OBS as observacoes,
  clientes.Sexo as sexo,
  clientes.Profissao as profissao,
  clientes.UltimaVenda as ultima_compra,
  clientes.Nascimento as nascimento,
  clientes.DataCad as cadastro
from clientes
