SELECT
    CODPRODUTO AS COD_FABRICANTE,
    DESCRIPTION AS DESCRICAO,
    -- ONHAND AS QTD,
    COST AS PRECO_CUSTO,
    LISTPRICE AS PRECO_VENDA,
    M_LUCRO AS MARGEM_LUCRO,
    NCM AS COD_NCM,
    CEST AS PERSONAL6
FROM TBPRODUTO
