SELECT
    CO_CLIENTE AS CODIGO,
    --DT_CADASTRO AS CADASTRO,
    NO_CLIENTE AS NOME,
    NU_CPF AS CNPJ_CNPF,
    DE_ENDERECO AS ENDERECO,
    NO_CIDADE AS CIDADE,
    CO_UF AS UF,
    NU_RG AS IE_RG,
    NO_FANTASIA AS FANTASIA,
    NU_CEP AS CEP,
    DE_EMAIL AS EMAIL,
    DE_BAIRRO AS BAIRRO,
    NU_TELEFONE1 AS TELEFONE,
    NU_TELEFONE2 AS CELULAR
FROM SISTB012_CLIENTE
