SELECT
    SISTB005_PRODUTO.CO_PRODUTO AS CODIGO,
    SISTB005_PRODUTO.CO_BARRAS AS BARRAS,
    SISTB005_PRODUTO.NO_ABREV_PRODUTO AS DESCRICAO,
    SISTB005_PRODUTO.VR_PRODUTO_CUSTO AS PRECO_CUSTO,
    SISTB005_PRODUTO.VR_PRODUTO AS PRECO_VENDA,
    SISTB005_PRODUTO.NU_ESTOQUE AS QTD,
    SISTB040_UNIDADE_MEDIDA.SG_UNIDADE_MEDIDA  AS UND,
    SISTB005_PRODUTO.CO_PRODUTO_CLIENTE AS COD_FABRICANTE,
    SISTB072_GRUPO_PRODUTO.DE_GRUPO_PRODUTO AS GRUPO,
    --SISTB005_PRODUTO.CO_BARRAS_FORNECEDOR AS BARRAS,
    REPLACE (SISTB005_PRODUTO.NU_NCM, '.', ' ') AS COD_NCM,
    SISTB051_TIPO_TRIBUTOS.co_tipo_tributos AS ST,
    REPLACE (SISTB005_PRODUTO.NU_CEST, '.', ' ') as CEST ,
    CAST (SISTB005_PRODUTO.DT_CADASTRO AS DATE) AS DATA_CADASTRO
FROM SISTB005_PRODUTO
LEFT JOIN SISTB040_UNIDADE_MEDIDA ON SISTB005_PRODUTO.IC_UNIDADE_MEDIDA = SISTB040_UNIDADE_MEDIDA.IC_UNIDADE_MEDIDA
LEFT JOIN SISTB072_GRUPO_PRODUTO  ON SISTB005_PRODUTO.NU_GRUPO_PRODUTO = SISTB072_GRUPO_PRODUTO.NU_GRUPO_PRODUTO
LEFT JOIN SISTB051_TIPO_TRIBUTOS ON SISTB051_TIPO_TRIBUTOS.nu_tipo_tributos = SISTB005_PRODUTO.nu_tipo_tributos_sn
WHERE SISTB005_PRODUTO.CO_PRODUTO < '999999'
