SELECT
    PRODUTO.CODIGO AS COD_FABRICANTE,
    GRUPO.NOME AS GRUPO,
    SUBGRUPO.NOME AS FAMILIA,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.MEDIDA AS UND,
    PRODUTO.PESO AS PESO,
    SUBSTRING (PRODUTO.TRIBUTACAO FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.TRIBUTACAO FROM 2 FOR 3) AS ST,
    PRODUTO.QUANTIDADE AS QTD,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO.MARGEMATUAL AS MARGEM_LUCRO,
    PRODUTO.VENDA AS PRECO_VENDA,
    PRODUTO.VENDATACADO AS PRECO_ATACADO,
    PRODUTO.NCM AS COD_NCM,
    CAST (PRODUTO.DATAHORINC AS DATE) AS DATA_CADASTRO,
    replace(PRODUTO.CEST,'.','') AS PERSONAL6
FROM PRODUTO
LEFT JOIN grupo ON GRUPO.codigo = PRODUTO.GRUPO
LEFT JOIN SUBgrupo ON SUBGRUPO.SUBGRUPO = PRODUTO.SUBGRUPO