SELECT
    PRODUTOS.CODPRODUTO AS CODIGO,
    PRODUTOS.CODBARRAS AS BARRAS,
    PRODUTOS.DSCPRODUTO AS DESCRICAO,
    PRODUTOS.DSCABREVIADA AS CARACTERISTICAS,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.PRECO_VENDA2 AS PRECO_VENDA,
    PRODUTOS.PRECO_ATACADO2 AS PRECO_ATACADO,
    PRODUTOS.PRECO_COMPRA AS PRECO_CUSTO,
    PRODUTOS.COD_NCM AS COD_NCM,
    PRODUTOS.COD_ORIGEM AS OST,
    PRODUTOS.COD_ICMS_SN AS ST,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.COD_CEST AS PERSONAL6,
    PRODUTOS.QTDE_ESTOQUE AS QTD
FROM PRODUTOS
