SELECT PRO_PRODUTO.PRO_ID AS CODIGO,
PRO_PRODUTO.PRO_CODIGO AS PERSONAL1,
GPR_GRUPO_PRODUTO.GPR_DESCRICAO AS GRUPO,
PRO_PRODUTO.PRO_COD_BARRAS AS BARRAS,
PRO_PRODUTO.PRO_DESCRICAO AS DESCRICAO,
PRO_PRODUTO.PRO_MARCA AS CARACTERISTICAS,
PRO_PRODUTO.PRO_TIPO_UNIDADE AS UND,
PRO_PRODUTO.PRO_PRECO1 AS PRECO_VENDA,
PRO_PRODUTO.PRO_CLASS_FISCAL AS COD_NCM,
CASE WHEN PRO_PRODUTO.PRO_COD_TRIB IS NULL THEN '000'
ELSE PRO_COD_TRIB END AS ST,
PRO_PRODUTO.PRO_CUSTO_TOTAL AS PRECO_CUSTO,
PRO_PRODUTO.PRO_DAT_CRI AS CADASTRO,
PRO_PRODUTO.PRO_DAT_ALT AS ALTERACAO_PRECO,
PRO_PRODUTO.PRO_CEST AS PERSONAL6,
PRO_PRODUTO.PRO_COD_PRO_FORNEC AS COD_FABRICANTE,
VLR_VALORES_PRODUTO.vlr_estoque AS QTD
FROM PRO_PRODUTO
LEFT JOIN GPR_GRUPO_PRODUTO ON PRO_PRODUTO.PRO_GPR_ID=GPR_GRUPO_PRODUTO.GPR_ID
LEFT JOIN VLR_VALORES_PRODUTO ON VLR_VALORES_PRODUTO.vlr_pro_id = PRO_PRODUTO.PRO_ID






