SELECT
  DSIAF006.PRO_COD AS CODIGO,
  DSIAF006.PRO_NOME AS DESCRICAO,
  DSIAF006.PRO_REF AS COD_FABRICANTE,
  case when PRO_GTIN = '' or PRO_GTIN is null then PRO_BARRA else PRO_GTIN END AS BARRAS,
  DSIAF005.GRU_NOME AS GRUPO,
  DSIAF019.SUB_NOME AS FAMILIA,
  SUBSTRING (DSIAF006.PRO_ST2 FROM 2 FOR 3) AS ST,
  DSIAF006.PRO_UNI AS UND,
  DSIAF006.PRO_CUSTO AS PRECO_CUSTO,
  DSIAF006.PRO_MEDIO AS CUSTO_MEDIO,
  DSIAF006.PRO_LUCRO AS MARGEM_LUCRO,
  DSIAF006.PRO_VENDA AS PRECO_VENDA,
  DSIAF006.PRO_EST AS QTD,
  DSIAF006.PRO_CAD AS DATA_CADASTRO,
  DSIAF006.PRO_CF AS COD_NCM
--DSIAF006.PRO_CEST AS PERSONAL6
FROM DSIAF006
LEFT JOIN DSIAF005 ON DSIAF005.GRU_COD = DSIAF006.GRU_COD
LEFT JOIN DSIAF019 ON DSIAF019.SUB_COD = DSIAF006.SUB_COD
