SELECT TB_PRODUTO.DESCRICAO,
TB_PRODUTO.DISPONIVEL AS QTD,
TB_PRODUTO.VLR_CUSTO AS PRECO_CUSTO,
TB_PRODUTO.VLR_VENDA AS PRECO_VENDA,
TB_PRODUTO.COD_BARRA AS BARRAS,
TB_PRODUTO.SIT_TRIBUTARIA AS ST,
TB_PRODUTO.COD_EXTERNO AS COD_FABRICANTE
FROM TB_PRODUTO

