SELECT
    TPE.ID_PESSOA AS CODIGO,
    TPE.NOME AS NOME,
    TPE.CNPJ_CPF AS CNPJ_CNPF,
    TPE.ENDERECO AS ENDERECO,
    TPE.NUMERO AS NUMERO,
    TPE.COMPLEMENTO AS COMPLEMENTO,
    TPE.BAIRRO AS BAIRRO,
    TC.DESCRICAO AS CIDADE,
    TC.ID_UF AS UF,
    TPE.CEP AS CEP,
    TPE.FONE AS TELEFONE,
    TPE.EMAIL AS EMAIL,
    case when TPE.ATIVO = 'S' then 'Ativo' else 'Inativo' end as situacao
FROM TB_PESSOA AS TPE
LEFT JOIN TB_CIDADE TC ON TPE.CIDADE = TC.COD_IBGE
WHERE TPE.ID_PESSOA > '0'