SELECT
    TPR.ID_PRODUTO AS CODIGO,
    TPR.DESCRICAO AS DESCRICAO,
    TPR.GTIN AS BARRAS,
    TPR.UND AS UND,
    TPR.QTDE_ESTOQUE AS QTD,
    TPR.VL_CUSTO AS PRECO_CUSTO,
    TPR.VL_UNITARIO AS PRECO_VENDA,
    TPR.ORIGEM AS OST,
    TPR.CST AS ST,
    TPR.CFOP AS CF,
    TPR.ID_CSTPIS AS PIS_CODIGO,
    TPR.PIS_ALIQUOTA AS PIS_ALIQ_NOR,
    100.00 AS PIS_BASE_NOR,
    TPR.ID_CSTCOFINS AS COFINS_CODIGO,
    TPR.COFINS_ALIQUOTA AS COFINS_ALIQ_NOR,
    100.00 AS COFINS_BASE_NOR,
    TPR.NCM AS COD_NCM,
    TPR.CEST AS PERSONAL6,
    case when TPR.ATIVO = 'S' then 'Ativo' else 'Inativo' end as situacao
FROM TB_PRODUTO AS TPR
WHERE TPR.ID_PRODUTO > '0'