SELECT
    GE_PESSOA.ID_PESSOA AS CODIGO,
    GE_PESSOA.RAZAO AS NOME,
    GE_PESSOA.FANTASIA AS FANTASIA,
    case when GE_PESSOA_FISICA.CPF = '' or GE_PESSOA_FISICA.CPF is null then GE_PESSOA_JURIDICA.CNPJ else GE_PESSOA_FISICA.CPF END AS CNPJ_CNPF,
    case when GE_PESSOA_FISICA.RG = '' or GE_PESSOA_FISICA.RG is null then GE_PESSOA_JURIDICA.INSC_ESTADUAL else GE_PESSOA_FISICA.RG END AS IE_RG,
    GE_PESSOA_JURIDICA.INSC_MUNICIPAL AS IM,
    GE_PESSOA_ENDERECO.ENDERECO AS ENDERECO,
    GE_PESSOA_ENDERECO.COMPLEMENTO AS COMPLEMENTO,
    GE_PESSOA_ENDERECO.BAIRRO AS BAIRRO,
    GE_PESSOA_ENDERECO.CEP AS CEP,
    GE_CIDADE.nome AS CIDADE,
    GE_ESTADO.id_estado AS UF,
    GE_PESSOA_ENDERECO.TELEFONE AS TELEFONE,
    GE_PESSOA_ENDERECO.CELULAR AS CELULAR,
    GE_PESSOA_ENDERECO.FAX AS FAX,
    GE_PESSOA_ENDERECO.EMAIL AS EMAIL,
    CAST (GE_PESSOA_FISICA.DT_NASCIMENTO AS DATE) AS NASCIMENTO,
    GE_PESSOA_FISICA.NOME_PAI AS PAI,
    GE_PESSOA_FISICA.NOME_MAE AS MAE,
    GE_PESSOA_FISICA.ESTADO_CIVIL AS EST_CIVIL,
    GE_PESSOA_FISICA.NOME_CONJUGE AS CONJUGE,
    GE_PESSOA_FISICA.SEXO AS SEXO
FROM GE_PESSOA
LEFT JOIN GE_PESSOA_ENDERECO ON GE_PESSOA_ENDERECO.ID_PESSOA = GE_PESSOA.ID_PESSOA
LEFT JOIN GE_CIDADE ON GE_CIDADE.id_cidade = GE_PESSOA_ENDERECO.id_cidade
LEFT JOIN GE_ESTADO ON GE_ESTADO.id_estado = GE_CIDADE.id_estado
LEFT JOIN GE_PESSOA_FISICA ON GE_PESSOA_FISICA.id_pessoa = GE_PESSOA.id_pessoa
LEFT JOIN GE_PESSOA_JURIDICA ON GE_PESSOA_JURIDICA.id_pessoa = GE_PESSOA.id_pessoa
WHERE GE_PESSOA.tipo_pessoa = 'F';
