SELECT
    ES_PRODUTO.ID_PRODUTO AS CODIGO,
    ES_PRODUTO.DESCRICAO AS DESCRICAO,
    ES_PRODUTO.CODIGO_BARRAS AS BARRAS,
    SUM (ES_PROSALDO.QUANTIDADE) AS QTD,
    MIN (ES_PROSALDO.CUSTOMEDIO) AS CUSTO_MEDIO,
    ES_PRODUTO_EMPRESA.PRECO_VENDA AS PRECO_VENDA,
    ES_PRODUTO_EMPRESA.PRECO_COMPRA AS PRECO_CUSTO,
    ES_PRODUTO_EMPRESA.PRECO_ATACADO AS PRECO_ATACADO,
    ES_PRODUTO.CODFAB AS COD_FABRICANTE,
    ES_GRUPO.DESCRICAO AS GRUPO,
    ES_PRODUTO.CODIGO_FISCAL AS COD_NCM,
    GE_PESSOA.razao AS FORNECEDOR,
    ES_PRODUTO.CSTPIS AS PIS_CODIGO,
    ES_PRODUTO.CSTCOFINS AS COFINS_CODIGO,
    ES_PRODUTO.CSTIPI AS IPI_CODIGO,
    ES_PRODUTO.CSOSN AS ST,  
    ES_PRODUTO.ID_UNIDADE AS UND,
    ES_PRODUTO.PESO_LIQUIDO AS PESO,
    ES_PRODUTO.OBSERVACOES AS OBSERVACOES,
    CAST (ES_PRODUTO.DT_CADASTRO AS DATE) AS DATA_CADASTRO,
    CAST (ES_PRODUTO.DATA_ATUALIZACAO AS DATE) AS ALTERACAO_PRECO,
    ES_PRODUTO.CEST AS PERSONAL6
FROM ES_PRODUTO
LEFT JOIN ES_PRODUTO_EMPRESA ON ES_PRODUTO_EMPRESA.id_produto = ES_PRODUTO.id_produto
LEFT JOIN ES_PROSALDO on ES_PROSALDO.id_produto = ES_PRODUTO.id_produto
LEFT JOIN ES_GRUPO ON ES_GRUPO.id_grupo = ES_PRODUTO.id_grupo
LEFT JOIN ge_pessoa ON GE_PESSOA.id_pessoa = ES_PRODUTO.id_fornecedor
GROUP BY 1,2,3,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22;
