SELECT
    CAST (FN_RECEBER.ID_RECEBER AS INTEGER) ||'/'|| FN_RECEBER.fg_origem AS DOCUMENTO,
    FN_TIPO_DOC.descricao AS TIPO_DOC,
    GE_PESSOA.id_pessoa AS COD_CLIENTE,
    GE_PESSOA.razao AS NOM_CLIENTE,
    CAST (FN_RECEBER.DT_LANCAMENTO AS DATE) AS EMISSAO,
    CAST (FN_RECEBER.DT_VENCTO AS DATE) AS VENCIMENTO,
    CAST (FN_RECEBER.DT_PAGTO AS DATE) AS RECEBIMENTO,
    FN_CONTA.descricao AS CONTA,
    FN_RECEBER.HISTORICO ||'-/-'|| FN_RECEBER.NR_NOTA AS HISTORICO,
    FN_RECEBER.NR_BANCO AS BANCO,
    FN_RECEBER.VR_PARCELA AS VALOR_DUP,
    FN_RECEBER.VR_PAGO AS VALOR_REC,
    FN_RECEBER.VR_JURO AS VALOR_JUR,
    FN_RECEBER.VR_DESC AS VALOR_DES,
    case when GE_PESSOA_FISICA.CPF = '' or GE_PESSOA_FISICA.CPF is null then GE_PESSOA_JURIDICA.CNPJ else GE_PESSOA_FISICA.CPF END AS CNPJ
FROM FN_RECEBER
LEFT JOIN GE_PESSOA ON GE_PESSOA.id_pessoa = FN_RECEBER.id_pessoa
LEFT JOIN FN_TIPO_DOC ON FN_TIPO_DOC.id_tipo_doc = FN_RECEBER.ID_TIPO_DOC
LEFT JOIN FN_CONTA ON FN_CONTA.id_conta = FN_RECEBER.ID_CTA_COBRANCA
LEFT JOIN GE_PESSOA_FISICA ON GE_PESSOA_FISICA.id_pessoa = FN_RECEBER.id_pessoa
LEFT JOIN GE_PESSOA_JURIDICA ON GE_PESSOA_JURIDICA.id_pessoa = FN_RECEBER.id_pessoa

