SELECT
  PESSOA.ID AS CODIGO,
  PESSOA.CLIENTE,
  PESSOA.NOME AS NOME,
  PESSOA.NOME_FANTASIA AS FANTASIA,
  PESSOA.CNPJ_CPF AS CNPJ_CNPF,
  PESSOA.INSC_MUNICIPAL AS IM,
  case when PESSOA.INSC_ESTADUAL = '' or PESSOA.INSC_ESTADUAL is null then PESSOA.RG else PESSOA.INSC_ESTADUAL END as IE_RG,
  PESSOA.CEP AS CEP,
  PESSOA.RUA AS ENDERECO,
  PESSOA.NUMERO AS BAIRRO,
  PESSOA.COMPLEMENTO AS COMPLEMENTO,
  PESSOA.BAIRRO AS BAIRRO,
  PESSOA.CIDADE AS CIDADE,
  PESSOA.UF AS UF,
  PESSOA.DDD ||''||PESSOA.FONE AS TELEFONE,
  PESSOA.DDD ||''||PESSOA.FAX AS FAX,
  PESSOA.CONTATO AS CONTATO,
  PESSOA.DDD ||''||PESSOA.CELULAR AS CELULAR,
  PESSOA.EMAIL AS EMAIL,
  PESSOA.OBSERVACOES AS OBSERVACOES
FROM PESSOA
WHERE PESSOA.FORNECEDOR = 'S';
