SELECT
  PESSOA.ID AS CODIGO,
  PESSOA.NOME AS RAZAO_SOCIAL,
  PESSOA.CNPJ_CPF AS CNPJ,
  case when PESSOA.INSC_ESTADUAL = '' or PESSOA.INSC_ESTADUAL is null then PESSOA.RG else PESSOA.INSC_ESTADUAL END as IE,
  PESSOA.RUA AS ENDERECO,
  PESSOA.CIDADE AS CIDADE,
  PESSOA.UF AS UF,
  PESSOA.DDD ||''||PESSOA.FONE AS TELEFONE,
  PESSOA.EMAIL AS EMAIL
FROM PESSOA
WHERE PESSOA.TRANSPORTADORA = 'S'
