SELECT CLIENTE.`cli_cod` AS CODIGO,
CAST(CLIENTE.`cli_dtcadastro` AS DATE) AS CADASTRO,
CLIENTE.`cli_nomecurto` AS FANTASIA,
CLIENTE.CLI_NOME AS NOME,
CLIENTE.`cli_endereco` AS ENDERECO,
CLIENTE.`cli_numero` AS NUMERO,
CLIENTE.`cli_complemento` AS COMPLEMENTO,
CLIENTE.`cli_bairro` AS BAIRRO,
CIDADE.`cid_nome` AS CIDADE,
UF.`uf_sigla` AS UF,
CLIENTE.CLI_CEP AS CEP,
CLIENTE.`cli_dtnascimento` AS NASCIMENTO,
CLIENTE.`cli_cnpj` AS CNPJ_CNPF,
CLIENTE.`cli_ie` AS IE_RG,
CLIENTE.CLI_FONE AS TELEFONE,
CLIENTE.`cli_fax` AS FAX,
CLIENTE.CLI_CONTATO AS CONTATO,
CLIENTE.`cli_email` AS EMAIL,
CLIENTE.CLI_OBS AS OBSERVACOES,
CLIENTE.`cli_celular` AS CELULAR
FROM CLIENTE
LEFT JOIN CIDADE ON CLIENTE.`cli_cidade`=CIDADE.`cid_cod`
LEFT JOIN UF ON CLIENTE.CLI_UF=UF.UF_COD
