SELECT
  DSIAF009.FOR_COD AS CODIGO,
  DSIAF009.FOR_RAZAO AS NOME,
  DSIAF009.FOR_NOME AS FANTASIA,
  DSIAF009.FOR_CONT AS CONTATO,
  case when DSIAF009.FOR_CGC = '' or DSIAF009.FOR_CGC is null then DSIAF009.FOR_CPF else DSIAF009.FOR_CGC END AS CNPJ_CNPF,
  case when DSIAF009.FOR_INSC = '' or DSIAF009.FOR_INSC is null then DSIAF009.FOR_INSCP else DSIAF009.FOR_INSC END AS IE_RG,
  DSIAF009.FOR_END AS ENDERECO,
--  DSIAF009.FOR_END_NUM AS NUMERO,
  DSIAF009.FOR_BAI AS BAIRRO,
  DSIAF009.FOR_CEP AS CEP,
  DSIAF009.FOR_CID AS CIDADE,
  DSIAF009.FOR_EST AS UF,
  DSIAF009.FOR_MAIL AS EMAIL,
  DSIAF009.FOR_FONE AS TELEFONE,
--  DSIAF009.FOR_CEL AS CELULAR,
  DSIAF009.FOR_FAX AS FAX,
  DSIAF009.FOR_OBS AS OBSERVACOES
FROM DSIAF009
