select PRODUTOS.CODIGO,
GR_PROD.NOME AS GRUPO,
CASE WHEN PRODUTOS.NOME ='' THEN PRODUTOS.NOMEPDV ELSE
PRODUTOS.NOME END AS DESCRICAO,
PRODUTOS.CODIGO_MERCOSUL AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6,
PRODUTOS.SIT_TRIB AS ST,
PRODUTOS.CODIGO_BARRA AS BARRAS,
PRODUTOS.CODIGO_FABRICANTE AS COD_FABRICANTE,
PRODUTOS.PCO_VENDA AS PRECO_VENDA,
PRODUTOS.PCO_ATACADO AS PRECO_ATACADO,
PRODUTOS.PCO_CUSTO AS PRECO_CUSTO,
PRODUTOS.CUSTO_MEDIO,
PRODUTOS.ESTOQUE_ATUAL_FILIAL1 AS QTD,
PRODUTOS.DATA_CADASTRO,
PRODUTOS.MEDIDA AS UND,
PRODUTOS.DATA_ULT_ENTRADA AS ULTIMA_COMPRA,
PRODUTOS.DATA_ULT_SAIDA AS ULTIMA_VENDA
FROM PRODUTOS
LEFT JOIN GR_PROD ON PRODUTOS.CODIGO_GRUPO=GR_PROD.CODIGO

