SELECT
  FORN.CODI AS CODIGO,
  FORN.NOME AS NOME,
  FORN.ENDE AS ENDERECO,
  FORN.CIDA  AS CIDADE,
  FORN.BAIR AS BAIRRO,
  FORN.ESTA AS UF,
  FORN.CEPC AS CEP,
  FORN.FAXC AS FAX,
  case when FORN.NCPF = '' or FORN.NCPF is null then FORN.CGCC else FORN.NCPF END as CNPJ_CNPF,
  FORN.INSC as IE_RG,
  FORN.CONT AS CONTATO,
  FORN.OBS1 AS OBSERVACOES,
  FORN.FON1 AS TELEFONE,
  FORN.FON2 AS CELULAR,
  FORN.EMAIL AS EMAIL
FROM FORN
