SELECT 
       CADCLI.CLIENTE AS CODIGO
      ,CADCLI.NOME AS NOME
      ,CADCLI.FANTASIA AS FANTASIA
      ,CADCLI.NOMERECADO AS CONTATO
      ,CADCLI.IDENTIDADE AS IE_RG
      ,CADCLI.CPF AS CNPJ_CNPF
      ,CADCLI.ENDERECO AS ENDERECO
      ,CADCLI.ENDERECOCOMPL AS COMPLEMENTO
      ,CADCLI.ENDERECONUMERO AS NUMERO
      ,CADCLI.BAIRRO AS BAIRRO
      ,CADCLI.CIDADE AS CIDADE
      ,CADCLI.ESTADO AS UF
      ,CADCLI.REFERENCIA AS OBSERVACOES
      ,CADCLI.CEP AS CEP
      ,CADCLI.FONE AS TELEFONE
      ,CADCLI.FAX AS FAX
      ,CADCLI.CELULAR AS CELULAR
      ,CADCLI.E_MAIL AS EMAIL
      ,CADCLI.PAI AS PAI
      ,CADCLI.MAE AS MAE
      ,CADCLI.NASCIMENTO AS NASCIMENTO
      ,CADCLI.SEXO AS SEXO
      ,CADCLI.ESTADOCIVIL AS EST_CIVIL
      ,CADCLI.CONJUGE AS CONJUGE
      ,LIMITE_CREDITO AS LIMITE_CREDITO
      ,CADCLI.DATA_INC AS CADASTRO
  FROM Empresario.dbo.CADCLI
  WHERE CADCLI.CLIENTE <> '999999'
