SELECT 
       CADPRO.ID AS CODIGO
      ,CADPRO.DESCRICAO AS DESCRICAO
      ,CADPRO.CODIGO_BARRA AS BARRAS
      ,CADPRO.REFERENCIA AS COD_FABRICANTE
      ,CADFOR.RAZAO_SOCIAL AS FORNECEDOR
      ,CADPRO.UNIDADEPRODUTOID AS UND
      ,CADPRO.OBSERVACAO AS OBSERVACOES
      ,CADPRO.CODIGONCM AS COD_NCM
      ,CADPRO.DATA AS DATA_CADASTRO
      ,CADPRO.CESTFISCALID AS PERSONAL6
      ,substring (CADPRO.CSTICMSID, 1,1) as OST
      ,substring (CADPRO.CSTICMSID, 2,3) as ST
      ,ESTGRU.DESCRICAO AS GRUPO
	  ,ESTSAL.VRVENDAV AS PRECO_VENDA
      ,ESTSAL.VRMEDIOV AS CUSTO_MEDIO
      ,ESTSAL.VRCUSTOV AS PRECO_CUSTO
      ,ESTSAL.LUCROV AS MARGEM_LUCRO
      ,ESTSAL.ESTOQUEATUAL AS QTD
  FROM Empresario.dbo.CADPRO
  LEFT JOIN Empresario.dbo.ESTSAL ON ESTSAL.MATRICULA = CADPRO.ID and ESTSAL.FILIAL = '1' --- AJUSTAR ID DA LOJA (TABELA FILIAL)
  LEFT JOIN Empresario.dbo.CADFOR ON CADFOR.FORNECEDOR = CADPRO.FORNECEDOR
  LEFT JOIN Empresario.dbo.ESTGRU ON ESTGRU.ID = CADPRO.GRUPO
