SELECT
    TFORNECEDOR.CONTROLE AS CODIGO,
    TFORNECEDOR.RAZAOSOCIAL AS NOME,
    TFORNECEDOR.NOMEFANTASIA AS FANTASIA,
    case when TFORNECEDOR.CPF = '' or TFORNECEDOR.CPF is null then TFORNECEDOR.CNPJ else TFORNECEDOR.CPF END AS CNPJ_CNPF,
    case when TFORNECEDOR.RG = '' or TFORNECEDOR.RG is null then TFORNECEDOR.IE else TFORNECEDOR.RG END AS IE_RG,
    TFORNECEDOR.IM AS IM,
    TFORNECEDOR.ENDERECO AS ENDERECO,
    TFORNECEDOR.NUMERO AS NUMERO,
    TFORNECEDOR.BAIRRO AS BAIRRO,
    TFORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    TFORNECEDOR.TELEFONE AS TELEFONE,
    TFORNECEDOR.CELULAR AS CELULAR,
    TFORNECEDOR.CIDADE AS CIDADE,
    TFORNECEDOR.UF AS UF,
    TFORNECEDOR.CEP AS CEP,
    TFORNECEDOR.EMAIL AS EMAIL,
    TFORNECEDOR.OBS AS OBSERVACOES
FROM TFORNECEDOR
