SELECT
    PRODUTO.IDPRODUTO AS CODIGO,
    PRODUTO.EAN AS BARRAS,
    PRODUTO.DESCRICAOPRODUTO AS DESCRICAO,
    PRODUTO.IDUNIDMEDIDA AS UND,
    GRUPO.DESCRICAOGRUPO AS GRUPO,
    PRODUTO.PESOLIQUIDO AS PESO, 
    PRODUTO.ESTOQUEMINIMO AS QTD_INICIAL,
    ESTOQUE.QTDEESTOQUE AS QTD,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO.MARGEMAVISTA AS MARGEM_LUCRO,
    PRODUTO.PRECOGONDOLA AS PRECO_VENDA,
    PRODUTO.REFFABRICANTE AS COD_FABRICANTE,
    PRODUTO.ORIGEM AS OST,
    PRODUTO.CST_ICMS AS ST,
    PRODUTO.OBSPROD AS OBSERVACOES,
    PRODUTO.DTREAJUSTE AS ALTERACAO_PRECO,
    PRODUTO.DATACADASTRO AS DATA_CADASTRO,
    ESTOQUE.ULTDATAENTRADA AS ULTIMA_COMPRA,
    ESTOQUE.ULTDATASAIDA AS ULTIMA_VENDA,
    PRODUTO.NCM AS COD_NCM,
    MAX (CEST.cest) AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.IDGRUPO = PRODUTO.IDGRUPO
LEFT JOIN ESTOQUE ON ESTOQUE.IDPRODUTO = PRODUTO.IDPRODUTO
LEFT JOIN CEST ON CEST.ncm = PRODUTO.NCM
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
