SELECT
    PESSOA.CODIGO AS CODIGO,
    PESSOA.CNPJ AS CNPJ_CNPF,
    PESSOA.IE AS IE_RG,
    PESSOA.FANTASIA AS FANTASIA,
    PESSOA.RAZAO AS NOME,
    PESSOA.ENDERECO AS ENDERECO,
    PESSOA.NUMERO AS NUMERO,
    PESSOA.COMPLEMENTO AS COMPLEMENTO,
    PESSOA.MUNICIPIO AS CIDADE,
    PESSOA.BAIRRO AS BAIRRO,
    PESSOA.UF AS UF,
    PESSOA.CEP AS CEP,
    PESSOA.FONE1 AS TELEFONE,
    PESSOA.CELULAR1 AS CELULAR,
    PESSOA.EMAIL1 AS EMAIL,
    PESSOA.OBS AS OBSERVACOES
FROM PESSOA
WHERE PESSOA.FORN = 'S'