SELECT
  PRODUTO.CODI AS BARRAS,
  PRODUTO.CDPRO AS COD_FABRICANTE,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.NOME AS DESCRICAO,
  PRODUTO.MARCA AS GRUPO,
  PRODUTO.UNID AS UND,
  FORNEC.nome AS FORNECEDOR,
  -- PRODUTO.ESTOQUE AS QTD,
  PRODUTO.CUSTO AS PRECO_CUSTO,
  PRODUTO.MEDIO AS CUSTO_MEDIO,
  PRODUTO.LUCROV AS MARGEM_LUCRO,
  PRODUTO.VENDA AS PRECO_VENDA,
  PRODUTO.ATACADO AS PRECO_ATACADO,
  PRODUTO.CESTABAS AS PERSONAL6
FROM PRODUTO
LEFT JOIN FORNEC ON PRODUTO.CDFOR = FORNEC.CODI
