SELECT
    IDCLIENTE AS CODIGO,
    NOME AS NOME,
    CPF AS CNPJ_CNPF,
    SEXO AS SEXO,
    DATANASCIMENTO AS NASCIMENTO,
    FONE1 AS TETEFONE,
    FONE2 AS CELULAR,
    UF AS UF,
    CIDADE AS CIDADE,
    BAIRRO AS BAIRRO,
    CEP AS CEP,
    RUA AS ENDERECO,
    NUMERO AS NUMERO,
    CREDITO AS LIMITE_CREDITO,
    APELIDO AS FANTASIA
FROM CLIENTE
