SELECT
    --replace(PRODUTO.PROCOD,'.','') AS CODIGO,
    PRODUTO.PROCOD AS CODIGO,
    PRODUTO.PRODES AS DESCRICAO,
    PRODUTO.PROUNDMED AS UND,
    MAX (PRODUTO_AUXILIAR.CODBARRAS) AS BARRAS,
    SALDOESTOQUE.QUANTIDADE AS QTD,
    PRODUTO.PROPREVND AS PRECO_VENDA,
    PRODUTO.PROREF AS COD_FABRICANTE
FROM PRODUTO
LEFT JOIN PRODUTO_AUXILIAR ON PRODUTO_AUXILIAR.PROCOD = PRODUTO.PROCOD
LEFT JOIN SALDOESTOQUE ON saldoestoque.IDPRODUTO = PRODUTO.PROCOD
GROUP BY 1,2,3,5,6,7