SELECT
  PRODUTOS.codigo AS CODIGO,
  PRODUTOS.descricao AS DESCRICAO,
  PRODUTOS.margem AS MARGEM_LUCRO,
  PRODUTOS.pcusto AS PRECO_CUSTO,
  PRODUTOS.ppendente AS PRECO_VENDO,
  PRODUTOS.estoque AS QTD,
  GPROD.DESCRICAO AS GRUPO,
  SUBPROD.DESCRICAO AS FAMILIA,
  PRODUTOS.stributa AS ST,
  PRODUTOS.peso AS PESO,
  FORNECEDORES.RAZAO AS FORNECEDOR,
  PRODUTOS.descrpdv AS CARACTERISTICAS,
  PRODUTOS.ncm AS COD_NCM,
  PRODUTOS.codbar AS BARRAS
FROM PRODUTOS
LEFT JOIN GPROD ON GPROD.CODIGO = PRODUTOS.GRUPO
LEFT JOIN SUBPROD ON SUBPROD.CODIGO = PRODUTOS.SUBGRUPO
LEFT JOIN FORNECEDORES ON FORNECEDORES.ID = PRODUTOS.CODFORNECE
