select
  tbcliente.chave as codigo,
  tbcliente.nome as nome,
  tbcliente.apelido as fantasia,
  tbcliente.contato as contato,
  tbcliente.cpf as cnpj_cnpf,
  tbcliente.rg as ie_rg,
  tbcliente.logradouro as endereco,
  tbcliente.complemento as complemento,
  tbcliente.numero as numero,
  tbcliente.bairro as bairro,
  tbcliente.cep as cep,
  tbcliente.uf as uf,
  tbcliente.municipio as cidade,
  tbcliente.fone as telefone,
  tbcliente.celular as celular,
  tbcliente.email as email,
  tbcliente.observacao as observacoes,
  tbcliente.pai as pai,
  tbcliente.mae as mae,
  tbcliente.nascimento as nascimento,
  tbcliente.estado_civil as est_civil,
  tbcliente.conjuge as conjuge,
  tbcliente.sexo as sexo,
  tbcliente.data_ultima_compra as ultima_compra,
  tbcliente.data as cadastro
from tbcliente
