SELECT
    TFORNECEDOR.CODIGO AS CODIGO,
    TFORNECEDOR.NOME AS NOME,
    TFORNECEDOR.NOME_FANTASIA AS FANTASIA,
    TFORNECEDOR.CPF_CNPJ AS CNPJ_CNPF,
    TFORNECEDOR.INSCRICAO_ESTADUAL_RG AS IE_RG,
    TFORNECEDOR.LOGRADOURO AS ENDERECO,
    TFORNECEDOR.NUMERO AS NUMERO,
    TFORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    TFORNECEDOR.BAIRRO AS BAIRRO,
    TCIDADE.NOM_CIDADE AS CIDADE,
    TFORNECEDOR.UF AS UF,
    TFORNECEDOR.CEP AS CEP,
    TFORNECEDOR.TELEFONE1 AS TELEFONE,
    TFORNECEDOR.CELULAR AS CELULAR,
    TFORNECEDOR.DS_EMAIL AS EMAIL,
    TFORNECEDOR.OBSERVACAO AS OBSERVACOES
FROM TFORNECEDOR
LEFT JOIN TCIDADE ON TCIDADE.COD_CIDADE = TFORNECEDOR.COD_CIDADE