SELECT
    CODPESSOA AS CODIGO,
    NOME AS NOME,
    PESSOA,
    CPFCGC AS CNPJ_CNPF,
    case when RG = '' or RG is null then IE else RG END AS IE_RG,
    IM AS IM,
    EMAIL AS EMAIL,
    FONES AS TELEFONE,
    FAX AS FAX,
    LOGRADOURO_1 AS ENDERECO,
    COMPLEMENTO_1 AS COMPLEMENTO,
    BAIRRO_1 AS BAIRRO,
    CIDADE_1 AS CIDADE,
    UF_1 AS UF,
    CEP_1 AS CEP,
    CELULAR AS CELULAR,
    NOMEFANTAZIA AS FANTASIA,
    PESSOA_CONTATO AS CONTATO,
    OBS AS OBSERVACOES,
    NUMERO_1 AS NUMERO
FROM PESSOA
WHERE PESSOA = '2' ---FORNECEDORES
