SELECT
    COLABORADOR.COL_COD AS CODIGO,
    COLABORADOR.COL_RAZ AS NOME,
    COLABORADOR.COL_NMF AS FANTASIA,
    COLABORADOR.COL_APE AS CONTATO,
    COLABORADOR.COL_INF AS CNPJ_CNPF,
    COLABORADOR.COL_INE AS IE_RG,
    COLABORADOR.COL_INM AS IM,
    --COLABORADOR.COL_DTI AS CADASTRO,
    COLABORADOR.COL_END AS ENDERECO,
    COLABORADOR.COL_NRO AS NUMERO,
    COLABORADOR.COL_CPL AS COMPLEMENTO,
    COLABORADOR.COL_BAI AS BAIRRO,
    MUNICIPIO.MUN_NOM AS CIDADE,
    MUNICIPIO.MUN_EST AS UF,
    COLABORADOR.COL_CEP AS CEP,
    COLABORADOR.COL_DDD  ||''|| COLABORADOR.COL_FON AS TELEFONE,
    COLABORADOR.COL_DDF  ||''|| COLABORADOR.COL_FAX AS FAX,   
    COLABORADOR.COL_DDC  ||''|| COLABORADOR.COL_CEL AS CELULAR,    
    COLABORADOR.COL_EMA AS EMAIL,
    COLABORADOR.COL_PAE AS PAI,
    COLABORADOR.COL_MAE AS MAE,
    COLABORADOR.COL_CJG AS CONJUGE
FROM COLABORADOR
LEFT JOIN MUNICIPIO ON MUNICIPIO.MUN_COD = COLABORADOR.COL_MUN
WHERE COLABORADOR.COL_TIP = 'CPF' ---CLIENTES
