SELECT
    SUBSTRING (PRODUTO.PRO_COD FROM 4 FOR 10) AS CODIGO,
    PRODUTO.PRO_EAN AS BARRAS,
    PRODUTO.PRO_NOM AS DESCRICAO,
    PRODUTO.PRO_UND AS UND,
    PRODUTO.PRO_PSL AS PESO,
    GRUPO.GRU_NOM AS GRUPO,
    SUBGRUPO.SGR_NOM AS FAMILIA,
    MARCA.MAR_NOM AS CARACTERISTICAS,
    COLABORADOR.COL_RAZ AS FORNECEDOR,
   (select FIRST 1 PRODUTOLOCAL.PRL_SLD from PRODUTOLOCAL where PRODUTOLOCAL.PRL_PRO = PRODUTO.PRO_COD AND PRODUTOLOCAL.PRL_LCD = '1' order by PRODUTO.PRO_COD ASC) as QTD,
   (select FIRST 1 PRODUTOFILIAL.PRF_CMO from PRODUTOFILIAL where PRODUTOFILIAL.PRF_PRO = PRODUTO.PRO_COD AND PRODUTOFILIAL.prf_fil = '1' order by PRODUTO.PRO_COD ASC) as CUSTO_MEDIO,
   (select FIRST 1 PRODUTOFILIAL.PRF_PCA from PRODUTOFILIAL where PRODUTOFILIAL.PRF_PRO = PRODUTO.PRO_COD AND PRODUTOFILIAL.prf_fil = '1' order by PRODUTO.PRO_COD ASC) as PRECO_CUSTO,
   (select FIRST 1 PRODUTOFILIAL.PRF_PRC from PRODUTOFILIAL where PRODUTOFILIAL.PRF_PRO = PRODUTO.PRO_COD AND PRODUTOFILIAL.prf_fil = '1' order by PRODUTO.PRO_COD ASC) as PRECO_VENDA,
    PRODUTO.PRO_CCP AS COD_FABRICANTE,
    PRODUTO.PRO_OBS AS OBSERVACOES,
    PRODUTO.PRO_NCM AS COD_NCM,
    CEST.CES_COD AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.GRU_COD = PRODUTO.PRO_GRU
LEFT JOIN MARCA ON MARCA.MAR_COD = PRODUTO.PRO_MAR
LEFT JOIN CEST ON CEST.CES_NCM = PRODUTO.PRO_NCM
LEFT JOIN COLABORADOR ON COLABORADOR.COL_COD = PRODUTO.PRO_FOR 
LEFT JOIN SUBGRUPO ON SUBGRUPO.SGR_COD = PRODUTO.PRO_SGR AND SUBGRUPO.SGR_GRU = GRUPO.GRU_COD
