SELECT 
  CODCLI AS CODIGO
, NOMECLI AS NOME
, NOMEFANTASIA AS FANTASIA
, ENDCLI AS ENDERECO
, COMPLEMENTOCLI AS COMPLEMENTO
, NUMERO
, CIDADECLI AS CIDADE
, BAIRROCLI AS BAIRRO
, ESTADOCLI AS UF
, CEPCLI AS CEP
, CONCAT(DDDCLI, FONECLI) AS TELEFONE
, CONCAT(DDDFAX, FONEFAX) AS FAX
, CONCAT(DDDCELULAR, CELULAR) AS CELULAR
, LIMCREDITO AS LIMITE_CREDITO
, E_MAIL AS EMAIL
, CONTATO
, OBS AS OBSERVACOES
, CARGO AS PROFISSAO
, CEPCOB AS COB_CEP
, BAIRROCOB AS COB_BAIRRO
, CIDADECOB AS COB_CIDADE
, UFCOB AS COB_UF
, ENDCOB AS COB_ENDERECO
, COMPLEMENTOCOB AS COB_COMPLEMENTO
, NUMEROCOB AS COB_NUMERO
, CASE WHEN RG = '' OR RG IS NULL THEN INSCESTCLI ELSE RG END AS IE_RG
, CASE WHEN CPFCLI = '' OR CPFCLI IS NULL THEN CONCAT(CGCCLI,CGCCPF) ELSE CPFCLI END AS CNPJ_CNPF
, DTNASC AS NASCIMENTO
, ESTADOCIVIL AS EST_CIVIL
, CONJUGE
, DATA_ULTIMA_COMPRA AS ULTIMA_VENDA
FROM CLIENTE