select
  recno as codigo,
  nome as nome,
  fantasia as fantasia,
  apelido as contato,
  case when cpf = '' or cpf is null then cgc else cpf END AS CNPJ_CNPF,
  case when identidade = '' or identidade is null then inscricaoestadual else identidade END AS IE_RG,
  inscricaomunicipal as im,
  endereco as endereco,
  numero as numero,
  referencia as complemento,
  bairro as bairro,
  cidade as cidade,
  uf as uf,
  cep as cep,
  case when foneresidencial = '' or foneresidencial is null then fonecomercial else foneresidencial END AS telefone,
  celular as celular,
  email as email,
  limitecredito as limite_credito,
  profissao as profissao,
  pai as pai,
  mae as mae,
  nascimento as nascimento,
  sexo as sexo,
  civil as est_civil,
  case when ativo = 'S' then 'Ativo' else 'Inativo' end as SITUACAO
from cliente
