select
  codigo as codigo,
  descricao as descricao,
  case when codbarra = '' or codbarra is null then codigofornecedor else codbarra END as barras,
  saldo as qtd,
  unidade as und,
  fornecedor as fornecedor,
  grupo as grupo,
  subgrupo as familia,
  localizacao as caracteristicas,
  precocusto as preco_custo,
  customedio as custo_medio,
  precovenda as preco_venda,
  substring(tributaria,1,1) as ost,
  substring(tributaria,2,4) as st,
  cest as personal6,
  natureza as cf,
  left (natureza,3) as ELO,  
  atualizado as alteracao_preco,
  observacao as observacoes,
  pesoliquido as peso,
  case when ativo = 'S' then 'Ativo' else 'Inativo' end as SITUACAO,
  ncm as cod_ncm
from estoque
