SELECT 
  PRODUTOS.[CODIGOPRODUTO] AS CODIGO
 ,MAX(PRODUTOS_BARRAS.BARRAS) AS BARRAS
 ,PRODUTOS.[DESCRICAO] AS DESCRICAO
 ,PRODUTOS.[UNDSAIDA] AS UND
 ,PRODUTOS_LOJAS.ESTOQUE AS QTD
 ,PRODUTOS.[QUANTIDADEMINIMA] AS QTD_IDEAL
 ,PRODUTOS.[NCM] AS COD_NCM
 ,PRODUTOS.[CEST] AS PERSONAL6
 ,PRODUTOS.[CUSTOAQUISICAO] AS PRECO_CUSTO
 ,PRODUTOS.[PRECOVENDA] AS PRECO_VENDA
 ,PRODUTOS.[CUSTOMEDIO] AS CUSTO_MEDIO
 ,PRODUTOS.[PERCLUCRO] AS MARGEM_LUCRO
 ,PRODUTOS.[MODELO] AS COD_FABRICANTE
 ,PRODUTOS.[LOCALIZACAO] AS PERSONAL1
 ,PRODUTOS.[FABRICANTE] AS FORNCEDOR
 ,PRODUTOS.[PESOBRUTO] AS PESO
 ,PRODUTOS.[DIASVALIDADE] AS VALIDADE_DIAS
 ,PRODUTOS.[COMISSAOPERC] AS COMISSAO
 ,PRODUTOS.[CSOSN] AS ST
 ,PRODUTOS.[ORIGEM] AS OST
 ,PRODUTOS.[PERCIPIENTRADA] AS ALIQ_IPI
 ,PRODUTOS.[CSTIPI] AS IPI_CODIGO_VENDA
 ,PRODUTOS.[CSTPISSAIDA] AS PIS_CODIGO
 ,PRODUTOS.[ALIQUOTAPISSAIDA] AS PIS_ALIQ_NOR
 ,PRODUTOS.[CSTCOFINSSAIDA] AS COFINS_CODIGO
 ,PRODUTOS.[ALIQUOTACOFINSSAIDA] AS COFINS_ALIQ_NOR
 ,PRODUTOS.[CSTPISENTRADA] AS PISE_CODIGO
 ,PRODUTOS.[ALIQUOTAPISENTRADA] AS PISE_ALIQ_NOR
 ,PRODUTOS.[CSTCOFINSENTRADA] AS COFINSE_CODIGO
 ,PRODUTOS.[ALIQUOTACOFINSENTRADA] AS COFINSE_ALIQ_NOR
 , CASE PRODUTOS.[INATIVO] WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
 ,GRUPOS.GRUPO AS GRUPO
 ,FAMILIAS.FAMILIA AS FAMILIA
 ,MARCAS.MARCA AS CARACTERISTICAS
  FROM [BDSTORE].[DBO].[PRODUTOS]
  LEFT JOIN [BDSTORE].[DBO].[PRODUTOS_BARRAS] ON PRODUTOS.CODIGOPRODUTO = PRODUTOS_BARRAS.CODIGOPRODUTO
  LEFT JOIN [BDSTORE].[DBO].[PRODUTOS_LOJAS] ON PRODUTOS.CODIGOPRODUTO = PRODUTOS_LOJAS.CODIGOPRODUTO
  LEFT JOIN [BDSTORE].[DBO].[GRUPOS] ON PRODUTOS.CODIGOGRUPO = GRUPOS.CODIGOGRUPO 
  LEFT JOIN [BDSTORE].[DBO].[FAMILIAS] ON PRODUTOS.CODIGOFAMILIA = FAMILIAS.CODIGOFAMILIA 
  LEFT JOIN [BDSTORE].[DBO].[MARCAS] ON PRODUTOS.CODIGOMARCA = MARCAS.CODIGOMARCA 
  GROUP BY
  PRODUTOS.[CODIGOPRODUTO]
 ,PRODUTOS.[DESCRICAO]
 ,PRODUTOS.[UNDSAIDA]
 ,PRODUTOS_LOJAS.[ESTOQUE]
 ,PRODUTOS.[NCM]
 ,PRODUTOS.[CEST]
 ,PRODUTOS.[PRECOVENDA]
 ,PRODUTOS.[CUSTOMEDIO]
 ,PRODUTOS.[CUSTOAQUISICAO]
 ,PRODUTOS.[CSOSN]
 ,PRODUTOS.[MODELO]
 ,PRODUTOS.[INATIVO]
 ,PRODUTOS.[MODELO]
 ,PRODUTOS.[LOCALIZACAO]
 ,PRODUTOS.[FABRICANTE]
 ,PRODUTOS.[PESOBRUTO]
 ,PRODUTOS.[QUANTIDADEMINIMA]
 ,PRODUTOS.[DIASVALIDADE] 
 ,PRODUTOS.[PERCIPIENTRADA]
 ,PRODUTOS.[COMISSAOPERC]
 ,PRODUTOS.[PERCLUCRO]
 ,PRODUTOS.[ORIGEM]
 ,PRODUTOS.[CSTIPI]
 ,PRODUTOS.[CSTPISSAIDA]
 ,PRODUTOS.[ALIQUOTAPISSAIDA]
 ,PRODUTOS.[CSTCOFINSSAIDA]
 ,PRODUTOS.[ALIQUOTACOFINSSAIDA]
 ,PRODUTOS.[CSTPISENTRADA]
 ,PRODUTOS.[ALIQUOTAPISENTRADA]
 ,PRODUTOS.[CSTCOFINSENTRADA]
 ,PRODUTOS.[ALIQUOTACOFINSENTRADA]
 ,GRUPOS.GRUPO
 ,FAMILIAS.FAMILIA
 ,MARCAS.MARCA
