SELECT EQPRODUTO.CODPROD AS CODIGO,
EQPRODUTO.DESCPROD AS DESCRICAO,
EQPRODUTO.CODUNID AS UND,
EQPRODUTO.CODFISC AS COD_NCM,
EQGRUPO.DESCGRUP AS GRUPO,
EQPRODUTO.CODBARPROD AS BARRAS,
EQPRODUTO.PRECOBASEPROD AS PRECO_VENDA,
EQPRODUTO.SLDPROD AS QTD
FROM EQPRODUTO
LEFT JOIN EQGRUPO ON EQPRODUTO.CODGRUP=EQGRUPO.CODGRUP

