SELECT PESSOA.CD_PESSOA AS CODIGO,
PESSOA.NM_PESSOA AS NOME,
PESSOA.NM_FANTASIA AS FANTASIA,
PESSOA.NR_CNPJCPF AS CNPJ_CNPF,
PESSOA.DT_NASCIMENTO AS NASCIMENTO,
PESSOA.DS_EMAIL AS EMAIL,
PESSOA.DT_CADASTRO AS CADASTRO,
PESSOA.DS_OBSERVACAO AS OBSERVACOES,
ENDERECOPESSOA.DS_ENDERECO AS ENDERECO,
ENDERECOPESSOA.NR_ENDERECO AS NUMERO,
ENDERECOPESSOA.DS_COMPLEMENTO AS COMPLEMENTO,
ENDERECOPESSOA.DS_BAIRRO AS BAIRRO,
MUNICIPIO.DS_MUNICIPIO AS CIDADE,
MUNICIPIO.SG_ESTADO AS UF,
ENDERECOPESSOA.NR_CEP AS CEP,
ENDERECOPESSOA.NR_INSCEST AS IE_RG,
ENDERECOPESSOA.NR_FONE AS TELEFONE,
ENDERECOPESSOA.NR_CELULAR AS CELULAR,
ENDERECOPESSOA.NR_FAX AS FAX
FROM PESSOA
LEFT JOIN ENDERECOPESSOA ON PESSOA.CD_PESSOA=ENDERECOPESSOA.CD_PESSOA AND ENDERECOPESSOA.CD_ENDERECO=1
LEFT JOIN MUNICIPIO ON ENDERECOPESSOA.CD_MUNICIPIO=MUNICIPIO.CD_MUNICIPIO
WHERE PESSOA.CD_TIPOPESSOA=2
