SELECT ITEM.CD_ITEM AS CODIGO,
ITEM.DS_ITEM AS DESCRICAO,
GRUPO.DS_GRUPO AS DESCRICAO,
ITEM.SG_UNIDMED AS UND,
ITEM.NR_NCM AS COD_NCM,
ITEM.CD_CODIGOBARRA AS BARRAS,
ITEM.CD_FORNECEDOR1 AS COD_FABRICANTE,
ITEM.DT_CADASTRO AS DATA_CADASTRO,
ITEM.DS_OBSERVACAO AS OBSERVACOES,
ITEM.CD_CEST AS PERSONAL6,
ITEMTABPRECO.VL_PRECO AS PRECO_VENDA
FROM ITEM
LEFT JOIN GRUPO ON ITEM.CD_GRUPO=GRUPO.CD_GRUPO
LEFT JOIN ITEMTABPRECO ON ITEM.CD_ITEM=ITEMTABPRECO.CD_ITEM

