select
  clientes.Codigo as codigo,
  clientes.DataCadastro as cadastro,
  clientes.RazaoSocial as nome,
  clientes.NomeFantasia as fantasia,
  case when clientes.CNPJ = '' or clientes.CNPJ is null then clientes.CPF else clientes.CNPJ END AS cnpj_cnpf,
  case when clientes.RG = '' or clientes.RG is null then clientes.IE else clientes.RG END AS ie_rg,
  clientes.DataNascimento as nascimento,
  clientes.Endereco as endereco,
  clientes.Numero as numero,
  clientes.Bairro as bairro,
  clientes.Cidade as cidade,
  clientes.CEP as cep,
  clientes.UF as uf,
  clientes.Complemento as complemento,
  clientes.Email as email,
  clientes.Telefone1 as telefone,
  clientes.Telefone2 as celular,
  clientes.Fax as fax,
  clientes.Profissao as profissao,
  clientes.NomePai as pai,
  clientes.NomeMae as mae,
  clientes.EstadoCivil as est_civil,
  clientes.ConjugeNome as conjuge,
  clientes.ValorCredito as limite_credito,
  clientes.OBSERVACAO as observacoes,
  clientes.Naturalidade as naturalidade
from clientes
