SELECT
  FORNECEDOR.CODIGO AS CODIGO,
  FORNECEDOR.NOME AS NOME,
  FORNECEDOR.RAZAO_SOCIAL AS FANTASIA,
  FORNECEDOR.ENDERECO AS ENDERECO,
  FORNECEDOR.NUMERO AS NUMERO,
  FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
  FORNECEDOR.BAIRRO AS BAIRRO,
  CIDADE_VILA.NOME AS CIDADE,
  FORNECEDOR.UF AS UF,
  FORNECEDOR.CEP AS CEP,
  FORNECEDOR.OBSERVACAO AS OBSERVACOES,
  FORNECEDOR.PESSOA AS CONTATO,
  case when FORNECEDOR.CPF = '' or FORNECEDOR.CPF is null then FORNECEDOR.CNPJ else FORNECEDOR.CPF END as CNPJ_CNPF,
  case when FORNECEDOR.RG = '' or FORNECEDOR.RG is null then FORNECEDOR.INSC_ESTADUAL else FORNECEDOR.RG END as IE_RG,
  FORNECEDOR.INSC_MUNICIPAL AS IM,
  FORNECEDOR.TELEFONE AS TELEFONE,
  FORNECEDOR.FAX AS FAX,
  FORNECEDOR.CELULAR AS CELULAR,
  FORNECEDOR.EMAIL AS EMAIL
FROM FORNECEDOR
LEFT JOIN CIDADE_VILA ON CIDADE_VILA.CODIGO =FORNECEDOR.CODIGO_CIDADE
