SELECT
    FORNECEDOR.COD_FORNECEDOR AS CODIGO,
    FORNECEDOR.RAZAO_SOCIAL AS NOME,
    FORNECEDOR.NOME_FANTASIA AS FANTASIA,
    FORNECEDOR.NOME_REPRESENTANTE AS CONTATO,
    FORNECEDOR.IE AS IE_RG,
    FORNECEDOR.CNPJ AS CNPJ_CNPF,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.CIDADE AS CIDADE,
    FORNECEDOR.UF AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.TELEFONE AS TELEFONE,
    FORNECEDOR.CELULAR AS CELULAR,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
