SELECT
    PRODUTOS.COD_PRODUTO AS CODIGO,
    PRODUTOS.COD_BARRAS AS BARRAS,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.CATEGORIA AS GRUPO,
    PRODUTOS.MARCA AS FAMILIA,
    PRODUTOS.UNIDADE_MEDIDA AS UND,
    PRODUTOS.OBSERVACAO AS OBSERVACOES,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    PRODUTOS_ESTOQUE.QTD as QTD,
    PRODUTOS_ESTOQUE.VENDA AS PRECO_VENDA,
    PRODUTOS_ESTOQUE.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS_ESTOQUE.CUSTO AS PRECO_CUSTO,
    PRODUTOS_ESTOQUE.LUCRO AS MARGEM_LUCRO,
    PRODUTOS_ESTOQUE.QTD_MINIMA AS QTD_IDEAL,
    PRODUTOS_ESTOQUE.CEST AS PERSONAL6,
    PRODUTOS_ESTOQUE.DATA_ALTERACAO_VALOR AS ALTERACAO_PRECO,
    PRODUTOS_ESTOQUE.I05 AS COD_NCM,
    PRODUTOS_ESTOQUE.N10 AS ST,
    PRODUTOS_ESTOQUE.ULTIMA_VENDA AS ULTIMA_VENDA,
    PRODUTOS_ESTOQUE.ULTIMA_COMPRA AS ULTIMA_COMPRA
FROM PRODUTOS
left JOIN PRODUTOS_ESTOQUE ON PRODUTOS_ESTOQUE.cod_produto = PRODUTOS.COD_PRODUTO
