SELECT 
  P.IDCODIGOPRODUTO AS COD_FABRICANTE
, P.CODIGOAUXILIAR AS BARRAS
, P.CODIGOORIGINAL AS PERSONAL1
, P.DESCRICAO
, P.ESTOQUE AS QTD
, P.PRECOVENDA AS PRECO_VENDA
, P.MARKUPVENDA AS MARGEM_LUCRO
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.CUSTOREAL AS PRECO_CUSTO
, P.ESTMINIMO AS QTD_IDEAL
, P.IPI AS ALIQ_IPI
, P.PESO
, CONVERT (DATE, P.DATA_ULT_VENDA) AS ULTIMA_VENDA
, CONVERT (DATE, P.DATA_ULT_COMPRA) AS ULTIMA_COMPRA
, P.IDORIGEM AS OST
, P.NCM AS COD_NCM
, P.CST_CSOSN AS ST
, P.CST_PIS AS PIS_CODIGO
, P.PERC_PIS AS PIS_ALIQ_NOR
, P.CST_COFINS AS COFINS_CODIGO
, P.PERC_COFINS AS COFINS_ALIQ_NOR
, P.CFOP_VENDAUF AS CF
, LEFT (P.CFOP_VENDAUF, 3) AS ELO
, P.CST_IPI AS IPI_CODIGO_VENDA
, P.PERC_IPI AS PIS_ALIQ_NOR
, P.CEST AS PERSONAL6
--, P.ATIVO AS SITUACAO
, P.ANP AS ANP
, P.COMISSAO
, PU.SIGLA AS UND
, PG.DESCRICAO AS IDGRUPO 
, PSG.DESCRICAO AS FAMILIA
, PF.DESCRICAO AS FABRICANTE
FROM PRODUTO P
LEFT JOIN PRODUTO_UNIDADE PU ON PU.IDUNIDADE  = P.IDUNIDADE
LEFT JOIN PRODUTO_GRUPO PG ON PG.IDGRUPO = P.IDGRUPO
LEFT JOIN PRODUTO_SUBGRUPO PSG ON PSG.IDSUBGRUPO = P.IDSUBGRUPO
LEFT JOIN PRODUTO_FABRICANTE PF ON PF.IDFABRICANTE = P.IDFABRICANTE
