SELECT
    ID AS CODIGO,
    DOC AS CNPJ_CNPF,
    CLIENTE AS NOME,
    LOGRADOURO AS ENDERECO,
    NUMERO,
    BAIRRO,
    MUNICIPIO AS CIDADE,
    COMPLEMENTO,
    UF,
    FONE AS TELEFONE,
    CEP,
    DOC2 AS IE_RG,
    CONTATO,
    EMAIL
FROM CLIENTE
WHERE ID > 0
