SELECT
    P.ID,
    P.DESCRICAO AS DESCRICAO,
    P.REF_INTERNA AS COD_FABRICANTE,
    P.UNIDADE AS UND,
    case when P.ATIVO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO,
    P.VALOR AS PRECO_VENDA,
    P.OBSERVACAO AS OBSERVACOES,
    E.QUANTIDADE AS QTD,
    P.ESTOQUE_MINIMO AS QTD_IDEAL,
    P.VALOR_COMPRA AS PRECO_CUSTO,
    P.EAN AS BARRAS,
    TI.CST_ICMS AS ST,
    P.NCM AS COD_NCM,
    P.CODIGO AS CODIGO,
    P.CEST AS PERSONAL6
FROM PRODUTOS AS P
LEFT JOIN PRODUTOS_TABELA_ICMS PI ON P.CODIGO = PI.ID_PRODUTO
LEFT JOIN TABELA_ICMS TI ON PI.ID_TABELA_ICMS = TI.ID
LEFT JOIN ESTOQUE E ON P.CODIGO = E.ID_PRODUTO
