SELECT TB_FORNECEDOR.ID_FORNEC AS CODIGO,
TB_FORNECEDOR.NOME,
TB_FORNECEDOR.NOME_FANTA AS FANTASIA,
TB_FORNECEDOR.CNPJ AS CNPF_CNPJ,
TB_FORNECEDOR.INSC_ESTAD AS IE_RG,
TB_FORNECEDOR.END_CEP AS CEP,
TB_FORNECEDOR.END_TIPO||' '||TB_FORNECEDOR.END_LOGRAD AS ENDERECO,
TB_FORNECEDOR.END_BAIRRO AS BAIRRO,
TB_FORNECEDOR.END_NUMERO AS NUMERO,
TB_CIDADE_SIS.NOME AS CIDADE,
TB_CIDADE_SIS.SIGLA_UF AS UF
FROM TB_FORNECEDOR
LEFT JOIN TB_CIDADE_SIS ON TB_FORNECEDOR.ID_CIDADE=TB_CIDADE_SIS.ID_CIDADE






