SELECT
    ID AS CODIGO,
    CODIGO AS BARRAS,
    REFERENCIA AS COD_FABRICANTE,
    DESCRICAO,
    QTDE AS QTD,
    VALOR AS PRECO_VENDA,
    UN AS UND,
    ST,
    NCM AS COD_NCM,
    GRUPO,
    SUBGRUPO AS FAMILIA
FROM PRODUTO
