SELECT
    PRODUTO.PRO_CODIGO AS CODIGO,
    PRODUTO.PRO_REFERENCIA AS COD_FABRICANTE,
    PRODUTO.PRO_NOMECOMPLETO AS DESCRICAO,
    GRUPO.GRU_NOME AS GRUPO,
    SUBGRUPO.SUB_NOME AS FAMILIA,
    PRODUTO.PRO_MARGEM AS MARGEM_LUCRO,
    PRODUTO.PRO_VENDA AS PRECO_VENDA,
    PRODUTO.PRO_ESTOQUE AS QTD,
    PRODUTO.PRO_ULTVENDA AS ULTIMA_VENDA,
    PRODUTO.PRO_ULTCOMPRA AS ULTIMA_COMPRA,
    PRODUTO.PRO_CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO.PRO_VLRCOMPRA AS PRECO_CUSTO,
    PRODUTO.PRO_CODBARRA AS BARRAS,
    PRODUTO.PRO_CADASTRO AS DATA_CADASTRO,
    PRODUTO.PRO_PESO AS PESO, 
    PRODUTO.PRO_CLASSIFISCAL AS COD_NCM,
    SITRIBUTARIA.SIT_SITUACAO AS ST, 
    PRODUTO.PRO_CESTNCM AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.GRU_CODIGO = PRODUTO.PRO_GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.SUB_CODIGO = PRODUTO.PRO_SUBGRUPO
LEFT JOIN SITRIBUTARIA ON SITRIBUTARIA.SIT_ID = PRODUTO.PRO_SITRIBUTARIA