SELECT
    FORNECEDORES.CODIGO_FOR AS CODIGO,
    FORNECEDORES.RAZAO_SOC AS NOME,
    FORNECEDORES.FANTASIA AS FANTASIA,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.CNPJ AS CNPJ_CNPF,
    case when FORNECEDORES.IDENTIDADE = '' or FORNECEDORES.IDENTIDADE is null then FORNECEDORES.INSCRICAO else FORNECEDORES.IDENTIDADE END AS IE_RG,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    MUNICIPIOS_IBGE.MUNICIPIO AS CIDADE,
    UF_IBGE.SIGLA AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.EMAILL AS EMAIL
FROM FORNECEDORES
LEFT JOIN MUNICIPIOS_IBGE ON MUNICIPIOS_IBGE.COD_MUNICIPIO_IBGE = FORNECEDORES.CODIGO_CID
LEFT JOIN UF_IBGE ON UF_IBGE.COD_UF = MUNICIPIOS_IBGE.COD_UF_IBGE