SELECT
        PESSOAS.CODIGO AS CODIGO,
        PESSOAS.RAZAOSOCIAL AS NOME,
        PESSOAS.NOMEFANTASIA AS FANTASIA,
        PESSOAS.CNPJ AS CNPJ_CNPF,
        PESSOAS.INSCRICAOESTADUAL AS IE_RG,
        PESSOAS.LOGRADOURORESIDENCIAL AS ENDERECO,
        PESSOAS.NUMEROLOCALRESIDENCIAL AS NUMERO,
        PESSOAS.BAIRRORESIDENCIAL AS BAIRRO,
        PESSOAS.CIDADERESIDENCIAL AS CIDADE,
        PESSOAS.UFRESIDENCIAL AS UF,
        PESSOAS.CEPRESIDENCIAL AS CEP,
        PESSOAS.EMAILRESIDENCIAL AS EMAIL,
        PESSOAS.CELULARRESIDENCIAL AS CELULAR,
        PESSOAS.CADASTRO AS CADASTRO
FROM PESSOAS
WHERE PESSOAS.TIPO = 4
