SELECT
        PRODUTOS.CODIGO AS CODIGO,
--        PRODUTOS.CODIGOBARRAS AS BARRAS,
        PRODUTOS.DESCRICAO AS DESCRICAO,
        GRUPOSPRODUTOS.DESCRICAO AS GRUPO,
        ESTOQUES.QUANTIDADE AS QTD,
         MAX(itensprecoscompras.PRECOCOMPRA) AS PRECO_CUSTO,
         MAX(ITENSPRECOSVENDAS.preconormal) AS PRECO_VENDA,
        LEFT(CLASSIFICACOESFISCAIS.DESCRICAO, 1) AS ST,
        PRODUTOS.NCM AS COD_NCM,
        PRODUTOS.CEST AS PERSONAL6,
        PRODUTOS.REFERENCIA AS COD_FABRICANTE,
        MAX (PRODUTOSCODIGOSBARRAS.codigobarras) AS BARRAS
FROM PRODUTOS
LEFT JOIN  ESTOQUES ON PRODUTOS.CODIGO = ESTOQUES.PRODUTO
left JOIN CLASSIFICACOESFISCAIS ON PRODUTOS.CLASSIFICACAOFISCAL = CLASSIFICACOESFISCAIS.CODIGO
LEFT JOIN gruposprodutos ON PRODUTOS.grupo = GRUPOSPRODUTOS.codigo
LEFT JOIN ITENSPRECOSVENDAS on PRODUTOS.codigo = ITENSPRECOSVENDAS.produto
LEFT join itensprecoscompras ON PRODUTOS.CODIGO =  itensprecoscompras.PRODUTO
LEFT JOIN PRODUTOSCODIGOSBARRAS ON PRODUTOS.CODIGO = PRODUTOSCODIGOSBARRAS.produto
WHERE ITENSPRECOSVENDAS.PRECO = '1'
group by
1,2,3,4,7,8,9,10
