SELECT
    ID AS CODIGO,
    CODBARRAS AS BARRAS,
    DESCRICAO AS DESCRICAO,
    UN AS UND,
    PRECO_COMPRA AS PRECO_CUSTO,
    MARGEM_LUCRO,
    MARCA AS GRUPO,
    TRIBUTACAO AS ST,
    NCM AS COD_NCM,
    ESTOQUE AS QTD,
    CEST AS PERSONAL6
FROM PRODUTOS
