SELECT
    CONTA.CONTAID AS CODIGO,
    CONTA.NOME_FANTASIA AS FANTASIA,
    CONTA.NOME,
    CONTA.CEP,
    max (CIDADE.descricao) AS CIDADE,
    CONTA.UF,
    CONTA.ENDERECO,
    CONTA.COMPLEMENTO,
    CONTA.BAIRRO,
    CONTA.CNPJ_CPF AS CNPJ_CNPF,
    CONTA.CGF_RG AS IE_RG,
    CONTA.NUMERO 
FROM CONTA
LEFT JOIN CIDADE ON CONTA.cidade = CIDADE.CODIGO
WHERE CONTA.CONTAID > 0
group by 1,2,3,4,6,7,8,9,10,11,12
