SELECT  
    PRODUTO.PRODUTOID AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    --(select FIRST 1 SALDO_ESTOQUE.SD_ANTERIOR from SALDO_ESTOQUE where SALDO_ESTOQUE.PRODUTOID = PRODUTO.PRODUTOID order by SALDO_ESTOQUE.DATA desc) as qtd,
    --ESTOQUE.SALDO AS QTD,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.CODIGO_BARRAS AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    MIN (CLASSIFICACAO_TRIBUTARIA.cst_saida) AS ST,
    PP.PRECO_COMPRA as preco_custo,
    PP.PRECO_AVISTA as preco_venda,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
--LEFT JOIN SALDO_ESTOQUE ON SALDO_ESTOQUE.PRODUTOID = PRODUTO.PRODUTOID
left join CLASSIFICACAO_TRIBUTARIA on CLASSIFICACAO_TRIBUTARIA.cstid = produto.cst
LEFT JOIN POLITICA_PRECO PP ON PP.PRODUTOID=PRODUTO.PRODUTOID
--WHERE ESTOQUE.CONTAID = '7'
GROUP BY 1,2,3,4,5,7,8,9,10
