SELECT 
    CONTAS_PAGAR.ID_DOCUMENTO ||'/'|| CONTAS_PAGAR.NUM_DOCUMENTO AS DOCUMENTO,
    CONTAS_PAGAR.DATA_EMISSAO AS EMISSAO,
    FORNECEDORES.CODIGO AS COD_FORNECEDOR,
    FORNECEDORES.RAZAO_SOCIAL AS NOM_FORNECEDOR,
    CONTAS_PAGAR.VALOR AS VALOR_DUP,
    CONTAS_PAGAR.VENCIMENTO AS VENCIMENTO,
    CONTAS_PAGAR.OBSERVACAO AS OBSERVACOES,
    CONTAS_PAGAR.VALOR_PAGO AS VALOR_PAG,
    CONTAS_PAGAR.DATA_PAGTO AS PAGAMENTO,
    CONTAS_PAGAR.PARCELA ||'--'|| CONTAS_PAGAR.DIFERENCA AS HISTORICO,
    FORNECEDORES.CNPJ
FROM CONTAS_PAGAR
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = CONTAS_PAGAR.CODIGO_FORNECEDOR
