SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.CODIGO_BARRAS AS BARRAS,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    SECAO.secao AS GRUPO,
    PRODUTOS.VALOR_CUSTO AS PRECO_CUSTO,
    PRODUTOS.VALOR_VENDA_1 AS PRECO_VENDA,
    PRODUTOS.ESTOQUE_ATUAL AS QTD,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.NUMERO_FABRICANTE AS COD_FABRICANTE,
    PRODUTOS.APLICACAO AS OBSERVACOES,
    PRODUTOS.ESTOQUE_MINIMO QTD_IDEAL
FROM PRODUTOS
LEFT JOIN SECAO ON PRODUTOS.codigo_secao = SECAO.codigo
