SELECT 
    CONTAS_RECEBER.CODIGO ||'/'|| CONTAS_RECEBER.FATURA AS DOCUMENTO,
    CONTAS_RECEBER.DATA_EMISSAO AS EMISSAO,
    --CONTAS_RECEBER.FATURA AS DOCUMENTO,
    CLIENTES.CODIGO AS COD_CLIENTE,
    CLIENTES.NOME AS NOM_CLIENTE,
    CONTAS_RECEBER.DATA_VENCIMENTO AS VENCIMENTO,
    CONTAS_RECEBER_PAGAMENTOS.VALOR_NOTAS AS VALOR_DUP,
    CONTAS_RECEBER.VALOR_JUROS AS VALOR_JUR,
    CONTAS_RECEBER_PAGAMENTOS.VALOR_PAGO AS VALOR_REC,
    CONTAS_RECEBER_PAGAMENTOS.DATA AS RECEBIMENTO,
    CONTAS_RECEBER.DOCUMENTO ||'-'|| CONTAS_RECEBER.OBS1 AS HISTORICO,
    CONTAS_RECEBER.DOCUMENTO ||'-'|| CONTAS_RECEBER.OBS1 AS OBSERVACOES,
    0 AS BANCO,
    0 AS CONTA,
    CLIENTES.CPF_CNPJ AS CNPJ
FROM CONTAS_RECEBER
LEFT JOIN CLIENTES ON CLIENTES.CODIGO = CONTAS_RECEBER.codigo_cliente
LEFT JOIN CONTAS_RECEBER_PAGAMENTOS ON CONTAS_RECEBER_PAGAMENTOS.id_registro_resto = contas_receber.codigo
