SELECT 
  CODIGO
, "NOME" AS NOME
, APELIDO AS FANTASIA
, ENDERECO
, BAIRRO
, CIDADE
, UF
, CEP
, COMPL AS COMPLEMENTO
, NUMERO
, case when CPF = '' or CPF is null then CGC else CPF END AS CNPJ_CNPF
, case when RG_IDENTIDADE = '' or RG_IDENTIDADE is null then IE else RG_IDENTIDADE END AS IE_RG
, "OBS" AS OBSERVACOES
, TELEFONE
, DTNASCIMENTO AS NASCIMENTO
, LIMITE AS LIMITE_CREDITO
, CELULAR
, EMAIL
, CONTATO
, NOME_PAI AS PAI
, NOME_MAE AS MAE
, PROFISSAO
, ESTADOCIVIL AS EST_CIVIL
FROM CLIENTES