SELECT
    COD_PRODUTO AS CODIGO,
    COALESCE(NOM_PRODUTO,'') || ' - ' ||COALESCE(NOM_APRESENTACAO,'') AS DESCRICAO,
    VLR_CUSTOATUAL AS PRECO_CUSTO,
    VLR_VENDA AS PRECO_VENDA,
    COD_BARRA AS BARRAS,
    NUM_ESTOQUEATUAL AS QTD,
    NCM AS COD_NCM,
    CST_SAIDA AS ST,
    COD_CEST AS PERSONAL6
FROM PRODUTO
WHERE NOM_PRODUTO <> '' AND NOM_APRESENTACAO <> '' or COD_PRODUTO < '999999'