SELECT FORNECEDORES.ID_FORNECEDOR AS CODIGO,
FORNECEDORES.CNPJ_CPF AS CNPJ_CNPF,
FORNECEDORES.IE_RG,
FORNECEDORES.RAZAO_NOME AS NOME,
FORNECEDORES.FANTASIA,
FORNECEDORES.ENDERECO,
FORNECEDORES.NUMERO,
FORNECEDORES.COMPL AS COMPLEMENTO,
FORNECEDORES.BAIRRO AS BAIRRO,
FORNECEDORES.CIDADE,
FORNECEDORES.UF,
FORNECEDORES.CEP,
FORNECEDORES.FONE AS TELEFONE,
FORNECEDORES.FAX,
FORNECEDORES.EMAIL,
FORNECEDORES.CONTATO,
FORNECEDORES.OBS AS OBSERVACOES
FROM FORNECEDORES
WHERE FORNECEDORES.ID_FORNECEDOR<>0

