SELECT
    PRODUTO.CODIGO AS COD_FABRICANTE,
    PRODUTO.DESCRI AS DESCRICAO,
    PRODUTO.UNIDADE AS UND,
    GRUPO.DESCRI AS GRUPO,
    MARCA.DESCRI AS FAMILIA,
    PRODUTO.ST AS ST,
    CLASSIFICACAO.NCM AS COD_NCM,
    PRODUTO.CODINTERNO AS BARRAS,
    MAX(PRECO.VALOR) AS PRECO_VENDA
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.CODGRUPO = GRUPO.CODIGO
LEFT JOIN CLASSIFICACAO ON PRODUTO.CODCLASSIFICACAO = CLASSIFICACAO.CODIGO
LEFT JOIN MARCA ON PRODUTO.CODMARCA = MARCA.CODIGO
LEFT JOIN PRECO ON PRODUTO.CODIGO = PRECO.CODPRODUTO
GROUP BY 1,2,3,4,5,6,7,8
