SELECT 
  P.IDPESSOA AS CODIGO
, P.RAZAO_SOCIAL AS NOME
, P.NOME_FANTASIA AS FANTASIA
, CASE WHEN P.FIS_CPF = '' OR P.FIS_CPF IS NULL THEN P.JUR_CNPJ ELSE P.FIS_CPF END AS CNPJ_CNPF
, CASE WHEN P.FIS_RG = '' OR P.FIS_RG IS NULL THEN P.JUR_INSC_EST ELSE P.FIS_RG END AS IE_RG
, P.TELEFONE1 AS TELEFONE
, P.TELEFONE2 AS CELULAR
, P.TELEFONE3 AS FAX
, P.ENDERECO
, P.NUMERO
, P.COMPLEMENTO
, P.BAIRRO
, P.CEP
, P.EMAIL
, P.OBS AS OBSERVACOES
, P.CODIGOBARRA AS PERSONAL1
, P.WATZAP AS PERSONAL2
, CI.DESCRICAO AS CIDADE 
, CI.UF 
FROM PESSOA P
LEFT JOIN CIDADE CI ON CI.COD_MUNICIPIO = P.CMUN 
WHERE CONF_ISFORNECEDOR = 'S'
