SELECT
  TABCLI.CODIGO  AS CODIGO,
  TABCLI.NOME AS NOME,
  TABCLI.ENDERECO AS ENDERECO,
  TABCLI.ENDNUMERO AS NUMERO,
  TABCLI.ENDCOMPLEMENTO AS COMPLEMENTO,
  TABCLI.BAIRRO AS BAIRRO,
  TABCLI.CIDADE AS CIDADE,
  TABCLI.ESTADO AS UF,
  TABCLI.CEP AS CEP,
  TABCLI.TELEFONE AS TELEFONE,
  TABCLI.CELULAR AS CELULAR,
  TABCLI.DATA AS DATA_CASDASTRO,
  TABCLI.OBS AS OBSERVACOES,
  TABCLI.EMAIL AS EMAIL,
  TABCLI.CGC AS CNPJ_CNPF,
  TABCLI.LIMITECRED AS LIMITE_CREDITO,
  TABCLI.CONTATO AS CONTATO,
  CASE WHEN TABCLI.INSC = '' THEN TABCLI.IDENTIDADE
  ELSE TABCLI.INSC END AS IE_RG,
  TABCLI.FAX AS FAX,
  TABCLI.NASCIMENTO AS NASCIMENTO,
  TABCLI.PROFISSAO AS PROFISSAO
FROM TABCLI