SELECT
  TABFOR.CONTROLE AS CODIGO,
  TABFOR.CODIGO AS FANTASIA,
  TABFOR.EMPRESA AS NOME,
  TABFOR.CONTATO AS CONTATO,
  TABFOR.ENDERECO AS ENDERECO,
  TABFOR.BAIRRO AS BAIRRO,
  TABFOR.CIDADE AS CIDADE,
  TABFOR.ESTADO AS UF,
  TABFOR.CEP AS CEP,
  TABFOR.TELEFONE AS TELEFONE,
  TABFOR.FAX AS FAX,
  TABFOR.CGC AS CNPJ_CNPF,
  TABFOR.INSC AS IE_RG,
  TABFOR.OBS AS OBSERVACOES,
  TABFOR.EMAIL AS EMAIL
FROM TABFOR
