SELECT
  TABEST1.CONTROLE AS CODIGO,
  TABEST1.CODIGO AS COD_FABRICANTE,
  TABEST1.PRODUTO AS DESCRICAO,
  --TABFOR.EMPRESA AS FORNECEDOR,
  --TABEST8.setor AS GRUPO,
  TABEST1.PRECOCUSTO AS PRECO_CUSTO,
  TABEST1.CUSTOMEDIO AS CUSTO_MEDIO,
  TABEST1.PRECOVENDA AS PRECO_VENDA,
  TABEST1.QUANTIDADE AS QTD,
  TABEST1.ESTMINIMO AS QTD_IDEAL,
  TABEST1.UNIDADE AS UND,
  TABEST1.LUCRO AS MARGEM_LUCRO,
  --TABEST1.COMISSAO AS COMISSAO,
  TABEST1.ULTREAJ AS ALTERACAO_PRECO,
  TABEST1.OBS AS OBSERVACOES,
  TABEST1.CODIPI AS COD_NCM,
  SUBSTRING(TABEST1.CST from 2 for 3) AS ST,
  TABEST1.CST AS ST,
  TABEST1.PESOLIQ AS PESO,
  SUBSTRING (TABEST1.CODIGO from 1 FOR 13) AS BARRAS
--case Produto.TABEST1.INATIVO when 'TRUE' then 'Inativo' else 'Ativo' end as situacao,
  --TABEST1.CEST AS PERSONAL6
FROM TABEST1
--LEFT JOIN tabest8 ON TABEST8.controle = TABEST1.lksetor
--LEFT JOIN TABFOR ON TABFOR.CONTROLE = TABEST1.LKFORNEC
