SELECT
  CLIENTE.CODIGO_ID AS CODIGO,
  CLIENTE.NOME AS NOME,
  CLIENTE.ENDERECO AS ENDERECO,
  CLIENTE.BAIRRO AS BAIRRO,
  CLIENTE.CIDADE AS CIDADE,
  CLIENTE.ESTADO AS UF,
  CLIENTE.CEP AS CEP,
  CLIENTE.REFERENCIA AS COMPLEMENTO,
  CLIENTE.CPF AS CNPJ_CNPF,
  CLIENTE.RG AS IE_RG,
  CLIENTE.RAZAOSOCIAL AS FANTASIA,
  CLIENTE.FONE AS TELEFONE,
  CLIENTE.NUMERO AS NUMERO,
  CLIENTE.EMAIL AS EMAIL,
  CLIENTE.LIMITEMENSAL AS LIMITE_CREDITO
FROM CLIENTE