SELECT
  PRODUTO.CODIGO_ID AS CODIGO,
  PRODUTO.CODIGOBARRAS AS BARRAS,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.PRECO AS PRECO_VENDA,
  PRODUTO.REFERENCIA AS COD_FABRICANTE,
  PRODUTO.CLASSIFICACAO AS GRUPO,
  PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
  PRODUTO.NCM AS COD_NCM,
  SUBSTRING (PRODUTO.SITTRIBUTARIA FROM 1 FOR 3) AS ST,
  PRODUTO.MARGEM AS MARGEM_LUCRO,
  PRODUTO.FABRICANTE AS FORNECEDOR
FROM PRODUTO