SELECT
	C.CAD_IDCADASTRO AS CODIGO,
	C.CAD_NOME AS NOME,
	C.CAD_NOMEFANTASIA AS FANTASIA,
	C.CAD_CPFCNPJ AS CNPJ_CNPF,
	C.CAD_RG_INSC AS IE_RG,
	C.CAD_INSCMUNICIPAL AS IM,
	COALESCE(C.CAD_DDD, '')||COALESCE(C.CAD_TELEFONE, '') AS TELEFONE,
	C.CAD_NUMEROCASA AS NUMERO,
	C.CAD_COMPLEMENTO AS COMPLEMENTO,
	C.CAD_SEXO AS SEXO,
	C.CAD_DATANASCIMENTO AS NASCIMENTO,
	CAST(C.DATAINCLUSAO AS DATE) AS CADASTRO,
	C.CAD_EMAIL AS EMAIL,
	C.CNH AS PERSONAL1,
	C.CAD_APELIDO AS CONTATO,
	C.NUMEROCARTAOIDENTIFID AS PERSONAL2,
	C.CAD_CRC AS PERSONAL3,
	C.CAD_CPF AS PERSONAL4,
	C.CAD_CNPJ AS PERSONAL5,
	C.TELEFONEWATSAP AS PERSONAL6,
	CF.CFU_NOMEFUNCAO AS PROFISSAO,
	CE.END_LOGRADOURO AS ENDERECO,
	CE.END_BAIRRO AS BAIRRO,
	CE.END_CEP AS CEP,
	CE.END_UF AS UF,
	CI.CID_NOME AS CIDADE,
	CO.CJU_NOME AS CONJUJE,
	C2.CMP_NOMEPAI AS PAI,
	C2.CMP_NOMEMAE AS MAE,
	C2.CMP_ESTADOCIVIL AS EST_CIVIL,
	C3.OBS_OBSERVACAO AS OBSERVACOES
FROM
	CADASTRO C
LEFT JOIN CADASTROCARGOFUNCAO CF ON CF.CFU_IDCARGOFUNCAO = C.CAD_IDCARGOFUNCAO 
LEFT JOIN CADASTROENDERECO CE ON CE.END_IDCADASTRO = C.CAD_IDCADASTRO 
LEFT JOIN CADASTROCIDADE CI ON CI.CID_IDCIDADE = CE.END_IDCIDADE
LEFT JOIN CADASTROCONJUGE CO ON CO.CJU_IDCADASTRO = C.CAD_IDCADASTRO
LEFT JOIN CADASTROCOMPLEMENTO C2 ON C2.CMP_IDCADASTRO = C.CAD_IDCADASTRO 
LEFT JOIN CADASTROOBSERVACAO C3 ON C3.OBS_IDCADASTRO = C.CAD_IDCADASTRO 
WHERE CAD_TIPO = 'C'