SELECT
	P.PRO_IDPRODUTO AS CODIGO,
	P.PRO_REFERENCIA AS COD_FABRICANTE,	
	P.PRO_CODIGO AS PERSONAL1,
	P.CODIGOGTINDOPRODUTO AS PERSONAL2,	
	P.PRO_CODIGOAUX AS PERSONAL4,
	P.PRO_NOME AS DESCRICAO,
	P.PRO_OBSERVACAO AS OBSERVACOES,
	P.PRO_CODIGOBARRA AS BARRAS,
	P.PRO_UNIDADE AS UND,
	P.PRO_COMISSAO AS COMISSAO,
	CASE P.PRO_STATUS WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	CAST(P.DATAINCLUSAO AS DATE) AS DATA_CADASTRO,
--	P.PRO_ESTOQUEMINIMO AS QTD_IDEAL,
	P.PRO_IDORIGEMPRODUTO AS OST,
	P.PRO_QTDEMBALAGEM AS FAT_CONV,
	P.PESOBRUTODOPRODUTO AS PESO,
	P.CODIGONCMDOPRODUTO AS COD_NCM,
	P.CEST AS PERSONAL6,	
	P.PRO_PIS AS PISE_ALIQ_NOR,
	P.PRO_COFINS AS COFINSE_ALIQ_NOR,
	P.CODIGOPISDOPRODUTO AS PIS_CODIGO,
	P.ALIQUOTAPIS AS PIS_ALIQ_NOR,
	P.CODIGOCOFINSDOPRODUTO AS COFINS_CODIGO,
	P.ALIQUOTACOFINS AS COFINS_ALIQ_NOR,
	P.ALIQUOTAIPI AS ALIQ_IPI_VENDA,
	PG.GRU_NOME AS GRUPO,
	C.CAD_NOME AS FORNECEDOR,
	PM.MAR_NOME AS FAMILIA,
	GI.CFOPVNDINTNCONTRIB AS CF,
	LEFT(GI.CFOPVNDINTNCONTRIB,3) AS ELO,
--	GI.CODIGOTRIBUTACAONASAIDA AS ST,
	GI.CSOSN AS ST,
	PE.EST_QTDEFISICO AS QTD,
	PE.EST_ESTOQ_MINIMO AS QTD_IDEAL,
	PR.PRE_PRECO_CUSTO AS PRECO_CUSTO,
	PR.PRE_PRECO_VENDA_AV AS PRECO_VENDA,
	PR.PRE_PERC_LUCRO_AV MARGEM_LUCRO,
	PR.CUSTOMEDIO AS CUSTO_MEDIO
FROM
	PRODUTO P
	LEFT JOIN PRODUTOGRUPO PG ON PG.GRU_IDGRUPO = P.PRO_IDGRUPO 
	LEFT JOIN CADASTRO C ON C.CAD_IDCADASTRO = P.PRO_IDFORNECEDOR 
	LEFT JOIN PRODUTOMARCA PM ON PM.MAR_IDMARCA = P.PRO_IDMARCA 
	LEFT JOIN GRUPOIMPOSTOSDOPRODUTO GI ON GI.IDGRUPOIMPOSTOS = P.IDGRUPOIMPOSTOS
	LEFT JOIN PRODUTOESTOQUE PE ON PE.EST_IDPRODUTO = P.PRO_IDPRODUTO AND PE.EST_IDSETOR = '2' --ESTOQUE GERAL
	LEFT JOIN PRODUTOSPRECO PR ON PR.PRE_IDPRODUTO = P.PRO_IDPRODUTO