SELECT
  PRODUTOS.COD_PRODUTO AS BARRAS,
  --PRODUTOS.COD_BARRAS,
  PRODUTOS.COD_NCM AS COD_NCM,
  PRODUTOS.COD_CEST AS PERSONAL6,
  PRODUTOS.COD_REFERENCIA AS COD_FABRICANTE,
  PRODUTOS.DSC_COMPLETA AS DESCRICAO,
  PRODUTOS.DSC_ABREVIADA AS OBSERVACOES,
  PRODUTOS.DSC_UNIDADE AS UND,
  PRODUTOS.DSC_FORNECEDOR AS FORNECEDOR,
  PRODUTOS.NUM_ICMS_CST AS ST,
  PRODUTOS.NUM_MARGEM_LUCRO AS MARGEM_LUCRO,
  PRODUTOS.NUM_PRECO_CUSTO AS PRECO_CUSTO,
  PRODUTOS.NUM_PRECO_VAREJO AS PRECO_VENDA,
  PRODUTOS.NUM_PRECO_ATACADO AS PRECO_ATACADO,
  PRODUTOS.NUM_ESTOQUE AS QTD,
  PRODUTOS.NUM_ESTOQUE_MINIMO AS QTD_IDEAL
FROM PRODUTOS
