SELECT
	MC01CODIGO AS CODIGO,
	MC01NOME AS NOME,
	MC01FANTASIA AS FANTASIA,
	MC01ENDERECO AS ENDERECO,
	MC01BAIRRO AS BAIRRO,
	MC01CIDADE AS CIDADE,
	MC01CEP AS CEP,
	MC01UF AS UF,
	MC01FONE AS TELEFONE,
	MC01FAX AS FAX,
	MC01CELULAR AS CELULAR,
	MC01EMAIL AS EMAIL,
	CAST (MC01DTCADASTRO AS DATE) AS CADASTRO,
	MC01DTNASCTO AS NASCIMENTO,
	CASE
		WHEN MC01CLIENTE.MC01CGC = ''
		OR MC01CLIENTE.MC01CGC IS NULL THEN MC01CLIENTE.MC01CPF
		ELSE MC01CLIENTE.MC01CGC
	END AS CNPJ_CNPF,
	CASE
		WHEN MC01CLIENTE.MC01IE = ''
		OR MC01CLIENTE.MC01IE IS NULL THEN
	MC01CLIENTE.MC01CI
		ELSE
	MC01CLIENTE.MC01IE
	END AS IE_RG,
	MC01ESTCIVIL AS EST_CIVIL,
	MC01PAI AS PAI,
	MC01MAE AS MAE,
	MC01CONTATO AS CONTATO,
	MC01EMPRESA AS PROFISSAO,
	MC01CONJUGE AS CONJUGE,
	MC01_OBS1 AS OBSERVACOES
FROM
	MC01CLIENTE
WHERE MC01CODIGO > 0