SELECT
	MC02CODIGO AS CODIGO,
	MC02NOME AS NOME,
	MC02FANTASIA AS FANTASIA,
	MC02ENDERECO AS ENDERECO,
	MC02BAIRRO AS BAIRRO,
	MC02CIDADE AS CIDADE,
	MC02CEP AS CEP,
	MC02UF AS UF,
	MC02FONE AS TELEFONE,
	MC02FAX AS FAX,
	MC02CELULAR AS CELULAR,
	MC02EMAIL AS EMAIL,
	MC02CGC AS CNPJ_CNPF,
	MC02IE AS IE_RG,
	MC02CONTATO AS CONTATO,
	MC02OBSGERAL AS OBSERCACOES
FROM
	MC02FORNEC
WHERE MC02CODIGO > 0