SELECT
    PRODUTOS.INTERNO AS CODIGO,
    PRODUTOS.CODIGO AS COD_FABRICANTE,
    PRODUTOS.CODBARRA AS BARRAS,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.REDUZIDO AS CARACTERISTICAS,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.UNIDADEMEDIDA AS UND,
    PRODUTOS.UNIDADEMEDIDA AS UND_COMPRA,
    REPLACE(PRODUTOS.CODIGONCM, '.', '') AS COD_NCM,
    PRODUTOS.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTOS.MARGEMLUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRECOVENDA AS PRECO_VENDA,
    REPLACE(PRODUTOS.CEST, '.', '') AS PERSONAL6
FROM PRODUTOS
