SELECT
    CLIFOR.CHAVE AS CODIGO,
    CLIFOR.NOME AS RAZAO_SOCIAL,
    CLIFOR.ENDERECO AS ENDERECO,
    CLIFOR.CIDADE AS CIDADE,
    CLIFOR.ESTADO AS UF,
    CLIFOR.DDDFONE ||''|| CLIFOR.TELEFONE AS TELEFONE,
    CLIFOR.EMAIL AS EMAIL,
    CLIFOR.CGCCPF AS CNPJ,
    CLIFOR.INSCEST AS IE
FROM CLIFOR
WHERE CLIFOR.TIPO = '1'   --- TRANSPORTADORES
