SELECT
  CODIGO
, DESCRICAO AS NOME
, FANTASIA
, OBSERVACAO AS OBSERVACOES
, CONVERT (DATE,[DATA NASCIMENTO]) AS NASCIMENTO
, [FILIACAO PAI] AS PAI
, [FILIACAO MAE] AS MAE
, [CPF OU CGC] AS CNPJ_CNPF
, [RG OU INSCRICAO ESTADUAL] AS IE_RG
, INSCMUNICIPAL AS IM
, ENDERECO
, NUMERO
, CONCAT((PONTOREFERENCIA),'. PERIMETRO: ',(PERIMETRO)) AS COMPLEMENTO
, BAIRRO
, REPLACE (CEP,'.','') AS CEP
, CIDADE
, ESTADO AS UF
, FONE AS TELEFONE
, FAX
, CASE WHEN CELULAR = '' OR CELULAR IS NULL THEN WHATSAPP ELSE CELULAR END AS CELULAR
, EMAIL
, [ENDERECO COBRANCA] AS COB_ENDERECO
, [NUMERO COBRANCA] AS COB_NUMERO
, [BAIRRO COBRANCA] AS COB_BAIRRO
, REPLACE ([CEP COBRANCA],'.','') AS COB_CEP
, [CIDADE COBRANCA] AS COB_CIDADE
, [ESTADO COBRANCA] AS COB_UF
, CASE SEXO WHEN 'Feminino' THEN 'F' WHEN 'Masculino' THEN 'M' END AS SEXO
, PROFISSAO
, [NOME CONJUJE] AS CONJUJE
, CONTATO
, CONVERT (DATE,DATACAD) AS CADASTRO
, LIMITEATUAL AS LIMITE_CREDITO
FROM CLIENTES
