SELECT
	CLIENTES.CLICODIGO AS CODIGO,
	CLIENTES.CLICNPJCPF AS CNPJ_CNPF,
	CLIENTES.CLIIERG AS IE_RG,
	CLIENTES.CLINOME AS NOME,
	CLIENTES.CLIENDERECO AS ENDERECO,
	CLIENTES.CLINUMERO AS NUMERO,
	CLIENTES.CLICOMPLEMENTO AS COMPLEMENTO,
	CLIENTES.CLIBAIRRO AS BAIRRO,
	CLIENTES.CLICIDADE AS CIDADE,
	CLIENTES.CLIUF AS UF,
	CLIENTES.CLIFONE1 AS TELEFONE,
	CLIENTES.CLIFONE2 AS CELULAR,
	CLIENTES.CLIEMAIL AS EMAIL,
	CLIENTES.CLICEP AS CEP,
	CLIENTES.CLINASCIMENTO AS NASCIMENTO
FROM
	CLIENTES
