SELECT FORNECEDORES.FORCODIGO AS CODIGO,
FORNECEDORES.FORCPFCNPJ AS CNPJ_CNPF,
FORNECEDORES.FORIE,
FORNECEDORES.FORRAZAO AS NOME,
FORNECEDORES.FORFANTASIA AS FANTASIA,
FORNECEDORES.FORENDERECO AS ENDERECO,
FORNECEDORES.FORNUMERO AS NUMERO,
FORNECEDORES.FORCOMPLEMENTO AS COMPLEMENTO,
FORNECEDORES.FORBAIRRO AS BAIRRO,
FORNECEDORES.FORCEP AS CEP,
FORNECEDORES.FORCIDADE AS CIDADE,
FORNECEDORES.FORUF AS UF,
FORNECEDORES.FOREMAIL AS EMAIL,
FORNECEDORES.FORFONE1 AS TELEFONE,
FORNECEDORES.FORCONTATO AS CONTATO
FROM FORNECEDORES

