SELECT
  PECAS.ID AS CODIGO,
  PECAS.REFERENCIA AS COD_FABRICANTE,
  PECAS.DESCRICAO AS DESCRICAO,
  PECAS.SALDO AS QTD,
  PECAS.CST AS ST,
  PECAS.CUSTO_MEDIO AS CUSTO_MEDIO,
  PECAS.PRECO_VAREJO AS PRECO_VENDA,
  PECAS.PRECO_ATACADO AS PRECO_ATACADO,
  PECAS.PRECO_CUSTO AS PRECO_CUSTO,
  CAST (PECAS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
  CAST (PECAS.DATA_ALTERACAO AS DATE) AS ALTERACAO_PRECO,
  PECAS.CLASSIFICACAO_FISCAL AS COD_NCM,
  PECAS.CODIGO_BARRA AS BARRAS,
  PECAS.NFE_CEST AS PERSONAL6
FROM PECAS