SELECT CLIENTES.ID AS CODIGO,
CLIENTES.NOME,
CLIENTES.ENDERECO,
CLIENTES.COMPLEMENTO,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.UF,
CLIENTES.CEP,
CASE WHEN CLIENTES.CPF='' THEN CLIENTES.CNPJ
ELSE CLIENTES.CPF END AS CNPJ_CNPF,
CLIENTES.INSC_ESTADUAL AS IE_RG,
CLIENTES.DDD||CLIENTES.TELEFONE,
CLIENTES.FAX,
CLIENTES.CELULAR,
CLIENTES.DATA_CADASTRO AS CADASTRO,
CLIENTES.EMAIL,
CLIENTES.END_NUM AS NUMERO,
CLIENTES.S_APELIDO AS FANTASIA
FROM CLIENTES
