SELECT
PRODUTOS.CODIGO_INTERNO AS CODIGO,
PRODUTOS.CODIGO_BARRAS AS BARRAS,
PRODUTOS.CODIGO_INTERNO AS COD_FABRICANTE,
PRODUTOS.DESCRICAO,
DEPARTAMENTOS.S_DESCRICAO AS GRUPO,
SESSOES.S_DESCRICAO AS FAMILIA,
PRODUTOS.UNIDADE AS UND,
SUBSTRING (PRODUTOS.ST FROM 1 FOR 3) AS ST,
PRODUTOS.PRECO_CUSTO,
PRODUTOS.ESTOQUE_ATUAL AS QTD,
PRODUTOS.PRECO_VENDA1 AS PRECO_VENDA,
PRODUTOS.ULT_VENDA AS ULTIMA_VENDA,
PRODUTOS.ULT_ALTERACAO AS ALTERACAO_PRECO,
PRODUTOS.DATA_INCLUSAO AS DATA_CADASTRO,
PRODUTOS.ULT_COMPRA AS ULTIMA_COMPRA,
PRODUTOS.CUSTO_MEDIO,
PRODUTOS.S_NCM AS COD_NCM,
PRODUTOS.S_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN DEPARTAMENTOS ON PRODUTOS.DEPARTAMENTO=DEPARTAMENTOS.ID
LEFT JOIN SESSOES ON PRODUTOS.SESSAO=SESSOES.ID
where produtos.ativo = '1'
