SELECT
AGENTES.NOME AS NOME,
AGENTES.FANTASIA AS FANTASIA,
AGENTES.DOC AS CNPJ_CNPF,
ENDERECOS.LOGRADOURO AS ENDERECO,
ENDERECOS.CEP AS CEP,
ENDERECOS.BAIRRO AS BAIRRO,
ENDERECOS.NUMERO AS NUMERO,
ENDERECOS.COMPLEMENTO AS COMPLEMENTO,
CIDADES.CIDADE,
CIDADES.UF
FROM AGENTES
LEFT JOIN ENDERECOS ON ENDERECOS.AGENTE = AGENTES.ID
LEFT JOIN CIDADES ON CIDADES.ID = ENDERECOS.CIDADE
