SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    FORNECEDOR.NOME AS NOME,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.CIDADE AS CIDADE,
    FORNECEDOR.UF AS UF,
    FORNECEDOR.FONE AS TELEFONE,
    FORNECEDOR.CGC AS CNPJ_CNPF,
    FORNECEDOR.INSCEST AS IE_RG,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.CONTATO AS CONTATO,
    FORNECEDOR.OBS AS OBSERVACOES,
    FORNECEDOR.END_ELETRONICO AS EMAIL
FROM FORNECEDOR
