SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.CODBARRA AS BARRAS,
    GRUPOS.descricao AS grupo,
    SUBGRUPOS.descricao AS FAMILIA,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.ESTMIN AS QTD_IDEAL,
    PRODUTOS.PRMEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARLUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRVENDA AS PRECO_VENDA,
    PRODUTOS.PRPROMOCAO AS PRECO_ATACADO,
    PRODUTOS.DTCOMPRA AS ULTIMA_COMPRA,
    PRODUTOS.DTVENDA AS ULTIMA_VENDA,
    FORNECEDOR.NOME AS FORNECEDOR,
    PRODUTOS.OBS AS OBSERVACOES,
    PRODUTOS.PRCUSTO AS PRECO_CUSTO,
    PRODUTOS.COMISSAO AS COMISSAO,
    PRODUTOS.CLASFIS AS COD_NCM,
    SUBSTRING( PRODUTOS.CST FROM 2 FOR 3) AS ST,
    PRODUTOS.PESOL AS PESO,
    PRODUTOS.DTCADASTRO AS DATA_CADASTRO,
    PRODUTOS.COD_SIMILAR AS COD_FABRICANTE,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.grupo = PRODUTOS.grupo
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.codigo = PRODUTOS.subgrupo
LEFT JOIN FORNECEDOR ON FORNECEDOR.codigo = PRODUTOS.fornecedor
