SELECT PRODUTO.COD_PRODUTO AS COD_FABRICANTE,
PRODUTO.CODBARRA_PRO AS BARRAS,
PRODUTO.DESCRICAO_PRO AS DESCRICAO,
GRUPO.DESCRICAO_GRP as grupo,
produto.UNIDADE_PRO as und,
produto.CONTA_NCM as cod_ncm,
produto.COD_CEST as personal6,
PRODUTO_INFORMACAO.LOCAL_INF as caracteristica,
PRODUTO_INFORMACAO.VALOR_TABELA_1 as preco_venda
from produto
left join grupo on PRODUTO.COD_GRUPO=grupo.COD_GRUPO
left join PRODUTO_INFORMACAO on produto.COD_PRODUTO=PRODUTO_INFORMACAO.COD_PRODUTO




