SELECT
    CLF_CLIFOR.ID_CLIFOR AS CODIGO,
    CLF_PESSOAFISICA.CPF AS CNPJ_CNPF,
    CLF_PESSOAFISICA.RG AS IE_RG,
    CLF_CLIFOR.DTCADASTRO AS CADASTRO,
    CLF_CLIFOR.NOME,
    CLF_CLIFORENDERECO.logradouro AS ENDERECO,
    CLF_BAIRRO.NOME AS BAIRRO,
    CLF_CIDADE.NOME AS CIDADE,
    CLF_CIDADE.SIGLAESTADO AS UF,
    CLF_CLIFORENDERECO.numero, 
    CLF_CLIFORENDERECO.cep,
    CLF_CLIFORENDERECO.COMPLEMENTO,
    CLF_TELEFONE.ddd || CLF_TELEFONE.NUMERO AS TELEFONE,
    CLF_CLIFOR.EMAIL,
    CLF_CLIFOR.OBSERVACAO AS OBSERVACOES
FROM CLF_CLIFOR
LEFT JOIN CLF_CLIFORENDERECO ON CLF_CLIFOR.ID_CLIFOR = CLF_CLIFORENDERECO.id_clifor
LEFT JOIN CLF_BAIRRO ON CLF_CLIFORENDERECO.CODBAIRRO = CLF_BAIRRO.CODBAIRRO
LEFT JOIN CLF_CIDADE ON CLF_CLIFORENDERECO.CODCIDADE = CLF_CIDADE.CODCIDADE
LEFT JOIN CLF_PESSOAFISICA ON CLF_CLIFOR.ID_CLIFOR = CLF_PESSOAFISICA.ID_CLIFOR
LEFT JOIN CLF_TELEFONE ON CLF_CLIFOR.ID_CLIFOR = CLF_TELEFONE.ID_CLIFOR
where CLF_CLIFOR.TIPO='C'
