SELECT
    EST_MERCADORIA.ID_MERCADORIA AS CODIGO,
    EST_CODIGOMERCADORIA.CODIGO AS BARRAS,
    EST_SUBGRUPO.NOME AS FAMILIA,
    EST_GRUPO.NOME AS GRUPO,
    EST_GRUPO.NCM AS COD_NCM,
    EST_GRUPO.CEST AS PERSONAL6,
    EST_MERCADORIA.CODCST AS ST,
    EST_UNIDADE.NOME AS UND,
    EST_MERCADORIA.DESCRICAO,
    EST_MERCADORIA.ESTOQUEMIM AS QTD_IDEAL,
    EST_MERCADORIA.SALDO AS QTD,
    EST_MERCADORIA.PRECOCUSTO AS PRECO_CUSTO,
    EST_MERCADORIA.PRECOVENDA AS PRECO_VENDA,
    EST_MERCADORIA.PRECOMEDIO AS CUSTO_MEDIO
FROM EST_MERCADORIA
LEFT JOIN EST_UNIDADE ON EST_MERCADORIA.CODUNIDADE = EST_UNIDADE.CODUNIDADE
LEFT JOIN EST_SUBGRUPO ON EST_MERCADORIA.CODSUBGRUPO = EST_SUBGRUPO.CODSUBGRUPO
LEFT JOIN EST_GRUPO ON EST_MERCADORIA.CODGRUPO = EST_GRUPO.CODGRUPO
LEFT join EST_CODIGOMERCADORIA ON EST_MERCADORIA.ID_MERCADORIA = EST_CODIGOMERCADORIA.ID_MERCADORIA
WHERE EST_CODIGOMERCADORIA.codtipocodigomercadoria = '1'
