SELECT
    FOR_CODIGO AS CODIGO,
    FOR_RAZAO AS NOME,
    FOR_ENDERECO AS ENDERECO,
    FOR_BAIRRO AS BAIRRO,
    FOR_CIDADE AS CIDADE,
    FOR_UF AS UF,
    FOR_CEP AS CEP,
    FOR_FONE AS TELEFONE,
    FOR_FAX AS FAX,
    FOR_CGC_CPF AS CNPJ_CNPF,
    FOR_CGF AS IE_RG,
    FOR_CONTATO AS CONTATO
FROM FORNEC