SELECT
    CAST (P.PAGCOD AS INTEGER) AS ID,
    SUBSTRING (P.PAGDOCUMENTO FROM 1 FOR 14) AS DOCUMENTO,
    P.PAGCOD ||' / '|| P.PAGDOCUMENTO AS HISTORICO,
    F.FORCOD AS COD_FORNECEDOR,
    F.FORNOME AS NOM_FORNECEDOR,
    P.PAGDTLANCAMENTO AS EMISSAO,
    P.PAGDTVENCIMENTO AS VENCIMENTO,
    P.PAGDTPAGAMENTO AS PAGAMENTO,
    P.PAGVALORORIGINAL AS VALOR_DUP,
    P.PAGDESCONTO AS VALOR_DES,
    P.PAGJUROS AS VALOR_JUR,
    P.PAGVALORPAGO AS VALOR_PAG,
    TPA.TPAGDESCR AS PORTADOR,
    P.PAGNOTAFISCAL ||' / '||P.PAGOBS AS OBSERVACOES
FROM PAGAR AS P
LEFT JOIN FORNECEDOR F ON P.PAGFORNECEDOR = F.FORCOD
LEFT JOIN TIPOPAGAMENTO TPA ON P.PAGTIPOPAGAMENTO = TPA.TPAGCOD 