SELECT 
    PRODUTO.PROCOD AS CODIGO,
    PRODUTO.PRODESCR AS DESCRICAO,
    PRODUTO.PROCODBARRA AS BARRAS,
    UNIDADEMED.UNDMDESCR AS UND,
    GRUPOPRO.GPRODESCR AS GRUPO,
    PRODUTO.PROPESO AS PESO,
    PRODUTO.PROREFERENCIA AS CARACTERISTICAS,
    PRODUTO.PROESTQ AS QTD,
    PRODUTO.PROESTQMIN AS QTD_IDEAL,
    PRODUTO.PROPRECOCOMPRA AS PRECO_CUSTO,
    PRODUTO.PROPRECO AS PRECO_VENDA,
    PRODUTO.PROOBS AS OBSERVACOES,
    PRODUTO.PROREFFORNECEDOR AS COD_FABRICANTE,
    PRODUTO.PRONCM AS COD_NCM,
    PRODUTO.PROCADASTRO AS DATA_CADASTRO,
    PRODUTO.PROULTALTERA AS ALTERACAO_PRECO,
    PRODUTO.PROCEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPOPRO on GRUPOPRO.GPROCOD = PRODUTO.PROGRUPO
LEFT JOIN UNIDADEMED ON UNIDADEMED.UNDMCOD = PRODUTO.PROUNIDADE
