SELECT ESTOQUE.CODIGO,
ESTOQUE.REFERENCIA AS BARRAS,
ESTOQUE.DESCRICAO,
ESTOQUE.NOME AS GRUPO,
ESTOQUE.FORNECEDOR,
ESTOQUE.MEDIDA AS UND,
ESTOQUE.PRECO AS PRECO_VENDA,
ESTOQUE.CUSTOCOMPR AS PRECO_CUSTO,
ESTOQUE.CUSTOMEDIO AS CUSTO_MEDIO,
ESTOQUE.QTD_ATUAL AS QTD,
ESTOQUE.CF AS COD_NCM,
ESTOQUE.CSOSN AS ST,
ESTOQUE.CEST AS PERSONAL6
FROM ESTOQUE

