SELECT CLIENTE.CODIGO,
CLIENTE.NOME,
CLIENTE.ENDERECO,
CLIENTE.CLI_NUM AS NUMERO,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.UF,
CLIENTE.CEP,
CLIENTE.CPFCNPJ AS CNPJ_CNPF,
CLIENTE.DTNASC AS NASCIMENTO,
CLIENTE.CLI_RG AS IE_RG,
CLIENTE.FONE1 AS TELEFONE,
CLIENTE.CLI_CELULAR AS CELULAR,
CLIENTE.PAI,
CLIENTE.MAE,
CLIENTE.CONJUGE,
CLIENTE.NOME2 AS FANTASIA,
CLIENTE.OBSERVACAO,
CLIENTE.CLI_EMAIL AS EMAIL
FROM CLIENTE



