SELECT ITEM.CODIGO,
ITEM.CODBARRA AS BARRAS,
ITEM.DESCRICAO,
ITEM.REFERENCIA AS COD_FABRICANTE,
ITEM.UM AS UND,
ITEM.PRCCUSTO AS PRECO_CUSTO,
ITEM.PRCVISTA AS PRECO_VENDA,
ESTOQUE.ESTOQUE AS QTD,
ITEM.ITEM_CF AS COD_NCM,
TRIBUTACAO.TRI_CSTUFPJ AS ST,
CLASSE.CLA_NOME AS GRUPO,
ITEM.ITE_CSTPIS AS PIS_CODIGO,
ITEM.ITE_CSTCOFINS AS COFINS_CODIGO,
ITEM.ITE_COFINSSAIDA AS COFINS_ALIQ_NOR,
CASE WHEN ITEM.ITE_COFINSSAIDA > 0 THEN 100
ELSE 0 END AS COFINS_BASE_NOR,
ITEM.ITE_PISSAIDA AS PIS_ALIQ_NOR,
CASE WHEN ITEM.ITE_PISSAIDA > 0.0 THEN 100
ELSE 0 END AS PIS_BASE_NOR,
ITEM.ITE_CEST AS PERSONAL6
FROM ITEM
LEFT JOIN GRUPO ON ITEM.GRUPO=GRUPO.CODIGO
LEFT JOIN TRIBUTACAO ON ITEM.ITE_TRIBUTACAO=TRIBUTACAO.TRI_CODIGO
LEFT JOIN CLASSE ON ITEM.ITE_CLASSE=CLASSE.CLA_CODIGO
LEFT JOIN ESTOQUE ON ITEM.CODIGO=ESTOQUE.CODIGO


