SELECT PRODUTO.CODIGO AS CODIGO,
PRODUTO.DESCRICAO AS DESCRICAO,
PRODUTO.CODBARRA AS BARRAS,
PRODUTO.REFERENCIA AS COD_FABRICANTE,
GRUPO.DESCRICAO AS GRUPO,
MARCA.DESCRICAO AS FAMILIA,
PRODUTO.UNIDADE AS UND,
PRODUTO.PR_CUSTO AS PRECO_CUSTO,
PRODUTO.PR_VENDA AS PRECO_VENDA,
PRODUTO.QTD_ATUAL AS QTD,
PRODUTO.QTD_MIN AS QTD_IDEAL,
PRODUTO.CSOSN AS ST,
PRODUTO.NCM AS COD_NCM,
PRODUTO.PRECO_ATACADO AS PRECO_ATACADO,
PRODUTO.CEST AS PERSONAL6,
case when PRODUTO.SERVICO = 'S' then '09 Serviços' else '00 Mercadoria para Revenda' end as TIPO_ITEM
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
LEFT JOIN MARCA ON MARCA.CODIGO = PRODUTO.FK_MARCA
