SELECT
    PRODUTOS.PROCOD AS CODIGO,
    PRODUTOS.PRODES AS DESCRICAO,
    --GRUPOPROD.GRUPODESCRICAO AS GRUPO,
    PRODUTOS.PROQUA AS QTD,
    PRODUTOS.PROVAL AS PRECO_VENDA,
    PRODUTOS.PROCODBARRA AS BARRAS,
    PRODUTOS.PROCODREF AS COD_FABRICANTE,
    NCM.NCMSIGLA AS COD_NCM,
    UNIDADE.UNIDADESIGLA AS UND,
    UNIDADE.UNIDADESIGLA AS UND_COMPRA,
    SITTRIBUT.SITTRIBUTSIGLA AS ST,
    PRODUTOS.PRODATAULTIMAVENDA AS ULTIMA_VENDA,
    PRODUTOS.PRO_CUSTO_MED AS CUSTO_MEDIO,
    PRODUTOS.PRO_CODCEST AS PERSONAL6,
    PRODUTOS.PROUCUSTO AS PRECO_CUSTO
FROM PRODUTOS
--LEFT JOIN GRUPOPROD ON GRUPOPROD.GRUPOCHAVE = PRODUTOS.PROGRU 
LEFT JOIN NCM ON NCM.NCMCODIGO = PRODUTOS.PRONCM
LEFT JOIN UNIDADE ON UNIDADE.UNIDADESEQ = PRODUTOS.PROUNIDADE
LEFT JOIN SITTRIBUT ON SITTRIBUT.SITTRIBUTSEQ = PRODUTOS.PROSITTRIBUT
