SELECT
FORNCODIGO AS CODIGO,
FORNRAZAO AS NOME,
FORNFANTASIA AS FANTASIA,
FORNENDERECO AS ENDERECO,
FORNCOMPLENTO AS COMPLEMENTO,
FORNBAIRRO AS BAIRRO,
FORNCIDADE AS CIDADE,
FORNUF AS UF,
FORNCEP AS CEP,
FORNFONE1 AS TELEFONE,
FORNFONE2 AS CELULAR,
FORNCONTATO1 AS CONTATO,
FORNFAX AS FAX,
FORNOBS AS OBSERVACOES,
FORNEMAIL1 AS EMAIL,
FORNCNPJCPF AS CNPJ_CNPF,
FORNIE AS IE_RG
FROM FORNECEDORES
