SELECT PRODUTOS.CODIGO as  cod_fabricante,
produtos.cd_produto as codigo,
PRODUTOS.CODIGO_BARRA AS barras,
GRUPOS.GRUPO,
PRODUTOS.DESCRICAO,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.CUSTO AS PRECO_CUSTO,
PRODUTOS.VENDA AS PRECO_VENDA,
PRODUTOS.ULTIMA_VENDA,
PRODUTOS.ULTIMA_COMPRA,
PRODUTOS.OBS AS OBSERVACOES,
PRODUTOS.QUANTIDADE AS QTD,
PRODUTOS.ST,
PRODUTOS.NCM AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.CD_GRUPO=GRUPOS.CD_GRUPO
