SELECT
substring (CLIENTES.COD_CLI FROM 3 FOR 8) AS CODIGO,
CLIENTES.NOM_CLI AS NOME,
CLIENTES.CONHECI AS FANTASIA,
CLIENTES.ENDEREC AS ENDERECO,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.ESTADO AS UF,
CLIENTES.CEP,
CLIENTES.NUMCASA AS NUMERO,
CLIENTES.FONE AS TELEFONE,
CLIENTES.CELULAR,
CLIENTES.RG AS IE_RG,
CLIENTES.CPF AS CNPJ_CNPF
FROM CLIENTES
