SELECT
substring (PRODUTO.COD_PRO FROM 5 FOR 10) AS CODIGO,
PRODUTO.CODIGO AS BARRAS,
GRUPO.DESCRIC AS GRUPO,
SUBGRUPO.DESCRIC AS FAMILIA,
PRODUTO.NOM_PRO AS DESCRICAO,
PRODUTO.MEDIDA AS UND,
PRODUTO.VR_UNID AS PRECO_CUSTO,
PRODUTO.PRE_VEN AS PRECO_VENDA,
PRODUTO.ESTOQUE AS QTD,
PRODUTO.CST AS ST,
PRODUTO.CODNCM AS COD_NCM,
PRODUTO.CDCEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.GRUPO=GRUPO.COD_GRU
LEFT JOIN SUBGRUPO ON PRODUTO.SUBGRUP=SUBGRUPO.COD_SUB


