SELECT
    CODIGO,
    NOME,
    RAZAO_SOCIAL AS FANTASIA,
    ENDERECO,
    BAIRRO,
    CIDADE,
    CEP,
    ESTADO AS UF,
    FONE AS TELEFONE,
    FAX,
    CELULAR,
    CONTATO,
    CGC_CPF AS CNPJ_CNPF,
    INSCR_EST AS IE_RG,
    EMAIL 
FROM FORNECEDORES
