SELECT
    PRODUTOS.CODIGO AS COD_FABRICANTE,
    PRODUTOS.DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.PRECO_VENDA,
    PRODUTOS.PRECO_COMPRA AS PRECO_CUSTO,
    GRUPOS.descricao AS GRUPO,
    PRODUTOS.MARCA AS FAMILIA,
    PRODUTOS.MARGEM_LUCRO
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO = GRUPOS.CODIGO
