SELECT
  PRODUTO.CODIGO AS CODIGO,
  PRODUTO.CODBARRAS AS BARRAS,
  PRODUTO.CODIGOFABRICA AS COD_FABRICANTE,
  PRODUTO.DESCRICAO AS DESCRICAO,
  FAMILIAPRODUTO.DESCRICAO AS FAMILIA,
  GRUPOPRODUTO.DESCRICAO AS GRUPO,
  SUBGRUPOPRODUTO.DESCRICAO AS CARACTERISTICAS,
  CLASSFISCAL.CODIGO AS COD_NCM,
  UNIDADE.UNMAIOR AS UND,
  PRODUTOESTOQUE.SALDO AS QTD,
  PRODUTOCUSTO.PRECOCUSTO AS PRECO_CUSTO,
  PRODUTOCUSTO.PRECOMEDIO AS CUSTO_MEDIO,
  PRODUTOVENDA.PRECOVENDA AS PRECO_VENDA,
  PRODUTO.PESOLIQUIDO AS PESO,
  CAST (PRODUTO.DATAHORACAD AS DATE) AS DATA_CADASTRO,
  PRODUTO.OBS AS OBSERVACOES,
  SUBSTRING (TRIBUTACAO.CODIGO FROM 1 FOR 1) AS OST,
  SUBSTRING (TRIBUTACAO.CODIGO FROM 2 FOR 3) AS ST,
  PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN CLASSFISCAL ON CLASSFISCAL.CHAVE = PRODUTO.CHAVECLASSFISCAL
LEFT JOIN GRUPOPRODUTO ON GRUPOPRODUTO.CHAVE = PRODUTO.CHAVEGRUPO
LEFT JOIN FAMILIAPRODUTO ON FAMILIAPRODUTO.CHAVE = PRODUTO.CHAVEFAMILIA
LEFT JOIN SUBGRUPOPRODUTO ON SUBGRUPOPRODUTO.CHAVE = PRODUTO.CHAVESUBGRUPO
LEFT JOIN UNIDADE ON UNIDADE.CHAVE = PRODUTO.CHAVEUNIDADE
LEFT JOIN GRUPOFISCAL ON GRUPOFISCAL.CHAVE = PRODUTO.CHAVEGRUPOFISCAL
LEFT JOIN PRODUTOESTOQUE ON PRODUTOESTOQUE.CHAVEPRODUTO = PRODUTO.CHAVE
LEFT JOIN PRODUTOCUSTO ON PRODUTOCUSTO.CHAVEPRODUTO = PRODUTO.CHAVE
LEFT JOIN PRODUTOVENDA ON PRODUTOVENDA.CHAVEPRODUTO = PRODUTO.CHAVE
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.CHAVE = GRUPOFISCAL.CHAVETRIBUTACAO
WHERE PRODUTOESTOQUE.CHAVEEMPRESA = '1' AND PRODUTOCUSTO.CHAVEEMPRESA = '1' AND PRODUTO.CHAVEEMPRESA = '1' AND produtovenda.CHAVEEMPRESA = '1'  ----VERIFICAR CHAVE EMPRESA
