SELECT
  CLIFOR.CODIGO AS CODIGO,
  CLIFOR.RAZAOSOCIAL AS RAZAO_SOCIAL,
  CLIFOR.CNPJCPF AS CNPJ,
  CLIFOR.IERG AS IE,
  CLIFOR.ENDERECO AS ENDERECO,
  CIDADE.CIDADE AS CIDADE,
  CIDADE.UF AS UF,
  CLIFOR.TELEFONE AS TELEFONE,
  CLIFOR.EMAIL AS EMAIL
FROM CLIFOR
LEFT JOIN CIDADE ON CIDADE.CHAVE = CLIFOR.CHAVECIDADE
WHERE CLIFOR.TRANSPORTADOR = 'S'
