SELECT
    COD_FORNECEDOR AS CODIGO,
    RAZAO_SOCIAL AS NOME,
    CGC_CPF AS CNPJ_CNPF,
    INSC_ESTADUAL AS IE_RG,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    COMPLEMENTO AS COMPLEMENTO,
    CEP AS CEP,
    CIDADE AS CIDADE,
    UF AS UF,
    TELEFONE AS TELEFONE,
    CELULAR AS CELULAR,
    FAX AS FAX,
    E_MAIL AS EMAIL,  
    OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES