SELECT 
  F.TBL_FOR_ID AS CODIGO
, F.TBL_FOR_RAZAO AS NOME
, F.TBL_FOR_FANTAZIA AS FANTASIA
, F.TBL_FOR_END AS ENDERECO
, F.TBL_FOR_NR_RESIDE AS NUMERO
, F.TBL_FOR_BAIRRO AS BAIRRO
, F.TBL_FOR_CEP AS CEP
, CI.CID_NOME AS CIDADE
, CI.EST_UF AS UF
, F.TBL_FOR_FONE1 AS TELEFONE
, F.TBL_FOR_FONE2 AS CELULAR
, F.TBL_FOR_FONE_FAX AS FAX
, F.TBL_FOR_CGC AS CNPJ_CNPF
, F.TBL_FOR_INSC AS IE_RG
, F.TBL_FOR_EMAIL AS EMAIL
, F.TBL_FOR_RESPONSAVEL AS CONTATO
, F.TBL_FOR_OBS AS OBSERVACOES
FROM TBL_FORNECEDOR F
LEFT JOIN TBL_CIDADE CI ON CI.CID_CODIGO = F.TBL_FOR_CID_CODIGO 