SELECT CLIENTE.CGC_CPF AS CNPJ_CNPF,
CLIENTE.CADASTRO,
CLIENTE.CLIENTE AS NOME,
CLIENTE.APELIDO AS FANTASIA,
CLIENTE.ENDERECO,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.UF,
CLIENTE.CEP,
CLIENTE.RG_IE AS IE_RG,
CLIENTE.TELEFONE,
CLIENTE.NASC AS NASCIMENTO,
CLIENTE.ID_CLIENTE AS CODIGO,
CLIENTE.CELULAR,
CLIENTE.EMAIL
FROM CLIENTE


