SELECT FORNECEDOR.ID_FORNECEDOR AS CODIGO,
FORNECEDOR.RAZAO_SOC AS NOME,
FORNECEDOR.NOME_FANTA AS FANTASIA,
FORNECEDOR.CNPJ AS CNPJ_CNPF,
FORNECEDOR.IE AS IE_RG,
FORNECEDOR.ENDERECO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CIDADE,
FORNECEDOR.CEP,
FORNECEDOR.UF,
FORNECEDOR.TELEFONE,
FORNECEDOR.LISTA_EMAIL AS EMAIL
FROM FORNECEDOR
