SELECT
    CODIGO,
    NOMERAZAO AS NOME, 
    FANTASIA,
    CPFCNPJ AS CNPJ_CNPF,
    RGINSC AS IE_RG,
    ENDERECO,
    NUMERO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    UF,
    CEP,
    FONE AS TELEFONE
FROM FORNECEDOR
