SELECT PRODUTOS.CODIGO,
PRODUTOS.NOME AS DESCRICAO,
MARCAS.NOME AS CARACTERISTICAS,
GRUPOS.NOME AS FAMILIA,
SUB_GRUPOS.NOME AS GRUPO,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.CBARRA AS BARRAS,
CASE WHEN PRODUTOS.COD_CSTTRIBICMS IN(-1,0) THEN '102'
ELSE PRODUTOS.COD_CSTTRIBICMS END AS ST,
PRODUTOS.UNIDADE_COMPRA AS UND_COMPRA,
PRODUTOS.CODIGO_NCM AS COD_NCM,
PRODUTOS.COD_CEST AS PERSONAL6,
PRODLOJAS.C_AQUIS AS PRECO_CUSTO,
PRODLOJAS.PCO_REMAR AS PRECO_VENDA,
PRODLOJAS.EST_ATUAL AS QTD
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO=GRUPOS.CODIGO
LEFT JOIN SUB_GRUPOS ON PRODUTOS.SUBG=SUB_GRUPOS.CODIGO
LEFT JOIN MARCAS ON PRODUTOS.MARCA=MARCAS.CODIGO
LEFT JOIN PRODLOJAS ON PRODUTOS.CODIGO=PRODLOJAS.CODIGO




