SELECT
C.CODIGO
,C.CPF_CNPJ AS CNPJ_CNPF
,C.INSCRICAOEST AS IE_RG
,C.INSCRICAOMUNICIPAL AS IM
,C.NOME
,C.FANTASIA
,C.ENDERECO
,C.NUMERO
,C.BAIRRO
,CI.CIDADE
,CI.UF
,C.CEP
,C.COMPLEMENTO
,C.FONE AS TELEFONE
,C.FAX
,C.CONTATO
,C.EMAIL
,C.CELULAR AS CELULAR
,CASE WHEN C.DATACAD IS NULL THEN CURRENT_DATE
ELSE DATACAD END AS CADASTRO,
CONCAT (OB.DESCRICAO,' - ',OB2.DESCRICAO) AS OBSERVACOES
FROM CLIENTES C
LEFT JOIN CIDADES CI ON C.CEP = CI.CEP
LEFT JOIN OBSERVACOES OB ON OB.CODIGO = C.CODOBSERVACAO
LEFT JOIN OBSERVACOES OB2 ON OB2.CODIGO = C.CODOBSERVACAO2
