SELECT  
            --PRODUTOS.CODIGO
           PRODUTOS.codigo AS COD_FABRICANTE
           ,PRODUTOS.DESCRICAO AS DESCRICAO
           ,PRODUTOS.CODBARRA AS BARRAS 
           ,PRODUTOS.UNIDADE AS UND
           ,PRODUTOS.QUANTIDADE AS QTD
           ,PRODUTOS.PRECOCUSTO AS PRECO_CUSTO
           ,PRODUTOS.PRECOVENDA AS PRECO_VENDA
           ,PRODUTOS.PRECOVENDA AS PRECO_IFOOD
           ,PRODUTOS.COD_NCM 
           ,SUBSTRING(PRODUTOS.SITUACAOTRIBUTARIA,1,1) AS OST
           ,SUBSTRING(PRODUTOS.SITUACAOTRIBUTARIA,2,4) AS ST
           ,CONCAT(PRODUTOS.APLICACAO,' ',PRODUTOS.OBSERVACOES) AS OBSERVACOES
           ,PRODUTOS.CEST AS PERSONAL6
           ,CASE PRODUTOS.ATIVO WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
           ,PRODUTOS.MARCA AS PERSONAL1
           ,PRODUTOS.LOCALIZACAO AS PERSONAL2
           ,PRODUTOS.TIPO_MERCADORIA AS PERSONAL4
           ,PRODUTOS.PESO_BRUTO AS PESO
           ,PRODUTOS.IPI AS ALIQ_IPI_VENDA
           ,PRODUTOS.IPI_ENTRADA AS ALIQ_IPI
           ,PRODUTOS.CODIGO_ANP AS COD_ANP
           ,PRODUTOS.BENEFICIO AS CBENEF
           ,GRUPO_PRODUTOS.NOME AS GRUPO
           ,SUBGRUPO_PRODUTOS.NOME AS FAMILIA           
           ,D.NOME AS CARACTERISTICAS  
           ,B.DIAS_VALIDADE AS VALIDADE_DIAS    
           ,EI.EST_MINIMO AS QTD_IDEAL
           ,I.CST AS IPI_CODIGO_VENDA
           ,I.CST_ENTRADA AS IPI_CODIGO
           ,PC.CST_PIS AS PIS_CODIGO
           ,PC.CST_COFINS AS COFINS_CODIGO
           ,PC.CST_PIS_ENTRADA AS PISE_CODIGO
           ,PC.CST_COFINS_ENTRADA AS COFINSE_CODIGO
           ,PC.PIS_ALIQ AS PIS_ALIQ_NOR
           ,PC.COFINS_ALIQ AS COFINS_ALIQ_NOR
           ,PC.PIS_ALIQ_ENTRADA AS PISE_ALIQ_NOR
           ,PC.COFINS_ALIQ_ENTRADA AS COFINSE_ALIQ_NOR
FROM PRODUTOS  
          LEFT JOIN GRUPO_PRODUTOS ON PRODUTOS.GRUPO=GRUPO_PRODUTOS.CODIGO
          LEFT JOIN SUBGRUPO_PRODUTOS ON PRODUTOS.SUBGRUPO=SUBGRUPO_PRODUTOS.CODIGO
          LEFT JOIN DEPARTAMENTOS D ON D.CODIGO = PRODUTOS.DEPARTAMENTO 
          LEFT JOIN BALANCAS B ON B.PRODUTO = PRODUTOS.CODIGO
          LEFT JOIN ESTOQUE_INICIAL EI ON EI.CD_PRODUTO = PRODUTOS.CODIGO 
          LEFT JOIN PRODUTOS_IPI I ON I.COD_PRODUTO = PRODUTOS.CODIGO 
          LEFT JOIN PIS_COFINS PC ON PC.PRODUTO = PRODUTOS.CODIGO 
ORDER BY PRODUTOS.CODIGO ASC
           
