SELECT GPFORNECEDOR.CD_FORNECEDOR AS CODIGO,
GPFORNECEDOR.ES_CGC AS CNPJ_CNPF,
GPFORNECEDOR.ES_IC AS IE_RG,
GPFORNECEDOR.ES_ENDERECO AS ENDERECO,
GPFORNECEDOR.ES_BAIRRO AS BAIRRO,
GPFORNECEDOR.ES_CIDADE AS CIDADE,
GPFORNECEDOR.ES_CEP AS CEP,
GPFORNECEDOR.ES_ESTADO AS UF,
GPFORNECEDOR.ES_CONTATO AS CONTATO,
GPFORNECEDOR.ES_TELEFONE AS TELEFONE,
GPFORNECEDOR.ES_EMAIL AS EMAIL,
GPFORNECEDOR.DS_FORNECEDOR AS NOME,
GPFORNECEDOR.SG_FORNECEDOR AS FANTASIA
FROM GPFORNECEDOR
WHERE GPFORNECEDOR.CD_FORNECEDOR>0

