SELECT
	P.NCOD___PESSOA AS CODIGO,
	P.VNOME__PESSOA AS NOME,
	DATE(P.DREGISTPESSOA) AS CADASTRO,	
	P.VFONE__PESSOA AS TELEFONE,
	P.VEMAIL_PESSOA AS EMAIL,
--	P.NCLASSEPESSOA, -- INFORMAÇÃO INCERTA, POSSIVELMENTE PARA IDENTIFICAR O TIPO DO CLIENTE
	E.VLOGRADENDPES AS ENDERECO,
	E.VCEP___ENDPES AS CEP,
	E.VNUMER_ENDPES AS NUMERO,
	E.VCOMPL_ENDPES AS COMPLEMENTO,
	E.VBAIRROENDPES AS BAIRRO,
	M.VNOME__MUNICI AS CIDADE,
	U.CSIGLA_UNIFED AS UF,
	PC.NLIMITEPESCLI AS LIMITE_CREDITO,
	PC.VAUTORIPESCLI AS PERSONAL1,
	PP.VIE____PESPRO AS PERSONAL2, --IE
	PF.CSEXO__PESFIS AS SEXO,
	PF.VMAE___PESFIS AS MAE,
	CASE WHEN PF.VCPF___PESFIS = '' OR PF.VCPF___PESFIS IS NULL THEN PJ.VCNPJ__PESJUR ELSE PF.VCPF___PESFIS END AS CNPJ_CNPF,
	CASE WHEN PF.VRG____PESFIS = '' OR PF.VRG____PESFIS IS NULL THEN PJ.VIE____PESJUR ELSE PF.VRG____PESFIS END AS IE_RG,
	PJ.VIM____PESJUR AS IM,
	DATE(PF.DNASC__PESFIS) AS NASCIMENTO,	
	PF.VEMPR__PESFIS AS LOCTRA,
	PF.VPROFISPESFIS AS PROFISSAO,
	PJ.VFANT__PESJUR AS FANTASIA,
	PJ.VCONTATPESJUR AS CONTATO
FROM
	GERA.PESSOA P
LEFT JOIN GERA.ENDPES E ON E.NID____PESSOA = P.NID____PESSOA AND E.CSITUACREGSIN = 'A' 
LEFT JOIN GERA.MUNICI M ON M.NIBGE__MUNICI = E.NIBGE__MUNICI 
LEFT JOIN GERA.UNIFED U ON U.NCODUF_UNIFED = M.NCODUF_UNIFED
LEFT JOIN GERA.PESCLI PC ON PC.NID____PESCLI = P.NID____PESSOA AND PC.CSITUACREGSIN = 'A' 
LEFT JOIN GERA.PESPRO PP ON PP.NID____PESPRO = P.NID____PESSOA AND PP.CSITUACREGSIN = 'A' 
LEFT JOIN GERA.PESFIS PF ON PF.NID____PESFIS = P.NID____PESSOA AND PF.CSITUACREGSIN = 'A'
LEFT JOIN GERA.PESJUR PJ ON PJ.NID____PESJUR = P.NID____PESSOA AND PJ.CSITUACREGSIN = 'A'
WHERE P.CSITUACREGSIN = 'A'
ORDER BY P.NCOD___PESSOA