SELECT 
  PK_CLIENTES AS CODIGO
, CLFANTASIA AS FANTASIA
, CLRAZAO AS NOME
, CLCGC AS CNPJ_CNPF
, CLIE AS IE_RG
, CLENDERECO AS ENDERECO
, CLCEP AS CEP
, CLNUMERO AS NUMERO
, CLBAIRRO AS BAIRRO
, CLCIDADE AS CIDADE
, CLUF AS UF
, CLCOMPLEMENTO AS COMPLEMENTO
, CLCREDEMPRESANOME AS LOCTRA
, CLCREDCARGO AS PROFISSAO
, CLCREDNOMECONJUGE AS CONJUGE
, CLCREDVLRLIMITE AS LIMITE_CREDITO
, CLFONE1 AS TELEFONE
, CLFONE2 AS CELULAR
, CLFONE3 AS FAX
, CLOBSERVACAO AS OBSERVACOES
, CLDTNASCIMENTO AS NASCIMENTO
, CLEMAIL AS EMAIL
, CLCOBENDERECO AS COB_ENDERECO
, CLCOBBAIRRO AS COB_BAIRRO
, CLCOBCIDADE AS COB_CIDADE
, CLCOBUF AS COB_UF
, CLCOBCOMPLEMENTO AS COB_COMPLEMENTO
, CLCOBNUMERO AS COB_NUMERO
, CLCOBCEP AS COB_CEP
, CLCREDNOMEPAI AS PAI
, CLCREDNOMEMAE AS MAE
, DATE (CLDTULTIMAVENDA) AS ULTIMA_VENDA
FROM CA_CLIENTES
WHERE PK_CLIENTES > 0
