SELECT 
  PK_FORNECEDORES AS CODIGO 
  , FORAZAO AS NOME
  , FOFANTASIA AS FANTASIA
  , FOCNPJ AS CNPJ_CNPF
  , FOIE AS IE_RG
  , FOENDERECO AS ENDERECO
  , FOCOMPLEMENTO AS COMPLEMENTO
  , FOBAIRRO AS BAIRRO
  , FOCIDADE AS CIDADE
  , FOUF AS UF
  , FOCEP AS CEP
  , FONUMERO AS NUMERO
  , FOOBSERVACAO AS OBSERVACOES
  , FOFONE1 AS TELEFONE
  , FOFONE2 AS CELULAR
  , FOFAX AS FAX
  , FOEMAIL AS EMAIL
FROM CA_FORNECEDORES
WHERE PK_FORNECEDORES > 0
