SELECT 
  P.PRODSEQUENCIA AS CODIGO
, P.PRODDESCRICAO AS DESCRICAO
, DATE (P.PRODTCADASTRO) AS DATA_CADASTRO
, P.PRODCODEXTERNO AS COD_FABRICANTE
, CASE P.PRODINATIVO WHEN 'N' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.PRODDIASVALIDADEBALANCA AS VALIDADE_DIAS
, P.PRODPESOBRUTO AS PESO
, P.PRODOBSVENDA AS OBSERVACOES
, P.PRODCEST AS PERSONAL6
, P.FK_UNIDADEMEDIDA AS UND
, P.FK_CSTIPICOMPRA AS IPI_CODIGO
, PC.CFNBMSH AS COD_NCM
--, PC.CFCFOPVENDA 
--, PC.FK_CSTIPI 
--, PC.CFPERCIPI 
--, PC.FK_CFCSTPIS 
--, PC.CFPERCPIS 
--, PC.FK_CFCSTCOFINS 
--, PC.CFPERCCOFINS 
, PV.VLRCUSTO AS PRECO_CUSTO
, PV.VLRVALORMEDIO AS CUSTO_MEDIO
, PV.VLRVENDA1 AS PRECO_VENDA
, PV.VLRVENDA2 AS PRECO_ATACADO
, PV.VLRESTOQUECRITICO AS QTD_IDEAL
, PV.VLRQTDE AS QTD
, PV.VLRPERCCOMISSAO AS COMISSAO
, PV.FK_CSTIPICOMPRA AS IPI_CODIGO
, PV.FK_CSTIPI AS IPI_CODIGO_VENDA
, PV.VLRPERCPIS AS PIS_ALIQ_NOR
, PV.VLRPERCCOFINS AS COFINS_ALIQ_NOR
, PV.FK_CSTPIS AS PIS_CODIGO
, PV.FK_CSTCOFINS AS COFINS_CODIGO
, PV.FK_CSTPISCOMPRA AS PISE_CODIGO
, PV.FK_CSTCOFINSCOMPRA AS COFINSE_CODIGO
, RIGHT (PV.FK_CST,2) AS ST
, LEFT (PV.FK_CST,1) AS OST
, PV.VLRPERCMARKUP AS MARGEM_LUCRO
, DATE (PV.VLRDTULTIMAVENDA) AS ULTIMA_VENDA
, REPLACE (FN.NATOPESTADUAL,'.','') AS CF
, PG.GRUDESCRICAO AS GRUPO
, PS.SUBDESCRICAO AS FAMILIA
, PS2.SUDESCRICAO AS CARACTERISTICAS
, PD.DEPDESCRICAO AS PERSONAL1 -- NOME DO DEPARTAMENTO
, PF.FABNOME AS FORNECEDOR
, PC2.CORDESCRICAO AS COR
, PT.TMDESCRICAO AS TAMANHO
, PC3.PK_CODBARRAS AS BARRAS
, PA.ALIQUOTA AS ELO
FROM PR_PRODUTOS P
LEFT JOIN PR_CLASSIFICACAOFISCAL PC ON PC.PK_CLASSIFICACAOFISCAL = P.FK_CLASSIFICACAOFISCAL 
LEFT JOIN PR_VLRPRODUTOS PV ON PV.FK_PRODUTOS = P.PK_PRODUTOS 
LEFT JOIN FI_NATOPERACAO FN ON FN.PK_NATOPERACAO = PV.FK_CFOPVENDA 
LEFT JOIN PR_GRUPOS PG ON PG.PK_GRUPOS = P.FK_GRUPO
LEFT JOIN PR_SUBGRUPOS PS ON PS.PK_SUBGRUPOS = P.FK_SUBGRUPO
LEFT JOIN PR_SUBGRUPO2 PS2 ON PS2.PK_SUBGRUPO2 = P.FK_SUBGRUPO2
LEFT JOIN PR_DEPARTAMENTO PD ON PD.PK_DEPARTAMENTO = P.FK_DEPARTAMENTO
LEFT JOIN PR_FABRICANTE PF ON PF.PK_FABRICANTE = P.FK_FABRICANTE 
LEFT JOIN PR_COR PC2 ON PC2.PK_COR = P.FK_COR 
LEFT JOIN PR_TAMANHO PT ON PT.PK_TAMANHO = P.FK_TAMANHO 
LEFT JOIN PR_CODBARRAS PC3 ON PC3.FK_PRODUTOS = P.PK_PRODUTOS AND PC3.CBATIVO = 'S'
LEFT JOIN PR_ALIQUOTA PA ON PA.PK_ALIQUOTA = PV.FK_ALIQUOTA
