SELECT
  PRODUTO.CD_PRODUTO AS COD_FABRICANTE,
  PRODUTO.NM_PRODUTO AS DESCRICAO,
  GRUPROD.NM_GRUPROD AS GRUPO,
  PRODUTO.UN_MEDIDA AS UND,
  PRODUTO.PESO_LIQUIDO AS PESO,
  PRODUTO.CD_ORIGINAL AS CARACTERISTICAS,
  PRODUTO.PC_LUCRO_LIQUIDO AS MARGEM_LUCRO,
  PRODUTO.OBS AS OBSERVACOES,
  PRODUTO.QT_ESTOQUE AS QTD,
  PRODUTO.PC_COMISSAO AS COMISSAO,
  PRODUTO.UN_COMPRA AS UND_COMPRA,
  PRODUTO.DT_CADASTRO AS DATA_CADASTRO,
  PRODUTO.CST_INT AS ST,
  PRODUTO_CLASS_FISCAL.NM_CLASS_FISCAL AS COD_NCM,
  CEST.CEST AS PERSONAL6,
  TABELA_PRECO_PRODUTO.PRECO_VENDA AS PRECO_VENDA
FROM PRODUTO
LEFT JOIN PRODUTO_CLASS_FISCAL ON PRODUTO_CLASS_FISCAL.CD_CLASS_FISCAL = PRODUTO.CD_CLASS_FISCAL
LEFT JOIN CEST ON CEST.CD_CEST = PRODUTO_CLASS_FISCAL.CD_CEST
LEFT JOIN TABELA_PRECO_PRODUTO ON TABELA_PRECO_PRODUTO.CD_PRODUTO = PRODUTO.CD_PRODUTO
LEFT JOIN GRUPROD ON GRUPROD.CD_GRUPROD = PRODUTO.CD_GRUPROD
