SELECT
    TB_PRO.CODIGO AS CODIGO,
    TB_PRO.COD_BARRA AS BARRAS,
    TB_PRO.DESCRICAO AS DESCRICAO,
    TB_PRO.UNIDADE AS UND,
    TB_PRO_GR.DESCRICAO AS GRUPO,
    TB_PRO.CUSTO AS PRECO_CUSTO,
    TB_PRO.VENDA AS PRECO_VENDA,
    TB_PRO.QTD AS QTD,
    TB_PRO.COD_NCM AS COD_NCM,
    TB_PRO.ICMS_CST AS ST,
    TB_PRO.COD_FABRICANTE AS COD_FABRICANTE,
    TB_PRO.CEST AS PERSONAL6
FROM TB_PRO
LEFT JOIN TB_PRO_GR ON TB_PRO.COD_GR = TB_PRO_GR.CODIGO
