SELECT 
  ID AS CODIGO
, DATA_INC AS CADASTRO
, NOME
, APELIDO AS FANTASIA
, CONTATO
, ENDERECO
, BAIRRO
, CIDADE
, ID_UF AS UF
, CEP
, FONE1 AS TELEFONE
, FONE2 AS PERSONAL1
, FAX
, CELULAR
, CNPJCPF AS CNPJ_CNPF
, IERG AS IE_RG
, DATANASC AS NASCIMENTO
, REFERENCIA AS COMPLEMENTO
, CREDITO AS LIMITE_CREDITO
, ENDERE_COB AS COB_ENDERECO
, BAIRRO_COB AS COB_BAIRRO
, CIDADE_COB AS COB_CIDADE
, UF_COB AS COB_UF
, CEP_COB AS COB_CEP
, FONE_COB AS PERSONAL2
FROM CLIENTES