SELECT
  ID AS CODIGO
, NOME
, APELIDO AS FANTASIA
, CONTATO
, VENDEDOR AS PERSONAL2
, FONEVEND AS PERSONAL3
, CELVEND AS PERSONAL4
, ENDERECO
, BAIRRO
, CIDADE
, ID_UF AS UF
, CEP
, FONE1 AS TELEFONE
, FONE2 AS PERSONAL1
, FAX
, CELULAR
, CNPJCPF AS CNPJ_CNPF
, IERG AS IE_RG
, REFERENCIAS AS COMPLEMENTO
, EMAIL
FROM FORNECEDOR