SELECT
FORNECED.FOCODIGO AS CODIGO,
FORNECED.NOME,
FORNECED.FANTASIA,
FORNECED.ENDERECO,
FORNECED.BAIRRO,
FORNECED.NUMEROCOM AS NUMERO,
FORNECED.COMPLEMENTOCOM AS COMPLEMENTO,
CIDADES.NOME AS CIDADE,
FORNECED.UF,
FORNECED.CEP,
FORNECED.TELEFONE,
FORNECED.CELULAR,
FORNECED.FAX,
FORNECED.CGC AS CNPJ_CNPF,
FORNECED.INSCRICA AS IE_RG
FROM FORNECED
LEFT JOIN CIDADES ON FORNECED.CICODIGO=CIDADES.CICODIGO

