SELECT
	P.RAZAOSOCIAL AS NOME,
	P.NOMEFANTASIA AS FANTASIA,
	P.CNPJ_CPF AS CNPJ_CNPF,
	P.INSCRICAOESTADUAL AS IE_RG,
	P.EMAIL AS EMAIL,
	P.TELEFONE AS TELEFONE,
	--P.DATACADASTRO AS CADASTRO,
	PE.Logradouro AS ENDERECO,
	PE.Numero AS NUMERO,
	PE.Bairro AS BAIRRO,
	PE.Municipio AS CIDADE,
	PE.UF AS UF,
	PE.CEP AS CEP
FROM PESSOA P
	LEFT JOIN PessoaEndereco PE ON PE.idPessoa = P.idPessoa
	RIGHT JOIN PessoaFornecedor pf ON PF.idPessoa = P.idPessoa
