SELECT
  FORNECEDOR.RAZAO_SOCIAL AS NOME,
  FORNECEDOR.NOME_FANTASIA AS FANTASIA,
  FORNECEDOR.ENDERECO AS ENDERECO,
  FORNECEDOR.BAIRRO AS BAIRRO,
  CIDADE.DESCRICAO AS CIDADE,
  CIDADE.UF AS UF,
  case when FORNECEDOR.CNPJ = '' or FORNECEDOR.CNPJ is null then FORNECEDOR.CPF else FORNECEDOR.CNPJ END as CNPJ_CNPF,
  FORNECEDOR.INSCRICAO AS IE_RG,
  FORNECEDOR.FONE1 AS TELEFONE,
  FORNECEDOR.FAX AS FAX,
  FORNECEDOR.CELULAR AS CELULAR,
  FORNECEDOR.REPRESENTANTE AS CONTATO,
  FORNECEDOR.EMAIL AS EMAIL,
  FORNECEDOR.OBSERVACAO AS OBSERVACOES,
  FORNECEDOR.NUMERO AS NUMERO,
  FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
  FORNECEDOR.CEP AS CEP
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.ID_CIDADE = FORNECEDOR.ID_CIDADE
