SELECT
  PRODUTO.ID_PRODUTO AS CODIGO,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.REFERENCIA AS CARACTERISTICAS,
  GRUPO.`DESCRICAO` AS GRUPO,
  FORNECEDOR.`RAZAO_SOCIAL` AS FORNECEDOR,
  CONCAT (PRODUTO.MARCA, ' -- ' ,PRODUTO.CODIGO) AS OBSERVACOES,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.SALDO_ATUAL AS QTD,
  PRODUTO.ESTOQUE_MINIMO AS QTD_IDEAL,
  PRODUTO.ULTIMA_COMPRA AS ULTIMA_COMPRA,
  PRODUTO.ULTIMA_VENDA AS ULTIMA_VENDA,
  PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
  PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTO.PRECO_VENDA1 AS PRECO_VENDA,
  PRODUTO.MARGEM1 AS MARGEM_LUCRO,
  SIMPLES_NACIONAL.`CODIGO_SIMPLES` AS ST,
  PRODUTO.PESO_LIQUIDO AS PESO,
  PRODUTO.FATOR_CONVERSAO AS FAT_CONV,
  PRODUTO.COD_FORNECEDOR AS COD_FABRICANTE,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.CODIGO_BARRA AS BARRAS,
  PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.`ID_GRUPO` = PRODUTO.`ID_GRUPO`
LEFT JOIN FORNECEDOR ON FORNECEDOR.`ID_FORNECEDOR` = PRODUTO.`ID_FORNECEDOR`
LEFT JOIN SIMPLES_NACIONAL ON SIMPLES_NACIONAL.`ID_SIMPLES` = PRODUTO.ID_SN
