SELECT
	--CODCLI AS CODIGO,
	DESCRICAO AS NOME,
	DESCRICAO2 AS FANTASIA,
	CNPJ_CPF AS CNPJ_CNPF,
	INSCRICAO_ID AS IE_RG,
	ENDERECO AS ENDERECO,
	BAIRRO AS BAIRRO,
	CEP AS CEP,
	CIDADE AS CIDADE,
	UF AS UF,
	OBS AS OBSERVACOES,
	FONE1 AS TELEFONE,
	FONE2 AS CELULAR,
	CONTATO AS CONTATO,
	EMAIL AS EMAIL,
	NUMERO AS NUMERO,
	COMPLEMENTO AS COMPLEMENTO
FROM GPVENDAS_DIMAPOL.dbo.ENTIDADES
WHERE GPVENDAS_DIMAPOL.dbo.ENTIDADES.TIPO = '2'
