SELECT
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.CODIGOCLIENTE AS BARRAS,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.DESCRICAO AS DESCRICAO,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.UNIDADE AS UND,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.PRECOVENDA AS PRECO_VENDA,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.PRECOCOMPRA AS PRECO_CUSTO,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.PRECOMEDIO AS CUSTO_MEDIO,
	GPVENDAS_DIMAPOL.dbo.TIPOPRODUTO.DESCRICAO AS GRUPO,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.PRODUTOID AS COD_FABRICANTE,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.DATACADASTRO AS DATA_CADASTRO,
	CASE GPVENDAS_DIMAPOL.dbo.PRODUTOS.ATIVO WHEN 'N' THEN 'Inativo' ELSE 'Ativo' END SITUACAO,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.CLAFISCAL AS COD_NCM,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.SITTRIBUTARIAID AS ST,
	GPVENDAS_DIMAPOL.dbo.PRODUTOS.cest AS PERSONAL6,
	GPVENDAS_DIMAPOL.dbo.ALMOXLOJAITENS.QUANTIDADE AS QTD
FROM GPVENDAS_DIMAPOL.dbo.PRODUTOS
LEFT JOIN GPVENDAS_DIMAPOL.dbo.TIPOPRODUTO ON GPVENDAS_DIMAPOL.dbo.PRODUTOS.TIPOPROD=GPVENDAS_DIMAPOL.dbo.TIPOPRODUTO.TIPOPROD 
LEFT JOIN GPVENDAS_DIMAPOL.dbo.ALMOXLOJAITENS ON GPVENDAS_DIMAPOL.dbo.PRODUTOS.PRODUTOID=GPVENDAS_DIMAPOL.dbo.ALMOXLOJAITENS.PRODUTOID WHERE GPVENDAS_DIMAPOL.dbo.ALMOXLOJAITENS.ENTIDADEID_LOJA = '1'