SELECT CLIE_DADOS.ID_CLIENTE AS CODIGO,
CLIE_DADOS.NOME_RAZAO AS NOME,
CLIE_DADOS.FANTASIA,
CLIE_DADOS.ENDERECO,
CLIE_DADOS.NUMERO,
CLIE_DADOS.ENDCOMPLMTO AS COMPLEMENTO,
CLIE_DADOS.BAIRRO,
CLIE_DADOS.CIDADE,
CLIE_DADOS.UF,
CLIE_DADOS.CEP,
CLIE_DADOS.CNPJ_CPF AS CNPJ_CNPF,
CLIE_DADOS.IE_RG,
CLIE_DADOS.FONE1 AS TELEFONE,
CLIE_DADOS.FONE2 AS CELULAR,
CLIE_DADOS.EMAIL,
CAST(CLIE_DADOS.DATA_CADASTRO AS DATE) AS CADASTRO,
CLIE_DADOS.DATA_NASCIMENTO AS NASCIMENTO,
CLIE_DADOS.OBS_MEMO AS OBSERVACOES
FROM CLIE_DADOS
WHERE CLIE_DADOS.TIPO_FORN='S'

