SELECT EST_PRODUTOS.ID_PRODUTO AS COD_FABRICANTE,
EST_PRODUTOS.NOME_PRODUTO AS DESCRICAO,
EST_GRUPOS.NOME_GRUPO AS GRUPO,
EST_PRODUTOS.COD_PRECO AS BARRAS,
CLIE_DADOS.NOME_RAZAO AS FORNECEDOR,
EST_PRODUTOS.UNM AS UND,
EST_ATUAL.EST_ATUAL AS QTD,
EST_PRODUTOS.CEST AS PERSONAL6,
TAB_ICM.TABICM_CSOSN AS ST,
EST_PRODUTOS.NCM AS COD_NCM,
EST_PRODUTOS.PRECO_CUSTO,
EST_PRODUTOS.PRECO_VENDA,
CAST(EST_PRODUTOS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
CAST(EST_PRODUTOS.DATA_REAJUSTE AS DATE) AS ALTERACAO_PRECO,
EST_PRODUTOS.CUSTO_MEDIO
FROM EST_PRODUTOS
LEFT JOIN EST_GRUPOS ON EST_PRODUTOS.GRUPOS=EST_GRUPOS.ID_GRUPOS
LEFT JOIN CLIE_DADOS ON EST_PRODUTOS.COD_FORNECEDOR=CLIE_DADOS.ID_CLIENTE
LEFT JOIN TAB_ICM ON EST_PRODUTOS.TABICM=TAB_ICM.ID_TABICM
LEFT JOIN EST_ATUAL ON EST_PRODUTOS.id_produto = EST_ATUAL.id_produto
where est_produtos.situacao <> '3' and est_produtos.unm <> 'KG'
