SELECT PRODUTOS.CODIGO,
SUB_GRUPO.NOME AS GRUPO,
PRODUTOS.BARRAS,
PRODUTOS.REF AS COD_FABRICANTE,
PRODUTOS.NOME AS DESCRICAO,
UNIDADE.NOME AS UND,
PRODUTOS.UND_FATOR AS FATOR_CONVERSAO,
PRODUTOS.OBS AS OBSERVACOES,
PRODUTOS.DATA_CAD AS DATA_CADASTRO,
ESTOQUE.SALDO_ATUAL AS QTD,
PRECOS.PRECO_VENDA,
PRECOS.PRECO_CUSTO,
STRIB.STRIB AS ST,
PRECOS.NCM AS COD_NCM,
PRECOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN SUB_GRUPO ON PRODUTOS.SUBGRUPO=SUB_GRUPO.CODIGO
LEFT JOIN UNIDADE ON PRODUTOS.UND_VENDA=UNIDADE.CODIGO
LEFT JOIN ESTOQUE ON PRODUTOS.CODIGO=ESTOQUE.CODIGO
LEFT JOIN PRECOS ON PRODUTOS.CODIGO=PRECOS.CODIGO
LEFT JOIN STRIB ON PRECOS.STRIB=STRIB.CODIGO



