SELECT
  CADGRU.GRU_DESGRU AS GRUPO,
  CADITE.ITE_CODITE AS CODIGO,
  CADITE.ITE_CODUNI AS UND,
  CADMAR.MAR_DESMAR AS FAMILIA,
  CADFOR.FOR_NOMFOR AS FORNECEDOR,
  CADITE.ITE_DESITE AS DESCRICAO,
  CADITE.ITE_REFERE AS COD_FABRICANTE,
  CADITE.ITE_CODBAR AS BARRAS,
  CADITE.ITE_CLAIPI AS COD_NCM
FROM CADITE
LEFT JOIN CADGRU ON CADITE.ITE_CODGRU = CADGRU.GRU_CODGRU
LEFT JOIN CADMAR ON CADITE.ITE_CODMAR = CADMAR.MAR_CODMAR
LEFT JOIN CADFOR ON CADITE.ITE_CODFOR = CADFOR.FOR_CODFOR
