SELECT 
       PK AS CODIGO
      ,NOME_FANTASIA AS NOME
      ,RAZAO_SOCIAL AS FANTASIA
      ,ENDERECO AS ENDERECO
      ,ENDERECO_NUM AS NUMERO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,UF AS UF
      ,CEP AS CEP
      ,FONE AS TELEFONE
      ,EMAIL AS EMAIL
      ,CNPJ_CPF AS CNPJ_CNPF
      ,IE AS IE_RG
      ,IM AS IM
      ,CONTATO_COMERCIAL AS CELULAR
      ,OBS AS OBSERVACOES
      ,LIMITE_CREDITO AS LIMITE_CREDITO
      ,COMPLEMENTO AS COMPLEMENTO
      --,DATA_CADASTRO AS CADASTRO
  FROM DATAPEIXE.dbo.CLIENTES