SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    case when FORNECEDOR.RAZAO = '' or FORNECEDOR.RAZAO is null then FORNECEDOR.NOME else FORNECEDOR.RAZAO END AS NOME,
    FORNECEDOR.NOME AS FANTASIA,
    FORNECEDOR.CONTATO AS CONTATO,
    replace (replace (replace(FORNECEDOR.CNPJ,'.','') ,'-', '') ,'/', '') AS CNPJ_CNPF,
    FORNECEDOR.INSCRICAO AS IE_RG,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.NUMERO AS NUMERO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.ESTADO AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.FONE1 AS TELEFONE,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.CELULAR AS CELULAR,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN cidade ON CIDADE.codigo = FORNECEDOR.CIDADE