SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.CODIGOBARRA AS BARRAS,
    FORNECEDOR.NOME AS FORNECEDOR,
    MARCA.NOME AS CARACTERISTICAS,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.ESTOQUE AS QTD,
    PRODUTO.ESTOQUEMIN AS QTD_IDEAL,
    PRODUTO.VALORCUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.VALORVENDA AS PRECO_VENDA,
    PRODUTO.CST AS ST,
    PRODUTO.CFOP AS CF,
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.CODIGOFORNECEDOR AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.DATACADASTRO AS DATA_CADASTRO,
    PRODUTO.DATAALTERACAO AS ALTERACAO_PRECO
FROM PRODUTO
LEFT JOIN fornecedor ON FORNECEDOR.codigo = PRODUTO.fornecedor
LEFT JOIN MARCA ON MARCA.codigo = PRODUTO.marca