SELECT
	P.COD_PESSOA AS CODIGO,
	P.NOM_PESSOA AS NOME,
	P.NOM_FANTASIA_PESSOA AS FANTASIA,
	P.NOM_BAIRRO AS BAIRRO,
	P.NUM_CEP AS CEP,
	P.NUM_CNPJ_CPF_PESSOA AS CNPJ_CNPF,
	P.NUM_IE_RG_PESSOA AS IE_RG,
	P.NUM_IM_PESSOA AS IM,
	P.NUM_TELEFONE_PESSOA AS TELEFONE,
	P.NUM_FAX_PESSOA AS FAX,
	P.NUM_CELULAR_PESSOA AS CELULAR,
	P.DES_EMAIL_PESSOA AS EMAIL,
	P.OBS_PESSOA AS OBSERVACOES,
 	P.DES_LOGRADOURO_PESSOA AS ENDERECO,
	P.NUM_ENDERECO_PESSOA AS NUMERO,
	P.DES_COMPL_ENDERECO_PESSOA AS COMPLEMENTO,
	CI.NOM_CIDADE AS CIDADE,
	E.DES_UF_ESTADO AS UF
FROM
	PESSOAS P
LEFT JOIN CIDADES CI ON CI.COD_CIDADE = P.COD_CIDADE 	
LEFT JOIN ESTADOS E ON E.COD_ESTADO = CI.COD_ESTADO	
RIGHT JOIN PESSOAS_FORNECEDORES PC ON PC.COD_PESSOA = P.COD_PESSOA
