SELECT
	--P.COD_PESSOA AS CODIGO,
	P.NOM_PESSOA AS RAZAO_SOCIAL,
	P.NUM_CNPJ_CPF_PESSOA AS CNPJ,
	P.NUM_IE_RG_PESSOA AS IE,
	P.NUM_TELEFONE_PESSOA AS TELEFONE,
	P.DES_EMAIL_PESSOA AS EMAIL,
	COALESCE(P.DES_LOGRADOURO_PESSOA, '') || ', ' || 
	COALESCE(P.NUM_ENDERECO_PESSOA, '') || ', ' || 
	COALESCE(P.NOM_BAIRRO, '') || ', ' || 
	COALESCE(P.NUM_CEP, '') || ', ' || 
	COALESCE(P.DES_COMPL_ENDERECO_PESSOA, '') AS ENDERECO,	
	CI.NOM_CIDADE AS CIDADE,
	E.DES_UF_ESTADO AS UF
FROM
	PESSOAS P
LEFT JOIN CIDADES CI ON CI.COD_CIDADE = P.COD_CIDADE 	
LEFT JOIN ESTADOS E ON E.COD_ESTADO = CI.COD_ESTADO	
RIGHT JOIN PESSOAS_TRANSPORTADORAS PC ON PC.COD_PESSOA = P.COD_PESSOA 
