SELECT
FATCLIFO.CLIB_CLIFOR AS CODIGO,
FATCLIFO.CLIB_RAZSOC AS NOME,
FATCLIFO.CLIB_FANTASIA AS FANTASIA,
FATCLIFO.CLIB_ENDER AS ENDERECO,
FATCLIFO.CLIB_CEP AS CEP,
FATCLIFO.CLIB_BAIRRO AS BAIRRO,
FATCIDAD.cid_munici AS CIDADE,
FATCIDAD.cid_uf AS UF,
FATCLIFO.CLIB_CGCPF AS CNPJ_CNPF,
FATCLIFO.CLIB_INSEST AS IE_RG,
FATCLIFO.CLIB_DDD_FONE || FATCLIFO.CLIB_FONE AS TELEFONE,
FATCLIFO.CLIB_DDD_CEL || FATCLIFO.CLIB_CELULAR AS CELULAR,
FATCLIFO.CLIB_EMAIL AS EMAIL,
FATCLIFO.CLIB_NUMERO AS NUMERO,
FATCLIFO.CLIB_COMPLEMENTO AS COMPLEMENTO
FROM FATCLIFO
LEFT JOIN FATCIDAD ON trim(FATCIDAD.cid_codigo) = FATCLIFO.clib_codcid
where FATCLIFO.clib_clifor <> 'CLIB_CLIFOR'