SELECT FORNECED.CODIGO,
FORNECED.NOME,
FORNECED.FANTASIA,
FORNECED.ENDERECO,
FORNECED.CIDADE,
FORNECED.BAIRRO,
FORNECED.UF,
FORNECED.CEP,
FORNECED.FONE1 AS TELEFONE,
FORNECED.FAX,
FORNECED.CONTATO,
FORNECED.EMAIL,
FORNECED.CNPJ AS CNPJ_CNPF,
FORNECED.INSCRICAO AS IE_RG,
FORNECED.OBSERVACAO,
FORNECED.COMPLEMENTO,
FORNECED.NUMERO
FROM FORNECED


