SELECT 
  RIGHT (CLICOD,6) as CODIGO
, CLICPFCGC as CNPJ_CNPF
, CLIRGCGF as IE_RG
, CLIDES as NOME
, CLIFAN as FANTASIA
, CLIEND as ENDERECO
, CLIBAI as BAIRRO
, CLICEP as CEP
, CLICID as CIDADE
, CLINUM as NUMERO
, CLICMP as COMPLEMENTO
, CLIEST as UF
, CLITEL as TELEFONE
, CLILIMCRE as LIMITE_CREDITO
, convert(DATE, CLIDTCAD, 103) as CADASTRO
, convert(DATE, CLIDTNAS, 103) as NASCIMENTO
, CLIPAI as PAI
, CLIMAE as MAE
, CLITEL2 as CELULAR
, CLIFAX as FAX
, CLICON as CONTATO
, CLIOBS as OBSERVACOES
, CLIEMAIL as EMAIL
, CLISEX as SEXO
FROM CLIENTE
where CLICOD <> '000000000000000'
