SELECT 
  FORCOD as CODIGO
, FORCGC as CNPJ_CNPF
, FORCGF as IE_RG
, FORDES as NOME
, FORFAN as FANTASIA
, FOREND as ENDERECO
, FORBAI as BAIRRO
, FORCID as CIDADE
, FOREST as UF
, FORTEL as TELEFONE
, FORFAX as FAX
, FORCEP as CEP
, FORNUM as NUMERO
, FORCMP as COMPLEMENTO
, FORCON as CONTATO
, FOROBS as OBSERVACOES
FROM FORNECEDOR
where FORCOD <> '0000'
