SELECT 
  C.CRCliCod AS CODIGO
, C.CRCliDes AS NOME
, C.CRCliDtaNs AS NASCIMENTO
, case when C.CRCliCGC1 = '' or C.CRCliCGC1 is null then C.CRCliCPF else C.CRCliCGC1 END AS CNPJ_CNPF
, case when C.CRCliIE1 = '' or C.CRCliIE1 is null then C.CRCliRG else C.CRCliIE1 END AS IE_RG
, C.CRCliFan AS FANTASIA
, C.CRCliEnd AS ENDERECO
, C.CRCliBai AS BAIRRO
, CONCAT (C.CMCEPCod , C.CRCliLog) AS CEP
, C2.CMUFCod AS UF
, C2.CMCEPDes AS CIDADE
, C.CRCliTel1 AS TELEFONE
, C.CRCliFax AS FAX
, C.CRCliTel3 AS CELULAR
, C.CRCliCDta AS CADASTRO
, C.CRCliLimCr AS LIMITE_CREDITO
, C.CRCliEMa AS EMAIL
, C.CRCliNroCa AS NUMERO
, C.CRCliConj AS CONJUGE
, C.CRCliSexo AS SEXO
, C.CRCliPai AS PAI
, C.CRCliMae AS MAE
, C.CRCliObs1 AS OBSERVACOES
, C.CRCliIndIE AS INDIEDEST
FROM MSINFOR.dbo.CRCli C
LEFT JOIN CMCEP c2 ON C2.CMCEPCod = C.CMCEPCod 