SELECT 
  F.CPCliCod AS CODIGO
, F.CPCliDes AS NOME
, F.CPCliFan AS FANTASIA
, F.CPCliEnd AS ENDERECO
, F.CPCliCEn AS COMPLEMENTO
, F.CPCliEMa AS EMAIL
, F.CPCliNroCa AS NUMERO
, F.CPCliObs AS OBSERVACOES
, F.CPCliBai AS BAIRRO
, F.CPCliCid AS CIDADE
, F.CPCliUf AS UF
, F.CPCliCep AS CEP
, F.CPCliTel1 AS TELEFONE
, F.CPCliFax AS FAX
, F.CPCliTel3 AS CELULAR
, case when F.CPCliCPF = '' or F.CPCliCPF is null then F.CPCliCgc else F.CPCliCPF END AS CNPJ_CNPF
, F.CPCliIE AS IE_RG
FROM MSINFOR.dbo.CPCLI F