SELECT 
  P.IDPESSOA AS CODIGO
, COALESCE (CAST (P.DATA_CADASTRO AS DATE), CURRENT_DATE) AS CADASTRO
, P.FIS_DATA_NASC AS NASCIMENTO
, P.RAZAO_SOCIAL AS NOME
, P.NOME_FANTASIA AS FANTASIA
, CASE WHEN P.FIS_CPF = '' OR P.FIS_CPF IS NULL THEN P.JUR_CNPJ ELSE P.FIS_CPF END AS CNPJ_CNPF
, CASE WHEN P.FIS_RG = '' OR P.FIS_RG IS NULL THEN P.JUR_INSC_EST ELSE P.FIS_RG END AS IE_RG
, P.FIS_FILIACAO_PAI AS PAI
, P.FIS_FILIACAO_MAE AS MAE
, P.TELEFONE1 AS TELEFONE
, P.TELEFONE2 AS CELULAR
, P.TELEFONE3 AS FAX
, P.ENDERECO
, P.NUMERO
, P.COMPLEMENTO
, P.BAIRRO
, P.CEP
, P.EMAIL
, P.OBS AS OBSERVACOES
, P.COB_ENDERECO
, P.COB_BAIRRO
, P.COB_NUMERO
, P.COB_CEP
, P.COB_UF
, P.COB_COMPLEMENTO
, P.PROF_EMPRESA AS LOCTRA
, P.PROF_PROFISSAO AS PROFISSAO
--, P.FINAN_LIMITE_CREDITO AS LIMITE_CREDITO
, P.LIMITECRE AS LIMITE_CREDITO
, P.DTULTVENDA AS ULTIMA_VENDA
, P.CODIGOBARRA AS PERSONAL1
, P.WATZAP AS PERSONAL2
, CC.DESCRICAO AS COB_CIDADE
, CI.DESCRICAO AS CIDADE 
, CI.UF 
FROM PESSOA P
LEFT JOIN CIDADE CC ON CC.IDCIDADE = P.COB_IDCIDADE
LEFT JOIN CIDADE CI ON CI.COD_MUNICIPIO = P.CMUN 
WHERE CONF_ISCLIENTE = 'S' OR CONF_ISREPRESENTANTE = 'S'
