SELECT 
  P.IDPESSOA AS CODIGO
, P.RAZAO_SOCIAL AS RAZAO_SOCIAL
, CASE WHEN P.FIS_CPF = '' OR P.FIS_CPF IS NULL THEN P.JUR_CNPJ ELSE P.FIS_CPF END AS CNPJ
, CASE WHEN P.FIS_RG = '' OR P.FIS_RG IS NULL THEN P.JUR_INSC_EST ELSE P.FIS_RG END AS IE
, P.TELEFONE1 AS TELEFONE
, P.ENDERECO ||', '|| P.NUMERO ||', '|| P.BAIRRO ||', CEP: '|| P.CEP || ', COMPLEMENTO: '|| P.COMPLEMENTO AS ENDERECO
, P.EMAIL
, CI.DESCRICAO AS CIDADE 
, CI.UF 
FROM PESSOA P
LEFT JOIN CIDADE CI ON CI.COD_MUNICIPIO = P.CMUN 
WHERE CONF_ISTRANSPORTADORA = 'S'
