SELECT 
  SUBSTRING (CODIGO FROM 3 FOR 6) AS CODIGO
, RAZ_SOC AS NOME
, NOM_FANT AS FANTASIA
, CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
, CASE WHEN IDENT = '' OR IDENT IS NULL THEN INC_EST ELSE IDENT END AS IE_RG
, ENDERECO
, NUMERO
, ENDERECO_COMPL ||' - '||PONTO_REF AS COMPLEMENTO
, BAIRRO
, NOM_CIDADE AS CIDADE
, ESTADO AS UF
, CEP
, TELEFONE
, CELULAR
, FAX
, EMAIL
, coalesce(DATA_CAD, current_date) AS CADASTRO
, DATA_NASC AS NASCIMENTO
, CONTATO
, LIM_CRED AS LIMITE_CREDITO
, OBS_CLI AS OBSERVACOES
, CEP_COB AS COB_CEP
, END_COB AS COB_ENDERECO
, BAIRRO_COB AS COB_BAIRRO
, NOM_CIDADE_COB AS COB_CIDADE
, EST_COB AS COB_UF
, ULT_COMPRA AS ULTIMA_VENDA
FROM CAD01
WHERE TIPO='C' 