SELECT 
  P1.CODPROD AS CODIGO
, P1.PRODUTO AS DESCRICAO
, P1.COD_BARRA AS BARRAS
, P1.EST_MIN AS QTD_IDEAL
, P1.PRECO_CUS AS PRECO_CUSTO
--, P1.PRECO_VENDA
, P1.PRECO_ATACADO
, P1.PRECO_DOLAR
, P1.PR_VENDA_MEDIO AS PERSONAL1
, P1.MARKUP AS MARGEM_LUCRO
, P1.COMISSAO
--, P1.SIT_TRIB AS ELO
--, P1.ICMS AS ELO
, LEFT (REPLACE (P1.ALIQ_CUPOM,',',''),3) AS ELO
--, P1.OBS AS OBSERVACOES
, P1.OBS_PROD AS OBSERVACOES
, P1.TIPO_PROD AS PERSONAL2
, P1.CODFOR AS COD_FABRICANTE
, P1.COD_FAB AS PERSONAL4
, P1.PESO_BRU AS PESO
--, P1.UNIDADE AS UND
, P1.UNID_FIM AS UND
, COALESCE(P1.DATA_CAD, CURRENT_DATE) AS DATA_CADASTRO
--, P1.QTD
, CASE P1.DISPONIVEL WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P1.VALIDADE AS VALIDADE_DIAS
, P1.CLAS_FISCAL AS COD_NCM
, P1.MARCA AS PERSONAL5
, P1.ULT_VENDA AS ULTIMA_VENDA
, P1.CEST AS PERSONAL6
, P1.ORIGEM AS OST
, P1.IPI AS ALIQ_IPI_VENDA
, P1.IPI_ENT AS ALIQ_IPI
, P1.PIS_CST AS PIS_CODIGO
, P1.COFINS_CST AS COFINS_CODIGO
, P1.PIS_ALIQ AS PIS_ALIQ_NOR
, P1.COFINS_ALIQ AS COFINS_ALIQ_NOR
, P1.PIS_CST_ENT AS PISE_CODIGO
, P1.COFINS_CST_ENT AS COFINSE_CODIGO
--, P1.PIS, P1.PIS_NAT_OP, P1.PIS_CST_CFOP_OP_E, P1.PIS_CST_OP_E, P1.COFINS_CST_CFOP_OP_E, P1.COFINS_CST_OP_E, P1.PIS_CST_CFOP_OP_S, P1.PIS_CST_OP_S, P1.COFINS_CST_CFOP_OP_S, P1.COFINS_CST_OP_S
, P1.COR
, P1.GRUPO
--, SUB_GRUPO
, P2.PRECO_VEN AS PRECO_VENDA
, P2.QTDE AS QTD
, P2.PRECO_CUS_MED AS CUSTO_MEDIO
FROM PROD01 P1
LEFT JOIN PROD02 P2 ON P2.CODPROD = P1.CODPROD







