SELECT 
  C0.IDCLIENTE AS CODIGO
, CASE WHEN C0.CPF = '' OR C0.CPF IS NULL THEN C0.CNPJ ELSE C0.CPF END AS CNPJ_CNPF
, CASE WHEN C0.RG = '' OR C0.RG IS NULL THEN C0.CEI ELSE C0.RG END AS IE_RG
, C0.RAZAO AS NOME
, C0.FANTASIA
, C0.ENDERECO
, C0.NUMERO
, C0.COMPLEMENTO
, C0.BAIRRO
, C0.CEP
, C0.FONE AS TELEFONE
, C0.FAX
, C0.CELULAR
, C0.DTCAD AS CADASTRO
, C0.CELULAR2 AS PERSONAL1
, C0.CELULAR3 AS PERSONAL2
, C0.WHATSAPP AS PERSONAL3
, CASE C0.TPCLICONTRIBUINTE 
	WHEN '1' THEN 'C'
	WHEN '2' THEN 'I'
	WHEN '9' THEN 'N'
  END AS SITUACAO
, C1.CLLIMCRED AS LIMITE_CREDITO
, C1.CLDTULTIMACOMP AS ULTIMA_VENDA
, C1.INSCMUNICIPAL AS IM
, C1.OBSERVACAO AS OBSERVACOES
, CI.CIDADE 
, CI.UF 
FROM TBLCDSCLI0 C0
LEFT JOIN TBLCDSCLI1 C1 ON C1.IDCLIENTE = C0.IDCLIENTE  
LEFT JOIN TBLCDSCID0 CI ON CI.IDCIDADE = C0.IDCIDADECLI 
WHERE CLIFOR = 'C'