SELECT 
  I0.IDITEM AS CODIGO
, I0.REFERENCIA AS COD_FABRICANTE
, CASE I0.STATUS WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, I0.NOMEPRO AS DESCRICAO
, I0.MARCA AS PERSONAL1
, I0.UNDCOMP1 AS UND_COMPRA
, I0.UNDVEND1 AS UND
, I0.PESOBRU AS PESO
, I0.QTDMIN AS QTD_IDEAL
, I0.COMISSAO
, I0.DTCAD AS DATA_CADASTRO
, I0.FATORCONV AS FAT_CONV
--, I0.NOMEOBS AS OBSERVACOES
, I1.OBS AS OBSERVACOES
, I1.ULTCOMPRA AS ULTIMA_COMPRA
, I1.ULTVENDA AS ULTIMA_VENDA
, I1.CSTIPICOM AS IPI_CODIGO
, I1.CSTIPIVEN AS IPI_CODIGO_VENDA
, I2.CUSTO AS PRECO_CUSTO
, I3.LUCRO AS MARGEM_LUCRO
, I3.IDNCM AS COD_NCM
, I3.CEST AS PERSONAL6
--, I4.CST AS ST
, I4.CSOSN AS ST
, I5.CODBARRA AS BARRAS
, I0.IPIVEN AS ALIQ_IPI_VENDA
, I0.IPICOM AS ALIQ_IPI
, M.MARCA AS FAMILIA
, G.SECAO AS GRUPO
, TP.PRECO AS PRECO_VENDA
, QT.SALDO AS QTD
FROM TBLCDSITE0 I0
LEFT JOIN TBLCDSITE1 I1 ON I1.IDITEM = I0.IDITEM  
LEFT JOIN TBLCDSEMP0 EM ON EM.IDEMPRESA = I0.IDEMPRESA AND I0.IDEMPRESA = 1
LEFT JOIN TBLCDSITE2 I2 ON I2.IDITEM  = I0.IDITEM AND I2.IDEMPRESA = 1
LEFT JOIN TBLCDSITE3 I3 ON I3.IDITEM  = I0.IDITEM
LEFT JOIN TBLCDSITE4 I4 ON I4.IDITEM  = I0.IDITEM AND I4.UF = EM.UFNFE AND I4.ENTSAI = 'S'
LEFT JOIN TBLCDSITE5 I5 ON I5.IDMESTRE = I0.IDITEM 
LEFT JOIN TBLCDSMAR0 M ON M.IDMARCA = I0.IDMARCA
LEFT JOIN TBLCDSSEC0 G ON G.IDCHAVEREG = I0.IDCHAVEREG 
LEFT JOIN TBLCDSPRE1 TP ON TP.IDITEM = I0.IDITEM  
LEFT JOIN TBLSDOITE1 QT ON QT.IDITEM = I0.IDITEM AND QT.IDEMPRESA = 1