SELECT 
CLIENTES.[CÓDIGO] AS CODIGO,
CLIENTES.NOME,
CLIENTES.APELIDO AS FANTASIA,
CAST(CLIENTES.[DATADAINCLUSÃO] AS DATE) AS CADASTRO,
CAST(CLIENTES.DATADENASCIMENTO AS DATE) AS NASCIMENTO,
CLIENTES.CEP,
CLIENTES.[ENDEREÇO] AS ENDERECO,
CLIENTES.[NÚMERO] AS NUMERO,
CONCAT(CLIENTES.COMPLEMENTO,' - ',CLIENTES.REFERÊNCIA) AS COMPLEMENTO,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.UF,
CLIENTES.TELEFONES AS TELEFONE,
CLIENTES.CELULARES AS CELULAR,
CLIENTES.FAX,
CLIENTES.EMAIL,
CASE WHEN CLIENTES.CPF = '' OR CLIENTES.CPF IS NULL THEN CLIENTES.CNPJ ELSE CLIENTES.CPF END AS CNPJ_CNPF,
CASE WHEN CLIENTES.RG = '' OR CLIENTES.RG IS NULL THEN CLIENTES.IE ELSE CLIENTES.RG END AS IE_RG,
CLIENTES.CONTATO,
CLIENTES.[OBSERVAÇÕES] AS OBSERVACOES
FROM GERENCIAL.DBO.CLIENTES
WHERE CLIENTES.[CÓDIGO]<>0
