SELECT 
FORNECEDORES.[CÓDIGO] AS CODIGO,
FORNECEDORES.NOME,
FORNECEDORES.APELIDO AS FANTASIA,
FORNECEDORES.CEP,
FORNECEDORES.[ENDEREÇO] AS ENDERECO,
FORNECEDORES.[NÚMERO] AS NUMERO,
FORNECEDORES.COMPLEMENTO,
FORNECEDORES.BAIRRO,
FORNECEDORES.CIDADE,
FORNECEDORES.UF,
FORNECEDORES.TELEFONES AS TELEFONE,
FORNECEDORES.CELULARES AS CELULAR,
FORNECEDORES.FAX,
FORNECEDORES.EMAIL,
FORNECEDORES.CNPJ AS CNPJ_CNPF,
FORNECEDORES.IE AS IE_RG,
FORNECEDORES.CONTATO,
FORNECEDORES.[OBSERVAÇÕES] AS OBSERVACOES 
FROM GERENCIAL.DBO.FORNECEDORES
WHERE FORNECEDORES.[CÓDIGO]<>0
