SELECT   
    CODIGO,
    CODBARRAS AS BARRAS,
    CODBARRASCAIXA AS CARACTERISTICAS,
    DESCRICAO AS DESCRICAO,
    REFORIGINAL AS COD_FABRICANTE,
    UNIDADE AS UND,
    GRUPO AS GRUPO,
    FORNECEDOR AS FORNECEDOR,
    VLRCUSTO AS PRECO_CUSTO,
    VLRVENDA AS PRECO_VENDA,
    ESTOQUE AS QTD,
    CODIGONCM AS COD_NCM,
    VLRATACADO AS PRECO_ATACADO,
    CEST AS PERSONAL6,
    CSOSN AS ST
FROM ESTOQUE
