SELECT 
       CXA_FORNECEDOR.FOR_CGCCPF AS CNPJ_CNPF
      ,CXA_FORNECEDOR.FOR_NOME AS NOME
      ,CXA_FORNECEDOR.FOR_NOMEFATASIA AS FANTASIA
      ,CXA_FORNECEDOR.FOR_NUMTELFIXO AS TELEFONE
      ,CXA_FORNECEDOR.FOR_NUMFAX AS FAX
      ,CXA_FORNECEDOR.FOR_NUMCELULAR AS CELULAR
      ,CXA_FORNECEDOR.FOR_CODINSCRICAO AS IE_RG
      ,CXA_FORNECEDOR.FOR_DATACADASTRO AS CADASTRO
      ,CXA_FORNECEDOR.FOR_EMAIL AS EMAIL
      ,BAI_BAIRRO.BAI_NMBAIRRO AS BAIRRO
      ,LOC_LOCALIDADE.LOC_NMLOCALIDADE AS CIDADE
      ,LOC_LOCALIDADE.UNF_SGUNIDADE AS UF
      ,CXA_FORNECEDOR.LOC_CDCEP AS CEP
      ,CXA_FORNECEDOR.LOG_NMLOGRADOURO AS ENDERECO
      ,CXA_FORNECEDOR.ENC_NRLOGRADOURO AS NUMERO
      ,CXA_FORNECEDOR.ENC_DSCOMPLEMENTO AS COMPLEMENTO
      ,CXA_FORNECEDOR.FOR_NR_INSCMUNICIPAL AS IM
  FROM DB_JAMSOFT.dbo.CXA_FORNECEDOR
  LEFT JOIN BAI_BAIRRO ON BAI_BAIRRO.BAI_CDBAIRRO = CXA_FORNECEDOR.BAI_CDBAIRRO 
  LEFT JOIN LOC_LOCALIDADE ON LOC_LOCALIDADE.LOC_CDLOCALIDADE = CXA_FORNECEDOR.LOC_CDLOCALIDADE