SELECT 
       CXA_ESTOQUE.EST_REFPRO AS CODIGO
      ,CXA_ESTOQUE.EST_EMBPRO AS UND
      ,CXA_ESTOQUE.EST_DESPRO AS DESCRICAO
      ,CXA_ESTOQUE.EST_PCOVEN AS PRECO_VENDA
      ,CXA_ESTOQUE.EST_PCOCUSTO AS PRECO_CUSTO
      ,CXA_ESTOQUE.EST_SALDO AS QTD
      ,CXA_ESTOQUE.EST_SALDOINICIAL AS QTD_IDEAL
      ,CXA_ESTOQUE.EST_PESOLIQUIDO AS PESO
      ,CXA_GRUPO.GRP_DSGRUPO AS GRUPO
      ,NATUREZA.CD_CSTSIMPLES AS ST
      ,CXA_ESTOQUE.EST_CDFABRICANTE AS COD_FABRICANTE
      ,CXA_ESTOQUE.EST_MLUCRO AS MARGEM_LUCRO
      ,CXA_ESTOQUE.cd_ncm AS COD_NCM
      ,CXA_FORNECEDOR.FOR_NOME AS FORNECEDOR
      ,CXA_ESTOQUE.EST_CDBARRA AS BARRAS
      ,CXA_ESTOQUE.TX_OBSERVACAO AS OBSERVACOES
      ,CXA_ESTOQUE.CD_CEST AS PERSONAL6
      ,CAST (CXA_ESTOQUE.EST_DT_CADASTRO AS DATE) AS DATA_CADASTRO
  FROM DB_JAMSOFT.dbo.CXA_ESTOQUE
  LEFT JOIN CXA_FORNECEDOR ON CXA_FORNECEDOR.FOR_CGCCPF = CXA_ESTOQUE.FOR_CGCCPF
  LEFT JOIN CXA_GRUPO ON CXA_GRUPO.GRP_CDGRUPO = CXA_ESTOQUE.GRP_CDGRUPO
  LEFT JOIN NATUREZA ON NATUREZA.CD_NATUREZA = CXA_ESTOQUE.CD_NATUREZA