SELECT
    FORNECEDORES.ID AS CODIGO,
    FORNECEDORES.RAZAO_SOCIAL AS NOME,
    FORNECEDORES.NOME_FANTASIA AS FANTASIA,
    case when FORNECEDORES.CNPJ = '' or FORNECEDORES.CNPJ is null then FORNECEDORES.CPF else FORNECEDORES.CNPJ END AS CNPJ_CNPF,
    FORNECEDORES.INSC_ESTADUAL AS IE_RG,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.END_NUM AS NUMERO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.UF AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.DDD ||''||FORNECEDORES.TELEFONE1 AS TELEFONE,
    FORNECEDORES.DDD_CEL ||''|| FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.OBSERVACOES AS OBSERVACOES
FROM FORNECEDORES
