SELECT
    PRODUTOS.CODIGO_INTERNO AS CODIGO, 
    PRODUTOS.CODIGO_BARRAS AS BARRAS,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.DESCRICAO_RESUMIDA AS CARACTERISTICAS,
    GRUPOS.s_descricao AS GRUPO,
    FAMILIAS.s_descricao AS FAMILIA,
    PRODUTOS.UNIDADE AS UND, 
    substring (PRODUTOS.ST from 1 for 1) AS OST,
    substring (PRODUTOS.ST from 2 for 3) AS ST,
    PRODUTOS.CUSTO_MEDIO  AS CUSTO_MEDIO,
    PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VENDA1 AS PRECO_VENDA,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.ESTOQUE_MIN AS QTD_IDEAL,
    PRODUTOS.ESTOQUE_ATUAL AS QTD,
    PRODUTOS.ULT_VENDA AS ULTIMA_VENDA,
    PRODUTOS.DATA_INCLUSAO AS DATA_CADASTRO,
    PRODUTOS.ULT_COMPRA AS ULTIMA_COMPRA,
    PRODUTOS.ULT_ALT_PRECO AS ALTERACAO_PRECO,
    PRODUTOS.S_OBS_PROD AS OBSERVACOES,
    PRODUTOS.S_NCM AS COD_NCM,
    PRODUTOS.S_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN grupos ON GRUPOS.id = PRODUTOS.GRUPO
LEFT JOIN familias ON FAMILIAS.id = PRODUTOS.FAMILIA
