SELECT CLIENTE.ID AS CODIGO,
CLIENTE.NOMEFANTASIA AS NOME,
CLIENTE.RAZAOSOCIAL AS FANTASIA,
CASE WHEN CLIENTE.CPF IS NULL THEN CLIENTE.CNPJ
ELSE CLIENTE.CPF END AS CNPJ_CNPF,
CASE WHEN CLIENTE.RG IS NULL THEN CLIENTE.INSCRICAO_ESTADUAL
ELSE CLIENTE.RG END AS IE_RG,
CLIENTE.FONE1 AS TELEFONE,
CLIENTE.FAX,
CLIENTE.CELULAR,
CLIENTE.EMAIL1 AS EMAIL,
CLIENTE.ENDERECO1 AS ENDERECO,
CLIENTE.BAIRRO1 AS BAIRRO,
CLIENTE.CEP1 AS CEP,
MUNICIPIO.NOME AS CIDADE,
ESTADO.SIGLA AS UF,
CLIENTE.ENDNUMERO1 AS NUMERO,
CLIENTE.COMPLEMENTO1 AS COMPLEMENTO
FROM CLIENTE
LEFT JOIN MUNICIPIO ON CLIENTE.ID_MUNICIPIO1=MUNICIPIO.ID
LEFT JOIN ESTADO ON CLIENTE.ID_ESTADO1=ESTADO.ID
WHERE CLIENTE.TIPO=1

