SELECT PRODUTO.ID AS CODIGO,
PRODUTO.DESCRICAO,
CATPRODUTO.DESCRICAO AS GRUPO,
UNIDADE.SIGLA AS UND,
SIT_TRIBUTARIA.CODIGO AS ST,
PRODUTO.CODIGO AS COD_FABRICANTE,
PRODUTO.CUSTO AS PRECO_CUSTO,
PRODUTO.OBSERVACOES,
PRODUTO.CODBARRA AS BARRAS,
PRODUTO.PRECOVENDA AS PRECO_VENDA,
PRODUTO.CODIGO_NCM AS COD_NCM,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN CATPRODUTO ON PRODUTO.ID_CATEGORIA=CATPRODUTO.ID
LEFT JOIN UNIDADE ON PRODUTO.ID_UNIDADE_VENDA=UNIDADE.ID
LEFT JOIN SIT_TRIBUTARIA ON PRODUTO.ID_CSOSN=SIT_TRIBUTARIA.ID
