SELECT 
       ITENS.ITEM AS COD_FABRICANTE
      ,ITENS.DESCRICAO AS DESCRICAO
      ,ITENS.CUSTO_MEDIO AS CUSTO_MEDIO
      ,ITENS.PRECO AS PRECO_VENDA
      ,ITENS.QTD_MINIMA AS QTD_IDEAL
      ,ITENS_FICHA.QTD AS QTD
      ,ITENS.GRUPO AS GRUPO
      ,ITENS.UNIDADE_VENDA AS UND
      ,ITENS.NCM AS COD_NCM
      ,ITENS.CSOSN AS ST
      ,ITENS.CEST AS PETSONAL6
  FROM DiegoAndinoReta.dbo.ITENS
left join DiegoAndinoReta.dbo.ITENS_FICHA on ITENS_FICHA.ITEM = ITENS.ITEM