SELECT
PRODUTO.ID AS CODIGO,
PRODUTO_SUBGRUPO.DESCRICAO AS GRUPO,
max (PRODUTO_CODIGO_BARRA.CODIGO_BARRA) AS BARRAS,
PRODUTO_UNIDADE.SIGLA AS UND,
PRODUTO.DESCRICAO,
PRODUTO.OBSERVACAO AS OBSERVACOES,
CLASSIFICACAO_FISCAL.CLASSIFICACAO AS COD_NCM,
PRODUTO.DATA_CADASTRO,
PRODUTO.REFERENCIA AS COD_FABRICANTE,
PRODUTO.CUSTO AS PRECO_CUSTO,
PRODUTO.CUSTO_MEDIO,
MIN(PRODUTO_FISCAL.ORIGEM_MERCADORIA) AS OST,
MIN (PRODUTO_FISCAL.ICMS_CST_INTERNO) AS ST,
MAX (PRODUTO_PRECO.VALOR) AS PRECO_VENDA,
CEST.CODIGO AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_SUBGRUPO ON PRODUTO.FK_PRODUTO_SUBGRUPO=PRODUTO_SUBGRUPO.ID
LEFT JOIN PRODUTO_CODIGO_BARRA ON PRODUTO.ID=PRODUTO_CODIGO_BARRA.FK_PRODUTO
LEFT JOIN PRODUTO_UNIDADE ON PRODUTO.FK_PRODUTO_UNIDADE=PRODUTO_UNIDADE.ID
LEFT JOIN CLASSIFICACAO_FISCAL ON PRODUTO.FK_CLASSIFICACAO_FISCAL=CLASSIFICACAO_FISCAL.ID
LEFT JOIN PRODUTO_FISCAL ON PRODUTO.ID=PRODUTO_FISCAL.FK_PRODUTO
LEFT JOIN PRODUTO_PRECO ON PRODUTO.ID=PRODUTO_PRECO.FK_PRODUTO
LEFT JOIN CEST ON PRODUTO.FK_CEST=CEST.ID
GROUP BY 1,2,4,5,6,7,8,9,10,11,15


