  SELECT
    CLIENTE.ID CODIGO,
    CLIENTE.NOME,
    CLIENTE.FANTASIA,
    CLIENTE.EMAIL,
    CLIENTE.CPF_CNPJ AS CNPJ_CNPF,
    CLIENTE.RG||INSCRICAO_ESTADUAL AS IE_RG,
    CLIENTE.DATA_CADASTRO AS CADASTRO,
    CLIENTE.DATA_NASCIMENTO AS NASCIMENTO,
    CLIENTE.LOGRADOURO AS ENDERECO,
    CLIENTE.NUMERO,
    CLIENTE.COMPLEMENTO,
    CLIENTE.CEP,
    CLIENTE.BAIRRO,
    CLIENTE.CIDADE,
    CLIENTE.UF,
    CLIENTE.FONE1 AS TELEFONE,
    CLIENTE.CELULAR,
    CLIENTE.CONTATO
from cliente
ORDER BY ID
