   SELECT
    PRODUTO.ID AS CODIGO,
    UNIDADE_PRODUTO.nome AS UND,
    PRODUTO.GTIN AS BARRAS,
    PRODUTO.CODIGO_INTERNO AS CARACTERISTICAS,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO_MARCA.DESCRICAO AS FAMILIA, --- É A "MARCA" DOS ITENS SOLICITADO PARA COLOCAR NOS "FAMILIAS"
    GRUPO_PRODUTO.NOME AS GRUPO,
    --SUBGRUPO_PRODUTO.NOME AS FAMILIA,
    PRODUTO.VALOR_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_VENDA AS PRECO_VENDA,
    PRODUTO.QTD_ESTOQUE AS QTD,
    PRODUTO.ESTOQUE_MIN AS QTD_IDEAL,
    PRODUTO.NCM AS COD_NCM,
    SUBSTRING (TRIICM.DESCRICAO FROM 1 FOR 1) AS ST,
    --PRODUTO.CST AS ST,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.VALOR_ATACADO AS PRECO_ATACADO,
    PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
    MAX (TABELA_CEST.CEST) AS PERSONAL6
    --PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN UNIDADE_PRODUTO ON PRODUTO.id_unidade_produto = UNIDADE_PRODUTO.id
LEFT JOIN GRUPO_PRODUTO ON GRUPO_PRODUTO.ID = PRODUTO.ID_GRUPO_PRODUTO
LEFT JOIN SUBGRUPO_PRODUTO ON SUBGRUPO_PRODUTO.ID = PRODUTO.ID_SUBGRUPO_PRODUTO
LEFT JOIN PRODUTO_MARCA ON PRODUTO_MARCA.ID = PRODUTO.ID_PRODUTO_MARCA
LEFT JOIN TRIBUTACAO_ICMS TRIICM ON PRODUTO.ID_TRIBUTACAO_ICMS = TRIICM.ID
LEFT JOIN TABELA_CEST ON TABELA_CEST.ncm = PRODUTO.NCM
WHERE UNIDADE_PRODUTO.nome <> ''
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
