SELECT
	CLCODIGO AS PERSONAL1,
	CLRAZSOC AS NOME,
	CLNOMFAN AS FANTASIA,
	CLCGCCPF AS CNPJ_CNPF,
	CLINSEST AS IE_RG,	
	CLFTENDE AS ENDERECO,
	CLFTBAIR AS BAIRRO,
	CLFTCIDA AS CIDADE,
	CLFTESTA AS UF,
	CLFTNCEP AS CEP,
	CLOBSERV AS OBSERVACOES,
	CLTELEFO AS TELEFONE,
	CLENDELE AS EMAIL,
	CLNUMFAX AS FAX,
	CLINSMUN AS IM,
	CLLIMCRE AS LIMITE_CREDITO,
	CAST(CLDATUSU AS DATE) AS CADASTRO,
	CLFTNUME AS NUMERO
FROM
	CREA01
