SELECT
	SCEA01.PRREFERE AS COD_FABRICANTE,
	SCEA01.PRCGRUPO AS GRUPO,
	SCEA01.PRSUBGRP AS FAMILIA,
	SCEA01.PRDESCRI AS DESCRICAO,
	SCEA01.PRUNIDAD AS UND,
	SCEA01.PRPESBRU AS PESO,
	SCEA01.PRPRCUST AS PRECO_CUSTO,
	SCEA01.PRCODBAR AS BARRAS,
	SCEA01.PRMARGEM AS MARGEM_LUCRO,
	SCEA01.PRUNDCPR AS UND_COMPRA,
	SCEA01.PRCLASSI AS COD_NCM,
	SCEA01.PRALQIPI AS ALIQ_IPI_VENDA,
	SCEA01.PRPOSTRI AS PERSONAL1,
	SCEA01.PROBSERV AS OBSERVACOES,
	CAST (SCEA01.PRULTVDA AS DATE) AS ULTIMA_VENDA,
	CAST (SCEA01.PRULTCPR AS DATE) AS ULTIMA_COMPRA,
	SCEA01.PRCDCEST AS PERSONAL6,
	SCEA07.EEESTATU AS QTD,
	SCEA07.EEPBRTB1 AS PRECO_VENDA,
	SCEA07.EET2PVD1 AS PERSONAL2
FROM
	SCEA01
LEFT JOIN SCEA07 ON SCEA07.EEREFERE = SCEA01.PRREFERE  	
WHERE SCEA07.EECODEMP = 'MEC'