SELECT
    CONTAS_RECEBIDA.ID AS DOCUMENTO,
    CONTAS_RECEBIDA.DATA_INC AS EMISSAO,
    CONTAS_RECEBIDA.DATAVENC AS VENCIMENTO,
    CONTAS_RECEBIDA.ID_CLIENTE AS CODIGO,
    CLIENTES.NOME AS NOM_CLIENTE,
    CONTAS_RECEBIDA.VALOR_PARC AS VALOR_DUP,
    CONTAS_RECEBIDA.NUM_DOC AS HISTORICO,
    --CONTAS_RECEBIDA.NUM_NOTAS AS HISTORICO,
    CONTAS_RECEBIDA.NUM_PARCE AS NUM_PARCELA,
    CONTAS_RECEBIDA.VLRJUROS AS VALOR_JUR,
    CONTAS_RECEBIDA.DATARECEBIDO AS RECEBIMENTO ,
    CONTAS_RECEBIDA.VLRDESCONTO AS VALOR_DES,
    CONTAS_RECEBIDA.VLRRECEBIDO AS VALOR_REC,
'' AS CNPJ
FROM CONTAS_RECEBIDA
LEFT JOIN CLIENTES ON CONTAS_RECEBIDA.id_cliente = CLIENTES.ID
