SELECT
  PRODUTOS.PRODUTO AS CODIGO,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  UNIDADES.DESCRICAO AS UND,
  GRUPOS.DESCRICAO AS GRUPO,
  SUBGRUPOS.DESCRICAO AS FAMILIA,
  PRODUTOS.CUSTO AS PRECO_CUSTO,
  PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTOS.VENDA AS PRECO_VENDA,
  PRODUTOS.LUCRO AS MARGEM_LUCRO,
  TRIBUTACOES.CSOSN AS ST,
  PRODUTOS.SALDO AS QTD,
  PRODUTOS.OBS AS OBSERVACOES,
  FORNECEDORES.RAZAO AS FORNECEDOR,
  PRODUTOS.EAN AS BARRAS,
  PRODUTOS.COD_FABRICANTE AS COD_FABRICANTE,
  CAST (PRODUTOS.ULTIMA_ALTERACAO AS DATE) AS ALTERACAO_PRECO,
  PRODUTOS.DESCRICAO_RESUMIDA AS CARACTERISTICAS,
  PRODUTOS.ULT_DATA_ENTRADA AS ULTIMA_COMPRA,
  PRODUTOS.DT_CADASTRO AS DATA_CADASTRO,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.VENDA_ATAC AS PRECO_ATACADO,
  PRODUTOS.EST_MINIMO AS QTD_IDEAL,
  PRODUTOS.PESO AS PESO,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN TRIBUTACOES ON TRIBUTACOES.TRIBUTACAO = PRODUTOS.TRIBUTACAO
LEFT JOIN GRUPOS ON GRUPOS.GRUPO = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.SUBGRUPO = PRODUTOS.SUBGRUPO
LEFT JOIN UNIDADES ON UNIDADES.UNIDADE = PRODUTOS.UNIDADE
LEFT JOIN FORNECEDORES ON FORNECEDORES.FORNECEDOR = PRODUTOS.FORNECEDOR
