SELECT
    GIL_PRO.PR_COD_PRO        AS CODIGO,
    GIL_PRO.PR_COD_ORI        AS COD_FABRICANTE,
    GIL_CAD.CD_NOME           AS FORNECEDOR,
    GIL_PRO.PR_COD_BAR        AS BARRAS,
    GIL_PRO.PR_NOME           AS DESCRICAO,
    GIL_PRO.PR_UNIDADE        AS UND,
    GIL_PRO.PR_PESO           AS PESO,
    GIL_PRO.PR_ESTOQUE_MINIMO AS QTD_IDEAL,
    GIL_PRO_SAL.PRS_SALDO_ATUAL AS QTD,
    GIL_PRO.PR_CCUSTO         AS PRECO_CUSTO,
    GIL_PRO.PR_PRECO1         AS PRECO_VENDA,
    GIL_PRO.PR_PRECO5         AS PRECO_ATACADO,
    
    CASE 
        WHEN GIL_PRO.PR_TRIBUTACAO = '1800' THEN '102'
        WHEN GIL_PRO.PR_TRIBUTACAO = '9900' THEN '500'
        WHEN GIL_PRO.PR_TRIBUTACAO IS NULL OR GIL_PRO.PR_TRIBUTACAO = '0' THEN '101'
        ELSE GIL_PRO.PR_ST
    END                       AS ST,
    
    GIL_PRO.PR_NCM            AS COD_NCM,
    GIL_PRO.PR_CEST           AS PERSONAL6

FROM 
    GIL_PRO
LEFT JOIN 
    GIL_PRO_SAL ON GIL_PRO_SAL.PRS_COD_PRO = GIL_PRO.PR_COD_PRO
LEFT JOIN 
    GIL_CAD ON GIL_CAD.CD_COD_CAD = GIL_PRO.PR_COD_FOR
WHERE 
    GIL_PRO_SAL.PRS_COD_EMP = '1' 
    AND GIL_PRO_SAL.PRS_SS = '1';
