SELECT 
  P.ID_PRODUTO as CODIGO
, P.DESCRICAO
, gf.NOME as FORNECEDOR 
, P.QUANTIDADE as QTD
, pe.ABREVIATURA as UND
, uc.ABREVIATURA as UND_COMPRA
, pg.DESCRICAO as GRUPO
, pc.DESCRICAO as CARACTERISTICAS
, P.MARGEM_LUCRO
, P.CODIGO_BARRA as BARRAS
, P.PRECO_CUSTO_BRUTO as PRECO_CUSTO 
, P.PRECO_VENDA
, P.PRECO_VENDA_ATACADO as PRECO_ATACADO
, P.OBSERVACAO as OBSERVACOES
, P.PERCENTUAL_COMISSAO as COMISSAO
, REPLACE(P.NCM, '.', '') as COD_NCM
, P.CST as ST
, P.ICMS_OUT as ELO
, P.PIS as PIS_ALIQ_NOR
, P.CONFINS as COFINS_ALIQ_NOR
, P.CST_PIS as PIS_CODIGO
, P.CST_COFINS as COFINS_CODIGO
, P.CST_IPI as IPI_CODIGO_VENDA
, P.PESO_BRUTO as PESO
, P.DATA_ULTIMA_VENDA as ULTIMA_VENDA
, P.DATA_ULTIMA_COMPRA as ULTIMA_COMPRA
, P.DATA_INCLUSAO as DATA_CADASTRO
, case P.STATUS
		when 'A' THEN 'Ativo'
		when 'I' THEN 'Inativo'
		END as SITUACAO
FROM GEN_PRODUTOS P
LEFT JOIN GEN_FORNECEDOR gf ON gf.ID_FORNECEDOR = P.ID_FORNECEDOR 
LEFT JOIN PROD_EMBALAGEM pe ON pe.ID_EMBALAGEM  = P.ID_EMBALAGEM
LEFT JOIN PROD_EMBALAGEM uc ON uc.ID_EMBALAGEM = P.ID_EMBALAGEM_COMPRA  
LEFT JOIN PROD_GONDOLAS pg ON pg.ID_GONDOLA = P.ID_GONDOLA 
LEFT JOIN PROD_CARACTERISTICAS pc ON pc.ID_CARACTERISTICA = P.ID_CARACTERISTICA 
