SELECT
    TBCLIENTE.NOME AS NOME,
    TBCLIENTE.ENDERECO AS ENDERECO,
    TBBAIRRO.nome AS BAIRRO,
    TBCLIENTE.CIDADE AS CIDADE,
    TBCLIENTE.EMAIL AS EMAIL,
    TBCLIENTE.REFERENCIA AS COMPLEMENTO,
    TBCLIENTE.OBS AS OBSERVACOES,
    TBCLIENTE.CEP AS CEP,
    TBCLIENTE.CPF AS CNPJ_CNPF,
    TBCLIENTE.FONE AS TELEFONE,
    TBCLIENTE.FONE2 AS CELULAR,
    TBCLIENTE.FONE3 AS FAX,
    TBCLIENTE.NUMERO AS NUMERO
FROM TBCLIENTE
LEFT JOIN tbbairro ON TBBAIRRO.COD = TBCLIENTE.BAIRRO