SELECT
  TBPROD.CODIGO AS CODIGO,
  TBPROD.NOME AS DESCRICAO,
  TBPROD.PRECO AS PRECO_VENDA,
  TBPROD.PRECO_CUSTO AS PRECO_CUSTO,
  TBCATEG.NOME AS GRUPO,
  TBPROD.UND AS UND,
  TBPROD.EAN AS BARRAS,
  TBPROD.NCM AS COD_NCM,
  cast(TBPROD.DT_ATUALIZACAO as date) AS ULTIMA_ALTERACAO,
  SUBSTRING (TBPROD.CST_ICMS_S FROM 1 FOR 1) AS OST,
  SUBSTRING (TBPROD.CST_ICMS_S FROM 2 FOR 3) AS ST,
  TBPROD.COMISSAO AS COMISSAO,
  TBPROD.CEST AS PERSONAL6,
  TBPROD.SALDO AS QTD,
  TBPROD.PESO AS PESO
FROM TBPROD
LEFT JOIN TBCATEG ON TBCATEG.CODIGO = TBPROD.CATEG
