SELECT 
       PES_00.PES_CODIGO AS CODIGO
      ,PES_00.PES_NOME AS NOME
      ,PES_00.PES_FANTASIA_OU_APELIDO AS FANTASIA
      ,PES_00.PES_ENDERECO AS ENDERECO
      ,PES_00.PES_NUMEROENDERECO AS NUMERO
      ,PES_00.PES_BAIRRO AS BAIRRO
      ,CID_00.CID_NOME AS CIDADE 
      ,UFS_00.UFS_SIGLA AS UF
      ,PES_00.CEP_CODIGO AS CEP
      ,PES_00.PES_PONTOREFERENCIA AS COMPLEMENTO
      ,PES_00.PES_DDD_TELEFONE_1 AS TELEFONE
      ,PES_00.PES_DDD_CELULAR AS CELULAR
      ,PES_00.PES_DDD_FAX AS FAX
      ,PES_00.PES_EMAIL AS EMAIL
      ,PES_00_02.PES_DATANASCIMENTO AS NASCIMENTO
      ,PES_00_02.PES_ESTADOCIVIL AS EST_CIVIL
      ,CONCAT (PES_00_02.PES_CPF,  PES_00_01.PES_CNPJ) AS CNPJ_CNPF
      ,concat (PES_00_02.PES_CI, PES_00_01.PES_IE) AS IE_RG     
      ,PES_00_02.PES_SEXO AS SEXO
      ,PES_00.PES_OBSERVACAO AS OBSERVACOES
      ,PES_00.PES_DATACADASTRO AS CADASTRO
  FROM NESKI_DBA_ERP.dbo.PES_00
  left join NESKI_DBA_ERP.dbo.PES_00_02 on PES_00_02.PES_CODIGO = PES_00.PES_CODIGO
    left join NESKI_DBA_ERP.dbo.PES_00_01 on PES_00_01.PES_CODIGO = PES_00.PES_CODIGO
  left join NESKI_DBA_ERP.dbo.CID_00 on CID_00.cid_codigo = PES_00.CID_CODIGO
  left join NESKI_DBA_ERP.dbo.UFS_00 on UFS_00.UFS_CODIGO = CID_00.UFS_CODIGO
where pes_00.pes_cliente = 'S'
