SELECT 
       PRO_00.PRO_CODIGO AS CODIGO
      ,PRO_00.PRO_DESCRICAO AS DESCRICAO
      ,max (PRO_00_05.PRO_CODIGOBARRA) AS BARRAS
      ,max (PRO_00_06.PRO_CODIGOFORNECEDOR) AS COD_FABRICANTE
      ,max (PES_00.PES_NOME) AS FORNECEDOR
      ,min (PRO_00_09.PRO_PRECOTABELA) AS PRECO_VENDA
      ,GRP_00.GRP_DESCRICAO AS GRUPO
      ,SGP_00.SGP_DESCRICAO AS FAMILIA
      ,PRO_00.SGM_CODIGO AS UND
      ,PRO_00.CLF_CODIGO AS COD_NCM
	  ,ETQ_00.ETQ_ESTOQUEFILIAL AS QTD
      ,ETQ_00.ETQ_VALORCUSTOCOMPRA AS PRECO_CUSTO
      ,PRO_00.PRO_CEST AS PERSONAL6
  FROM NESKI_DBA_ERP.dbo.PRO_00
LEFT JOIN NESKI_DBA_ERP.dbo.PRO_00_05 ON PRO_00.PRO_CODIGO = PRO_00_05.PRO_CODIGO
LEFT JOIN NESKI_DBA_ERP.dbo.PRO_00_06 ON PRO_00.PRO_CODIGO = PRO_00_06.PRO_CODIGO
LEFT JOIN NESKI_DBA_ERP.dbo.PES_00 ON PRO_00_06.PES_CODIGO = PES_00.PES_CODIGO
LEFT JOIN NESKI_DBA_ERP.dbo.PRO_00_09 ON PRO_00.PRO_CODIGO = PRO_00_09.PRO_CODIGO
LEFT JOIN NESKI_DBA_ERP.dbo.GRP_00 ON PRO_00.GRP_CODIGO = GRP_00.GRP_CODIGO
LEFT JOIN NESKI_DBA_ERP.dbo.SGP_00 ON PRO_00.GRP_CODIGO = SGP_00.SGP_CODIGO
left join NESKI_DBA_ERP.dbo.ETQ_00 on PRO_00.PRO_CODIGO = ETQ_00.PRO_CODIGO
where ETQ_00.FIL_CODIGO = '001'
group by 
       PRO_00.PRO_CODIGO
      ,PRO_00.PRO_DESCRICAO
      ,GRP_00.GRP_DESCRICAO
      ,SGP_00.SGP_DESCRICAO
      ,PRO_00.SGM_CODIGO
      ,PRO_00.CLF_CODIGO
	  ,ETQ_00.ETQ_ESTOQUEFILIAL
      ,ETQ_00.ETQ_VALORCUSTOCOMPRA
      ,PRO_00.PRO_CEST
	  order by 1
