SELECT 
  CNPJ AS CNPJ_CNPF
, CASE WHEN RG = '' OR RG IS NULL THEN IE ELSE RG END AS IE_RG
, FANTA AS FANTASIA
, RAZAO AS NOME
, CEP
, END AS ENDERECO
, NUM AS NUMERO
, COMP AS COMPLEMENTO
, MUN AS CIDADE
, UF
, BAIR AS BAIRRO
, FONE AS TELEFONE
, FAX
, CELU AS CELULAR
, CADA AS CADASTRO
, EMAIL
, OBS AS OBSERVACOES
, LIMITE AS LIMITE_CREDITO
, CONTATO
, CASE ATIVO WHEN '1' THEN 'ATIVO' ELSE 'INATIVO' END AS SITUACAO
FROM NFE.CLIENTES