SELECT 
  CODF AS CODIGO
,  CNPJ AS CNPJ_CNPF
, IE AS IE_RG
, FANTA AS FANTASIA
, RAZAO AS NOME
, CEP
, END AS ENDERECO
, NUM AS NUMERO
, COMP AS COMPLEMENTO
, MUN AS CIDADE
, UF 
, BAIR AS BAIRRO
, FONE AS TELEFONE
, FAX
, CELU AS CELULAR
, EMAIL
, CONTATO
FROM NFE.FORNE