SELECT 
  CODP AS COD_FABRICANTE 
, REF AS BARRAS 
, DESCP AS DESCRICAO
, UNIP AS UND
, NCMP AS COD_NCM
, CUSTOP AS PRECO_CUSTO
, MARGP AS MARGEM_LUCRO
, VENDP AS PRECO_VENDA
, ORIGP AS OST
, CODCFOP AS CF
, LOCALP AS PERSONAL1
, TRIBP AS PERSONAL2
, ALIQICMS AS ELO
, IPIP AS IPI_CODIGO_VENDA
, ALIPI AS ALIQ_IPI_VENDA
, PISP AS PIS_CODIGO
, ALPIS AS PIS_ALIQ_NOR
, CONFP AS COFINS_CODIGO
, ALCONF AS COFINS_ALIQ_NOR
, COR
, TAM AS TAMANHO
, PBRUTO AS PESO
, IPPT
, ESTOQUE AS QTD
-- , QUANTD
, MARCA AS CARACTERISTICAS
, CEST AS PERSONAL6
, QTDEMIN AS QTD_IDEAL
, F.RAZAO AS FORNCEDOR
, G.NOMEG AS GRUPO
FROM NFE.PRODUTOS
LEFT JOIN GRUPOS G ON G.CODG = PRODUTOS.CODGP 
LEFT JOIN FORNE F ON F.CODF = PRODUTOS.CODFP 