SELECT
    PRODUTOS.CODIGO_PRODUTO AS CODIGO,
    GRUPOS_PRODUTO.DESCRICAO AS GRUPO,
    SUBGRUPOS_PRODUTO.DESCRICAO AS FAMILIA,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.CUSTO_COMPRA AS PRECO_COMPRA,
    PRODUTOS.UNIDADE_ENTRADA AS UND_COMPRA,
    PRODUTOS.UNIDADE_SAIDA AS UND,
    PRODUTOS.ULTIMO_REAJUSTE AS ALTERACAO_PRECO,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    PRODUTOS.REFERENCIA3 AS OBSERVACOES,
    CAST (PRODUTOS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
    SUBSTRING (PRODUTOS.CST FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.CST FROM 2 FOR 3) AS ST,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.SALDO_ATUAL AS QTD
FROM PRODUTOS
LEFT JOIN GRUPOS_PRODUTO ON GRUPOS_PRODUTO.CODIGO_GRUPO = PRODUTOS.CODIGO_GRUPO
LEFT JOIN SUBGRUPOS_PRODUTO ON SUBGRUPOS_PRODUTO.CODIGO_SUBGRUPO = PRODUTOS.CODIGO_SUBGRUPO