SELECT FORNECEDORES.CODIGO,
FORNECEDORES.NOME,
FORNECEDORES.ENDERECO,
FORNECEDORES.BAIRRO,
FORNECEDORES.CIDADE,
FORNECEDORES.CEP,
FORNECEDORES.UF,
FORNECEDORES.TEL1 AS TELEFONE,
FORNECEDORES.TEL2 AS CELULARES,
FORNECEDORES.FAX,
FORNECEDORES.CNPJ AS CNPJ_CNPF,
FORNECEDORES.INSCEST AS IE_RG,
FORNECEDORES.CONTATO,
FORNECEDORES.OBS AS OBSERVACOES,
FORNECEDORES.EMAIL,
FORNECEDORES.NUMENDERECO AS NUMERO,
FORNECEDORES.COMPLEMENTO
FROM FORNECEDORES

