SELECT PRODUTOS.CODIGO,
PRODUTOS.PRODUTO AS DESCRICAO,
GRUPO.DESCRICAO AS GRUPO,
SUBGRUPO.DESCRICAO AS FAMILIA,
PRODUTOS.CODBARRAS AS BARRAS,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.CLASFISCAL AS COD_NCM,
PRODUTOS.PRCUSTO AS PRECO_CUSTO,
PRODUTOS.PRVENDA AS PRECO_VENDA,
PRODUTOS.DTREAJUSTE AS ALTERACAO_PRECO,
FORNECEDORES.NOME AS FORNECEDOR,
PRODUTOS.OBS AS OBSERVACOES,
PRODUTOS.CODCEST AS PERSONAL6,
ESTOQUE.SALDO AS QTD
FROM PRODUTOS
LEFT JOIN GRUPO ON PRODUTOS.GRUPO=GRUPO.CODIGO
LEFT JOIN SUBGRUPO ON PRODUTOS.SUBGRUPO=SUBGRUPO.CODIGO
LEFT JOIN FORNECEDORES ON PRODUTOS.FORNECEDOR=FORNECEDORES.CODIGO
LEFT JOIN ESTOQUE ON PRODUTOS.CODIGO=ESTOQUE.CODPROD
