SELECT
  ID AS CODIGO,
  GTIN AS BARRAS,
  CODIGO_INTERNO AS COD_FABRICANTE,
  NOME AS DESCRICAO,
  VALOR_CUSTO AS PRECO_CUSTO,
  MARKUP AS MARGEM_LUCRO,
  VALOR_VENDA AS PRECO_VENDA,
  QTD_ESTOQUE AS QTD,
  ICMSCST AS ST,
  CEST AS PERSONAL6,
  NCM AS COD_NCM,
  PISCST AS PIS_CODIGO,
  COFINSCST AS COFINS_CODIGO,
  VALOR_VENDA_ATACADO AS PRECO_ATACADO
FROM PRODUTO
