SELECT
	P.ID_PRODUTO AS CODIGO,
	P.DESCRICAO AS DESCRICAO,
	P.MODELO AS PERSONAL1,
	M.DESCRICAO AS FAMILIA,
	G.DESCRICAO AS GRUPO,
	P.VALORCUSTO AS PRECO_CUSTO,
	P.VALORVENDAVISTA AS PRECO_VENDA,
	P."CODIGOBARRA" AS BARRAS,
	P.DATACADASTRO AS DATA_CADASTRO,
	P.NCM AS COD_NCM,
	P.ID_UNIDADEMEDIDA AS UND,
	P.ID_SITUACAOTRIBUTARIA AS ST,
	P.MARGEMLUCRO AS MARGEM_LUCRO,
	P.OBSERVACAO AS OBSERVACOES,
	P.REFERENCIA AS COD_FABRICANTE,
	P.CODIGOCEST AS PERSONAL6,
	E.QUANTIDADE AS QTD
FROM PRODUTO P
LEFT JOIN MARCA M  ON P.ID_MARCA=M.ID_MARCA 
LEFT JOIN GRUPO G ON P.ID_GRUPO=G.ID_GRUPO 
LEFT JOIN ESTOQUE E ON P.ID_PRODUTO=E.ID_PRODUTO 