SELECT
    FORNECEDOR.CDFORNECEDOR AS CODIGO,
    FORNECEDOR.FORNECEDOR AS NOME,
    FORNECEDOR.FANTASIA AS FANTASIA,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.NUMERO AS NUMERO,
    MUNICIPIO.MUNICIPIO AS CIDADE,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.UF AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.TELEFONE AS TELEFONE,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.CELULAR AS CELULAR,
    FORNECEDOR.CGC AS CNPJ_CNPF,
    FORNECEDOR.INSCEST AS IE_RG,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN MUNICIPIO ON MUNICIPIO.CDMUNICIPIO = FORNECEDOR.CDMUNICIPIO
