SELECT
    PRODUTO.CDPRODUTO AS CODIGO,
    PRODUTO.PRODUTO AS DESCRICAO,
    PRODUTO.CODIGOBARRA AS BARRAS,
    PRODUTO.CDUNIDADE AS UND_COMPRA,
    PRODUTO.CDUNIDVENDA AS UND,
    PRODUTO.GRUPO AS GRUPO,
    PRODUTO.FORNECEDOR AS FORNECEDOR,
    MOVIMENTO.QTDEATUAL AS QTD,
    PRODUTO.PESOUNIT AS PESO,
    PRODUTO.SUBSTTRIB AS ST,
    PPVV.VLCUSTO AS PRECO_CUSTO,
    PRODUTO.VLCUSTOMEDIO AS CUSTO_MEDIO,
    PPVV.PERCENTUAL AS MARGEM_LUCRO,
    PPVV.PRECO AS PRECO_VENDA,
    PPVA.PRECO AS PRECO_ATACADO,
    PRODUTO.CDFABRICANTE AS COD_FABRICANTE,
    CAST (PRODUTO.DTCOMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (PRODUTO.DTALTERACAO AS DATE) AS ALTERACAO_PRECO,
    PRODUTO.CLASSFISCAL AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTOPRECO PPVV ON PRODUTO.CDPRODUTO = PPVV.CDPRODUTO AND PPVV.IDPRECO = 1
LEFT JOIN PRODUTOPRECO PPVA ON PRODUTO.CDPRODUTO = PPVA.CDPRODUTO AND PPVA.IDPRECO = 3
LEFT JOIN MOVIMENTO ON MOVIMENTO.CDPRODUTO = PRODUTO.CDPRODUTO
WHERE MOVIMENTO.CDDEPOSITO = '1'
