SELECT
    CADPRO.ICODINTPRO AS CODIGO,
    CADPRO.CCODPRO AS COD_FABRICANTE,
    CADPRO.CDESCRICAO AS DESCRICAO,
    CADPRO.CCODBARRA AS BARRAS,
    case when CADPRO.CSITUACAO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO,
    CADPRO.DDATCAD AS DATA_CADASTRO,
    CADPRO.CUNIDADE AS UND,
    CADPRO.MAPLICACAO AS OBSERVACOES,
    CADFOR.CNOME AS FORNECEDOR,
    CADPRO.CCODSITTRITABA AS OST,
    CADPRO.CCODSITTRITABB AS ST,
    CADPRO.CCODNCM AS COD_NCM,
    CADPRO.DDATULTPRCVEN AS ALTERACAO_PRECO,
    CADPRO.QESTOQUE AS QTD,
    CADPRO.QESTMIN AS QTD_IDEAL,
    CADPRO.VPRCCUS AS PRECO_CUSTO,
    CADPRO.VPRCVEN AS PRECO_VENDA,
    CADPRO.CCEST AS PERSONAL6
FROM CADPRO
LEFT JOIN CADFOR ON CADFOR.ICODFOR = CADPRO.ICODFOR