SELECT
  CLIFOR.ID AS CODIGO,
  CLIFOR.CNP AS CNPJ_CNPF,
  CLIFOR.NOME AS FANTASIA,
  CLIFOR.RAZAO_SOCIAL AS NOME,
  CLIFOR.INSCRICAO_ESTADUAL AS IE_RG,
  CLIFOR.INSCRICAO_MUNICIPAL AS IM,
  CLIFOR.FONE AS TELEFONE,
  CLIFOR.CELULAR AS CELULAR,
  CLIFOR.CONTATO AS CONTATO,
  CLIFOR.EMAIL AS EMAIL,
  CLIFOR.OBS AS OBSERVACOES,
  CLIFOR.ENDERECO AS ENDERECO,
  CLIFOR.NUMERO AS NUMERO,
  CLIFOR.COMPLEMENTO AS COMPLEMENTO,
  CLIFOR.BAIRRO AS BAIRRO,
  CLIFOR.CIDADE AS CIDADE,
  CLIFOR.UF AS UF,
  CLIFOR.CEP AS CEP,
  CLIFOR.FAX AS FAX
FROM CLIFOR
WHERE CLIFOR.TIPO = '2'