SELECT
  PESSOAS.COD_PESS AS CODIGO,
  PESSOAS.CNPJCPF_PESS AS CNPJ_CNPF,
  PESSOAS.IE_PESS AS IE_RG,
  PESSOAS.IM_PESS AS IM,
  PESSOAS.NOM_PESS AS NOME,
  PESSOAS.FANT_PESS AS FANTASIA,
  PESSOAS.CONTATO_PESS AS CONTATO,
  PESSOAS.END_PESS AS ENDERECO,
  PESSOAS.NUM_PESS AS NUMERO,
  PESSOAS.COMPL_PESS AS COMPLEMENTO,
  PESSOAS.BAIRRO_PESS AS BAIRRO,
  MUN.NOM_MUN AS CIDADE,
  PESSOAS.UF_PESS AS UF,
  PESSOAS.CEP_PESS AS CEP,
  PESSOAS.FONE_PESS AS TELEFONE,
  PESSOAS.FAX_PESS AS FAX,
  PESSOAS.CELULAR_PESS AS CELULAR,
  PESSOAS.EMAIL_PESS AS EMAIL,
  PESSOAS.OBS_PESS AS OBSERVACOES
FROM PESSOAS
LEFT JOIN MUN ON MUN.COD_MUN = PESSOAS.COD_MUN
WHERE PESSOAS.FORN_PESS = 'S'
