SELECT
  CLI.CD_PESSOA AS CODIGO,
  CLI.NOME,
  CLI.APELIDO AS FANTASIA,
  CLI.CONTATO,
  CLI.CGC AS CNPJ_CNPF,
  COALESCE(NULLIF(CLI.INSC_EST, ''), CLI.RG) AS IE_RG, -- Ajuste aqui para usar o campo correto
  CLI.ENDERECO,
  CLI.NUM_END AS NUMERO,
  CLI.END_COMPL AS COMPLEMENTO,
  BAI.NOME AS BAIRRO,
  CID.NOME AS CIDADE,
  CID.CD_UF AS UF, -- Incluindo o estado (UF)
  CLI.CEP,
  CLI.TELEFONE1 AS TELEFONE,
  CLI.CELULAR,
  CLI.FAX,
  CLI.EMAIL,
  CLI.PAI,
  CLI.MAE
FROM SMB_TOIGO_GEF001.dbo.TCLIE CLI
LEFT JOIN SMB_TOIGO_GEF001.dbo.TBAIR BAI ON CLI.CD_BAIRRO = BAI.CD_BAIRRO
LEFT JOIN SMB_TOIGO_GEF001.dbo.TCIDA CID ON BAI.CD_CIDADE = CID.CD_CIDADE
ORDER BY CLI.CD_PESSOA ASC