SELECT
  FORN.CD_PESSOA AS CODIGO,
  FORN.NOME,
  FORN.APELIDO AS FANTASIA,
  FORN.CONTATO,
  FORN.CGC AS CNPJ_CNPF,
  -- Usando COALESCE para buscar o primeiro valor não nulo entre INSC_EST e RG
  COALESCE(NULLIF(FORN.INSC_EST, ''), FORN.RG) AS IE_RG, 
  FORN.ENDERECO,
  FORN.NUM_END AS NUMERO,
  FORN.END_COMPL AS COMPLEMENTO,
  BAI.NOME AS BAIRRO,
  CID.NOME AS CIDADE,
  CID.CD_UF AS UF, -- Incluindo o estado (UF)
  FORN.CEP,
  FORN.TELEFONE1 AS TELEFONE,
  FORN.CELULAR,
  FORN.FAX,
  FORN.EMAIL
FROM SMB_TOIGO_GEF001.dbo.TFORN FORN
LEFT JOIN SMB_TOIGO_GEF001.dbo.TBAIR BAI ON FORN.CD_BAIRRO = BAI.CD_BAIRRO
LEFT JOIN SMB_TOIGO_GEF001.dbo.TCIDA CID ON BAI.CD_CIDADE = CID.CD_CIDADE
ORDER BY FORN.CD_PESSOA ASC