SELECT 
    TI.[CD_ITEM] AS COD_FABRICANTE,
    TI.[CD_BARRAS] AS BARRAS,
    TI.[DESCRICAO],
    TI.[CD_UNIDADE] AS UND,
    TI.[CD_UNIDADE] AS UND_COMPRA, 
    TI.[DESCR_PRODUTO] AS CARACTERISTICAS,    
    ISNULL(TE.QTD, 0) AS QTD,    
    TI.[PRECO_MEDIO] AS CUSTO_MEDIO,
    TI.[PRECO_CUSTO],
    TI.[MARGEM_LUCRO],
    TI.[PRECO_VENDA],           
    TI.[TP_TRIBICMS] AS ST,        
    TI.[PERC_IPI] AS ALIQ_IPI,
    TI.[PERC_IPI] AS ALIQ_IPI_VENDA,    
    TI.[ITEM_IPI_SITUACAOTRIB] AS IPI_CODIGO,
    TI.[ITEM_IPI_SITUACAOTRIBENTRADA] AS IPI_CODIGO_VENDA,
    TI.[ITEM_PIS_TIPOTRIBUTACAO] AS PIS_CODIGO,    
    TI.[ITEM_PIS_ALIQUOTA] AS PIS_ALIQ_NOR,
    TI.[ITEM_COFINS_ALIQUOTA] AS COFINS_ALIQ_NOR,
    TI.[ITEM_CLASSFISCAL] AS COD_NCM,
	TI.[TITEM_CEST] AS PERSONAL6
FROM [SMB_TOIGO_GEF001].[dbo].[TITEM] TI
LEFT JOIN (
    SELECT CD_ITEM, SUM(QTD_ITEM) AS QTD
    FROM [SMB_TOIGO_GEF001].[dbo].[TITES]
    GROUP BY CD_ITEM
) TE ON TE.CD_ITEM = TI.CD_ITEM