SELECT 
CLIENTE.CODCLIENTE AS CODIGO,
CLIENTE.NOME,
CLIENTE.APELIDO_FANTASIA AS FANTASIA,
CAST(CLIENTE.CADASTRADO_EM AS DATE) AS CADASTRO,
CLIENTE.FONE AS TELEFONE,
CLIENTE.CELULAR_FAX AS CELULAR,
CLIENTE.E_MAIL AS EMAIL,
CLIENTE.ENDERECO,
CLIENTE.NUMERO,
CLIENTE.COMPLEMENTO,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.UF,
CLIENTE.CEP,
CLIENTE.RG_INSCEST AS IE_RG,
CLIENTE.CPF_CNPJ AS CNPJ_CNPF,
CLIENTE.OBS AS OBSERVACOES
FROM CLIENTE
WHERE CLIENTE.CODCLIENTE>0
