SELECT TABPRO.SEQLPRO AS CODIGO,
TABGRU.NOMEGRU AS GRUPO,
TABPRO.NOMEPRO AS DESCRICAO,
TABPRO.CFABPRO AS COD_FABRICANTE,
TABPRO.PRVEPRO AS PRECO_VENDA,
TABPRO.UNIDPRO AS UND,
TABPRO.CANPPRO AS COD_NCM
FROM TABPRO
LEFT JOIN TABGRU ON TABPRO.GRUPPRO=TABGRU.CODIGRU

