SELECT
    CODIGO,
    NOMEFORNECEDOR AS NOME,
    CNPJ AS CNPJ_CNPF,
    ENDERECO,
    BAIRRO,
    CIDADE,
    ESTADO AS UF,
    NUMERO,
    IE AS IE_RG,
    FONE1 AS TELEFONE,
    FONE2 AS CELULAR,
    FAX,
    CEP,
    EMAIL
FROM CADASTROFORNECEDOR