SELECT
    CADASTRODESCRICAO.CODIGO AS CODIGO,
    CADASTRODESCRICAO.DESCRICAO AS DESCRICAO,
    CADASTRODESCRICAO.PRECO AS PRECO_VENDA,
    CADASTRODESCRICAO.CODIGOBARRAS AS BARRAS,
    CADASTRODESCRICAO.ESTOQUE AS QTD,
    CADASTRODESCRICAO.MARGEMLUCRO AS MARGEM_LUCRO,
    CADASTRODESCRICAO.PRECOCOMPRA AS PRECO_CUSTO,
    CADASTRODESCRICAO.ESTOQUEMINIMO AS QTD_IDEAL,
    CADASTRODESCRICAO.UN AS UND,
    CADASTROSETORES.setor AS GRUPO,
    CADASTRODESCRICAO.DATA AS DATA_CADASTRO,
    CADASTRODESCRICAO.PRECOATACADO AS PRECO_ATACADO,
    CADASTRODESCRICAO.CODIGOINTERNO AS COD_FABRICANTE
FROM CADASTRODESCRICAO
LEFT JOIN cadastrosetores ON CADASTROSETORES.codigo = CADASTRODESCRICAO.SETOR
