SELECT 
  F.ID AS CODIGO
, F.RAZAO_SOCIAL AS NOME
, F.NOME_FANTASIA AS FANTASIA
, F.CPF_CNPJ AS CNPJ_CNPF
, F.IE_RG
, F.RUA AS ENDERECO
, F.NUMERO
, F.BAIRRO
, F.TELEFONE
, F.CELULAR
, F.EMAIL
, F.CEP
, Ci.NOME AS CIDADE
, Ci.UF
FROM FORNECEDORS F
LEFT JOIN CIDADES Ci ON Ci.ID = F.CIDADE_ID 
