SELECT 
  P.ID AS CODIGO
, P.CODBARRAS AS BARRAS
, P.NOME AS DESCRICAO
, P.COR
, P.VALOR_VENDA AS PRECO_VENDA
, P.VALOR_COMPRA AS PRECO_CUSTO
, P.MARGEM_LUCRO AS MARGEM_LUCRO
, REPLACE (P.NCM, '.','') AS COD_NCM
, REPLACE (P.CEST, '.','') AS PERSONAL6
, P.ESTOQUE_MINIMO AS QTD_IDEAL
, P.REFERENCIA AS COD_FABRICANTE
, P.PESO_BRUTO AS PESO
, P.UNIDADE_COMPRA AS UND_COMPRA
, P.CONVERSAO_UNITARIA AS FAT_CONV
, P.UNIDADE_VENDA AS UND
, P.PERC_PIS AS PIS_ALIQ_NOR
, P.PERC_COFINS AS COFINS_ALIQ_NOR
, P.PERC_IPI AS ALIQ_IPI_VENDA
, P.CST_CSOSN AS ST
, P.CST_PIS AS PIS_CODIGO
, P.CST_COFINS AS COFINS_CODIGO
, P.CST_IPI AS IPI_CODIGO_VENDA
-- , P.PERC_ICMS AS ELO
, LEFT (P.CFOP_SAIDA_ESTADUAL,3) AS ELO
, DATE (P.CREATED_AT) AS DATA_CADASTRO
, C.NOME AS GRUPO
, E.QUANTIDADE AS QTD
FROM PRODUTOS P
LEFT JOIN CATEGORIAS C ON C.ID = P.CATEGORIA_ID
LEFT JOIN ESTOQUES E ON E.PRODUTO_ID = P.ID
