SELECT
  CLIENTES.codigo AS CODIGO,
  CLIENTES.nome AS NOME,
  CLIENTES.razaosocia AS FANTASIA,
  CLIENTES.endereco AS ENDERECO,
  CLIENTES.Nrologr AS NUMERO,
  CLIENTES.complement AS COMPLEMENTO,
  CLIENTES.bairro AS BAIRRO,
  CLIENTES.cidade AS CIDADE,
  CLIENTES.uf AS UF,
  CLIENTES.cep AS CEP,
  CLIENTES.telefone AS TELEFONE,
  CLIENTES.fax AS FAX,
  CLIENTES.celular AS CELULAR,
  CLIENTES.email AS EMAIL,
  CLIENTES.ident1 AS CNPJ_CNPF,
  CLIENTES.ident2 AS IE_RG
FROM CLIENTES
where CLIENTES.codigo >0