SELECT 
       CLIENTES.CodCli AS CODIGO
      ,CLIENTES.Nome AS NOME
      ,CLIENTES.Endereco AS ENDERECO
      ,CLIENTES.Complemento AS COMPLEMENTO
      ,CLIENTES.Bairro AS BAIRRO
      ,CLIENTES.Telefone AS TELEFONE
      ,CLIENTES.Celular AS CELULAR
      ,CLIENTES.CEP AS CEP
      ,MUNICIPIOS.MUNICIPIO AS CIDADE
      ,MUNICIPIOS.UF AS UF
      ,CLIENTES.IE AS IE_RG
      ,CLIENTES.CNPJ AS CNPJ_CNPF
      ,CLIENTES.Email AS EMAIL
      ,CLIENTES.Cargo AS PROFISSAO
      ,CLIENTES.Observacao AS OBSERVACOES
      ,CLIENTES.Fantasia AS FANTASIA
      ,CLIENTES.Numero AS NUMERO
  FROM Bancodados.dbo.Clientes
LEFT JOIN Bancodados.dbo.Municipios ON CLIENTES.CODMUN = MUNICIPIOS.CODMUN