SELECT 
       PRODUTOS.CodPro AS CODIGO
      ,PRODUTOS.Produto AS DESCRICAO
      ,ESTFIL.ESTOQUE AS QTD
      ,GRUPOS.GRUPO AS GRUPO
      ,MARCAS.MARCA AS FAMILIA
      ,PRODUTOS.CodUni AS UND
      ,PRODUTOS.CodBar AS BARRAS
      ,PRODUTOS.PrecoCusto AS PRECO_CUSTO
      ,PRODUTOS.Margem AS MARGEM_LUCRO
      ,PRODUTOS.PrecoVenda AS PRECO_VENDA
      ,PRODUTOS.NCM AS COD_NCM
      ,PRODUTOS.CustoMedio AS CUSTO_MEDIO
      ,PRODUTOS.CEST AS PERSONAL6
  FROM Bancodados.dbo.Produtos
LEFT JOIN Bancodados.dbo.Grupos ON PRODUTOS.CODGRU = GRUPOS.CODGRU
LEFT JOIN Bancodados.dbo.Marcas ON PRODUTOS.CODMAR = MARCAS.CODMAR
LEFT JOIN Bancodados.dbo.Estfil ON PRODUTOS.CODPRO = ESTFIL.CODPRO