SELECT
  TRANSPORTADORA.IDTRANSPORTADORA AS CODIGO,
  TRANSPORTADORA.NOME AS RAZAO_SOCIAL,
  case when TRANSPORTADORA.CNPJ = '' or TRANSPORTADORA.CNPJ is null then TRANSPORTADORA.CPF else TRANSPORTADORA.CNPJ END as CNPJ,
  TRANSPORTADORA.INSCEST AS IE_RG,
  TRANSPORTADORA.ENDERECO AS ENDERECO,
  TRANSPORTADORA.FONE AS TELEFONE,
  TRANSPORTADORA.EMAIL AS EMAIL,
  TRANSPORTADORA.PLACA AS PLACA,
  TRANSPORTADORA.RNTC AS RNTRC,
  CIDADE.NOME AS CIDADE,
  UF.SIGLA AS UF
FROM TRANSPORTADORA
LEFT JOIN CIDADE ON CIDADE.IDCIDADE = TRANSPORTADORA.IDCIDADE
LEFT JOIN UF ON UF.IDUF = TRANSPORTADORA.IDUF
