SELECT
    "FORNECEDOR"."CODIGO",
    "CIDADE_IBGE"."MUNICIPIO" AS CIDADE,
    "CIDADE_IBGE"."UF",
    "FORNECEDOR"."RAZAO_SOCIAL" AS NOME,
    "FORNECEDOR"."FORNECEDOR" AS FANTASIA,
    "FORNECEDOR"."CEP",
    "FORNECEDOR"."ENDERECO",
    "FORNECEDOR"."NUMERO",
    "FORNECEDOR"."COMPLEMENTO",
    "FORNECEDOR"."BAIRRO",
    "FORNECEDOR"."CNPJ" AS CNPJ_CNPF,
    "FORNECEDOR"."IE" AS IE_RG,
    "FORNECEDOR"."TELEFONE",
    "FORNECEDOR"."CELULAR",
    "FORNECEDOR"."EMAIL"
FROM "FORNECEDOR"
LEFT JOIN "CIDADE_IBGE" ON "FORNECEDOR"."CODIGO_CIDADE_IBGE" = "CIDADE_IBGE"."CODIGO_MUNICIPIO"