SELECT
  PRODSERV.PRSCODSEQ AS CODIGO,
  PRODSERV.PRSCODBAR AS BARRAS,
  PRODSERV.PRSCODINT AS COD_FABRICANTE,
  PRODSERV.PRSDESCOM AS DESCRICAO,
  PRODSERV.PRSDESRES AS CARACTERISTICAS,
  PRODSERV.PRSUNICOD AS UND,
  GRUPO.GRPDES AS GRUPO,
  PRODSERV.PRSCSTCOD AS ST,
  PRODSERV.PRSNCMCOD AS COD_NCM,
  PRODSERV.PRSDATCAD AS DATA_CADASTRO,
  PRODSERV.PRSPRCVEN AS PRECO_VENDA,
  PRODSERV.PRSCUSMED AS CUSTO_MEDIO,
  PRODSERV.PRSMARLUC AS MARGEM_LUCRO,
  PRODSERV.PRSQTDMIN AS QTD_IDEAL,
  PRODSERV.PRSPESLIQ AS PESO,
  PRODSERV.PRSALT AS QTD
FROM PRODSERV
LEFT JOIN GRUPO ON GRUPO.GRPCOD = PRODSERV.PRSGRPCOD
