SELECT
  SUBSTRING (PRODUTO.PROCOD FROM 9 FOR 14) AS CODIGO,
  PRODUTO.PRODES AS DESCRICAO,
  PRODUTO.PRODESRDZ AS CARACTERISTICAS,
  FORNECEDOR.FORDES AS FORNECEDOR,
  GRUPO.GRPDES AS GRUPO,
  ESTOQUE.ESTATU AS QTD,
  PRODUTO.PROESTMIN AS QTD_IDEAL,
  PRODUTO.PRONCM AS COD_NCM,
  PRODUTO.PROPRC1 AS PRECO_VENDA,
  PRODUTO.PROUNDCMP AS UND_COMPRA,
  PRODUTO.PROUNID AS UND,
  PRODUTO.TRBID AS ST,
  PRODUTO.PROCOD AS COD_FABRICANTE,
  CAST (PRODUTO.PRODATCADALT AS DATE) AS ALTERACAO_PRECO,
  CAST (PRODUTO.PRODATCADINC AS DATE) AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.GRPCOD = PRODUTO.GRPCOD
LEFT JOIN FORNECEDOR ON FORNECEDOR.CLICOD = PRODUTO.FORCOD
LEFT JOIN ESTOQUE ON ESTOQUE.PROCOD = PRODUTO.PROCOD
WHERE ESTOQUE.LOJCOD = '0001'