SELECT
    CODIGO,
    RAZAO AS NOME,
    CPMF AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    LOGRADOURO AS ENDERECO,
    COMPLEMENTO,
    BAIRRO,
    CEP,
    UF,
    MUNICIPIO AS CIDADE,
    NUMERO
FROM FORNECEDORES
