select
PRODUCT.ID AS CODiGO,
PRODUCT.ID AS COD_FABRICANTE,
PRODUCT.CODBARS AS BARRAS,
PRODUCT.DESCRIPTION AS DESCRICAO,
PRODUCT.CSOSN AS ST,
PRODUCT.NCM AS COD_NCM,
PRODUCT.QUANTITYSTOCK AS QTD,
PRODUCT.PRICESALE AS PRECO_VENDA,
PRODUCT.PRICECOST AS PRECO_CUSTO,
PRODUCT.REFERENCE AS COD_FABRICANTE,
PRODUCT.COST_MEDIUM AS CUSTO_MEDIO,
PRODUCT.LASTSALE AS ULTIMA_VENDA,
PRODUCT.lastpurchase AS ALTERACAO_PRECO,
cest.cest as personal6,
PRODUCTGROUP.description AS OBSERVACOES
from PRODUCT
LEFT JOIN CEST on CEST.ID = PRODUCT.idcest
LEFT JOIN PRODUCTGROUP ON PRODUCTGROUP.ID = PRODUCT.id_group


