SELECT
  CLIEFORN.CODI AS CODIGO,
  CLIEFORN.NOME AS NOME,
  CLIEFORN.DATA_NASC AS NASCIMENTO,
  case when CLIEFORN.CNPJ ='' then CLIEFORN.CPF
  else CLIEFORN.CNPJ end as CNPJ_CNPF,
  case when CLIEFORN.INSC = '' or CLIEFORN.INSC is null then CLIEFORN.RG else CLIEFORN.INSC END AS IE_RG,
  CLIEFORN.ENDE AS ENDERECO,
  CLIEFORN.FONE AS TELEFONE,
  CLIEFORN.BAIR AS BAIRRO,
  CLIEFORN.CIDA AS CIDADE,
  CLIEFORN.UF AS UF,
  CLIEFORN.CEP AS CEP,
  CLIEFORN.ESTA_CIVI AS EST_CIVIL,
  CLIEFORN.CONJ AS CONJUGE,
  CLIEFORN.NOME_PAI AS PAI,
  CLIEFORN.NOME_MAE AS MAE,
  CLIEFORN.MAIL AS EMAIL,
  CLIEFORN.OBS AS OBSERVACOES,
  CLIEFORN.COMP AS COMPLEMENTO,
  CLIEFORN.FONE2 AS CELULAR,
  CLIEFORN.FAX AS FAX,
  CLIEFORN.NOME_FANT AS FANTASIA,
  CLIEFORN.NOME_CONTATO AS CONTATO,
  CLIEFORN.LIMT_CRED AS LIMITE_CREDITO,
  CLIEFORN.SEXO AS SEXO
FROM CLIEFORN
WHERE CLIEFORN.TIPOCAD = 'A'OR TIPOCAD = 'C'
