SELECT
  PROD.CODI AS CODIGO,
  PROD.DESCR AS DESCRICAO,
  GRUP_PROD.DESCR AS GRUPO,
  PROD.UNID AS UND,
  PROD.DESCR2 AS CARACTERISTICAS,
  PROD.REFE AS COD_FABRICANTE,
  PROD.CODI_BARRA AS BARRAS,
  PROD.NCM AS COD_NCM,
  PROD.OBS AS OBSERVACOES,
  PROD.CEST AS PERSONAL6,
  PROD_ADICIONAIS.ADIC_DATA_ULT_COMPRA AS ULTIMA_COMPRA,
  PROD_ADICIONAIS.ADIC_DATA_ULT_VENDA AS ULTIMA_VENDA,
  PROD_CUSTOS.CUST_CUSTO AS PRECO_CUSTO,
  PROD_CUSTOS.CUST_CUSTO_MEDIO AS CUSTO_MEDIO,
  PROD_CUSTOS.CUST_PRECO_VISTA AS PRECO_VENDA,
  PROD_ESTO.QTD AS QTD,
 PROD_TRIBUTOS.TRIB_SN_CSOSN_INTER_CF AS PERSONAL3,
  PROD_TRIBUTOS.TRIB_SN_CSOSN_INTER_CF AS ST
FROM PROD
LEFT JOIN PROD_ADICIONAIS ON PROD_ADICIONAIS.ADIC_PROD_CODI = PROD.CODI
LEFT JOIN PROD_CUSTOS ON PROD_CUSTOS.CUST_PROD_CODI = PROD.CODI
LEFT JOIN PROD_ESTO ON PROD_ESTO.COD_PROD = PROD.CODI
LEFT JOIN GRUP_PROD ON GRUP_PROD.CODI = PROD.GRUP
LEFT JOIN PROD_TRIBUTOS ON PROD_TRIBUTOS.TRIB_PROD_CODI = PROD.CODI
