select PRODUTOS.id AS CODIGO,
PRODUTOS.CodigoBarras AS BARRAS,
CATEGORIAS.`Descricao` AS GRUPO,
`unidades`.`Sigla` AS UND,
PRODUTOS.Descricao AS DESCRICAO,
PRODUTOS.PrecoVenda AS PRECO_VENDA
FROM PRODUTOS
LEFT JOIN UNIDADES ON `unidades`.`ID` = `produtos`.`UnidadeID`
LEFT JOIN CATEGORIAS ON CATEGORIAS.`ID` = PRODUTOS.`SetorEstoqueID`
