SELECT
  -- PRODUTOS.ID AS CODIGO,
  PRODUTOS.Descricao AS DESCRICAO,
  PRODUTOS.Unidade AS UND,
  PRODUTOS.CodigoBarra AS BARRAS,
  PRODUTOS.CodigoFabrica AS COD_FABRICANTE,
  GRUPO_PRODUTOS.DESCRICAO AS GRUPO,
  MARCA_PRODUTOS.DESCRICAO AS FAMILIA,
  PRODUTOS.PrecoVenda AS PRECO_VENDA,
  PRODUTOS.Estoque AS QTD,
  PRODUTOS.CodigoNCM AS COD_NCM,
  PRODUTOS.PrecoCusto  AS PRECO_CUSTO
FROM PRODUTOS
LEFT JOIN GRUPO_PRODUTOS ON PRODUTOS.GRUPO = GRUPO_PRODUTOS.ID
LEFT JOIN MARCA_PRODUTOS ON PRODUTOS.MARCA = MARCA_PRODUTOS.ID
