SELECT
    id_fornecedor as codigo,
    FORNECEDOR.FORNECEDOR_CODIGO AS CODIGO,
    FORNECEDOR.RAZAO_SOCIAL AS NOME,
    FORNECEDOR.NOME_FANTASIA AS FANTASIA,
    FORNECEDOR.LOGRADOURO AS ENDERECO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.OBS AS OBSERVACOES,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.FONE AS TELEFONE,
    FORNECEDOR.CPF_CNPJ AS CNPJ_CNPF,
    CIDADE.DESCRICAO AS CIDADE,
    CIDADE.SIGLA_ESTADO AS UF,
    FORNECEDOR.INSC_ESTADUAL AS IE_RG,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.NUMERO AS NUMERO,
    FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.CONTATO AS CONTATO
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.ID_CIDADE = FORNECEDOR.ID_CIDADE
