SELECT 
       CDFOR AS CODIGO
      ,NOME AS NOME
      ,FANTASIA AS FANTASIA
      ,ENDERECO AS ENDERECO
      ,BAIRRO AS BAIRRO
      ,CEP AS CEP
      ,CIDADE AS CIDADE
      ,CGC AS CNPJ_CNPF
      ,IE AS IE_RG
      ,ESTADO AS UF
      ,CONTATO AS CONTATO
      ,FONE AS TELEFONE
      ,FAX AS FAX
      ,EMAIL AS EMAIL
      ,OBS AS OBSERVACOES
  FROM ESystem.dbo.FORNECEDOR
