SELECT    
    PRODUTO.CODIGO AS BARRAS,
    PRODUTO.DESCRICAO AS DESCRICAO,
    GRUPO.DESCRICAO AS GRUPO,
    FORNECEDOR.NOME AS FORNECEDOR,
    PRODUTO.QUANTIDADE AS QTD,
    PRODUTO.PRECO AS PRECO_VENDA,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6,
    PRODUTO.AUTOR AS PERSONAL1
FROM PRODUTO
LEFT JOIN FORNECEDOR ON PRODUTO.FORNECEDOR = FORNECEDOR.CODIGO
LEFT JOIN GRUPO ON PRODUTO.GRUPO = GRUPO.CODIGO
