SELECT
PRODUTO.ID AS CODIGO,
PRODUTO.NCM AS COD_NCM,
PRODUTO.CODIGO AS COD_FABRICANTE,
PRODUTO.CODBAR AS BARRAS,
PRODUTO.DESCRICAO,
PRODUTO.UNIDADE AS UND,
PRODUTO.CUSTO AS PRECO_CUSTO,
PRODUTO.PRECO AS PRECO_VENDA,
PRODUTO.ESTOQUE AS QTD,
PRODUTO.ESTOQUE_MIN AS QTD_IDEAL,
PRODUTO.CEST AS PERSONAL6,
PRODUTO.MARCA AS CARACTERISTICAS, 
PRODUTO.ORIGEM AS OST,
PRODUTO.CPRODANP AS COD_ANP,
case when REGRA_TRIBUTACAO.CST_F ='' then REGRA_TRIBUTACAO.CST_J else REGRA_TRIBUTACAO.CST_F end as ST,
GRUPO.NOME AS GRUPO
FROM PRODUTO
LEFT JOIN REGRA_TRIBUTACAO ON PRODUTO.ID_TRIBUTACAO=REGRA_TRIBUTACAO.ID
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTO.ID_GRUPO
order by codigo
