SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    FORNECEDOR.NOME AS NOME,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.CIDADE AS CIDADE,
    FORNECEDOR.UF AS UF,
    case when FORNECEDOR.CNPJ = '' or FORNECEDOR.CNPJ is null then FORNECEDOR.CPF else FORNECEDOR.CNPJ END as CNPJ_CNPF,
    case when FORNECEDOR.INSC = '' or FORNECEDOR.INSC is null then FORNECEDOR.CI else FORNECEDOR.INSC END as IE_RG,
    FORNECEDOR.FONE AS TELEFONE,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.NUMERO AS NUMERO,
    FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR