SELECT 
PRODUTOS.CODIGO AS COD_FABRICANTE,
PRODUTOS.NOME AS DESCRICAO,
PRODUTOS.ESTOQUEATUAL AS QTD,
UNIDADECOMERCIALIZACAO.SIGLA AS UND,
PRODUTOS.NCM AS COD_NCM,
ETIQUETAS.DESCRICAO AS GRUPO,
PRODUTOS.CEST AS PERSONAL6,
PRODUTOS.SITUACAOTRIBUTARIAPIS AS PIS_CODIGO,
PRODUTOS.ALIQUOTAPIS AS PIS_ALIQ_NOR,
PRODUTOS.SITUACAOTRIBUTARIACOFINS AS COFINS_CODIGO,
PRODUTOS.ALIQUOTACOFINS AS COFINS_ALIQ_NOR,
CASE PRODUTOS.DESCONTINUADO WHEN 'S' THEN 'Inativo' ELSE 'Ativo' END AS SITUACAO, 
MIN(PRODUTODETALHE.PRECOVENDA) AS PRECO_VENDA,
MIN(PRODUTODETALHE.PRECOCUSTO) AS PRECO_CUSTO
FROM PRODUTOS
LEFT JOIN ETIQUETAS ON PRODUTOS.CODIGOETIQUETA=ETIQUETAS.CODIGO
LEFT JOIN PRODUTODETALHE ON PRODUTOS.CODIGO=PRODUTODETALHE.CODIGOPRODUTO
LEFT JOIN UNIDADECOMERCIALIZACAO ON PRODUTOS.codigounidadecomercial = UNIDADECOMERCIALIZACAO.CODIGO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
