SELECT
    CODIGO_PRODUTO AS CODIGO,
    DESCRICAO AS DESCRICAO,
    QUANTIDADE AS QTD,
    VALOR_A_VISTA AS PRECO_VENDA,
    VALOR_DA_COMPRA AS PRECO_CUSTO,
    PORCENTUAL_LUCRO_VENDA_VISTA AS MARGEM_LUCRO,
    CAST (DATA_ULTIMA_COMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (DATA_ULTIMA_VENDA AS DATE) AS ULTIMA_VENDA,
    CAST (DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
    OBSERVACAO AS OBSERVACOES,
    ESTOQUE_MINIMO AS QTD_IDEAL,
    COD_FABRICANTE AS COD_FABRICANTEW,
    NCM AS COD_NCM,
    CST AS ST,
    UN_COMERCIAL AS UND,
    EAN AS BARRAS,
    CEST AS PERSONAL6
FROM PRODUTOS