SELECT
    --PESSOA.CODPES AS CODIGO,
    PESSOA.NOMEPES AS NOME,
    PESSOA.ENDERECOPES AS ENDERECO,
    CIDADE.NOMECID AS CIDADE,
    UF.UF,
    PESSOA.BAIRROPES AS BAIRRO,
    PESSOA.FONEPES AS TELEFONE,
    PESSOA.EMAILNFPES AS EMAIL,
    PESSOA.CPFCNPJPES AS CNPJ_CNPF,
    PESSOA.RGIEPES AS IE_RG,
    PESSOA.DTNASCPES AS NASCIMENTO,
    --ESSOA.DTCADASTROPES AS CADASTRO,
    PESSOA.CELULARPES AS CELULAR,
    PESSOA.NUMEROPES AS NUMERO,
    PESSOA.CEPPES AS CEP,
    PESSOA.COMPLEMENTOPES AS COMPLEMENTO
FROM PESSOA
LEFT JOIN CIDADE ON PESSOA.CODCID = CIDADE.CODCID
LEFT JOIN UF ON CIDADE.coduf = UF.coduf
WHERE PESSOA.CLIENTE = 'S'
