select
    "CLIENTE"."CODIGO",
    "CIDADE_IBGE"."MUNICIPIO" AS CIDADE,
    "CIDADE_IBGE"."UF",
    "CLIENTE"."CLIENTE" AS FANTASIA,
    "CLIENTE"."RAZAO_SOCIAL" AS NOME,
    "CLIENTE"."ENDERECO",
    "CLIENTE"."COMPLEMENTO",
    "CLIENTE"."BAIRRO",
    "CLIENTE"."CEP",
    COALESCE("CLIENTE"."RG",'') || COALESCE("CLIENTE"."IE",'') AS IE_RG,
    COALESCE("CLIENTE"."CPF",'') || COALESCE("CLIENTE"."CNPJ",'') AS CNPJ_CNPF, 
    "CLIENTE"."TELEFONE",
    "CLIENTE"."FAX",
    "CLIENTE"."CELULAR",
    "CLIENTE"."EMAIL",
    "CLIENTE"."NUMERO"
from "CLIENTE"
LEFT JOIN "CIDADE_IBGE" ON "CLIENTE"."CODIGO_CIDADE_IBGE" = "CIDADE_IBGE"."CODIGO_MUNICIPIO"