
SELECT
    "CODIGO" AS COD_FABRICANTE,
    "CODIGO_BARRAS" AS BARRAS,
    "CODIGO_UNIDADE_MEDIDA" AS UND,
    "NCM" AS COD_NCM,
    "CSOSN" AS ST,
    "PRODUTO" AS DESCRICAO,
    "PRECO_CUSTO",
    "PRECO_VENDA",
    "QTDE" AS QTD,
    "CEST" AS PERSONAL6,
    "CODIGO_ANP" AS COD_ANP
FROM "PRODUTO"