SELECT
  FORNECEDORES.CODIGO AS CODIGO,
  FORNECEDORES.NOME AS NOME,
  FORNECEDORES.NOMEFANTASIA AS FANTASIA,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
  FORNECEDORES.BAIRRO AS BAIRRO,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.CIDADE AS CIDADE,
  FORNECEDORES.ESTADO AS UF,
  FORNECEDORES.CNPJ AS CNPJ_CNPF,
  case when FORNECEDORES.INSCRICAO = '' then FORNECEDORES.RG else FORNECEDORES.INSCRICAO END as IE_RG,
  FORNECEDORES.TELEFONE AS TELEFONE,
  FORNECEDORES.CONTATO AS CONTATO,
  FORNECEDORES.FAX AS FAX,
  FORNECEDORES.OBSERVACOES AS OBSERVACOES,
  FORNECEDORES.EMAIL AS EMAIL
FROM FORNECEDORES
