SELECT
    CAD_PESSOAS.CODPES_PES AS CODIGO,
    CAD_PESSOAS.DESCRICAO_PES AS NOME,
    CAD_PESSOA_JURIDICA.FANTASIA_PESJUR AS FANTASIA,
    CAD_PESSOA_FISICA.APELIDO_PESFIS AS CONTATO,
    case when CAD_PESSOA_FISICA.CPF_PESFIS = '' or CAD_PESSOA_FISICA.CPF_PESFIS is null then CAD_PESSOA_JURIDICA.CNPJ_PESJUR else CAD_PESSOA_FISICA.CPF_PESFIS END AS CNPJ_CNPF,
    case when CAD_PESSOA_FISICA.RGNUMERO_PESFIS = '' or CAD_PESSOA_FISICA.RGNUMERO_PESFIS is null then CAD_PESSOA_JURIDICA.INSCMUNICIPAL_PESJUR else CAD_PESSOA_FISICA.RGNUMERO_PESFIS END AS IE_RG,
    CAD_PESSOA_JURIDICA.INSCMUNICIPAL_PESJUR AS IM,
    CAD_PESSOA_ENDERECO.LOGRADOURO_PESEND AS ENDERECO,
    CAD_PESSOA_ENDERECO.NUMERO_PESEND AS NUMERO,
    CAD_PESSOA_ENDERECO.COMPLEMENTO_PESEND AS COMPLEMENTO,
    CAD_BAIRROS.DESCRICAO_BRO AS BAIRRO,
    CAD_CIDADES.DESCRICAO_CID AS CIDADE,
    CAD_ESTADOS.sigla_est AS UF,
    CAD_PESSOA_ENDERECO.CEP_PESEND AS CEP,
    CAD_PESSOA_TELEFONE.TELEFONE_PESTEL AS TELEFONE,
    CAD_PESSOA_EMAIL.EMAIL_PESMAIL AS EMAIL,
    CAD_PESSOAS.OBSERVACOES_PES AS OBSERVACOES
FROM CAD_PESSOAS
LEFT JOIN CAD_PESSOA_EMAIL ON CAD_PESSOA_EMAIL.PESSOA_PESMAIL = CODPES_PES
LEFT JOIN CAD_PESSOA_ENDERECO ON CAD_PESSOA_ENDERECO.pessoa_pesend = CODPES_PES
LEFT JOIN CAD_PESSOA_FISICA ON CAD_PESSOA_FISICA.CODPESFIS_PESFIS = CODPES_PES
LEFT JOIN CAD_PESSOA_JURIDICA ON CAD_PESSOA_JURIDICA.CODPESJUR_PESJUR = CODPES_PES
LEFT JOIN CAD_PESSOA_TELEFONE ON CAD_PESSOA_TELEFONE.PESSOA_PESTEL = CODPES_PES
left join CAD_BAIRROS on CAD_BAIRROS.codbro_bro = CAD_PESSOA_ENDERECO.BAIRRO_PESEND
LEFT JOIN CAD_CIDADES ON CAD_CIDADES.codcid_cid = CAD_BAIRROS.cidade_bro
LEFT JOIN CAD_ESTADOS ON CAD_ESTADOS.codest_est = CAD_CIDADES.ESTADO_CID
WHERE CAD_PESSOAS.FORNECEDOR_PES = 'S' AND CAD_PESSOAS.CODPES_PES > '0'