SELECT
    CAD_ITENS.CODITE_ITE AS CODIGO,
    CAD_ITENS.DESCRICAO_ITE AS DESCRICAO,
    CAD_ITENS.DESCRICAOREDUZIDA_ITE AS CARACTERISTICAS,
    CAD_ITENS.CODIGOBARRAS_ITE AS BARRAS,
    CAD_ITENS.REFERENCIA_ITE AS COD_FABRICANTE,
    cad_unidades.sigla_und AS UND_COMPRA,
    cad_unidades.sigla_und AS UN,
    cad_grupos.descricao_grp AS GRUPO,
    CAD_CATEGORIAS.descricao_cat AS FAMILIA,
    CAD_ITEM_ESTOQUE.DISPONIVEL_ITEEST AS QTD,
    CAD_ITENS.PRECOCUSTO_ITE AS PRECO_CUSTO,
    CAD_ITENS.PRECOVENDA_ITE AS PRECO_VENDA,
    CAD_ITENS.MARGEMLUCRO_ITE AS MARGEM_LUCRO,
    CAD_ITENS.PESOLIQUIDO_ITE AS PESO,
    TRIB_ICMS.cst_icms AS ST,
    CAD_ITENS.OBSERVACOES_ITE AS OBSERVACOES,
    TRIB_NCM.ncm_ncm AS COD_NCM,
    TRIB_CEST.cest_cest AS PERSONAL6,
    CAD_ITENS.INSDATE_ITE AS DATA_CADASTRO
FROM CAD_ITENS
LEFT JOIN cad_unidades ON CAD_UNIDADES.codund_und = CAD_ITENS.UNIDADEVENDA_ITE
LEFT JOIN cad_grupos ON CAD_GRUPOS.codgrp_grp = CAD_ITENS.GRUPO_ITE
LEFT JOIN CAD_CATEGORIAS ON CAD_CATEGORIAS.codcat_cat = CAD_ITENS.CATEGORIA_ITE
LEFT JOIN TRIB_ICMS ON TRIB_ICMS.codicms_icms = CAD_ITENS.MODALIDADEICMSST_ITE
LEFT JOIN TRIB_CEST ON TRIB_CEST.codcest_cest = CAD_ITENS.CEST_ITE
LEFT JOIN TRIB_NCM ON trib_ncm.codncm_ncm = CAD_ITENS.NCM_ITE
LEFT JOIN CAD_ITEM_ESTOQUE ON CAD_ITEM_ESTOQUE.CODITEEST_ITEEST = CAD_ITENS.CODITE_ITE