SELECT
TBPRODUT.PROCODBAR AS BARRAS,
TBPRODUT.PRODESCRI AS DESCRICAO,
TBGRUPRO.GRUDESCRI AS GRUPO,
TBPRODUT.PROUNIDA1 AS UND,
TBPRODUT.PROCUSFAB AS PRECO_CUSTO,
TBPRODUT.PROPREVEN AS PRECO_VENDA,
TBPRODUT.PROQNTEST AS QTD,
TBPRODUT.NBMCODIGO AS COD_NCM,
TBPRODUT.PRODATCAD AS DATA_CADASTRO,
TBPRODUT.PRODATALT AS ALTERACAO_PRECO,
TBPRODUT.PROCODSEQ AS CODIGO,
SUBSTRING(TBPRODUT.PROCSOSN1 FROM 3 FOR 6) AS ST
FROM TBPRODUT
LEFT JOIN TBGRUPRO ON TBPRODUT.GRUCLASSI=TBGRUPRO.GRUCLASSI




