SELECT PRO.CODPRO AS CODIGO,
PRO.NOMPRO AS DESCRICAO,
PRO.RFUPRO AS COD_FABRICANTE,
PRO.EANPRO AS BARRAS,
PRO.NCMPRO AS COD_NCM,
PRO.UNDPRO AS UND,
PPL.PCOPPL AS PRECO_VENDA,
PPL.PCUPPL AS PRECO_CUSTO,
PPL.SLDPPL AS QTD,
CAT.NOMCAT AS GRUPO,
MAR.NOMMAR AS CARACTERISTICAS
FROM PRO
LEFT JOIN CAT ON PRO.CATPRO=CAT.CODCAT
LEFT JOIN PPL ON PRO.CODPRO=PPL.PROPPL -- AND PPL.LOJPPL ='5170' --- caso use Multilojas, aqui ajusta o código da loja 
LEFT JOIN MAR ON PRO.MARPRO=MAR.CODMAR
