SELECT
	CF.ID AS CODIGO,
	CF.RAZAOSOCIAL AS NOME,	
	CF.NOMEFANTASIA AS FANTASIA,	
	CF.CPFCNPJ AS CNPJ_CNPF,
	CASE WHEN CF.INSCRICAOESTADUAL = '' OR CF.INSCRICAOESTADUAL IS NULL THEN CF.RG ELSE CF.INSCRICAOESTADUAL END AS IE_RG,
	CF.INSCRICAOMUNICIPAL AS IM,
	CF.ENDERECO,
	CF.NUMERO,
	CONCAT(CF.REFERENCIA,' - ',CF.COMPLEMENTO) AS COMPLEMENTO,	
	CF.BAIRRO,	
	CF.CEP,	
	CF.TELEFONE,	
	CF.CELULAR,
	CF.EMAIL,
	CF.OBSERVACOES,
	CF.NOMECONTATO AS CONTATO,
	M.NOME AS CIDADE,
	E.SIGLA AS UF
FROM
	CLIENTEFORNECEDOR CF
LEFT JOIN MUNICIPIO M ON M.ID = CF.MUNICIPIO_ID 
LEFT JOIN ESTADO E ON E.ID = M.ESTADO_ID 
WHERE TIPOCADASTRO = 'F' OR TIPOCADASTRO = 'CF'
