SELECT
	P.ID AS CODIGO,
	CASE P.ATIVO WHEN TRUE THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
--	P.CODIGOFORNECEDOR AS COD_FABRICANTE,
--	P.CODIGOFABRICANTE AS COD_FABRICANTE,	
	P.CODIGOINTERNO AS COD_FABRICANTE,
	P.DESCRICAO,
	P.EANCOMERCIAL AS BARRAS,
	P.INFADICIONAL AS OBSERVACOES,
	P.ORIGEMMERCADORIA AS PERSONAL1,
	P.PESOBRUTO AS PESO,
	P.QUANTIDADEMINIMA AS QTD,
--	P.ESTOQUEMINIMO,	
--	P.QUANTIDADETRIBUTACAO,
	P.UNIDADECOMERCIAL AS UND,
--	U.SIGLA AS UND,	
	P.VALORCOMPRA AS PRECO_CUSTO,	
	P.MARGEMLUCROFIXA AS MARGEM_LUCRO,
--	P.PERCENTUALLUCRO,	
	P.VALORUNITARIOCOMERCIAL AS PRECO_VENDA,
	P.VALORAPRAZO AS PERSONAL2,
	P.CODIGOANP AS COD_ANP,
	P.DATACADASTRO AS DATA_CADASTRO,
	P.NCM AS COD_NCM,
	P.CEST AS PERSONAL6,
	P.CODIGOBENEFICIOFISCAL AS CBENEF,
	P.FATORCONVERSAO AS FAT_CONV,
	P.LOCALIZACAO AS PERSONAL4,
	P.MARGEMCOMISSAO AS COMISSAO,
	M.DESCRICAO AS FAMILIA,
	C.CODIGO AS ST,
	CI.CODIGO AS IPI_CODIGO_VENDA,
	CPC.CODIGO AS PIS_CODIGO,
	CPC.CODIGO AS COFINS_CODIGO,
--      USAR_CSTS_NCMS,	-- TRATAR CASO USE A TRIBUTAÇÃO PELO NCM
	D.DESCRICAO AS GRUPO
FROM
	PRODUTO P
LEFT JOIN CST C ON C.ID = P.CSTICMS_ID 
LEFT JOIN CST CI ON CI.ID = P.CSTIPI_ID  
LEFT JOIN CST CPC ON CPC.ID = P.CSTPISCOFINS_ID 
LEFT JOIN UNIDADEMEDIDA U ON U.ID = P.UNIDADEMEDIDACOMERCIAL_ID 
LEFT JOIN MARCA M ON M.ID = P.MARCA_ID 
LEFT JOIN DEPARTAMENTO D ON D.ID = P.DEPARTAMENTO_ID 
