SELECT
  GLO_PESSOAS_FJ.ID AS CODIGO,
  GLO_PESSOAS_FJ.NOME_RAZAO AS NOME,
  GLO_PESSOAS_FJ.NOME_FANTASIA AS FANTASIA,
  GLO_PESSOAS_FJ.CPF_CNPJ AS CNPJ_CNPF,
  GLO_PESSOAS_FJ.RG_IE AS IE_RG,
  GLO_PESSOAS_FJ.DT_NASCIMENTO AS NASCIMENTO,
  GLO_PESSOAS_FJ.SEXO AS SEXO,
  GLO_PESSOAS_FJ.ENDERECO AS ENDERECO,
  GLO_PESSOAS_FJ.NUMERO AS NUMERO,
  GLO_PESSOAS_FJ.COMPLEMENTO AS COMPLEMENTO,
  GLO_PESSOAS_FJ.BAIRRO AS BAIRRO,
  GLO_CIDADES.NOME AS CIDADE,
  GLO_ESTADOS.UF AS UF,
  GLO_PESSOAS_FJ.CEP AS CEP,
  GLO_PESSOAS_FJ.FONE_RES AS TELEFONE,
  GLO_PESSOAS_FJ.CELULAR AS CELULAR,
  GLO_PESSOAS_FJ.EMAIL AS EMAIL,
  GLO_PESSOAS_FJ.OBS AS OBSERVACOES
  --CAST (GLO_PESSOAS_FJ.DT_CADASTRO AS DATE) AS CADASTRO
  from GLO_PESSOAS_FJ
  LEFT JOIN GLO_CIDADES ON GLO_CIDADES.COD_MUN_IBGE = GLO_PESSOAS_FJ.MUNICIPIO
  LEFT JOIN GLO_ESTADOS ON GLO_ESTADOS.COD_UF_IBGE = GLO_CIDADES.COD_UF_IBGE
