SELECT
  EST_PRODUTOS.ID AS CODIGO,
  EST_PRODUTOS.GTIN AS BARRAS,
  EST_PRODUTOS.NOME AS DESCRICAO,
  EST_PRODUTOS.NOME_GRUPO AS GRUPO,
  EST_UNIDADES.SIGLA AS UND,
  EST_PRODUTOS.ESTOQUE AS QTD,
  EST_PRODUTOS.PRC_CUSTO AS PRECO_CUSTO,
  EST_PRODUTOS.PRC_VENDA AS PRECO_VENDA,
  EST_PRODUTOS.MRG_LUCRO AS MARGEM_LUCRO,
  FIS_TRIBUTACOES.ICMS_SN_ST AS ST,
  EST_PRODUTOS.DESCRICAO AS OBSERVACOES,
  EST_PRODUTOS.NCM AS COD_NCM,
  EST_PRODUTOS.CEST AS PERSONAL6
FROM EST_PRODUTOS
LEFT JOIN EST_UNIDADES ON EST_UNIDADES.ID = EST_PRODUTOS.UNIDADE
LEFT JOIN FIS_TRIBUTACOES ON FIS_TRIBUTACOES.ID = EST_PRODUTOS.TRIBUTACAO
