SELECT PRODFILHO.CODPRODFILHO AS CODIGO,
UNIDADE.SIGLA AS UND,
PRODFILHO.DESCRICAO,
PRODFILHO.ESTOQUE AS QTD,
PRODFILHO.PRECOCUSTO AS PRECO_CUSTO,
PRODFILHO.PRECOPRATICADO1 AS PRECO_VENDA,
PRODFILHO.GRUPO,
PRODFILHO.NCM_CODIGO AS COD_NCM,
PRODFILHO.PRDF_CST_TRIBICMS AS ST,
PRODFILHO.CODIGOCEST AS PERSONAL6,
MIN(PRODFILHOCODBARRA.CODBARRA) AS BARRAS
FROM PRODFILHO
LEFT JOIN UNIDADE ON PRODFILHO.CODUNIDADE=UNIDADE.CODUNIDADE
LEFT JOIN PRODFILHOCODBARRA ON PRODFILHO.CODPRODFILHO=PRODFILHOCODBARRA.CODPRODFILHO
GROUP BY 1,2,3,4,5,6,7,8,9,10


