SELECT 
  c.ID AS CODIGO
, c.DT_INC AS CADASTRO
, CASE c.STATUS WHEN 'L' THEN 'Ativo' ELSE 'Inativo' end AS SITUACAO
, c.NOME AS FANTASIA
, c.RAZAOSOCIAL AS NOME
, c.DT_NASC AS NASCIMENTO
, c.TELEFONE
, c.EMAIL
, c.CELULAR
, c.CONTATO
, c.ENDERECO
, c.BAIRRO
, c.REFERENCIA AS COMPLEMENTO
, c.COMPLEMENTO AS PERSONAL1
, c.NUMERO
, ci.NOME AS CIDADE
, ci.UF 
, c.CEP
, case when c.CPF = '' or c.CPF is null then c.CNPJ else c.CPF END AS CNPJ_CNPF
, case when c.RG = '' or c.RG is null then c.IE else c.RG END AS IE_RG
, c.SEXO
, c.PROFISSAO
, c.LOCAL_TRABALHO AS LOCTRA
, c.OBSERVACAO AS OBSERVACOES
, c.NOME_PAI AS PAI
, c.NOME_MAE AS MAE
FROM CLIENTE c
LEFT JOIN CIDADE_IBGE ci ON ci.ID = c.IDCIDADE 
