SELECT
    FORNECEDOR.ID AS CODIGO,
    FORNECEDOR.RAZAO AS NOME,
    FORNECEDOR.FANTASIA AS FANTASIA,
    FORNECEDOR.CNPJ AS CNPJ_CNPF,
    FORNECEDOR.IE AS IE_RG,
    FORNECEDOR.ENDERECO AS ENDERECO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.CIDADE AS CIDADE,
    FORNECEDOR.UF AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.FONE AS TELEFONE,
    FORNECEDOR.FAX AS FAX,
    FORNECEDOR.CEL AS CELULAR,
    FORNECEDOR.EMAIL AS EMAIL
FROM FORNECEDOR