SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.CODBARRA AS BARRAS,
    PRODUTOS.UNID AS UND,
    PRODUTOS.CARACTERISTICA AS CARACTERISTICAS,
    PRODUTOS.NOMEFOR AS FORNECEDOR,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.QEST AS QTD,
    PRODUTOS.QMIN AS QTD_IDEAL,
    --GRUPO.NOME AS GRUPO,
    --SUBGRUPO.NOME AS FAMILIA,
    PRODUTOS.ALIQUOTA AS ST,
    PRODUTOS.PCUSTO AS PRECO_CUSTO,
    PRODUTOS.PVENDA AS PRECO_VENDA,
    PRODUTOS.REF AS COD_FABRICANTE,
    PRODUTOS.OBS AS OBSERVACOES,
    PRODUTOS.DATACAD AS DATA_CADASTRO,
    PRODUTOS.DATAALT AS ALTERACAO_PRECO,
    PRODUTOS.ULTCOMPRA AS ULTIMA_COMPRA,
    PRODUTOS.ULTSAIDA AS ULTIMA_VENDA
FROM PRODUTOS
--LEFT JOIN GRUPO ON GRUPO.ID = PRODUTOS.GRUPO
--LEFT JOIN SUBGRUPO ON SUBGRUPO.ID = PRODUTOS.SUBGRUPO
WHERE PRODUTOS.DESCRICAO IS NOT NULL or PRODUTOS.DESCRICAO <> ''