SELECT CLIENTE.CODIGO,
CLIENTE.NOME||' '||CLIENTE.SOBRENOME AS NOME,
CLIENTE.ENDERECO,
CLIENTE.NUMERO,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.ESTADO AS UF,
CLIENTE.CEP,
CLIENTE.TELEFONE1 AS TELEFONE,
CLIENTE.TELEFONE2 AS CELULAR,
CLIENTE.NASCIMENTO,
CLIENTE.RG AS IE_RG,
CLIENTE.CPF AS CNPJ_CNPF,
CLIENTE.CADASTRO,
CLIENTE.OBSERVACAO AS OBSERVACOES,
CLIENTE.NOMEPAI AS PAI,
CLIENTE.NOMEMAE AS MAE,
CLIENTE.COMPLEMENTO,
CLIENTE.EMAIL
FROM CLIENTE
WHERE CLIENTE.CODIGO>0

