SELECT PRODUTO.CODIGO,
PRODUTO.REFERENCIA AS COD_FABRICANTE,
PRODUTO.DESCRICAO,
PRODUTO.PRCCOMPRA AS PRECO_CUSTO,
PRODUTO.PRCVENDA AS PRECO_VENDA,
PRODUTO.CODBARRA AS BARRAS,
PRODUTO.DATULTCOMP AS ULTIMA_COMPRA,
PRODUTO.UNIDADE AS UND,
PRODUTO.SITTRIBUTARIA AS ST,
PRODUTO.NCM AS COD_NCM,
SALDO.ESTOQUE AS QTD
FROM PRODUTO
LEFT JOIN SALDO ON PRODUTO.CODIGO=SALDO.PRODUTO

