SELECT
  TABCLI.CODIGO AS CODIGO,
  TABCLI.NOME AS NOME,
  TABCLI.ENDERECO AS ENDERECO,
  TABCLI.BAIRRO AS BAIRRO,
  TABCLI.CIDADE AS CIDADE,
  TABCLI.ESTADO AS UF,
  TABCLI.CEP AS CEP,
  TABCLI.TELEFONE AS TELEFONE,
  TABCLI.DATA AS CADASTRO,
  TABCLI.OBS AS OBSERVACOES,
  TABCLI.EMAIL AS EMAIL,
  case when TABCLI.CNPJ = '' or TABCLI.CNPJ is null then TABCLI.CPF else TABCLI.CNPJ END AS CNPJ_CNPF,
  case when TABCLI.INSC = '' or TABCLI.INSC is null then TABCLI.RG else TABCLI.INSC END AS IE_RG,
  TABCLI.LIMITECRED AS LIMITE_CREDITO,
  TABCLI.CONTATO AS CONTATO,
  TABCLI.FAX AS FAX,
  TABCLI.DATANASC AS NASCIMENTO,
  TABCLI.NUMERO AS NUMERO,
  TABCLI.COMPLEMENTO AS COMPLEMENTO
FROM TABCLI
WHERE TABCLI.CODIGO > '0'
