SELECT
  TABFORN.CODIGO AS CODIGO,
  TABFORN.EMPRESA AS NOME,
  TABFORN.FANTASIA AS FANTASIA,
  TABFORN.CONTATO AS CONTATO,
  TABFORN.ENDERECO AS ENDERECO,
  TABFORN.NUMERO AS NUMERO,
  TABFORN.COMPLEMENTO AS COMPLEMENTO,
  TABFORN.BAIRRO AS BAIRRO,
  TABFORN.CIDADE AS CIDADE,
  TABFORN.ESTADO AS UF,
  TABFORN.CEP AS CEP,
  TABFORN.TELEFONE AS TELEFONE,
  TABFORN.FAX AS FAX,
  TABFORN.CNPJ AS CNPJ_CNPF,
  TABFORN.INSC AS IE_RG,
  TABFORN.OBS AS OBSERVACOES,
  TABFORN.EMAIL AS EMAIL
FROM TABFORN
WHERE TABFORN.CODIGO  > '0'
