SELECT
    REPLACE (PRODUTOS.CODIGO, ' ' , '') AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.PCUSTO AS PRECO_CUSTO,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.PVENDA AS PRECO_VENDA,
    PRODUTOS.QUANTIDADE AS QTD,
    PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.CODIGO_BARRAS AS BARRAS,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.OBSERVACOES AS OBSERVACOES,
    GRUPOS_PRODUTOS.descricao AS GRUPO,
    SUBGRUPOS_PRODUTOS.descricao AS FAMILIA,
    PRODUTOS.COMISSAO AS COMISSAO
FROM PRODUTOS
LEFT JOIN GRUPOS_PRODUTOS ON GRUPOS_PRODUTOS.id_grupo_produtos = PRODUTOS.id_grupo_produtos
LEFT JOIN SUBGRUPOS_PRODUTOS  ON SUBGRUPOS_PRODUTOS.id_subgrupo_produtos = PRODUTOS.id_subgrupo_produtos
