SELECT
    IN01PRO.CDPRO AS COD_FABRICANTE,
    IN01PRO.Codbr AS BARRAS,
    IN01PRO.NMPRO AS DESCRICAO,
    IN01PRO.CDFAB AS COD_FABRICANTE,
    IN01PRO.CDUND AS UND,
    IN01PRO.SALDO AS QTD,
    IN01PRO.PREVE AS PRECO_VENDA,
    IN01PRO.PRECU AS PRECO_CUSTO,
    IN01PRO.CUSME AS CUSTO_MEDIO,
    IN01PRO.TRIBU AS ST,
    IN01PRO.DTCAD AS DATA_CADASTRO,
    IN01PRO.INFOR AS OBSERVACOES,
    IN01PRO.CDNCM AS COD_NCM,
    IN01PRO.CODCEST AS PERSONAL6,
    IN01GRU.NMGRU AS GRUPO,
    IN01SBG.NMSBG AS FAMILIA,
    IN01FAB.NMFAB AS CARACTERISTICAS
FROM IN01PRO
LEFT JOIN IN01GRU ON IN01GRU.CDGRU = IN01PRO.CDGRU
LEFT JOIN IN01SBG ON IN01SBG.CDSBG = IN01PRO.CDSBG
LEFT JOIN IN01FAB ON IN01FAB.CDFAB = IN01PRO.CDFAB
