SELECT
    min (ACADGERAL.COD_GERAL) AS CODIGO,
    ACADGERAL.RAZAOSOCIAL AS NOME,
    ACADGERAL.APELIDO AS CONTATO,
    min (ACADGERAL.CNPJCPF) AS CNPJ_CNPF,
    case when ACADGERAL.INSCEST = '' or ACADGERAL.INSCEST is null then ACADGERAL.RG else ACADGERAL.INSCEST END as IE_RG,
    min (ACADENDERECOS.endereco) as ENDERECO,
    ACADENDERECOS.complemento AS COMPLEMENTO,
    ACADENDERECOS.bairro AS BAIRRO,
    ACADENDERECOS.cidade AS CIDADE,
    ACADENDERECOS.cep AS CEP,
    ACADENDERECOS.uf AS UF,
    max (ACADFONES.numerofone) AS TELEFONE,
    ACADGERAL.EMAIL AS EMAIL
FROM ACADGERAL
LEFT JOIN ACADTIPOS ON ACADTIPOS.cod_tipo = ACADGERAL.COD_TPCLIENTE
LEFT JOIN ACADFONES ON ACADFONES.cod_geral = ACADGERAL.cod_geral
LEFT JOIN ACADENDERECOS ON ACADENDERECOS.cod_geral = ACADGERAL.cod_geral
WHERE ACADTIPOS.cod_tipo = '2' AND ACADENDERECOS.tipoender = 'RESIDENCIAL' or ACADENDERECOS.tipoender = 'COMERCIAL' AND ACADFONES.tipofone = 'COMERCIAL'
GROUP BY 2,3,5,7,8,9,10,11,13
