SELECT
	F.FORNECEDOR_ID AS CODIGO,
	F.NOME_FANTASIA AS FANTASIA,
	F.RAZAO_SOCIAL AS NOME,
	F.CNPJ_CPF AS CNPJ_CNPF,
	F.IE AS IE_RG,
	F.ENDERECO,
	F.NUMERO,
	F.COMPLEMENTO,
	F.BAIRRO,
	F.CEP,
	F.TELEFONE,
	F.FAX,
	F.EMAIL,
	F.REPRESENTANTE AS CONTATO,
	F.TELEFONE_REPRESENTANTE1 AS CELULAR,
	F.OBSERVACAO AS OBSERVACOES,
	M.NOME AS CIDADE,
	M.UF 
FROM
	FORNECEDOR F
LEFT JOIN MUNICIPIO M ON M.MUNICIPIO_ID = F.CODIGO_MUNICIPIO  	