SELECT
	P.PRODUTO_ID AS CODIGO,
	P.DESCRICAO,
	P.COD_BARRA AS BARRAS,
	P.COD_DISTRIBUIDOR AS COD_FABRICANTE,
	P.QUANT_ESTOQUE AS QTD,
	P.ESTOQUE_MINIMO AS QTD_IDEAL,
	P.UNIDADE AS UND,
	P.DESCONTO_MAX,
	P.REFERENCIA AS PERSONAL1,
	P.CUSTO AS PRECO_CUSTO,
	P.MARGEM_VAREJO AS MARGEM_LUCRO,
	P.VALOR_VAREJO AS PRECO_VENDA,
	P.PORCENTAGEM_COMISSAO AS COMISSAO,
	P.NCM AS COD_NCM,
	LEFT (P.CFOP_DENTRO,3) AS ELO,
	P.ORIGEM AS OST,
	P.CST_ICMS AS ST,
	P.ALIQUOTA_ICMS_DENTRO AS PERSONAL2,
	P.CST_IPI AS IPI_CODIGO_VENDA,
	P.ALIQUOTA_IPI AS ALIQ_IPI_VENDA,
	P.CST_PIS AS PIS_CODIGO,
	P.ALIQUOTA_PIS AS PIS_ALIQ_NOR,
	P.CST_COFINS AS COFINS_CODIGO,
	P.ALIQUOTA_COFINS AS COFINS_ALIQ_NOR,	
	CASE P.EXCLUIDO WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	P.VALOR_ATACADO AS PRECO_ATACADO,
	P.IPI AS ALIQ_IPI,
	P.PIS AS PISE_ALIQ_NOR,
	P.COFINS AS COFINSE_ALIQ_NOR,
	P.CEST AS PERSONAL6,
	P.CPRODANP AS COD_ANP,
	F.RAZAO_SOCIAL AS FORNCEDOR,
	M.NOME AS CARACTERISTICAS,
	G.GRUPO,
	S.SUBGRUPO AS FAMILIA
FROM
	PRODUTO P
LEFT JOIN FORNECEDOR F ON F.FORNECEDOR_ID = P.ID_FORNECEDOR
LEFT JOIN MARCA M ON M.MARCA_ID = P.ID_MARCA
LEFT JOIN GRUPO G ON G.GRUPO_ID = P.ID_GRUPO
LEFT JOIN SUBGRUPO S ON S.SUBGRUPO_ID = P.ID_SUBGRUPO