SELECT Cli_For.Código as CODIGO,
Cli_For.Nome,
Cli_For.Fantasia,
Cli_For.[Endereço] AS ENDERECO,
Cli_For.Complemento,
Cli_For.Bairro,
Cli_For.Cidade,
Cli_For.Estado AS UF,
Cli_For.CEP,
Cli_For.CGC AS CNPJ_CNPF,
Cli_For.[Inscrição] AS IE_RG,
Cli_For.Fone_1 AS TELEFONE,
Cli_For.Fone_2 AS CELULAR,
Cli_For.Fax,
Cli_For.[Comentários] AS OBSERVACOES,
Cli_For.[Endereço_Cob] AS COB_ENDERECO,
Cli_For.Complemento_Cob AS COB_COMPLEMENTO,
Cli_For.Bairro_Cob AS COB_BAIRRO,
Cli_For.Cidade_Cob AS COB_CIDADE,
Cli_For.Estado_Cob AS COB_UF,
Cli_For.CEP_Cob AS COB_CEP,
Cli_For.email,
Cli_For.Data_Cadastro AS CADATRO
FROM Cli_For
WHERE Cli_For.[Código]>0 AND Cli_For.Tipo='F'
