SELECT
    PESSOAS.RAZAO_SOCIAL AS NOME,
    PESSOAS.NOME_FANTASIA AS FANTASIA,
    CIDADE.NOME_CIDADE AS CIDADE,
    BAIRRO.NOME_BAIRRO AS BAIRRO,
    PESSOAS.CEP,
    PESSOAS.ENDERECO,
    PESSOAS.NUMERO,
    PESSOAS.COMPLEMENTO,
    PESSOAS.TELEFONE,
    PESSOAS.FAX,
    PESSOAS.CELULAR,
    PESSOAS.CPF_CNPJ AS CNPJ_CNPF,
    PESSOAS.RG_INSCESTADUAL AS IE_RG,
    PESSOAS.EMAIL
FROM PESSOAS
LEFT JOIN CIDADE ON PESSOAS.ID_CIDADE = CIDADE.ID_CIDADE
LEFT JOIN BAIRRO ON PESSOAS.ID_BAIRRO = BAIRRO.ID_BAIRRO
WHERE PESSOAS.FORNECEDOR ='1'