SELECT
    PRODUTOS.COD_ITEM AS CODIGO,
    PRODUTOS.COD_BARRA AS BARRAS,
    PRODUTOS.DESCR_ITEM AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.COD_NCM AS COD_NCM,
    GRUPOS.DESCRICAO AS GRUPO,
    PRODUTOS.CST_ICMS AS ST,
    PRODUTOS.CUSTO AS PRECO_CUSTO,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.PR_AVISTA AS PRECO_VENDA,
    PRODUTOS.SALDO AS QTD
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.GRUPO = GRUPOS.CODIGO