SELECT TBCLIENTE.PKCODCLI AS CODIGO,
CAST(TBCLIENTE.DATACAD AS DATE) AS CADASTRO,
TBCLIENTE.RAZAOSOCIAL AS NOME,
TBCLIENTE.NOMEFANTASIA AS FANTASIA,
TBCLIENTE.ENDERECO,
TBCLIENTE.NUM AS NUMERO,
TBCLIENTE.COMP AS COMPLEMENTO,
TBCLIENTE.CEP AS CEP,
TBCLIENTE.BAIRRO,
TBCIDADE.NMCID AS CIDADE,
TBCIDADE.UFCID AS UF,
TBCLIENTE.FONE1 AS TELEFONE,
TBCLIENTE.FAX,
TBCLIENTE.CNPJCPF AS CNPJ_CNPF,
TBCLIENTE.INSCESTRG AS IE_RG,
TBCLIENTE.EMAIL
FROM TBCLIENTE
LEFT JOIN TBCIDADE ON TBCLIENTE.FKCODCID=TBCIDADE.PKCODCID

