SELECT 
  C.CODIGO
, C.NOME AS FANTASIA
--, CAST (C.DATACADASTRO AS DATE) AS CADASTRO
, C.RAZAOSOCIAL AS NOME
, C.LIMITE AS LIMITE_CREDITO
, C.ENDERECO
, C.NUMERO
, C.PONTOREFERENCIA AS COMPLEMENTO
, C.CEP
, C.BAIRRO
, C.UF
, C.FONE AS TELEFONE
, C.FAX
, C.CONTATO
, C.CNPJCPF
, CASE WHEN C.RGCLIENTE = '' OR C.RGCLIENTE IS NULL THEN C.CGFRG ELSE C.RGCLIENTE END AS IE_RG
, C.EMAIL
, CAST (C.NASCIMENTORESPONSAVEL AS DATE) AS NASCIMENTO
, C.MAERESPONSAVEL AS MAE
, C.OBS AS OBSERVACOES
, CAST (C.DATACOMPRA AS DATE) AS ULTIMA_VENDA
, C.VALORCREDITO AS LIMITE_CREDITO
, C.ENDERECOCOBRANCA AS COB_ENDERECO
, C.CEPCOBRANCA AS COB_CEP
, C.BAIRROCOBRANCA AS COB_BAIRRO
, C.UFCOBRANCA AS COB_UF
, C.FONECOBRANCA AS CELULAR
, CI.CIDADE
, CIC.CIDADE AS COB_CIDADE
FROM CLIENTES C
LEFT JOIN CIDADES CI ON CI.CODIGO = C.CIDADE 
LEFT JOIN CIDADES CIC ON CIC.CODIGO = C.CIDADECOBRANCA 
