SELECT 
  F.CODIGO 
, F.RAZAOSOCIAL AS NOME
, F.FANTASIA
, F.ENDERECO
, F.CEP
, F.BAIRRO
, F.UF
, F.FONE AS TELEFONE
, F.FAX
, F.CNPJCPF AS CNPJ_CNPF
, F.CGFRG AS IE_RG
, F.CONTATO
, F.CELULAR
, F.OBS AS OBSERVACOES
, F.EMAIL
, CI.CIDADE
FROM FORNECEDORES F
LEFT JOIN CIDADES CI ON CI.CODIGO = F.CIDADE
