SELECT
FORNECEDORES.CODIGO
,FORNECEDORES.CNPJ AS CNPJ_CNPF
,FORNECEDORES.INSCRICAOEST AS IE
,FORNECEDORES.NOME
,FORNECEDORES.FANTASIA
,FORNECEDORES.ENDERECO
,FORNECEDORES.NUMERO
,FORNECEDORES.BAIRRO
,CIDADES.CIDADE
,CIDADES.UF
,FORNECEDORES.CEP
,FORNECEDORES.COMPLEMENTO
,FORNECEDORES.FONE AS TELEFONE
,FORNECEDORES.FAX
,FORNECEDORES.CONTATO
,FORNECEDORES.EMAIL
,FORNECEDORES.OBSERVACOES AS OBSERVACOES
,FORNECEDORES.FONE2 AS CELULAR
FROM FORNECEDORES
LEFT JOIN CIDADES ON FORNECEDORES.CEP=CIDADES.CEP
