SELECT 
  P.CODLIN AS CODIGO
--  P.COD_PRODUTO AS CODIGO
, P.CODPRD AS COD_FABRICANTE
--, P.REFFAB AS COD_FABRICANTE
--, P.QTDCAIXA AS FAT_CONV
, P.COMISSAO
, E.ATUAL AS QTD
, CAST(E.ENTRADA1 AS DATE) AS DATA_CADASTRO
, CAST(E.DT_ENT AS DATE) AS ULTIMA_COMPRA
, CAST(E.DT_SAI AS DATE) AS ULTIMA_VENDA
, CASE E.ATIVOVENDA WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, E.MINIMO AS QTD_IDEAL
, E.PESO
, E.CFOP_VENDA AS CF
, LEFT (E.CFOP_VENDA,3) AS ELO
, E.CST_ICMS AS ST
, E.CST_PIS AS PIS_CODIGO
, E.CST_COFINS AS COFINS_CODIGO
, E.CST_IPI AS IPI_CODIGO
, E.IPI AS ALIQ_IPI
, E.PIS AS PIS_ALIQ_NOR
, E.COFINS AS COFINS_ALIQ_NOR
--, P.PIS
--, P.COFINS
--, P.IPI
, E.PRECOATACADO AS PRECO_ATACADO
, E.PRECOCOMPRA AS PRECO_CUSTO
, E.PRECOVENDA AS PRECO_VENDA
, E.PRECOVENDA2 AS PERSONAL2
, E.MARGEM AS MARGEM_LUCRO
, L.NOMLIN AS DESCRICAO
, L.UND
, L.NCM AS COD_NCM
, L.OBSLINHA AS OBSERVACOES
, L.CODCEST AS PERSONAL6
, MR.DESCRI AS FORNECEDOR
, S.NOMSEG AS FAMILIA
, G.DESGRP AS GRUPO
, MAX (C.BARRA_CODIGO) AS BARRAS
FROM ESTOQ E
INNER JOIN PRODTO P ON (E.CODPRD = P.CODPRD)
INNER JOIN LINHAS L ON (E.CODLIN = L.CODLIN)
INNER JOIN MARCAS MR ON (L.CODMAR = MR.CODMAR)
INNER JOIN SEGMENTO S ON (L.CODSEG = S.CODSEG)
LEFT OUTER JOIN GRUPOS G ON (L.CODGRP = G.CODGRP)
LEFT JOIN CODIGODEBARRA C ON (C.CODPRD = P.CODPRD)
GROUP BY P.CODLIN, P.CODPRD, P.COMISSAO, E.ATUAL, E.ENTRADA1, E.DT_ENT, E.DT_SAI, E.ATIVOVENDA,
         E.MINIMO, E.PESO, E.CFOP_VENDA, LEFT(E.CFOP_VENDA,3), E.CST_ICMS, E.CST_PIS, E.CST_COFINS,
         E.CST_IPI, E.IPI, E.PIS, E.COFINS, E.PRECOATACADO, E.PRECOCOMPRA, E.PRECOVENDA, E.PRECOVENDA2,
         E.MARGEM, L.NOMLIN, L.UND, L.NCM, L.OBSLINHA, L.CODCEST, MR.DESCRI, S.NOMSEG, G.DESGRP
