SELECT
    IDPRODUTO AS CODIGO,
    COD_BARRA AS BARRAS,
    DESCRICAO,
    UNIDADE AS UND,
    ESTOQUE_ATUAL AS QTD,
    PRECO_CUSTO,
    MLV AS MARGEM_LUCRO,
    VR_AVISTA AS PRECO_VENDA,
    FABRICANTE AS FAMILIA,
    GRUPO,
    NCM AS COD_NCM,
    COD_PROD_FORN AS COD_FABRICANTE,
    CEST AS PERSONAL6
FROM PRODUTO
