SELECT
    ITENS.ID_ITEM AS COPDIGO,
    ITENS.CODIGO AS COD_FABRICANTE,
    ITENS.CODIGO_BARRAS AS BARRAS,
    ITENS.DESCRICAO AS DESCRICAO,
    ITENS.UNIDADE AS UND,
    SUBSTRING (ITENS.ST FROM 1 FOR 1) AS OST,
    SUBSTRING (ITENS.ST FROM 2 FOR 3) AS ST,
    ITENS.CF AS COD_NCM,
    GRUPOS.NOME AS GRUPO,
    SUBGRUPOS.NOME AS FAMILIA,
    ITENS.PESO_LIQUIDO AS PESO,
    ITENS.ESTOQUE AS QTD,
    ITENS.ESTOQUE_MINIMO AS QTD_IDEAL,
    ITENS.PRECO_CUSTO AS PRECO_CUSTO,
    ITENS.PRECO_VENDA AS PRECO_VENDA,
    ITENS.MARGEM_LUCRO AS MARGEM_LUCRO,
    ITENS.CODIGO_EXTERNO AS CARACTERISTICAS,
    ITENS.ULTIMA_COMPRA AS ULTIMA_COMPRA,
    ITENS.MARCA AS OBSERVACOES,
    ITENS.CEST AS PERSONAL6
FROM ITENS
LEFT JOIN grupos ON GRUPOS.id_grupo = ITENS.ID_GRUPO
LEFT JOIN subgrupos ON SUBGRUPOS.id_subgrupo = ITENS.ID_SUBGRUPO
