select
  SUBSTRING (P.CODIGO FROM 8 FOR 14) AS CODIGO
, P.CODIGO AS COD_FABRICANTE
, P.DESCRICAO
, P.CUSTO AS PRECO_CUSTO
, P.LUCRO_PERC AS MARGEM_LUCRO
, P.VENDA AS PRECO_VENDA
, P.EST_MINIMO AS QTD_IDEAL
, P.ICMS AS ELO
, P.UNIDADE AS UND
, CASE P.EXCLUIDO WHEN 'N' THEN 'Ativo' else 'Inativo' end AS SITUACAO
, P.TIPO_PRODUCAO AS IPPT
, P.PERC_IPI AS ALIQ_IPI_VENDA
, P.GTIN AS BARRAS
, P.PESO
, IP.ncm AS COD_NCM
, IP.csosn AS ST
, IP.origem AS OST
, IP.cst_ipi AS IPI_CODIGO_VENDA
, IP.cst_pis AS PIS_CODIGO
, IP.cst_cofins AS COFINS_CODIGO
, IP.p_ipi AS ALIQ_IPI_VENDA
, IP.p_pis AS PIS_ALIQ_NOR
, IP.p_cofins AS COFINS_ALIQ_NOR
, E.quantidade AS QTD
, C.descricao AS GRUPO
FROM PRODUTO P
LEFT JOIN imposto_produto IP ON IP.cod_produto = P.codigo
LEFT JOIN estoque E ON E.cod_produto= P.codigo
LEFT JOIN categoria c ON c.codigo = P.cod_categoria
--WHERE COD_EMPRESA=1
