SELECT
    PESSOA.CODPESSOA AS CODIGO,
    PESSOA.PES_NOME AS NOME,
    PESSOA.PES_RAZAO_SOCIAL AS FANTASIA,
    PESSOA.PES_CPFCNPJ AS CNPJ_CNPF,
    case when PESSOA.PES_IE = '' or PESSOA.PES_IE is null then PESSOA.PES_RG else PESSOA.PES_IE END AS IE_RG,
    PESSOA.PES_IM AS IM,
    PESSOA.PES_ENDERECO AS ENDERECO,
    PESSOA.PES_ENDERECO_NUMERO AS NUMERO,
    PESSOA.PES_ENDERECO_COMPLEMENTO AS COMPLEMENTO,
    PESSOA.PES_BAIRRO AS BAIRRO,
    PESSOA.PES_CIDADE AS CIDADE,
    PESSOA.PES_UF AS UF,
    PESSOA.PES_CEP AS CEP,
    PESSOA.PES_TELEFONE_DDD ||' '|| PESSOA. PES_TELEFONE AS TELEFONE,
    PESSOA.PES_FAX_DDD ||' '|| PESSOA. PES_FAX AS FAX,
    PESSOA.PES_CELULAR_DDD ||' '|| PESSOA. PES_CELULAR AS CELULAR,
    PESSOA.PES_CONTATOS AS CONTATO,
    PESSOA.PES_EMAIL AS EMAIL,
    PESSOA.PES_OBS AS OBSERVACOES
FROM PESSOA
WHERE PESSOA.PES_CLASS_FOR = 'S'
