SELECT
    PESSOA.CODIGO AS CODIGO,
    PESSOA.NOME AS NOME,
    PESSOA.FANTASIA AS FANTASIA,
    PESSOA.CNPJ_CPF AS CNPJ_CNPF,
    case when PESSOA.INSCR_EST = '' or PESSOA.INSCR_EST is null then PESSOA.RG else PESSOA.INSCR_EST END AS IE_RG,
    PESSOA.INSC_MUNICIPAL AS IM,  
    PESSOA.ENDERECO AS ENDERECO,
    PESSOA.COMPLEMENTO_END AS COMPLEMENTO,
    PESSOA.NUM_END AS NUMERO,
    PESSOA.BAIRRO AS BAIRRO,
    PESSOA.CIDADE AS CIDADE,
    PESSOA.UF AS UF,
    PESSOA.CEP AS CEP,
    PESSOA.TELEFONE1 AS TELEFONE,
    PESSOA.DDDFAX ||''|| PESSOA.FAX AS FAX,
    PESSOA.DDDCELULAR ||''|| PESSOA.CELULAR AS CELULAR,
    PESSOA.OBS AS OBSERVACOES,
    PESSOA.EMAIL_NFE AS EMAIL,   
    PESSOA.NOME_CONTATO AS CONTATO
FROM PESSOA
WHERE PESSOA.TP_FORNECEDOR = 'S'
