SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.NOME AS DESCRICAO,
    PRODUTO.COD_BARRA AS BARRAS,
    PESSOA.nome AS FORNECEDOR,
    GRUPO.NOME AS GRUPO,
    SUBGRUPO.nome AS FAMILIA,
    PRODUTO.PESOLIQUIDO AS PESO,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.QTD_ESTOQUE_MIN AS QTD_IDEAL,
    ESTOQUE_ATUAL.QTD AS QTD,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO.PERC_MARGEMLUCRO AS MARGEM_LUCRO,
    PRODUTO.PRECO_VENDA AS PRECO_VENDA,
    PRODUTO.ORIGEM_PROD AS OST,
    TAB_CSTICMS.COD_CST AS ST,
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.DTCAD AS DATA_CADASTRO,
    PRODUTO.DT_ALTPRECO AS ALTERACAO_PRECO,
    TAB_NCM.NCM AS COD_NCM,
    PRODUTO.COD_CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN grupo ON GRUPO.id = PRODUTO.ID_GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.id = PRODUTO.ID_SUBGRUPO
LEFT JOIN pessoa ON PESSOA.codigo = PRODUTO.ID_FORNECEDOR
LEFT JOIN TAB_NCM ON TAB_NCM.id = PRODUTO.ID_NCM
LEFT JOIN TAB_CSTICMS ON TAB_CSTICMS.id = PRODUTO.ID_CSTICMS
LEFT JOIN estoque_atual ON ESTOQUE_ATUAL.id_produto = PRODUTO.ID
where estoque_atual.filial = '1' and ESTOQUE_ATUAL.ID_LOCAL_ESTOQUE = '1'
