SELECT
    TBCLI.CODCLI AS CODIGO,
    TBCLI.NOME AS NOME,
    TBCLI.APELIDIO AS FANTASIA,
    TBCLI.NUMERO AS NUMERO,
    TBCLI.COMPLEMENTO AS COMPLEMENTO,
    TBCLI.FONE AS TELEFONE,
    TBCLI.CELULAR AS CELULAR,
    TBCLI.CPF AS CNPJ_CNPF,
    TBCLI.RG AS IE_RG,
    TBCLI.DTCAD AS CADASTRO,
    TBCLI.EMAIL AS EMAIL,
    TBCLI.DTNASC AS NASCIMENTO,
    TBCLI.OBS AS OBSERVACOES,
    TBCLI.ENDERECO AS ENDERECO,
    TBCLI.BAIRRO AS BAIRRO,
    TBCLI.CEP AS CEP,
    TBCLI.UF AS UF,
    TBCIDADE.DESCRICAO AS CIDADE
FROM TBCLI
LEFT JOIN TBCIDADE ON TBCLI.CODCIDADEI = TBCIDADE.CODIGO
