SELECT
    TBFOR.CODFOR AS CODIGO,
    TBFOR.NOME AS NOME,
    TBFOR.APELIDIO AS FANTASIA,
    TBFOR.ENDERECO AS ENDERECO,
    TBFOR.COMPLEMENTO AS COMPLEMENTO,
    TBFOR.CEP AS CEP,
    TBFOR.BAIRRO AS BAIRRO,
    TBFOR.CIDADE AS CIDADE,
    TBFOR.UF AS UF,
    TBFOR.FONE AS TELEFONE,
    TBFOR.FAX AS FAX,
    TBFOR.CELULAR AS CELULAR,
    TBFOR.EMAIL AS EMAIL,
    TBFOR.RG AS IE_RG,
    TBFOR.CNPJ AS CNPJ_CNPF,
    TBFOR.NUMERO AS NUMERO
FROM TBFOR
