SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    case when REPLACE(replace(replace(CPF,'-',''),'.',''),'/','') = '' or REPLACE(replace(replace(CPF,'-',''),'.',''),'/','') is null then REPLACE(replace(replace(CGC,'-',''),'.',''),'/','') else REPLACE(replace(replace(CPF,'-',''),'.',''),'/','') END AS CNPJ_CNPF,
    case when RG = '' or RG is null then INSC_EST else RG END AS IE_RG,
    CONTATO AS CONTATO,
    ENDERECO AS ENDERECO,
    COMPLEMENTO AS COMPLEMENTO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    CELULAR AS CELULAR,
    EMAIL AS EMAIL,
    LIMITE AS LIMITE_CREDITO,
    SEXO AS SEXO,
    ESTADO_CIVIL AS EST_CIVIL,
    OBS AS OBSERVACOES,
    DATA_NASCIMENTO AS NASCIMENTO,
    DATA_CADASTRO AS CADASTRO
FROM CLIENTES