SELECT
    PRODUTOS.CODIGO AS CODIGO,
    GRUPOS.GRUPO AS GRUPO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.UN_ENTRADA AS UND_COMPRA,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.QTD_MINIMA AS QTD_IDEAL,
    PRODUTOS.QUANTIDADE AS QTD,
    PRODUTOS.CUSTO AS PRECO_CUSTO,
    PRODUTOS.LUCRO AS MARGEM_LUCRO,
    PRODUTOS.VENDA AS PRECO_VENDA,
    PRODUTOS.TRIBUTO AS ST,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.OBS AS OBSERVACOES,
    PRODUTOS.ULTIMA_COMPRA AS ULTIMA_COMPRA,
    PRODUTOS.ULTIMA_VENDA AS ULTIMA_VENDA,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.CD_GRUPO =  PRODUTOS.CD_GRUPO