SELECT
    TBPRODUTO.PROD_CODIGO AS CODIGO,
    TBPRODUTO.PROD_COD1 AS COD_FABRICANTE,
    TBPRODUTO.PROD_CODBARRAS AS BARRAS,
    TBPRODUTO.PROD_NOME AS DESCRICAO,
    TBPRODUTO.PROD_PRECOVENDA AS PRECO_VENDA,
    TBPRODUTO.PROD_PRECOCUSTO AS PRECO_CUSTO,
    TBPRODUTO.PROD_PESOBRUTO AS PESO,
    TBPRODUTO.PROD_CSOSN AS ST,
    CASE TBPRODUTO.PROD_ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
    TBPRODUTO.PROD_COMISSAO AS COMISSAO,
    TBPRODUTO.PROD_MARGEM AS MARGEM_LUCRO,
    TBPRODUTO.PROD_NCM AS COD_NCM,
    TBPRODUTO.PROD_UNID AS UND,
    TBPRODUTO.PROD_ESTOQMINIMO AS QTD_IDEAL,
	TBPRODUTO.PROD_FATORCONVERSAO AS FAT_CONV,
    TBPRODUTO.PROD_CODBARRAS2 AS PERSONAL1,
    TBPRODUTO.PROD_CEST AS PERSONAL6,
    TBPRODUTO.PROD_PRECOPRAZO AS PERSONAL2,
    TBPRODUTO.PROD_ESTOQUE AS QTD,
    TBPRODUTO.PROD_OBS AS OBSERVACOES,
    LEFT (TBPRODUTO.PROD_CFOP,3) AS ELO, 
    TBPESSOA.PES_NOME AS FORNECEDOR,
    GRU.ARQ_NOME AS GRUPO,
    CAT.ARQ_NOME AS FAMILIA,
    TIP.ARQ_REF AS TIPO_ITEM
FROM TBPRODUTO
LEFT JOIN TBPESSOA ON TBPESSOA.PES_CODIGO = TBPRODUTO.PROD_CODFORNECEDOR 
LEFT JOIN TBARQUIVO00 GRU ON GRU.ARQ_CODSEQ = TBPRODUTO.PROD_CODGRUPO AND GRU.ARQ_TABELA = 'GRUPO_PRODUTO'
LEFT JOIN TBARQUIVO00 CAT ON CAT.ARQ_CODSEQ = TBPRODUTO.PROD_CODCATEGORIA AND CAT.ARQ_TABELA = 'CATEGORIA'
LEFT JOIN TBARQUIVO00 TIP ON TIP.ARQ_CODSEQ = TBPRODUTO.PROD_CODTIPOITEM AND TIP.ARQ_TABELA = 'TIPO_ITEM'
