SELECT
       CADPRO.TP AS CARACTERISTICAS
      ,CADPRO.BARRA AS BARRAS
      ,CADPRO.DESCR AS DESCRICAO
      ,CADPRO.UNID AS UND
      ,CADPROG.DESCR AS GRUPO
      ,CADPROL.DESCR AS FAMILIA
      ,CADPRO.PTAB1 AS PRECO_VENDA
      ,CADFOR.RAZAO AS FORNECEDOR
      ,CADPRO.REFAB AS COD_FABRICANTE
      ,CADPRO.NCM AS COD_NCM
      ,CADPRO.DTCAD AS DATA_CADASTRO
      ,CADPRO.PESO AS PESO
      ,CADPRO.CEST AS PERSONAL6
  FROM EasyLinx.dbo.CADPRO
  LEFT JOIN EasyLinx.dbo.CADPROG ON CADPROG.PRODUG = CADPRO.GRUPO
  LEFT JOIN EasyLinx.dbo.CADPROL ON CADPROL.PRODUL = CADPRO.LINHA
  LEFT JOIN EasyLinx.dbo.CADFOR ON CADFOR.FORNE = CADPRO.FORNE