SELECT
  E.CODIGO
, E.RAZAO_SOCIAL AS NOME
, E.FANTASIA
, CASE WHEN E.CPF = '' OR E.CPF IS NULL OR E.CPF = '99999999999' THEN E.CNPJ ELSE E.CPF END AS CNPJ_CNPF
, E.INSCRICAO_ESTADUAL AS IE_RG
, E.INSCRICAO_MUNICIPAL AS IM
, E.CEP
, E.LOGRADOURO AS ENDERECO
, E.NUMERO
, E.COMPLEMENTO
, E.REFERENCIA AS PERSONAL1
, E.BAIRRO
, E.EMAIL
, E.TELEFONE
, E.CELULAR
, E.FAX
, E.OBSERVACAO AS OBSERVACOES
, C.DESCRICAO AS CIDADE
, U.ABREVIATURA AS UF
FROM ENTIDADE E
LEFT JOIN CIDADE C ON C.CIDADE_ID = E.CIDADE_ID 
LEFT JOIN UF U ON U.UF_ID = C.UF_ID 
WHERE E.FORNECEDOR IS TRUE
