SELECT
  E.CODIGO
, E.RAZAO_SOCIAL
, E.CNPJ
, E.INSCRICAO_ESTADUAL AS IE
, E.LOGRADOURO||', '||E.NUMERO||', '||E.COMPLEMENTO||', '||E.BAIRRO||', '||E.CEP||', '||E.REFERENCIA AS ENDERECO
, E.EMAIL
, E.TELEFONE
, C.DESCRICAO AS CIDADE
, U.ABREVIATURA AS UF
FROM ENTIDADE E
LEFT JOIN CIDADE C ON C.CIDADE_ID = E.CIDADE_ID 
LEFT JOIN UF U ON U.UF_ID = C.UF_ID 
WHERE E.TRANSPORTADOR IS TRUE
