SELECT
    PES_CODIGO AS CODIGO,
    PES_NOME AS NOME,
    PES_FANTASIA AS FANTASIA,
    PES_CONTATO AS CONTATO,
    case when PES_CPF = '' or PES_CPF is null then PES_CGC else PES_CPF END AS CNPJ_CNPF,
    case when PES_RG = '' or PES_RG is null then PES_IE else PES_RG END AS IE_RG,
    PES_IM AS IM,
    PES_ENDERECO AS ENDERECO,
    PES_PONTOREFERENCIA AS COMPLEMENTO,
    PES_BAIRRO AS BAIRRO,
    PES_CIDADE AS CIDADE,
    PES_CEP AS CEP,
    PES_UF AS UF,
    PES_FONE AS TELEFONE,
    PES_FAX AS FAX,
    PES_EMAIL AS EMAIL,
    PES_OBS AS OBSERVACOES
FROM PESSOAS
WHERE PES_FORNECEDOR = 'S'