SELECT
    PRODUTOS.PROD_CODIGO AS CODIGO,
    PRODUTOS.PROD_NOME AS DESCRICAO,
    PRODUTOS.UN_CODIGO AS UND,
    SUBGRUPOS.SUBG_NOME AS GRUPO,
    MODELOS.MOD_NOME AS CARACTERISTICAS,
    MAX (PRODUTOS_FORNECEDORES.PRODF_REFERENCIA) AS BARRAS,
    PRODUTOS.PROD_PESOLIQUIDO AS PESO,
    PRODUTOS.PROD_MINIMO AS QTD_IDEAL,
    MAX (MOVIMENTO_ESTOQUE.esto_quantidade) AS QTD,
    PRODUTOS.PROD_COMPRA AS PRECO_CUSTO,
    PRODUTOS.PROD_VENDA AS PRECO_VENDA,
    PRODUTOS.PROD_BUSCA AS OBSERVACOES,
    PRODUTOS.PROD_REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.PROD_NCM_NUMERO AS COD_NCM,
    PRODUTOS.PROD_CEST_NUMERO AS PERSONAL6
FROM PRODUTOS
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.SUBG_CODIGO = PRODUTOS.SUBG_CODIGO
LEFT JOIN MODELOS ON MODELOS.mod_codigo = PRODUTOS.MOD_CODIGO
LEFT JOIN produtos_fornecedores ON produtos_fornecedores.prod_codigo = PRODUTOS.PROD_CODIGO
LEFT JOIN MOVIMENTO_ESTOQUE ON MOVIMENTO_ESTOQUE.prod_codigo = PRODUTOS.PROD_CODIGO
GROUP BY 1,2,3,4,5,7,8,10,11,12,13,14,15