SELECT CLIENTES.CODIGO,
CLIENTES.RAZAO AS NOME,
CLIENTES.FANTASIA,
CLIENTES.ENDERECO,
CLIENTES.NUMERO,
CLIENTES.BAIRRO,
CLIENTES.CNPJCPF AS CNPJ_CNPF,
CLIENTES.IERG AS IE_RG,
MUNICIPIOS.NOME AS CIDADE,
CLIENTES.UF,
CLIENTES.DDDFONE||CLIENTES.FONE AS TELEFONE,
CLIENTES.DDDCEL||CLIENTES.CEL AS CELULAR,
CLIENTES.DTCAD AS CADASTRO,
CLIENTES.CEP,
CLIENTES.DDDFAX||CLIENTES.FAX AS FAX,
CLIENTES.OBS AS OBSERVACOES,
CLIENTES.EMAIL,
CLIENTES.COMPENDERECO AS COMPLEMENTO,
CLIENTES.DTNASC AS NASCIMENTO
FROM CLIENTES
LEFT JOIN MUNICIPIOS ON CLIENTES.MUNICIPIO=MUNICIPIOS.CODIGOIBGE



