SELECT
    PRODUTOS.CODIGO_PRODUTO AS CODIGO,
    GRUPOS_PRODUTO.descricao AS GRUPO,
    subgrupos_produto.descricao AS FAMILIA,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    FORNECEDORES.razao_social AS FORNECEDOR,
    PRODUTOS_SALDO.saldo_atual AS QTD,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.CUSTO_COMPRA AS PRECO_CUSTO,
    PRODUTOS.UNIDADE_ENTRADA AS UND_COMPRA,
    PRODUTOS.UNIDADE_SAIDA AS UND, 
    PRODUTOS.PESO AS PESO,  
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    SUBSTRING (PRODUTOS.CST FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.CST FROM 2 FOR 3) AS ST,   
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,   
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN grupos_produto ON grupos_produto.codigo_grupo = PRODUTOS.CODIGO_GRUPO
LEFT JOIN subgrupos_produto ON grupos_produto.codigo_grupo = subgrupos_produto.codigo_grupo and subgrupos_produto.codigo_subgrupo = PRODUTOS.CODIGO_SUBGRUPO
LEFT JOIN PRODUTOS_SALDO ON PRODUTOS_SALDO.codigo_produto = PRODUTOS.CODIGO_PRODUTO
LEFT JOIN FORNECEDORES ON FORNECEDORES.codigo_fornecedor = PRODUTOS.CODIGO_FORNECEDOR
