SELECT V_CONSULTA_DADOS_CLIENTE.CLIFOR AS CODIGO,
V_CONSULTA_DADOS_CLIENTE.NOME_FANTASIA AS FANTASIA,
V_CONSULTA_DADOS_CLIENTE.CGC_CPF AS CNPJ_CNPF,
V_CONSULTA_DADOS_CLIENTE.RAZAO_SOCIAL AS NOME,
V_CONSULTA_DADOS_CLIENTE.RG_IE AS IE_RG,
V_CONSULTA_DADOS_CLIENTE.CEP,
V_CONSULTA_DADOS_CLIENTE.ENDERECO,
V_CONSULTA_DADOS_CLIENTE.EndNumero AS NUMERO,
V_CONSULTA_DADOS_CLIENTE.BAIRRO,
V_CONSULTA_DADOS_CLIENTE.CIDADE,
V_CONSULTA_DADOS_CLIENTE.UF,
V_CONSULTA_DADOS_CLIENTE.TELEFONE1 AS TELEFONE,
V_CONSULTA_DADOS_CLIENTE.FAX,
V_CONSULTA_DADOS_CLIENTE.CONTATO,
V_CONSULTA_DADOS_CLIENTE.CADASTRAMENTO AS CADASTRO,
V_CONSULTA_DADOS_CLIENTE.EMAIL,
V_CONSULTA_DADOS_CLIENTE.CELULAR,
V_CONSULTA_DADOS_CLIENTE.OBS AS OBSERVACOES
FROM V_CONSULTA_DADOS_CLIENTE
WHERE V_CONSULTA_DADOS_CLIENTE.INDICA_CLIENTE=1


