SELECT
    PESSOAS.CODIGO AS CODIGO,
    PESSOAS.NOME AS NOME,
    PESSOAS.APELIDO AS FANTASIA,
    PESSOAS.ENDERECO AS ENDERECO,
    PESSOAS.NUMERORUA AS NUMERO,
    PESSOAS.BAIRRO AS BAIRRO,
    PESSOAS.COMPLEMENTO AS COMPLEMENTO,
    CIDADE.CIDADE AS CIDADE,
    CIDADE.ESTADO AS UF, 
    PESSOAS.FONE01 AS TELEFONE,
    PESSOAS.FONE02 AS CELULAR,
    PESSOAS.CONTATO AS CONTATO,
    PESSOAS.CPFCNPJ AS CNPJ_CNPF,
    PESSOAS.RGIE AS IE_RG,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.CEP AS CEP,
    PESSOAS.INSCRICAOMUNICIPAL AS IM
FROM PESSOAS
LEFT JOIN CIDADE ON CIDADE.CODIGO = PESSOAS.CIDADE
WHERE PESSOAS.FORNECEDOR = '1'
