SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.CODIGOBARRAS AS BARRAS,
    PRODUTOS.UNIDADE AS UND_COMPRA,
    PRODUTOS.UNSAIDA AS UND,
    PRODUTOS.PESO AS PESO,
    PRODUTO_ESTOQUE.ESTOQUE AS QTD,
    PRODUTOS.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTOS.PRECO AS PRECO_VENDA,
    PRODUTOS.PRECOATACADO AS PRECO_ATACADO,
    TRIBUTACAO.CST AS ST,
    NCM.NCM AS COD_NCM,
    CEST AS PERSONAL6,
    CAST (PRODUTOS.DATA_ATUALIZACAO AS DATE) AS ALTERACAO_PRECO,
    CAST (PRODUTOS.ULTIMACOMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (PRODUTOS.ULTIMAVENDA AS DATE) AS ULTIMA_VENDA,
    CAST (PRODUTOS.DATACADASTRO AS DATE) AS DATA_CADASTRO
FROM PRODUTOS
LEFT JOIN PRODUTO_ESTOQUE ON PRODUTO_ESTOQUE.IDPRODUTO = PRODUTOS.CODIGO
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.CODIGO = PRODUTOS.TRIBUTACAO
LEFT JOIN NCM ON NCM.CODIGO = PRODUTOS.NCM
