SELECT
	C.CODPARC AS CODIGO,
	C.NOMPARC NOME,
	C.SOBPARC AS FANTASIA,
	C.CNPPARC AS CNPJ_CNPF,
	C.REGPARC AS IE_RG,
	C.NASPARC:: DATE AS NASCIMENTO,
	C.CADPARC:: DATE AS CADASTRO,
	C.OBSPARC AS OBSERVACOES,
	C.EMAPARC AS EMAIL,
	C.VENPREF AS PERSONAL1,
	C.ULTVEND:: DATE AS ULTIMA_VENDA,
	C.LIMCRED AS LIMITE_CREDITO,
	C.ESTCIVI AS EST_CIVIL,
	CASE C.SEXPARC WHEN 'M' THEN 'M'
		WHEN 'F' THEN 'F'
		ELSE ''
	END AS SEXO,
	C.NOMEMPR AS LOCTRA,
	C.NOMCONJ AS CONJUGE,
	C.PAIPARC AS PAI,
	C.MAEPARC AS MAE,
	E.FONENDE AS TELEFONE,
	E.ENDENDE AS ENDERECO,
	E.REFEREN AS COMPLEMENTO,
	E.NUMENDE AS NUMERO,
	E.BAIENDE AS BAIRRO,
	E.CEPENDE AS CEP,
	E.CELENDE AS CELULAR,
	E.FAXENDE AS FAX, 
	E.NOMMUNI AS CIDADE,
	E.UF_ENDE AS UF
FROM TAB_PARC C
LEFT JOIN TAB_ENDE E ON E.CODPARC = C.CODPARC 
