SELECT
  PRODUTO.ID AS CODIGO,
  PRODUTO.BARRAS AS BARRAS,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.EST_MIN AS QTD_IDEAL,
  PRODUTO.ESTOQUE AS QTD,
  PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
  PRODUTO.MARKUP_LUCRO_PERC AS MARGEM_LUCRO,
  PRODUTO.PRECO_VENDA AS PRECO_VENDA,
  PRODUTO.OBS AS OBSERVACOES,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.CEST AS PERSONAL6,
  PRODUTO.ICMS_CST AS ST,
  PRODUTO.DATA_ALTERACAO AS ALTERACAO_PRECO
FROM PRODUTO
