SELECT 
  C.ID AS CODIGO
, CAST (C.DATA_CADASTRO AS DATE) AS CADASTRO
,CASE WHEN C.DF1 = '' OR C.DF1 IS NULL THEN C.CODIGO1 ELSE C.DF1 END AS CNPJ_CNPF
,CASE WHEN C.DF3 = '' OR C.DF3 = 'ISENTO' OR C.DF3 IS NULL THEN C.DF2 ELSE C.DF3 END AS IE_RG
, C.NOME
, C.APELIDO AS FANTASIA
, C.TEL1 AS TELEFONE
, C.TEL2 AS PERSONAL1
, C.FAX1 AS FAX
, C.EMAIL
, CAST (C.DATA_NASCIMENTO AS DATE) AS NASCIMENTO
, C.OBS AS OBSERVACOES
, CASE C.TIPOIE 
	WHEN '9' THEN 'N'
	WHEN '1' THEN 'C'
	WHEN '2' THEN 'I'
  END AS INDIEDEST
, CASE SX.DESCRICAO 
	WHEN 'Masculino' THEN 'M'
	WHEN 'Feminino' THEN 'F'
  END AS SEXO	
, E.CEP 
, E.LOGRADOURO AS ENDERECO
, E.NUMERO 
, E.COMPLEMENTO 
, E.BAIRRO 
, E.CIDADE 
, E.ESTADO AS UF
, E.TEL AS PERSONAL2
, CO.CELULAR 
, CO.NOME AS CONTATO
, DC.LIMITE AS LIMITE_CREDITO
FROM TB_PARCEIRO C
LEFT JOIN TB_PARCEIRO_SEXO SX ON SX.ID = C.ID_SEXO
LEFT JOIN TB_PARCEIRO_ENDERECO E ON E.ID_PARCEIRO = C.ID AND E.ID_TIPO_ENDERECO = 1
LEFT JOIN TB_PARCEIRO_CONTATO CO ON CO.ID_PARCEIRO = C.ID AND CO.TIPO =1
LEFT JOIN TB_PARCEIRO_CREDITO_DEBITO DC ON DC.IDPARCEIRO = C.ID
WHERE ID_PARCEIRO_TIPO = 1