SELECT CLIENTE.COD_CLI AS CODIGO,
CLIENTE.NOME_CLI AS NOME,
CLIENTE.ENDRES_CLI AS ENDERECO,
CLIENTE.BAIRES_CLI AS BAIRRO,
CLIENTE.CIDRES_CLI AS CIDADE,
CLIENTE.ESTRES_CLI AS UF,
CLIENTE.CEPRES_CLI AS CEP,
CLIENTE.TELRES_CLI AS TELEFONE,
CLIENTE.CNPJ_CLI AS CNPJ_CNPF,
CLIENTE.DOC_CLI AS IE_RG,
CLIENTE.PAI_CLI AS PAI,
CLIENTE.MAE_CLI AS MAE,
CLIENTE.CONJUGE_CLI AS CONJUGE,
CLIENTE.PROFISSAO_CLI AS PROFISSAO,
CLIENTE.EMPRESA_TRAB_CLI AS LOCTRA,
CLIENTE.OBS_VENDA AS OBSERVACOES,
CLIENTE.NASCIMENTO_CLI AS NASCIMENTO,
CLIENTE.DATACADASTRO_CLI AS CADASTRO,
CLIENTE.CELULAR_CLI AS CELULAR,
CLIENTE.NOME_FANTASIA AS FANTASIA,
CLIENTE.PONTO_REFERENCIA AS COMPLEMENTO,
CLIENTE.CONTATO_CLI AS CONTATO,
CLIENTE.NUMRES_CLI AS NUMERO,
CLIENTE.EMAIL_CLI AS EMAIL
FROM CLIENTE




