SELECT FORNECEDOR.COD_FOR AS CODIGO,
FORNECEDOR.RAZAO_FOR AS NOME,
FORNECEDOR.END_FOR AS ENDERECO,
FORNECEDOR.BAI_FOR AS BAIRRO,
FORNECEDOR.CID_FOR AS CIDADE,
FORNECEDOR.CEP_FOR AS CEP,
FORNECEDOR.EST_FOR AS UF,
FORNECEDOR.CNPJ_FOR AS CNPJ_CNPF,
FORNECEDOR.INSC_FOR AS IE_RG,
FORNECEDOR.TEL_FOR AS TELEFONE,
FORNECEDOR.FAX_FOR AS FAX,
FORNECEDOR.CONTATO_FOR AS CONTATO,
FORNECEDOR.NUM_FOR AS NUMERO,
FORNECEDOR.EMAIL_FOR AS EMAIL
--FORNECEDOR.FANTASIA_FOR AS FANTASIA
FROM FORNECEDOR


