SELECT PRODUTO.COD_PRO AS COD_FABRICANTE,
PRODUTO.VALOR_PRO AS PRECO_VENDA,
PRODUTO.NOME_PRO AS DESCRICAO,
--PRODUTO.CSOSN AS ST,
PRODUTO.cst_cont_est AS ST,
PRODUTO.COD_NCM,
PRODUTO.PRECO_CUSTO,
PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
UNIDADE_MEDIDA.SIGLA AS UND,
PRODUTO.OBS AS OBSERVACOES,
PRODUTO.COD_CEST AS PERSONAL6,
--FORNECEDOR.RAZAO_FOR AS FORNECEDOR,
ESTOQUE.ESTOQUE AS QTD
FROM PRODUTO
LEFT JOIN UNIDADE_MEDIDA ON PRODUTO.CODIGO_UNIDADE_SAIDA=UNIDADE_MEDIDA.CODIGO
--LEFT JOIN FORNECEDOR ON PRODUTO.COD_FOR=FORNECEDOR.COD_FOR
LEFT JOIN ESTOQUE ON PRODUTO.COD_PRO = ESTOQUE.COD_PRO

