SELECT
    ITENS.COD AS CODIGO,
    ITENS.REFER AS COD_FABRICANTE,
    ITENS.NOME AS DESCRICAO,
    ITENS.CODBAR AS BARRAS,
    ITENS.MARCA AS CARACTERISTICAS,
    ITENS.UNID AS UND,
    ITENS.QUN1 AS QTD,
    SUBSTRING (ALIQUOTAS.NOME FROM 1 FOR 1) AS ST,
    ITENS.NCM AS COD_NCM,
    ITENS.CEST AS PERSONAL6,
    ITENS.CUSTO AS PRECO_CUSTO,
    ITENS.VENDA AS PRECO_VENDA
FROM ITENS
LEFT JOIN ALIQUOTAS ON ALIQUOTAS.COD = ITENS.ALIQ
