SELECT 
  F.CODFOR AS CODIGO
, F.NOMEFOR AS NOME
, F.FANTASIAFOR AS FANTASIA
,	case when F.CPFFOR = '' or F.CPFFOR is null then F.CNPJFOR else F.CPFFOR END AS CNPJ_CNPF
,   case when F.RG = '' or F.RG is null then F.INSCESTFOR else F.RG END AS IE_RG
, F.ENDFOR AS ENDERECO
, F.PONTOREFFOR AS COMPLEMENTO
, F.NUMFOR AS NUMERO
, F.BAIRROFOR AS BAIRRO
, F.CEPFOR AS CEP
, F.CIDADEFOR AS CIDADE
, F.UF
, F.CONTATO
, F.NOMEREPRES AS PERSONAL1
, F.TELEFOR AS TELEFONE
, F.TELREPRES AS PERSONAL2
, F.MAILFOR AS EMAIL
, F.FAXFOR AS FAX
, F.CELULARFOR AS CELULAR
FROM CADFORNECEDOR F
