SELECT
    PECA.CODIGO AS CODIGO,
    PECA.DESCRICAO AS DESCRICAO,
    PECA.UNIDADE AS UND,
    PECA.VALOR AS PRECO_VENDA,
    PECA.CODNUM AS COD_FABRICANTE,
    PECA.CUSTO AS PRECO_CUSTO,
    PECA.MARCAS AS CARACTERISTICAS,
    PECA.ESTOQUE AS QTD,
    PECA.ESTMIN AS QTD_IDEAL,
    SUBSTRING (IMPOSTO.SITTRIB FROM 1 FOR 1) AS OST,
    SUBSTRING (IMPOSTO.SITTRIB FROM 2 FOR 4) AS ST,
    PECA.NCM AS COD_NCM,
    PECA.PESOLIQ AS PESO,
    PECA.CODBARRAS AS BARRAS,
    PECA.OBSTEXTO AS OBSERVACOES,
    PECA.CEST AS PERSONAL6,
    PECA.CADASTRO_DATA AS DATA_CADASTRO
FROM PECA
LEFT JOIN IMPOSTO ON IMPOSTO.CODIGO = PECA.IMPOSTO
