SELECT
  FORNECEDORES.FORNECEDORESID AS CODIGO,
  FORNECEDORES.NOME AS NOME,
  ENDERECOS.ENDERECO AS ENDERECO,
  ENDERECOS.BAIRRO AS BAIRRO,
  ENDERECOS.CEP AS CEP,
  MUNICIPIOS.DESCRICAO AS CIDADE,
  ENDERECOS.UF AS UF,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
  case when FORNECEDORES.CPF = '' or FORNECEDORES.CPF is null then FORNECEDORES.CNPJ else FORNECEDORES.CPF END AS CNPJ_CNPF,
  case when FORNECEDORES.RG = '' or FORNECEDORES.RG is null then FORNECEDORES.IE else FORNECEDORES.RG END AS IE_RG,
  FORNECEDORES.TELEFONE AS TELEFONE,
  FORNECEDORES.CELULAR AS CELULAR,
  FORNECEDORES.EMAIL AS EMAIL,
  FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES
LEFT JOIN ENDERECOS ON ENDERECOS.ENDERECOSID = FORNECEDORES.ENDERECOSID
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.MUNICIPIOSID = ENDERECOS.MUNICIPIOSID