SELECT
    CADASTROFORNECEDOR.CODIGO AS CODIGO,
    CADASTROFORNECEDOR.NOMEFORNECEDOR AS NOME,
    CADASTROFORNECEDOR.REPRESENTANTE AS CONTATO,
    case when CADASTROFORNECEDOR.CPF= '' or CADASTROFORNECEDOR.CPF is null then CADASTROFORNECEDOR.CNPJ else CADASTROFORNECEDOR.CPF END AS CNPJ_CNPF,
    CADASTROFORNECEDOR.IE AS IE_RG,
    CADASTROFORNECEDOR.ENDERECO AS ENDERECO,
    CADASTROFORNECEDOR.PONTOREFERENCIA AS COMPLEMENTO,
    CADASTROFORNECEDOR.NUMERO AS NUMERO,
    CADASTROFORNECEDOR.BAIRRO AS BAIRRO,
    CADASTROFORNECEDOR.CIDADE AS CIDADE,
    CADASTROFORNECEDOR.ESTADO AS UF,
    CADASTROFORNECEDOR.CEP AS CEP,
    CADASTROFORNECEDOR.FONE1 AS TELEFONE,
    CADASTROFORNECEDOR.FONE2 AS CELULAR,
    CADASTROFORNECEDOR.FAX AS FAX,
    CADASTROFORNECEDOR.EMAIL AS EMAIL,
    CADASTROFORNECEDOR.OBS AS OBSERVACOES
FROM CADASTROFORNECEDOR
