SELECT
    PRODUTOS.CODIGO  AS COD_FABRICANTE,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIMED AS UND,
    QTDE2023.QUANTANT AS QTD,
    PRODUTOS.PESOLIQUIDO AS PESO,
    QTDE2023.CUSTOANT AS PRECO_CUSTO,
    PRECOPR.PRECO1 AS PRECO_VENDA,
    PRODUTOS.CODTRIBUTACAO AS ST,
    PRODUTOS.CLASFISCAL AS COD_NCM,
    PRODUTOS.DATACADASTRO AS DATA_CADASTRO,
    GRUPOSPR.DESCR AS GRUPO,
    PRODUTOS.ESTOQMINIMO AS QTD_IDEAL,
    PRODUTOS.MARCA AS CARACTERISTICAS,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN PRECOPR ON PRECOPR.CODPRODUTO = PRODUTOS.CODIGO
LEFT JOIN QTDE2023 ON QTDE2023.CODPROD = PRODUTOS.CODIGO
LEFT JOIN GRUPOSPR ON GRUPOSPR.GRUPO = PRODUTOS.GRUPOS