SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.CODBARRAS AS BARRAS,
    PRODUTO.DESCRICAO AS DESCRICAO,
    UNIDADE.UNMAIOR AS UND,
    PRODUTO.PESOLIQUIDO AS PESO,
   (select first 1 ESTOQUE.SALDO from estoque where ESTOQUE.CHAVEPRODUTO = PRODUTO.CHAVE order by estoque.data desc) as qtd,
    PRODUTO.CHAVE AS CARACTERISTICAS,
    PRODUTOCUSTO.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTOCUSTO.PRECOMEDIO AS CUSTO_MEDIO, 
    PRODUTOVENDA.PRECOVENDA as preco_venda,
    PRODUTO.CODIGOFABRICA AS COD_FABRICANTE,
    TRIBUTACAO.CODIGOSOSN AS ST,
    CLASSFISCAL.CODIGO AS COD_NCM,
    CLASSFISCAL.CEST AS PERSONAL6,
    CAST (PRODUTO.DATAHORACAD AS DATE) AS DATA_CADASTRO,
    CAST (PRODUTOVENDA.DATAHORAALT AS DATE) AS ALTERACAO_PRECO,
    PRODUTO.OBS AS OBSERVACOES,
    case when PRODUTO.ATIVO = '1' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PRODUTO
LEFT JOIN CLASSFISCAL ON CLASSFISCAL.CHAVE = PRODUTO.CHAVECLASSFISCAL
LEFT JOIN UNIDADE ON UNIDADE.CHAVE = PRODUTO.CHAVEUNIDADE
LEFT JOIN GRUPOFISCAL ON GRUPOFISCAL.CHAVE = PRODUTO.CHAVEGRUPOFISCAL
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.CHAVE = GRUPOFISCAL.CHAVETRIBUTACAO
LEFT JOIN PRODUTOCUSTO ON PRODUTOCUSTO.CHAVEPRODUTO = PRODUTO.CHAVE
LEFT JOIN PRODUTOVENDA ON PRODUTOVENDA.CHAVEPRODUTO = PRODUTO.CHAVE
--LEFT JOIN ESTOQUE ON ESTOQUE.CHAVEPRODUTO = PRODUTO.CHAVE
