SELECT
substring (FORNECEDOR.COD_FOR FROM 3 FOR 8) AS CODIGO,
FORNECEDOR.FORNECE AS NOME,
FORNECEDOR.RAZ_SOC AS FANTASIA,
FORNECEDOR.ENDEREC AS ENDERECO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CIDADE,
FORNECEDOR.ESTADO AS UF,
FORNECEDOR.CEP,
CASE WHEN FORNECEDOR.CNPJ IS NULL OR FORNECEDOR.CNPJ=''
THEN FORNECEDOR.CPF ELSE FORNECEDOR.CNPJ END AS CNPJ_CNPF,
FORNECEDOR.FONE1 AS TELEFONE,
FORNECEDOR.FONE2 AS CELULAR,
FORNECEDOR.FAX,
FORNECEDOR.EMAIL,
FORNECEDOR.OBSERVA AS OBSERVACOES,
FORNECEDOR.NUMCASA AS NUMERO
FROM FORNECEDOR
