SELECT
    CLIENTES.COD_CLIENTE AS CODIGO,
    ESTADOS.SIGLA_UF AS UF,
    CLIENTES.CPFCGC AS CNPJ_CNPF,
    CLIENTES.NOME_CLIENTE AS FANTASIA,
    CLIENTES.RAZAO AS NOME,
    CLIENTES.CIDADE AS CIDADE,
    CLIENTES.CEP AS CEP,
    CLIENTES.INSC_EST AS IE_RG,
    CLIENTES.CONTATO AS CONTATO,
    CLIENTES.FONE_CLIENTE AS TELEFONE,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.BAIRRO AS BAIRRO,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.NUM_END_CLIENTE AS NUMERO,
    CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.FONE_CELULAR AS CELULAR
FROM CLIENTES
LEFT JOIN ESTADOS ON CLIENTES.CODIGO_UF = ESTADOS.codigo_uf