SELECT
    COD_PROD AS CODIGO,
    EST_F AS QTD,
    PREC_CUS_PROD AS PRECO_CUSTO,
    PREC_TAB_PROD AS PRECO_VENDA,
    DESCR_PROD AS DESCRICAO,
    NUM_FAB_PROD AS COD_FABRICANTE,
    UNIDADE AS UND,
    CST_PROD AS ST,
    NBM AS COD_NCM,
    CEST AS PERSONAL6
FROM PRODUTOS