SELECT
    COD_CLI AS CODIGO,
    NOME_CLI AS NOME,
    ENDRES_CLI AS ENDERECO,
    BAIRES_CLI AS BAIRRO,
    CIDRES_CLI AS CIDADE,
    ESTRES_CLI AS UF,
    CEPRES_CLI AS CEP,
    TELRES_CLI AS TELEFONE,
    CNPJ_CLI AS CNPJ_CNPF,
    DOC_CLI AS IE_RG,
    DATACADASTRO_CLI AS CADASTRO,
    NOME_FANTASIA AS FANTASIA,
    NUMRES_CLI AS NUMERO
FROM CLIENTE
