SELECT PRODUTO.COD_PRO AS CODIGO,
PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
PRODUTO.COD_NCM,
--PRODUTO.COD_CEST AS PERSONAL6,
PRODUTO.NOME_PRO AS DESCRICAO,
LABORATORIO.NOME_LAB AS GRUPO,
--PRODUTO.DATA_CADASTRO,
PRODUTO.PRECO_CUSTO,
PRODUTO.VALOR_PRO AS PRECO_VENDA,
UNIDADE_MEDIDA.DESCRICAO AS UND,
ESTOQUE.ESTOQUE AS QTD
FROM PRODUTO
LEFT JOIN LABORATORIO ON PRODUTO.COD_LAB=LABORATORIO.COD_LAB
LEFT JOIN UNIDADE_MEDIDA ON PRODUTO.CODIGO_UNIDADE_SAIDA=UNIDADE_MEDIDA.CODIGO
LEFT JOIN ESTOQUE ON PRODUTO.COD_PRO=ESTOQUE.COD_PRO

