SELECT
    CONTAS_RECEBER.COD_CTR || '/' || CONTAS_RECEBER.NUMDOCUMENTO_CTR AS DOCUMENTO,
    CONTAS_RECEBER.DATA_CTR AS EMISSAO,
    SUBSTRING('000000' from 1 for (6-CHAR_LENGTH(CONTAS_RECEBER.COd_CLI)))||CONTAS_RECEBER.COd_CLI AS COD_CLIENTE,
    CLIENTE.NOME_CLI AS NOM_CLIENTE,
    CONTAS_RECEBER.VENCTO_CTR AS VENCIMENTO,
    CONTAS_RECEBER.VALOR_CTR AS VALOR_DUP,
    CONTAS_RECEBER.DTPAGTO_CTR AS RECEBIMENTO,
    CONTAS_RECEBER.VLRPAGO_CTR AS VALOR_REC,
    CONTAS_RECEBER.ACRESCIMO_CTR VALOR_JUR,
    CONTAS_RECEBER.DESCONTO_CTR VALOR_DES,
    CONTAS_RECEBER.NUMDOCUMENTO_CTR AS HISTORICO,
    CONTAS_RECEBER.PARCELA_CTR AS NUM_PARCELA,
'' AS CNPJ
FROM CONTAS_RECEBER
LEFT JOIN CLIENTE ON CONTAS_RECEBER.COD_CLI = CLIENTE.COD_CLI
