SELECT 
       CODIGO_FORNECEDOR AS CODIGO
      ,NOME AS NOME
      ,CPF_CGC AS CNPJ_CNPF
      ,INSC AS IE_RG
      ,RUA AS ENDERECO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,ESTADO AS UF
      ,CEP AS CEP
      ,CONTATO AS CONTATO
      ,FANTASIA AS FANTASIA
      ,NUMERO AS NUMERO
      ,COMPLEMENTO AS COMPLEMENTO
      ,EMAIL AS EMAIL
  FROM BACKGO2.dbo.FORNECEDORES