SELECT
       PRODUTOS.CODIGO_INTERNO AS CODIGO
      ,PRODUTOS.CODIGO_BARRAS AS BARRAS
      ,PRODUTOS.DESCRICAO AS DESCRICAO
      ,FORNECEDORES.NOME AS FORNECEDOR
      ,TAB_UNIDADE_MEDIDA.CODIGO_UNIDADE AS UND
      ,PRODUTOS.PESO_LIQUIDO AS PESO
      ,ESTOQUE.SALDO_ATUAL AS QTD
      ,ESTOQUE.CUSTO AS PRECO_CUSTO
      ,ESTOQUE.CUSTO_MEDIO AS CUSTO_MEDIO
      ,ESTOQUE.VALOR_VENDA AS PRECO_VENDA
      ,TAB_TRIBUTOS.TRIBUTO AS ST
      ,ESTOQUE.DT_ULTIMA_VD AS ULTIMA_VENDA
      ,ESTOQUE.OBSERVACAO AS OBSERVACOES
      ,ESTOQUE.ULT_ALT_PRECO AS ALTERACAO_PRECO
      ,PRODUTOS.DATA_CAD AS DATA_CADASTRO
      ,PRODUTOS.CODIGO_NCM AS COD_NCM
      ,PRODUTOS.CODIGO_CEST AS PERSONAL6
  FROM BACKGO2.dbo.PRODUTOS
  LEFT JOIN BACKGO2.dbo.ESTOQUE ON ESTOQUE.CODIGO_INTERNO = PRODUTOS.CODIGO_INTERNO
LEFT JOIN BACKGO2.dbo.TAB_UNIDADE_MEDIDA ON TAB_UNIDADE_MEDIDA.CODIGO = PRODUTOS.UNIDADE
LEFT JOIN BACKGO2.dbo.TAB_TRIBUTOS ON TAB_TRIBUTOS.CODIGO = ESTOQUE.TRIBUTACAO
LEFT JOIN BACKGO2.dbo.FORNECEDORES ON FORNECEDORES.CODIGO_FORNECEDOR = PRODUTOS.CODIGO_FORNECEDOR