SELECT
    CONTATO.ID AS CODIGO,
    CONTATO.NOME AS NOME,
    --CONTATO.RAZAO_SOCIAL AS FANTASIA,
    CONTATO.ENDERECO,
    CONTATO.NUM_END AS NUMERO,
    CONTATO.BAIRRO_END AS BAIRRO,
    CONTATO.CIDADE_END AS CIDADE,
    CONTATO.CEP_END AS CEP,
    CONTATO.TELEFONE,
    CONTATO.CELULAR,
    CONTATO.CNPJ_CPF AS CNPJ_CNPF,
    CONTATO.INSC_RG AS IE_RG,
    CONTATO.CONTATO,
    CONTATO.COMPLEMENTO,
    CONTATO.EMAIL
FROM CONTATO
WHERE TIPO_CONTATO = 'C'
