SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.CODBAR AS BARRAS,
    PRODUTOS.DESCR AS DESCRICAO,
    PRODUTOS.UNDVEN AS UND,
    PRODUTOS.PESOLIQ AS PESO,
    GRUPOS.DESCR AS GRUPO,
    SUBGRUPOS.DESCRSGRP AS FAMILIA,
    MARCAS.DESCR AS CARACTERISTICAS,
    PRODUTOS.PRCUS AS PRECO_CUSTO,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRVEN AS PRECO_VENDA,
    PRODUTOS.PRATAC AS PRECO_ATACADO,
    PRODUTOS.ESTMIN AS QTD_IDEAL,
    PRODUTOS.ESTFIS AS QTD,
    PRODUTOS.CSOSN AS ST,
    PRODUTOS.REF AS COD_FABRICANTE,
    replace(PRODUTOS.NCM,'.','') AS COD_NCM,
    PRODUTOS.ULTVEN AS ULTIMA_VENDA,
    PRODUTOS.ULTCOMP AS ULTIMA_COMPRA,
    PRODUTOS.DTALTER AS ALTERACAO_PRECO
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.CODIGO = PRODUTOS.SUBGRUPO
LEFT JOIN MARCAS ON MARCAS.CODIGO = PRODUTOS.MARCA