SELECT
    ID_FORNECEDOR AS CODIGO,
    FORNECEDOR AS NOME,
    RAZ_SOCIAL AS FANTASIA,
    CONTATO AS CONTATO,
    CNPJ AS CNPJ_CNPF,
    INSC_EST AS IE_RG,
    ENDER AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    CEP AS CEP,
    UF AS UF,
    FONE AS TELEFONE,
    FAX AS FAX,
    CELULAR AS CELULAR,
    EMAIL AS EMAIL,
    OBS AS OBSERVACOES
FROM FORNECEDOR
