SELECT
    PRODUTO.CD_PRODUTO AS PERSONAL2,
    PRODUTO.NM_PRODUTO AS DESCRICAO,
    GRUPROD.NM_GRUPROD AS GRUPO,
    MARCA.NM_MARCA AS CARACTERISTICAS,
    PRODUTO.UN_MEDIDA AS UND,
    PRODUTO.PESO_LIQUIDO AS PESO,
    MAX (ESTOQUE.QTDE) AS QTD,
    TABELA_PRECO_PRODUTO.PRECO_VENDA AS PRECO_VENDA,
    PRODUTO.OBS AS OBSERVACOES,
    SUBGRUPROD.NM_SUBGRUPROD AS FAMILIA,
    PRODUTO.DT_ATZ AS ALTERACAO_PRECO,
    CST.FL_ICM AS ST,
    PRODUTO_CLASS_FISCAL.NM_CLASS_FISCAL AS COD_NCM,
    CEST.CEST AS PERSONAL6,
    PRODUTO.CD_FABRICANTE AS COD_FABRICANTE,
    PRODUTO.DT_CADASTRO AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN CST ON CST.CD_CST = CD_CLASS_FISCAL
LEFT JOIN ESTOQUE ON ESTOQUE.CD_PRODUTO = PRODUTO.CD_PRODUTO
LEFT JOIN GRUPROD ON GRUPROD.CD_GRUPROD = PRODUTO.CD_GRUPROD
LEFT JOIN SUBGRUPROD ON SUBGRUPROD.CD_SUBGRUPROD = PRODUTO.CD_SUBGRUPROD
LEFT JOIN MARCA ON MARCA.CD_MARCA = PRODUTO.CD_MARCA
LEFT JOIN TABELA_PRECO_PRODUTO ON TABELA_PRECO_PRODUTO.CD_PRODUTO = PRODUTO.CD_PRODUTO
LEFT JOIN PRODUTO_CLASS_FISCAL ON PRODUTO_CLASS_FISCAL.CD_CLASS_FISCAL = PRODUTO.CD_CLASS_FISCAL
LEFT JOIN CEST ON CEST.CD_CEST = PRODUTO_CLASS_FISCAL.CD_CEST
GROUP BY 1,2,3,4,5,6,8,9,10,11,12,13,14,15,16
