SELECT
  P.CODIGO,

  -- BARRAS: somente números
  CASE
    WHEN TRIM(P.CODIGO_BARRA) SIMILAR TO '[0-9]+' THEN P.CODIGO_BARRA
    ELSE NULL
  END AS BARRAS,

  -- COD_FABRICANTE: se tiver letras ou caracteres
  CASE
    WHEN TRIM(P.CODIGO_BARRA) SIMILAR TO '[0-9]+' THEN NULL
    ELSE P.CODIGO_BARRA
  END AS COD_FABRICANTE,

  P.NOME AS DESCRICAO,
  NULL AS UND,
  P.FORNECEDOR,
  COALESCE(P.ESTOQUE, 0) AS QTD,
  COALESCE(P.MINIMO, 0) AS QTD_IDEAL,
  COALESCE(P.PESO, 0) AS PESO,
  COALESCE(P.CUSTO, 0) AS PRECO_CUSTO,
  0 AS CUSTO_MEDIO,
  COALESCE(P.MARGENS, 0) AS MARGEM_LUCRO,
  COALESCE(P.VENDA, 0) AS PRECO_VENDA,
  NULL AS OBSERVACOES,
  P.DATA_CADATRO AS CADASTRO,
  P.NCM AS COD_NCM,
  P.DATA_ULTCOMPRA AS ULTIMA_COMPRA,
  P.CFOP AS CF,

  -- Situação
  CASE P.SITUACAO
    WHEN 'A' THEN 'Ativo'
    WHEN 'I' THEN 'Inativo'
    ELSE 'Desconhecido'
  END AS SITUACAO,

  -- JOINs
  C.CEST AS PERSONAL6,
  L.NOME AS GRUPO,
  T.CSOSN AS ST

FROM PRODUTOS P
LEFT JOIN (
  SELECT NCM, MIN(CEST) AS CEST
  FROM CEST
  GROUP BY NCM
) C ON C.NCM = P.NCM
LEFT JOIN LABORATORIO L ON L.CODIGO = P.COD_LABORATORIO
LEFT JOIN TRIBUTACAO_PRODUTOS T ON T.CODIGO = P.COD_TRIBUTACAO;