SELECT
	C.CODCLIENTE AS CODIGO,
	C.NOME AS NOME,
	C.NOMEFANTASIA AS FANTASIA,
	C.DATANASC AS NASCIMENTO,
	C.CPFCNPJ AS CNPJ_CNPF,
	CASE WHEN C.IE = '' OR C.IE IS NULL THEN C.RG ELSE C.IE END AS IE_RG,
	C.EMAIL AS EMAIL,
	C.NOMEPAI AS PAI,
	C.NOMEMAE AS MAE,
	C.FAX AS FAX,
	C.LIMITE AS LIMITE_CREDITO,
	CE.ENDERECO AS ENDERECO,
	CE.NUMERO AS NUMERO,
	CE.BAIRRO AS BAIRRO,
	CE.COMPLEMENTO AS COMPLEMENTO,
	CE.CEP AS CEP,
	CI.CIDADE AS CIDADE,
	CI.UF AS UF
FROM CLIENTES C
LEFT JOIN CLIENTES_ENDERECOS CE ON C.CODCLIENTE=CE.CODCLIENTE
LEFT JOIN CIDADES CI ON CE.CODCIDADE = CI.CODCIDADE
