SELECT
	P.CODIGO AS CODIGO,
	P.IDBARRA AS COD_FABRICANTE,
	P.PRODUTO AS DESCRICAO,
	CASE P.INATIVO WHEN 'S' THEN 'Inativo' WHEN 'N' THEN 'Ativo' END AS SITUACAO,
	P.OBSERVACAO AS OBSERVACOES,
	P.REFERENCIA AS PERSONAL1,
	P.CUSTO AS PRECO_CUSTO,
	P.VALOR1 AS PRECO_VENDA,
	F.NOME AS FORNECEDORES,
	G.DESCRICAO AS GRUPO,
	U.UNIDADE AS UND,
	P.CODSITUACAOTRIBUTARIA AS ST,
	P.CODALIQUOTA AS ELO,
	P.NCM AS COD_NCM,
	P.CUSTOMEDIO AS CUSTO_MEDIO,
	P.GTIN AS BARRAS,
	P.PIS_CST AS PIS_CODIGO,
	P.COFINS_CST AS COFINS_CODIGO,
	P.CEST AS PERSONAL6,
	PE.DISPONIVEL AS QTD
FROM PRODUTOS P
LEFT JOIN FORNECEDORES F ON P.CODFORNECEDOR =F.CODIGO 
LEFT JOIN GRUPOS G ON P.CODGRUPO=G.CODGRUPO 
LEFT JOIN UNIDADES U ON P.CODUNIDADE=U.CODUNIDADE 
LEFT JOIN PRODUTOS_ESTOQUE PE ON P.CODIGO=PE.CODPRODUTO 