SELECT
  CLIENTE.CLIENTE_ID AS PERSONAL2,
  CLIENTE.NOME_CLIENTE AS NOME,
  CLIENTE.NOME_CURTO AS FANTASIA,
  CLIENTE_END.CNPJ AS CNPJ_CNPF,
  CLIENTE_END.IE AS IE_RG,
  CLIENTE_END.LOGRADOURO AS ENDERECO,
  CLIENTE_END.NUMERO AS NUMERO,
  CLIENTE_END.COMP AS COMPLEMENTO,
  CLIENTE_END.BAIRRO AS BAIRRO,
  CLIENTE_END.CEP AS CEP,
  CIDADES.NOME AS CIDADE,
  ESTADO_TBL.ABREV_UF,
  CLIENTE_END.TELEFONE1,
  CLIENTE.SEXO,
  CLIENTE.NATURALIDADE,
  CLIENTE.DATA_NASCIMENTO,
  CLIENTE.NOME_PAI,
  CLIENTE.NOME_MAE,
  CLIENTE.DATA_CADASTRO,
  CLIENTE.OBS
FROM CLIENTE
LEFT JOIN CLIENTE_END ON CLIENTE_END.CLIENTE_ID = CLIENTE.CLIENTE_ID
LEFT JOIN CIDADES ON CIDADES.CIDADE_ID = CLIENTE_END.CIDADE
LEFT JOIN ESTADO_TBL ON ESTADO_TBL.COD_UF = CLIENTE_END.ESTADO
