SELECT
  FORNECEDOR.FORNECEDOR_ID AS CODIGO,
  FORNECEDOR.NOME AS NOME,
  FORNECEDOR.NOME_CURTO AS FANTASIA,
  FORNECEDOR.NOME_CONTATO AS CONTATO,
  FORNECEDOR.EMAIL AS EMAIL,
  FORNECEDOR.LOGRADOURO AS ENDERECO,
  FORNECEDOR.NUMERO AS NUMERO,
  FORNECEDOR.COMP AS COMPLEMENTO,
  FORNECEDOR.BAIRRO AS BAIRRO,
  FORNECEDOR.CEP AS CEP,
  CIDADES.NOME AS CIDADE,
  ESTADO_TBL.ABREV_UF AS UF,
  FORNECEDOR.TELEFONE1 AS TELEFONE,
  FORNECEDOR.TELEFONE2 AS CELULAR,
  FORNECEDOR.CPF_CNPJ AS CNPJ_CNPF,
  FORNECEDOR.RG_IE AS IE_RG,
  FORNECEDOR.IM AS IM
FROM FORNECEDOR
LEFT JOIN CIDADES ON CIDADES.CIDADE_ID = FORNECEDOR.CIDADE
LEFT JOIN ESTADO_TBL ON ESTADO_TBL.COD_UF = FORNECEDOR.ESTADO
