SELECT
    PRODUTOS.PRODUTOS_ID AS CODIGO,
    UNIDADES.UNIDADE_NOME AS UND,
    PRODUTOS.PRODUTO_NOME AS DESCRICAO,
    DEPARTAMENTOS.DEPARTAMENTO_NOME AS GRUPO,
    SUBGRUPOS.SUBGRUPO_NOME AS FAMILIA,
    PRODUTOS.PRODUTO_PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTOS.PRODUTO_MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRODUTO_PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.PRODUTO_ESTOQUE_DISPONIVEL AS QTD,
    PRODUTOS.NCM_ID AS COD_NCM,
    PRODUTOS.CEST_ID AS PERSONAL6
FROM PRODUTOS
LEFT JOIN UNIDADES ON PRODUTOS.UNIDADES_ID = UNIDADES.UNIDADES_ID
LEFT JOIN DEPARTAMENTOS ON PRODUTOS.DEPARTAMENTOS_ID = DEPARTAMENTOS.DEPARTAMENTOS_ID
LEFT JOIN SUBGRUPOS ON PRODUTOS.SUBGRUPOS_ID = SUBGRUPOS.SUBGRUPOS_ID
