SELECT
  CADPRO.codpro01 AS CODIGO,
  CADPRO.codpro01 AS COD_FABRICANTE,
  CADGSS.DESCGSS00 AS GRUPO,
  CADPRO.descpro01 AS DESCRICAO,
  REPLACE (max(ARQBAR.codbarra), '.' , '') AS BARRAS,
  CADPRO.precust01 AS PRECO_CUSTO,
  CADPRO.prevend01 AS PRECO_VENDA, -- PRECO_VENDAS 2
  CADPRO.prevend201 AS PERSONAL1,
  CADPRO.margtra01 AS MARGEM_LUCRO,
  CADPRO.unidpro01 AS UND,
  CADPRO.estatu01 AS QTD,
  CADPRO.estmin01 AS QTD_IDEAL,
  CADPRO.pesoliq01 AS PESO,
--  CADPRO.sitpro01 AS ST,
  CADPRO.subtri01 AS ST,
  CADPRO.dataalt01 AS ALTERACAO_PRECO,
  CADPRO.descabr01 AS OBSERVACOES,
  CADPRO.FORNEC01 AS FORNECEDOR,
  CADPRO.datacad01 AS DATA_CADASTRO,
  REPLACE (CADPRO.codncm01, '.' , '') AS COD_NCM,
  REPLACE (CADPRO.codcest01, '.' , '') AS PERSONAL6
FROM CADPRO
LEFT JOIN CADGSS ON CADGSS.CODGSS00 = CADPRO.CODGSS01
LEFT JOIN CADFORN ON CADFORN.CODFORN02 = CADPRO.FORNEC01
LEFT JOIN ARQBAR ON ARQBAR.CODPRO = CADPRO.codpro01
where cadpro.codfil01 = '1'
group by 1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
