SELECT
    ID_CLIFOR AS CODIGO,
    NOME,
    CONTATO,
    IE AS IE_RG,
    CGC AS CNPJ_CNPF,
    ENDERE AS ENDERECO,
    NUMERO,
    COMPLE AS COMPLEMENTO,
    BAIRRO,
    CEP,
    CIDADE,
    ESTADO AS UF,
    FONE AS TELEFONE,
    CELULAR,
    EMAIL
FROM CLIFOR
