SELECT
    CODIGO,
    REFERENCIA AS BARRAS,
    DESCRICAO,
    MEDIDA AS UND,
    PRECO AS PRECO_VENDA,
    CUSTOCOMPR AS PRECO_CUSTO,
    CUSTOMEDIO AS CUSTO_MEDIO,
    CF AS COD_NCM,
    CSOSN AS ST,
    CST_PIS_COFINS_SAIDA AS PIS_CODIGO,
    CST_PIS_COFINS_SAIDA AS COFINS_CODIGO,
    CEST AS PERSONAL6
FROM ESTOQUE
