SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    NOME_FANTASIA AS FANTASIA,
    REPRESENTANTE AS CONTATO,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    CNPJ AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    E_MAIL1 AS EMAIL,
    OBSERVACOES AS OBSERVACOES
FROM FORNECEDORES
