SELECT
    CODIGO AS CODIGO,
    REFERENCIA AS COD_FABRICANTE,
    CODIGO_BARRA AS BARRAS,
    DESCRICAO AS DESCRICAO,
    FORNECEDOR AS FORNECEDOR,
    UNIDADE AS UND,
    PRECO_VENDA AS PRECO_VENDA,
    PRECO_CUSTO AS PRECO_CUSTO,
    PRECO_CUSTO_MEDIO AS CUSTO_MEDIO,
    MARGEM AS MARGEM_LUCRO,
    ESTOQUE AS QTD,
    ESTOQUE_MINIMO AS QTD_IDEAL,
    PESO AS PESO,
    SITUAC_TRIBUTARIA,
    ULTIMA_COMPRA AS ULTIMA_COMPRA,
    ULTIMA_VENDA AS ULTIMA_VENDA,
    ULTIMA_ALTERACAO AS ALTERACAO_PRECO,
    MARCA AS CARACTERISTICAS,
    OBSERVACOES AS OBSERVACOES
FROM PRODUTOS
WHERE DESCRICAO <> '';
