SELECT
    PRODUTO.id_produto AS CODIGO,
	PRODUTO.REFERENCIA AS PERSONAL1,
	max (PRODUTO_CONSULTA.CODIGO_GTIN) AS BARRAS,
	min (PRODUTO_CONSULTA.CODIGO_GTIN) AS cod_fabricante,
    NCM.CODIGO AS COD_NCM,
    GRUPO_PRODUTO.DESCRICAO AS GRUPO,
    PRODUTO.descricao AS DESCRICAO,
	MAX (PRODUTO_CONSULTA.ESTOQUE) AS QTD,
	MAX (PRODUTO_CONSULTA.CUSTO_REAL) AS PRECO_CUSTO,
	MAX (PRODUTO_CONSULTA.VALOR_UNITARIO) AS PRECO_VENDA,
    CSOSN.CODIGO_CST AS ST,
    PRODUTO.cest AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_CONSULTA ON PRODUTO.ID_PRODUTO = PRODUTO_CONSULTA.ID_PRODUTO
LEFT JOIN CSOSN ON PRODUTO.ID_CSOSN = CSOSN.ID_CSOSN
LEFT JOIN NCM ON PRODUTO.ID_NCM = NCM.ID_NCM
LEFT JOIN GRUPO_PRODUTO ON PRODUTO.ID_GRUPO_PRODUTO = GRUPO_PRODUTO.ID_GRUPO_PRODUTO
GROUP BY 1,2,5,6,7,11,12
ORDER BY 1