SELECT PDV_PRODUTOS.ID_PRODUTO AS CODIGO,
PDV_PRODUTOS.CODPRODUTO AS COD_FABRICANTE,
PDV_PRODUTOS.DESCRICAO,
PDV_PRODUTOS.UNIDADE AS UND,
PDV_PRODUTOS.QUANTIDADE AS QTD,
PDV_PRODUTOS.EAN AS BARRAS,
PDV_PRODUTOS.ID_CSOSN AS ST,
PDV_PRODUTOS.classificacaofiscal as cod_ncm,
PDV_PRODUTOS.VLRVENDASUGERIDO AS PRECO_VENDA,
PDV_PRODUTOS.CODIGOCEST AS PERSONAL6
FROM PDV_PRODUTOS
