SELECT
    FORNECEDOR AS CODIGO,
    NOME AS NOME,
    NOMEFANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    CICCGC AS CNPJ_CNPF,
    RGINS AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    replace(CAST (FAR103.CEP AS INTEGER),'.','') AS CEP,
    FONE AS TELEFONE,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM FAR103
