SELECT
    CAD_PRODUTOS.CODIGO AS CODIGO,
    CAD_PRODUTOS.CODIGO_BARRA AS BARRAS,
    CAD_PRODUTOS.DESCRICAO AS DESCRICAO,
    CAD_PRODUTOS.PESO AS PESO,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    CAD_PRODUTOS.MARCA AS CARACTERISTICAS,
    CAD_PRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
    CAD_PRODUTOS.ESTOQUESALDO AS QTD,
    CAD_PRODUTOS.MG_LUCRO AS MARGEM_LUCRO,
    CAD_PRODUTOS.PRC_CUSTO AS PRECO_CUSTO,
    CAD_PRODUTOS.PRC_VENDA AS PRECO_VENDA,
    CAD_PRODUTOS.CLASSIF_FISCAL AS ST,
    CAD_PRODUTOS.DETALHES AS OBSERVACOES,
    CAD_PRODUTOS.CODIGO_BARRA AS COD_FABRICANTE,
    --CAD_PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    CAD_PRODUTOS.DATA AS DATA_CADASTRO,
    CAD_PRODUTOS.DT_ULTIMA_COMPRA AS ULTIMA_COMPRA,
    CAD_PRODUTOS.DT_ULTIMA_VENDA AS ULTIMA_VENDA,
    CAD_PRODUTOS.NCM AS COD_NCM
FROM CAD_PRODUTOS
LEFT JOIN GRUPO ON GRUPO.CODIGO = CAD_PRODUTOS.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CODIGO = CAD_PRODUTOS.SUBGRUPO
WHERE CAD_PRODUTOS.DESCRICAO IS NULL OR CAD_PRODUTOS.DESCRICAO <> ''
AND CAD_PRODUTOS.DATA > '2016-12-31'
