SELECT
    TB_CADFORNECEDOR_FOR.COD_FOR AS CODIGO,
    TB_CADFORNECEDOR_FOR.RAZAO_FOR AS NOME,
    TB_CADFORNECEDOR_FOR.NOME_FANTASIA_FOR AS FANTASIA,
    TB_CADFORNECEDOR_FOR.CPF_CGC_FOR AS CNPJ_CNPF,
    TB_CADFORNECEDOR_FOR.END_FOR AS ENDERECO,
    TB_CADFORNECEDOR_FOR.NUMERO_FOR AS NUMERO,
    TB_CADFORNECEDOR_FOR.COMPL_FOR AS COMPLEMENTO,
    TB_CADFORNECEDOR_FOR.BAIRRO_FOR AS BAIRRO,
    TB_CADFORNECEDOR_FOR.CIDADE_FOR AS CIDADE,
    TB_CADFORNECEDOR_FOR.UF_FOR AS UF,
    TB_CADFORNECEDOR_FOR.CEP_FOR AS CEP,
    TB_CADFORNECEDOR_FOR.INSC_MUN_FOR AS IM,
    TB_CADFORNECEDOR_FOR.INSC_EST_FOR AS IE_RG,
    TB_CADFORNECEDOR_FOR.FONE_FOR AS TELEFONE,
    TB_CADFORNECEDOR_FOR.OBS_FOR AS OBSERVACOES
FROM TB_CADFORNECEDOR_FOR
