SELECT
    TB_CADPRODUTO_PRO.COD_PRO AS CODIGO,
    TB_CADPRODUTO_PRO.COD_BARRAS_PRO AS BARRAS,
    TB_CADPRODUTO_PRO.DESCRICAO_PRO AS DESCRICAO,
    TB_CADPRODUTO_PRO.UND_PRO AS UND,
    tb_cadfornecedor_for.razao_for AS FORNECEDOR,
    TB_CADPRODUTO_PRO.DT_ULT_COMPRA_PRO AS ULTIMA_COMPRA,
    TB_CADPRODUTO_PRO.VALOR_CUSTO_PRO AS PRECO_CUSTO,
    TB_CADPRODUTO_PRO.VALOR_VENDA_PRO AS PRECO_VENDA,
    TB_CADPRODUTO_PRO.VALOR_ATACADO_PRO AS PRECO_ATACADO,
    TB_CADPRODUTO_PRO.EST_MIN_PRO AS QTD_IDEAL,
    MIN (tb_estoque_est.QUANTIDADE_EST) AS QTD,
    TB_CADPRODUTO_PRO.PESO_LIQUIDO_PRO AS PESO,
    TB_CADPRODUTO_PRO.CF_PRO AS COD_NCM,
    TB_CADPRODUTO_PRO.COD_TRB AS ST,
    TB_CADPRODUTO_PRO.COD_FAB AS COD_FABRICANTE,
    TB_CADPRODUTO_PRO.OBS1_PRO AS OBSERVACOES,
    tb_cadcest_ces.cest_ces AS PERSONAL6
FROM TB_CADPRODUTO_PRO
LEFT JOIN tb_cadfornecedor_for ON tb_cadfornecedor_for.cod_for = TB_CADPRODUTO_PRO.COD_FOR
LEFT JOIN tb_cadcest_ces ON tb_cadcest_ces.cod_ces = TB_CADPRODUTO_PRO.COD_CES
LEFT JOIN tb_estoque_est ON tb_estoque_est.cod_pro = TB_CADPRODUTO_PRO.COD_PRO
GROUP BY 1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17
