SELECT
    PRODUTOS.COD_PRODUTO AS CODIGO,                   
    PRODUTOS.DESCRICAO AS DESCRICAO,                     
    UNIDADE_PRODUTO.SIMBOLO AS UNIDADE,                   
    --MARCA_PRODUTO AS FAMILIA,                 
    --FORNECEDORES.NOME AS FORNECEDOR,
    GRUPOS.NOME AS GRUPO,                     
    PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,                   
    PRODUTOS.ESTOQUE AS QTD,                       
    PRODUTOS.COD_BARRA_PRODUTO AS BARRAS,             
    PRODUTOS.PRECO_AVISTA AS PRECO_VENDA,                  
    PRODUTOS.COD_SITUACAO_TRIBUTARIA AS ST,       
    PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,                
    PRODUTOS.NUMERO_NCM AS COD_NCM,                    
    PRODUTOS.COD_FABRICANTE AS COD_FABRICANTE,                
    PRODUTOS.COD_PIS AS PIS_CODIGO,                       
    PRODUTOS.COD_COFINS AS COFINS_CODIGO,                    
    PRODUTOS.CST_PIS_ENTRADA AS PISE_CODIGO,               
    PRODUTOS.CST_COFINS_ENTRADA AS COFINSE_CODIGO,           
    PRODUTOS.CEST AS PERSONAL6                          
FROM PRODUTOS
LEFT JOIN UNIDADE_PRODUTO ON PRODUTOS.COD_UNIDADE = UNIDADE_PRODUTO.COD_UNIDADE
LEFT JOIN FORNECEDORES ON PRODUTOS.COD_FORNECEDOR = FORNECEDORES.COD_FORNECEDOR
LEFT JOIN GRUPOS ON PRODUTOS.COD_GRUPO = GRUPOS.COD_GRUPO
