SELECT
	P.ID as codigo,
	CASE P.ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	P.CODIGOBARRA AS BARRAS,
	CAST (P.DATACADASTRO AS DATE) AS DATA_CADASTRO,		
	P.NOME AS DESCRICAO,
--	P.PERCENTUALMARGEMLUCRO AS MARGEM_LUCRO,
	P.VALORCUSTO AS PRECO_CUSTO, ---EM FUTURAS CONVERSÕES, VERIFICAR NA TABELA DBO.CUSTOPRODUTO SE TEM RELACAO
--	P.VALORCUSTOFIXO AS PRECO_CUSTO,
--	P.VALORULTIMOCUSTO AS PRECO_CUSTO,
	P.INFORMARVALIDADE AS VALIDADE_DIAS,
--	P.NCM AS COD_NCM,
	OM.CODIGO AS OST,
	TIP.CODIGO AS TIPO_ITEM,
	UM.SIGLA AS UND,
	N.CODIGO AS COD_NCM,
	C.CODIGO AS PERSONAL6,
	A.NOME AS GRUPO,
	MP.NOME AS FAMILIA,
	LEFT (C2.CODIGO,3) AS ELO,	
	TP.PERCENTUALALIQUOTAIPI AS ALIQ_IPI_VENDA,  
	TP.PERCENTUALALIQUOTAPIS AS PIS_ALIQ_NOR,  
	TP.PERCENTUALALIQUOTACOFINS AS COFINS_ALIQ_NOR,  
	TP.PERCENTUALALIQUOTAICMS AS ELO,
	TP.CODIGOBENEFICIOFISCAL AS CBENEF,
	TI.CODIGO AS IPI_CODIGO_VENDA,
	TPI.CODIGO AS PIS_CODIGO,
	TC.CODIGO AS COFINS_CODIGO,
	TIC.CODIGO AS ST,
	PP.VALOR AS PRECO_VENDA,
	PP.PERCENTUALMARGEMLUCRO AS MARGEM_LUCRO,
	RI.SALDOATUAL AS QTD,
	RI.ESTOQUEMINIMO AS QTD_IDEAL
FROM
	PRODUTO P
LEFT JOIN ORIGEMMERCADORIA OM ON OM.ID = P.IDORIGEMMERCADORIA
LEFT JOIN TIPOITEMPRODUTO TIP ON TIP.ID = P.IDTIPOITEMPRODUTO 
LEFT JOIN UNIDADEMEDIDA UM ON UM.ID = P.IDUNIDADEMEDIDA 	
LEFT JOIN NCM N ON N.ID = P.IDNCM 
LEFT JOIN CEST C ON C.ID = P.IDCEST 
LEFT JOIN AGRUPAMENTO A ON A.ID = P.IDAGRUPAMENTO 
LEFT JOIN MARCAPRODUTO MP ON MP.ID = P.IDMARCAPRODUTO 	
LEFT JOIN TRIBUTACAOPRODUTO TP ON TP.IDPRODUTO = P.ID 
LEFT JOIN TRIBUTACAO TI ON TI.IDTIPOTRIBUTACAO = TP.IDTRIBUTACAOIPI
LEFT JOIN TRIBUTACAO TPI ON TPI.IDTIPOTRIBUTACAO = TP.IDTRIBUTACAOPIS
LEFT JOIN TRIBUTACAO TC ON TC.IDTIPOTRIBUTACAO = TP.IDTRIBUTACAOCOFINS
LEFT JOIN TRIBUTACAO TIC ON TIC.IDTIPOTRIBUTACAO = TP.IDTRIBUTACAOICMS
LEFT JOIN CFOP C2 ON C2.ID = TP.IDCFOP
LEFT JOIN PRECOPRODUTO PP ON PP.IDPRODUTO = P.ID 
LEFT JOIN REQUISICAOITEM RI ON RI.IDPRODUTO = P.ID 
