SELECT
	ID AS CODIGO,
	NOME,
	NOMEFANTASIA AS FANTASIA,
	CEP,
	BAIRRO,
	LOGRADOURO AS ENDERECO,
	COMPLEMENTO,	
	NUMERO,
	CIDADE,
	UF,	
	CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF,
	CASE WHEN REGISTROGERAL = '' OR REGISTROGERAL IS NULL THEN INSCRICAOESTADUAL ELSE REGISTROGERAL END AS IE_RG,
	INSCRICAOMUNICIPAL AS IM,
	CONTATO,
	DATANASCIMENTO AS NASCIMENTO,
	CASE WHEN CELULARPESSOAL = '' OR CELULARPESSOAL IS NULL THEN CELULARCOMERCIAL ELSE CELULARPESSOAL END AS CELULAR,
	CASE WHEN EMAILCOMERCIAL = '' OR EMAILCOMERCIAL IS NULL THEN EMAILPESSOAL ELSE EMAILCOMERCIAL END AS EMAIL,
	LIMITE AS LIMITE_CREDITO,
	OBSERVACAO AS OBSERVACOES,
	TELEFONECOMERCIAL AS TELEFONE,
	TELEFONERESIDENCIAL AS PERSONAL1,
	CASE INDICADORIEDESTINATARIO WHEN '1' THEN 'C'
	WHEN '2' THEN 'I'
	WHEN '3' THEN 'N'
	END AS INDIEDEST
FROM
	PESSOAS
WHERE CLIENTE = '1'
