SELECT
	ID AS CODIGO,
	NOME,
	NOMEFANTASIA AS FANTASIA,
	CEP,
	BAIRRO,
	LOGRADOURO AS ENDERECO,
	COMPLEMENTO,	
	NUMERO,
	CIDADE,
	UF,	
	CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF,
	CASE WHEN REGISTROGERAL = '' OR REGISTROGERAL IS NULL THEN INSCRICAOESTADUAL ELSE REGISTROGERAL END AS IE_RG,
	INSCRICAOMUNICIPAL AS IM,
	CONTATO,
	CASE WHEN CELULARPESSOAL = '' OR CELULARPESSOAL IS NULL THEN CELULARCOMERCIAL ELSE CELULARPESSOAL END AS CELULAR,
	CASE WHEN EMAILCOMERCIAL = '' OR EMAILCOMERCIAL IS NULL THEN EMAILPESSOAL ELSE EMAILCOMERCIAL END AS EMAIL,
	OBSERVACAO AS OBSERVACOES,
	TELEFONECOMERCIAL AS TELEFONE,
	TELEFONERESIDENCIAL AS PERSONAL1
FROM
	PESSOAS
WHERE FORNECEDOR = '1'
