SELECT 
       PRODUTO.ID AS CODIGO
      ,UNIDADE_PRODUTO.NOME AS UND
      ,PRODUTO.GTIN AS BARRAS
      ,PRODUTO.NOME AS DESCRICAO
      ,GRUPO_PRODUTO.NOME AS GRUPO
      ,SUBGRUPO_PRODUTO.NOME AS FAMILIA
      ,PRODUTO.VALOR_CUSTO AS PRECO_CUSTO
      ,PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO
      ,PRODUTO.VALOR_VENDA AS PRECO_VENDA
      ,PRODUTO.QTD_ESTOQUE AS QTD
      ,PRODUTO.NCM COD_NCM
      ,SUBSTRING (TRIBUTACAO_ICMS.DESCRICAO, 1,1) AS ST
      ,PRODUTO.CST AS ST
      ,PRODUTO.REFERENCIA AS COD_FABRICANTE
      ,PRODUTO.VALOR_ATACADO AS PRECO_ATACADO
      ,PRODUTO.CUSTO_MEDIO
      ,FORNECEDOR.RAZAO_SOCIAL AS FORNECEDOR
      ,PRODUTO.CEST AS PERSONAL6
  FROM click.dbo.PRODUTO
LEFT JOIN click.dbo.FORNECEDOR ON PRODUTO.ID_FORNECEDOR = FORNECEDOR.ID
LEFT JOIN click.dbo.UNIDADE_PRODUTO ON PRODUTO.ID_UNIDADE_PRODUTO = UNIDADE_PRODUTO.ID
LEFT JOIN click.dbo.TRIBUTACAO_ICMS ON TRIBUTACAO_ICMS.ID = PRODUTO.ID_TRIBUTACAO_ICMS
LEFT JOIN click.dbo.GRUPO_PRODUTO ON GRUPO_PRODUTO.ID = PRODUTO.ID_GRUPO_PRODUTO
LEFT JOIN click.dbo.SUBGRUPO_PRODUTO ON SUBGRUPO_PRODUTO.ID = PRODUTO.ID_SUBGRUPO_PRODUTO