SELECT
       PRODUTOS.CODIGO AS COD_FABRICANTE
      ,PRODUTOS.NOME AS DESCRICAO
      ,GRUPOS.NOME AS GRUPO
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.APLICACAO AS CARACTERISTICAS
      ,PRODUTOS.CBARRA AS BARRAS
      ,PRODUTOS.PESO_LIQ AS PESO
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.DATA_ALTERACAO AS ALTERACAO_PRECO
      ,PRODUTOS.COD_CEST AS COD_CEST
      ,CADFOR.NOME AS FORNECEDOR
      ,PRODLOJAS.EST_MINIM AS QTD_IDEAL
      ,PRODLOJAS.EST_ATUAL AS QTD
      ,PRODLOJAS.PCO_COMPRA AS PRECO_CUSTO
      ,PRODLOJAS.PCO_VENDA AS PRECO_VENDA
	  ,PRODUTOS.CODIGO_NCM AS COD_NCM
  FROM robinho.dbo.PRODUTOS
LEFT JOIN robinho.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = robinho.dbo.PRODUTOS.CODIGO
LEFT JOIN robinho.dbo.GRUPOS ON GRUPOS.CODIGO = robinho.dbo.PRODUTOS.GRUPO
LEFT JOIN robinho.dbo.CADFOR ON CADFOR.CODIGO = robinho.dbo.PRODLOJAS.FORNECEDOR