SELECT
  CLIENTES.CLI_CODIGO AS CODIGO,
  CLIENTES.CLI_CGCCPF AS CNPJ_CNPF,
  CLIENTES.CLI_INSCRI AS IE_RG,
  CLIENTES.CLI_NOME AS NOME,
  --CLIENTES.CLI_NOMEFA AS FANTASIA,
  CLIENTES.CLI_SEXO AS SEXO,
  CLIENTES.CLI_NASCIMENTO AS NASCIMENTO,
  CLIENTES.CLI_ENDERE AS ENDERECO,
  CLIENTES.CLI_BAIRRO ||' - '|| CLIENTES.CLI_DISTRITO AS BAIRRO,
  CLIENTES.CLI_CIDADE AS CIDADE,
  CLIENTES.CLI_ESTADO AS UF,
  CLIENTES.CLI_CEP AS CEP,
  CLIENTES.CLI_FONE AS TELEFONE,
  CLIENTES.CLI_CELULAR AS CELULAR,
  CLIENTES.CLI_FAX AS FAX,
  CLIENTES.CLI_EMAIL AS EMAIL,
  CLIENTES.CLI_PAI AS PAI,
  CLIENTES.CLI_MAE AS MAE,
  CLIENTES.CLI_CIVIL AS EST_CIVIL,
  CLIENTES.CLI_CJ_NOME AS CONJUGE,
  CLIENTES.CLI_LIMITE AS LIMITE_CREDITO,
  CLIENTES.CLI_OBS AS OBSERVACOES,
  CLIENTES.CLI_CADASTRO AS CADASTRO
  --CLIENTES.CLI_CONTATO AS CONTATO
FROM CLIENTES
WHERE CLIENTES.CLI_CODIGO <> '000000'
