SELECT
  FORNECEDORES.CODFORNECEDOR AS CODIGO,
  FORNECEDORES.NOME AS FANTASIA,
  FORNECEDORES.RAZAOSOCIAL AS NOME,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
  BAIRROS.DESCRICAO AS BAIRRO,
  CIDADES.CIDADE AS CIDADE,
  FORNECEDORES.UF AS UF,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.CPF_CNPJ AS CNPJ_CNPF,
  FORNECEDORES.IE_IDENTIDADE AS IE_RG,
  FORNECEDORES.INSCRICAO_MUNICIPAL AS IM,
  FORNECEDORES.TELEFONE1 AS TELEFONE,
  FORNECEDORES.CELULAR AS CELULAR,
  FORNECEDORES.TELEFAX AS FAX,
  FORNECEDORES.REPRESENTANTE AS CONTATO,
  FORNECEDORES.OBS AS OBSERVACOES,
  FORNECEDORES.EMAIL AS EMAIL
FROM FORNECEDORES
LEFT JOIN BAIRROS ON BAIRROS.CODBAIRRO = FORNECEDORES.CODBAIRRO
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = FORNECEDORES.CODCIDADE
