SELECT
  PRODUTOS.CODPRODUTO AS COD_FABRICANTE,
  PRODUTOS.CODBARRA_EAN AS BARRAS,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  PRODUTOS.CODCLASS_TRIBUTARIA_VENDA AS ST,
  PRODUTOS.UNIDADE AS UND,
  PRODUTOS.FATOR_CONVERSAO AS FAT_CONV,
  PRODUTOS.PESO_LIQUIDO AS PESO,
  GRUPOS.GRUPO AS GRUPO,
  FORNECEDORES.NOME AS FORNECEDOR,
  PRODUTOS.VR_VENDA AS PRECO_VENDA,
  PRODUTOS.VR_CUSTO AS PRECO_CUSTO,
  PRODUTOS.VR_CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTOS.MARGEM_LUCRO AS MARGEN_LUCRO,
  PRODUTOS.ESTOQUE AS QTD,
  PRODUTOS.DT_ULT_VENDA AS ULT_VENDA,
  PRODUTOS.DT_ULT_ENTRADA AS ILT_COMPRA,
  PRODUTOS.CODCLASS_FISCAL AS COD_NCM,
  PRODUTOS.OBS AS OBSERVACOES,
  PRODUTOS.CEST AS PERSONAL6,
  PRODUTOS.DT_DESCRICAO AS DATA_CADASTRO
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.CODGRUPOP = PRODUTOS.CODGRUPO
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODFORNECEDOR = PRODUTOS.CODFORNECEDOR
