SELECT
    CODIGO AS CODIGO,
    RAZAOSOCIAL AS NOME,
    NOMEFANT AS FANTASIA,
    CONTATO AS CONTATO,
    CGC AS CNPJ_CNPF,
    INSCEST AS IE_RG,
    EMAIL AS EMAIL,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CEP AS CEP,
    CIDADE AS CIDADE,
    UF AS UF,
    TELEFONE AS TELEFONE
FROM FORNECEDORES