SELECT TB_CADESTOQUE.CODIGO,
TB_CADESTOQUE.CODBARRAS AS COD_FABRICANTE,
TB_CADESTOQUE.DESCRICAO,
TB_CADCLIENTEFORNEC.NOME AS FORNECEDOR,
TB_CADESTOQUE.MEDIDA AS UND,
TB_CADESTOQUE.DATACADASTRO AS DATA_CADASTRO,
TB_CSOSN.CODCSOSN AS ST,
TB_CADNCM.NCM AS COD_NCM,
TB_CADESTOQUE.PRECOVENDA AS PRECO_VENDA,
TB_CADESTOQUE.PRECOCUSTO AS PRECO_CUSTO,
TB_CADESTOQUE.ULTIMAVENDA AS ULTIMA_VENDA,
TB_CADESTOQUE.QTD
FROM TB_CADESTOQUE
LEFT JOIN TB_CADCLIENTEFORNEC ON TB_CADESTOQUE.FORNECEDOR=TB_CADCLIENTEFORNEC.CODIGO
LEFT JOIN TB_CSOSN ON TB_CADESTOQUE.CSTCSOSN=TB_CSOSN.CODIGO
LEFT JOIN TB_CADNCM ON TB_CADESTOQUE.NCM=TB_CADNCM.CODIGO
