SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    GRUPO.DESCRICAO AS GRUPO,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.PESO AS PESO,
    PRODUTO.PR_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.PR_VENDA AS PRECO_VENDA,
    PRODUTO.PRECO_ATACADO AS PRECO_ATACADO,
    PRODUTO.QTD_ATUAL AS QTD,
    PRODUTO.QTD_MIN AS QTD_IDEAL,
    PRODUTO.CSOSN AS ST,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6,
    PRODUTO.ULT_COMPRA AS ULTIMS_COMPRA,
    PRODUTO.DT_CADASTRO AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO