SELECT
    CODIGO,
    NOME,
    ENDERECO,
    NUMERO,
    BAIRRO,
    CIDADE,
    CEP,
    ESTADO AS UF,
    FONE AS TELEFONE,
    CELULAR,
    INSCESTADUAL AS IE_RG,
    COMPLEMENTO,
    EMAIL,
    CPF_CNPJ AS CNPJ_CNPF,
    CONTATO,
    DATA_NASCIMENTO AS NASCIMENTO
FROM CLIENTES
