SELECT
    P.CODIGO AS CODIGO,
    P.DESCRICAO AS DESCRICAO,
    P.BARRAS AS BARRAS,
    P.UNIDADE AS UND,
    P.UNCOMPRA AS UND_COMPRA,
    P.FORNECEDOR AS FORNECEDOR,
    P.MARCA AS FAMILIA,
    P.PESO AS PESO,
    P.ESTOQUEMINIMO AS QTD_IDEAL,
    P.ESTOQUEATUAL AS QTD,
    G.DESCRICAO AS GRUPO,
    P.PRECOCUSTO AS PRECO_CUSTO,
    P.MARGEM AS MARGEM_LUCRO,
    P.PRECOVENDA AS PRECO_VENDA,
    P.TRIBUTARIA AS ST,
    P.REFERENCIA AS COD_FABRICANTE,
    P.NCM AS COD_NCM,
    P.CEST AS PERSONAL6
FROM PRODUTO AS P
LEFT JOIN GRUPO G ON P.GRUPO = G.CODIGO
