SELECT
    PRODUTOS.IDPRODUTO AS CODIGO,
    PRODUTOS.DESCRICAO_PRODUTO AS DESCRICAO,
    UNIDADES_MEDIDA.ABREVIACAO AS UND,
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    ESTOQUES.ESTOQUE AS QTD,
    ESTOQUES.ESTOQUE_MIN AS QTD_IDEAL,
    PRODUTOS.PESO AS PESO,
    GRUPOS_PRODUTO.DESCRICAO_GRUPO AS GRUPO,
    SUBGRUPOS_PRODUTO.DESCRICAO_SUBGRUPO AS FAMILIA,
    ESTOQUES.PRECO_CUSTO AS PRECO_CUSTO,
    ESTOQUES.PRECO_CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.PRECO_ATACADO AS PRECO_ATACADO,
    PRODUTOS.CST_ORIGEM AS OST,
    ESTOQUES.SITUACAO_TRIBUTARIA AS ST,
    ESTOQUES.CFOP_INT AS CF,
    PRODUTOS.OBS_PRODUTO AS OBSERVACOES,
    PRODUTOS.CODIGO_FORNECEDOR AS COD_FABRICANTE,
    ESTOQUES.DATA_COMPRA AS ULTIMA_COMPRA,
    CAST (PRODUTOS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
    CAST (PRODUTOS.DATA_ALTERACAO_PRECO AS DATE) AS ALTERACAO_PRECO,
    PRODUTOS.CLASSIFICACAO_NCM AS COD_NCM,
    ESTOQUES.CEST AS PERSONAL6,
    case when ESTOQUES.SITUACAO_PRODUTO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PRODUTOS
LEFT JOIN UNIDADES_MEDIDA ON UNIDADES_MEDIDA.IDUNIDADE_MEDIDA = PRODUTOS.IDUNIDADE_MEDIDA
LEFT JOIN SUBGRUPOS_PRODUTO ON SUBGRUPOS_PRODUTO.IDSUBGRUPO_PRODUTO = PRODUTOS.IDSUBGRUPO_PRODUTO
LEFT JOIN GRUPOS_PRODUTO ON GRUPOS_PRODUTO.IDGRUPO_PRODUTO = SUBGRUPOS_PRODUTO.IDGRUPO_PRODUTO
LEFT JOIN ESTOQUES ON ESTOQUES.IDPRODUTO = PRODUTOS.IDPRODUTO
