select CLIENTE.ID AS CODIGO,
COALESCE(CLIENTE.DATA_INCLUSAO,CURRENT_DATE) AS CADASTRO,
CLIENTE.NOME_DO_CLIENTE AS NOME,
CLIENTE.CODINOME AS FANTASIA,
CLIENTE.INSC_FEDERAL AS CNPJ_CNPF,
CLIENTE.ENDERECO,
CLIENTE.NUMERO,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.CEP,
CLIENTE.ESTADO AS UF,
CLIENTE.FAX,
CLIENTE.CELULAR,
CLIENTE.DATA_DE_NASCIMENTO AS NASCIMENTO,
CLIENTE.CONTATO,
CLIENTE.NOME_PAI AS PAI,
CLIENTE.NOME_MAE AS MAE,
CLIENTE.NATURALIDADE,
CLIENTE.EMAIL,
CLIENTE.TRABALHO_NOME AS LOC_TRA,
CLIENTE.INSC_ESTADUAL AS IE_RG,
CLIENTE.COMPLEMENTO
FROM CLIENTE




