SELECT
  PEOPLE.ID AS CODIGO,
  PEOPLE.NAME AS NOME,
  PEOPLE.FANTASY AS FANTASIA,
  PEOPLE.CONTACT AS CONTATO,
  PEOPLE.CGC AS CNPJ_CNPF,
  PEOPLE.IERG AS IE_RG,
  PEOPLE.IM AS IM,
  PEOPLE.ADDRESS AS ENDERECO,
  PEOPLE.NUMBER AS NUMERO,
  PEOPLE.NEIGHBORHOOD AS BAIRRO,
  PEOPLE.COMPLEMENT AS COMPLEMENTO,
  PEOPLE.CEP AS CEP,
  PEOPLE.DDD_PHONE||PEOPLE.PHONE AS TELEFONE,
  PEOPLE.DDD_CELL||PEOPLE.CELL_PHONE AS CELULAR,
  PEOPLE.DDD_FAX||PEOPLE.FAX AS FAX,
  PEOPLE.EMAIL AS EMAIL,
  PEOPLE.CREDIT_LIMIT AS LIMITE_CREDITO,
  PEOPLE.LAST_SALE AS ULTIMA_VENDA,
  PEOPLE.DATE_BIRTHDAY AS NASCIMENTO,
  PEOPLE.OBSERVATION AS OBSERVACOES,
  PEOPLE.DATE_REGISTER AS CADASTRO,
  CASE PEOPLE.INDICATOR_IE 
  WHEN 1 THEN 'C'
  WHEN 2 THEN 'I'
  WHEN 9 THEN 'N' END AS INDIEDEST,
  CITY.DESCRIPTION AS CIDADE,
  CITY.UF AS UF
FROM PEOPLE
LEFT JOIN CITY ON CITY.ID = PEOPLE.ID_CITY
RIGHT JOIN CUSTOMER ON CUSTOMER.ID_PEOPLE = PEOPLE.ID





