SELECT 
  PEOPLE.ID AS CODIGO,
  PEOPLE.NAME AS NOME,
  PEOPLE.FANTASY AS FANTASIA,
  PEOPLE.CONTACT AS CONTATO,
  PEOPLE.CGC AS CNPJ_CNPF,
  PEOPLE.IERG AS IE_RG,
  PEOPLE.IM AS IM,
  PEOPLE.ADDRESS AS ENDERECO,
  PEOPLE.NUMBER AS NUMERO,
  PEOPLE.NEIGHBORHOOD AS BAIRRO,
  PEOPLE.COMPLEMENT AS COMPLEMENTO,
  PEOPLE.CEP,
  PEOPLE.DDD_PHONE||PEOPLE.PHONE AS TELEFONE,
  PEOPLE.DDD_CELL||PEOPLE.CELL_PHONE AS CELULAR,
  PEOPLE.DDD_FAX||PEOPLE.FAX AS FAX,
  PEOPLE.EMAIL AS EMAIL,
  PEOPLE.DATE_REGISTER AS CADASTRO,
  CITY.DESCRIPTION AS CIDADE,
  CITY.UF
FROM PEOPLE
LEFT JOIN CITY ON CITY.ID = PEOPLE.ID_CITY
RIGHT JOIN PROVIDER ON PROVIDER.ID_PEOPLE = PEOPLE.ID
