SELECT 
  PRODUCT.ID AS CODIGO,
  PRODUCT.CODBARS AS BARRAS,
  PRODUCT.DESCRIPTION AS DESCRICAO,
  PRODUCT.DATEREGISTER AS DATA_CADASTRO,
--ICMSCST.CODIGO AS ST,
--PRODUCT.PICMS AS ST,  
  PRODUCT.CSOSN AS ST,
  REPLACE(PRODUCT.NCM,'.','') AS COD_NCM,
  UNITMEASUREMENT.SYMBOL AS UND,
  PRODUCT.PRICESALE AS PRECO_VENDA,
  PRODUCT.GROSSPROFIT AS MARGEM_LUCRO,
  PRODUCT.PRICECOST AS PRECO_CUSTO,
  PRODUCT.COST_MEDIUM AS CUSTO_MEDIO,
  PRODUCT.WHOLESALE_PRICE AS PRECO_ATACADO,
  PRODUCT.WHOLESALE_QUANTITY AS QTD_PRECO_ATACADO, 
  PRODUCT.AMOUNT_MIN AS QTD_IDEAL,
  PRODUCT.LASTPURCHASE AS ULTIMA_COMPRA,
  PRODUCT.LASTSALE AS ULTIMA_VENDA,
  PRODUCT.QUANTITYSTOCK AS QTD,
  PRODUCT.LOCATION AS PERSONAL1,
  PRODUCT.WEIGHT AS PESO,
  PRODUCT.COMMISSION AS COMISSAO,
  PRODUCT.REFERENCE AS COD_FABRICANTE,
--PRODUCT.IPI_ALIQUOTSTANDARD,
  PRODUCT.PERCENTAGEIPI AS ALIQ_IPI_VENDA,
  PRODUCT.PERCENTAGEPIS AS PIS_ALIQ_NOR,
  PRODUCT.PERCENTAGECOFINS AS COFINS_ALIQ_NOR,
  CSTIPI.CSTIPI AS IPI_CODIGO_VENDA, 
  PRODUCT.CSTPIS AS PIS_CODIGO,
  PRODUCT.CSTCOFINS AS COFINS_CODIGO,
  PRODUCT.CBENEF AS CBENEF,
  REPLACE (PRODUCT.CFOP_OUTPUT_NFCE,'.','') AS CF,
  LEFT (REPLACE (PRODUCT.CFOP_OUTPUT_NFCE,'.',''),3) AS ELO,
  CASE PRODUCT.ACTIVE WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
  TYPEPRODUCT.VALUE_TYPE ||' '||TYPEPRODUCT.DESCRIPTION AS TIPO_ITEM,
  REPLACE (CEST.CEST,'.','') AS PERSONAL6,
  PRODUCTGROUP.DESCRIPTION AS GRUPO,
  PRODUCTSUBGROUP.DESCRIPTION AS FAMILIA,
  DEPARTMENT.DESCRIPTION AS PERSONAL2
FROM PRODUCT
LEFT JOIN UNITMEASUREMENT ON UNITMEASUREMENT.ID = PRODUCT.COD_MEASURE
LEFT JOIN CSTIPI ON CSTIPI.ID = PRODUCT.CSTIPI 
LEFT JOIN ICMSCST ON ICMSCST.ID = PRODUCT.CST_ICMS 
LEFT JOIN CEST ON CEST.ID = PRODUCT.IDCEST 
LEFT JOIN TYPEPRODUCT ON TYPEPRODUCT.ID = PRODUCT.ID_TYPEPRODUCT
LEFT JOIN PRODUCTGROUP ON PRODUCTGROUP.ID = PRODUCT.ID_GROUP
LEFT JOIN PRODUCTSUBGROUP ON PRODUCTSUBGROUP.ID = PRODUCT.ID_SUBGROUP
LEFT JOIN DEPARTMENT ON DEPARTMENT.ID  = PRODUCT.ID_DEPARTMENT 