SELECT
    CODIGO AS CODIGO,
    FORNECEDOR AS NOME,
    FANTASIA AS FANTASIA,
    case when CPF = '' or CPF is null then CNPJ else CPF END AS CNPJ_CNPF,
    IE AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPL AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    EMAIL AS EMAIL,
    FOR_OBS AS OBSERVACOES
FROM FORNECEDORES