SELECT
  TBFORNECEDOR.CODIGO AS CODIGO,
  TBFORNECEDOR.FANTASIA AS NOME,
  TBFORNECEDOR.CGC AS CNPJ_CNPF,
  TBFORNECEDOR.FORNECEDOR  AS FANTASIA,
  TBFORNECEDOR.INSCRICAO AS IE_RG,
  TBFORNECEDOR.ENDERECO AS ENDERECO,
  TBFORNECEDOR.BAIRRO AS BAIRRO,
  TBFORNECEDOR.CIDADE AS CIDADE,
  TBFORNECEDOR.CEP AS CEP,
  TBFORNECEDOR.UF AS UF,
  TBFORNECEDOR.FONE AS TELEFONE,
  TBFORNECEDOR.FONE1 AS CELULAR,
  TBFORNECEDOR.FONE_FAX AS FAX,
  TBFORNECEDOR.EMAIL AS EMAIL,
  TBFORNECEDOR.CONTATO1 AS CONTATO,
  TBFORNECEDOR.OBS AS OBSERVACOES
FROM TBFORNECEDOR
