SELECT 
PRODUTOS.[CÓDIGO] AS CODIGO,
PRODUTOS.[DESCRIÇÃO] AS DESCRICAO,
PRODUTOS.PRODUTOGTIN AS PERSONAL2,
PRODUTOS.PRODUTOREFERENCIA AS COD_FABRICANTE,
PRODUTOS.PRODUTOBUSCA AS PERSONAL1,
PRODUTOS.PRODUTONCM AS COD_NCM,
CASE PRODUTOS.ATIVO WHEN '1' THEN 'Ativo' WHEN '0' THEN 'Inativo' END AS SITUACAO,
PRODUTOS.UNA AS UND,
PRODUTOS.[Comentários] AS OBSERVACAO,
PRODUTOS.PESO,
PRODUTOS.DIAS AS VALIDADE_DIAS,
PRODUTOS.COMISSAOPERCENTUAL AS COMISSAO,
PRODUTOS.[ESTOQUEMÍNIMO] AS QTD_IDEAL,
--PRODUTOS.PRODUTOCEST AS PERSONAL6,
PRODUTOS.PRODUTOANP AS COD_ANP,
PRODUTOSPRECOSDEVENDA.PRECO AS PRECO_VENDA,
PRODUTOSPRECOSDEVENDA.LUCRO AS MARGEM_LUCRO,
PRODUTOSESTOQUES.QDE AS QTD,
CATEGORIAS.[DESCRIÇÃO] AS GRUPO,
SETORES.[DESCRIÇÃO] AS FAMILIA,
PRODUTOSCODIGOSDEBARRAS.CODIGODEBARRAS AS BARRAS,
MAX(FORNECEDORES.NOME) AS FORNECEDOR,
MAX (CEST.CEST) AS PERSONAL6
FROM PRODUTOS
LEFT JOIN CATEGORIAS ON PRODUTOS.CATEGORIA=CATEGORIAS.[CÓDIGO]
LEFT JOIN SETORES ON PRODUTOS.SETOR=SETORES.[CÓDIGO]
LEFT JOIN PRODUTOSPRECOSDEVENDA ON PRODUTOS.[CÓDIGO]=PRODUTOSPRECOSDEVENDA.PRODUTOID
LEFT JOIN PRODUTOSESTOQUES ON PRODUTOS.[CÓDIGO]=PRODUTOSESTOQUES.PRODUTOID
LEFT JOIN PRODUTOS_FORNECEDORES ON PRODUTOS_FORNECEDORES.PRODUTO = PRODUTOS.[CÓDIGO] 
LEFT JOIN FORNECEDORES ON FORNECEDORES.[CÓDIGO] = PRODUTOS_FORNECEDORES.FORNECEDOR 
LEFT JOIN PRODUTOSCODIGOSDEBARRAS ON PRODUTOSCODIGOSDEBARRAS.PRODUTOID = PRODUTOS.[CÓDIGO] AND PRODUTOSCODIGOSDEBARRAS.ATIVO = '1'
LEFT JOIN CEST ON CEST.NCM = PRODUTOS.PRODUTONCM
GROUP BY  
	PRODUTOS.[CÓDIGO],
    PRODUTOS.[DESCRIÇÃO],
    PRODUTOS.PRODUTOGTIN,
    PRODUTOS.PRODUTOREFERENCIA,
    PRODUTOS.PRODUTOBUSCA,
    PRODUTOS.PRODUTONCM,
    PRODUTOS.ATIVO,
    PRODUTOS.UNA,
    PRODUTOS.PESO,
    PRODUTOS.DIAS,
    PRODUTOS.COMISSAOPERCENTUAL,
    PRODUTOS.[ESTOQUEMÍNIMO],
    PRODUTOS.PRODUTOANP,
    PRODUTOSPRECOSDEVENDA.PRECO,
    PRODUTOSPRECOSDEVENDA.LUCRO,
    PRODUTOSESTOQUES.QDE,
    CATEGORIAS.[DESCRIÇÃO],
    SETORES.[DESCRIÇÃO],
    PRODUTOSCODIGOSDEBARRAS.CODIGODEBARRAS,
	PRODUTOS.[Comentários]