SELECT FORNECEDORES.CODFOR AS CODIGO,
       FORNECEDORES.CNPJFO AS CNPJ_CNPF,
       FORNECEDORES.INSFOR AS IE_RG,
       FORNECEDORES.RAZFOR AS NOME,
       FORNECEDORES.FANFOR AS FANTASIA,
       FORNECEDORES.ENDERE AS ENDERECO,
       FORNECEDORES.BAIRRO AS BAIRRO,
       FORNECEDORES.CEPFOR AS CEP,
       CIDADES.CIDADE AS CIDADE,
       FORNECEDORES.ESTADO AS UF,
       FORNECEDORES.FO1FOR AS TELEFONE,
       FORNECEDORES.FAXFOR AS FAX,
       FORNECEDORES.CONTAT AS CONTATO,
       FORNECEDORES.EMAFOR AS EMAIL,
       FORNECEDORES.OBSERV AS OBSERVACOES
FROM FORNECEDORES
     LEFT JOIN CIDADES ON CIDADES.CODCID = FORNECEDORES.ID_CODCID
