SELECT 
  P.ID_PRD AS CODIGO
, P.CODIGO_PRD AS BARRAS
, P.REFERENCIA_PRD AS COD_FABRICANTE
-- , P.CODIGO_FORNECEDOR_PRD AS COD_FABRICANTE
, P.DESCRICAO_PRD AS DESCRICAO
, P.UNIDADE_VENDA_PRD AS UND
, P.TAMANHO_PRD AS TAMANHO
, P.NCM_PRD AS COD_NCM
, P.PESO_BRUTO_PRD AS PESO
, P.UNIDADE_COMPRA_PRD AS UND_COMPRA
, P.ID_ORG AS OST 
, P.IPPT_PRD AS IPPT
, P.FATOR_CONVERSAO_PRD AS FAT_CONV
, P.CEST_PRD AS PERSONAL6
, P.OBSERVACAO_SISTEMA_PRD AS OBSERVACOES
-- , CAST (P.DATA_CADASTRO_PRD AS DATE) AS CADASTRO
, CASE P.STATUS_PRD WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, GP.NOME_GRP AS GRUPO
, M.DESCRICAO_MRC AS FAMILIA
, ALE.QUANTIDADE_ATUAL_ALE AS QTD
, ALE.PRECO_CUSTO_ALE AS PRECO_CUSTO
, ALE.PERC_MARKUP_ALE AS MARGEM_LUCRO
, ALE.PRECO_VENDA_ALE AS PRECO_VENDA
, ALE.QUANTIDADE_MINIMA_ALE AS QTD_IDEAL
, ALE.ID_ICM_SAIDA AS ST  
, ALE.ALIQUOTA_IPIENTRADA_ALE AS ALIQ_IPI
, ALE.ID_IPI_ENTRADA AS IPI_CODIGO 
, ALE.ALIQUOTA_IPI_ALE AS ALIQ_IPI_VENDA 
, ALE.ID_IPI_SAIDA AS IPI_CODIGO_VENDA
, ALE.ID_PSC_ENTRADA AS PISE_CODIGO
, ALE.ID_PSC_ENTRADA AS COFINSE_CODIGO
, ALE.ID_PSC_SAIDA AS PIS_CODIGO
, ALE.ID_PSC_SAIDA AS COFINS_CODIGO 
, ALE.PERC_COMISSAO_ALE AS COMISSAO 
, ALE.QUANTIDADE_MINIMA_VENDA2_ALE AS QTD_PRECO_ATACADO
, LEFT (ALE.ID_CFP_SAIDA, 3 ) AS ELO
, CAST (ALE.DATA_ULTIMACOMPRA_ALE AS DATE) AS ULTIMA_COMPRA
, CAST (ALE.DATA_ULTIMAVENDA_ALE AS DATE) AS ULTIMA_VENDA
FROM PRODUTOS P
LEFT JOIN GRUPOS_PRODUTOS GP ON GP.ID_GRP = P.ID_GRP 
LEFT JOIN MARCAS M ON M.ID_MRC = P.ID_MRC 
LEFT JOIN ALMOXARIFADOS_ESTOQUE ALE ON ALE.ID_PRD = P.ID_PRD AND ALE.ID_ALM = '1'
