SELECT FORNECE.CODIGO,
FORNECE.NOME,
FORNECE.FANTASIA,
FORNECE.ENDERECO,
FORNECE.BAIRRO,
FORNECE.CIDADE,
FORNECE.TELEFONE1 AS TELEFONE,
FORNECE.TELEFONE2 AS CELULAR,
FORNECE.FAX,
FORNECE.CGC_CPF AS CNPJ_CNPF,
FORNECE.INSC_ESTADUAL_RG AS IE_RG,
FORNECE.CONTATO,
FORNECE.ESTADO AS UF,
FORNECE.CEP,
FORNECE.EMAIL,
FORNECE.NUMERO
FROM FORNECE




