SELECT 
       CLIENTES.CODIGO AS CODIGO
      ,CLIENTES.NOME AS FANTASIA
      ,CLIENTES.RAZAO AS NOME
      ,CLIENTES.FONE AS TELEFONE
      ,CLIENTES.CELULAR AS CELULAR
      ,CLIENTES.FAX AS FAX
      ,CLIENTES.CONTATO AS CONTATO
      ,CLIENTES.EMAIL AS EMAIL
      ,CLIENTES.ENDERECO AS ENDERECO
      ,CLIENTES.CEP AS CEP
      ,CLIENTES.BAIRRO AS BAIRRO
      ,CLIENTES.CIDADE AS CIDADE
      ,CLIENTES.ESTADO AS UF
      ,CLIENTES.INS_RG AS IE_RG
      ,CLIENTES.CGC_CPF AS CNPJ_CNPF
      ,CLIENTES.N_PAI AS PAI
      ,CLIENTES.N_MAE AS MAE
      ,CLIENTES.NATURALID AS NATURALIDADE
      ,CLIENTES.DATA_NASC AS NASCIMENTO
      ,CLIENTES.DATA_CAD AS CADASTRO
      ,CLIENTES.PROFISS AS PROFISSAO
      ,CLIENTES.EST_CIVIL AS EST_CIVIL
      ,CLIENTES.CONJUGE AS CONJUGE
      ,CLIENTES.LIMITE_CR AS LIMITE_CREDITO
      ,CONCAT (CLIENTES.OBJS, ' -  ' ,CLIENTES.INFOADICIONAIS) AS OBSERVACOES
      ,CLIENTES.NUMERO_END AS NUMERO
      ,CLIENTES.INSC_MUNICIPAL AS IM
      ,CLIENTES.SEXO AS SEXO
  FROM ESTANCELL.dbo.CLIENTES