SELECT 
       CADFOR.CODIGO AS CODIGO
      ,CADFOR.NOME AS FANTASIA
      ,CADFOR.RAZAO AS NOME
      ,CADFOR.FONE AS TELEFONE
      ,CADFOR.FAX AS FAX
      ,CADFOR.CONTATO AS CONTATO
      ,CADFOR.ENDERECO AS ENDERECO
      ,CADFOR.CEP AS CEP
      ,CADFOR.BAIRRO AS BAIRRO
      ,CADFOR.CIDADE AS CIDADE
      ,CADFOR.ESTADO AS UF
      ,CADFOR.INSCR AS IE_RG
      ,CADFOR.CGC AS CNPJ_CNPF
      ,CONCAT (CADFOR.OBJS, ' ' ,CADFOR.INFOADICIONAIS) AS OBSERVACOES
      ,CADFOR.EMAIL AS EMAIL
      ,CADFOR.INSC_MUNICIPAL AS IM
      ,CADFOR.NUMERO_END AS NUMERO
  FROM ESTANCELL.dbo.CADFOR