SELECT
    FORNEC.CDFRN AS CODIGO,
    FORNEC.FANTASIAFORNEC AS FANTASIA,
    FORNEC.RAZAO AS NOME,
    case when FORNEC.CPF = '' or FORNEC.CPF is null then FORNEC.CGC else FORNEC.CPF END AS CNPJ_CNPF,
    FORNEC.INSCEST AS IE_RG,
    FORNEC.INSCMUNI AS IM,
    FORNEC.ENDERECO AS ENDERECO,
    FORNEC.NUMERO AS NUMERO,
    FORNEC.COMPLEMENTO AS COMPLEMENTO,
    BAIRRO.BAIRRO AS BAIRRO,
    CIDADE.CIDADE AS CIDADE,
    CIDADE.ESTADO AS UF,
    FORNEC.CEP AS CEP,
    FORNEC.FAX AS FAX,
    FORNEC.CONTATO AS CONTATO,
    FORNEC.TELEFONE AS TELEFONE,
    FORNEC.CELULAR AS CELULAR,
    FORNEC.EMAIL AS EMAIL,
    FORNEC.OBS AS OBSERVACOES
FROM FORNEC
LEFT JOIN BAIRRO ON BAIRRO.CODBAI = FORNEC.CDBAI
LEFT JOIN CIDADE ON CIDADE.CODCID = FORNEC.CDCID