SELECT
    MERCAD.CDMRC AS BARRAS,
    MERCAD.DESCRMERC AS DESCRICAO,
    FORNEC.RAZAO AS FORNECEDOR,
    MERCAD.PESOLIQ AS PESO,
    MERCAD.CDMRCFRN AS COD_FABRICANTE,
    GRUPO.DESCRGRUPO AS GRUPO,
    SUBGRUPO.DESCRSGRUPO AS FAMILIA,
    MERCAD.CDUND AS UND,
    MERCAD.MARCA AS CARACTERISTICAS,
    MERLOJ.SDATEST AS QTD,
    IMPOSTOMERC.CST AS ST,
    MERCAD.CUSTO AS PRECO_CUSTO,
    MERCAD.CUSTOMED AS CUSTO_MEDIO,
    MERCAD.PRVENDA1 AS PRECO_VENDA,
    MERCAD.DATULTVND AS ULTIMA_VENDA,
    MERCAD.DATACAD AS DATA_CADASTRO,
    MERCAD.OBS AS OBSERVACOES,
    IMPOSTOMERC.NCM AS COD_NCM,
    IMPOSTOMERC.CEST AS PERSONAL6
FROM MERCAD
LEFT JOIN FORNEC ON FORNEC.CDFRN = MERCAD.CDFRN
LEFT JOIN GRUPO ON GRUPO.CDGRUPO = MERCAD.CDGRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CDSGRUPO = MERCAD.CDSGRUP
LEFT JOIN MERLOJ ON MERLOJ.CDMRC = MERCAD.CDMRC
LEFT JOIN IMPOSTOMERC ON IMPOSTOMERC.CDMRC = MERCAD.CDMRC
