SELECT
    PRODUTOS.CD_PRD AS CODIGO,
    PRODUTOS.DS_PRD AS DESCRICAO,
    PRODUTOS.NM_FAB AS CARACTERISTICAS,
    GRUPOS_PRODUTO.ds_grp AS GRUPO,
    PRODUTOS.CD_BAR AS BARRAS,
    PRODUTOS.NR_PSO_LIQ AS PESO,
    PRODUTOS.NR_EST_MIN AS QTD_IDEAL,
    PRODUTOS_ESTOQUE.nr_qtd AS QTD,
    PRODUTOS.TP_UNI_CMP AS UND_COMPRA,
    PRODUTOS.TP_UNI_VND AS UND,
    PRODUTOS.NR_VLR_VST AS PRECO_VENDA,
    PRODUTOS.DT_ULT_CMP AS ULTIMA_COMPRA,
    PRODUTOS.DT_ULT_VND AS ULTIMA_VENDA,
    PRODUTOS.NR_NCM AS COD_NCM,
    PRODUTOS.CD_CES AS PERSONAL6
from PRODUTOS
LEFT JOIN grupos_produto ON GRUPOS_PRODUTO.cd_grp = PRODUTOS.CD_GRP
LEFT JOIN PRODUTOS_ESTOQUE ON PRODUTOS_ESTOQUE.cd_prd = PRODUTOS.CD_PRD
