SELECT 
  CODIGO
, NOME
, NOMEFANTASIA AS FANTASIA
, CNPJCPF AS CNPJ_CNPF
, RGINSC AS IE_RG
, IM
, END_RES AS ENDERECO
, COMPLEMENTO_RES AS COMPLEMENTO
, BAIRRO_RES AS BAIRRO
, CID_RES AS CIDADE
, CEP_RES AS CEP
, UF_RES AS UF
, EMAIL
, NOMEPAI AS PAI
, NOMEMAE AS MAE
, NOMECONJUGUE AS CONJUGE
, OBSERVACAO AS OBSERVACOES
, EMPRESA AS LOCTRA
, CONTATO
, VALORCRED AS LIMITE_CREDITO
, END_COB AS COB_ENDERECO
, BAIRRO_COB AS COB_BAIRRO
, CID_COB AS COB_CIDADE
, CEP_COB AS COB_CEP
, UF_COB AS COB_UF
, DATACADASTRO AS CADASTRO
, CARGO AS PROFISSAO
, ESTADOCIVIL AS EST_CIVIL
, SUBSTRING (FONE_RESID FROM 1 FOR 16) AS TELEFONE
, SUBSTRING (FAX FROM 1 FOR 16) AS FAX
, SUBSTRING (CELULAR FROM 1 FOR 16) AS CELULAR
, FONE_RESID AS PERSONAL1
, FAX AS PERSONAL2
, CELULAR AS PERSONAL3
FROM CLIENTE