SELECT 
  CODIGO
, RAZAOSOCIAL AS NOME
, NOMEFANTASIA AS FANTASIA
, IE AS IE_RG
, CNPJ AS CNPJ_CNPF
, ENDERECO
, BAIRRO
, CIDADE
, CEP
, UF
, EMAIL
, OBSERVACAO AS OBSERVACOES
, CONTATO
, SUBSTRING (FONE FROM 1 FOR 16) AS TELEFONE
, SUBSTRING (FAX FROM 1 FOR 16) AS FAX
, SUBSTRING (CELULAR FROM 1 FOR 16) AS CELULAR
, FONE AS PERSONAL1
, FAX AS PERSONAL2
, CELULAR AS PERSONAL3
, SITE AS PERSONAL4
FROM FORNEC