SELECT 
  P.CODIGO
, P.CBARRAS AS BARRAS 
, P.DESCRICAO
, P.UNIDADE AS UND
, P.ESTOQUE AS QTD
, P.MINIMO AS QTD_IDEAL
, P.VRVENDA AS PRECO_VENDA
, P.VRCUSTO AS PRECO_CUSTO
, P.PLUCRO AS MARGEM_LUCRO
, P.NBM AS COD_NCM
, P.CUSTOMEDIO AS CUSTO_MEDIO
, P.PESOBRUTOPROD AS PESO
, CASE P.SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.TAMANHO
, P.REFERENCIA AS COD_FABRICANTE
, P.PCOMISSOES AS COMISSAO
, P.LOCALIZACAO AS PERSONAL1
, P.MARCA AS CARACTERISTICAS
, P.PIPI AS ALIQ_IPI_VENDA
, P.DTULTCOMPRA AS ULTIMA_COMPRA
, P.DIASVALIDADE AS VALIDADE_DIAS
, P.CEST AS PERSONAL6
--, P.CODSITRIBUT
--, P.CSOSN AS ST
, P.CSOSNFISICO AS ST
, P.PPIS AS PIS_ALIQ_NOR
, P.PCOFINS AS COFINS_ALIQ_NOR
--, P.PIS_CST
--, P.COFINS_CST
, G.DESCRICAO AS GRUPO
, SUBSTRING (T.CFOP_DENTRO_UF FROM 1 FOR 3) AS ELO
, T.PIS_CST AS PIS_CODIGO
, T.COFINS_CST AS COFINS_CODIGO
FROM PRODUTO P
LEFT JOIN GRUPO G ON G.CODIGO = P.GRUPO  
LEFT JOIN TRIBUT T ON T.CODIGO = P.TRIBUT 