SELECT
  PRODUTOS.ID AS CODIGO,
PRODUTOS.DESCRICAO AS DESCRICAO,
PRODUTOS.DESCRICAO_RESUMIDA AS OBSERVACOES,
  PRODUTOS.GTIN_TRIBUTACAO AS BARRAS,
  PRODUTOS.UNIDADE_COMERCIAL AS UND,
  PRODUTOS.QUANTIDADE_COMERCIAL AS QTD,
  TABELAPRECO_ITENS.VALOR_COMERCIAL AS PRECO_VENDA,
  PRODUTOS.CST AS ST,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN TABELAPRECO_ITENS ON TABELAPRECO_ITENS.PRODUTO_ID = PRODUTOS.ID 
