SELECT
    CODIGO AS CODIGO,
    RAZAO_SOCIAL AS NOME,
    NOME_FANTASIA AS FANTASIA,
    TELEFONE AS TELEFONE,
    FAX AS FAX,
    E_MAIL AS EMAIL,
    ENDERECO AS ENDERECO,
    BAIRRO,
    CIDADE,
    CEP,
    UF,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    NUMERO AS NUMERO,
    TELEFONE2 AS CELULAR
FROM FORNECEDOR