SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    FORNECEDOR.RAZAO_SOCIAL AS NOME,
    FORNECEDOR.NOME AS FANTASIA,
    FORNECEDOR.CONTATO_RESP AS CONTATO,
    FORNECEDOR.CGC AS CNPJ_CNPF,
    FORNECEDOR.IE AS IE_RG,
    FORNECEDOR.RUA AS ENDERECO,
    FORNECEDOR.NUMERO AS NUMERO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    CIDADE.CEP AS CEP,
    FORNECEDOR.FONE AS TELEFONE,
    FORNECEDOR.EMAIL AS EMAIL
FROM FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.CODIGO = FORNECEDOR.CODCID
