SELECT
    PRODUTOS.CODIGO AS CODIGO,
    PRODUTOS.NOME AS DESCRICAO,
    replace(PRODUTOS.COD_EAN,'.','') AS BARRAS,
    PRODUTOS.COMPOSTO_POR AS UND,
    PRODUTOS.CODPROD AS CARACTERISTICAS,
    FORNECEDOR.NOME AS FORNECEDOR,
    PRODUTOS.SLD_ATUAL AS QTD,
    PRODUTOS.PRECO_CUSTO_UNITARIO AS PRECO_CUSTO,
    PRODUTOS.CUSTOMED AS CUSTO_MEDIO,
    PRODUTOS.PERCENTUAL AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VEND AS PRECO_VENDA,
    SUBSTRING (PRODUTOS.CLASSIFIC_FISCAL FROM 1 FOR 1) AS OST,
    PRODUTOS.CSOSN AS ST,
    PRODUTOS.CD_DO_FORN AS COD_FABRICANTE,
    PRODUTOS.DATA_CAD AS DATA_CADASTRO,
    PRODUTOS.APLICACAO AS OBSERVACOES,
    PRODUTOS.CLAS_FISCAL AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTOS.CODFORN
