SELECT CLIENTES.CODIGO AS CODIGO,
CLIENTES.NOME AS NOME,
CLIENTES.FANTASIA AS FANTASIA,
CLIENTES.ENDERECO AS ENDERECO,
CLIENTES.CLINUMEROEND AS NUMERO,
CLIENTES.COMPLEMENTO AS COMPLEMENTO,
CLIENTES.BAIRRO AS BAIRRO,
CIDADES.CIDADE AS CIDADE,
CIDADES.ESTADO AS UF,
CLIENTES.CEP AS CEP,
CLIENTES.CNPJ_CPF AS CNPJ_CNPF,
CLIENTES.INSCRICAOESTADUAL_RG AS IE_RG,
CLIENTES.TELEFONE AS TELEFONE,
CLIENTES.CELULAR AS CELULAR,
CLIENTES.CONTATO AS CONTATO,
CLIENTES.EMAIL AS EMAIL,
CLIENTES.DTNASCIMENTO AS NASCIMENTO
FROM CLIENTES
LEFT JOIN CIDADES ON CIDADES.CODIGO = CLIENTES.CODCIDADE
