SELECT FORNECEDORES.CODIGO AS CODIGO,
FORNECEDORES.RAZAO AS NOME,
FORNECEDORES.FANTASIA AS FANTASIA,
FORNECEDORES.ENDERECO AS ENDERECO,
FORNECEDORES.NUMERO AS NUMERO,
FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
FORNECEDORES.BAIRRO AS BAIRRO,
CIDADES.CIDADE AS CIDADE,
CIDADES.ESTADO AS UF,
FORNECEDORES.CEP AS CEP,
FORNECEDORES.CNPJ AS CNPJ_CNPF,
FORNECEDORES.INSCRICAO AS IE_RG,
FORNECEDORES.TELEFONE AS TEFEFONE,
FORNECEDORES.FAX AS FAX,
FORNECEDORES.EMAIL AS EMAIL,
FORNECEDORES.CONTATO AS CONTATO,
FORNECEDORES.DTCADASTRO AS CADASTRO
FROM FORNECEDORES
LEFT JOIN CIDADES ON CIDADES.CODIGO = FORNECEDORES.CODCIDADE
