SELECT
    CLIFOR.CHAVE AS CODIGO,
    CLIFOR.CGCCPF AS CNPJ_CNPF,
    CLIFOR.INSCEST AS IE_RG,
    CLIFOR.INSCMUN AS IM,
    CLIFOR.NOME AS NOME,
    CLIFOR.ENDERECO AS ENDERECO,
    CLIFOR.NUMERO AS NUMERO,
    CLIFOR.BAIRRO AS BAIRRO,
    CLIFOR.COMPLEMENTO AS COMPLEMENTO,
    CLIFOR.CEP AS CEP,
    CLIFOR.CIDADE AS CIDADE,
    CLIFOR.ESTADO AS UF,
    CLIFOR.DDDFONE ||''|| CLIFOR.TELEFONE AS TELEFONE,
    CLIFOR.DDDFONE2 ||''|| CLIFOR.TELEFONE2 AS CELULAR,
    CLIFOR.DDDFAX ||''|| CLIFOR.FAX AS FAX,
    CLIFOR.EMAIL AS EMAIL,
    CLIFOR.CONTATO AS CONTATO,
    CLIFOR.OBSERVACAO1 AS OBSERVACOES
FROM CLIFOR
WHERE CLIFOR.TIPO = '1'   --- FORNECEDORES
