SELECT
    ESTOQUE.CODIGO AS CODIGO,
    ESTOQUE.PRODUTO AS DESCRICAO,
    ESTOQUE.UNIDADE AS UND,
    ESTOQUE.ESTOQUE AS QTD,
    GRUPOS.DESCRICAO AS GRUPO,
    ESTOQUE.PCO_CUSTO AS PRECO_CUSTO,
    ESTOQUE.PCO_VENDA AS PRECO_VENDA,
    ESTOQUE.CODBARRA AS BARRAS,
    ESTOQUE.CST AS ST,
    ESTOQUE.COD_NCM AS COD_NCM,
    ESTOQUE.CEST AS PERSONAL6
FROM ESTOQUE
LEFT JOIN GRUPOS ON ESTOQUE.GRUPO = GRUPOS.CODIGO
