SELECT 
       PRODUTOS.CODIGO AS CODIGO
      ,PRODUTOS.CODLOJA
      ,PRODUTOS.NOME AS DESCRICAO
      ,PRODUTOS.CBARRA AS BARRAS
      ,GRUPOS.NOME AS GRUPO
      ,SUB_GRUPOS.NOME AS FAMILIA
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.UNIDADE_COMPRA AS UND_COMPRA
      ,PRODUTOS.PESO_LIQ AS PESO
      ,PRODLOJAS.EST_MINIM AS QTD_IDEAL
      ,PRODLOJAS.EST_ATUAL AS QTD
      ,PRODLOJAS.PCO_COMPRA AS PRECO_CUSTO
      ,PRODLOJAS.PCO_VENDA AS PRECO_VENDA
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.ORIGINAL AS COD_FABRICANTE
      ,PRODUTOS.APLICACAO AS OBSERVACOES
      ,CAST (PRODLOJAS.DAT_VENDA AS DATE) AS ULTIMA_VENDA
      ,CAST (PRODLOJAS.DAT_COMPRA AS DATE) AS ULTIMA_COMPRA
      ,CAST (PRODUTOS.DATA_ALTERACAO AS DATE) AS ALTERACAO_PRECO
      ,PRODUTOS.CODIGO_NCM AS COD_NCM
      ,PRODUTOS.COD_CEST AS PERSONAL6
  FROM DESTINO.dbo.PRODUTOS
LEFT JOIN DESTINO.dbo.GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO
LEFT JOIN DESTINO.dbo.SUB_GRUPOS ON SUB_GRUPOS.CODIGO = PRODUTOS.SUBG
LEFT JOIN DESTINO.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = PRODUTOS.CODIGO
