SELECT
	ID_EMPRESA AS CODIGO,
	"NOME" AS RAZAO_SOCIAL,
	CNPJ_CPF AS CNPJ,
	IE_RG,
	ENDERECO||','||ENDERECO_NUMERO||','||CEP||','||"BAIRRO" AS ENDERECO,
	"TELEFONE",
	"EMAIL",
	CIDADE,
	ESTADO AS UF
FROM
	EMPRESAS
WHERE TRANSPORTADORA = 'S'
