SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.COD_BARRAS AS BARRAS,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.PESO_LIQUIDO AS PESO,
    PRODUTO_ESTOQUE.estoque_atual AS QTD,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTO.PERC_LUCRO AS MARGEM_LUCRO,
    PRODUTO.PRECO_VENDA AS PRECO_VENDA, 
    GRUPO_PRODUTOS.descricao AS GRUPO,
    SUBSTRING(PRODUTO.CST_SAIDA FROM 2 FOR 3) AS ST,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.ULTIMA_VENDA AS ULTIMA_VENDA,
    PRODUTO.ULTIMA_COMPRA AS ULTIMA_COMPRA,
    PRODUTO.OBSERVACOES AS OBSERVACOES, 
    PRODUTO.DATA_CADASTRO AS DATA_CADASTRO,
    CEST.CODIGO AS PERSONAL6
FROM PRODUTO
LEFT JOIN CEST ON CEST.ID = PRODUTO.ID_CEST
LEFT JOIN grupo_produtos ON grupo_produtos.id_grupo = PRODUTO.id_grupo
LEFT JOIN PRODUTO_ESTOQUE ON PRODUTO_ESTOQUE.id_produto = PRODUTO.ID
WHERE PRODUTO_ESTOQUE.id_empresa = '4'
