SELECT 
       FORNECEDOR AS CODIGO
      ,RAZAO_SOCIAL AS NOME
      ,FANTASIA AS FANTASIA
      ,ENDERECO AS ENDERECO
      ,ENDERECOCOMPL AS COMPLEMENTO
      ,ENDERECONUMERO AS NUMERO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,ESTADO AS UF
      ,CEP AS CEP
      ,FONE AS TELEFONE
      ,FAX AS FAX
      ,CNPJ AS CNPJ_CNPF
      ,INSCRICAO AS IE_RG
      ,CONTATO AS CONTATO
      ,E_MAIL AS EMAIL
      ,DATA_INC AS CADASTRO
  FROM Empresario.dbo.CADFOR
  WHERE DATA_INC <> '1753-01-01'