SELECT 
       CP.ID AS CODIGO
      ,CP.CODIGO_BARRA AS BARRAS
      ,CP.DESCRICAO AS DESCRICAO
      ,CP.UNIDADEPRODUTOID AS UND
      ,CF.RAZAO_SOCIAL AS FORNECEDOR
      ,EG.DESCRICAO AS GRUPO
      ,ES.ESTOQUEATUAL AS QTD
      ,CP.REFERENCIA AS COD_FABRICANTE
      ,ES.VRCUSTOV AS CUSTO_COMPRA
      ,ES.VRMEDIOV AS CUSTO_MEDIO
      ,ES.VRVENDAV AS PRECO_VENDA
      ,SUBSTRING (CP.CSTICMSID, 1 ,1) AS OST
      ,SUBSTRING (CP.CSTICMSID, 2 ,3) AS ST
      ,CP.OBSERVACAO AS OBSERVACOES
      ,CP.CODIGONCM AS COD_NCM
      ,CAST (CP.DATA AS DATE) AS DATA_CADASTRO
      ,CP.CESTFISCALID AS PERSONAL6
  FROM Empresario.dbo.CADPRO AS CP
LEFT JOIN Empresario.dbo.ESTGRU EG ON CP.GRUPO = EG.ID
LEFT JOIN Empresario.dbo.CADFOR CF ON CP.FORNECEDOR = CF.FORNECEDOR
LEFT JOIN Empresario.dbo.ESTSAL ES ON CP.ID = ES.MATRICULA
WHERE ES.FILIAL = '1'