SELECT VDCLIENTE.CODCLI AS CODIGO,
VDCLIENTE.RAZCLI AS NOME,
VDCLIENTE.NOMECLI AS FANTASIA,
VDCLIENTE.DATACLI AS CADASTRO,
COALESCE(VDCLIENTE.CNPJCLI,VDCLIENTE.CPFCLI) AS CNPJ_CNPF,
COALESCE(VDCLIENTE.INSCCLI,VDCLIENTE.RGCLI) AS IE_RG,
VDCLIENTE.ENDCLI AS ENDERECO,
VDCLIENTE.NUMCLI AS NUMERO,
VDCLIENTE.COMPLCLI AS COMPLEMENTO,
VDCLIENTE.BAIRCLI AS BAIRRO,
VDCLIENTE.CIDCLI AS CIDADE,
VDCLIENTE.UFCLI AS UF
FROM VDCLIENTE
