SELECT
PRODUTOS.CODPRODUTO AS COD_FABRICANTE,
PRODUTOS.F_CODBARRA AS BARRAS,
PRODUTOSGRUPOS.DESCRICAO AS GRUPO,
PRODUTOS.CODNCM AS COD_NCM,
PRODUTOS.CEST_CODIGO AS PERSONAL6,
PRODUTOS.CODUNDMEDIDA AS UND,
PRODUTOS.DESCRICAO,
PRODUTOS.CODCSOSNSAIDA AS ST,
PRODUTOS.F_OBSERVACOES AS OBSERVACOES,
PRODUTOS.VRPRECOCUSTO AS PRECO_CUSTO,
PRODUTOS.VRPRECOVENDA AS PRECO_VENDA
FROM PRODUTOS
LEFT JOIN PRODUTOSGRUPOS ON PRODUTOS.NSEQPRODUTOSGRUPOS=PRODUTOSGRUPOS.NSEQPRODUTOSGRUPOS


