SELECT
    PESSOA.ID AS CODIGO,
    PESSOA.CPFCNPJ AS CNPJ_CNPF,
    PESSOA.NOME,
    PESSOA.FANTASIA,
    PESSOA.IESTADUAL AS IE_RG,
    PESSOA.CEP,
    PESSOA.LOGRADOURO AS ENDERECO,
    PESSOA.NUMERO,
    PESSOA.COMPLEMENTO,
    PESSOA.BAIRRO,
    MUNICIpiO.NOME AS CIDADE,
    UF.UF
FROM PESSOA
LEFT JOIN MUNICIpiO ON PESSOA.MUNICIPIO = MUNICIpiO.ID
LEFT JOIN UF ON MUNICIPIO.UF = UF.codigo
