SELECT
    PRODUTO_SERVICO.ID AS CODIGO,
    PRODUTO_SERVICO.BARRA AS BARRAS,
    PRODUTO_SERVICO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO_SERVICO.NOME AS DESCRICAO,
    PRODUTO_SERVICO.UNIDADE AS UND,
    PRODSERV_EMPRESA.PRECO AS PRECO_VENDA,
    PRODSERV_EMPRESA.CUSTO AS PRECO_CUSTO,
    PRODSERV_EMPRESA.ESTOQUE AS QTD,
    PRODUTO_SERVICO.NCM AS COD_NCM
    --PRODUTO_SERVICO.CEST AS PERSONAL6
FROM PRODUTO_SERVICO
LEFT JOIN PRODSERV_EMPRESA ON PRODUTO_SERVICO.ID = PRODSERV_EMPRESA.PRODUTO_SERVICO
WHERE PRODSERV_EMPRESA.empresa = '1'
