SELECT
    FORNEC AS CODIGO,
    NOME AS NOME,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CEP AS CEP,
    CIDADE AS CIDADE,
    UF AS UF,
    FONE AS TELEFONE,
    FAX,
    CONTATO,
    CGC AS CNPJ_CNPF,
    INSC AS IE_RG,
    FANTASIA,
    EMAIL,
    NUMERO_ENDERECO AS NUMERO
FROM FORNEC
