SELECT
    ESTOQUE.ESTOQUE_CODIGO AS CODIGO,
    ESTOQUE.CLASSE AS GRUPO,
    ESTOQUE.ESPECIE AS FAMILIA,
    ESTOQUE.NOME AS DESCRICAO,
    FORNEC.NOME AS FORNECEDOR,
    ESTOQUE.UNIDADE AS UND,
    ESTOQUE.ESTOQUE AS QTD,
    ESTOQUE.CUSTO AS PRECO_CUSTO,
    ESTOQUE.VENDA AS PRECO_VENDA,
    ESTOQUE.NCM AS COD_NCM,
    ESTOQUE.BARRAS AS BARRAS,
    ESTOQUE.CODIGO_REFERENCIA AS COD_FABRICANTE,
    ESTOQUE.CST_SN AS ST,
    ESTOQUE.CEST AS PERSONAL6
FROM ESTOQUE
LEFT JOIN FORNEC ON ESTOQUE.CODFOR = FORNEC.FORNEC
