SELECT
	COD_PESSOA AS CODIGO,
	NOME AS NOME,
	CASE WHEN PESSOAS.CPF = '' OR PESSOAS.CPF IS NULL THEN PESSOAS.CNPJ ELSE PESSOAS.CPF END AS CNPJ_CNPF,
	CASE WHEN PESSOAS.RG = '' OR PESSOAS.RG IS NULL THEN PESSOAS.IE ELSE PESSOAS.RG END IE_RG,
	FANTASIA AS FANTASIA,
	C.DESCRICAO AS CIDADE,
	C.UF AS UF,
	B.DESCRICAO AS BAIRRO,
	L.DESCRICAO AS ENDERECO,
	FONE_PRINC AS TELEFONE,
	FAX_PRINC AS FAX,
	CEL_PRINC AS CELULAR,
	EMAIL_PRINC1 AS EMAIL,
	COMPLEMEN_PRINC AS COMPLEMENTO,
	NUMERO_PRINC AS NUMERO,
	CEP_PRINC AS CEP
FROM PESSOAS 
LEFT JOIN CIDADES C ON PESSOAS.COD_CID_PRINC=C.COD_CIDADES 
LEFT JOIN BAIRROS B ON PESSOAS.COD_BAIRRO_PRINC=B.COD_BAIRRO 
LEFT JOIN LOGRADOUROS L ON PESSOAS.COD_LOGRADOURO_PRINC=L.COD_LOGRADOURO 
WHERE PESSOAS.EFORNEC = 'S'