SELECT
	IT.COD_ITEM AS CODIGO,
	IT.DESCRICAO AS DESCRICAO,
	IT.COD_UNIDADE AS UND,
	IT.REF_FORNEC AS GRUPO,
	IT.REF_FABRICANTE AS COD_FABRICANTE,
	IT.REFERENCIA AS FAMILIA,
    IT.MEDIDA AS OBSERVACOES,
	TIPO_ITEM AS TIPO_ITEM,
	IT.NCM AS COD_NCM,
	IT.COD_BARRAS_NFE AS BARRAS,
	IT.CST_PIS_COFINS AS PIS_CODIGO,
	IT.CST_PIS_COFINS AS COFINS_CODIGO,
	IT.CEST AS PERSONAL6,
	IT.CODIGO_ANP AS COD_ANP,
	IE.QTD AS QTD,
	IE.CUSTO_MEDIO AS CUSTO_MEDIO,
	IE.CUSTO_COMPRA AS PRECO_CUSTO,
	IE.PRECO_VENDA AS PRECO_VENDA
FROM ITENS IT
LEFT JOIN ITENS_ESTOQUE IE ON IT.COD_ITEM=IE.COD_ITEM 