SELECT
    CODIGO AS CODIGO,
    RAZAO_SOCIAL AS NOME,
    NOME_FANTASIA AS FANTASIA,
    ENDERECO,
    NUMERO,
    COMPLEMENTO,
    BAIRRO,
    CIDADE,
    ESTADO AS UF,
    CEP,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    FONE AS TELEFONE,
    FAX AS FAX,
    EMAIL AS EMAIL,
    CONTATO
FROM FORNECEDORES
