SELECT
  CLIFOR.CODIGO AS CODIGO,
  CLIFOR.RAZAOSOCIAL AS NOME,
  CLIFOR.FANTASIA AS FANTASIA,
  CLIFOR.CNPJCPF AS CNPJ_CNPF,
  CLIFOR.IERG AS IE_RG,
  CLIFOR.ENDERECO AS ENDERECO,
  CLIFOR.NUMERO AS NUMERO,
  CLIFOR.BAIRRO AS BAIRRO,
  CLIFOR.COMPLEMENTO AS COMPLEMENTO,
 substring( cidade from 1 for position('(' in cidade) - 1) as CIDADE,
  CLIFOR.CEP AS CEP,
  CIDADE.UF AS UF,
  CLIFOR.TELEFONE AS TELEFONE,
  --CLIFOR.FONEFAX AS FAX,
  CLIFOR.CELULAR AS CELULAR,
  CLIFOR.EMAIL AS EMAIL,
  CLIFOR.INSCRICAOMUNICIPAL AS IM
FROM CLIFOR
LEFT JOIN CIDADE ON CIDADE.CHAVE = CLIFOR.CHAVECIDADE
WHERE CLIFOR.CLIENTE = 'N'
