SELECT
    PESSOAS.IDPESSOA AS CODIGO,
    PESSOAS.NOME AS NOME,
    PESSOAS.FANTASIA AS FANTASIA,
    PESSOAS.CNPJCPF AS CNPJ_CNPF,
    case when PESSOAS.RG = '' or PESSOAS.RG is null then PESSOAS.INSCR_EST else PESSOAS.RG END AS IE_RG,
    PESSOAS.INSCR_MUN AS IM,
    PESSOAS.FONE1 AS TELEFONE,
    PESSOAS.CELULAR AS CELULAR,
    PESSOAS.FAX AS FAX,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.PRI_ENDERECO AS ENDERECO,
    PESSOAS.PRI_COMPLEMENTO AS COMPLEMENTO,
    PESSOAS.PRI_BAIRRO AS BAIRRO,
    PESSOAS.PRI_CEP AS CEP,
    CIDADES.DESCRICAO AS CIDADE,
    CIDADES.UF AS uf
FROM PESSOAS
LEFT JOIN CIDADES ON CIDADES.idcidade = PESSOAS.PRI_CIDADE
WHERE IDTIPO_PS = '2'  --FORNECEDORES
--GROUP BY 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
