SELECT
    TITULOS.IDCLIFOR AS COD_FORNECEDOR,
    TITULOS.NOMECLIFOR AS NOM_FORNECEDOR,
    TITULOS.IDTITULO ||'/'|| IDPARCELA ||'/'|| TITULOS.IDSERIE AS DOCUMENTO,
    TITULOS.IDTITULO ||'/'|| IDPARCELA ||'/'|| TITULOS.IDSERIE AS HISTORICO,
    TITULOS.IDPARCELA AS PARCELA,
    TITULOS.IDTIPO,
    TITULOS.EMISSAO AS EMISSAO,
    TITULOS.VENCIMENTO AS VENCIMENTO,
    TITULOS.DTPAGAMENTO AS PAGAMENTO,
    TITULOS.VALOR AS VALOR_DUP,
    TITULOS.SALDO AS VALOR_PAG,
    TITULOS.VALDESCONTO AS VALOR_DES,
    MIN (PESSOAS.CNPJCPF) AS CNPJ,
    '0' AS NUNCONTA,
    '0' AS CTO_CUSTO
FROM TITULOS
LEFT JOIN PESSOAS ON PESSOAS.NOME = TITULOS.NOMECLIFOR
WHERE TITULOS.IDTIPO = 'P'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,14
