SELECT
    SUBSTRING (PRODUTOS.IDPRODUTO FROM 4 FOR 8)AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UN AS UND,
    PRODUTOS.BARRAS AS BARRAS,
    PRODUTOS.PESO_LIQ AS PESO,
    PRODUTOS.EST_MIN AS QTD_IDEAL,
    PRODUTOS.EST_ATUAL AS QTD,
    MIN (PESSOAS.NOME) AS FORNECEDOR,
    GRUPOS_PROD.descricao AS GRUPO,
    SUBGRUPOS_PROD.descricao AS FAMILIA,
    PRODUTOS.VLR_CUSTO AS PRECO_CUSTO,
    PRODUTOS.VLR_CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.VLR_VENDA AS PRECO_VENDA,
    SUBSTRING (SITTRIB.codigo FROM 1 FOR 1) AS OST,
    SUBSTRING (SITTRIB.codigo FROM 2 FOR 3) AS ST,
    CLASSFISCAL.classificacao AS COD_NCM,
    PRODUTOS.DTA_ULTCOMPRA AS ULTIMA_COMPRA,
    PRODUTOS.DTULTVENDA AS ULTIMA_VENDA,
    PRODUTOS.IDPRODUTO AS CARACTERISTICAS,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    MIN (CEST.CEST) AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPOS_PROD ON GRUPOS_PROD.idgrupo = PRODUTOS.GRUPO
LEFT JOIN subgrupos_prod ON SUBGRUPOS_PROD.idsubgrupo = PRODUTOS.SUBGRUPO
LEFT JOIN SITTRIB on SITTRIB.idsittrib = PRODUTOS.SITTRIB
LEFT JOIN CLASSFISCAL ON CLASSFISCAL.idclassfiscal = PRODUTOS.CLASSFISCAL
LEFT JOIN CEST ON CEST.ncm = CLASSFISCAL.classificacao
LEFT JOIN PESSOAS ON PESSOAS.IDPESSOA = PRODUTOS.FORNECEDOR
GROUP BY 1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22
