SELECT
    PRODUTO.ID AS CODIGO,
    PRODUTO.GTIN AS BARRAS,
    PRODUTO.UN_VENDA AS UND,
    PRODUTO.UN_VENDA AS UND_COMPRA,
    PRODUTO.NOME AS DESCRICAO,
    CLASSIFICACAO_GRUPO.DESCRICAO AS GRUPO,
    CLASSIFICACAO_SG.DESCRICAO AS FAMILIA,
    PRODUTO.QUANTIDADE_ESTOQUE AS QTD,
    PRODUTO.ESTOQUE_MINIMO AS QTD_IDEAL,
    PRODUTO.ORIGEM_PRODUTO AS OST,
    PRODUTO.CST AS ST,
    PRODUTO.CFOP AS CF,
    PRODUTO.VALOR_COMPRA AS PRECO_CUSTO,
    PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_VENDA AS PRECO_VENDA,
    PRODUTO.CST_PIS AS PIS_CODIGO,
    PRODUTO.CST_COFINS AS COFINS_CODIGO,
    PRODUTO.CODIGO_INTERNO AS COD_FABRICANTE,
    NCM.NCM AS COD_NCM,
    NCM.CEST AS PERSONAL6,
    PRODUTO.OBSERVACOES AS OBSERVACOES
FROM PRODUTO
LEFT JOIN NCM ON NCM.ID = PRODUTO.NCM
LEFT JOIN CLASSIFICACAO_GRUPO ON CLASSIFICACAO_GRUPO.ID =  PRODUTO.ID_GRUPO
LEFT JOIN CLASSIFICACAO_SG ON CLASSIFICACAO_SG.ID =  PRODUTO.ID_SUBGRUPO