SELECT PESSOAS.CODIGO,
PESSOAS.NOME,
PESSOAS.NOMEFANTASIA AS FANTASIA,
PESSOAS.ENDERECO,
PESSOAS.BAIRRO,
PESSOAS.CIDADE,
PESSOAS.ESTADO AS UF,
PESSOAS.CEP,
CONCAT(PESSOAS.DDD,PESSOAS.TELEFONE1) AS TELEFONE,
PESSOAS.FAX,
PESSOAS.EMAIL,
PESSOAS.CONTATO,
PESSOAS.CPFCGC AS CNPJ_CNPF,
PESSOAS.INSCRICAOIDENTIDADE AS IE_RG,
PESSOAS.COMPLEMENTO,
CAST(PESSOAS.DATACRIADO AS DATE)AS CADASTRO
FROM PESSOAS
WHERE PESSOAS.CODIGO > 0
AND BIN_AND(PESSOAS.CLIFOR::INTEGER, 2) = 2 OR BIN_AND(PESSOAS.CLIFOR::INTEGER, 32) = 32;