SELECT 
CLIENTE.CODIGO_CLIENTE AS CODIGO,
CLIENTE.NOME_CLIENTE AS NOME,
CLIENTE.CPF_CLIENTE AS CNPJ_CNPF,
CLIENTE.DOC_CLIENTE AS IE_RG,
CLIENTE.ENDERECO_CLIENTE AS ENDERECO,
CLIENTE.NUMEROEND_CLIENTE AS NUMERO,
CLIENTE.COMPLEMENTOEND_CLIENTE AS ENDERECO,
CLIENTE.BAIRRO_CLIENTE AS BAIRRO,
CLIENTE.CEP_CLIENTE AS CEP,
CLIENTE.EMAIL_CLIENTE AS EMAIL,
CLIENTE.TELEFONE1_CLIENTE AS TELEFONE,
CLIENTE.CELULAR_CLIENTE AS CELULAR,
--CAST(CLIENTE.DATACAD_CLIENTE AS DATE) AS CADASTRO,
CIDADE.NOM_CIDADE AS CIDADE,
CIDADE.COD_ESTADO,
ESTADO.SGL_ESTADO AS UF
FROM CLIENTE
LEFT JOIN CIDADE ON CLIENTE.COD_CIDADE = CIDADE.COD_CIDADE
LEFT JOIN ESTADO ON CIDADE.COD_ESTADO=ESTADO.COD_ESTADO

