SELECT 
  F.CODIGO
, F.FORNECEDOR AS NOME
, F.FANTASIA
, F.ENDERECO
, F.NUMERO
, F.BAIRRO
, F.COMPLEMENTO
, F.CEP
, F.FONE AS TELEFONE
, F.CELULAR
, F.FAX
, F.CPFCNPJ AS CNPJ_CNPF
, CASE WHEN F.RG = '' OR F.RG IS NULL THEN F.IE ELSE F.RG END AS IE_RG
, F.IM
, F.EMAIL
, F.CONTATO
, F.OBS AS OBSERVACOES
, CI.CIDADE 
, ES.UF 
FROM FORNECEDORES F
LEFT JOIN CIDADES CI ON CI.CODIGO = F.CIDADE 
LEFT JOIN ESTADOS ES ON ES.CODIGO = CI.ESTADO 
