SELECT
  ID AS CODIGO,
  NOME,
  APELIDO AS FANTASIA,
  CPF AS CNPJ_CNPF,
  RG AS IE_RG,
  ENDERECO,
  NUMERO,
  COMPLEMENTO,
  BAIRRO,
  CIDADE,
  UF,
  CEP,
  TELEFONE1 AS TELEFONE,
  CELULAR,
  TELEFONE2 AS FAX,
  EMAIL
  -- DATE_FORMAT(DATA_CADASTRO, '%d/%m/%Y') AS CADASTRO
FROM
  clientes;