SELECT PESSOAS.ID_PESSOA AS CODIGO,
PESSOAS.NOME_RAZAO AS NOME,
PESSOAS.FANTASIA,
PESSOAS.ENDERECO,
PESSOAS.NUMERO,
PESSOAS.COMPLEMENTO,
PESSOAS.BAIRRO,
CIDADES.NOME AS CIDADE,
CIDADES.UF,
PESSOAS.CEP,
PESSOAS.TELEFONE,
PESSOAS.CELULAR,
PESSOAS.EMAIL,
CAST(PESSOAS.DT_CADASTRO AS DATE) AS CADASTRO,
CASE WHEN PESSOAS.CPF='' OR PESSOAS.CPF IS NULL THEN PESSOAS.CNPJ
ELSE PESSOAS.CPF END AS CNPJ_CNPF,
PESSOAS.IE,
PESSOAS.OBS AS OBSERVACOES,
PESSOAS.CONTATO
FROM PESSOAS
LEFT JOIN CIDADES ON PESSOAS.ID_CIDADE=CIDADES.ID_CIDADE
WHERE PESSOAS.CLIENTE='S'

