SELECT PRODUTOS.ID_PRODUTO AS CODIGO,
PRODUTOS.DESCRICAO,
UNIDADES_MEDIDA.SIGLA AS UND,
PRODUTOS.CODIGO_BARRA AS BARRAS,
MARCAS.DESCRICAO AS CARACTERISTICAS,
CATEGORIAS.DESCRICAO AS GRUPO,
PRODUTOS.PRECO_CUSTO,
PRODUTOS.PRECO_VENDA,
PRODUTOS.SALDO AS QTD,
CAST (PRODUTOS.DT_CADASTRO AS DATE) AS DATA_CADASTRO,
CAST (PRODUTOS.DT_ULTCOMPRA AS DATE) AS ULTIMA_COMPRA,
CAST (PRODUTOS.DT_ULTVENDA AS DATE) AS ULTIMA_VENDA,
PRODUTOS.OBS AS OBSERVACOES,
PRODUTOS.REFERENCIA AS COD_FABRICANTE,
SUBSTRING(PRODUTOS.REGIME_TRIBUTACAO FROM 6 FOR 9) AS ST,
PRODUTOS.ORIGEM AS OST,
PRODUTOS.NCM AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6,
PRODUTOS.PRECO_VENDA_ATACADO AS PRECO_ATACADO
FROM PRODUTOS
LEFT JOIN UNIDADES_MEDIDA ON PRODUTOS.ID_UNIDADE=UNIDADES_MEDIDA.ID_UNIDADE
LEFT JOIN MARCAS ON PRODUTOS.ID_MARCA=MARCAS.ID_MARCA
LEFT JOIN CATEGORIAS ON PRODUTOS.ID_CATEGORIA=CATEGORIAS.ID_CATEGORIA

