SELECT
    CODIGO,
    NOME,
    ENDERECO,
    BAIRRO,
    CIDADE,
    UF,
    CEP,
    TELEFONE,
    COALESCE(CNPJ,'') || COALESCE(CPF,'') AS CNPJ_CNPF,
    INSC_ESTADUAL AS IE_RG,
    NUMERO,
    COMPLEMENTO,
    EMAIL
FROM CLIENTES