SELECT
    CODIGO AS COD_FABRICANTE,
    DESCRICAO AS DESCRICAO,
    UNIDADE AS UND,
    PRECO_UN AS PRECO_VENDA,
    CODIGO_NCM AS COD_NCM,
    CODIGO_BARRAS AS BARRAS,
    PRECO_AVISTA AS PRECO_ATACADO,
    PRECO_CUSTO AS PRECO_CUSTO,
    MATL_CSON_COD AS ST,
    MATL_PIS_CST AS PIS_CODIGO,
    MATL_PIS_CST_ENTR AS PISE_CODIGO,
    MATL_COFINS_CST AS COFINS_CODIGO,
    MATL_COFINS_CST_ENTR AS COFINSE_CODIGO,
    MATL_ESTOQUE AS QTD,
    CEST AS PERSONAL6
FROM MATERIAIS