SELECT
    CLIENTE.CNPJCPF AS CNPJ_CNPF,
    CLIENTE.IERG AS IE_RG,
    CLIENTE.RAZAO AS NOME,
    CLIENTE.FANTASIA AS FANTASIA,
    CLIENTE.ENDERECO,
    CLIENTE.NUMERO,
    CLIENTE.COMPLEMENTO,
    CLIENTE.BAIRRO,
    CLIENTE.CIDADE,
    CLIENTE.CEP,
    CLIENTE.UF,
    CLIENTE.FONE1 AS TELEFONE,
    CLIENTE.CONTATO,
    CLIENTE.EMAIL
FROM CLIENTE
