SELECT
    COD_FOR AS CODIGO,
    RAZAO_FOR AS NOME,
    CONTATO_FOR AS CONTATO,
    CNPJ_FOR AS CNPJ_CNPF,
    INSC_FOR AS IE_RG,
    END_FOR AS ENDERECO,
    NUM_FOR AS NUMERO,
    BAI_FOR AS BAIRRO,
    CID_FOR AS CIDADE,
    CEP_FOR AS CEP,
    EST_FOR AS UF,
    TEL_FOR AS TELEFONE,
    FAX_FOR AS FAX,
    EMAIL_FOR AS EMAIL,
    OBS_FOR AS OBSERVACOES
FROM FORNECEDOR
WHERE RAZAO_FOR <> ''
