select
  clientes.CLICOD as codigo,
  clientes.CLINOM as nome,
  clientes.CLIEND as endereco,
  clientes.NUMERO_ENDERECO as numero,
  clientes.CLIBAI as bairro,
  clientes.COMPLEMENTO_ENDERECO as complemento,
  clientes.CLICEP as cep,
  clientes.CLICID as cidade,
  clientes.CLIEST as uf,
  clientes.CLIFON as telefone,
  clientes.CLIFAX as fax,
  clientes.CELULAR as celular,
  clientes.CLILIM as im,
  clientes.CLICPF as cnpj_cnpf,
  clientes.CLIREG as ie_rg,
  clientes.CLINAS as nascimento,
  clientes.CLIOBS as observacoes,
  clientes.CONJUGUE as conjuge,
  clientes.PAI as pai,
  clientes.MAE as mae,
  clientes.DT_CADAS as cadastro, 
  clientes.E_MAIL as email
from clientes