SELECT
    PRODUTO.CDPRODUTO AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.CODIGOFABRICANTE AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.PESOLIQUIDO AS PESO,
    PRODUTO.ESTOQUEMINIMO AS QTD_IDEAL,
    PRODUTO.ESTOQUEATUAL AS QTD,
    FORNECEDOR.RAZAOSOCIAL AS FORNRCRDOR,
    PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEMLUCRO AS MARGEM_LUCRO,
    PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO.PRECOVENDA AS PRECO_VENDA,
    PRODUTO.CODIGOFABRICANTE AS COD_FABRICANTE,
    PRODUTO.CLASSIFICACAOORIGEM AS OST,
    PRODUTO.SITUACAOTRIBUTARIA AS ST,
    PRODUTO.CODIGONCM AS COD_NCM,
    PRODUTO.ULTIMACOMPRA AS ULTIMA_COMPRA,
    PRODUTO.ULTIMAVENDA AS ULTIMA_VENDA,
    PRODUTO.DATACADASTRO AS DATA_CADASTRO,
    PRODUTO.OBSERVACAO AS OBSERVACOES,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN FORNECEDOR ON FORNECEDOR.CDFORNECEDOR = PRODUTO.CDFORNECEDOR