SELECT
PRODU.COD_PROD AS CODIGO,
PRODU.DAT_CAD AS DATA_CADASTRO,
PRODU.DESCRICAO,
PRODU.unid_estoque AS QTD,
PRODU.COD_INTERNO AS COD_FABRICANTE,
PRODU.COD_BARRA AS BARRAS,
PRODU.UNID_VEND AS UND,
PRODU.CEST AS PERSONAL6,
PRODU.PRC_COMPRA AS PRECO_CUSTO,
PRODU.PRC_MEDIO AS CUSTO_MEDIO,
PRODU.MARGEM_VAREJO AS MARGEM_LUCRO,
PRODU.PRC_VENDA AS PRECO_VENDA,
PRODU.PRC_VENDA_ATACADO AS PRECO_ATACADO,
PRODU.NCM AS COD_NCM,
TRIBUTACAO_ICMS.CST_ICMS_SN AS ST
FROM PRODU
LEFT JOIN TRIBUTACAO_ICMS ON PRODU.COD_TRIBUT_ICMS_SAIDA=TRIBUTACAO_ICMS.COD_TRIBUT
--LEFT JOIN TB_PRC_IT ON PRODU.COD_PROD=TB_PRC_IT.COD_PROD
