SELECT PRODUTO.ID AS CODIGO,
PRODUTO.NOME AS DESCRICAO,
PRODUTO.CODIGO AS COD_FABRICANTE,
PRODUTO.UNIDADE AS UND,
PRODUTO.CSOSN AS ST,
PRODUTO.PRECO_VENDA,
PRODUTO.CODIGONCM AS COD_NCM,
PRODUTO.CEST AS PERSONAL6,
GRUPO.GRUPO
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.ID_GRUPO=GRUPO.ID

