SELECT
    CLIFOR.COD_CLIFOR AS CODIGO,
    CLIFOR.NOME AS NOME,
    CLIFOR.FANTASIA AS FANTASIA,
    CLIFOR.NOM_CONTAT AS CONTATO,
    CLIFOR.CGC AS CNPJ_CNPF,
    CLIFOR.INSC_EST AS IE_RG,
    CLIFOR.INSCMUNICIPAL AS IM,
    CLIFOR.E_MAIL AS EMAIL,
    CLIFOR.ENDERECO AS ENDERECO,
    CLIFOR.COMPLEMENTO AS COMPLEMENTO,
    CLIFOR.BAIRRO AS BAIRRO,
    CLIFOR.NUMERO AS NUMERO,
    CLIFOR.CIDADE AS CIDADE,
    CLIFOR.COD_CEPEND AS CEP,
    CLIFOR.ESTADO AS UF,
    CLIFOR.DDDFAX ||''|| CLIFOR.FAX AS FAX,
    CLIFOR.DDDFONE1 ||''|| CLIFOR.TELEFONE1 AS TELEFONE,
    CLIFOR.DDDFONE2 ||''|| CLIFOR.TELEFONE2 AS CELULAR,
    CLIFOR.OBSERVACAO AS OBSERVACOES
FROM CLIFOR
WHERE TIPO = '3' --FORNECEDORES