SELECT
    ESTPROMA.COD_REDUZ AS CODIGO,
    ESTPROMA.NOME1 AS DESCRICAO,
    ESTPROMA.GTIN_CEAN AS BARRAS,
    ESTPROMA.UNID_PAD AS UND,
    ESTPROMA.PESO AS PESO,
    ESTPROMA.QTD_FIS AS QTD,
    ESTPROMA.QTD_MIN AS QTD_IDEAL,
    ESTPROMA.CUSTOMEDIO AS CUSTO_MEDIO,
    ESTPROMA.PRECO_VEND AS PRECO_VENDA,
    ESTPROMA.SUBST_TRIB AS ST,
    ESTPROMA.REFERENCIA AS COD_FABRICANTE,
    ESTPROMA.OBSERV1 AS OBSERVACOES,
    ESTPROMA.DATACADASTRO AS DATA_CADASTRO,
    ESTPROMA.CLAS_FISC AS COD_NCM,
    ESTPROMA.CEST AS PERSONAL6
from ESTPROMA