SELECT
    RAZAO_SOCIAL AS NOME,
    NOM_FANTASIA AS FANTASIA,
    CPFCNPJ AS CNPJ_CNPF,
    INS_ESTADUAL_RG AS IE_RG,
    UF,
    ENDERECO,
    TEL_FORNEC AS TELEFONE,
    TEL_CELULAR AS CELULAR,
    TEL_FAX AS FAX,
    E_MAIL AS EMAIL,
    DSC_MUNICIPIO AS CIDADE,
    DSC_BAIRRO AS BAIRRO,
    CEP,
    NRO_LOGRADOURO AS NUMERO
FROM FORNECEDOR
