SELECT
    FORNECEDORES.RAZAOSOCIAL AS NOME,
    FORNECEDORES.NOMEFANTASIA AS FANTASIA,
    FORNECEDORES.CGC AS CNPJ_CNPF,
    FORNECEDORES.IE AS IE_RG,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.UF AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.DDD  || '' || FORNECEDORES.FONE AS TELEFONE,
    FORNECEDORES.DDD  || '' || FORNECEDORES.FAX AS FAX,
    FORNECEDORES.DDD  || '' || FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.OBS AS OBSERVACOES
FROM FORNECEDORES
