SELECT
	C.CLI_CODIGO AS CODIGO,
--	C.CLI_RAZAO_SOCIAL AS NOME,	
	C.CLI_NOME AS NOME,
	C.CLI_DATA_NASCIMENTO AS NASCIMENTO,
	CASE WHEN C.CLI_CPF = '' OR C.CLI_CPF IS NULL THEN C.CLI_CNPJ ELSE C.CLI_CPF END AS CNPJ_CNPF,
	CASE WHEN C.CLI_RG = '' OR C.CLI_RG IS NULL THEN C.CLI_IE ELSE C.CLI_RG END AS IE_RG,	
	C.CLI_LOGRADOURO AS ENDERECO,
	C.CLI_NUMERO AS NUMERO,
	C.CLI_COMPLEMENTO AS COMPLEMENTO,
	C.CLI_BAIRRO AS BAIRRO,
	C.CLI_CEP AS CEP,	
	C.CLI_TELEFONE AS TELEFONE,
	C.CLI_CELULAR AS CELULAR,
	C.CLI_LIMITECREDITO AS LIMITE_CREDITO,
	C.CLI_EMAIL1 AS EMAIL,
	C.OBSERVACAO AS OBSERVACOES,
	CI.CID_NOME AS CIDADE,
	E.EST_SIGLA AS UF
FROM
	CLIENTE C
INNER JOIN CIDADE CI ON CI.CID_CODIGO = C.CID_CODIGO 
LEFT JOIN ESTADO E ON E.EST_CODIGO = CI.CID_ESTADO 