SELECT
	F.FOR_CODIGO AS CODIGO,
--	F.FOR_RAZAOSOCIAL AS NOME,
	F.FOR_NOME AS NOME,	
	CASE WHEN F.FOR_CPF = '' OR F.FOR_CPF IS NULL THEN F.FOR_CNPJ ELSE F.FOR_CPF END AS CNPJ_CNPF,
	CASE WHEN F.FOR_RG = '' OR F.FOR_RG IS NULL THEN F.FOR_IE ELSE F.FOR_RG END AS IE_RG,
	F.FOR_EMAIL AS EMAIL,
	F.FOR_CEP AS CEP,
	F.FOR_LOGRADOURO AS ENDERECO,
	F.FOR_NUMERO AS NUMERO,
	F.FOR_COMPLEMENTO AS COMPLEMENTO,
	F.FOR_BAIRRO AS BAIRRO,
	F.FOR_TELEFONE AS TELEFONE,
	F.FOR_FAX AS FAX,
	CI.CID_NOME AS CIDADE,
	E.EST_SIGLA AS UF
FROM
	FORNECEDORES F
INNER JOIN CIDADE CI ON CI.CID_CODIGO = F.FOR_CIDADE 
LEFT JOIN ESTADO E ON E.EST_CODIGO = CI.CID_ESTADO