SELECT 
  C.CLI_CODIGO AS CODIGO
, C.CLI_NOME AS NOME
, C.CLI_NOMEFANTASIA AS FANTASIA
, C.CLI_CPFCNPJ AS CNPJ_CNPF
, C.CLI_RGINSC AS IE_RG
, C.CLI_INSCMUNICIPAL AS IM
, C.CLI_ENDERECO AS ENDERECO
, C.CLI_COMPLEMENTO AS COMPLEMENTO
, C.CLI_CEP AS CEP
, C.CLI_NUMENDERECO AS NUMERO
, C.CLI_BAIRRO AS BAIRRO
, C.CLI_FONERES AS TELEFONE
, C.CLI_FONECOM AS FAX
, C.CLI_FONEMOV AS CELULAR
, CASE C.CLI_SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, C.CLI_CONTATO AS CONTATO
, C.CLI_DATANASCTO AS NASCIMENTO
, C.CLI_LIMITECREDITO AS LIMITE_CREDITO
, C.CLI_DATACADASTRO AS CADASTRO
, C.CLI_OBS AS OBSERVACOES
, C.CLI_EMAILPRINCIPAL AS EMAIL
, CI.CID_DESCRICAO AS CIDADE
, CI.UF_SIGLA AS UF
FROM CLIENTE C
LEFT JOIN CIDADE CI ON CI.CID_CODIGO = C.CID_CODIGO  
WHERE CLI_CLIENTE = 'S'