SELECT 
  P.PROD_CODIGO AS CODIGO
, P.PROD_CODBARRA AS BARRAS
, P.PROD_NOME AS DESCRICAO
, P.PROD_COMPLEMENTO AS OBSERVACOES
--, P.PROD_VALORCUSTO
, P.PROD_CUSTOCOMPRA AS PRECO_CUSTO
--, P.PROD_VALORUNIT
, P.PROD_VALORVISTA AS PRECO_VENDA
, P.PROD_PERCENTLUCRO AS MARGEM_LUCRO
, P.PROD_QTDEMINIMA AS QTD_IDEAL
, P.PROD_QTDEATACADO AS QTD_PRECO_ATACADO
, CASE P.PROD_SITUACAO WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.PROD_DATACADASTRO AS DATA_CADASTRO
, P.PROD_NCM AS COD_NCM
, P.PROD_CSTIPI AS IPI_CODIGO_VENDA
, P.PROD_CSTPIS AS PIS_CODIGO
, P.PROD_CSTCOFINS AS COFINS_CODIGO
, P.PROD_ORIGEM AS OST
, P.PROD_ALIQUOTAPIS AS PIS_ALIQ_NOR
, P.PROD_ALIQUOTACOFINS AS COFINS_ALIQ_NOR
, P.PROD_ALIQUOTAIPI AS ALIQ_IPI_VENDA
, P.PROD_CODFABRICA AS COD_FABRICANTE
, P.PROD_CEST AS PERSONAL6
, P.PROD_PESO AS PESO
--, P.PROD_CSTICMS AS ST
--, P.PROD_ALIQUOTAICMS
, (P.PROD_ENTRADAS - PROD_SAIDAS) AS QTD
--, (E.ESTDEP_ENTRADAS - E.ESTDEP_SAIDAS) AS QTD
, A.ALIQ_CSTICMS AS ST
, M.MARCA_DESCRICAO AS CARACTERISTICAS
, G.GRP_NOME AS GRUPO
, S.SET_NOME AS FAMILIA
, U.UNIP_ABREV AS UND
, U.UNIP_FATOR AS FAT_CONV
, REPLACE (N.NAT_CODFISCAL,'.','') AS CF
FROM PRODUTO P
LEFT JOIN ALIQUOTA A ON A.ALIQ_CODIGO = P.ALIQ_CODIGO
LEFT JOIN MARCA M ON M.MARCA_CODIGO = P.MARCA_CODIGO
LEFT JOIN GRUPOPRODUTO G ON G.GRP_CODIGO = P.GRP_CODIGO
LEFT JOIN SETOR S ON S.SET_CODIGO = P.SET_CODIGO
LEFT JOIN UNIDADEPRODUTO U ON U.UNIP_CODIGO = P.UNIP_CODIGO
LEFT JOIN NATOPERACAO N ON N.NAT_CODIGO = P.CFOP_CODIGODENTROESTADO
--LEFT JOIN ESTOQUEDEPOSITO E ON E.PROD_CODIGO = P.PROD_CODIGO 