SELECT FORNECE.CODFORNEC AS CODIGO,
FORNECE.NOME,
FORNECE.NOMEFANTASIA AS FANTASIA,
FORNECE.BAIRRO,
FORNECE.CEP,
FORNECE.CGCCPF AS CNPJ_CNPF,
CIDADES.CIDADE,
FORNECE.CONTATO,
FORNECE.ENDERECO,
FORNECE.ESTADO AS UF,
FORNECE.FONE AS TELEFONE,
FORNECE.FAX,
FORNECE.INSCEST AS IE_RG,
FORNECE.OBSERVACAO AS OBSERVACOES,
FORNECE.EMAIL,
FORNECE.CELULAR,
FORNECE.COMPLEMENTO,
FORNECE.NUMERO
FROM FORNECE
LEFT JOIN CIDADES ON FORNECE.CODCIDADE=CIDADES.CODCIDADE
WHERE FORNECE.CODFORNEC>'000000'
