SELECT 
P.CODIGO
, P.DESCRICAO
, P.OBSERVACAO AS OBSERVACOES
, P.VALOR_CUSTO AS PRECO_CUSTO
, P.MARGEM_LUCRO AS MARGEM_LUCRO
--, P.MARKUP AS MARGEM_LUCRO
, P.VALOR_VENDA AS PRECO_VENDA
, CASE P.STATUS WHEN TRUE THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.CODIGO_BARRAS AS BARRAS
, P.CODIGO_FORNECEDOR AS COD_FABRICANTE
, P.ESTOQUE AS QTD
, CAST(P.DATA_ULTIMA_VENDA AS DATE) AS ULTIMA_VENDA
, P.DATA_ULTIMA_COMPRA AS ULTIMA_COMPRA
, P.ORIGEM_ID AS OST
, P.CEST AS PERSONAL6
, P.VALIDADE_DIAS
, P.LOCALIZACAO AS PERSONAL1
, P.ESTOQUE_MINIMO AS QTD_IDEAL
, U.ABREVIATURA AS UND
, N.CODIGO AS COD_NCM
--, TI.CST_ICMS AS ST
, TI.CSOSN_ICMS AS ST
, TI.CST_IPI AS IPI_CODIGO_VENDA
, TI.CST_PIS AS PIS_CODIGO
, TI.CST_COFINS AS COFINS_CODIGO
--, TI.ALIQUOTA_ICMS AS ELO
, TI.ALIQUOTA_IPI AS ALIQ_IPI_VENDA
, TI.ALIQUOTA_PIS AS PIS_ALIQ_NOR
, TI.ALIQUOTA_COFINS AS COFINS_ALIQ_NOR
--, LEFT (TPC.DESCRICAO,2) AS COFINS_CODIGO
--, TPC.CST_PIS_ENTRADA
--, TPC.ALIQUOTA_PIS_ENTRADA
--, TPC.CST_PIS_SAIDA
--, TPC.ALIQUOTA_PIS_SAIDA
--, TPC.CST_COFINS_ENTRADA
--, TPC.ALIQUOTA_COFINS_ENTRADA
--, TPC.CST_COFINS_SAIDA
--, TPC.ALIQUOTA_COFINS_SAIDA
--, TOI.CST_IPI_ENTRADA
--, TOI.ALIQUOTA_IPI_ENTRADA
--, TOI.CST_IPI_SAIDA
--, TOI.ALIQUOTA_IPI_SAIDA
, LEFT (C.CODIGO,3) AS ELO
, E.RAZAO_SOCIAL AS FORNECEDOR
, M.DESCRICAO AS CARACTERISTICAS
, M2.DESCRICAO AS PERSONAL2
, G.DESCRICAO AS GRUPO
FROM PRODUTO P
LEFT JOIN UNIDADE U ON U.UNIDADE_ID = P.UNIDADE_VENDA_ID
LEFT JOIN NCM N ON N.NCM_ID = P.NCM_ID
LEFT JOIN TIPO_OPERACAO TI ON TI.TIPO_OPERACAO_ID = P.TIPO_OPERACAO_ID
LEFT JOIN CFOP C ON C.CFOP_ID = TI.CFOP_ID 
LEFT JOIN ENTIDADE E ON E.ENTIDADE_ID = P.FORNECEDOR_ID
LEFT JOIN MARCA M ON M.MARCA_ID = P.MARCA_ID
LEFT JOIN MODELO M2 ON M2.MODELO_ID = P.MODELO_ID
LEFT JOIN GRUPO G ON G.GRUPO_ID = P.GRUPO_ID
LEFT JOIN GRUPO_SUBGRUPO SG ON SG.GRUPO_SUBGRUPO_ID = P.GRUPO_SUBGRUPO_ID AND G.GRUPO_ID = SG.GRUPO_ID
--LEFT JOIN TIPO_OPERACAO_PIS_COFINS TPC ON TPC.TIPO_OPERACAO_PIS_COFINS_ID = P.TIPO_OPERACAO_PIS_COFINS_ID
--LEFT JOIN TIPO_OPERACAO_IPI TOI ON TOI.TIPO_OPERACAO_IPI_ID = P.TIPO_OPERACAO_IPI_ID
