SELECT
    PRODUTOS.ID AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.EAN13 AS BARRAS,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    UNIDADES.DESCRICAO AS UND,
    UNIDADES.DESCRICAO AS UND_COMPRA,
    PRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.PRECO_COMPRA AS PRECO_CUSTO,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.ORIGEM AS OST,
    PRODUTOS.CSOSN AS ST,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    PRODUTOS.COD_CEST AS PERSONAL6,
    CAST (PRODUTOS.DATA_ULTIMA_ALTERACAO AS DATE) AS ALTERACAO_PRECO,
    CAST (PRODUTOS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO
FROM PRODUTOS
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.ID = PRODUTOS.SUBGRUPO
LEFT JOIN UNIDADES ON UNIDADES.ID = PRODUTOS.UNIDADE
