SELECT
    FORNECEDORES.CD_FRN AS CODIGO,
    FORNECEDORES.NR_CPF AS CNPJ_CNPF,
    FORNECEDORES.NR_INS_EST AS IE_RG,
    FORNECEDORES.NM_RAZ AS NOME,
    FORNECEDORES.NM_FNT AS FANTASIA,
    FORNECEDORES.NM_CNT AS CONTATO,
    FORNECEDORES.NM_RUA AS ENDERECO,
    FORNECEDORES.NR_NRO AS NUMERO,
    FORNECEDORES.NM_CPL AS COMPLEMENTO,
    FORNECEDORES.NM_BAI AS BAIRRO,
    FORNECEDORES.NM_EST AS UF,
    CIDADES.NM_CID AS CIDADE,
    FORNECEDORES.NR_CEP AS CEP,
    FORNECEDORES.NR_TEL AS TELEFONE,
    FORNECEDORES.NR_FAX AS FAX,
    FORNECEDORES.NM_EML AS EMAIL,
    FORNECEDORES.BB_OBS AS OBSERVACOES
FROM FORNECEDORES
LEFT JOIN cidades ON CIDADES.cd_cid = FORNECEDORES.CD_CID
