SELECT
    PRODUTOS.PRODUTOS_ID AS CODIGO,
    PRODUTOS.PRODUTO_NOME AS DESCRICAO,
    SUBGRUPOS.SUBGRUPO_NOME AS GRUPO,
    UNIDADES.UNIDADE_NOME AS UND,
    PRODUTOS.PRODUTO_PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTOS.PRODUTO_MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRODUTO_PRECO AS PRECO_VENDA,
    PRODUTOS.PRODUTO_ESTOQUE AS QTD,
    PRODUTOS.PRODUTO_CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.NCM_NCM AS COD_NCM,
    PRODUTOS.PRODUTO_CODIGO_BARRAS AS BARRAS,
    PRODUTOS.CSOSN_ID AS ST,
    PRODUTOS.PRODUTO_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN SUBGRUPOS ON PRODUTOS.SUBGRUPOS_ID = SUBGRUPOS.SUBGRUPOS_ID
LEFT JOIN UNIDADES ON PRODUTOS.UNIDADES_ID = UNIDADES.UNIDADES_ID
