SELECT
PRODUTOS.COD_PRODUTO AS COD_FABRICANTE,
GRUPOS.GRUPO,
PRODUTOS_BARRAS.EAN AS BARRAS,
PRODUTOS.TIPO_UNIDADE AS UND,
PRODUTOS.CST AS ST,
PRODUTOS.PRODUTO AS DESCRICAO,
PRODUTOS.VL_CUSTO AS PRECO_CUSTO,
PRODUTOS.PRECO AS PRECO_VENDA,
PRODUTOS.ESTOQUE AS QTD,
PRODUTOS.NCM AS COD_NCM
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.COD_GRUPO=GRUPOS.COD_GRUPO
LEFT JOIN PRODUTOS_BARRAS ON PRODUTOS.COD_PRODUTO=PRODUTOS_BARRAS.COD_PRODUTO
WHERE PRODUTOS.PRODUTO IS NOT NULL AND  PRODUTOS.COD_PRODUTO <> '-1'
