SELECT PRODUTO.CODIGO AS COD_FABRICANTE,
PRODUTO.CODIGOINT AS CODIGO,
PRODUTO.NOME AS DESCRICAO,
PRODUTOGRP.NOME AS GRUPO,
PRODUTO.UNIDADE AS UND,
PRODUTO.PRECOVENDA AS PRECO_VENDA,
PRODUTO.POSICAO AS COD_NCM,
PRODUTO.CADASTRO AS DATA_CADASTRO,
PRODUTO.CODIGOBARRA AS BARRAS,
PRODUTO.CEST AS PERSONAL6,
SUBSTRING(PRODUTO.CST FROM 2 FOR 4) AS ST,
PRODUTOEST.ESTOQUE AS QTD
FROM PRODUTO
LEFT JOIN PRODUTOGRP ON PRODUTO.GRUPO=PRODUTOGRP.CODIGO
LEFT JOIN PRODUTOEST ON PRODUTO.CODIGO=PRODUTOEST.PRODUTO


