SELECT FORNECEDOR.FORNECEDOR_ID AS CODIGO,
FORNECEDOR.NOME_FANTASIA AS FANTASIA,
FORNECEDOR.RAZAO_SOCIAL AS NOME,
FORNECEDOR.CNPJ_CPF AS CNPJ_CNPF,
FORNECEDOR.IE AS IE_RG,
FORNECEDOR.ENDERECO,
FORNECEDOR.NUMERO,
FORNECEDOR.COMPLEMENTO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CEP,
MUNICIPIO.NOME AS CIDADE,
MUNICIPIO.UF,
FORNECEDOR.TELEFONE,
FORNECEDOR.FAX,
FORNECEDOR.EMAIL,
FORNECEDOR.OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR
LEFT JOIN MUNICIPIO ON FORNECEDOR.CODIGO_MUNICIPIO=MUNICIPIO.MUNICIPIO_ID


