SELECT
PRODUTO.PRODUTO_ID AS CODIGO,
PRODUTO.cod_distribuidor AS COD_FABRICANTE,
PRODUTO.DESCRICAO,
PRODUTO.COD_BARRA AS BARRAS,
PRODUTO.QUANT_ESTOQUE AS QTD,
PRODUTO.UNIDADE AS UND,
FORNECEDOR.RAZAO_SOCIAL AS FORNECEDOR,
GRUPO.DESCRICAO AS GRUPO,
PRODUTO.CUSTO AS PRECO_CUSTO,
PRODUTO.VALOR_VAREJO AS PRECO_VENDA,
PRODUTO.NCM AS COD_NCM,
LEFT (PRODUTO.CFOP_DENTRO,3) AS ELO,
--PRODUTO.CST_ICMS AS ST,
CASE PRODUTO.tributacao
 WHEN 'I' THEN '400'
 WHEN 'T' THEN '102'
 WHEN 'S' THEN '500'
 WHEN 'N' THEN '400'
end AS st,
PRODUTO.VALOR_ATACADO AS PRECO_ATACADO,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN FORNECEDOR ON PRODUTO.ID_FORNECEDOR=FORNECEDOR.FORNECEDOR_ID
LEFT JOIN GRUPO ON PRODUTO.ID_GRUPO=GRUPO.GRUPO_ID
