SELECT 
  CODIGO
, REPLACE (REPLACE(REPLACE(CGC,',',''),'-',''),'/','') AS CNPJ_CNPF
, CASE WHEN IDENTIDADE = '' OR IDENTIDADE IS NULL THEN INSC ELSE IDENTIDADE END AS IE_RG
, NOME
, FANTASIA_APELIDO AS FANTASIA
, ENDERECO
, NUMERO
, COMPLEND AS COMPLEMENTO
, BAIRRO
, CIDADE
, ESTADO AS UF
, CEP
, TELEFONE
, CELULAR
, CONTATO
, FAX
, CONVERT (DATE,[DATA]) AS CADASTRO
, OBS AS OBSERVACOES
, EMAIL
, LIMITECRED AS LIMITE_CREDITO
, CONVERT (DATE,NASCIMENTO) AS NASCIMENTO
, FILIACAO AS PAI
, PROFISSAO
, CONVERT (DATE,ULTVENDA) AS ULTIMA_VENDA
FROM TABCLI