SELECT 
  CODIGO
, EMPRESA AS NOME
, FANTASIA_APELIDO AS FANTASIA
, CONTATO
, ENDERECO
, NUMERO
, BAIRRO
, CIDADE
, ESTADO AS UF
, CEP
, TELEFONE
, FAX
, REPLACE (REPLACE(REPLACE(CGC,',',''),'-',''),'/','') AS CNPJ_CNPF
, INSC AS IE_RG
, OBS AS OBSERVACOES
, EMAIL
, CELULAR
, CELULAR2 AS PERSONAL1
, CONTATO2 AS PERSONAL2
FROM TABFOR