SELECT
  PRODUTO.codprodu AS CODIGO,
  PRODUTO.refprodu AS COD_FABRICANTE,
  PRODUTO.codbarra AS BARRAS,
  PRODUTO.nomprodu AS DESCRICAO,
  MARCA.NOMMARCA AS FAMILIA,
  GRUPOPROB.NOMGRUPB AS GRUPO,
  PRODUTO.unidprod AS UND,
  PRODUTO.custouni AS PRECO_CUSTO,
  PRODUTO.qtprodut AS QTD,
  PRODUTO.vendauni AS PRECO_VENDA,
  PRODUTO.codigncm AS COD_NCM,
  PRODUTO.codicest AS PERSONAL6,
  PRODUTO.numcsosn AS ST
FROM PRODUTO
LEFT JOIN MARCA ON PRODUTO.FKMARPRO = MARCA.CODMARCA
LEFT JOIN GRUPOPROB ON PRODUTO.FKGRUPOB = GRUPOPROB.CODGRUPB
WHERE PRODUTO.CODPRODU >0