SELECT 
  C.CLIENTE_ID AS CODIGO
, C.CLIENTE_NOME AS NOME
, C.CLIENTE_FANTASIA AS FANTASIA
, C.CLIENTE_DOCUMENTO AS CNPJ_CNPF
, C.CLIENTE_RG_IE AS IE_RG
, C.CLIENTE_LOGRADOURO AS ENDERECO
, C.CLIENTE_BAIRRO AS BAIRRO
, C.CLIENTE_NUMERO AS NUMERO
, C.CLIENTE_COMPLEMENTO AS COMPLEMENTO
, C.CLIENTE_CEP AS CEP
, C.CLIENTE_TELEFONE AS TELEFONE
, C.CLIENTE_CELULAR AS CELULAR 
, C.CLIENTE_NASCIMENTO AS NASCIMENTO
, C.CLIENTE_CADASTRO AS CADASTRO
, C.CLIENTE_EMAIL AS EMAIL
, C.CLIENTE_PAI AS PAI
, C.CLIENTE_MAE AS MAE
, C.CLIENTE_CONJUGE AS CONJUGE
, C.CLIENTE_PROFISSAO AS PROFISSAO
, C.CLIENTE_EMPREGO_ATUAL AS LOCTRA
, C.CLIENTE_VALOR_LIMITE AS LIMITE_CREDITO
, C.CLIENTE_OBSERVACOES AS OBSERVACOES
, CI.CIDADE_NOME AS CIDADE
, CI.CIDADE_UF AS UF
, CASE PS.PESSOA_SEXO_DESC WHEN 'Masculino' THEN 'M' WHEN 'Feminino' THEN 'F' END AS SEXO
, PEC.PESSOA_EST_CIV_DESC AS EST_CIVIL
FROM CLIENTES C
LEFT JOIN CIDADES CI ON CI.CIDADE_ID = C.CLIENTE_CIDADE
LEFT JOIN PESSOA_SEXO PS ON PS.PESSOA_SEXO_ID = C.CLIENTE_SEXO
LEFT JOIN PESSOA_EST_CIVIL PEC ON PEC.PESSOA_EST_CIV_ID = C.CLIENTE_EST_CIVIL