SELECT PRODUTO.CODIGO_PRODUTO AS CODIGO,
PRODUTO.REFERENCIA_PRODUTO AS BARRAS,
PRODUTO.NOME_PRODUTO AS DESCRICAO,
PRODUTO.UNIDADE_PRODUTO AS UND,
TIPOTRIBUTACAO.CST_TIPOTRIBUTACAO AS ST,
PRODUTO.CODIGO_NCM AS COD_NCM,
PRODUTO.CEST_PRODUTO AS PERSONAL6,
PRODUTO_EMPRESA.VALORCUSTO_PRODUTO AS PRECO_CUSTO,
PRODUTO_EMPRESA.VALORVENDA_PRODUTO AS PRECO_VENDA
FROM PRODUTO
LEFT JOIN TIPOTRIBUTACAO ON PRODUTO.CODIGO_TIPOTRIBUTACAO=TIPOTRIBUTACAO.CODIGO_TIPOTRIBUTACAO
LEFT JOIN PRODUTO_EMPRESA ON PRODUTO.CODIGO_PRODUTO = PRODUTO_EMPRESA.CODIGO_PRODUTO
