select CLIENTES.ID_CLIENTE AS CODIGO,
CLIENTES.NOME,
CLIENTES.TELEFONE,
CLIENTES.EMAIL,
CLIENTES.CPF_CNPJ AS CNPJ_CNPF,
CLIENTES.RG AS IE_RG,
CLIENTES.ENDERECO,
CIDADES.NOME_CIDADE AS CIDADE,
ESTADOS.SIGLA AS UF,
CLIENTES.DATA_CADASTRO AS CADASTRO,
CLIENTES.BAIRRO,
CLIENTES.CEP,
CLIENTES.CELULAR
FROM CLIENTES
LEFT JOIN CIDADES ON CLIENTES.ID_CIDADE = CIDADES.ID_CIDADE
LEFT JOIN ESTADOS ON  CIDADES.ID_ESTADO = ESTADOS.ID_ESTADO
