SELECT PRODUTOS.ID_PRODUTO AS CODIGO,
PRODUTOS.DESCRICAO,
PRODUTOS.ESTOQUE AS QTD,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.VALOR AS PRECO_VENDA,
PRODUTOS.DATA_COMPRA AS ULTIMA_COMPRA,
PRODUTOS.CUSTO AS PRECO_CUSTO,
PRODUTOS.LUCRO AS MARGEM_LUCRO,
PRODUTOS.COD_BARRAS AS BARRAS,
CATEGORIAS_PRODUTOS.NOME_CATEGORIA AS GRUPO,
PRODUTOS.REFERENCIA AS COD_FABRICANTE,
SUBSTRING (PRODUTOS.SITUACAO_TRIBUTARIA FROM 1 FOR 2) AS ST
FROM PRODUTOS
LEFT JOIN CATEGORIAS_PRODUTOS ON PRODUTOS.CATEGORIA = CATEGORIAS_PRODUTOS.ID_CATEGORIA
