SELECT TRECCLIENTEGERAL.CODIGO,
TGERCIDADE.NOME AS CIDADE,
TGERCIDADE.ESTADO AS UF,
TRECCLIENTEGERAL.CPFCNPJ AS CNPJ_CNPF,
TRECCLIENTEGERAL.RGIE AS IE_RG,
TRECCLIENTEGERAL.NOME,
TRECCLIENTEGERAL.FANTASIA,
TRECCLIENTEGERAL.ENDERECO,
TRECCLIENTEGERAL.COMPLEMENTO,
TRECCLIENTEGERAL.BAIRRO,
TRECCLIENTEGERAL.CEP,
TRECCLIENTEGERAL.FONE AS TELEFONE,
TRECCLIENTEGERAL.FAX,
TRECCLIENTEGERAL.EMAIL,
TRECCLIENTEGERAL.CLIENTEDESDE AS CADASTRO,
TRECCLIENTEGERAL.FONECELULAR AS CELULAR,
TRECCLIENTEGERAL.NUMEROENDERECO AS NUMERO,
TRECCLIENTEGERAL.OBS AS OBSERVACOES
FROM TRECCLIENTEGERAL
LEFT JOIN TGERCIDADE ON TRECCLIENTEGERAL.CIDADE=TGERCIDADE.CODIGO
WHERE TRECCLIENTEGERAL.CODIGO NOT IN('88888','99999')
