SELECT TPAGFORNECEDOR.CODIGO,
TGERCIDADE.NOME AS CIDADE,
TGERCIDADE.ESTADO AS UF,
TPAGFORNECEDOR.NOME,
TPAGFORNECEDOR.FANTASIA,
TPAGFORNECEDOR.CPFCNPJ AS CNPJ_CNPF,
TPAGFORNECEDOR.RGIE AS IE_RG,
TPAGFORNECEDOR.ENDERECO,
TPAGFORNECEDOR.COMPLEMENTO,
TPAGFORNECEDOR.BAIRRO,
TPAGFORNECEDOR.CEP,
TPAGFORNECEDOR.FONE AS TELEFONE,
TPAGFORNECEDOR.FAX,
TPAGFORNECEDOR.EMAIL,
TPAGFORNECEDOR.CONTATO,
TPAGFORNECEDOR.OBSERVACAO AS OBSERVACOES,
TPAGFORNECEDOR.NUMEROENDERECO AS NUMERO
FROM TPAGFORNECEDOR
LEFT JOIN TGERCIDADE ON TPAGFORNECEDOR.CIDADE=TGERCIDADE.CODIGO
