SELECT
  tbclientes.codcliente AS CODIGO,
  case when tbclientes.cnpj = '' or tbclientes.cnpj is null then tbclientes.cpf else tbclientes.cnpj END as CNPJ_CNPF,
  tbclientes.cpf,
  tbclientes.inscricaoestadual AS IE_RG,
  tbclientes.inscricaomunicipal AS IM,
  tbclientes.nomerazao AS NOME,
  tbclientes.nomefantasia AS FANTASIA,
  tbclientes.sexo AS SEXO,
  tbclientes.datanascimento AS NASCIMENTO,
  tbclientes.nomemae AS MAE,
  tbclientes.nomepai AS PAI,
  tbclientes.cepc AS CEP,
  tbclientes.logradouroc AS ENDERECO,
  tbclientes.bairroc AS BAIRRO,
  tbclientes.numeroc AS NUMERO,
  tbclientes.complementoc AS COMPLEMENTO,
  tbclientes.ufc AS UF,
  tbclientes.cidadec AS CIDADE,
  tbclientes.telefonegeral AS TELEFONE,
  tbclientes.telefonefax AS FAX,
  tbclientes.emailgeral AS EMAIL,
  tbclientes.observacoes AS OBSERVACOES, 
  tbclientes.limitecredito AS LIMITE_CREDITO,  
  tbclientes.telefonecelular AS CELULAR
FROM tbclientes