SELECT
  CADFORNECEDOR.FOR_CODIGO AS CODIGO,
  CADFORNECEDOR.FOR_RAZAOSOCIAL AS NOME,
  CADFORNECEDOR.FOR_FANTASIA AS FANTASIA,
  CADFORNECEDOR.FOR_CNPJ AS CNPJ_CNPF,
  CADFORNECEDOR.FOR_IE AS IE_RG,
  CADFORNECEDOR.FOR_ENDERECO AS ENDERECO,
  CADFORNECEDOR.FOR_COMPL AS COMPLEMENTO,
  CADFORNECEDOR.FOR_BAIRRO AS BAIRRO,
  CADFORNECEDOR.FOR_CEP AS CEP,
  CADCIDADE.CID_NOME AS CIDADE,
  CADFORNECEDOR.FOR_FONE AS TELEFONE,
  CADFORNECEDOR.FOR_FAX AS FAX,
  CADFORNECEDOR.FOR_CONTATO AS CONTATO,
  CADFORNECEDOR.FOR_ENDNUM AS NUMERO,
  CADFORNECEDOR.CID_CODIGO AS CIDADE
FROM CADFORNECEDOR
LEFT JOIN CADCIDADE ON CADCIDADE.CID_CODIGO = CADFORNECEDOR.CID_CODIGO
