SELECT
PRODUTO.COD_PRO AS CODIGO,
PRODUTO.NOME_PRO AS DESCRICAO,
PRODUTO.VALOR_PRO AS PRECO_VENDA,
PRODUTO.PRECO_CUSTO  AS PRECO_CUSTO,
PRODUTO.REFERENCIA_PRO AS COD_FABRICANTE,
PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
PRODUTO.CSOSN AS ST,
PRODUTO.CEST AS PERSONAL6,
PRODUTO.CST_PIS AS PIS_CODIGO,
PRODUTO.CST_COFINS AS COFINS_CODIGO,
PRODUTO.CST_IPI AS IPI_CODIGO,
PRODUTO.COD_NCM,
ESTOQUE.ESTOQUE AS QTD,
UNIDADE_MEDIDA.DESCRICAO AS UND
FROM PRODUTO
LEFT JOIN ESTOQUE ON PRODUTO.COD_PRO = ESTOQUE.COD_PRO
LEFT JOIN UNIDADE_MEDIDA ON UNIDADE_MEDIDA.CODIGO = PRODUTO.CODIGO_UNIDADE_SAIDA 