SELECT
	CODIGOPARCEIRO AS CODIGO,
--	CLIENTEFORNECEDOR,
	DESCRICAO AS NOME,
	NOMEFANTASIA AS FANTASIA,	
	CONTATO,
	CPFCGC CNPJ_CNPF,
	case when RG = '' or RG is null then INSCRICAOESTADUAL else RG END AS IE_RG,
	INSCRICAOMUNICIPAL AS IM,	
	ENDERECO,
	NUMEROLOGRADOURO AS NUMERO,
	COMPLEMENTOLOGRADOURO AS COMPLEMENTO,	
	BAIRRO,
	CIDADE,
	ESTADO AS UF,
	CEP,
	FONE1 AS TELEFONE,
	FONE2 AS CELULAR,
	FAX,
	OBSERVACAO AS OBSERVACOES,
	EMAIL
FROM
	CADPARCEIRO	
