SELECT
    PRODUTO.CODIGO_PRODUTO AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO_UNIDADE.ABREVIACAO AS UND,
    PRODUTO.CODIGO_BARRA AS BARRAS,
    PRODUTO.PESO_LIQUIDO AS PESO,
    PRODUTO_GRUPO.DESCRICAO AS GRUPO,
    PRODUTO.ESTOQUE_MINIMO AS QTD_IDEAL,
    PRODUTO_ESTOQUE.QUANTIDADE AS QTD,
    PRODUTO.PRECO_CUSTO_COMPRA AS PRECO_CUSTO,
    PRODUTO.PERCENUTAL_LUCRO AS MARGEM_LUCRO,
    PRODUTO.PRECO_VENDA AS PRECO_VENDA,
    PRODUTO.CST_ICMS_VENDA AS ST,
    NCM.NUMERO AS COD_NCM,
    CEST.NUMERO AS PERSONAL6,
    PRODUTO.DATA_CAD AS DATA_CADASTRO,
    PRODUTO.SITUACAO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE
FROM PRODUTO
LEFT JOIN PRODUTO_ESTOQUE ON PRODUTO_ESTOQUE.CODIGO_PRODUTO = PRODUTO.CODIGO
LEFT JOIN NCM ON NCM.CODIGO = PRODUTO.CODIGO_NCM
LEFT JOIN PRODUTO_UNIDADE ON PRODUTO_UNIDADE.CODIGO = PRODUTO.CODIGO_UNIDADE
LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.CODIGO = PRODUTO.CODIGO_GRUPO
LEFT JOIN CEST ON CEST.CODIGO = PRODUTO.CODIGO_CEST