SELECT
    CODPESSOA AS CODIGO,
    NOME,
    CPFCGC AS CNPJ_CNPF,
    IE AS IE_RG,
    EMAIL,
    FONES AS TELEFONE,
    LOGRADOURO_1 AS ENDERECO,
    COMPLEMENTO_1 AS COMPLEMENTO,
    BAIRRO_1 AS BAIRRO,
    CIDADE_1 AS CIDADE,
    UF_1 AS UF,
    CEP_1 AS CEP,
    CELULAR AS CELULAR,
    PESSOA_CONTATO AS CONTATO,
    NUMERO_1 AS NUMERO
FROM PESSOA
WHERE PESSOA.TIPOpessoa = 'Fornecedor'