SELECT 
      PRODUTOS.Codigo AS CODIGO
      ,PRODUTOS.CodigoBarra AS BARRAS
      ,PRODUTOS.Descricao AS DESCRICAO
      ,PRODUTOS.Unidade AS UND
      ,PRODUTOS.PrCusto AS PRECO_CUSTO
      ,PRODUTOS.MARGEM AS MARGEM_LUCRO
      ,PRODUTOS.PrVenda AS PRECO_VENDA
      ,PRODUTOS.ClassPis AS PIS_CODIGO
      ,PRODUTOS.ClassCofins AS COFINS_CODIGO
      ,PRODUTOS.CodNCM AS COD_NCM
      ,PRODUTOS.Cest AS PERSONAL6
      ,PRODUTOS.tributacao2 AS ST
      ,PRODUTOS.Estoque AS QTD
      ,PRODUTOS.nomfornecedor AS FORNECEDOR
      ,PRODUTOS.codfabricante AS COD_FABRICANTE
      ,PRODUTOS.nomgrupo AS GRUPO
      ,PRODUTOS.Referencia AS CARACTERISTICAS
      ,PRODUTOS.PrAtacado AS PRECO_ATACADO
  FROM NFCE.dbo.Produtos
