SELECT
       PRODUTO.COD_PRODUTO AS CODIGO,
       PRODUTO.COD_PRODUTOINFO AS COD_FABRICANTE,
       PRODUTO.DESCRICAO AS DESCRICAO,
       PRODUTO.CONTA_NCM AS COD_NCM,
       PRODUTO.EAN AS BARRAS,
       PRODUTO_PRECO.PRECO_CUSTO AS PRECO_CUSTO,
       PRODUTO_PRECO.MARGEM_1 AS MARGEM_LUCRO,
       PRODUTO_PRECO.VALOR_TABELA_1 AS PRECO_VENDA,
       MARCA.DESCRICAO AS CARACTERISTICAS,
       PRODUTO.PESO AS PESO,
       PRODUTO.cod_classificacao as st,
       SD_ESTOQUE.SALDO_ATUAL AS QTD,
       PRODUTO.NUM_CEST AS PERSONAL6,
       PRODUTO.DATA_CADASTRO AS DATA_CADASTRO,
       GRUPO.DESCRICAO AS GRUPO,
       MARCA.DESCRICAO    || '<<' || PRODUTO.COD_PRODUTO || '<<' || PRODUTO.DESCRICAO  AS MARCA,
       PRODUTO.REFERENCIA || '<<' || PRODUTO.COD_PRODUTO || '<<' || PRODUTO.DESCRICAO  AS OBSERVACOES,
       UNIDADE_MEDIDA.UNIDADE AS UND
FROM PRODUTO
INNER JOIN SD_ESTOQUE ON PRODUTO.COD_PRODUTO = SD_ESTOQUE.COD_PRODUTO
LEFT  JOIN UNIDADE_MEDIDA ON PRODUTO.COD_UNIDADE = UNIDADE_MEDIDA.COD_UNIDADE
LEFT  JOIN MARCA ON PRODUTO.COD_MARCA = MARCA.COD_MARCA
LEFT  JOIN GRUPO ON PRODUTO.COD_GRUPO = GRUPO.COD_GRUPO
INNER JOIN PRODUTO_PRECO ON PRODUTO.COD_PRODUTO = PRODUTO_PRECO.COD_PRODUTO
