SELECT
    PRODUTO.CODIGO AS CODIGO,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.PRODUTO AS DESCRICAO,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.UNIDADE AS UND_COMPRA,
    PRODUTO.ESTOQUE AS QTD,
    FORNECEDOR.NOME AS FORNECEDOR,
    PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTO.PRECOVENDA AS PRECO_VENDA,
    SUBSTRING (PRODUTO.CST FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.CST FROM 2 FOR 3) AS ST,
    CAST (PRODUTO.DATA_ULTIMACOMPRA AS DATE) AS ULTIMA_COMPRA,
    CAST (PRODUTO.DATA_ULTIMAVENDA AS DATE) AS ULTIMA_VENDA,
    CAST (PRODUTO.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.CLASSIFICACAO_FISCAL AS COD_NCM
FROM PRODUTO
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTO.CODFORNECEDOR