SELECT
	CASE
		C.TIPO_CLIENTE WHEN 'F' THEN (CONCAT (C.NOME,
		'',
		C.SOBRENOME))
		ELSE C.NOME
	END AS NOME,
	C.SOBRENOME AS FANTASIA,
	C.CEP,
	C.ENDERECO,
	C.NUMERO,	
	C.COMPLEMENTO,
	C.BAIRRO,
	C.E_MAIL AS EMAIL,
	C.ENDERECO_COBRANCA AS COB_ENDERECO,
	C.NUMERO_COBRANCA AS COB_NUMERO,	
	C.CEP_COBRANCA AS COB_CEP,
	C.COMPLEMENTO_COBRANCA AS COB_COMPLEMENTO,
	C.BAIRRO_COBRANCA AS COB_BAIRRO,
	C.CIDADE_COBRANCA AS COB_CIDADE,
	C.UF_COBRANCA AS COB_UF,
	C.TELEFONE1 AS TELEFONE,
	C.TELEFONE2 AS FAX,
	C.CELULAR,
	C.CPF AS CNPJ_CNPF,
	C.RG AS IE_RG,
	C.DATA_ULTIMA_COMPRA AS ULTIMA_VENDA,
	C.LIMITE AS LIMITE_CREDITO,
	C.DATA_NASCIMENTO AS NASCIMENTO,
	C.SEXO,
	C.OBSERVACOES,
	C.NOME_CONJUGUE AS CONJUGE,
	CI.DESCRICAO AS CIDADE, 
	CI.UF
FROM
	CLIENTE C
LEFT JOIN CIDADE CI ON CI.COD_CIDADE = C.COD_CIDADE
WHERE
	COD_LOJA = '1' -- CÓDIGO DA LOJA (TABELA LOJA)
