SELECT
	F.COD_FORNECEDOR AS CODIGO,
	F.RAZAO_SOCIAL AS NOME,
	F.FANTASIA,
	F.CNPJ AS CNPJ_CNPF,
	F.INSCRICAO_ESTADUAL AS IE_RG,
	F.CEP,
	F.ENDERECO,
	F.COMPLEMENTO,
	F.BAIRRO,
	F.TELEFONE1 AS TELEFONE,
	F.TELEFONE2 AS CELULAR,
	F.E_MAIL AS EMAIL,
	F.CONTATO,
	CI.DESCRICAO AS CIDADE, 
	CI.UF
FROM
	FORNECEDOR F
LEFT JOIN CIDADE CI ON CI.COD_CIDADE = F.COD_CIDADE
