SELECT
	P.COD_PRODUTO AS CODIGO,
	P.DESCRICAO,
	P.COD_UNIDADE_COMPRA AS UND_COMPRA,
	P.COD_UNIDADE_VENDA AS UND,	
	CASE P.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	P.INFORMACAO AS OBSERVACOES,
	P.REFERENCIA_FORNECEDOR AS COD_FABRICANTE,
	P.COD_SITUACAO_TRIBUTARIA AS ST,
--	P.CSOSN AS ST,	
	P.ALIQUOTA AS ELO,	
	P.COD_NCM,
	P.COD_EAN AS BARRAS,
	P.PERCENTUAL_COMISSAO_VENDA AS COMISSAO,
	P.CARACTERISTICAS,
	P.ORIGEM_MERCADORIA AS OST,
	P.PERCENTUAL_PIS AS PIS_ALIQ_NOR,
	P.PERCENTUAL_COFINS AS COFINS_ALIQ_NOR,
	P.PERCENTUAL_MARKUP AS MARGEM_LUCRO,
	P.ESTOQUE_MINIMO AS QTD_IDEAL,
	P.DATA_ULTIMA_VENDA AS ULTIMA_VENDA,
	P.VALOR_CUSTO AS PRECO_CUSTO,
	P.VALOR_VENDA_VAREJO AS PRECO_VENDA,
	P.LOCALIZACAO AS PERSONAL1,
	P.ST_PIS_COFINS_ENTRADA AS PISE_CODIGO,
	P.ST_PIS_COFINS_SAIDA AS COFINSE_CODIGO,
	P.COD_ANP,
	P.COD_CEST AS PERSONAL6,
	GP.DESCRICAO AS GRUPO,
	S.DESCRICAO AS FAMILIA,
	F.RAZAO_SOCIAL AS FORNECEDOR,
	SA.quantidade as QTD
FROM
	PRODUTO P
LEFT JOIN GRUPO_PRODUTO GP ON GP.COD_GRUPO_PRODUTO = P.COD_GRUPO_PRODUTO 
LEFT JOIN SUBGRUPO S ON S.COD_SUBGRUPO = P.COD_SUBGRUPO 
LEFT JOIN FORNECEDOR F ON F.COD_FORNECEDOR = P.COD_FORNECEDOR 
LEFT JOIN GRADE_PRODUTO GR ON GR.COD_PRODUTO = P.COD_PRODUTO 
LEFT JOIN SALDO SA ON SA.COD_GRADE_PRODUTO = GR.COD_GRADE_PRODUTO AND  SA.COD_LOJA = '1' -- CÓDIGO DA LOJA (TABELA LOJA)
