SELECT
    ITEM.ITE_CODIGO AS BARRAS,
    ITEM.ITE_DESCRICAO AS DESCRICAO,
    ITENS_EMPRESAS.ISE_ESTOQUE AS QTD,
    UNIDADE.UNI_DESCRICAO AS UND,
    ITENS_EMPRESAS.ISE_CLF_CODIGO AS ST,
    GRUPO.GRP_DESCRICAO AS GRUPO,
    ITENS_EMPRESAS.ISE_VALOR_VENDA AS PRECO_VENDA,
    ITENS_EMPRESAS.ISE_CUSTO_MEDIO AS CUSTO_MEDIO,
    ITENS_EMPRESAS.ISE_VALOR_CUSTO AS PRECO_CUSTO,
    ITENS_EMPRESAS.ISE_MARGEM_LUCRO AS MARGEM_LUCRO,
    ITENS_EMPRESAS.ISE_VALOR_PROMOCAO AS PRECO_ATACADO,
    ITEM.ITE_CODIGO_FABRIC AS COD_FABRICANTE,
    ITEM.ITE_ULT_ENTRADA AS ULTIMA_COMPRA,
    ITEM.ITE_ULT_SAIDA AS ULTIMA_VENDA,
    ITEM.ITE_PESO_LIQUIDO AS PESO,
    CAST (ITEM.ITE_DATACADASTRO AS DATE) AS DATA_CADASTRO,
    ITEM.ITE_OBSERVACAO AS OBSERVACOES,
    ITEM.CLN_CODIGO AS COD_NCM,
    ITEM.ITE_CEST_CODIGO AS PERSONAL6,
    case when ITENS_EMPRESAS.ISE_ATIVO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO
FROM ITEM
LEFT JOIN ITENS_EMPRESAS ON ITENS_EMPRESAS.ISE_ITE_ID = ITEM.ITE_ID
LEFT JOIN GRUPO ON GRUPO.GRP_CODIGO = ITEM.GRP_CODIGO
LEFT JOIN UNIDADE ON UNIDADE.UNI_CODIGO = ITEM.UNI_CODIGO