SELECT
    replace(PROD.COD,'.','') AS CODIGO,
    PROD.codind AS BARRAS,
    PROD.PRODUTO AS DESCRICAO,
    PROD.UNID AS UND,
    PRO.QUANT AS QTD,
    PROD.EST_MIN AS QTD_IDEAL, 
    PROD.PVEND AS PRECO_VENDA,
    PROD.CSOSN AS ST,
    PROD.OBS AS OBSERVACOES,
    PROD.NCM AS COD_NCM,
    PROD.CEST AS PERSONAL6,
    CAST (PROD.ULTIMAALTERACAOPRECO AS DATE) AS ALTERACAO_PRECO
FROM PROD
LEFT JOIN PRO ON PRO.COD = PROD.COD  