SELECT
  CLIENTE.ID AS PERSONAL1,
  CLIENTE.DOC_CLIENTE AS CNPJ_CNPF,
  CLIENTE.NOME_CLIENTE AS FANTASIA,
  CLIENTE.razao_social AS NOME,
  CLIENTE.TELEFONE AS TELEFONE,
  CLIENTE.CELULAR AS CELULAR,
  CLIENTE.ENDERECO AS ENDERECO,
  CLIENTE.NUMERO AS NUMERO,
  CLIENTE.COMPLEMENTO AS COMPLEMENTO,
  CLIENTE.CEP AS CEP,
  CLIENTE.BAIRRO AS BAIRRO,
  CLIENTE.CIDADE AS CIDADE,
  CLIENTE.UF AS UF,
  cliente.data_nascimento AS NASCIMENTO,
  cliente.obs AS OBSERVACOES
FROM CLIENTE