 SELECT
    M.CODIGO AS CODIGO,
    M.CODFAB AS BARRAS,
    M.MERCADORIA AS DESCRICAO,
    U.ABREVIATURA AS UND,
    M.FORNECEDOR AS FORNECEDOR,
    ME.SALDO_ESTOQUE AS QTD,
    M.MINIMO AS QTD_IDEAL,
    M.PESO_LIQUIDO AS PESO,
    M.GRUPODESC AS GRUPO,
    M.MARCA AS FAMILIA,
    M.CUSTO AS PRECO_CUSTO,
    ME.CUSTO_MEDIO AS CUSTO_MEDIO,
    MAX (MLP.MARGEM) AS MARGEM_LUCRO,
    MAX (MLP.PRECO_FINAL) AS PRECO_VENDA,
    M.ECFNUM AS ST,
    M.CODEMP AS COD_FABRICANTE,
    M.APLICACAO AS OBSERVACOES,
    M.DATA_INGRESSO AS CADASTRO,
    M.CODIGO_NCM AS COD_NCM,
    M.CEST AS PERSONAL6,
    M.DATA_ULTIMA_ENTRADA AS ULTIMA_COMPRA,
    case when M.ATIVO = 'S' then 'Ativo' else 'Inativo' end as situacao
FROM MERCADORIAS AS M
LEFT JOIN UNIDADES U ON M.UNIDADE = U.CODIGO
LEFT JOIN MERCADORIAS_ESTOQUE ME ON M.CODIGO = ME.CODIGO_MERCADORIA
LEFT JOIN MERCADORIAS_LISTA_PRECOS MLP ON M.CODIGO = MLP.CODIGO_MERCADORIAS
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,15,16,17,18,19,20,21,22
