SELECT 
  CLIENTE_ID AS CODIGO
, NOME
, NOME_FANTASIA AS FANTASIA
, CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
, CASE WHEN CARTEIRAIDENTIDE = '' OR CARTEIRAIDENTIDE IS NULL THEN INSCEST ELSE CARTEIRAIDENTIDE END AS IE_RG
, INSCRICAO_MUNICIPAL AS IM
, LIMITE_CREDITO AS LIMITE_CREDITO
, EMAIL
, ENDERECO
, CIDADE
, BAIRRO
, UF
, CEP
, DDD || FONE1 AS TELEFONE
, DDD || FONE2 AS CELULAR
, DDD || FAX AS FAX
, CONTATO
, ENDERECO_COBR AS COB_ENDERECO
, CIDADE_COBR AS COB_CIDADE
, BAIRRO_COBR AS COB_BAIRRO
, UF_COBR AS COB_UF
, CEP_COBR AS COB_CEP
, OBSERVACAO AS OBSERVACOES
, ESTADOCIVIL AS EST_CIVIL
, CAST(DATANASCIMENTO AS DATE) AS NASCIMENTO
, NOMEPAI AS PAI 
, NOMEMAE AS MAE
, CONJUGE
, LOCALTRABALHO AS LOCTRA
, CAST(DATA_ULTIMA_MOVIMENTACAO AS DATE) AS ULTIMA_VENDA
FROM CLIENTE
