SELECT 
  FORNECEDOR_ID AS CODIGO
, NOME
, NOME_FANTASIA AS FANTASIA
, CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END AS CNPJ_CNPF
, INSCEST AS IE_RG
, INSCRICAO_MUNICIPAL AS IM
, ENDERECO
, BAIRRO
, CEP
, CIDADE
, UF
, DDD || FONE1 AS TELEFONE
, DDD || FONE2 AS CELULAR
, DDD_FAX || FAX AS FAX
, CONTATO
, EMAIL
, OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR
