SELECT 
  P.PRODUTO_ID AS CODIGO
, P.CODIGO_PRODUTO AS BARRAS
, P.DESCRICAO
, P.ESTOQUE_ATUAL AS QTD
, P.ESTOQUE_MINIMO AS QTD_IDEAL
, P.PRECO_CUSTO AS PRECO_CUSTO
, P.PRECO_CUSTO_MEDIO AS CUSTO_MEDIO
, P.MARGEM_LUCRO AS MARGEM_LUCRO
, P.PRECO_VENDA AS PRECO_VENDA
--, P.CARACTERISTICA AS PERSONAL1
, P.MODELO AS PERSONAL2
, P.PRECO_PRAZO AS PERSONAL4
--, P.PRECO_VISTA AS PERSONAL5
, P.CEST AS PERSONAL6
, CAST(DATA_ULT_COMPRA AS DATE) AS ULTIMA_COMPRA
, CAST(DATA_ULT_VENDA AS DATE) AS ULTIMA_VENDA
, P.VALIDADE AS VALIDADE_DIAS
, P.FATOR AS FAT_CONV
, P.PESO_BRUTO AS PESO
, CASE P.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.NOMECLATURA_MERCOSUL AS COD_NCM
, P.NUMERO_FABRICACAO AS COD_FABRICANTE
, P.ALIQUOTA_IPI AS ALIQ_IPI_VENDA
, P.CST_IPI AS IPI_CODIGO_VENDA
, P.CST_PIS AS PISE_CODIGO
, P.CST_COFINS AS COFINSE_CODIGO
, P.ALIQUOTA_PIS_COFINS AS PISE_ALIQ_NOR
, P.ALIQUOTA_COFINS AS COFINSE_ALIQ_NOR
, P.CST_PIS_SAIDA AS PIS_CODIGO
, P.CST_COFINS_SAIDA AS COFINS_CODIGO
, P.ALIQUOTA_PIS_COFINS_SAIDA AS PIS_ALIQ_NOR
, P.ALIQUOTA_COFINS_SAIDA AS COFINS_ALIQ_NOR
, P.IPPT
, CAST(P.DATA_INCLUSAO AS DATE) AS DATA_CADASTRO
, P.OUTRAS_OBSERVACOES AS OBSERVACOES
, P.CFOP_DENTRO_UF AS CF
, SUBSTRING (P.CFOP_DENTRO_UF FROM 1 FOR 3) AS ELO
--, P.ALIQUOTA_ICMS AS ST
, P.CST_SAIDA AS ST
, P.CODIGO_ANP AS COD_ANP
, U.UNIDADE AS UND
, F.DESCRICAO AS FORNECEDOR
, TP.DESCRICAO AS PERSONAL5
, G.DESCRICAO AS GRUPO
, FA.DESCRICAO AS FAMILIA
FROM PRODUTO P
LEFT JOIN UNIDADEMEDIDA U ON U.UNIDADE_MEDIDA_ID = P.UNIDADE_MEDIDA_ID 
LEFT JOIN FABRICANTE F ON F.FABRICANTE_ID = P.FABRICANTE_ID 
LEFT JOIN PRODUTOTIPOITEM TP ON TP.PRODUTOTIPOITEM_ID = P.PRODUTOTIPOITEM_ID 
LEFT JOIN GRUPOPRODUTO G ON G.GRUPO_PRODUTO_ID = P.GRUPO_PRODUTO_ID
LEFT JOIN FAMILIA FA ON FA.FAMILIA_ID = P.FAMILIA_ID
