SELECT CLIENTES.CLI_ID AS CODIGO,
CLIENTES.CLI_NOM AS NOME,
CLIENTES.CLI_ENDCOR AS ENDERECO,
CLIENTES.CLI_NUMCOR AS NUMERO,
CLIENTES.CLI_CMPCOR AS COMPLEMENTO,
CLIENTES.CLI_BAICOR AS BAIRRO,
CLIENTES.CLI_CEPCOR AS CEP,
CLIENTES.CLI_CNPJCPF AS CNPJ_CNPF,
CLIENTES.CLI_IERG AS IE_RG,
CLIENTES.CLI_EMAIL AS EMAIL,
CLIENTES.CLI_TEL AS TELEFONE,
CLIENTES.CLI_CEL AS CELULAR,
CLIENTES.CLI_FAX AS FAX
FROM CLIENTES





