SELECT PRODUTOS.PRO_ID AS CODIGO,
GRUPOS.GRP_DES AS GRUPO,
PRODUTOS.PRO_DES AS DESCRICAO,
PRODUTOS.PRO_UND AS UND,
PRODUTOS.PRO_CODBAR AS BARRAS,
ESTOQUE.ETQ_PRCVEN AS PRECO_VENDA,
ESTOQUE.ETQ_QTDATU AS QTD
FROM PRODUTOS
LEFT JOIN GRUPOS ON PRODUTOS.GRP_ID=GRUPOS.GRP_ID
LEFT JOIN ESTOQUE ON PRODUTOS.PRO_ID=ESTOQUE.PRO_ID




