SELECT
	CODIGO,
	CASE
		WHEN RAZAO_SOCIAL = ''
		OR RAZAO_SOCIAL IS NULL THEN CODIGO
	END AS NOME,
	FANTASIA,
	CNPJ AS CNPJ_CNPF,
	CASE
		WHEN RG = ''
		OR RG IS NULL THEN INSCRICAO
		ELSE RG
	END AS IE_RG,
	CEP,
	CIDADE,
	UF,
	ENDERECO,
	COMPLEMENTO,
	NUMERO,
	SETOR AS BAIRRO,
	TELEFONE,
	FAX,
	CONTATO,
	CELULAR,
	EMAIL,
	OBS AS OBSERVACOES,
	DTNASC AS NASCIMENTO,
	TRABALHO AS LOCTRA,
	CARGO AS PROFISSAO,
	CREDITO AS LIMITE_CREDITO,
	CASE
		INDICADORIE WHEN '1' THEN 'C'
		WHEN '2' THEN 'N'
		WHEN '9' THEN 'I'
	END AS INDIEDEST
FROM PESSOAS
WHERE CODIGO <> '0'
AND
--WHERE CLIENTE = '1';
FORNECEDOR <> '1';