SELECT
	P.IDPRODUTO AS CODIGO,
	P.CODIGO AS BARRAS,
	P.CODREF AS COD_FABRICANTE,
	P.CODLOJA AS PERSONAL1,
	P.PRODUTO AS DESCRICAO,
	P.MEDIDA AS UND,
	P.ALIQUOTA AS ELO,
	P.ESTOQUE AS QTD,
	P.MINIMO AS QTD_IDEAL,
	P.CUSTO AS PRECO_CUSTO,
	P.CUSTOMEDIO AS CUSTO_MEDIO,
	P.LUCRO AS MARGEM_LUCRO,
	P.VENDA AS PRECO_VENDA,
	P.PROMOCAO AS PERSONAL5,
	P.DT_ULTCOMPRA AS ULTIMA_COMPRA,
	P.DT_ULTVENDA AS ULTIMA_VENDA,
	COALESCE(P.DT_CAD, CURRENT_DATE) AS DATA_CADASTRO,
	P.LOCALIZACAO AS PERSONAL2,
	P.COMISSAO,
	P.MARCA AS FAMILIA,
	P.NCM AS COD_NCM,
	P.TIPO_ITEM AS PERSONAL4,
	CASE
		P.ATIVO WHEN '1' THEN 'Ativo'
		ELSE 'Inativo'
	END AS SITUACAO,
	P.CEST AS PERSONAL6,
	--	P.UTRIB AS MED_TRIB,
	P.OBSPROD AS OBSERVACOES,
	P.ORIGEM AS OST,
	P.CSTPISCOFINS_S AS PIS_CODIGO,
	P.CSTPISCOFINS_S AS COFINS_CODIGO,
	P.PIS_S AS PIS_ALIQ_NOR,
	P.COFINS_S AS COFINS_ALIQ_NOR,
	--	P.CST AS ST,
	G.GRUPO,
	PE.RAZAO_SOCIAL AS FORNECEDOR,
	GT.CSOSN AS ST
	--	GT.CSTPISCOFINS
FROM LOJA P
LEFT JOIN GRUPOS g ON G.CODGRU = P.CODGRU
LEFT JOIN PESSOAS pE ON PE.CODIGO = P.CODFOR
LEFT JOIN GRUPOTRIBUTARIO gT ON GT.IDGRUPOTRIBUTARIO = P.ID_GRUPOTRIBUTARIO	