SELECT ITEMSERV.ITEMSERV_CONTROLE AS CODIGO,
ITEMSERV.ITEMSERV_CODBARRAS AS BARRAS,
ITEMSERV.ITEMSERV_NOME AS DESCRICAO,
ITEMSERV.GRUPOITENS_NOME AS GRUPO,
ITEMSERV.CSTICMS_CODIGO AS ST,
ITEMSERV.NCM_CODIGO AS COD_NCM,
ITEMSERV.CEST_CODIGO AS PERSONAL6,
ITEMSERV.ITEMSERV_VLR_PR_CUSTO_UNIT AS PRECO_CUSTO,
ITEMSERV.ITEMSERV_VLR_PR_UNIT AS PRECO_VENDA,
ESTOQUE_SDTOT.ESTOQUE_SDTOT_SALDO_EP AS QTD
FROM ITEMSERV
LEFT JOIN ESTOQUE_SDTOT ON ITEMSERV.ITEMSERV_CONTROLE=ESTOQUE_SDTOT.ITEMSERV_CONTROLE
WHERE ITEMSERV.ITEMSERV_CONTROLE>0 and ESTOQUE_SDTOT.empresas_controle = 1
