SELECT 
    PRODSERV.CODPRODSERV AS CODIGO,
    PRODSERV.CODBARRA AS BARRAS,
    PRODSERV.DESCR AS DESCRICAO,
    PRODSERV.ABREV AS CARACTERISTICAS,
    PRODSERV.PESOUNIT AS PESO,
    PRODSERV.UNIDADE1 AS UND,
    PRODSERV.UNIDADE1 AS UND_COMPRA,
    ESTOQUE.PRCOMPRA AS PRECO_CUSTO,
    ESTOQUE.PRVENDA1 AS PRECO_VENDA, 
    ESTOQUE.SALDO AS QTD, 
    ESTOQUE.MARGEMLUCRO AS MARGEM_LUCRO, 
    ESTOQUE.DTULTIMAENTRADA AS ULTIMA_COMPRA,
    ESTOQUE.DTULTIMASAIDA AS ULTIMA_VENDA,
    PRODSERV.CODFABRICANTE AS COD_FABRICANTE,
    PRODSERV.CODNCM AS COD_NCM,
    PRODSERV.CODCEST AS PERSONAL6,
    PRODSERV.CST AS ST
FROM PRODSERV
LEFT JOIN ESTOQUE ON ESTOQUE.CODPRODSERV = PRODSERV.CODPRODSERV