SELECT CLIENTES.CODIGOCLI AS CODIGO,
CLIENTES.NOMECLI AS FANTASIA,
CLIENTES.ENDERCLI AS ENDERECO,
CLIENTES.BAIRROCLI AS BAIRRO,
CLIENTES.CIDADECLI AS CIDADE,
CLIENTES.ESTADOCLI AS UF,
CLIENTES.CEPCLI AS CEP,
CLIENTES.FONECLI AS TELEFONE,
CLIENTES.FAXCLI AS FAX,
CLIENTES.CPFCGC AS CNPJ_CNPF,
CLIENTES.IDENINSC AS IE_RG,
CLIENTES.EMAIL,
CLIENTES.RAZAO AS NOME
FROM CLIENTES






