SELECT
    ESTOQUE.CODIGO AS CODIGO,
    ESTOQUE.BARRAS AS BARRAS,
    ESTOQUE.NOME AS DESCRICAO,
    ESTOQUE.UND_V AS UND,
    ESTOQUE.UND_C AS UND_COMPRA,
    EST_ADICIONAIS.nome_fornecedor AS FORNECEDOR,
    ESTOQUE.CARACTERISTICA AS CARACTERISTICAS,
    ESTOQUE.GRUPO AS GRUPO,
    ESTOQUE.SUB_GRUPO AS FAMILIA,
    ESTOQUE.PESO_LIQUIDO AS PESO,
    ESTOQUE.QTD AS QTD,
    ESTOQUE.QTD_MINIMA AS QTD_IDEAL,
    ESTOQUE.PRECO_CUSTO AS PORECO_CUSTO,
    ESTOQUE.PRECO_VENDA AS PRECO_VENDA,
    ESTOQUE.PRECO_REVENDA AS PRECO_ATACADO,
    ESTOQUE.PRECO_CUSTO_MEDIO AS CUSTO_MEDIO,
    substring (EST_TRIBUTACAO.st from 1 for 1) as ost,
    substring (EST_TRIBUTACAO.st from 2 for 3) as st,
    ESTOQUE.NCM AS COD_NCM,
    EST_TRIBUTACAO.CEST AS PERSONAL6,
    est_adicionais.cod_fabricante AS COD_FABRICANTE,
    EST_ADICIONAIS.OBS AS OBSERVACOES,
    ESTOQUE.DATA_ULTIMA_COMPRA AS ULTIMA_COMPRA,
    ESTOQUE.DATA_ULTIMA_VENDA AS ULTIMA_VENDA,
    ESTOQUE.DATA_ALTERACAO_PRECO AS ALTERACAO_PRECO
FROM ESTOQUE
LEFT JOIN EST_ADICIONAIS ON EST_ADICIONAIS.codigo = ESTOQUE.codigo
LEFT JOIN EST_TRIBUTACAO ON EST_TRIBUTACAO.codigo = ESTOQUE.CODIGO
