SELECT 
  f.ID AS CODIGO
, f.NOME AS FANTASIA
, f.RAZAOSOCIAL AS NOME
, f.CONTATO
, f.TELEFONE
, f.ENDERECO
, f.BAIRRO
, ci.NOME AS CIDADE
, ci.UF 
, f.CEP
, f.EMAIL
, f.CELULAR
, f.CNPJ AS CNPJ_CNPF
, f.IE AS IE_RG
, f.NUMERO
FROM FORNECEDOR f
LEFT JOIN CIDADE_IBGE ci ON ci.ID = f.IDCIDADE 
