SELECT 
  p.ID AS CODIGO
, p.DT_INC AS DATA_CADASTRO
, CASE p.STATUS WHEN 'A' THEN 'Ativo' ELSE 'Inativo' end AS SITUACAO
, p.NOME AS DESCRICAO
, p.REFERENCIA AS COD_FABRICANTE
, g.NOME AS GRUPO
, s.NOME AS FAMILIA
, f.NOME AS FORNECEDOR
, p.DESCRICAO AS OBSERVACOES
, p.NCM AS COD_NCM
, p.CEST AS PERSONAL6
, p.CFOP AS CF
--, CST AS ST
, p.CSOSN AS ST
, p.ALIQ_ICMS AS ELO
, pie.SALDO AS QTD
, pie.SALDO_MINIMO AS QTD_IDEAL
--, pie.PREC_TAB2 
, pie.PREC_VENDA AS PRECO_VENDA
, pie.MARGEM_LUCRO 
, (select first 1 pi1.PESO from PRODUTO_ITEM pi1 where pi1.ID = p.ID order by pi1.DT_ALT  desc) AS PESO
, (select first 1 pi2.PREC_CUSTO from PRODUTO_ITEM pi2 where pi2.ID = p.ID order by pi2.DT_ALT  desc) AS PRECO_CUSTO
, (select first 1 pi3.COD_FABRICA from PRODUTO_ITEM pi3 where pi3.ID = p.ID order by pi3.DT_ALT  desc) AS BARRAS
, (select first 1 pi4.UNIDADE from PRODUTO_ITEM pi4 where pi4.ID = p.ID order by pi4.DT_ALT  desc) AS UND
FROM PRODUTO p
LEFT JOIN FORNECEDOR f ON f.ID = p.IDFORNECEDOR 
LEFT JOIN GRUPO g ON g.ID = p.IDGRUPO 
LEFT JOIN SUB_GRUPO s ON s.ID = p.IDSUBGRUPO 
LEFT JOIN PRODUTO_ITEM_ESTOQUE pie ON pie.IDITEM = p.ID  
WHERE p.ID <> '0'
