SELECT
  PRODUTO.CODIGO AS CODIGO,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.REF_PRODUTO_AUXILIAR AS COD_FABRICANTE,
  PRODUTO.REF_PRODUTO_FORNEC AS CARACTERISTICAS,
  PRODUTO.DATA_CADASTRO AS DATA_CADASTRO,
  PRODUTO.DATA_ALTERACAO AS ALTERACAO_PRECO,
  PRODUTO.OBSERVACAO AS OBSERVACOES,
  ESTOQUE_PRODUTO.ESTOQUE AS QTD,
  PRODUTO_GRUPO.DESCRICAO AS GRUPO,
  PRODUTO_SUBGRUPO.DESCRICAO AS FAMILIA,
  FORNECEDOR.NOME AS FORNECEDOR,
  PRODUTO.DATA_ULTIMA_COMPRA AS ULTIMA_COMPRA,
  PRODUTO.DATA_ULTIMA_VENDA AS ULTIMA_VENDA,
  PRODUTO.CUSTO_MEDIO AS CUSTO_MEDIO,
  PRODUTO.PRECO_VENDA AS PRECO_VENDA,
  PRODUTO.CODIGO_BARRA AS BARRAS,
  MEDIDAS.SIGLA AS UND,
  MEDIDAS.SIGLA AS UND_COMPRA,
  --coalesce('APLICACAO: -- '||PRODUTO.APLICACAO1,'')||' '||coalesce(PRODUTO.APLICACAO2,'')||' '||coalesce(PRODUTO.APLICACAO3,'') AS OBSERVACOES,
  --PRODUTO.APLICACAO1 AS PERSONAL2,
  --PRODUTO.APLICACAO2 AS PERSONAL3,
  --PRODUTO.APLICACAO3 AS PERSONAL4,
  PRODUTO.NCM AS COD_NCM,
  SUBSTRING (PRODUTO.CSOSN FROM 2 FOR 4) AS ST,
  PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_GRUPO ON PRODUTO_GRUPO.CODIGO = PRODUTO.COD_GRUPO
LEFT JOIN PRODUTO_SUBGRUPO ON PRODUTO_SUBGRUPO.CODIGO = PRODUTO.COD_SUBGRUPO
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTO.COD_FORNECEDOR
LEFT JOIN MEDIDAS ON MEDIDAS.CODIGO = PRODUTO.CODIGO_MEDIDA_VENDA
LEFT JOIN ESTOQUE_PRODUTO ON ESTOQUE_PRODUTO.CODIGO_PRODUTO = PRODUTO.CODIGO
WHERE ESTOQUE_PRODUTO.codigo_estoque ='1'