SELECT TFORNECEDOR.CONTROLE AS CODIGO,
TFORNECEDOR.RAZAOSOCIAL AS NOME,
TFORNECEDOR.NOMEFANTASIA AS FANTASIA,
TFORNECEDOR.ENDERECO,
TFORNECEDOR.BAIRRO,
TFORNECEDOR.CIDADE,
TFORNECEDOR.UF,
TFORNECEDOR.CEP,
COALESCE(TFORNECEDOR.RG,TFORNECEDOR.IE) AS IE_RG,
COALESCE(TFORNECEDOR.CPF,TFORNECEDOR.CNPJ) AS CNPJ_CNPF,
TFORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
TFORNECEDOR.TELEFONE,
TFORNECEDOR.CELULAR,
TFORNECEDOR.EMAIL,
TFORNECEDOR.NUMERO
FROM TFORNECEDOR

