SELECT 
       PRODUTO.CDPRODUTO AS CODIGO
      ,PRODUTO.DESCRICAO AS DESCRICAO
      ,MAX (BARRA.BARRA) AS BARRAS
      ,MAX (BALANCO.QTDE) AS QTD
      ,UNIDADE.DESCRICAO AS UND
      ,UNIDADE.DESCRICAO AS UND_COMPRA
      ,CATEGORIA.DESCRICAO AS GRUPO
      ,PRODUTO.MARCA AS FAMILIA
      --,PRODUTO.MARCA AS CARACTERISTICAS
      ,PRODUTO.CUSTO AS PRECO_CUSTO
      ,PRODUTO.BASE AS PRECO_VENDA
      ,PRODUTO.OBSERVACAO AS OBSERVACOES
      ,PRODUTO.PESOLIQ AS PESO
      ,SUBCATEGORIA.DESCRICAO AS FAMILIA
      ,PRODUTO.CLASSIFICACAO AS COD_NCM
      ,SUBSTRING (PRODUTO.CST,1,1) AS OST
      ,SUBSTRING (PRODUTO.CST,2,4) AS ST
      ,FORNECEDOR.NOME AS FORNECEDOR
      ,PRODUTO.CEST AS PERSONAL6
  FROM BANCO.dbo.PRODUTO
LEFT JOIN BANCO.dbo.UNIDADE ON UNIDADE.CDUND = PRODUTO.UNVENDA
LEFT JOIN BANCO.dbo.FORNECEDOR ON FORNECEDOR.CDFOR = PRODUTO.CODFORN
LEFT JOIN BANCO.dbo.BARRA ON BARRA.CDPRODUTO = PRODUTO.CDPRODUTO
LEFT JOIN BANCO.dbo.CATEGORIA ON CATEGORIA.CDCAT = PRODUTO.CDCAT
LEFT JOIN BANCO.dbo.SUBCATEGORIA ON SUBCATEGORIA.CDSCAT = PRODUTO.CDSUBCAT
LEFT JOIN BANCO.dbo.BALANCO ON BALANCO.CDPRODUTO = PRODUTO.CDPRODUTO
WHERE BALANCO.LOJA = '001'
GROUP BY
       PRODUTO.CDPRODUTO
      ,PRODUTO.DESCRICAO
      --,BARRA.BARRA
      ,UNIDADE.DESCRICAO
      ,UNIDADE.DESCRICAO
      ,CATEGORIA.DESCRICAO
      ,PRODUTO.MARCA
      ,PRODUTO.CUSTO
      ,PRODUTO.BASE
      ,PRODUTO.OBSERVACAO
      ,PRODUTO.PESOLIQ
      ,SUBCATEGORIA.DESCRICAO
      ,PRODUTO.CLASSIFICACAO
      ,PRODUTO.CST
      ,FORNECEDOR.NOME
      ,PRODUTO.CEST
ORDER BY PRODUTO.CDPRODUTO ASC
