select PESSOA.PES_CD,
PESSOA.ERE_COMPLEMENTO AS COMPLEMENTO,
PESSOA.ERE_BAIRRO AS BAIRRO,
PESSOA.ERE_CELULAR AS CELULAR,
PESSOA.ERE_CEP AS CEP,
MUNICIPIO.MUN_NM AS CIDADE,
MUNICIPIO.MUN_SIGLA_UF AS UF,
PESSOA.ERE_EMAIL AS EMAIL,
PESSOA.ERE_ENDERECO AS ENDERECO,
PESSOA.ERE_FAX AS FAX,
PESSOA.ERE_FONE AS TELEFONE,
PESSOA.ERE_NUMERO AS NUMERO,
PESSOA.PES_CONTATO AS CONTATO,
PESSOA.PES_CPF_CNPJ AS CNPJ_CNPF,
PESSOA.PES_DT_CADASTRO AS CADASTR,
PESSOA.PES_FANTASIA AS FANTASIA,
PESSOA.PES_NM AS NOME,
PESSOA.PES_OBS AS OBSERVACOES,
PESSOA.PES_RG_IE AS IE_RG
FROM PESSOA
LEFT JOIN MUNICIPIO ON PESSOA.ERE_COD_MUNICIPIO=MUNICIPIO.MUN_CD

