SELECT PRODUTO_SERVICO.PRS_CD AS COD_FABRICANTE,
GRUPOS_ESTOQUE.GES_NM_REFERENCIA AS GRUPO,
CLASSIFICACAO_FISCAL.CLF_COD AS COD_NCM,
PRODUTO_SERVICO.PRS_COD_BARRAS AS BARRAS,
PRODUTO_SERVICO.PRS_DATA_CADASTRO AS DATA_CADASTRO,
PRODUTO_SERVICO.PRS_NM AS DESCRICAO,
PRODUTO_SERVICO.PRS_UNIDADE AS UND,
CEST_NCM.ID_CEST AS PERSONAL6,
ESTOQUE.EST_PRECO_CUSTO AS PRECO_CUSTO,
ESTOQUE.EST_PRECO_MEDIO AS CUSTO_MEDIO,
ESTOQUE.EST_PRECO_VENDA AS PRECO_VENDA,
ESTOQUE.EST_QTDE_ATUAL AS QTD
FROM PRODUTO_SERVICO
LEFT JOIN GRUPOS_ESTOQUE ON PRODUTO_SERVICO.PRS_CD_GRUPO=GRUPOS_ESTOQUE.GES_CD_GRUPO
LEFT JOIN CLASSIFICACAO_FISCAL ON PRODUTO_SERVICO.PRS_CF=CLASSIFICACAO_FISCAL.CLF_IDX
LEFT JOIN CEST_NCM ON PRODUTO_SERVICO.ID_CEST_NCM=CEST_NCM.ID
LEFT JOIN ESTOQUE ON PRODUTO_SERVICO.PRS_CD=ESTOQUE.EST_CD_PRODUTO
