SELECT
  CONCAT (CONTAS_PAGAR.NUMERO_NOTA, '-' ,CONTAS_PAGAR.SERIE_NOTA) AS HISTORICO,
  CONTAS_PAGAR.DOCUMENTO AS DOCUMENTO,
  CONTAS_PAGAR.DATA_EMISSAO AS EMISSAO,
  CONTAS_PAGAR.VENCIMENTO AS VENCIMENTO,
  CONTAS_PAGAR.VALOR AS VALOR_DUP,
  CONTAS_PAGAR.OBS AS OBSERVACOES,
  FORNECEDOR.ID_FORNECEDOR AS COD_FORNECEDOR,
  FORNECEDOR.RAZAO_SOCIAL AS NOM_FORNECEDOR,
  FORNECEDOR.CNPJ AS CNPJ
FROM CONTAS_PAGAR
LEFT JOIN FORNECEDOR ON FORNECEDOR.ID_FORNECEDOR = CONTAS_PAGAR.ID_FORNECEDOR