SELECT
  CONTAS_RECEBER.ID_CONTAS_RECEBER AS DOCUMENTO,
  CONCAT (CONTAS_RECEBER.DOCUMENTO, '-' ,CONTAS_RECEBER.NUMERO_NOTA) AS HISTORICO,
  substring(CONTAS_RECEBER.DOCUMENTO from 8 for 35) AS NUM_PARCELA,
  CLIENTE.CODIGO AS COD_CLIENTE,
  CLIENTE.RAZAO_SOCIAL AS NOM_CLIENTE,
  CONTAS_RECEBER.DATA_EMISSAO AS EMISSAO,
  CONTAS_RECEBER.VENCIMENTO AS VENCIMENTO,
  CONTAS_RECEBER.VALOR AS VALOR_DUP,
  TIPO_PAGAMENTO.DESCRICAO AS TIPO_DOC,
  CONTAS_RECEBER.NOSSO_NUMERO AS NOSSO_NUM,
  BANCO.`ID_BANCO` AS CONTA_BANCARIA_ID,
  CONTAS_RECEBER.OBS AS OBSERVACOES,
  CONTA_CORRENTE.AGENCIA AS AGENCIA,
  CONTA_CORRENTE.BANCO AS BANCO,
  CONTA_CORRENTE.CONTA_CORRENTE AS CONTA,
  CONTAS_RECEBER.DATA_PAGTO AS RECEBIMENTO,
  CONTAS_RECEBER.VL_PAGTO AS VALOR_REC,
  CONTAS_RECEBER.VL_JUROS AS VALOR_JUR,
  CONTAS_RECEBER.VL_DESCONTOS AS VALOR_DES,
  CENTRO_CUSTO.`DESCRICAO` AS CTO_CUSTO,
  case when CLIENTE.CNPJ = '' or CLIENTE.CNPJ is null then CLIENTE.CPF else CLIENTE.CNPJ END as CNPJ
FROM CONTAS_RECEBER
LEFT JOIN CLIENTE ON CLIENTE.ID_CLIENTE = CONTAS_RECEBER.ID_CLIENTE
LEFT JOIN TIPO_PAGAMENTO ON TIPO_PAGAMENTO.ID_TIPO_PGTO = CONTAS_RECEBER.ID_TIPO_PAGTO
LEFT JOIN BANCO ON BANCO.`ID_BANCO` = contas_receber.ID_BANCO
LEFT JOIN CONTA_CORRENTE ON CONTA_CORRENTE.ID_CONTA_CORRENTE = CONTAS_RECEBER.`ID_CONTA_CORRENTE`
LEFT JOIN `centro_custo` ON `centro_custo`.`ID_CENTRO_CUSTO` = CONTAS_RECEBER.`ID_CENTRO_CUSTO`
