SELECT
    CODIGO AS CODIGO,
    DESCRICAO AS NOME,
    CONTATO AS CONTATO,
    RG AS CNPJ_CNPF,
    CPF AS IE_RG,
    IM AS IM,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    CEP AS CEP,
    COMERCIAL AS TELEFONE,
    CELULAR AS CELULAR,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBS AS OBSERVACOES
FROM PACIENTES
WHERE FORNECEDOR = 'S'
