SELECT
    PRODUTO.CD_PROD AS CODIGO,
    PRODUTO.DS_PROD AS DESCRICAO,
    replace(PRODUTO.CD_REF,'.','') AS BARRAS,
    GRUPO.ds_grupo AS GRUPO,
    PRODUTO.AB_UNIDADE AS UND,
    PRODUTO.QT_MIN AS QTD_IDEAL,
    ESTOQUE.QT_PROD AS QTD,
    SUB_TAB_PRECO.VL_CUSTO AS PRECO_CUSTO,
    SUB_TAB_PRECO.VL_VENDA AS PRECO_VENDA,
    PRODUTO.CD_ORIGEM_CST AS OST,
    GRUPO_TRIBUTACAO.CD_CST_CF AS ST,
    PRODUTO.DT_ALT AS ALTERACAO_PRECO,
    PRODUTO.DT_CAD AS DATA_CADASTRO,
    replace(PRODUTO.CD_NCM_SH,'.','') AS COD_NCM,
    PRODUTO.CD_INTERNO AS COD_FABRICANTE,
    replace(PRODUTO.CD_CEST_PRODUTO,'.','') AS PERSONAL6
FROM PRODUTO
LEFT JOIN ESTOQUE ON ESTOQUE.CD_REF = PRODUTO.CD_REF
LEFT JOIN SUB_TAB_PRECO ON SUB_TAB_PRECO.CD_REF = PRODUTO.CD_REF 
LEFT JOIN GRUPO_TRIBUTACAO ON GRUPO_TRIBUTACAO.CD_GRUPO_TRIBUTACAO = PRODUTO.CD_GRUPO_TRIBUTACAO  
LEFT JOIN GRUPO ON GRUPO.cd_grupo = PRODUTO.cd_grupo