SELECT 
  ID AS BARRAS
, DESCRICAO
, UNIDADE AS UND
, PRECO AS PRECO_CUSTO
, LUCRO AS MARGEM_LUCRO
, PRECO_VENDA
, PRECO_ATACADO
, QTDE_ATACADO AS QTD_PRECO_ATACADO
-- , ICMS, NCM, CTS
, ESTOQUE AS QTD
, ESTOQUEMINIMO AS QTD_IDEAL
, GRUPO
, SUBGRUPO AS PERSONAL1
, MARCA AS CARACTERISTICAS
, CATEGORIA AS FAMILIA
, TEMANHO AS TAMANHO
, COMISSAO
, OBS AS OBSERVACOES
, FORNECEDOR
, CASE STATUS WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
FROM CADPRODUTO
