SELECT
    SUBSTRING(CADPRO.CODPRO FROM 2 FOR 7) AS ST,
    CADPRO.BARPRO AS BARRAS,
    CADPRO.NOMPRO AS DESCRICAO,
    CADCAT.nomcat AS GRUPO,
    CADSUB.nomsub AS FAMILIA,
    CAST (CADPRO.INCPRO AS DATE) AS DATA_CADASTRO,
    CADPRO.LUCPRO AS MARGEM_LUCRO,
    CADPRO.AQUPRO AS PRECO_CUSTO,
    CADPRO.ESTPRO AS QTD,
    CADPRO.PRCPRO AS PRECO_VENDA,
    CAST (CADPRO.ALTPRO AS DATE) AS ALTERACAO_PRECO,
    CADPRO.CLAIPI AS COD_NCM,
    CADPRO.REFPRO AS COD_FABRICANTE,
    CADPRO.OBSPRO AS OBSERVACOES,  
    CADPRO.CESTPRO AS PERSONAL6
FROM CADPRO
LEFT JOIN CADCAT ON CADCAT.codcat = CADPRO.catpro
LEFT JOIN CADSUB ON CADSUB.codsub = CADPRO.subpro