SELECT
    CAD_CLIENTES.ID AS CODIGO,
    CAD_CLIENTES.NOME_RAZAO AS NOME,
    CAD_CLIENTES.CNPJ_CPF AS CNPJ_CNPF,
    CAD_CLIENTES.IE_RG AS IE_RG,
    CAD_CLIENTES.ENDERECO AS ENDERECO,
    CAD_CLIENTES.NUMERO AS NUMERO,
    CAD_CLIENTES.COMPLEMENTO AS COMPLEMENTO,
    CAD_CLIENTES.BAIRRO AS BAIRRO,
    CAD_CIDADES.DESCRICAO AS CIDADE,
    CAD_CIDADES.UF_IBGE AS UF,
    CAD_CLIENTES.CEP AS CEP,
    CAD_CLIENTES.TELEFONE01 AS TELEFONE,
    CAD_CLIENTES.TELEFONE02 AS CELULAR,
    CAD_CLIENTES.EMAILS AS EMAIL,
    CAD_CLIENTES.OBSERVACAO AS OBSERVACOES,
    CAD_CLIENTES.ESTADO_CIVIL AS EST_CIVIL,
    CAD_CLIENTES.CONJUGE AS CONJUGE,
    CAD_CLIENTES.NOME_MAE AS MAE,
    CAD_CLIENTES.NOME_PAI AS PAI,
    CAD_CLIENTES.NASCIMENTO AS NASCIMENTO
    --CAD_CLIENTES.DATA_INCLUSAO AS CADASTRO
FROM CAD_CLIENTES
LEFT JOIN CAD_CIDADES ON CAD_CIDADES.ID = CAD_CLIENTES.ID_CIDADE
