SELECT
    CAD_FORNECEDORES.ID AS CODIGO,
    CAD_FORNECEDORES.RAZAO_SOCIAL AS NOME,
    CAD_FORNECEDORES.FANTASIA AS FANTASIA,
    CAD_FORNECEDORES.CPF_CNPJ AS CNPJ_CNPF,
    case when CAD_FORNECEDORES.RG_IE = '' or CAD_FORNECEDORES.RG_IE is null then CAD_FORNECEDORES.IEST else CAD_FORNECEDORES.RG_IE END AS IE_RG,
    CAD_FORNECEDORES.LOGRADOURO AS ENDERECO,
    CAD_FORNECEDORES.NUMERO AS NUMERO,
    CAD_FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    CAD_FORNECEDORES.BAIRRO AS BAIRRO,
    CAD_CIDADES.DESCRICAO AS CIDADE,
    CAD_CIDADES.UF_IBGE AS UF,
    CAD_FORNECEDORES.CEP AS CEP,
    CAD_FORNECEDORES.CONTATO AS CONTATO,
    CAD_FORNECEDORES.TELEFONE01 AS TELEFONE,
    CAD_FORNECEDORES.TELEFONE02 AS CELULAR,
    CAD_FORNECEDORES.EMAIL AS EMAIL,
    CAD_FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM CAD_FORNECEDORES
LEFT JOIN CAD_CIDADES ON CAD_CIDADES.ID = CAD_FORNECEDORES.ID_CIDADE
