SELECT
    CAD_PRODUTOS.ID AS CODIGO,
    CAD_PRODUTOS.COD_BARRAS AS BARRAS,
    CAD_PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    CAD_PRODUTOS.DESCRICAO_SAIDA AS DESCRICAO,
    CAD_UNIDADES.SIGLA AS UND,
    CAD_PRODUTOS.PESO_LIQUIDO AS PESO,
    CAD_PRODUTOS.ESTOQUE_ATUAL AS QTD,
    CAD_PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    CAD_PRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
    CAD_PRODUTOS.PRECO_VISTA AS PRECO_VENDA,
    CAD_PRODUTOS.PRECO_PROMOCAO AS PRECO_ATACADO,
    SUBSTRING (CAD_PRODUTOS.ICMS_CST_CSOSN_SAIDA FROM 1 FOR 3) AS ST,
    CAD_PRODUTOS.OBSERVACAO AS OBSERVACOES, 
    CAD_PRODUTOS.ULTIMA_ENTRADA AS ULTIMA_COMPRA,
    CAD_PRODUTOS.ULTIMA_SAIDA AS ULTIMA_VENDA,
    CAD_PRODUTOS.NCM AS COD_NCM,
    CAD_PRODUTOS.CEST AS PERSOMAL6,
    CAD_PRODUTOS.DATA_INCLUSAO AS DATA_CADASTRO
FROM CAD_PRODUTOS
LEFT JOIN CAD_UNIDADES ON CAD_UNIDADES.ID = CAD_PRODUTOS.ID_UNIDADE
