SELECT
    FORNECEDOR_ID AS CODIGO,
    FORNECEDOR AS NOME,
    FORN_INSCRESTADUAL AS IE_RG,
    FORN_CNPJ AS CNPJ_CNPF,
    FORN_ENDERECO AS ENDERECO,
    FORN_ENDER_NUM AS NUMERO,
    FORN_BAIRRO AS BAIRRO,
    FORN_CIDADE AS CIDADE,
    FORN_CEP AS CEP,
    FORN_UF AS UF,
    FORN_TELEFONE AS TELEFONE,
    FORN_CELULAR AS CELULAR,
    FORN_FAX AS FAX,
    FORN_EMAIL AS EMAIL,
    FORN_CONTATO AS CONTATO
FROM FORNECEDORES
