SELECT
    PRODUTOS.PRODUTO_ID AS CODIGO,
    FORNECEDORES.FORNECEDOR AS FORNECEDOR,
    CATEGORIA.CATEGORIA AS GRUPO,
    TRIBUTACOES.COD_TRIBUTACAO AS ST,
    PRODUTOS.REGISTRO_MS AS ANVISA_CODIGO_DE_PRODUTO,
    PRODUTOS.PRODUTO AS DESCRICAO,
    PRODUTOS.COD_BARRAS AS BARRAS,
    PRODUTOS.PROD_PRCOMPRA AS PRECO_CUSTO,
    PRODUTOS.PROD_PRVENDA AS PRECO_VENDA,
    PRODUTOS.PROD_PRPROMOCAO AS PRECO_ATACADO,
    PRODUTOS.PROD_SALDO AS QTD,
    PRODUTOS.PROD_ESTMINIMO AS QTD_IDEAL,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PROD_UNIDADE AS UND,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON FORNECEDORES.FORNECEDOR_ID = PRODUTOS.FORNECEDOR_ID
LEFT JOIN CATEGORIA ON CATEGORIA.CATEGORIA_ID = PRODUTOS.CATEGORIA_ID
LEFT JOIN TRIBUTACOES ON TRIBUTACOES.TRIBUTACAO_ID = PRODUTOS.TRIBUTACAO_ID
