SELECT    
    CODIGO,
    NOME,
    ENDERECORESIDENCIAL as endereco,
    BAIRRORESIDENCIAL AS BAIRRO,
    CIDADERESIDENCIAL AS CIDADE,
    ESTADORESIDENCIAL AS UF,
    CEPRESIDENCIAL AS CEP,
    TELEFONERESIDENCIAL AS TELEFONE,
    CELULAR AS CELULAR,
    CIC AS CNPJ_CNPF,
    RG AS IE_RG,
    EMAIL,
    NUMERO,
    COMPLEMENTO
FROM CLIENTES
where codigo > 0
