SELECT   
    PRODUTOS.CODIGO AS BARRAS,
    PRODUTOS.PRODUTO AS DESCRICAO,
    PRODUTOS.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTOS.LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRECOVENDA AS PRECO_VENDA,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.TRIBUTACAO AS ST,
    SECAO.secao AS GRUPO,
    SUBSECAO.nome AS FAMILIA,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.ESTOQUEATUAL AS QTD,
    PRODUTOS.CEST AS PERSONAL6

FROM PRODUTOS
LEFT JOIN SECAO ON PRODUTOS.secao = SECAO.codigo
LEFT JOIN SUBSECAO ON PRODUTOS.subsecao = SUBSECAO.codigo