SELECT 
       PRODUTOS.CODIGO AS CODIGO
      ,PRODUTOS.NOME AS DESCRICAO
      ,GRUPOS.NOME AS GRUPO
      ,SUB_GRUPOS.NOME AS FAMILIA
      ,PRODLOJAS.EST_ATUAL AS QTD
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.CBARRA AS BARRAS
      ,PRODUTOS.PESO_LIQ AS PESO
      ,PRODLOJAS.PCO_REMAR AS PRECO_VENDA
      ,PRODUTOS.COD_CSTORIGEM AS OST
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.UNIDADE_COMPRA AS UND_COMPRA
      ,PRODUTOS.CODIGO_NCM AS COD_NCM
      ,CAST (PRODUTOS.DATA_ALTERACAO AS DATE) AS ALTERACAO_PRECO
      ,PRODUTOS.COD_CEST AS PERSONAL6
  FROM NSYS.dbo.PRODUTOS
  LEFT JOIN NSYS.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = PRODUTOS.CODIGO
  LEFT JOIN NSYS.dbo.GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO
  LEFT JOIN NSYS.dbo.SUB_GRUPOS ON SUB_GRUPOS.CODIGO = PRODUTOS.SUBG
