SELECT
	CODFOR AS CODIGO,
	NOMFOR AS NOME,
	NOMFAN AS FANTASIA,
	ENDERECO,
	BAIRRO,
	CIDADE,
	CEP,
	ESTADO AS UF,
	CGCMF AS CNPJ_CNPF,
	INSCEST AS IE_RG,
	TELEFONE1 AS TELEFONE,
	TELEFONE2 AS CELULAR,
	TELEFONE3 AS PERSONAL1,
	TELEFONE4 AS PERSONAL2,
	FAX1 AS FAX,
	FAX2 AS PERSONAL3,
	VENDEDOR AS CONTATO,
	OBSERV AS OBSERVACOES,
	EMAIL
FROM
	FORNECEDORES
WHERE CODFOR > 0
