SELECT
	P.PRODUTOCODIGO AS CODIGO,
	P.PRODUTONOME AS DESCRICAO,
	P.PRODUTOUNIDADE AS UND,
	G.GRUPONOME AS GRUPO,
	P.PRODUTOCUSTO AS PRECO_CUSTO,
	P.PRODUTOVENDA AS PRECO_VENDA,
	F.FORNECEDORNOME AS FORNECEDOR,
	P.PRODUTOESTOQUE AS QTD,
	P.CSTCODIGO AS ST,
	P.PRODUTOCONFIS AS COFINS_CODIGO,
	P.PRODUTONCM AS COD_NCM,
	P.PRODUTOBARRA AS BARRAS,
	S.SUBGRUPONOME AS FAMILIA,
	P.PRODUTOREFERENCIA AS CARACTERISTICAS,
	P.PRODUTOATACADO AS PRECO_ATACADO,
	P.PRODUTOOBSERVACAO AS OBSERVACOES
FROM PRODUTO P
LEFT JOIN GRUPO G ON P.GRUPOCODIGO=G.GRUPOCODIGO
LEFT JOIN FORNECEDOR F ON P.FORNECEDORCODIGO=F.FORNECEDORCODIGO 
LEFT JOIN SUBGRUPO S ON P.SUBGRUPOCODIGO=S.SUBGRUPOCODIGO
