SELECT
    PRODUTOS_CODIGO AS BARRAS,
    PRODUTOS_NOME AS DESCRICAO,
    PRODUTOS_UNIDADE AS UND,
    PRODUTOS_ALTERADO AS ALTERACAO_PRECO,
    PRODUTOS_QUANTIDADE AS QTD,
    PRODUTOS_ESTOQUEMINIMO AS QTD_IDEAL,
    PRODUTOS_PRECOCUSTO AS PRECO_CUSTO,
    PRODUTOS_PRECOVENDA AS PRECO_VENDA,
    PRODUTOS_LUCRO AS MARGEM_LUCRO,
    PRODUTOS_OBSERVACOES AS OBSERVACOES,
    case when PRODUTOS_INATIVO = '1' then 'Inativo' else 'Ativo' end as SITUACAO,
    CAST (PRODUTOS_ICMSST AS INTEGER) AS ST,
    PRODUTOS_ICMSNCM AS COD_NCM,
    PRODUTOS_PESOLIQUIDO AS PESO,
    PRODUTOS_CEST AS PERSONAL6
FROM PRODUTOS