SELECT
    PRODUTO.COD_PRO AS CODIGO,
    PRODUTO.NOME_PRO AS DESCRICAO,
    PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
    UNIDADE_MEDIDA.DESCRICAO AS UND,
    ESTOQUE.ESTOQUE AS QTD,
    SECAO_GRUPO.DESCRICAO AS GRUPO,
    SECAO_GRUPO_SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM_LUCRO_PRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_PRO AS PRECO_VENDA,
    SUBSTRING (GRUPO_ICMS.CST FROM 1 FOR 1)  AS OST,
    SUBSTRING (GRUPO_ICMS.CST FROM 2 FOR 3) AS ST, 
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.COD_NCM AS COD_NCM,
    MAX (CEST.CEST) AS PERSONAL6,
    case when PRODUTO.ATIVO_PRO = 'S' then 'Ativo' else 'Inativo' end as SITUACAO
FROM PRODUTO
LEFT JOIN SECAO_GRUPO ON SECAO_GRUPO.COD_GRUPO = PRODUTO.COD_GRUPO AND SECAO_GRUPO.cod_sec = PRODUTO.cod_sec
LEFT JOIN SECAO_GRUPO_SUBGRUPO ON SECAO_GRUPO_SUBGRUPO.COD_SUBGRUPO = PRODUTO.SUB_GRUPO AND SECAO_GRUPO_SUBGRUPO.cod_grupo = SECAO_GRUPO.COD_GRUPO
AND SECAO_GRUPO_SUBGRUPO.cod_sec = SECAO_GRUPO.cod_sec
LEFT JOIN GRUPO_ICMS ON GRUPO_ICMS.COD_GRP = PRODUTO.ICMS_CF_EST
LEFT JOIN ESTOQUE ON ESTOQUE.COD_PRO = PRODUTO.COD_PRO
LEFT JOIN UNIDADE_MEDIDA ON UNIDADE_MEDIDA.CODIGO = PRODUTO.CODIGO_UNIDADE_SAIDA
LEFT JOIN CEST ON CEST.NCM = PRODUTO.COD_NCM 
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,16