SELECT
    PRODUTOS.CODPRODUTO AS CODIGO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.DESCRICAO,
    PRODUTOS.FORNECEDOR,
    UNIDADESDEMEDIDA.ABREVIATURA AS UND,
    MARCAS.DESCRICAO AS CARACTERISTICAS,
    PRODUTOS_GRUPOS.DESCRICAO AS GRUPO,
    PRODUTOS_SUBGRUPOS.DESCRICAO AS FAMILIA,
    PRODUTOS.CODBARRAS AS BARRAS,
    PRODUTOS.ESTOQUEATUAL AS QTD,
    PRODUTOS.PRECOCOMPRA AS PRECO_CUSTO,
    PRODUTOS.PRECOVENDA AS PRECO_VENDA,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN UNIDADESDEMEDIDA ON PRODUTOS.CODUNIDADE = UNIDADESDEMEDIDA.CODUNIDADE
LEFT JOIN MARCAS ON PRODUTOS.CODMARCA = MARCAS.CODMARCA
LEFT JOIN PRODUTOS_GRUPOS ON PRODUTOS.CODGRUPO = PRODUTOS_GRUPOS.CODGRUPO
LEFT JOIN PRODUTOS_SUBGRUPOS ON PRODUTOS.CODSUBGRUPO = PRODUTOS_SUBGRUPOS.CODSUBGRUPO
