SELECT TAB_CLIENTE.COD_CLIENTE AS CODIGO,
TAB_CLIENTE.DES_CLIENTE AS NOME,
TAB_CLIENTE.NUM_CGC AS CNPJ_CNPF,
TAB_CLIENTE.NUM_INSC_EST AS IE_RG,
TAB_CLIENTE.DES_ENDERECO AS ENDERECO,
TAB_CLIENTE.DES_BAIRRO AS BAIRRO,
TAB_CLIENTE.NUM_CEP AS CEP,
TAB_CIDADE.DES_CIDADE AS CIDADE,
TAB_CLIENTE.DES_SIGLA AS UF,
TAB_CLIENTE.NUM_FONE AS TELEFONE,
TAB_CLIENTE.NUM_FAX AS FAX,
TAB_CLIENTE.DES_CONTATO AS CONTATO,
TAB_CLIENTE.DES_EMAIL AS EMAIL,
TAB_CLIENTE.NUM_ENDERECO AS NUMERO,
TAB_CLIENTE.DES_COMPLEMENTO AS COMPLEMENTO
FROM TAB_CLIENTE
LEFT JOIN TAB_CIDADE ON TAB_CLIENTE.COD_CIDADE=TAB_CIDADE.COD_CIDADE



