SELECT
       PESSOAS.OBSERVACAO AS OBSERVACOES
      ,PESSOAS.CODIGO AS CODIGO
      ,PESSOAS.NOME AS NOME
      ,PESSOAS.FANTASIA AS FANTASIA
      ,PESSOAS.CONTATO AS CONTATO
      ,PESSOAS_COMPLEMENTO.ENDERECO AS ENDERECO
      ,PESSOAS_COMPLEMENTO.NUMERO AS NUMERO
      ,PESSOAS_COMPLEMENTO.COMPLEMENTO AS COMPLEMENTO
      ,PESSOAS_COMPLEMENTO.BAIRRO AS BAIRRO
      ,PESSOAS_COMPLEMENTO.CEP AS CEP
      ,CIDADES.NOME AS CIDADE
      ,UF.SIGLA AS UF
      ,PESSOAS_FONE.NUMERO_SEM_MASCARA AS TELEFONE
      ,PESSOAS.CGC_CPF AS CNPJ_CNPF
      ,case when PESSOAS.INSC = '' or PESSOAS.INSC is null then PESSOAS.RG else PESSOAS.INSC END as IE_RG
      ,PESSOAS.EMAIL_1 AS EMAIL
      ,PESSOAS.INSCRICAO_MUNICIPAL AS IM
  FROM trade.dbo.PESSOAS
  LEFT JOIN trade.dbo.PESSOAS_COMPLEMENTO ON PESSOAS_COMPLEMENTO.PES_HANDLE = PESSOAS.HANDLE
  LEFT JOIN trade.dbo.PESSOAS_FONE ON PESSOAS_FONE.PES_HANDLE = PESSOAS.HANDLE
  LEFT JOIN trade.dbo.CIDADES ON CIDADES.HANDLE = PESSOAS_COMPLEMENTO.CID_HANDLE
  LEFT JOIN trade.dbo.UF ON UF.Handle = CIDADES.UF_HANDLE
  WHERE trade.dbo.PESSOAS.INDFOR = '1'
