SELECT CODIGO AS CODIGO
      ,NOME AS NOME
      ,ENDERECO AS ENDERECO
      ,CPF AS CNPJ_CNPF
      ,RG AS IE_RG
      ,TELEFONE
      ,CELULAR
      ,FIDELIDADE AS PERSONAL1
      ,EMAIL
      ,CONTATO
      ,RAZAOSOCIAL AS FANTASIA
  FROM SYSMARKET.dbo.CLIENTE
