SELECT
    PARTICIPANTE.codigo AS CODIGO,
    PARTICIPANTE.nome AS NOME,
    PARTICIPANTE.endereco AS ENDERECO,
    PARTICIPANTE.numero AS NUMERO,
    PARTICIPANTE.complemento AS COMPLEMENTO,
    PARTICIPANTE.bairro AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.SIGLA_ESTADO AS UF,
    PARTICIPANTE.email AS EMAIL,
    PARTICIPANTE.data_cadastro AS CADASTRO,
    PARTICIPANTE.data_nascimento AS NASCIMENTO,
    PARTICIPANTE.nome_pai AS PAI,
    PARTICIPANTE.nome_mae AS MAE,
    PARTICIPANTE.cpf_cnpj AS CNPJ_CNPF,
    PARTICIPANTE.insc_estadual||rg AS IE_RG,
    PARTICIPANTE.cep AS CEP,
    TELEFONE_PARTICIPANTE.NUMERO AS TELEFONE
FROM PARTICIPANTE
LEFT JOIN CIDADE ON PARTICIPANTE.CODIGO_CIDADE = CIDADE.CODIGO
LEFT JOIN TELEFONE_PARTICIPANTE ON PARTICIPANTE.CODIGO = TELEFONE_PARTICIPANTE.CODIGO_PARTICIPANTE
WHERE PARTICIPANTE.CODIGO > 0
