SELECT
       PRODUTO.CODIGO AS CODIGO
      ,PRODUTO.DESCRICAO AS DESCRICAO
      ,PRODANT.COD_BARRAS AS BARRAS
      ,PRODUTO.UNIDADEDEMEDIDA AS UND
      ,PRODANT.QUANTIDADE AS QTD
      ,GRUPO.DESCRICAO AS GRUPO
      ,FORNECEDOR.NOME AS FORNECEDOR
      ,PRODUTO.PRECOCUSTO AS PRECO_CUSTO
      ,PRODUTO.VLVAREJO AS PRECO_VENDA
      ,PRODUTO.OBS AS OBSERVACOES
      ,PRODUTO.CDFISC AS COD_NCM
      ,PRODUTO.REFER_FABRICA AS COD_FABRICANTE
      ,CAST (PRODUTO.DTALTERA AS DATE) AS ALTERACAO_PRECO
      ,CAST (PRODUTO.DTULTINV AS DATE) AS ULTIMA_VENDA
      ,CAST (PRODUTO.DTCAD AS DATE) AS DATA_CADASTRO
  FROM Loja.dbo.PRODUTO
LEFT JOIN Loja.dbo.GRUPO ON GRUPO.GRUPO = PRODUTO.GRUPO
LEFT JOIN Loja.dbo.FORNECEDOR ON FORNECEDOR.CODIGO = PRODUTO.FORNECEDOR
LEFT JOIN Loja.dbo.PRODANT ON PRODANT.COD_PRODUTO = PRODUTO.CODIGO 
WHERE PRODANT.TABELA_PRECOS = '1'