SELECT
    PRODUTOS.CODIGO AS CODIGO,
    GRUPO.NOME_GRUPO AS GRUPO,
    PRODUTOS.CODBARRAS AS BARRAS,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.MODELO AS CARACTERISTICAS,
    PRODUTOS.ESTMIN AS QTD_IDEAL,
    PRODUTOS.SALDO AS QTD,
    PRODUTOS.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    PRODUTOS.PRECOVENDA AS PRECO_VENDA,
    PRODUTOS.ORIGEM AS OST,
    PRODUTOS.CST AS ST,
    PRODUTOS.DATAALTERACAO AS ALTERACAO_PRECO,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.OBS AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPO ON GRUPO.ID_GRUPO = PRODUTOS.CODGRUPO