SELECT
    TFOR.CODFOR AS CODIGO,
    TFOR.RAZAOSOCIAL AS NOME,
    TFOR.NOMEFANTASIA AS FANTASIA,
    TFOR.ENDERECO AS ENDERECO,
    TFOR.COMPL AS COMPLEMENTO,
    TFOR.CEP AS CEP,
    TFOR.BAIRRO AS BAIRRO,
    TFOR.ESTADO AS UF,
    TFOR.CIDADE AS CIDADE,
    TFOR.FONE AS TELEFONE,
    TFOR.FAX AS FAX,
    TFOR.CELULAR AS CELULAR,
    TFOR.EMAIL AS EMAIL,
    TFOR.IDINSC AS IE_RG,
    TFOR.CGC AS CNPJ_CNPF,
    TFOR.OBS AS OBSERVACOES
FROM TFOR
WHERE TFOR.CODFOR <> '0'
