select `clientes`.`COD_CLIENTE` as codigo,
clientes.`NOME`,
clientes.`APELIDO` as fantasia,
clientes.`ENDERECO`,
`clientes`.`NUMERO`,
`clientes`.`CEP`,
`clientes`.`BAIRRO`, 
`clientes`.`MUNICIPIO` as cidade,
clientes.`UF`,
clientes.`FONES` as telefone,
clientes.`ENDERECO_REFERENCIA` as complemento,
clientes.`CELULAR`,
clientes.`FAX`,
clientes.`CONJUGE`,
clientes.`CONTATO`,
clientes.`EMAIL`,
clientes.`OBS` as observacoes,
clientes.`DATA_CAD` as cadastro,
`clientes`.rg as IE_RG,
clientes.`CPF` as CNPJ_CNPF,
CAST(clientes.`DATA_NASC` as DATE) nascimento,
clientes.`NOME_MAE` as mae,
clientes.`NOME_PAI` as pai
from clientes