SELECT PARCEIROS.PARCEIROS_CONTROLE AS CODIGO,
PARCEIROS.PARCEIROS_DESDE AS CADASTRO,
PARCEIROS.PARCEIROS_CNPJ_CPF AS CNPJ_CNPF,
PARCEIROS.PARCEIROS_IESTADUAL AS IE_RG,
PARCEIROS.PARCEIROS_NOME AS NOME,
PARCEIROS.PARCEIROS_FANTASIA AS FANTASIA,
PARCEIROS.PARCEIROS_EMAIL AS EMAIL,
PARCEIROS.PARCEIROS_TELEFONE1 AS TELEFONE,
PARCEIROS.PARCEIROS_TELEFONE2 AS CELULAR,
PARCEIROS.PARCEIROS_CEP AS CEP,
PARCEIROS.PARCEIROS_ENDERECO AS ENDERECO,
PARCEIROS.PARCEIROS_ENDERECO_NUMERO AS NUMERO,
PARCEIROS.PARCEIROS_ENDERECO_COMPLEMENTO AS COMPLEMENTO,
PARCEIROS.BAIRROS_NOME AS BAIRRO,
PARCEIROS.CIDADES_NOME AS CIDADE,
PARCEIROS.ESTADOS_SIGLA AS UF,
PARCEIROS.PARCEIROS_OBSERVACAO_GERAL AS OBSERVACOES
FROM PARCEIROS
WHERE PARCEIROS.PARCEIROS_CONTROLE>0 AND PARCEIROS.PARCEIROS_FORNECEDOR='S'


