SELECT 
       CLIENTE.CODIGO AS CODIGO
      ,CLIENTE.NOME AS NOME
      ,CLIENTE.FANTASIA AS FANTASIA
      ,CLIENTE.ENDERECO AS ENDERECO
      ,CLIENTE.NUMERO AS NUMERO
      ,CLIENTE.COMPLEM AS COMPLEMENTO
      ,CLIENTE.BAIRRO AS BAIRRO
      ,CIDADES.NOME AS CIDADE
      ,CIDADES.UF AS UF
      ,CLIENTE.CEP AS CEP
      ,CLIENTE.FONE1 AS TELEFONE
      ,CLIENTE.FONE2 AS CELULAR
      ,CLIENTE.FAX AS FAX
      ,CLIENTE.EMAIL AS EMAIL
      ,CLIENTE.CPFCGC AS CNPJ_CNPF
      ,CLIENTE.INSCESTRG AS IE_RG
      ,CLIENTE.NASCIMENTO AS NASCIMENTO
      ,CLIENTE.SEXO AS SEXO
      ,CLIENTE.CONJUGE AS CONJUGE
      ,CLIENTE.LIMITE AS LIMITE_CREDITO
      ,CLIENTE.CADASTRO AS CADASTRO
      ,CLIENTE.PAI AS PAI
      ,CLIENTE.MAE AS MAE
      ,CLIENTE.OBS AS OBSERVACOES
      ,CLIENTE.CONTATO AS CONTATO
  FROM WN.dbo.CLIENTE
  LEFT JOIN WN.dbo.CIDADES ON CIDADES.CODIGO = CLIENTE.MUNICIPIO
