SELECT
	CODIGO,
	NOME,
	ENDERECO,
	NUMERO,
	CIDADE,
	UF,
	BAIRRO,
	CEP,
	TELEFONE,
	TELEFONE2 AS PERSONAL1,
	FAX,
	CELULAR,
	E_MAIL AS EMAIL,
	REPLACE(REPLACE(REPLACE(REPLACE((CASE WHEN CPF = '' OR CPF IS NULL THEN CNPJ ELSE CPF END), '.', ''), '/', ''), '-', ''), ',', '') AS CNPJ_CNPF,
	REPLACE(REPLACE(REPLACE(REPLACE(I_ESTADUAL, '.', ''), '/', ''), '-', ''), ',', '') AS IE_RG
FROM
	FORNECEDORES