SELECT
    CLIENTE.CODIGO,
    GRCD_CIDAD.NM_CIDAD as CIDADE,
    GRCD_ESTAD.SG_ESTAD as UF,
    CLIENTE.NOME,
    CLIENTE.FANTASIA,
    CLIENTE.CPF_CNPJ as CNPJ_CNPF,
    case when CLIENTE.RG = '' or CLIENTE.RG is null then CLIENTE.INSCRICAO_ESTADUAL else CLIENTE.RG END AS IE_RG,
    CLIENTE.INSCRICAO_MUNICIPAL as IM,
--    CLIENTE.DATA_CADASTRO as CADASTRO,
    CLIENTE.NM_LOGRA as ENDERECO,
    CLIENTE.NU_LOGRA as NUMERO,
    CLIENTE.NM_COMPL as COMPLEMENTO,
    CLIENTE.NM_BAIRR as BAIRRO,
    CLIENTE.NU_TELFN as TELEFONE,
    CLIENTE.NU_CEP as CEP,
    CLIENTE.NM_EMAIL_NFE as EMAIL
FROM CLIENTE
LEFT JOIN GRCD_CIDAD ON(GRCD_CIDAD.CODIGO = CLIENTE.COD_GRCD_CIDAD)
LEFT JOIN GRCD_ESTAD ON(GRCD_ESTAD.CODIGO = GRCD_CIDAD.COD_GRCD_ESTAD)
LEFT JOIN GRCD_PAIS ON(GRCD_PAIS.CODIGO = GRCD_ESTAD.COD_GRCD_PAIS)