SELECT CLIENTES.CODIGO,
CLIENTES.NOME,
CLIENTES.ENDERECO,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.CEP,
CLIENTES.UF,
CLIENTES.TEL1 AS TELEFONE,
CLIENTES.TEL2 AS CELULAR,
CLIENTES.FAX,
CLIENTES.CNPJ AS CNPJ_CNPF,
CLIENTES.INSCEST AS IE_RG,
CLIENTES.CONTATO,
CLIENTES.DATACADASTRO AS CADASTRO,
CLIENTES.EMAIL,
CLIENTES.OBS AS OBSERVACOES,
CLIENTES.DTNASC AS NASCIMENTO,
CLIENTES.FANTASIA,
CLIENTES.NUMENDERECO AS NUMERO,
CLIENTES.COMPLEMENTO
FROM CLIENTES


