SELECT
    CODIGO AS CODIGO,
    RAZAO AS NOME,
    CGC AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    CEP AS CEP,
    FONE1 AS TELEFONE,
    FONE2 AS CELULAR,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR
