SELECT
    PRODUTO.CODIGO AS BARRAS,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
    PRODUTO.PRECOVENDA AS PRECO_VENDA,
    PRODUTO.QUANTIDADE AS QTD,
    PRODUTO.DATAREAJUSTE AS ALTERACAO_PRECO,
    PRODUTO.DATACADASTRO AS DATA_CADASTRO,
    PRODUTO.MARGEMLUCRO AS MARGEM_LUCRO,
    SUBSTRING (PRODUTO.CST FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTO.CST FROM 2 FOR 3) AS ST,
    PRODUTO.CLASSE_IPI AS COD_NCM,
    PRODUTO.PRECO_MEDIO AS CUSTO_MEDIO,
    PRODUTO.OBSERVACAO AS OBSERVACOES,
    PRODUTO.CSOSN,
    PRODUTO.COD_CEST AS PERSONAL6,
    PRODUTO.DT_ULTIMA_VENDA AS ULTIMA_VENDA
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.CODIGO = PRODUTO.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.CODIGO = PRODUTO.SUBGRUPO
