SELECT
    PRODUTO.IDPRODUTO AS CODIGO,
    PRODUTO.DESCRICAOPRODUTO AS DESCRICAO,
    PRODUTO.EAN AS BARRAS,
    PRODUTO.UNIDADEMEDIDA AS UND,
    GRUPO.NOMEGRUPO AS GRUPO,
    SUBGRUPO.NOMESUBGRUPO AS FAMILIA,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
    ESTOQUE.QTDER AS QTD,
    PRODUTO.PRECOAVISTA AS PRECO_VENDA,
    PRODUTO.CSOSN AS ST,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.CODIGONCM AS COD_NCM,
    PRODUTO.ULTIMADATAALTPRECO AS ALTERACAO_PRECO,
    PRODUTO.ULTIMADATAENTRADA AS ULTIMA_COMPRA,
    PRODUTO.ULTIMADATASAIDA AS ULTIMA_VENDA
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.IDGRUPO = PRODUTO.IDGRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.IDSUBGRUPO = PRODUTO.IDSUBGRUPO
LEFT JOIN ESTOQUE ON ESTOQUE.IDPRODUTO = PRODUTO.IDPRODUTO
WHERE ESTOQUE.IDFILIAL = 'AM'
