SELECT
       FORNECEDOR.CODIGO AS CODIGO
	 , FORNECEDOR.NOME AS NOME
	 , FORNECEDOR.nome_fantasia AS FANTASIA
     , FORNECEDOR.CONTATO AS CONTATO
	 , FORNECEDOR.CNPJ AS CNPJ_CNPF
	 , FORNECEDOR.IE AS IE_RG
	 , FORNECEDOR.TELEFONE AS TELEFONE
     , FORNECEDOR.CELULAR AS CELULAR
	 , FORNECEDOR.FAX AS FAX
	 , substring(FORNECEDOR.comentario from 1 for 1000) AS OBSERVACOES
	 , FORNECEDOR.EMAIL AS EMAIL
	 , FORNECEDOR.PAIS AS PAIS_NOME
	 , FORNECEDOR.ENDERECO
	 , FORNECEDOR.NUMERO
	 , FORNECEDOR.COMPLEMENTO
	 , FORNECEDOR.BAIRRO
	 , FORNECEDOR.CIDADE
	 , FORNECEDOR.UF
	 , FORNECEDOR.CEP
FROM FORNECEDOR
WHERE NOME <> '' AND FORNECEDOR.CODIGO <> '00000'
Order by codigo