SELECT
cast(ESTOQUE.CODIGO as integer) AS codigo,
ESTOQUE.BARRAS,
ESTOQUE.NOME AS DESCRICAO,
ESTOQUE.und_venda AS UND,
ESTOQUE.und_compra AS UND_COMPRA,
GRUPOS_NOVOS.DESCRICAO AS GRUPO,
ESTOQUE.qtd_em_estoque AS QTD,
ESTOQUE.local_armazenado AS PERSONAL4,
ADM_EST_ADICIONAIS.CUSTO_MEDIO AS CUSTO_MEDIO,
ESTOQUE.preco_de_custo AS PRECO_CUSTO,
ESTOQUE.preco_consumidor AS PRECO_VENDA,
SUBSTRING(ESTOQUE.observacao FROM 1 FOR 1000) AS OBSERVACOES,
--SUBSTRING(ADM_EST_ADICIONAIS.ST FROM 1 FOR 1) AS OST,
--SUBSTRING(ADM_EST_ADICIONAIS.ST FROM 2 FOR 2) AS ST,
SUBSTRING(ADM_EST_ADICIONAIS.csosn FROM 1 FOR 1) AS OST,
SUBSTRING(ADM_EST_ADICIONAIS.csosn FROM 2 FOR 4) AS ST,
ADM_EST_ADICIONAIS.CF AS CF,
ADM_EST_ADICIONAIS.PIS_ST AS PIS_CODIGO,
ADM_EST_ADICIONAIS.PIS_BASE AS PIS_BASE_NOR,
ADM_EST_ADICIONAIS.PIS_ALIQ AS PIS_ALIQ_NOR,
ADM_EST_ADICIONAIS.PIS_SUB_BASE AS PIS_BASE_SUB,
ADM_EST_ADICIONAIS.PIS_SUB_ALIQ AS PIS_ALIQ_SUB,
ADM_EST_ADICIONAIS.COFINS_ST AS COFINS_CODIGO,
ADM_EST_ADICIONAIS.COFINS_BASE AS COFINS_BASE_NOR,
ADM_EST_ADICIONAIS.COFINS_ALIQ AS COFINS_ALIQ_NOR,
ADM_EST_ADICIONAIS.COFINS_SUB_BASE AS COFINS_BASE_SUB,
ADM_EST_ADICIONAIS.COFINS_SUB_ALIQ AS COFINS_ALIQ_SUB
FROM ESTOQUE
LEFT JOIN ADM_EST_ADICIONAIS ON ESTOQUE.CODIGO = ADM_EST_ADICIONAIS.CODIGO
LEFT JOIN GRUPOS_NOVOS ON ESTOQUE.GRUPO = GRUPOS_NOVOS.CODIGO
ORDER BY ESTOQUE.CODIGO
