SELECT
    ITENS.CODIGO AS CODIGO,
    ITENS.DESCRICAO AS DESCRICAO,
    ITENS.CODIGOBARRAS AS BARRAS,
    ITENS.UNIDADE AS UND,
    ITENS.UNIDADEENTRADA AS UND_COMPRA,
    GRUPOS.descricaogrupo AS GRUPO,
    FAVORECIDOS.NOME AS FORNECEDOR,
    ITENS.QTDEMINIMO AS QTD_INICIAL,
    ITENS.ESTOQUE AS QTD,
    ITENS.CUSTOMEDIO AS CUSTO_MEDIO,
    ITENS.PRECOCOMPRA AS PRECO_CUSTO,
    ITENS.FATORLUCRO AS MARGEM_LUCRO,
    PRODUTOSPRECO.preco AS PRECO_VENDA,
    ITENS.REFERENCIA AS COD_FABRICANTE,
    ITENS.DATACADASTRO AS DATA_CADASTRO,
    ITENS.ULTIMACOMPRA AS ULTIMA_COMPRA,
    ITENS.CST AS ST,
    ITENS.CLASFISCAL AS COD_NCM,
    ITENS.CEST_OPC AS PERSONAL6
FROM ITENS
INNER JOIN ITENSCODIGOS ON ITENSCODIGOS.CODIGO = ITENS.CODIGOVENDA
INNER JOIN PRODUTOSPRECO ON PRODUTOSPRECO.ITEM = ITENS.ITEM AND PRODUTOSPRECO.tabelapreco = 0
LEFT JOIN grupos ON GRUPOS.grupo = ITENS.GRUPO
LEFT JOIN FAVORECIDOS ON FAVORECIDOS.favorecido = ITENS.ULTIMOFORNECEDOR
