SELECT BCOPR.CODIGO,
BCOPR.DESCRICAO,
BCOPR.UNIDMED AS UND,
BCOFOR.RAZAO AS FORNECEDOR,
BCOGP.DESCRICAO AS GRUPO,
BCOPR.CODBARRAS AS BARRAS,
BCOPR.REFERENCIA AS COD_FABRICANTE,
BCOPR.ESTOQUE1 AS QTD,
BCOPR.PRECOCUSTO AS PRECO_CUSTO,
BCOPR.PRECOVENDA1 AS PRECO_VENDA,
CAST(BCOPR.DATACAD AS DATE) AS DATA_CADASTRO,
BCOPR.ST,
BCOPR.NCM AS COD_NCM,
BCOPR.CEST AS PERSONAL6
FROM BCOPR
LEFT JOIN BCOFOR ON BCOPR.CODFORN=BCOFOR.CODIGO
LEFT JOIN BCOGP ON BCOPR.GRUPOPROD=BCOGP.CODIGO
