SELECT
    FORNECEDORES.FORNECEDORESID AS CODIGO,
    FORNECEDORES.NOME AS NOME,
    case when FORNECEDORES.CPF = '' or FORNECEDORES.CPF is null then FORNECEDORES.CNPJ else FORNECEDORES.CPF END AS CNPJ_CNPF,
    case when FORNECEDORES.RG = '' or FORNECEDORES.RG is null then FORNECEDORES.IE else FORNECEDORES.RG END AS IE_RG,
    ENDERECOS.ENDERECO AS ENDERECO,
    ENDERECOS.BAIRRO AS BAIRRO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    ESTADOS.SIGLA AS UF,
    MUNICIPIOS.DESCRICAO AS CIDADE,
    ENDERECOS.CEP AS CEP,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES
LEFT JOIN ENDERECOS ON ENDERECOS.ENDERECOSID = FORNECEDORES.ENDERECOSID
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.MUNICIPIOSID = ENDERECOS.MUNICIPIOSID
LEFT JOIN ESTADOS ON ESTADOS.ESTADOSID = MUNICIPIOS.ESTADOSID