SELECT
    replace(PRODUTOS.PRODUTOSID,'.',''),
    PRODUTOS.CODIGOBARRA AS BARRAS,
    PRODUTOS.NOME AS DESCRICAO,
    UNIDADES.SIGLA AS UND,
    PRODUTOS.CUSTO AS PRECO_CUSTO,
    PRODUTOS.PRECO AS PRECO_VENDA,
    PRODUTOS.MARGEM AS MARGEM_LUCRO,
    GRUPOS_PRODUTOS.DESCRICAO AS GRUPO,
    PRODUTOS.ESTOQUEMINIMO AS QTD_IDEAL,
    PRODUTOS.ESTOQUEATUAL AS QTD,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.CSOSN AS ST,
    --PRODUTOS.CST,
    PRODUTOS.CEST AS PERSONAL6,
    PRODUTOS.OBSERVACAO AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN GRUPOS_PRODUTOS ON GRUPOS_PRODUTOS.GRUPOSPRODUTOSID = PRODUTOS.GRUPOSPRODUTOSID
LEFT JOIN UNIDADES ON UNIDADES.UNIDADESID = PRODUTOS.UNIDADESID