SELECT
    FORNECEDORES.CODIGOFORNECEDOR AS CODIGO,
    FORNECEDORES.NOMEFORNECEDOR AS NOME,
    FORNECEDORES.RESPON AS CONTATO,
    FORNECEDORES.CPFCNPJ AS CNPJ_CNPF,
    FORNECEDORES.RGIE AS IE_RG,
    CEPS.ENDERECO AS ENDERECO,
    BAIRROS.NOME AS BAIRRO,
    FORNECEDORES.NUMERO AS NUMERO,
    CEPS.COMPLEMENTO AS COMPLEMENTO,
    replace (replace(CEPS.NUM_CEP,'-',''),'.','') AS CEP,
    CIDADES.NOMECIDADE AS CIDADE,
    CIDADES.UF AS UF,
    FORNECEDORES.E_MAIL AS EMAIL,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX
    --FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES
LEFT join CEPS ON CEPS.IDCEP = FORNECEDORES.IDCEP
LEFT JOIN BAIRROS ON BAIRROS.IDBAIRRO = CEPS.IDBAIRRO
LEFT JOIN CIDADES ON CIDADES.IDCIDADE = BAIRROS.IDCIDADE
