SELECT
    PRODUTOS.CODIGOPRODUTO AS CODIGO,
    PRODUTOS.CODIGOBARRA AS BARRAS,
    PRODUTOS.NOMEPRODUTO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
    GRUPOS.NOMEGRUPO AS GRUPO,
    SUBGRUPOS.NOMESUBGRUPO AS FAMILIA,
    PRODUTOS.PESOLIQUIDO AS PESO,
    PRODUTOS.PR_AVISTA AS PRECO_VENDA,
    SUBSTRING (PRODUTOS.CSTPRO FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.CSTPRO FROM 2 FOR 3) AS ST,
    PRODUTOS.DATALANC AS ULTIMA_VENDA,
    PRODUTOS.CFNCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPOS ON GRUPOS.IDGRUPO = PRODUTOS.IDGRUPO
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.IDSUBGRUPO = PRODUTOS.IDSUBGRUPO
WHERE CODIGOPRODUTO < '900000'
