 SELECT
  FORNECEDORES.CODIGO AS CODIGO,
  FORNECEDORES.RAZAOSOCIAL AS NOME,
  FORNECEDORES.INSCRICAO AS CNPJ_CNPF,
  FORNECEDORES.INSCRICAOESTADUAL AS IE_RG,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.BAIRRO AS BAIRRO,
  CIDADES.NOME AS CIDADE,
  CIDADES.UF AS UF,
  FORNECEDORES.FANTASIA AS FANTASIA,
  FORNECEDORES.INSCMUNICIPAL AS IM,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
  FORNECEDORES.OBS AS OBSERVACOES,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.EMAIL AS EMAIL,
  FORNECEDORES.CONTATO AS CONTATO
  FROM FORNECEDORES
  LEFT JOIN CIDADES ON CIDADES.CODIGO = FORNECEDORES.CODCIDADE 
