 SELECT
  ITENS.CODIGO AS CODIGO,
  ITENS.DESCRICAO AS DESCRICAO,
  cast (CLASSIFICACAOFISCAL.DTCADASTRO as date) AS DATA_CADASTRO,
  ITENS.COMPLEMENTO AS CARACTERISTICAS,
  ITENS.CODBARRAS AS BARRAS,
  ITENS.VALORCUSTO AS PRECO_CUSTO,
  ITENS.PERLUCRO AS MARGEM_LUCRO,
  ITENS.PERCCOMISSAO AS COMISSAO,
  ITENS.UNID1CONV AS UND,
  CLASSIFICACAOFISCAL.NCM AS COD_NCM,
  ITENS.VALORVENDA AS PRECO_VENDA,
  ITENS.PESOLIQUIDO AS PESO,
  ITENS.SALDO AS QTD,
  ITENS.CEST AS PERSONAL6,
  ITENS.CSOSNITEM AS ST
  FROM ITENS
  LEFT JOIN CLASSIFICACAOFISCAL ON CLASSIFICACAOFISCAL.CODIGO = ITENS.CLASSIFICACAOFISCAL
