SELECT
    CODIGO_FOR AS CODIGO,
    NOME_FOR AS NOME,
    FANTASIA_FOR AS FANTASIA,
    ENDERE_FOR AS ENDERECO,
    COMPLEM_FOR AS COMPLEMENTO,
    CIDADE_FOR AS CIDADE,
    ESTADO_FOR AS UF,
    CEP_FOR AS CEP,
    CGC_FOR AS CNPJ_CNPF,
    INSCRI_FOR AS IE_RG,
    TELEFO_FOR AS TELEFONE,
    FAX_FOR AS FAX,
    CONTATO_FOR AS CONTATO,
    CELULAR_FOR AS CELULAR,
    EMAIL_FOR AS EMAIL,
    BAIRRO_FOR AS BAIRRO
FROM FORNECEDOR
