SELECT
    PRODUTO.ID_PRODUTO AS COD_FABRICANTE,
    PRODUTO.DESCRICAO_PRODUTO AS DESCRICAO,
    PRODUTO.ESTOQUE AS QTD,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    --PRODUTO.PV1 AS PRECO_VENDA,
    PRODUTO.PV2 AS PRECO_VENDA,
    --PRODUTO.PV2 AS PRECO_ATACADO,
    FORNECEDOR.NOME_FOR AS FORNECEDOR,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    SUBGRUPO.DESCRICAO_SUBGRUPO AS GRUPO,
    PRODUTO.CODIGO_BARRA AS BARRAS,
    PRODUTO.CODIGO_NACIONAL AS COD_NCM,
    PRODUTO.CSOSN AS ST,
    PRODUTO.CODIGO_CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN FORNECEDOR ON PRODUTO.CODIGO_FOR = FORNECEDOR.CODIGO_FOR
LEFT JOIN SUBGRUPO ON PRODUTO.COD_SUBGRUPO = SUBGRUPO.COD_SUBGRUPO
