SELECT
    PRODUTO.id AS CODIGO,
    PRODUTO.nome AS DESCRICAO,
    PRODUTO.gtin AS BARRAS,
    PRODUTO_UNIDADE.SIGLA AS UND,
    PRODUTO.quantidade_estoque AS QTD,
    PRODUTO.valor_compra AS PRECO_CUSTO,
    PRODUTO.valor_venda AS PRECO_VENDA,
    PRODUTO.ncm AS COD_NCM,
    PRODUTO.cest AS PERSONAL6,
    PRODUTO.data_alteracao AS ALTERACAO_PRECO,
    PRODUTO.data_cadastro AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN PRODUTO_UNIDADE ON PRODUTO.ID_UNIDADE = PRODUTO_UNIDADE.ID