SELECT
    ID AS CODIGO,
    CDPR AS COD_FABRICANTE,
    BARRAS AS BARRAS,
    DSPR AS DESCRICAO,
    PESOLIQ AS PESO,
    NCM AS COD_NCM,
    CST AS ST,
    PRECOVENDA AS PRECO_VEMDA,
    CUSTOMEDIO AS CUSTO_MEDIO,
    ESTOQUE AS QTD
FROM CADPRO