SELECT  [CONTATO] AS CONTATO
      ,[AGECOD] AS CODIGO
      ,[AGEDES] AS NOME
      ,[AGEFAN] AS FANTASIA
      ,[AGECGCCPF] AS CNPJ_CNPF
      ,[AGECGFRG] AS IE_RG
      ,[AGETEL1] AS TELEFONE
      ,[AGETEL2] AS CELULAR
      ,[AGEEND] AS ENDERECO
      ,[AGEBAI] AS BAIRRO
      ,[AGENUM] AS NUMERO
      ,[AGECPL] AS COMPLEMENTO
      ,[AGECEP] AS CEP
      ,[AGECORELE] AS EMAIL
      ,[AGECID] AS CIDADE
      ,[AGEEST] AS UF
  FROM [SysacME].[dbo].[V_CLIENTE]
  order by 2
