SELECT REFERENCIA.REFPLU AS CODIGO
      ,PRODUTO.[PROCOD] AS COD_FABRICANTE
      ,MARCA.MARDES AS CARACTERISTICAS
      ,SUBGRUPO.SBGDES AS FAMILIA
      ,GRUPO.GRPDES AS GRUPO
	  ,ESTOQUE.ESTTOT AS QTD 
      ,PRODUTO.[PROUNDVDA] AS UND
      ,PRODUTO.[TRBID] AS ST
      ,PRODUTO.[PROUNDCMP] AS UND_COMPRA
      ,PRODUTO.[PRODES] AS DESCRICAO
      ,PRODUTO.[PROCOM1] AS PRECO_CUSTO
      ,PRODUTO.[PROMRG1] AS MARGEM_LUCRO
      ,PRODUTO.[PRONCM] AS COD_NCM
      ,PRODUTO.[PROPRCCADVDA1] AS PRECO_VENDA
  FROM [SysacME].[dbo].[PRODUTO]
  LEFT JOIN [SysacME].[dbo].GRUPO ON PRODUTO.GRPCOD = GRUPO.GRPCOD
  LEFT JOIN [SysacME].[dbo].SUBGRUPO ON PRODUTO.SBGCOD = SUBGRUPO.SBGCOD AND GRUPO.GRPCOD = SUBGRUPO.GRPCOD
  LEFT JOIN [SysacME].[dbo].[MARCA] ON PRODUTO.MARCOD = MARCA.MARCOD
  LEFT JOIN [SysacME].[dbo].[REFERENCIA] ON PRODUTO.PROCOD = REFERENCIA.PROCOD
  LEFT JOIN [SysacME].[dbo].ESTOQUE ON REFERENCIA.REFPLU = ESTOQUE.REFPLU
  WHERE ESTOQUE.LOCCOD = '001' AND ESTOQUE.LOJCOD = '000001'
