SELECT
    PRODUTOS.CODIGO,
    PRODUTOS.DESCRICAO,
    PRODUTOS.REFERENCIA COD_FABRICANTE,
    PRODUTOS.REFERENCIAEXT AS CARACTERISTICAS,
    PRODUTOS.COD_BARRA AS BARRAS,
    GRUPOEST.DESCRICAO AS GRUPO,
    ESTOQUE.QUANTIDADE AS QTD,
    PRODUTOS.UNID AS UND,
    PRODUTOS.PRECO_VENDA,
    PRODUTOS.PRECO_CUSTO,
    PRODUTOS.APLICACAO2 as OBSERVACOES,
    PRODUTOS.NCM
FROM PRODUTOS
LEFT JOIN GRUPOEST ON PRODUTOS.COD_GRP = GRUPOEST.CODIGO
LEFT JOIN ESTOQUE ON PRODUTOS.CODIGO = ESTOQUE.IDCODIGO
