SELECT
    ID AS CODIGO,
    NOME AS NOME,
    NOME_FANT AS FANTASIA,
    CGC AS CNPJ_CNPF,
    IE AS IE_RG,
    NOMERUA AS ENDERECO,
    NUMRUA AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ID_UF AS UF,
    CEP  AS CEP,
    COALESCE (DDD,'') || COALESCE (TELEFONE, '') AS TELEFONE,
    COALESCE (DDD,'') || COALESCE (FAX, '') AS FAX,
    CONTATO_VENDA AS CONTATO,
    EMAIL AS EMAIL
FROM FORNECE
