SELECT
    CODFOR AS CODIGO,
    NOMFOR AS NOME,
    FANTASIA AS FANTASIA,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    COMPLEMENTO AS COMPLEMENTO,
    CIDADE AS CIDADE,
    CEP AS CEP,
    UF AS UF,
    FONE AS TELEFONE,
    FAX AS FAX,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    CONTATO AS CONTATO,
    OBS1 AS OBSERVACOES,
    NUMERO AS NUMERO,
    EMAIL AS EMAIL
FROM FORNECEDOR
