SELECT
    PRODUTOS.CODPRO AS CODIGO,
    PRODUTOS.NOMPRO AS DESCRICAO,
    PRODUTOS.LOCAL2 AS OBSERVACOES,
    PRODUTOS.BARRA AS BARRAS,
    PRODUTOS.PVENDA AS PRECO_VENDA,
    PRODUTOS.PCUSTO AS PRECO_CUSTO,
    PRODUTOS.PPRAZO AS PERSONAL5,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.MINIMO AS QTD_IDEAL,
    PRODUTOS.LUCRO AS MARGEM_LUCRO,
    PRODUTOS.CADASTRO AS DATA_CADASTRO,
    PRODUTOS.REFPRO AS COD_FABRICANTE,
    GRUPOS.NOMGRU AS GRUPO,
    SGRUPOS.NOMSGRU AS FAMILIA,
    MARCAS.NOMMAR AS CARACTERISTICAS,
    replace(PRODUTOS.CODNCM,'.','') AS COD_NCM,
    PRODUTOS.PESOLIQ AS PESO,
    FORNECEDOR.NOMFOR AS FORNECEDOR,
    TRIBUTA.ST AS ST,
    PRODUTOS.DATAALTERA AS ALTERACAO_PRECO,
    PRODUTOS.PCODCEST AS PERSONAL6
FROM PRODUTOS 
LEFT JOIN TRIBUTA ON TRIBUTA.CODTRI = PRODUTOS.CODTRI
LEFT JOIN FORNECEDOR ON FORNECEDOR.CODFOR = PRODUTOS.CODFOR 
LEFT JOIN GRUPOS ON GRUPOS.CODGRU = PRODUTOS.CODGRU
LEFT JOIN SGRUPOS ON SGRUPOS.CODSGRU = PRODUTOS.CODSGRU
LEFT JOIN MARCAS ON MARCAS.CODMAR = PRODUTOS.CODMAR
