SELECT
    PRODUTO.CD_PRODUTO AS CODIGO,
    PRODUTO.NR_REFERENCIA AS COD_FABRICANTE,
    GRUPO.ds_grupo AS GRUPO,
    PRODUTO.DS_PRODUTO AS DESCRICAO,
    PRODUTO.NR_CODBARRAS AS BARRAS,
    PRODUTO.VL_PRECOCUSTO AS PRECO_CUSTO,
    PRODUTO.VL_PRECOVENDA AS PRECO_VENDA,
    PRODUTO.UN_UNIDADE AS UND,
    TRIBUTACAO.DS_CSTSIMPLES AS ST,
    PRODUTO.NR_CLASSFIS AS COD_NCM,
    PRODUTO.DT_CADASTRO AS DATA_CADASTRO,
    PRODUTO.PR_MARKUP AS MARGEM_LUCRO,
    PRODUTO.DT_ULTALTPRE AS ALTERACAO_PRECO,
    PRODUTO.NR_CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.cd_grupo = PRODUTO.CD_GRUPO
LEFT JOIN tributacao ON TRIBUTACAO.cd_tribut = PRODUTO.CD_TRIBUTACAO