SELECT 
CLIENTES.ID_CODIGO AS CODIGO,
CLIENTES.NOME,
CLIENTES.NASCIMENTO,
CLIENTES.NOMEPOP AS FANTASIA,
CLIENTES.ENDERECO,
CLIENTES.NUMERO,
CLIENTES.CIDADE,
CLIENTES.ESTADO AS UF,
CLIENTES.CEP,
case when CLIENTES.CIC = '' or CLIENTES.CIC is null then CLIENTES.CGC else CLIENTES.CIC END as CNPJ_CNPF,
case when CLIENTES.RG = '' or CLIENTES.RG is null then CLIENTES.INSC_EST else CLIENTES.RG END as IE_RG,
CLIENTES.TELEFONE,
CLIENTES.FAX,
CLIENTES.CELULAR,
CLIENTES.PAI,
CLIENTES.MAE,
CLIENTES.EMAIL
FROM CLIENTES




