SELECT
  FORNECEDORES.CODIGO AS CODIGO,
  FORNECEDORES.NOME AS NOME,
  FORNECEDORES.NOMEFANTASIA AS FANTASIA,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.CIDADE AS CIDADE,
  FORNECEDORES.ESTADO AS UF,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.TELEFONE AS TELEFONE,
  FORNECEDORES.FAX AS FAX,
  FORNECEDORES.EMAIL AS EMAIL,
  FORNECEDORES.CNPJ AS CNPJ_CNPF,
  FORNECEDORES.IE AS IE_RG,
  FORNECEDORES.BAIRRO AS BAIRRO,
  FORNECEDORES.OBSERVACOES AS OBSERVACOES,
  FORNECEDORES.REPRESNOME AS CONTATO,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO
FROM FORNECEDORES


