SELECT PRODUTOS.ID_CODIGO AS CODIGO,
PRODUTOS.NOMPRO_ AS DESCRICAO,
PRODUTOS.N_REF_ AS BARRAS,
PRODUTOS.MARCA_ AS CARACTERISTICAS,
PRODUTOS.UND_ AS UND,
PRODUTOS.UNDE_ AS UND_COMPRA,
PRODUTOS.NOMGRU_ AS GRUPO,
PRODUTOS.ESTOQUE_ AS QTD,
PRODUTOS.PRAVISTA_ AS PRECO_VENDA,
PRODUTOS.PRCCOMPRA_ AS PRECO_CUSTO,
SUBSTRING (tabsittrib.NOMSITTRIBUTO FROM 1 FOR 1) AS ST,
PRODUTOS.DATACAD AS DATA_CADASTRO,
PRODUTOS.NCM_ AS COD_NCM,
PRODUTOS.OBSERVACAO AS OBSERVACOES,
PRODUTOS.CEST_ AS PERSONAL6
FROM PRODUTOS
left join tabsittrib on tabsittrib.id_codigo = produtos.st_


