SELECT
  TBCLI.CODCLI AS CODIGO,
  TBCLI.NOME AS NOME,
  TBCLI.APELIDIO AS CONTATO,
  TBCLI.NUMERO AS NUMERO,
  TBCLI.COMPLEMENTO AS COMPLEMENTO,
  TBCLI.FONE AS TELEFONE,
  TBCLI.FAX AS FAX,
  TBCLI.CELULAR AS CELULAR,
  TBCLI.CPF AS CNPJ_CNPF,
  TBCLI.RG AS IE_RG,
  TBCLI.DTCAD AS CADASTRO,
  TBCLI.LIMITE AS LIMITE_CREDITO,
  TBCLI.EMAIL AS EMAIL,
  TBCLI.OBS AS OBSERVACOES,
  TBCLI.ENDERECO AS ENDERECO,
  TBCLI.BAIRRO AS BAIRRO,
  TBCLI.CEP AS CEP,
  TBCLI.UF AS UF,
  TBCIDADE.DESCRICAO AS CIDADE,
  TBCLI.PAI AS PAI,
  TBCLI.MAE AS MAE
FROM TBCLI
LEFT JOIN TBCIDADE ON TBCIDADE.CODIGO = TBCLI.CODCIDADEI



