SELECT
  TBFOR.CODFOR AS CODIGO,
  TBFOR.NOME AS NOME,
  TBFOR.APELIDIO AS CONTATO,
  TBFOR.ENDERECO AS ENDERECO,
  TBFOR.COMPLEMENTO AS COMPLEMENTO,
  TBFOR.CEP AS CEP,
  TBFOR.BAIRRO AS BAIRRO,
  TBFOR.UF AS UF,
  TBFOR.CIDADE AS CIDADE,
  TBFOR.FONE AS TELEFONE,
  TBFOR.FAX AS FAX,
  TBFOR.CELULAR AS CELULAR,
  TBFOR.EMAIL AS EMAIL,
  TBFOR.RG AS IE_RG,
  TBFOR.CNPJ AS CNPJ_CNPF,
  TBFOR.OBSGERAIS AS OBSERVACOES,
  TBFOR.NUMERO AS NUMERO
FROM TBFOR





