SELECT
  TBITEM.CODITEM AS CODIGO,
  TBITEM.CODBARRA AS BARRAS,
  TBITEM.REF AS COD_FABRICANTE,
  TBITEM.DESCRICAO AS DESCRICAO,
  TBITEM.DESCABREV AS CARACTERISTICAS,
  TBITEM.CODUNDI AS UND,
  TBESTOQUE.QTDDISPONIVEL AS QTD,
  TBCST.CODCST AS ST,
  TBGRUPO.DESCRICAO AS GRUPO,
  TBSUBGRUPO.DESCRICAO AS FAMILIA,
  TBITEM.DTCAD AS DATA_CADASTRO,
  TBITEM.PESOLIQUIDO AS PESO,
  TBITEM.CUSTOMEDIO AS CUSTO_MEDIO,
  TBITEM.VALOR AS PRECO_VENDA,
  TBESTOQUE.DTULTVENDA AS ULTIMA_VENDA,
  TBNCM.CODNCM AS COD_NCM,
  TBITEM.CEST_ST AS PERSONAL6
FROM TBITEM
LEFT JOIN TBNCM ON TBNCM.CHAVE = TBITEM.CODNCM
LEFT JOIN TBGRUPO ON TBGRUPO.CODIGO = TBITEM.CODGRUPOI
LEFT JOIN TBSUBGRUPO ON TBSUBGRUPO.CODIGO = TBITEM.CODSUBGRUPOI
LEFT JOIN TBESTOQUE ON TBESTOQUE.CODITEMI = TBITEM.CODITEM
LEFT JOIN TBCST ON TBCST.CODCST = TBITEM.CODTIPOITEMI

