SELECT
    CODIGO_FORNECEDOR AS CODIGO,
    NOME_FORNECEDOR AS NOME,
    RAZAO_SOCIAL AS FANTASIA,
    ENDERECO,
    BAIRRO,
    CEP,
    CIDADE,
    UF,
    CNPJ AS CNPJ_CNPF,
    INSC_ESTADUAL AS IE_RG,
    TELEFONE_1 AS TELEFONE,
    TELEFONE_2 AS CELULAR,
    FAX,
    E_MAIL AS EMAIL,
    CONTATO_1 AS CONTATO
FROM FORNECEDORES
