select  
        TC.CONTROLE AS CODIGO
,       TC.CLIENTE AS NOME
,       TC.FANTASIA
,       TC.ENDERECO AS ENDERECO
,       TC.NUMERO
,       TC.COMPLEMENTO
,       TC.BAIRRO
,       TC.CIDADE
,       TC.UF
,       TC.CEP
,       TC.NATURALIDADE
,   CASE WHEN TC.CPF IS NULL THEN TC.CNPJ ELSE TC.CPF END AS CNPJ_CNPF
,   CASE WHEN TC.IE IS NULL THEN TC.RG ELSE TC.IE END AS IE_RG
,      CAST(TC.DATAHORACADASTRO AS DATE) AS CADASTRO
,      TC.DATANASCIMENTO AS NASCIMENTO
,      TC.PAI
,      TC.MAE
,      TC.TELEFONE
,      TC.CELULAR
,      TC.EMAIL
,      TC.OBS ||' - '|| TC.DADOSADICIONAIS AS OBSERVACOES
,      TC.NOMECONTATOJURIDICA AS CONTATO
,      TC.ESTADOCIVIL AS EST_CIVIL
,      TC.LIMITECREDITO AS LIMITE_CREDITO
,      TC.NOMECONJUGE AS CONJUGE 
,      TC.DATAULTIMAVENDA AS ULTIMA_VENDA
,      TC.PROFISSAO 
,      TC.EMPRESAQUETRABALHA AS LOCTRA
,      TC.sexo
,      LEFT (TC.CAMPO1, 30) AS personal1
,      LEFT (TC.CAMPO2, 30) AS personal2 
,      LEFT (TC.CAMPO3, 30) AS personal3 
,      LEFT (TC.CAMPO4, 30) AS personal4 
,      LEFT (TC.CAMPO5, 30) AS personal5 
,      LEFT (TC.EMAIL2, 30) AS personal6
,      case when TC.ATIVO =  'SIM' then 'Ativo' else 'Inativo' end as SITUACAO
from TCLIENTE AS TC
--WHERE TC.ATIVO='SIM'
