SELECT 
       TF.CONTROLE AS CODIGO
,      TF.RAZAOSOCIAL AS NOME
,      TF.NOMECONTATOJURIDICA AS CONTATO
,      TF.NOMEFANTASIA AS FANTASIA
,      TF.ENDERECO
,      TF.NUMERO
,      TF.BAIRRO
,      TF.CIDADE
,      TF.UF
,      TF.CEP
,      CASE WHEN CNPJ IS NULL THEN CPF ELSE CNPJ END AS CNPJ_CNPF
,      CASE WHEN IE IS NULL THEN RG ELSE IE END AS IE_RG
,      TF.COMPLEMENTO
,      TF.TELEFONE
,      TF.CELULAR
,      TF.EMAIL
,      TF.OBS AS OBSERVACOES
FROM TFORNECEDOR AS TF
--WHERE TF.ATIVO='SIM'
