SELECT
  TTRANSPORTADORA.CONTROLE AS CODIGO,
  TTRANSPORTADORA.NOMERAZAOSOCIAL AS RAZAO_SOCIAL,
  TTRANSPORTADORA.ENDERECO||' - '||TTRANSPORTADORA.BAIRRO||' - '||TTRANSPORTADORA.CEP AS ENDERECO,
  TTRANSPORTADORA.CIDADE AS CIDADE,
  case when TTRANSPORTADORA.CNPJ  = '' then TTRANSPORTADORA.CPF else TTRANSPORTADORA.CNPJ  end as CNPJ,
  TTRANSPORTADORA.IE AS IE,
  TTRANSPORTADORA.TELEFONE AS TELEFONE,
  TTRANSPORTADORA.CODIGOANTT AS RNTRC,
  TTRANSPORTADORA.PLACAVEICULO AS PLACA,
  TTRANSPORTADORA.UF AS UF,
  TTRANSPORTADORA.EMAIL AS EMAIL
FROM TTRANSPORTADORA
