SELECT CODIGO AS CODIGO,
NOME AS NOME,
ENDERECO AS ENDERECO,
BAIRRO AS BAIRRO,
CEP AS CEP,
CIDADE AS CIDADE,
UF AS UF,
TELEFONES AS TELEFONE,
NASCIMENTO AS NASCIMENTO,
EMAIL AS EMAIL,
RG AS IE_RG,
CPF AS CNPJ_CNPF
FROM CLIENTES
