SELECT CODIGO AS CODIGO,
NOME AS NOME,
ENDERECO AS ENDERECO,
BAIRRO AS BAIRRO,
CEP AS CEP,
CIDADE AS CIDADE,
UF AS UF,
TELEFONES AS TELEFONE,
EMAIL AS EMAIL,
INSC_ESTADUAL AS IE_RG,
CNPJ AS CNPJ_CNPF
FROM FORNECEDORES
