SELECT
    CODIGO AS CODIGO,
    NOME AS DESCRICAO,
    CODIGO_DE_BARRAS AS BARRAS,
    FABRICANTE AS CARACTERISTICAS,
    FAMILIA AS FAMILIA, 
    PRECO_DE_VENDA AS PRECO_VENDA,
    QUANTIDADE_ESTOQUE AS QTD,
    PRECO_DE_COMPRA AS PRECO_CUSTO,
    UNIDADE_MEDIDA AS UND,
    NCM AS COD_NCM,
    CODIGO_FABRICANTE AS COD_FABRICANTE,
    ICMS_SITUA_TRIBUT AS ST,
    CEST AS PERSONAL6
FROM PRODUTOS 
