SELECT
    PESSOAS.CODIGO AS CODIGO,
    PESSOAS.NOME_RAZAOSOCIAL AS NOME,
    PESSOAS.APELIDO_FANTASIA AS FANTASIA,
    PESSOAS.CPF_CNPJ AS CNPJ_CNPF,
    PESSOAS.RG_IE AS IE_RG,
    ENDERECOS.LOGRADOURO AS ENDERECO,
    ENDERECOS.NUMERO AS NUMERO,
    ENDERECOS.COMPLEMENTO AS COMPLEMENTO,
    ENDERECOS.BAIRRO AS BAIRRO,
    CIDADES.CIDADE AS CIDADE,
    CIDADES.UF AS UF,
    ENDERECOS.CEP AS CEP,
    PESSOAS.TELEFONE AS TELEFONE,
    PESSOAS.FAX AS FAX,
    PESSOAS.EMAIL AS EMAIL,
    PESSOAS.CELULAR AS CELULAR,
    PESSOAS.CONTATO AS CONTATO,
    PESSOAS.OBSERVACOES AS OBSERVACOES
FROM PESSOAS
LEFT JOIN ENDERECOS ON ENDERECOS.ID = PESSOAS.ENDERECO
LEFT JOIN CIDADES ON CIDADES.CODIGO = ENDERECOS.CIDADE
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = PESSOAS.CODIGO
WHERE TIPO_PESSOA = 'J' --FORNECEDORES