SELECT
    PRODUTOS.CD_PRODUTO AS CODIGO,
    UNIDADES.NOME_UNIDADE AS UND,
    GRUPO.NOME_GRUPO AS GRUPO,
    PRODUTOS.DESCRICAO_PRODUTO AS DESCRICAO,
    PRODUTOS.CODBARRA_PRODUTO AS BARRAS,
    SALDOS.SALDO_SALDO AS QTD,
    PRODUTOS.OBSERVACAO_PRODUTO AS OBSERVACOES,
    CAST (PRODUTOS.DTULTALTERACAO_PRODUTO AS DATE) AS ALTERACAO_PRECO,
    PRODUTOS.CODREF_PRODUTO AS COD_FABRICANTE,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.PCE_PCO_NORMAL AS PRECO_VENDA,
    PRODUTOS.CD_PRODUTO_NCM AS COD_NCM,
    MAX (TRIBUTACAO_PRODUTO.TP_CSOSN) AS ST,
    PRODUTOS.PRD_PESOLIQUIDO AS PESO,
    PRODUTOS.CD_PRODUTO_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN TRIBUTACAO_PRODUTO  ON TRIBUTACAO_PRODUTO.TP_CODIGO_TRIBUTACAO = PRODUTOS.TP_CODIGO_TRIBUTACAO 
LEFT JOIN UNIDADES ON UNIDADES.CD_UNIDADE = PRODUTOS.CD_UNIDADE
LEFT JOIN GRUPO ON GRUPO.CD_GRUPO = PRODUTOS.CD_GRUPO
LEFT JOIN SALDOS ON SALDOS.cd_produto = PRODUTOS.CD_PRODUTO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,14,15
