SELECT
    PRODUTO.PRO_CODIGO AS CODIGO,
    MAX(PRODUTO.PRO_CODIGO_OR) AS BARRAS,
    MAX(PRODUTO.PRO_DESCRICAO) AS DESCRICAO,
    MAX(PRODUTO.PRO_UNIDADE) AS UND,
    MAX(PRODUTO.PRO_PRECO_CUSTO) AS PRECO_CUSTO,
    MAX(PRODUTO.PRO_PRECO_VENDA) AS PRECO_VENDA,
    MAX(PRODUTO.PRO_MARKUP_MARGLUCR_PERC) AS MARGEM_LUCRO,
    MAX(PRODUTO.PRO_REFERENCIA) AS COD_FABRICANTE,
    MAX(PRODUTO.PRO_DATA_INC::DATE) AS DATA_CADASTRO,
    MAX(PRODUTO.PRO_OBS) AS OBSERVACOES,
    MAX(PRODUTO.PRO_COR) AS COR,
    MAX(PRODUTO.PRO_TAMANHO) AS TAMANHO,
    MAX(PRODUTO.PRO_PESO) AS PESO,
    MAX(PRODUTO.PRO_COMISSAO) AS COMISSAO,
    MAX(PRODUTO.PRO_PIS) AS PISE_ALIQ_NOR,
    MAX(PRODUTO.PRO_COFINS) AS COFINSE_ALIQ_NOR,
    MAX(PRODUTO.PRO_FATOR_CONVERSAO) AS FAT_CONV,
    MAX(PRODUTO.PRO_ESTOQUE_MINIMO) AS QTD_IDEAL,
    MAX(NC.NC_NUMERO) AS COD_NCM,
    MAX(NC.NC_NUMERO_CEST) AS PERSONAL6,
    MAX(SUB_GRUPO.SUB_DESCRICAO) AS FAMILIA,
    MAX(GRUPOS.GRP_DESCRICAO) AS GRUPO,
    MAX(M.MA_DESCRICAO) AS CARACTERISTICAS,
    SUM(EES.EES_UP_SALDO) AS QTD,
    MAX(EES.EES_UP_CUSTO_MEDIO) AS CUSTO_MEDIO,
    MAX(CF.CST_IPI) AS IPI_CODIGO,
    MAX(CF.ALICOTA_IPI) AS IPI_CODIGO_VENDA,
    MAX(CF.CST_PIS) AS PIS_CODIGO,
    MAX(CF.PIS_ALICOTA) AS PIS_ALIQ_NOR,
    MAX(CF.CST_COFINS) AS COFINS_CODIGO,
    MAX(CF.COFINS_ALICOTA) AS COFINS_ALIQ_NOR,
    MAX(C.CS_NUM) AS ST,
    MAX(SUBSTRING (NO2.NO_FCOP from 1 for 3)) AS ELO
FROM PRODUTO
LEFT JOIN GRUPOS ON PRODUTO.GRP_CODIGO = GRUPOS.GRP_CODIGO
LEFT JOIN SUB_GRUPO ON PRODUTO.SUB_CODIGO = SUB_GRUPO.SUB_CODIGO
LEFT JOIN MARCA M ON PRODUTO.MA_CODIGO = M.MA_CODIGO 
LEFT JOIN NUM_CLASSIFICACAO NC ON PRODUTO.NC_CODIGO = NC.NC_CODIGO 
LEFT JOIN ESTOQUE_EMPRESA_SALDO EES ON PRODUTO.PRO_CODIGO = EES.PRO_CODIGO 
LEFT JOIN CLASSIFICACAO_FISCAL CF ON CF.NC_CODIGO = NC.NC_CODIGO AND CF.TF_CODIGO = '5' 
LEFT JOIN CST C ON C.CS_CODIGO = CF.CS_CODIGO 
LEFT JOIN NAT_OPERACAO NO2 ON NO2.NO_CODIGO = CF.NO_CODIGO 
GROUP BY PRODUTO.PRO_CODIGO;