SELECT
	CODIGO AS CODIGO,
	NOME AS NOME,
	ENDERECO AS ENDERECO,
	CEP AS CEP,
	BAIRRO AS BAIRRO,
	CIDADE AS CIDADE,
	ESTADO AS UF,
	FONE AS TELEFONE,
	FAX AS FAX,
	CGC AS CNPJ_CNPF,
	CONTATO AS CONTATO,
	FANTAZIA AS FANTASIA,
	COMPLEMENTO AS COMPLEMENTO,
	INSCEST AS IE_RG,
	EMAIL AS EMAIL
FROM FORNECEDOR
