SELECT
	P.CODIGO AS CODIGO,
	P.DESCRICAO AS DESCRICAO,
	--G.DESCRICAO AS GRUPO
	F.NOME AS FORNECEDOR,
	L.DESCRICAO AS GRUPO,
	T.DESCRICAO AS TAMANHO,
	T.DESCRICAO AS PERSONAL1,
	C.DESCRICAO AS COR,
	--E.QUANTIDADE AS QTD,
	P.PRCUSTO AS PRECO_CUSTO,
	P.PRVENDA AS PRECO_VENDA,
	P.VALORLUCRO AS MARGEM_LUCRO,
	P.UNIDADE AS UND,
	P.REFERENCIA AS COD_FABRICANTE,
	M.DESCRICAO AS FAMILIA,
	P.ATACADO AS PRECO_ATACADO,
	P.NCM AS COD_NCM,
	P.PIS AS PIS_CODIGO,
	P.COFINS AS COFINS_CODIGO,
	SUBSTRING(CFOP FROM 1 FOR 3) AS ELO,
	P.CFOP AS CF,
	P.CST AS ST,
	P.CEST AS PERSONAL6
FROM PRODUTO P
LEFT JOIN FORNECEDOR F ON F.CODIGO=P.FORNECEDOR 
LEFT JOIN LINHA L ON L.CODIGO=P.LINHA 
LEFT JOIN TAMANHO T ON T.CODIGO=P.TAMANHO 
LEFT JOIN COR C ON C.CODIGO=P.COR  
LEFT JOIN GRUPO G ON G.CODIGO=P.GRUPO 
LEFT JOIN MARCA M ON M.CODIGO=P.MARCA 
--LEFT JOIN ESTOQUE E ON E.REFERENCIA=P.CODIGO 