SELECT
    CAST (CADPRODUTOSVND.CODPRODUTO AS INTEGER) AS CODIGO,
    CADPRODUTOSVND.DSCPRODUTO AS DESCRICAO,
    CADPRODUTOSVND.CODBARRAS AS BARRAS,
    CADSEGMENTO.DSCSEGMENTO AS GRUPO,
    CADUNIDADES.UNIDADE AS UND,
    CADCATEGORIA.DSCCATEGORIA AS FAMILIA,
    CADPRODUTOSVND.QTDE_MINIMA AS QTD_IDEAL,
    CADPRODUTOSVND.COMPLEMENTO AS OBSERVACOES,
    CADPRODUTOSVND.PRECO_VENDA AS PRECO_VENDA,
    CADPRODUTOSVND.PRECO_COMPRA AS PRECO_CUSTO,
    CADPRODUTOSVND.MARGEM AS MARGEM_LUCRO,
    CAST (CADPRODUTOSVND.DTATUALIZACAO AS DATE) AS ALTERACAO_PRECO,
    CADPRODUTOSVND.QTDE_ESTOQUE AS QTD,
    CAST (CADPRODUTOSVND.DTCADASTRO AS DATE) AS DATA_CADASTRO,
    SUBSTRING (CADSITTRIBUTARIA.CODSITTRIB_NF FROM 1 FOR 1) AS OST,
    SUBSTRING (CADSITTRIBUTARIA.CODSITTRIB_NF FROM 2 FOR 3) AS ST,
    case when CADPRODUTOSVND.STATUSPROD = 'A' then 'Ativo' else 'Inativo' end as SITUACAO,
    CADPRODUTOSVND.COD_NCM AS COD_NCM,
    CADPRODUTOSVND.COD_CEST AS PERSONAL6
FROM CADPRODUTOSVND
LEFT JOIN CADSEGMENTO ON CADSEGMENTO.CODSEGMENT0 = CADPRODUTOSVND.CODSEGMENTO
LEFT JOIN CADUNIDADES ON CADUNIDADES.CODUNIDADE = CADPRODUTOSVND.CODUNIDADE
LEFT JOIN CADCATEGORIA ON CADCATEGORIA.CODCATEGORIA = CADPRODUTOSVND.CODCATEGORIA
LEFT JOIN CADSITTRIBUTARIA ON CADSITTRIBUTARIA.CODSITTRIB = CADPRODUTOSVND.CODSITTRIB