SELECT 
  P.IDPESSOA AS CODIGO
, P.NOME
, P.OBSERVACAO AS OBSERVACOES
, P.CONTATO
, P.CPF_CNPJ AS CNPJ_CNPF
, P.IE_RG
, P.EMAIL
, P.TELEFONE
, P.CELULAR
, P.FAX
, P.LOGRADOURO AS ENDERECO
, P.NUMERO
, P.COMPLEMENTO
, P.MUNICIPIO
, P.CEP
, P.BAIRRO
, TE2.SIGLA AS UF
--, TE.TITULO AS PERSONAL1
, TE.ENDERECO AS PERSONAL1
, TE.CEP AS PERSONAL2
, TE.PONTO_REFERENCIA AS PERSONAL3
, TE.NUMERO AS PERSONAL4
, TE.COMPLEMENTO AS PERSONAL5
, TB.NOME  AS PERSONAL6
, MAX (TE.ID)
FROM PGD.TB_PESSOAS P
RIGHT JOIN PGD.TB_FORNECEDOR TF ON TF.IDFORNECEDOR = P.IDPESSOA 
LEFT JOIN PGD.TB_ENDERECO TE ON TE.ID = P.ENDERECO_PADRAO_ID
LEFT JOIN PGD.TB_ESTADO_CIVIL TEC ON TEC.ID = P.ESTADO_CIVIL 
LEFT JOIN PGD.TB_ESTADO TE2 ON TE2.IDESTADO = P.IDESTADO
LEFT JOIN PGD.TB_BAIRRO TB ON TB.ID = TE.IDBAIRRO 
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
