SELECT 
  IDPRODUTO AS CODIGO
, CAST(P.ULTIMA_VENDA AS DATE) AS ULTIMA_VENDA
, CAST(P.DATA_CAD AS DATE) AS DATA_CADASTRO
, P.CUSTO AS PRECO_CUSTO
, P.PRECO AS PRECO_VENDA
, P.LUCRO AS MARGEM_LUCRO
, P.OBS AS OBSERVACOES
, P.DESCRICAO
, P.QUANTIDADE AS QTD
, P.QTD_MINIMA AS QTD_IDEAL
--, P.IPI AS ALIQ_IPI_VENDA
, P.COD_BARRA AS BARRAS
, P.TAMANHO
, P.PAF_IPPT AS IPPT
, CASE P.ATIVO WHEN TRUE THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.REFERENCIA AS COD_FABRICANTE
--, P.CSOSN AS ST
, P.COMISSAO
, P.VALIDADE_EM_DIAS as VALIDADE_DIAS
, P.DESCONTO_A_PARTIR_DE_QTD as QTD_PRECO_ATACADO
, P.PESO_BRUTO AS PESO
, SUBSTRING ((P.CFOP_SAIDA_LOCAL::VARCHAR) FROM 1 FOR 3) AS ELO
, P.CFOP_SAIDA_LOCAL AS CF
, SUBSTRING ((P.ICMS::VARCHAR) FROM 27 FOR 3) AS ST
, SUBSTRING ((P.ICMS::VARCHAR) FROM 45 FOR 1) AS OST
, SUBSTRING ((P.PIS::VARCHAR) FROM 13 FOR 2) AS PIS_CODIGO
--, SUBSTRING ((P.PIS::VARCHAR) FROM 54 FOR 1) AS PIS_ALIQ_NOR
, SUBSTRING ((P.COFINS::VARCHAR) FROM 16 FOR 2) AS COFINS_CODIGO
--, SUBSTRING ((P.COFINS::VARCHAR) FROM 63 FOR 1) AS COFINS_ALIQ_NOR
, SUBSTRING ((P.IPI_JSON::VARCHAR) FROM 13 FOR 2) AS IPI_CODIGO
, TN.CODIGO AS COD_NCM
, TC.CODIGO AS PERSONAL6
, TU.BREV AS UND
, TG.NOME AS GRUPO
, TPM.DESCRICAO AS FAMILIA
, TPE.DESCRICAO AS PERSONAL1
FROM PGD.TB_PRODUTO P
LEFT JOIN PGD.TB_NCM TN ON TN.ID = P.NCM
LEFT JOIN PGD.TB_CEST TC ON TC.ID = P.CEST_ID
LEFT JOIN PGD.TB_UNIDADE TU ON TU.ID = P.PAF_UNIDADE
LEFT JOIN PGD.TB_GRUPO_MERCADORIA TG ON TG.IDGRUPO = P.IDGRUPO
LEFT JOIN PGD.TB_PRODUTO_MARCA TPM ON TPM.ID = P.MARCA_ID
LEFT JOIN PGD.TB_PRODUTO_ESPECIE TPE ON TPE.ID = P.ESPECIE_ID