SELECT
    CLIENTE.ID AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLIENTE.NOME_FANTASIA AS FANTASIA,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.BAIRRO AS BAIRRO,
    CLIENTE.CIDADE AS CIDADE,
    CLIENTE.CEP AS CEP,
    CLIENTE.ESTADO AS UF,
    CLIENTE.TELEFONE AS TELEFONE,
    CLIENTE.CELULAR AS CELULAR,
    CLIENTE.FAX AS FAX,
    CLIENTE.INSCRICAO_RG AS IE_RG,
    CLIENTE.CNPJ_CPF AS CNPJ_CNPF,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.OBSERVACAO AS OBSERVACOES,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.LIMITE AS LIMITE_CREDITO
FROM CLIENTE
