SELECT
    PRODUTO.ID AS CODIGO,
    -- PRODUTO.ID AS COD_FABRICANTE,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.CODIGO AS BARRAS,
    PRODUTO.PRECO_VENDA AS PRECO_VENDA,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.CUSTO AS PRECO_CUSTO,
    PRODUTO.COMISSAO AS COMISSAO,
    PRODUTO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.ESTOQUE_MINIMO AS QTD_IDEAL,
    PRODUTO.IPI AS ALIQ_IPI_VENDA,
    PRODUTO.IPI_ENTRADA AS ALIQ_IPI,
    GRUPOS.DESCRICAO AS GRUPO,
    FABRICANTE.ID AS COD_FABRICANTE,
    FABRICANTE.DESCRICAO AS PERSONAL1,
    PRODUTO.APLICACAO AS OBSERVACOES,
    ESTOQUE.QUANTIDADE AS QTD
FROM PRODUTO
LEFT JOIN GRUPOS ON GRUPOS.ID = PRODUTO.ID_GRUPO
LEFT JOIN FABRICANTE ON FABRICANTE.ID = PRODUTO.ID_FABRICANTE
LEFT JOIN ESTOQUE ON ESTOQUE.id_produto = PRODUTO.ID
