SELECT
  CLIENTE.ID_CLIENTE AS CODIGO,
  CLIENTE.NOME AS NOME,
  CLIENTE.CPFCNPJ AS CNPJ_CNPF,
  CLIENTE.INSCRICAO_RG AS IE_RG,
  ENDERECO_CLIENTE.CEP,
  ENDERECO_CLIENTE.ENDERECO,
  ENDERECO_CLIENTE.NUMERO,
  ENDERECO_CLIENTE.BAIRRO,
  ENDERECO_CLIENTE.COMPLEMENTO,
  CIDADE.NOME AS CIDADE,
  ESTADO.SIGLA AS UF

FROM CLIENTE
LEFT JOIN ENDERECO_CLIENTE ON CLIENTE.ID_CLIENTE = ENDERECO_CLIENTE.ID_CLIENTE
LEFT JOIN CIDADE ON ENDERECO_CLIENTE.ID_CIDADE = CIDADE.iD_CIDADE
LEFT JOIN ESTADO ON ENDERECO_CLIENTE.ID_ESTADO = ESTADO.ID_ESTADO