SELECT 
  PRODUTO.ID_PRODUTO AS CODIGO,
  CODIGO_PRODUTO.CODIGO AS BARRAS,
  GRUPO.DESCRICAO AS GRUPO,
  ESTOQUE.QTD_ATUAL AS QTD,
  UNIDADE_MEDIDA.UNIDADE AS UND,
  PRODUTO.DESCRICAO,
  PRODUTO.UNITARIO AS PRECO_VENDA,
  PRODUTO.CUSTO AS PRECO_CUSTO,
  PRODUTO.FATOR_CONVERSAO_ENTRADA AS FT_CONV,
  PRODUTO.MARGEM_LUCRO AS MARGEM_LUCRO,
  NCM.NCM AS COD_NCM,
  CEST.CEST AS PERSONAL6,
  CSOSN.CSOSN AS ST
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.ID_GRUPO = GRUPO.ID_GRUPO
LEFT JOIN CODIGO_PRODUTO ON PRODUTO.ID_PRODUTO = CODIGO_PRODUTO.ID_PRODUTO
LEFT JOIN ESTOQUE ON PRODUTO.ID_PRODUTO = ESTOQUE.ID_PRODUTO
LEFT JOIN UNIDADE_MEDIDA ON PRODUTO.ID_UNIDADE_MEDIDA = UNIDADE_MEDIDA.ID_UNIDADE_MEDIDA
LEFT JOIN GRUPO_FISCAL ON PRODUTO.ID_GRUPO_FISCAL = GRUPO_FISCAL.ID_GRUPO_FISCAL
LEFT JOIN NCM ON GRUPO_FISCAL.ID_NCM = NCM.ID_NCM
LEFT JOIN CEST ON GRUPO_FISCAL.ID_CEST = CEST.ID_CEST
LEFT JOIN CSOSN ON GRUPO_FISCAL.ID_CSOSN = CSOSN.ID_CSOSN