SELECT
    CODIGO AS CODIGO,
    CODIGO_BARRAS AS BARRAS,
    DESCRICAO AS DESCRICAO,
    UNIDADE AS UND,
    ESTOQUE AS QTD,
    PESOLIQ AS PESO,
    PCOMPRA AS PRECO_CUSTO,
    PMEDIO AS CUSTO_MEDIO,
    PVISTA AS PRECO_VENDA,
    CSOSN AS ST,
    OBSERVACOES AS OBSERVACOES,
    NCM AS COD_NCM,
    CEST AS PERSONAL6,
    COD_FABRICANTE AS COD_FABRICANTE,
    DATAULTCOMPRA AS ULTIMA_COMPRA,
    DATAULTVENDA AS ULTIMA_VENDA
FROM PRODUTOS