SELECT 
  F.ID AS CODIGO
,CASE WHEN F.DF1 = '' OR F.DF1 IS NULL THEN F.CODIGO1 ELSE F.DF1 END AS CNPJ_CNPF
,CASE WHEN F.DF3 = '' OR F.DF3 = 'ISENTO' OR F.DF3 IS NULL THEN F.DF2 ELSE F.DF3 END AS IE_RG
, F.NOME
, F.APELIDO AS FANTASIA
, F.TEL1 AS TELEFONE
, F.TEL2 AS PERSONAL1
, F.FAX1 AS FAX
, F.EMAIL
, F.OBS AS OBSERVACOES	
, E.CEP 
, E.LOGRADOURO AS ENDERECO
, E.NUMERO 
, E.COMPLEMENTO 
, E.BAIRRO 
, E.CIDADE 
, E.ESTADO AS UF
, E.TEL AS PERSONAL2
, CO.CELULAR 
, CO.NOME AS CONTATO
FROM TB_PARCEIRO F
LEFT JOIN TB_PARCEIRO_ENDERECO E ON E.ID_PARCEIRO = F.ID AND E.ID_TIPO_ENDERECO = 1
LEFT JOIN TB_PARCEIRO_CONTATO CO ON CO.ID_PARCEIRO = F.ID AND CO.TIPO =1
WHERE ID_PARCEIRO_TIPO = 2;