SELECT 
  P.ID AS CODIGO
, CASE P.DELETADO WHEN '0' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P.CODIGO1 AS BARRAS
, P.CODIGO2 AS COD_FABRICANTE
, P.DESCRICAO
, P.PRECO_VENDA AS PRECO_VENDA
--, P.PRECO_REDE AS PRECO_VENDA
, P.PRECOCUSTOREAL AS PRECO_CUSTO
--, P.PRECO_COMPRA AS PRECO_CUSTO
, P.MARKUP AS MARGEM_LUCRO
, P.PESO_BRUTO AS PESO
, P.ESTOQUEQUANTIDADE AS QTD
, P.ESTOQUEQTDMINIMA AS QTD_IDEAL
, P.IPPT
, P.ID_CEST AS PERSONAL6
--, P.CEST AS PERSONAL6
--, P.ID_SITUACAO_TRIBUTARIA_PIS
--, P.ID_SITUACAO_TRIBUTARIA_COFINS
--, P.ID_SITUACAO_TRIBUTARIA_IPI
--, P.ID_SITUACAO_TRIBUTARIA AS ELO
--, P.IMP_PIS
--, P.IMP_COFINS
, LEFT (U.DESCRICAO, 2) AS UND
, GR.DESCRICAO AS GRUPO
, SG.DESCRICAO AS FAMILIA
, GR2.DESCRICAO AS CARACTERISTICAS
, CF.DESCRICAO AS COD_NCM
, TRI3.CFOP AS CF
, LEFT (TRI3.CFOP,3) AS ELO
, TRI2.ALIQUOTAPIS AS PIS_ALIQ_NOR
, TRI2.ALIQUOTACOFINS AS COFINS_ALIQ_NOR
, TRI2.ALIQUOTAIPI AS ALIQ_IPI_VENDA
, TRI2.SITUACAO_TRIBUTARIA_ORIGEM AS OST
, TRI3.CSTPIS AS PIS_CODIGO
, TRI3.CSTCOFINS AS COFINS_CODIGO
, TRI3.CSTIPI AS IPI_CODIGO_VENDA
, TRI3.CSTICMS AS ST
FROM TB_COMERCIO_PRODUTO P
LEFT JOIN TB_COMERCIO_PRODUTO_UNIDADE U ON U.ID = P.ID_UNIDADE
LEFT JOIN TB_COMERCIO_PRODUTO_GRUPO1 GR ON GR.ID = P.ID_GRUPO1
LEFT JOIN TB_COMERCIO_PRODUTO_GRUPO1_SUB SG ON SG.ID = P.ID_GRUPO1_SUB AND SG.ID_GRUPO1 = GR.ID
LEFT JOIN TB_COMERCIO_PRODUTO_GRUPO2 GR2 ON GR2.ID = P.ID_GRUPO2
LEFT JOIN TB_COMERCIO_CLASSIFICACAO_FISCAL CF ON CF.ID = P.ID_CLASSIFICACAO_FISCAL
LEFT JOIN TB_COMERCIO_SEQUENCIA_FISCAL_ALIQUOTASXPRODUTO TRI ON TRI.PRODUTOID = P.ID AND TRI.SEQUENCIAFISCALALIQUOTASID = 1 --AQUI VERIFICA E AJUSTA A SEQUENCIA FISCAL DO TRIBUTO, APARENTEMENTE 1 É O PADRÃO.
LEFT JOIN TB_COMERCIO_SEQUENCIA_FISCAL_ALIQUOTAS TRI2 ON TRI2.ID = TRI.SEQUENCIAFISCALALIQUOTASID
LEFT JOIN TB_COMERCIO_SEQUENCIA_FISCAL_LOCAL TRI3 ON TRI3.ID = TRI2.SEQUENCIAFISCALID_LOCAL