SELECT
    CONTATO.ID AS CODIGO,
    CONTATO.NOME AS NOME,
    CONTATO.RAZAO_SOCIAL AS FANTASIA,
    CONTATO.CONTATO AS CONTATO,
    CONTATO.CNPJ_CPF AS CNPJ_CNPF,
    CONTATO.INSC_RG AS IE_RG,
    CONTATO.ENDERECO AS ENDERECO,
    CONTATO.COMPLEMENTO AS COMPLEMENTO,
    CONTATO.NUM_END AS NUMERO,
    CONTATO.BAIRRO_END AS BAIRRO,
    CODCIDADE.DESCRICAO AS CIDADE,
    CODCIDADE.UF AS UF,
    CONTATO.CEP_END AS CEP,
    CONTATO.TELEFONE AS TELEFONE,
    CONTATO.TELEFAX AS FAX,
    CONTATO.CELULAR AS CELULAR,
    CONTATO.EMAIL AS EMAIL,
    CONTATO.FILIACAO_PAI AS PAI,
    CONTATO.FILIACAO_MAE AS MAE,
    CONTATO.LIMITE_CRED AS LIMITE_CREDITO,
    CONTATO.OBSERVACOES AS OBSERVACOES,
    CAST (CONTATO.DATA_CAD AS DATE) AS CADASTRO,
    CAST (CONTATO.DATA_NASC AS DATE) AS NASCIMENTO
FROM CONTATO
LEFT JOIN CODCIDADE ON CODCIDADE.CODIGO = CONTATO.CODCIDADE
WHERE CONTATO.TIPO_CONTATO = 'C' ---CLIENTES
