SELECT 
       PS.COD_PRODUTO AS CODIGO
      ,PS.DES_PRODUTO AS DESCRICAO
      ,PS.COD_UNIDADE_MEDIDA AS UND
      ,GPS.DES_GRUPO AS GRUPO
      ,SGPS.DES_SUB_GRUPO AS FAMILIA
      ,E.QTD_ATUAL AS QTD
      ,TP.VLR_PRECO_BASE AS PRECO_VENDA
      ,SUBSTRING (PS.COD_SITUACAO_TRIBUTARIA, 1,1) AS OST
      ,SUBSTRING (PS.COD_SITUACAO_TRIBUTARIA, 2, 4) AS ST
      ,PS.OBS_PRODUTO AS OBSERVACOES
      ,CAST (PS.DAT_CADASTRO AS DATE) AS DATA_CADASTRO
      ,CAST (E.DAT_ULTIMA_ENTRADA AS DATE) AS ULTIMA_COMPRA
      ,CAST (E.DAT_ULTIMA_SAIDA AS DATE) AS ULTIMA_VENDA
      ,CAST (TP.DAT_ATUALIZACAO_PRECO AS DATE) AS ALTERACAO_PRECO
      ,case when PS.SIT_PRODUTO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
  FROM hscorp.dbo.PRODUTOS_SERVICOS AS PS
LEFT JOIN hscorp.dbo.GRUPOS_PRODUTOS_SERVICOS GPS ON PS.COD_SUB_GRUPO = GPS.COD_GRUPO
LEFT JOIN hscorp.dbo.SUB_GRUPOS_PRODUTOS_SERVICOS SGPS ON PS.COD_SUB_GRUPO = SGPS.COD_SUB_GRUPO
LEFT JOIN hscorp.dbo.ITENS_VALIDADE_TAB_PR TP ON PS.COD_PRODUTO = TP.COD_PRODUTO
LEFT JOIN hscorp.dbo.ESTOQUES E ON PS.COD_PRODUTO = E.COD_PRODUTO