SELECT
	C.IDCODIGO_CLIENTE AS CODIGO,
	C.RAZAO_CLIENTE AS NOME,
	C.FANTASIA_CLIENTE AS FANTASIA,
	C.ENDERECO_CLIENTE AS ENDERECO,
	C.BAIRRO_CLIENTE AS BAIRRO,
	C.UF_CLIENTE AS UF,
	C.CEP_CLIENTE AS CEP,
	C.NASCIMENTO_CLIENTE AS NASCIMENTO,
	C.PAI_CLIENTE AS PAI,
	C.MAE_CLIENTE AS MAE,
	C.TELEFONE_CLIENTE AS TELEFONE,
	C.FAX_CLIENTE AS FAX,
	C.CELULAR_CLIENTE AS CELULAR,
	C.CNPJ_CLIENTE AS CNPJ_CNPF,
	CASE WHEN C.RG_CLIENTE = '' OR C.RG_CLIENTE IS NULL THEN C.INSCRICAO_CLIENTE ELSE C.RG_CLIENTE END AS IE_RG,
	C.INSCMUNICIPAL_CLIENTE AS IM,
	C.OBSEVACAO_CLIENTE AS OBSERVACOES,
	C.EMAIL_CLIENTE AS EMAIL,
	C.CONTATO_CLIENTE AS CONTATO,
	C.TRABALHO_CLIENTE AS LOCTRA,
	C.TRABALHO_FUNCAO_CLIENTE AS PROFISSAO,
	C.CREDITO_CLIENTE AS LIMITE_CREDITO,
	C.TELEFONE02_CLIENTE AS PERSONAL1,
	COALESCE(C.DTCADASTRO_CLIENTE, CURRENT_DATE) AS CADASTRO,
	C.ULTIMACOMPRA_CLIENTE AS ULTIMA_VENDA,
	CI.DESCRICAO_CIDADE AS CIDADE
FROM
	CLIENTES C
LEFT JOIN CIDADES CI ON CI.IDCODIGO_CIDADE = C.IDCIDADE_CLIENTE 
WHERE C.TIPO_CLIENTE = '0'