SELECT CLIENTES.CLI_CODIGO AS CODIGO,
CLIENTES.CLI_DATACADASTRO AS CADASTRO,
CLIENTES.CLI_NOME AS NOME,
CLIENTES.CLI_APELIDO AS FANTASIA,
CLIENTES.CLI_ENDERECO AS ENDERECO,
CLIENTES.CLI_NUMERO AS NUMERO,
CLIENTES.CLI_COMPLEMENTO AS COMPLEMENTO,
CLIENTES.CLI_BAIRRO AS BAIRRO,
CLIENTES.CLI_CIDADE AS CIDADE,
CLIENTES.CLI_UF AS UF,
CLIENTES.CLI_FONE1 AS TELEFONE,
CLIENTES.CLI_FONE2 AS CELULAR,
CLIENTES.CLI_FONEFAX AS FAX,
CLIENTES.CLI_CPF_CNPJ AS CNPJ_CNPF,
CLIENTES.CLI_RG_IE_IM_PR AS IE_RG,
CLIENTES.CLI_DATANASCIMENTO AS NASCIMENTO,
CLIENTES.CLI_LIMITECREDITO AS LIMITE_CREDITO,
CLIENTES.CLI_EMAIL AS EMAIL
FROM CLIENTES


