SELECT FORNECEDOR.FOR_CODIGO AS CODIGO,
FORNECEDOR.FOR_RAZAOSOCIAL AS NOME,
FORNECEDOR.FOR_NOMEFANTASIA AS FANTASIA,
FORNECEDOR.FOR_IE_RG AS IE_RG,
FORNECEDOR.FOR_ENDERECO AS ENDERECO,
FORNECEDOR.FOR_NUMERO AS NUMERO,
FORNECEDOR.FORCOMPLEMENTO AS COMPLEMENTO,
FORNECEDOR.FOR_BAIRRO AS BAIRRO,
FORNECEDOR.FOR_CIDADE AS CIDADE,
FORNECEDOR.FOR_UF AS UF,
FORNECEDOR.FOR_CEP AS CEP,
FORNECEDOR.FOR_FONE1 AS TELEFONE,
FORNECEDOR.FOR_FONE2 AS CELULAR,
FORNECEDOR.FOR_FONEFAX AS FAX,
FORNECEDOR.FOR_EMAIL AS EMAIL
FROM FORNECEDOR

