SELECT PRODUTOS.PRO_CODIGO AS CODIGO,
PRODUTOS.PRO_CODBARRAS AS BARRAS,
PRODUTOS.PRO_CODPRODFORNEC AS COD_FABRICANTE,
PRODUTOS.PRO_COD_NBMSH AS COD_NCM,
PRODUTOS.PRO_DESCRICAO AS DESCRICAO,
PRODUTOS.PRO_UNIDADE AS UND,
GESTOQUE.GRU_NOMEGRUPOESTOQUE AS GRUPO,
PRODUTOS.PRO_VALORCUSTO1N AS PRECO_CUSTO,
PRODUTOS.PRO_PRVENDAVISTA AS PRECO_VENDA,
PRODUTOS.PRO_ST_NF AS ST,
PRODUTOS.CEST AS PERSONAL6,
ESTOQUE.ESTOQUE1N AS QTD
FROM PRODUTOS
LEFT JOIN GESTOQUE ON PRODUTOS.PRO_CODGRUPO=GESTOQUE.GRU_CODIGO
LEFT JOIN ESTOQUE ON PRODUTOS.PRO_CODIGO=ESTOQUE.CODIGOPRODUTO
