SELECT 
  P.CODIGO
, P.NOME
, P.NUM_CPF_CNPJ AS CNPJ_CNPF
, P.NUM_RG AS IE_RG
, COALESCE (P.DAT_INCLUIDO, CURRENT_DATE) AS CADASTRO
, P.OBS ||' - '|| P.MENSAGEM_OPERADOR AS OBSERVACOES
, PF.SEXO
, PF.DAT_NASCIMENTO AS NASCIMENTO
, PJ.NOM_FANTASIA AS FANTASIA
, PJ.NUM_IM AS IM
, C.CONTATO 
, E2.ENDERECO 
, E2.NUMERO 
, E2.COMPLEMENTO 
, E2.BAIRRO 
, E2.CIDADE 
, E2.UF 
, E2.CEP
, MAX (E.EMAIL) AS EMAIL
FROM PESSOA P
LEFT JOIN PESSOA_PF PF ON P.EMPRESA_PESSOA_ID = PF.EMPRESA_PESSOA_ID AND P.PESSOA_ID = PF.PESSOA_ID
LEFT JOIN PESSOA_PJ PJ ON P.EMPRESA_PESSOA_ID = PJ.EMPRESA_PESSOA_ID AND P.PESSOA_ID = PJ.PESSOA_ID
LEFT JOIN CONTATO C ON P.EMPRESA_PESSOA_ID = C.EMPRESA_PESSOA_ID AND P.PESSOA_ID = C.PESSOA_ID
LEFT JOIN ENDERECO E2 ON P.EMPRESA_PESSOA_ID = E2.EMPRESA_PESSOA_ID AND P.PESSOA_ID = E2.PESSOA_ID AND E2.TIPO_ENDERECO <> 3
LEFT JOIN EMAIL E ON P.EMPRESA_PESSOA_ID = E.EMPRESA_PESSOA_ID AND P.PESSOA_ID = E.PESSOA_ID
WHERE P.CLASSE = '1'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
