SELECT
  P.PRODUTO_ID AS CODIGO
, P.DESCRICAO
, P.QTD_CAIXA AS FAT_CONV
, P.OBSERVACAO AS OBSERVACOES
, COALESCE(P.DAT_INCLUIDO, CURRENT_DATE) AS CADASTRO
, P.CODIGO_NCM AS COD_NCM
, P.CODIGO_ANP AS COD_ANP
, P.CODIGO_CEST AS PERSONAL6
, P.CTO AS OST
, P.CST_PIS_COFINS_ENTRADA AS PISE_CODIGO
, P.CST_PIS_COFINS_ENTRADA AS COFINSE_CODIGO
, P.CST_PIS_COFINS AS PIS_CODIGO
, P.CST_PIS_COFINS AS COFINS_CODIGO
, P.CST_IPI AS IPI_CODIGO_VENDA
, CASE P.UND_COMERCIAL_COMPRA
	WHEN '1' THEN 'CX'
	WHEN '2' THEN 'DUZ'
	WHEN '3' THEN 'KG'
	WHEN '4' THEN 'LTS'
	WHEN '5' THEN 'M³'
	WHEN '6' THEN 'MT'
	WHEN '7' THEN 'UN'
  END AS UND_COMPRA
, CASE P.UND_VENDA
	WHEN '1' THEN 'CX'
	WHEN '2' THEN 'DUZ'
	WHEN '3' THEN 'KG'
	WHEN '4' THEN 'LTS'
	WHEN '5' THEN 'M³'
	WHEN '6' THEN 'MT'
	WHEN '7' THEN 'UN'
  END AS UND
, CASE P.CT
	WHEN '1' THEN 'TT'
	WHEN '2' THEN 'FF'
	WHEN '3' THEN 'II'
	WHEN '4' THEN 'NN'
	WHEN '5' THEN 'TT'
  END AS ELO
, CASE P.CT
	WHEN '1' THEN '00'
	WHEN '2' THEN '60'
	WHEN '3' THEN '40'
	WHEN '4' THEN '40'
	WHEN '5' THEN '20'
  END AS ST  
, PE.PER_COMISSAO AS COMISSAO
, PE.PRC_CUSTO AS PRECO_CUSTO
, PE.MARKUP AS MARGEM_LUCRO
, PE.PRC_VEN_VISTA AS PRECO_VENDA
, PE.PRC_VEN_PRAZO AS PERSONAL1
, PE.QTD_ESTOQUE AS QTD
, PE.QTD_MINIMA AS QTD_IDEAL
, CASE PE.SN_ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
, P2.DESCRICAO AS GRUPO
, P1.DESCRICAO AS FAMILIA
, MAX(CBP.COD_BARRA) AS BARRAS
FROM PRODUTO P 
LEFT JOIN PRODUTO_EMPRESA PE ON P.PRODUTO_ID  = PE.PRODUTO_ID
LEFT JOIN PRODUTO_NIVEL2 P2 ON P2.PRODUTO_NIVEL2_ID = P.PRODUTO_NIVEL2_ID
LEFT JOIN DESPESA_NIVEL1 P1 ON P1.DESPESA_NIVEL1_ID  = P2.PRODUTO_NIVEL2_ID 
LEFT JOIN COD_BARRA_PRODUTO CBP ON CBP.PRODUTO_ID = P.PRODUTO_ID AND CBP.TIPO_GTIN = 'GTIN 13'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
