SELECT
    FORNECEDOR.CODIGO AS CODIGO,
    FORNECEDOR.NOME AS NOME,
    FORNECEDOR.FANTASIA AS FANTASIA,
    FORNECEDOR.CONTATO AS CONTATO,
    FORNECEDOR.CPF_CNPJ AS CNPJ_CNPF,
    FORNECEDOR.INS_ESTADUAL AS IE_RG,
    FORNECEDOR.EMAIL AS EMAIL,
    FORNECEDOR.LOGRADOURO AS ENDERECO,
    FORNECEDOR.NUMERO AS NUMERO,
    FORNECEDOR.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDOR.BAIRRO AS BAIRRO,
    FORNECEDOR.CIDADE AS CIDADE,
    FORNECEDOR.ESTADO AS UF,
    FORNECEDOR.CEP AS CEP,
    FORNECEDOR.TEL_RESID AS TELEFONE,
    FORNECEDOR.CELULAR AS CELULAR,
    FORNECEDOR.OBS AS OBSERVACOES
FROM FORNECEDOR
