SELECT
    substring (PRODUTO_SERVICO.CODIGO from 3 for 8) AS CODIGO,
    PRODUTO_SERVICO.NOME AS DESCRICAO,
    PRODUTO_SERVICO.CODBARRA AS BARRAS,
    PRODUTO_SERVICO.UN_TRIB AS UND,
    PRODUTO_SERVICO.CST AS ST,
    PRODUTO_SERVICO.PESOLIQUIDO AS PESO,
    GRUPO_PRODUTO.DESCRICAO AS GRUPO,
    PRODUTO_SERVICO.FORNECEDOR AS FORNECEDOR,
    PRODUTO_SERVICO.FABRICANTE AS CARACTERISTICAS,
    PRODUTO_SERVICO.ESTOQUEATUAL AS QTD,
    PRODUTO_SERVICO.ESTOQUEIDEAL AS QTD_IDEAL,
    PRODUTO_SERVICO.CUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTO_SERVICO.PRECO_COMPRA AS PRECO_CUSTO,
    PRODUTO_SERVICO.MARGEMLUCRO AS MARGEM_LUCRO,
    PRODUTO_SERVICO.PRECO_VENDA AS PRECO_VENDA,
    PRODUTO_SERVICO.OBS AS OBSERVACOES,
    PRODUTO_SERVICO.NUM_FABRIC AS COD_FABRICANTE,
    PRODUTO_SERVICO.CODNCM AS COD_NCM,
    PRODUTO_SERVICO.CODCEST AS PERSONAL6,
    PRODUTO_SERVICO.ULTIMOREAJUSTE AS ALTERACAO_PRECO,
    PRODUTO_SERVICO.DATA_CADASTRO AS DATA_CADASTRO
FROM PRODUTO_SERVICO
LEFT JOIN grupo_produto ON grupo_produto.codigo = PRODUTO_SERVICO.GRUPO
