SELECT
    MATERIAL.ID_MAT AS CODIGO,
    MATERIAL.BAR_MAT AS BARRAS,
    MATERIAL.DESCRI_MAT AS DESCRICAO,
    MATERIAL.UND_MAT AS UND,
    MATERIAL.NOME_FOR AS FORNECEDOR,
    GRUPO.DESCRI_GRUPO AS GRUPO,
    SUB_GRUPO.DESCRI_SUB AS FAMILIA,
    MATERIAL.QUA_MAT AS QTD,
    MATERIAL.PCUSTO_MAT AS PRECO_CUSTO,
    MATERIAL.PER_MAT AS MARGEM_LUCRO,
    MATERIAL.PVENDA_MAT AS PRECO_VENDA,
    MATERIAL.COD_CST AS ST,
    MATERIAL.NCM AS COD_NCM,
    MAX (CEST.CEST) AS PERSONAL6
FROM MATERIAL
LEFT JOIN GRUPO ON GRUPO.ID_GRUPO = MATERIAL.ID_GRUPO_FK
LEFT JOIN SUB_GRUPO ON SUB_GRUPO.ID_SUB = MATERIAL.ID_SUB_FK
LEFT JOIN CEST ON CEST.NCM = MATERIAL.NCM
WHERE MATERIAL.DESCRI_MAT <> ''
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13