SELECT 
       [NOME_CLIENTE] AS NOME
      ,[APELIDO] AS FANTASIA
      ,[CPF_CNPJ] AS CNPJ_CNPF
      ,[RG_INSCRICAO] AS IE_RG
      ,[ENDERECO_RES] AS ENDERECO
      ,[NUMERO_RES] AS NUMERO
      ,[BAIRRO_RES] AS BAIRRO
      ,[CIDADE_RES] AS CIDADE
      ,[ESTADO_RES] AS UF
      ,[TELEFONE_RES] AS TELEFONE
      ,[REFERENCIA_RES] AS COMPLEMENTO
      ,[E_MAIL_RES] AS EMAIL
      ,[CEP_RES] AS CEP
  FROM [wfcom].[dbo].[vw_cliente_completo]
