select CLIENTES.CLIENTE AS CODIGO,
CLIENTES.NOME,
CLIENTES.FANTASIA,
CLIENTES.ENDERECO,
CLIENTES.NUMERO,
CLIENTES.COMPLEMENTO,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.CEP,
CLIENTES.ESTADO AS UF,
CLIENTES.TELEFONE,
CLIENTES.DATA_CLIENTE AS CADASTRO,
CLIENTES.CELULAR,
CASE WHEN CLIENTES.CGC='' THEN CLIENTES.CPF
ELSE CLIENTES.CGC END AS CNPJ_CNPF,
CLIENTES.INSC_EST AS IE_RG,
CLIENTES.E_MAIL AS EMAIL,
CLIENTES.ULTIMA_COMPRA
FROM CLIENTES


