SELECT FORNECEDORES.FORNECEDOR AS CODIGO,
FORNECEDORES.NOME,
FORNECEDORES.RAZAO_SOCIAL AS FANTASIA,
FORNECEDORES.CONTATO,
FORNECEDORES.BAIRRO,
FORNECEDORES.ENDERECO,
FORNECEDORES.NUMERO,
FORNECEDORES.COMPLEMENTO,
FORNECEDORES.TELEFONE,
FORNECEDORES.CIDADE,
FORNECEDORES.CEP,
FORNECEDORES.E_MAIL AS EMAIL,
FORNECEDORES.ESTADO AS UF,
FORNECEDORES.CELULAR,
FORNECEDORES.FAX,
CASE WHEN FORNECEDORES.CGC='' THEN FORNECEDORES.CPF
ELSE FORNECEDORES.CGC END AS CNPJ_CNPF,
FORNECEDORES.INSC_EST AS IE_RG,
FORNECEDORES.OBS AS OBSERVACOES
FROM FORNECEDORES


