SELECT
PKCODFORN AS CODIGO
,NOMEFANTASIA AS FANTASIA
,RAZAOSOCIAL AS NOME
,ENDERECO
,NUM  AS NUMERO
,COMPLEMENTO
,CEP
,BAIRRO
,TBCIDADE.NMCID AS CIDADE
,TBCIDADE.UFCID AS UF
,FONE1 AS TELEFONE
,FONE2 AS CELULAR
,FAX
,CNPJCPF AS CNPJ_CNPF
,INSCESTRG AS IE_RG
,EMAIL
,OBS AS OBSERVACOES
FROM tbfornecedor
LEFT JOIN TBCIDADE ON tbfornecedor.fkcodcid = TBCIDADE.PKCODCID
