SELECT 
TBPRODUTO.PKCODPROD AS CODIGO,
TBPRODUTO.REFERENCIA AS COD_FABRICANTE,
CAST(TBPRODUTO.DATACAD AS DATE)AS DATA_CADASTRO,
TBPRODUTO.CODBARRAS AS BARRAS,
TBPRODUTO.NOME as descricao,
TBPRODUTO.descricaogeral || ' - ' || TBPRODUTO.observacao AS OBSERVACOES,
TBCLASFISCAL.CODIGO AS COD_NCM,
tbunidade.sigla AS UF,
TBSITTRIBUTARIA.CODIGO AS ST,
TBPRODUTO.VALORVENDA AS PRECO_VENDA,
TBPRODUTO.valorcusto AS PRECO_CUSTO,
TBPRODUTO.customedio AS CUSTO_MEDIO,
TBPRODUTO.margemlucro AS MARGEM_LUCRO,
--CAST(TBPRODUTO.aliqicms AS INTEGER) AS ELO,
LEFT (tbnaturezaop.cfop,3) AS ELO,
tbnaturezaop.cfop AS CF,
TBPRODUTO.dataultcompra AS ULTIMA_COMPRA,
TBPRODUTO.valorcomissao AS COMISSAO,
TBPRODUTO.estoqueatu AS QTD,
TBPRODUTO.estoquemin AS QTD_IDEAL,
TBPRODUTO.aliqipi AS ALIQ_IPI_VENDA,
TBPRODUTO.aliquotapis AS PIS_ALIQ_NOR,
TBPRODUTO.cstpis AS PIS_CODIGO,
TBPRODUTO.aliquotacofins AS COFINS_ALIQ_NOR,
TBPRODUTO.cstcofins AS COFINS_CODIGO,
TBPRODUTO.cstpisentradas AS PISE_CODIGO,
TBPRODUTO.cstcofinsentradas AS COFINSE_CODIGO,
TBPRODUTO.pesobruto AS PESO,

TBPRODUTO.CEST AS PERSONAL6
FROM TBPRODUTO
LEFT JOIN TBCLASFISCAL ON TBPRODUTO.FKCODCLASFISCAL=TBCLASFISCAL.PKCODCLASFISCAL
LEFT JOIN TBSITTRIBUTARIA ON TBPRODUTO.FKCODSITTRIB=TBSITTRIBUTARIA.PKCODSITTRIB
LEFT JOIN tbunidade ON tbunidade.pkcoduni = TBPRODUTO.fkcoduni
LEFT JOIN tbnaturezaop ON tbnaturezaop.pkcodnatop = tbproduto.fknaturezaop
