SELECT TCLIENTE.CONTROLE AS CODIGO,
TCLIENTE.CLIENTE AS NOME,
TCLIENTE.ENDERECO,
TCLIENTE.COMPLEMENTO,
TCLIENTE.BAIRRO,
TCLIENTE.CIDADE,
TCLIENTE.UF,
TCLIENTE.CEP,
COALESCE(TCLIENTE.RG,TCLIENTE.IE) AS IE_RG,
COALESCE(TCLIENTE.CPF,TCLIENTE.CNPJ) AS CNPJ_CNPF,
TCLIENTE.DATANASCIMENTO AS NASCIMENTO,
CAST(TCLIENTE.DATAHORACADASTRO AS DATE) AS CADASTRO,
TCLIENTE.TELEFONE,
TCLIENTE.CELULAR,
TCLIENTE.EMAIL,
TCLIENTE.FANTASIA,
TCLIENTE.NUMERO
FROM TCLIENTE



