SELECT
	CLI_CODIGO AS CODIGO,
	CLI_NOME AS NOME,
	CASE WHEN CLIENTES.CLI_CGC = '' OR CLIENTES.CLI_CGC  IS NULL THEN CLIENTES.CLI_CPF  ELSE CLIENTES.CLI_CGC END AS CNPJ_CNPF,
	CASE WHEN CLIENTES.CLI_NRG = '' OR CLIENTES.CLI_NRG  IS NULL THEN CLIENTES.CLI_INSC_EST ELSE CLIENTES.CLI_NRG END AS IE_RG,
	CLI_ENDERECO AS ENDERECO,
	CLI_NUM_END AS NUMERO,
	CLI_BAIRRO AS BAIRRO,
	CLI_TELEFONE AS TELEFONE,
	CLI_CEP AS CEP,
	CLI_NASC AS NASCIMENTO,
	CLI_PAI AS PAI,
	CLI_MAE AS MAE,
	CLI_OBS AS OBSERVACOES,
	C.CID_NOME AS CIDADE,
	C.CID_UF AS UF,
	CLI_FAX AS FAX,
	CLI_EMAIL AS EMAIL,
	CLI_FANTASIA AS FANTASIA
FROM CLIENTES
LEFT JOIN CIDADE C ON CLIENTES.CLI_CID_CODIGO=C.CID_CODIGO 