SELECT
	PRO_CODIGO AS CODIGO,
	PRO_COD_FAB AS COD_FABRICANTE,
	PRO_NOME AS DESCRICAO,
	PRO_COD_BARRA AS BARRAS,
	PRO_PRECO_CUSTO AS PRECO_CUSTO,
	PRO_LUCRO AS MARGEM_LUCRO,
	PRO_VENDA AS PRECO_VENDA,
	PRO_ESTOQUE AS QTD,
	PRO_ICM AS ELO,
	PRO_UNI AS UND,
	CASE PRODUTOS.PRO_ATIVO WHEN '1' THEN 'Ativo' WHEN '2' THEN 'Inativo' END AS SITUACAO,
	PRO_OBS AS OBSERVACOES,
	PRO_FISCAL AS COD_NCM,
	PRO_SIT_TRIB AS ST,
	PRO_CEST AS PERSONAL6
FROM PRODUTOS