SELECT
  FORNECEDORES.CODIGO AS CODIGO,
  FORNECEDORES.NOME AS NOME,
  FORNECEDORES.FANTASIA AS FANTASIA,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
  FORNECEDORES.BAIRRO AS BAIRRO,
  FORNECEDORES.CIDADE AS CIDADE,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.ESTADO AS UF,
  FORNECEDORES.FONE AS TELEFONE,
  FORNECEDORES.FAX AS FAX,
  FORNECEDORES.E_MAIL AS EMAIL,
  case when FORNECEDORES.CNPJ = '' then FORNECEDORES.CPF else FORNECEDORES.CNPJ END as CNPJ_CNPF,
  case when FORNECEDORES.INSCRICAO= '' then FORNECEDORES.IDENTIDADE else FORNECEDORES.INSCRICAO END as IE_RG,
  FORNECEDORES.CONTATO AS CONTATO,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.CELULAR AS CELULAR
FROM FORNECEDORES
