SELECT
  PRODUTOS.CODIGO AS CODIGO,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  PRODUTOS.UNIDADE AS UND,
  PRODUTOS.REFERENCIA AS COD_FABRICANTE,
  PRODUTOS.VENDA AS PRECO_VENDA,
  PRODUTOS.BARRAS AS BARRAS,
  GRUPOS.DESCRICAO AS GRUPO,
  PRODUTOS.TRIBUTARIA AS ST,
  PRODUTOS.CUSTO AS PRECO_CUSTO,
  PRODUTOS.PESOLIQUIDO AS PESO,
  PRODUTOS.MEDIO AS CUSTO_MEDIO,
  PRODUTOS.PERLUCRO AS MARGEM_LUCRO,
  PRODUTOS.DATA AS DATA_CADASTRO,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.EST_ATUAL AS QTD,
  FORNECEDORES.NOME AS FORNECEDOR,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = PRODUTOS.CODFOR
LEFT JOIN GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO