SELECT
  CADCID.CID_NOMCID AS CIDADE,
  CADCID.CID_ESTADO AS UF,
  CADCLI.CLI_DTACAD AS CADASTRO,
  CADCLI.CLI_NOMCLI AS NOME,
  CADCLI.CLI_FANSOB AS FANTASIA,
  CADCLI.CLI_ENDERE AS ENDERECO,
  CADCLI.CLI_ENDCMP AS COMPLEMENTO,
  CADCLI.CLI_BAIRRO AS BAIRRO,
  CADCLI.CLI_C_E_P_ AS CEP,
  CADCLI.CLI_C_G_C_ AS CNPJ_CNPF,
  CADCLI.CLI_I_E_S_ AS IE_RG,
  CADCLI.CLI_FONE01 AS TELEFONE,
  CADCLI.CLI_CONTAT AS CONTATO,
  CADCLI.CLI_EMAIL_ AS EMAIL,
  CADCLI.CLI_CELULA AS CELULAR,
  CADCLI.CLI_ENDNUM AS NUMERO
FROM CADCLI
LEFT JOIN CADCID ON CADCLI.CLI_CODCID = CADCID.CID_CODCID
