SELECT
  CADCID.CID_NOMCID AS CIDADE,
  CADCID.CID_ESTADO AS UF,
  CADFOR.FOR_NOMFOR AS NOME,
  CADFOR.FOR_NOMFAN AS FANTASIA,
  CADFOR.FOR_ENDERE AS ENDERECO,
  CADFOR.FOR_BAIRRO AS BAIRRO,
  CADFOR.FOR_C_E_P_ AS CEP,
  CADFOR.FOR_C_G_C_ AS CNPJ_CNPF,
  CADFOR.FOR_I_E_S_ AS IE_RG,
  CADFOR.FOR_CONTAT AS CONTATO,
  CADFOR.FOR_FONE01 AS TELEFONE,
  CADFOR.FOR_F_A_X_ AS FAX,
  CADFOR.FOR_EMAIL_ AS EMAIL,
  CADFOR.FOR_ENDNUM AS NUMERO,
  CADFOR.FOR_CELULA AS CELULAR
FROM CADFOR
LEFT JOIN CADCID ON CADFOR.FOR_CODCID = CADCID.CID_CODCID
