SELECT
    ID AS CODIGO,
    NOME,
    ENDERECO,
    CIDADE,
    ESTADO AS UF,
    BAIRRO,
    CEP,
    DATA_NASC AS NASCIMENTO,
    CPF||CNPJ AS CNPJ_CNPF,
    RG||IE AS IE_RG,
    TELEFONE1 AS TELEFONE,
    TELEFONE2 AS CELULAR,
    EMAIL,
    INSC_MUNICIPAL AS IM
FROM CLIENTES
