SELECT
    CLIENTE.CODIGO AS CODIGO,
    CLIENTE.RAZAO_SOCIAL AS NOME,
    CLIENTE.NOME AS FANTASIA,
    case when CLIENTE.CPF = '' or CLIENTE.CPF is null then CLIENTE.CNPJ else CLIENTE.CPF END AS CNPJ_CNPF,
    case when CLIENTE.CIC = '' or CLIENTE.CIC is null then CLIENTE.IE else CLIENTE.CIC END AS IE_RG,
    CLIENTE.RUA AS ENDERECO,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.BAIRRO AS BAIRRO,
    CIDADE.NOME AS CIDADE,
    CIDADE.UF AS UF,
    CIDADE.CEP AS CEP,
    CLIENTE.FONE AS TELEFONE,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.OBSERVACAO AS OBSERVACOES
    --CLIENTE.DATACAD
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.CODIGO = CLIENTE.CODCID
