SELECT
  id_cliente        AS CODIGO,
  nome              AS NOME,
  nome_fantasia     AS FANTASIA,
  contato           AS CONTATO,
  cgc_cpf           AS CNPJ_CNPF,
  ie_rg             AS IE_RG,
  NULL              AS IM,
  endereco          AS ENDERECO,
  numero            AS NUMERO,
  complemento       AS COMPLEMENTO,
  bairro            AS BAIRRO,
  cidade            AS CIDADE,
  id_municipio      AS ID_MUNICIPIO,
  uf                AS UF,
  cep               AS CEP,
  tel_fixo          AS TELEFONE,
  celular           AS CELULAR,
  fax               AS FAX,
  email             AS EMAIL,
  limite_credito    AS LIMITE_CREDITO,
  dia_vencto        AS DIA_DE_ACERTO,
  COALESCE(dtcad, CURRENT_DATE) AS CADASTRO,
  data_ult_venda    AS ULTIMA_VENDA,
  regime            AS REG_SIMPLES,
  obs               AS OBSERVACOES,
  dtnasc            AS NASCIMENTO,
  naturalidade      AS NATURALIDADE,
  profissao         AS PROFISSAO,
  sexo              AS SEXO,
  indicador_ie      AS INDIEDEST
FROM
  public.cliente;
