SELECT
    CLIENTES.ID_CLIENTE AS CODIGO,
    CLIENTES.NOME AS NOME,
    CLIENTES.NOME_FANTASIA AS FANTASIA,
    CLIENTES.IM AS IM,  
    CLIENTES.CPF_CNPJ AS CNPJ_CNPF,
    case when CLIENTES.RG = '' or CLIENTES.RG is null then CLIENTES.IE else CLIENTES.RG END AS IE_RG,
    CLIENTES_DADOS.ENDERECO AS ENDERECO,
    CLIENTES_DADOS.NUMERO AS NUMERO,
    CLIENTES_DADOS.BAIRRO AS BAIRRO,
    CLIENTES_DADOS.COMPLEMENTO AS COMPLEMENTO,
    CLIENTES_DADOS.CEP AS CEP,
    CLIENTES_DADOS.FONE_RES AS TELEFONE,
    CLIENTES_DADOS.FAX AS FAX,
    CLIENTES_DADOS.CELULAR AS CELULAR,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES_DADOS.NOME_CONJUGE AS CONJUGE,
    CLIENTES_DADOS.ESTADO_CIVIL AS EST_CIVIL,
    CLIENTES_DADOS.PAI AS PAI,
    CLIENTES_DADOS.MAE AS MAE,
    CLIENTES.OBS AS OBSERVACOES,
    CLIENTES.SEXO AS SEXO,
    CLIENTES.NATURALIDADE AS NATURALIDADE,    
    CLIENTES.LIMITE AS LIMITE_CREDITO,
    CLIENTES.NASCIMENTO AS NASCIMENTO,
    CLIENTES.DATA_CADASTRO AS CADASTRO
FROM CLIENTES
LEFT JOIN CLIENTES_DADOS ON CLIENTES_DADOS.id_cliente = CLIENTES.id_cliente
WHERE CLIENTES.DATA_CADASTRO IS NOT NULL
