SELECT 
    replace(PRODUTOS.ID_PRODUTO,'.','') AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.CODIGO_BARRA AS BARRAS,
    CATEGORIAS.descricao AS GRUPO,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.ESTOQUE_MIN AS QTD_IDEAL,
    MAX (PRODUTO_PRECOS.PRECO_CUSTO) AS PRECO_CUSTO,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.REF AS PRECO_VENDA,
    SUBSTRING (PRODUTOS.ST FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.ST FROM 2 FOR 3) AS ST,
    PRODUTOS.CODIGO_FAB AS COD_FABRICANTE,
    PRODUTOS.OBS AS OBSERVACOES,
    CAST (PRODUTOS.DATA_CADASTRO AS DATE) AS DATA_CADASTRO,
    CAST (PRODUTOS.ULTIMA_ENTRADA AS DATE) AS ULTIMA_COMPRA,
    CAST (PRODUTOS.ULTIMA_SAIDA AS DATE) AS ULTIMA_VENDA,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    PRODUTOS.CODIGO_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN produto_precos ON PRODUTO_PRECOS.ID_PRODUTO = PRODUTOS.ID_PRODUTO
LEFT JOIN categorias ON CATEGORIAS.id_categoria = PRODUTOS.id_categoria
GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20,21
