SELECT
    ITENS.ITEM,
    ITENS.CODIGO AS CODIGO,
    ITENS.CODIGOVENDA AS BARRAS,
    ITENS.DESCRICAO AS DESCRICAO,
    ITENS.UNIDADE AS UND,
    ITENS.PESOLIQUIDO AS PESO,
    GRUPOS.DESCRICAOGRUPO AS GRUPO,
    ITENS.QTDEMINIMO AS QTD_IDEAL,
    ITENS.ESTOQUE AS QTD,
    ITENS.CST AS ST,
    ITENS.CUSTOMEDIO AS CUSTO_MEDIO,
    ITENS.PRECOCOMPRA AS PRECO_CUSTO,
    PRODUTOSPRECO.PRECO AS PRECO_VENDA,
    ITENS.REFERENCIA AS COD_FABRICANTE,
    ITENS.DATACADASTRO AS DATA_CADASTRO,
    ITENS.ULTIMACOMPRA AS ULTIMA_COMPRA,
    ITENS.ULTIMAVENDA AS ULTIMA_VENDA,
    ITENS.CLASFISCAL AS COD_NCM,
    ITENS.CODIGOBARRAS,
    ITENS.CEST_OPC AS PERSONAL6
FROM ITENS
LEFT JOIN PRODUTOSPRECO ON PRODUTOSPRECO.ITEM = ITENS.ITEM
LEFT JOIN GRUPOS ON GRUPOS.GRUPO = ITENS.GRUPO
