SELECT 
  P.GTIN AS BARRAS
, P.ID AS CODIGO 
, P.CODIGO_INTERNO AS COD_FABRICANTE
, P.DESCRICAO as DESCRICAO 
, P.NCM as COD_NCM
, U.CODIGO AS UND
, T.NOME  as PERSONAL1 -- AJUSTAR APOS A CONVERSÃO O TIPO_ITEM
, G.NOME  as GRUPO
, M.NOME as CARACTERISTICAS  
, P.ALIQ_IPI as ALIQ_IPI
, left (P.ALIQ_ICMS,2) as ELO
, P.LUCRO as MARGEM_LUCRO
, P.PRECO as PRECO_VENDA
, P.ESTOQUE_QTD as QTD
, P.PRECO_CUSTO as PRECO_CUSTO
, P.ID_CFOP as CF
, P.COD_SIT_TRIB as ST
FROM DBDADOS.PRODUTO P
LEFT JOIN UNIDADE U ON U.ID = P.ID_UNIDADE 
left join  TIPOPRODUTO T on T.ID = P.ID_TIPOPRODUTO
left join grupoproduto G on G.ID = P.ID_GRUPOPRODUTO
left join marca m on m.ID = P.ID_MARCA
