SELECT 
TESTPRODUTOGERAL.CODIGO,
TESTPRODUTOGERAL.DESCRICAO,
TESTPRODUTOGERAL.CODIGOBARRA AS BARRAS,
TESTPRODUTOGERAL.CODIGOFABRICA AS COD_FABRICANTE,
TESTPRODUTOGERAL.EMBALAGEM AS UND,
SUBSTRING (TESTGRUPOICMS.CSF FROM 1 FOR 1) AS OST,
SUBSTRING (TESTGRUPOICMS.CSF FROM 2 FOR 3) AS ST,
TESTPRODUTOGERAL.OBSERVACAO AS OBSERVACOES,
TESTPRODUTOGERAL.DATACADASTRO AS DATA_CADASTRO,
TESTPRODUTOGERAL.CLASSIFICACAOFISCAL AS COD_NCM,
replace(TESTCEST.CEST,'.','') AS PERSONAL6,
TESTESTOQUE.ESTDISPONIVEL AS QTD,
TESTPRODUTO.CUSTOFINAL AS PRECO_CUSTO,
TESTPRODUTO.PRPRATICADO AS PRECO_VENDA,
TESTGRUPO.DESCRICAO AS GRUPO,
TESTSUBGRUPO.DESCRICAO AS FAMILIA,
TESTPRODUTO.PRATACADO AS PRECO_ATACADO
FROM TESTPRODUTOGERAL
LEFT JOIN TESTCEST ON TESTPRODUTOGERAL.IDCEST=TESTCEST.IDCEST
LEFT JOIN TESTESTOQUE ON TESTPRODUTOGERAL.CODIGO=TESTESTOQUE.PRODUTO
LEFT JOIN TESTPRODUTO ON TESTPRODUTOGERAL.CODIGO=TESTPRODUTO.PRODUTO
LEFT JOIN TESTGRUPO ON TESTPRODUTO.GRUPO=TESTGRUPO.CODIGO
LEFT JOIN TESTSUBGRUPO ON TESTPRODUTO.SUBGRUPO=TESTSUBGRUPO.SUBGRUPO AND TESTPRODUTO.GRUPO=TESTSUBGRUPO.GRUPO
LEFT join TESTGRUPOICMS ON TESTGRUPOICMS.codigoid = TESTPRODUTOGERAL.grupoicms
