select
P.ID AS CODIGO,
P.NOME AS DESCRICAO,
P.BARRA AS BARRAS,
P.UNID AS UND,
PQ.qtde AS QTD,
P.EST_MIM AS QTD_IDEAL,
P.MARGEM AS MARGEM_LUCRO,
P.VLR_VENDA AS PRECO_VENDA,
P.VLR_CUSTO AS PRECO_CUSTO,
P.ULT_VENDA AS ULTIMA_VENDA,
P.ULT_COMPRA AS ULTIMA_COMPRA,
G.nome AS GRUPO,
SG.nome AS CARACTERISTICAS,
C.nome AS FORNECEDOR,
P.OBS AS OBSERVACOES,
P.DATA AS DATA_CADASTRO,
F.nome AS FAMILIA,
P.NCM AS COD_NCM,
T.situacao_trib AS ST,
TPC.aliq_pis_s as PIS_ALIQ_NOR,
TPC.aliq_cofins_s as  COFINS_ALIQ_NOR,
P.IPI AS ALIQ_IPI_VENDA,
OM.id AS ost,
P.CST_PIS AS PIS_CODIGO,
P.CST_COFINS AS COFINS_CODIGO,
P.CST_PIS_COFINS_ENTRADA AS PISE_CODIGO,
P.ALIQ_PIS_ENT AS PISE_ALIQ_NOR,
P.ALIQ_COFINS_ENT AS COFINSE_ALIQ_NOR,
P.VLR_ATACADO AS PRECO_ATACADO,
P.CFOP_SAIDAUF AS CF,
P.PESO,
P.CEST AS PERSONAL6,
P.COD_BENEFICIO_FISCAL AS CBENEF,
P.PERC_COMISSAO AS COMISSAO
FROM PRODUTO P
LEFT JOIN grupo G ON G.id = P.id_grupo
LEFT JOIN sub_grupo SG ON SG.id = P.id_sub_grup
LEFT JOIN cliente C ON C.id = P.id_fornec
LEFT JOIN familia F ON F.id = P.id_familia
LEFT JOIN tab_tributaria T ON T.id = P.ID_TAB_TRIB
LEFT JOIN tab_trib_pis TPC ON TPC.id = P.ID_TAB_PIS_COFINS
LEFT JOIN origem_mercadoria OM ON OM.id = P.id_origem_produto
LEFT JOIN produto_qtde PQ ON PQ.id_prod = P.id;