SELECT
	CODIGO,
	RAZAO AS NOME,
	FANTASIA,
	ENDERECO,
	NUMERO,	
	BAIRRO,
	COMPLEMENTO,
	CIDADE,
	UF,
	REPLACE (CEP,'.','') AS CEP,
	right(INSCRICAO, 20) AS IE_RG,
	right(CNPJ,18) AS CNPJ_CNPF,
	INSCRICAOMUNICIPAL AS IM,	
	FONE AS TELEFONE,
	FAX,
	CELULAR,	
	CONTATO,
	EMAIL,
	OBSERVACAO AS OBSERVACOES,
	REFERENCIAS AS PERSONAL1,
	PONTOREFERENCIA AS PERSONAL2
FROM
	FORNECEDORES
