SELECT
    CO_FORNECEDOR AS  CODIGO,
    NO_FORNECEDOR AS NOME,
    NO_FANTASIA AS FANTASIA,
    case when NU_CPF = '' or NU_CPF is null then NU_CGC else NU_CPF END AS CNPJ_CNPF,
    CO_INSCRICAO_ESTADUAL AS IE_RG,
    DE_ENDERECO AS ENDERECO,
    DE_SITIO AS COMPLEMENTO,
    DE_BAIRRO AS BAIRRO,
    NO_CIDADE AS CIDADE,
    CO_UF AS UF,
    CO_CEP AS CEP,
    NU_DDD1 || NU_TELEFONE1 AS TELEFONE,
    NU_DDD2 || NU_TELEFONE2 AS CELULAR,
    NU_FAX AS FAX,
    NO_EMAIL AS EMAIL
FROM SISTB010_FORNECEDOR
