SELECT
  PRODUTOS.Codigo,
  PRODUTOS.Cod_Barras AS BARRAS,
  PRODUTOS.Descricao,
  Marca.DESCRICAO AS FAMILIA,
  Familia.descricao AS GRUPO,
  PRODUTOS.Unidade AS UND,
  PRODUTOS.Preco_Custo,
  PRODUTOS.Preco_Vista AS PRECO_VENDA,
  PRODUTOS.Preco_Atacado,
  PRODUTOS.Qtd_Estoque AS QTD,
  PRODUTOS.ST,
  PRODUTOS.NCM AS COD_NCM,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN MARCA ON PRODUTOS.MARCA = MARCA.codigo
LEFT JOIN FAMILIA ON PRODUTOS.FAMILIA = FAMILIA.codigo
WHERE PRODUTOS.DESCRICAO <> ''