SELECT
  FORNECEDORES.REGISTRO AS CODIGO,
  FORNECEDORES.NOME AS NOME,
  FORNECEDORES.CONTATO AS CONTATO,
  FORNECEDORES.CPFCPNJ AS CNPJ_CNPF,
  FORNECEDORES.INSCEST AS IE_RG,
  FORNECEDORES.LOGRADOURO AS ENDERECO,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
  FORNECEDORES.BAIRRO AS BAIRRO,
  FORNECEDORES.CIDADE AS CIDADE,
  FORNECEDORES.UF AS UF,
  FORNECEDORES.CEP AS CEP,
  FORNECEDORES.TELEFONE AS TELEFONE,
  FORNECEDORES.OBS AS OBSERVACOES,
  FORNECEDORES.EMAIL AS EMAIL
FROM FORNECEDORES
