SELECT
    CONTASAPG.REGISTRO AS DOCUMENTO,
    CONTASAPG.REGFORNECEDOR AS COD_FORNECEDOR,
    CONTASAPG.NOME AS NOM_FORNECEDOR,
    CONTASAPG.DOCUMENTO AS HISTORICO,
    CONTASAPG.DATAEMISSAO AS EMISSAO,
    CONTASAPG.VENCIMENTO AS VENCIMENTO,
    CONTASAPG.VALOR AS VALOR_DUP,
    CONTASAPG.VALORATUAL AS VALOR_TOT,
    CONTASAPG.DATAPAGAMENTO AS PAGAMENTO,
    CONTASAPG.VALORPAGO  AS VALOR_PAG,
  FORNECEDORES.CPFCPNJ AS CNPJ
FROM CONTASAPG
INNER JOIN FORNECEDORES ON CONTASAPG.REGFORNECEDOR = FORNECEDORES.REGISTRO
WHERE CONTASAPG.REGFORNECEDOR <> '0' AND CONTASAPG.REGFORNECEDOR = CONTASAPG.REGFORNECEDOR
