SELECT
  PRODUTOS.REGISTRO AS CODIGO,
  PRODUTOS.CODBARRAS AS BARRAS,
  PRODUTOS.PRODUTO AS DESCRICAO,
  PRODUTOS.NOMEGRUPO AS GRUPO,
  PRODUTOS.NOMEFORNEC AS FORNECEDOR,
  PRODUTOS.PRECOCUSTO AS PRECO_CUSTO,
  PRODUTOS.PRECOVENDA AS PRECO_VENDA,
  PRODUTOS.QUANTIDADE AS QTD,
  PRODUTOS.UNIDADE AS UND,
  PRODUTOS.LUCRO AS MARGEM_LUCRO,
  PRODUTOS.CODNCM AS COD_NCM,
  PRODUTOS.DATACADASTRO AS DATA_CADASTRO,
  PRODUTOS.DATAULTMOV AS ULTIMA_COMPRA,
  PRODUTOS.OBS AS OBSERVACOES,
  CAST (PRODUTOS.DATAATUALIZACAO AS DATE) AS ALTERACAO_PRECO,
  PRODUTOS.CEST AS PERSONAL6,
  PROD_TRIB.TIPOTRIB AS ST
FROM PRODUTOS
left join prod_trib on prod_trib.codproduto = PRODUTOS.REGISTRO
where prod_trib.uf_destino = 'IN'
