SELECT
    CONTASAREC.REGISTRO AS DOCUMENTO,
    CONTASAREC.REGCLIENTE AS COD_CLIENTE,
    CONTASAREC.NOME AS NOM_CLIENTE,
    CLIENTES.CPFCNPJ AS CNPJ,
    CONTASAREC.DOCUMENTO AS HISTORICO,
    CONTASAREC.DATAEMISSAO AS EMISSAO,
    CONTASAREC.VENCIMENTO AS VENCIMENTO,
    CONTASAREC.VALOR AS VALOR_DUP,
    CONTASAREC.JUROS AS VALOR_JUR,
    CONTASAREC.VALORATUAL AS VALOR_TOT,
    CONTASAREC.DATAPAGAMENTO AS RECEBIMENTO,
    CONTASAREC.VALORPAGO AS VALOR_REC,
    --CONTASAREC.DUPLICATA AS NUM_PARCELA,
    CONTASAREC.OBS AS OBSERVACOES
  FROM CONTASAREC
INNER JOIN CLIENTES ON CONTASAREC.REGCLIENTE = CLIENTES.REGISTRO
WHERE CONTASAREC.REGCLIENTE = CONTASAREC.REGCLIENTE and contasarec.dataemissao >= '2020/01/01'

