SELECT 
  IDCLIENTE AS CODIGO
, APELIDO AS FANTASIA
, RAZAOSOCIAL AS NOME
, ENDERECO
, NUMERO
, COMPLEMENTO
, BAIRRO
, CIDADE
, UF
, CEP
, CNPJ AS CNPJ_CNPF
, INSCRICAOESTADUAL AS IE_RG
, INSCRICAOMUNICIPAL AS IM
, TELEFONE
, TELEFONECONTATO AS CONTATO
, FAX
, EMAIL
, LIMITECREDITO AS LIMITE_CREDITO
, OBSERVACAO AS OBSERVACOES
, ENDERECOCOBRANCA AS COB_ENDERECO
, NUMEROCOBRANCA AS COB_NUMERO
, COMPLEMENTOCOBRANCA AS COB_COMPLEMENTO
, BAIRROCOBRANCA AS COB_BAIRRO
, CIDADECOBRANCA AS COB_CIDADE
, UFCOBRANCA AS COB_UF
, CEPCOBRANCA AS COB_CEP
FROM CLIENTE
