SELECT 
  IDFORNECEDOR AS CODIGO
, APELIDO AS FANTASIA
, RAZAOSOCIAL AS NOME
, ENDERECO
, BAIRRO
, CIDADE
, UF
, CEP
, CNPJ AS CNPJ_CNPF
, INSCRICAOESTADUAL AS IE_RG
, INSCRICAOMUNICIPAL AS IM
, TELEFONE
, FAX
, CONTATO
, EMAIL
, OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR
