SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    FANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    CGC AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    FONE AS TELEFONE,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR