SELECT
    CLIENTE.IDCLIENTE AS CODIGO,
    CLIENTE.NOMECLIENTE AS NOME,
    CLIENTE.DOCTOCLIENTE AS CNPJ_CNPF,
    case when CLIENTE.IDENTIDADE = '' or CLIENTE.IDENTIDADE is null then CLIENTE.INSCESTADUAL else CLIENTE.IDENTIDADE END AS IE_RG,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.BAIRRO AS BAIRRO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,
    CIDADE.nomecidade AS CIDADE,
    ESTADO.uf AS UF,
    CLIENTE.CEP AS CEP,
    CLIENTE.FAX AS FAX,
    CLIENTE.TELEFONES AS TELEFONE,
    CLIENTE.CELULAR AS CELULAR,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.DATANASC AS NASCIMENTO,
    CLIENTE.PAI AS PAI,
    CLIENTE.MAE AS MAE,
    CLIENTE.ESTADOCIVIL AS EST_CIVIL,
    CLIENTE.CONJUGUE AS CONJUGE,
    CLIENTE.LIMITECREDITO AS LIMITE_CREDITO,
    CLIENTE.DATACADASTRO AS CADASTRO,
    CLIENTE.OBS AS OBSERVACOES
FROM CLIENTE
LEFT JOIN CIDADE ON CIDADE.idcidade = CLIENTE.IDCIDADE
LEFT JOIN ESTADO ON ESTADO.idestado = CLIENTE.IDESTADO
