SELECT
  PRODUTO.ID AS CODIGO,
  PRODUTO.NOME AS DESCRICAO,
  PRODUTO.CODIGO AS BARRAS,
  PRODUTO.NOMEREDUZIDO AS CARACTERISTICAS,
  PRODUTO.UNIDADE AS UND,
  PRODUTO_ESTOQUE.LOJA AS QTD,
  GRUPO.GRUPO AS GRUPO,
  PESSOA.NOME AS FORNECEDOR,
  PRODUTO.REFERENCIA AS COD_FABRICANTE,
  SUBSTRING (PRODUTO.CST FROM 1 FOR 1) AS OST,
  SUBSTRING (PRODUTO.CST FROM 2 FOR 3) AS ST,
  PRODUTO.PESOLIQUIDO AS PESO,
  PRODUTO.DT_CADASTRO AS DATA_CADASTRO,
  PRODUTO.DT_ULTIMACOMPRA AS ULTIMA_COMPRA,
  PRODUTO.OBSERVACOES AS OBSERVACOES,
  PRODUTO.CUSTO_MEDIO AS CUSTOMEDIO,
  PRODUTO.PRECO_VENDA AS PRECO_VENDA,
  PRODUTO.MARGEM_LIQUIDA AS MARGEM_LUCRO,
  PRODUTO.ESTOQUE_MINIMO AS QTD_IDEAL,
  PRODUTO.CODIGONCM AS COD_NCM,
  PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_ESTOQUE ON PRODUTO_ESTOQUE.ID_PRODUTO = PRODUTO.ID
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTO.ID_GRUPO
LEFT JOIN PESSOA ON PESSOA.ID = PRODUTO.ID_FORNECEDOR
