SELECT
   COD_CLIENTE AS CODIGO,
    RAZAO_SOCIAL AS NOME,
    FANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    CNPJ_CPF AS CNPJ_CNPF,
    case when RG = '' or RG is null then INSC_ESTADUAL else RG END AS IE_RG,
    INSC_MUNICIPAL AS IM,
    UF AS UF,
    LOGRADOURO AS ENDERECO,
    COMPLEMENTO AS COMPLEMENTO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    MUNICIPIO AS CIDADE,
    CEP AS CEP,
    DDD ||''|| FONE_1 AS TELEFONE,
    DDDCELULAR ||''|| CELULAR AS CELULAR,
    FAX  ||''|| DDDFAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM CLIENTE
--WHERE CADASTRO = 'FOR'
