SELECT PRODUTO.CODIGO,
PRODUTO.CODIGOBARRAS AS BARRAS,
PRODUTO.REFERENCIA AS COD_FABRICANTE,
PRODUTO.DESCRICAO,
PRODUTO.UNIDADE AS UND,
GRUPOPRODUTO.NOME AS GRUPO,
FABRICANTE.NOME AS CARACTERISTICAS,
PRODUTO.CSOSN AS ST,
PRODUTO.ESTOQUE AS QTD,
PRODUTO.PRECOCUSTO AS PRECO_CUSTO,
PRODUTO.PRECOVENDA AS PRECO_VENDA,
REPLACE (PRODUTO.NCM,'.','') as COD_NCM,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPOPRODUTO ON PRODUTO.GRUPO=GRUPOPRODUTO.CODIGO
LEFT JOIN FABRICANTE ON PRODUTO.FABRICANTE=FABRICANTE.CODIGO


