SELECT PDV_CLIENTES.ID_CLIENTE AS CODIGO,
PDV_CLIENTES.NOMEFANTASIA AS NOME,
PDV_CLIENTES.RGIE AS IE_RG,
PDV_CLIENTES.CPFCNPJ AS CNPJ_CNPF,
PDV_CLIENTES.NUMEROENDERECO AS NUMERO,
PDV_CLIENTES.COMPLEMENTO,
PDV_CLIENTES.CEP,
PDV_CLIENTES.ENDERECO,
PDV_CLIENTES.NOMECIDADE AS CIDADE,
PDV_CLIENTES.SIGLA AS UF,
PDV_CLIENTES.NOMEBAIRRO AS BAIRRO,
PDV_CLIENTES.EMAIL
FROM PDV_CLIENTES
WHERE ID_CLIENTE>0

