SELECT
    ID_PRODUTO AS CODIGO,
    NOME_PRODUTO AS DESCRICAO,
    PRECO_PRODUTO AS PRECO_VENDA,
    CUSTO_PRODUTO AS PRECO_CUSTO,
    QUANTIDADE AS QTD,
    UNIDADE AS UND,
    replace(NCM,'.','') AS COD_NCM,
    SECAO AS GRUPO,
    CST AS ST,
    CODIGO_PRODUTO AS BARRAS,
    CEST AS PERSONAL6
FROM PRODUTO
