
SELECT
    COD_FOR AS CODIGO,
    RAZAO_SOC AS NOME,
    NOME AS FANTASIA,
    ENDERECO,
    CIDADE,
    BAIRRO,
    UF,
    CGC AS CNPJ_CNPF,
    INS_EST AS IE_RG,
    CEP,
    FONE1 AS TELEFONE,
    NUM_END AS NUMERO
    from FORNECEDOR