select
    COD_PROD AS CODIGO,
    CODBARRAS AS BARRAS,
    DESCRICAO AS DESCRICAO,
    NOM_GRUPO AS GRUPO,
    UN_COMPRA AS UND_COMPRA,
    UNIDADE AS UND,
    SIT_TRIB AS ST,
    EST_ATUAL AS QTD,
    P_CUSTO AS PRECO_CUSTO,
    P_MEDIO AS CUSTO_MEDIO,
    PERCENTUAL AS MARGEM_LUCRO,
    P_VENDA AS PRECO_VENDA,
    ULT_FORNEC AS FORNECEDOR,
    COD_NCM AS COD_NCM
    from produto
