SELECT
  FORNECE.FOR_CODIGO AS CODIGO,
  FORNECE.FOR_RAZAO AS NOME,
  FORNECE.FOR_FANTASIA AS FANTASIA,
  FORNECE.FOR_ENDERECO AS ENDERECO,
  FORNECE.FOR_NUMERO AS NUMERO,
  FORNECE.FOR_BAIRRO AS BAIRRO,
  FORNECE.FOR_CIDADE AS CIDADE,
  FORNECE.FOR_CEP AS CEP,
  FORNECE.FOR_ESTADO AS UF,
  FORNECE.FOR_TELEFONE AS TELEFONE,
  FORNECE.FOR_FAX AS FAX,
  FORNECE.FOR_EMAIL AS EMAIL,
  FORNECE.FOR_CONTATO AS CONTATO,
  FORNECE.FOR_CGC AS CNPJ_CNPF,
  FORNECE.FOR_IE AS IE_RG,
  FORNECE.FOR_TELEFONE2 AS CELULAR
FROM FORNECE
