SELECT
CAST(PRODUTO.PRO_CODIGO AS INTEGER) AS CODIGO,
PRODUTO.PRO_DESCRICAO AS DESCRICAO,
PRODUTO.PRO_NOMEREDUZIDO AS CARACTERISTICAS,
GRUPO.GRU_DESCRICAO AS GRUPO,
FORNECE.FOR_RAZAO AS FORNECEDOR,
PRODUTO.PRO_VALORCOMPRA AS PRECO_CUSTO,
PRODUTO.PRO_VALORVISTA AS PRECO_VENDA,
PRODUTO.PRO_MARGEMV AS MARGEM_LUCRO,
PRODUTO.PRO_CODIGOBARRA AS BARRAS,
PRODUTO.PRO_ESTOQUEATUAL AS QTD,
SUBSTRING(PRODUTO.PRO_SITTRIB FROM 2 FOR 4) AS ST,
PRODUTO.PRO_UNIDADE AS UND,
PRODUTO.PRO_DATACADASTRO AS DATA_CADASTRO,
CLASFIS.CFIS_NUMERO AS COD_NCM
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.PRO_GRUPO=GRUPO.GRU_CODIGO
LEFT JOIN CLASFIS ON PRODUTO.PRO_CLASFISCAL=CLASFIS.CFIS_CODIGO
LEFT JOIN FORNECE ON FORNECE.FOR_CODIGO = PRODUTO.PRO_FABRICANTE
WHERE PRODUTO.PRO_DESCRICAO <> ''
AND PRODUTO.PRO_EMPRESA = '01'
