SELECT 
  CODIGO
, NOME AS FANTASIA
, CONTATO
, RAZAO AS NOME
, ENDERECO
, CEP
, COMPLEMENTO
, NUMERO
, BAIRRO
, OBS AS OBSERVACOES
, TELEFONE
, FAX
, CELULAR
, CASE WHEN CPF = '' OR CPF IS NULL THEN CGC ELSE CPF END AS CNPJ_CNPF
, CASE WHEN RG = '' OR RG IS NULL THEN IE ELSE RG END AS IE_RG
, EMAIL
, CIDADE
, UF
FROM FORNECEDOR
