SELECT
    PAGAR.codigo AS ID
   ,left (PAGAR.CODIGO||'/'||PAGAR.DOCUMENTO,14) AS DOCUMENTO
   ,PAGAR.HISTORICO AS HISTORICO
   ,PAGAR.CODFORNECEDOR AS COD_FORNECEDOR
   ,FORNECEDOR.razao AS NOM_FORNECEDOR
   ,CAST(PAGAR.DATAEMISSAO AS DATE) AS EMISSAO
   ,PAGAR.DATAVENCIMENTO AS VENCIMENTO
   ,PAGAR.VALOR AS VALOR_DUP
   ,PAGAR.DATAPAGAMENTO AS PAGAMENTO
   ,PAGAR.VALORPAGO AS VALOR_PAG
   ,PAGAR.perc_juros AS VALOR_JUR
   ,PAGAR.per_desconto AS VALOR_DES
       ,CASE
        WHEN PAGAR.cancelado = 'N' THEN 0
        WHEN PAGAR.cancelado = 'S' THEN 1
        ELSE NULL
    END AS CANCELADA
   ,PAGAR.nome_fornec_func AS OBSERVACOES
FROM PAGAR
LEFT JOIN FORNECEDOR ON FORNECEDOR.codigo = PAGAR.codfornecedor
WHERE FORNECEDOR.nome <> ''
