SELECT 
  E.CODIGO
 ,E.CODBARRA AS BARRAS
, E.REFERENCIA AS COD_FABRICANTE
, E.DESCRICAO
, E.MED AS UND
, E.PRECOCUSTO AS PRECO_CUSTO
, E.PRECOVENDA AS PRECO_VENDA
, E.PRECOPRAZO AS PERSONAL1
, E.PRECOPROMOCAO AS PERSONAL2
, E.CUSTOMEDIO AS CUSTO_MEDIO
, E.QTDE AS QTD
, E.QTDEMINIMA AS QTD_IDEAL
, E.COMISSAO
, E.DATACADASTRO AS DATA_CADASTRO
, E.DATAULTCOMPRA AS ULTIMA_COMPRA
, E.DATAULTVENDA AS ULTIMA_VENDA
, CASE E.INATIVO WHEN 'N' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO 
, E.OBS AS OBSERVACOES
, E.COD_NCM
, E.IPPT
, E.PESO_BRUTO AS PESO
, E.VALIDADE AS VALIDADE_DIAS
--, E.COD_CST AS ST
, E.CFOP_NA_UF AS CF
, E.COD_CSTIPI AS IPI_CODIGO_VENDA
, E.COD_CSTPIS AS PIS_CODIGO
, E.COD_CSTCOFINS AS COFINS_CODIGO
, E.IPI AS ALIQ_IPI_VENDA
, E.PIS AS PIS_ALIQ_NOR
, E.COFINS AS COFINS_ALIQ_NOR
, G.NOME AS GRUPO 
, S.NOME AS FAMILIA
, F.RAZAO AS FORNECEDOR
, M.NOME AS CARACTERISTICAS
, ST.COD_ST AS ST
, SUBSTRING (ST.CFOP_NA_UF FROM 1 FOR 3) AS ELO
FROM ESTOQUE E
LEFT JOIN GRUPO G ON G.CODIGO = E.CODGRUPO
LEFT JOIN SUBGRUPO S ON S.CODIGO = E.CODSUBGRUPO AND S.CODGRUPO = G.CODIGO 
LEFT JOIN FORNECEDOR F ON F.CODIGO = E.CODFORNECEDOR 
LEFT JOIN MARCA M ON M.CODIGO = E.CODMARCA 
LEFT JOIN SITUACAO_TRIBUTARIA ST ON ST.CODIGO = E.COD_ST
