SELECT
  TRANSP.CODIGO AS CODIGO,
  TRANSP.NOME AS RAZAO_SOCIAL,
  TRANSP.ENDERECO AS ENDERECO,
  TRANSP.CIDADE AS CIDADE,
  TRANSP.cgc AS CNPJ,
  TRANSP.IE AS IE,
  TRANSP.TELEFONE AS TELEFONE,
  TRANSP.PLACA AS PLACA,
  TRANSP.UF AS UF
 -- TRANSP.EMAIL AS EMAIL
FROM TRANSP