SELECT TB_CLIENTE.CLI_ID AS CODIGO,
TB_CLIENTE.CLI_RSOCIAL_NOME AS NOME,
TB_CLIENTE.CLI_FANTASIA_APELIDO AS FANTASIA,
TB_CLIENTE.CLI_CNPJ_CPF AS CNPJ_CNPF,
TB_CLIENTE.CLI_IE_RG AS IE_RG,
TB_CLIENTE.CLI_ENDERECO AS ENDERECO,
TB_CLIENTE.CLI_COMPLEMENTO AS COMPLEMENTO,
TB_CLIENTE.CLI_NUMERO AS NUMERO,
TB_CLIENTE.CLI_BAIRRO AS BAIRRO,
TB_CIDADE.CID_NOME AS CIDADE,
TB_ESTADO.EST_SIGLA AS UF,
TB_CLIENTE.CLI_CEP AS CEP,
TB_CLIENTE.CLI_TELEFONE AS TELEFONE,
TB_CLIENTE.CLI_FAX AS FAX,
TB_CLIENTE.CLI_CELULAR AS CELULAR,
TB_CLIENTE.CLI_EMAIL AS EMAIL,
TB_CLIENTE.CLI_CONTATO AS CONTATO,
TB_CLIENTE.CLI_DT_CADASTRO AS CADASTRO,
TB_CLIENTE.CLI_DT_NASCIMENTO AS NASCIMENTO
FROM TB_CLIENTE
LEFT JOIN TB_CIDADE ON TB_CLIENTE.CLI_CIDADE=TB_CIDADE.CID_ID
LEFT JOIN TB_ESTADO ON TB_CIDADE.CID_ESTADO=TB_ESTADO.EST_ID
