SELECT TB_FORNECEDOR.FOR_ID AS CODIGO,
TB_FORNECEDOR.FOR_RSOCIAL_NOME AS NOME,
TB_FORNECEDOR.FOR_FANTASIA_APELIDO AS FANTASIA,
TB_FORNECEDOR.FOR_CNPJ_CPF AS CNPJ_CNPF,
TB_FORNECEDOR.FOR_IE_RG AS IE_RG,
TB_FORNECEDOR.FOR_ENDERECO AS ENDERECO,
TB_FORNECEDOR.FOR_COMPLEMENTO AS COMPLEMENTO,
TB_FORNECEDOR.FOR_NUMERO AS NUMERO,
TB_FORNECEDOR.FOR_BAIRRO AS BAIRRO,
TB_CIDADE.CID_NOME AS CIDADE,
TB_ESTADO.EST_SIGLA AS UF,
TB_FORNECEDOR.FOR_CEP AS CEP,
TB_FORNECEDOR.FOR_TELEFONE AS TELEFONE,
TB_FORNECEDOR.FOR_FAX AS FAX,
TB_FORNECEDOR.FOR_CELULAR AS CELULAR,
TB_FORNECEDOR.FOR_EMAIL AS EMAIL,
TB_FORNECEDOR.FOR_CONTATO AS CONTATO,
TB_FORNECEDOR.FOR_OBSERVACAO AS OBSERVACOES
FROM TB_FORNECEDOR
LEFT JOIN TB_CIDADE ON TB_FORNECEDOR.FOR_CIDADE=TB_CIDADE.CID_ID
LEFT JOIN TB_ESTADO ON TB_CIDADE.CID_ESTADO=TB_ESTADO.EST_ID

