SELECT
    --THOSPEDES.ID_HOSPEDE AS CODIGO,
    TCIDADES.CIDADE,
    THOSPEDES.NOME,
    THOSPEDES.CPF AS CNPJ_CNPF,
    THOSPEDES.RG AS IE_RG,
    THOSPEDES.ENDERECO,
    THOSPEDES.ENDERECO_COMPLEMENTO AS COMPLEMENTO,
    THOSPEDES.ENDERECO_NUMERO AS NUMERO,
    THOSPEDES.BAIRRO,
    THOSPEDES.CEP,
    THOSPEDES.TELEFONE,
    THOSPEDES.FAX,
    THOSPEDES.EMAIL,
    THOSPEDES.CELULAR
FROM THOSPEDES
LEFT JOIN TCIDADES ON THOSPEDES.ID_CIDADE = TCIDADES.ID_CIDADE
WHERE THOSPEDES.ID_HOSPEDE > 0
