SELECT CLIENTE.ID AS CODIGO,
CLIENTE.NOME,
CLIENTE.FANTASIA,
CLIENTE.EMAIL,
CLIENTE.CPF_CNPJ AS CNPJ_CNPF,
CLIENTE.RG AS IE_RG,
CLIENTE.DATA_CADASTRO AS CADASTRO,
CLIENTE.LOGRADOURO AS ENDERECO,
CLIENTE.NUMERO,
CLIENTE.COMPLEMENTO AS COMPLEMENTO,
CLIENTE.CEP,
CLIENTE.BAIRRO,
CLIENTE.CIDADE,
CLIENTE.UF,
CLIENTE.FONE1 AS TELEFONE,
CLIENTE.CELULAR,
CLIENTE.CONTATO
FROM CLIENTE

