SELECT 
  C.CLICOD AS CODIGO
, C.CLINOME AS NOME
,	case when C.CLISOBRENOME = '' or C.CLISOBRENOME is null then C.CLIFANTASIA else C.CLISOBRENOME END AS FANTASIA
,	case when C.CLICPF = '' or C.CLICPF is null then C.CLICNPJ else C.CLICPF END AS CNPJ_CNPF
,   case when C.CLIRG = '' or C.CLIRG is null then C.CLIINSCEST else C.CLIRG END AS IE_RG
, C.CLIDN AS NASCIMENTO
, C.CLIDATADACASTRO AS CADASTRO
, C.CLICONJUGE AS CONJUGE
, C.CLITELE AS TELEFONE
, C.CLIFAX AS FAX
, C.CLICELULAR AS CELULAR
, C.CLIMAE AS MAE
, C.PAI
, C.CLITRABALHO  AS LOCTRA
, C.CLIPROFIEXERCIDA AS PROFISSAO
, C.LIMITECRED AS LIMITE_CREDITO
, C.CLIMAIL AS EMAIL
, C.DATA_ULT_VENDA AS ULTIMA_VENDA
, C.CLIEND AS ENDERECO
, C.CLINUM AS NUMERO
, C.CLIBAIRRO AS BAIRRO
, C.CEP
, C.CIDADE
, C.CLIPONTOREF AS COMPLEMENTO
, C.UF
FROM CADCLIENTE C
