SELECT 
  P.CODPROD AS COD_FABRICANTE
, P.CODIGODEBARRAS AS BARRAS
, P.CODIGO AS CODIGO
, P.PRODUTO AS DESCRICAO
--, P.PRECOCUSTO AS PRECO_CUSTO
--, P.LUCRO
, P.MARGEMLUCRO AS MARGEM_LUCRO
, P.PRECOVENDA AS PRECO_VENDA
--, P.UNIDADE AS UND
, P.GRUPO
, P.ESTOQUEATUAL AS QTD
--, P.QDE_LOJA
--, P.ESTOQUEMINIMO AS QTD_IDEAL
--, P.COMISSAO
, P.DATACADASTRO AS DATA_CADASTRO
--, P.LOCALIZACAO AS PERSONAL1
--, P.ULTIMA_COMPRA AS ULTIMA_COMPRA
, P.ULTIMA_VENDA AS ULTIMA_VENDA
, P.CEST AS PERSONAL6
--, P.CSTICMS
--, P.CSOSN AS ST
--, P.CSTIPI AS IPI_CODIGO_VENDA
--, P.CSTPIS AS PIS_CODIGO
--, P.CSTCOFINS AS COFINS_CODIGO
, CASE P.STATUS WHEN 'A' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO
--, P.TAMANHO
--, P.PESO
FROM PRODUTOS P
