SELECT
    P.CODIGO AS CODIGO,
    P.DESCRICAO AS DESCRICAO,
    P.CODIGOBARRAS AS BARRAS,
    P.REFERENCIA AS PERSONAL1,
    P.GTIN_TRIBUTAVEL AS PERSONAL2,
    P.CBARRA AS PERSONAL4,
    P.CODIGO_ORIGINAL AS COD_FABRICANTE,    
    CASE P.ATIVO WHEN 'S' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,    
    P.TAMANHO,
    P.COR,
    P.NCM AS COD_NCM,
    P.UN_COMPRAS AS UND_COMPRA,
    P.UN_VENDAS AS UND,
    P.FAT_CONVERSAO AS FAT_CONV,
    P.COD_ANP, 
    P.CEST AS PERSONAL6,
    M.DESCRICAO AS CARACTERISTICAS,
    PC.PRECO AS PRECO_CUSTO,
    PV.PRECO AS PRECO_VENDA,
    PR.ATUAL AS QTD,
    PR.MARGEMLUCRO AS MARGEM_LUCRO,
    PR.ESTOQUEMINIMO AS QTD_IDEAL,
    PR.QTDE_P_ATACADO AS QTD_PRECO_ATACADO,
    C.DESCRICAO AS FAMILIA,
    LEFT(GT.ICMS_CFOP_S_INT_CF,3) AS ELO,
    GT.ICMS_SIT_TRIB_CF AS ST,
    GT.IPI_ALIQ AS ALIQ_IPI_VENDA, 
    GT.IPI_SIT_TRIB AS IPI_CODIGO_VENDA,
    GT.PIS_ALIQ AS PIS_ALIQ_NOR,
    GT.PIS_SIT_TRIB AS PIS_CODIGO,
    GT.COFINS_ALIQ AS COFINS_ALIQ_NOR,
    GT.COFINS_SIT_TRIB AS COFINS_CODIGO
FROM PRODUTOS P
LEFT JOIN MARCAS M ON P.MARCA = M.CODIGO
LEFT JOIN PRECOS_PROD_SERV PC ON P.CODIGO = PC.PRODUTO AND PC.TABELA ='1' AND PC.FILIAL = '1' AND PC.TIPOPRODUTO = 'P'  -- Tabela '1' tem o PRECO DE CUSTO
LEFT JOIN PRECOS_PROD_SERV PV ON P.CODIGO = PV.PRODUTO AND PV.TABELA ='2' AND PV.FILIAL = '1' AND PV.TIPOPRODUTO = 'P' -- Tabela '2' tem o PRECO DE VENDA
LEFT JOIN PRODS_ESTOQ_IMP_OUTR PR ON P.CODIGO = PR.PRODUTO AND PR.FILIAL = '1'
LEFT JOIN GRUPOS_TRIBUTACAO GT ON GT."CODIGO" = PR.GRUPO_TRIBUTACAO AND GT.FILIAL = '1'
LEFT JOIN CATEGORIAS C ON C."CODIGO" = P.CATEGORIA 
