SELECT FORNECEDOR.CD_FORNECEDOR AS CODIGO,
       FORNECEDOR.CD_CGC_FORNECEDOR AS CNPJ_CNPF,
       FORNECEDOR.NM_RAZ_SOC_FORNECEDOR AS NOME,
       FORNECEDOR.CD_INSCR_EST_FORNECEDOR AS IE_RG,
       FORNECEDOR.DS_END_COM_FORNECEDOR AS ENDERECO,
       FORNECEDOR.DS_NUMERO AS NUMERO,
       FORNECEDOR.DS_DDD_TELEFONE || ' ' || CD_FONE_FORNECEDOR AS TELEFONE,
       FORNECEDOR.DS_DDD_TELEFONE || ' ' || CD_FAX_FORNECEDOR AS FAX,
       FORNECEDOR.CD_ESTADO AS UF,
       FORNECEDOR.CD_CEP AS CEP,
       FORNECEDOR.NM_FANTASIA_FORNECEDOR AS FANTASIA,
       CIDADE.DS_CIDADE AS CIDADE,
       FORNECEDOR.CD_INSCR_MUN_FORNECEDOR AS IM,
       BAIRRO.DS_BAIRRO AS BAIRRO,
       FORNECEDOR.DS_COMPLEMENTO AS COMPLEMENTO
FROM FORNECEDOR
     LEFT JOIN BAIRRO ON BAIRRO.CD_BAIRRO = FORNECEDOR.CD_BAIRRO
     LEFT JOIN CIDADE ON CIDADE.CD_CIDADE = FORNECEDOR.CD_CIDADE
