SELECT PRODUTOS.CD_PRODUTO AS CODIGO,
       PRODUTOS.DS_NCM_PRODUTO AS COD_NCM,
       SUBSTRING(PRODUTOS.DS_DESCRICAO_PRODUTO FROM 1 FOR 120) AS DESCRICAO,
       SUBSTRING(PRODUTOS.DS_DESCRICAO_PRODUTO FROM 121 FOR 200) AS CARACTERISTICAS,
       SUBSTRING (PRODUTOS.DS_UNIDADE_PRODUTO FROM 1 FOR 2) AS UND,
     GRUPOS.DS_GRUPO AS GRUPO,
     PRODUTOS.VL_PRECO_VENDA AS PRECO_VENDA,
     PRODUTOS.DS_CODIGO_BARRAS AS BARRAS,
     PRODUTOS.VL_PRECO_CUSTO AS PRECO_CUSTO,
     PRODUTOS.VL_CUSTO_MEDIO AS CUSTO_MEDIO,
     ESTOQUE_PRODUTOS.QTD_ATUAL AS QTD,
     PRODUTOS.QT_ESTOQUE_MINIMO AS QTD_IDEAL,
     PRODUTOS.DS_REFERENCIA AS COD_FABRICANTE
FROM PRODUTOS
     LEFT JOIN GRUPOS ON GRUPOS.CD_GRUPO = PRODUTOS.CD_GRUPO
     LEFT JOIN ESTOQUE_PRODUTOS ON ESTOQUE_PRODUTOS.CD_PRODUTO =
     PRODUTOS.CD_PRODUTO
