SELECT
  FORNECEDORES.CODFOR AS CODIGO,
  FORNECEDORES.NOMEFOR AS NOME,
  FORNECEDORES.FANTFOR AS FANTASIA,
  FORNECEDORES.CNPJFOR AS CNPJ_CNPF,
  FORNECEDORES.IEFOR AS IE_RG,
  FORNECEDORES.ENDFOR AS ENDERECO,
  FORNECEDORES.BAIRROFOR AS BAIRRO,
  FORNECEDORES.CIDFOR AS CIDADE,
  FORNECEDORES.COMPFOR AS COMPLEMENTO,
  FORNECEDORES.UFFOR AS UF,
  FORNECEDORES.CEPFOR AS CEP,
  FORNECEDORES.TELFOR AS TELEFONE,
  FORNECEDORES.CELFOR AS CELULAR,
  FORNECEDORES.FAXFOR AS FAX,
  FORNECEDORES.OBSFOR AS OBSERVACOES,
  FORNECEDORES.CONTFOR AS CONTATO,
  FORNECEDORES.NUMEROFOR AS NUMERO
FROM FORNECEDORES
