SELECT
  PRODUTOS.CODPROD AS CODIGO,
  GRUPO.DESCGRUPO AS GRUPO,
  PRODUTOS.DESCPROD AS DESCRICAO,
  PRODUTOS.UNDPROD AS UND,
  PRODUTOS.BARRAPROD AS BARRAS,
  PRODUTOS.MARCAPROD AS CARACTERISTICAS,
  PRODUTOS.ESTPROD AS QTD,
  PRODUTOS.CUSTMPROD AS CUSTO_MEDIO,
  PRODUTOS.PREC1PROD AS PRECO_VENDA,
  PRODUTOS.PESOPROD AS PESO,
  PRODUTOS.OBSPROD AS OBSERVACOES,
  SUBSTRING (PRODUTOS.CSTPROD FROM 2 FOR 3) AS ST,
  PRODUTOS.CUSTOPROD AS PRECO_CUSTO,
  FORNECEDORES.NOMEFOR AS FORNECEDOR,
  PRODUTOS.NCMPROD AS COD_NCM,
  PRODUTOS.DATAESTOQUE AS DATA_CADASTRO
 -- REPLACE (PRODUTOS.CESTPROD, '.' , '') AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPO ON GRUPO.CODGRUPO = PRODUTOS.CODGRUPO
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODFOR = PRODUTOS.CODFOR
order by codprod
