SELECT
    CODIGO AS COD_FABRICANTE,
    NOME AS DESCRICAO,
    UNID AS UND,
    PVENDA AS PRECO_VENDA,
    ESTOQ AS QTD,
    PCUSTO AS PRECO_CUSTO,
    CODST AS COD_NCM,
    CODCSTSAIDA AS ST,
    CST_PIS AS PIS_CODIGO,
    CST_COFINS AS COFINS_CODIGO,
    CODCEST AS PERSONAL6
FROM PRODUTO
