SELECT
    CODIGO AS CODIGO,
    RAZAO_SOCIAL AS NOME,
    NOME AS FANTASIA,
    CGC AS CNPJ_CNPF,
    INSCRICAO AS IE_RG,
    ENDERECO AS ENDERECO,
    COMPLEMENTO AS COMPLEMENTO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    FONE AS TELEFONE,
    CELULAR_REPR AS CELULAR,
    FAX AS FAX,
    EMAIL AS EMAIL,
    OBSERVACAO AS OBSERVACOES
FROM ACADFORN
where RAZAO_SOCIAL <> ''
