SELECT
    CLIENTE.NOME AS NOME,
    CLIENTE.NOMEFANTASIA AS FANTASIA,
    CLIENTE.ENDERECO AS ENDERECO,
    CLIENTE.BAIRRO AS BAIRRO,
    CIDADES.CIDADE AS CIDADE,
    CIDADES.ESTADO AS UF,
    CLIENTE.CEP AS CEP,
    CLIENTE.CGCCPF AS CNPJ_CNPF,
    CLIENTE.INSCEST AS IE_RG,
    CLIENTE.CONTATO AS CONTATO,
    CLIENTE.FONE AS TELEFONE,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.CELULAR AS CELULAR
FROM CLIENTE
LEFT JOIN CIDADES ON CLIENTE.CODCIDADE = CIDADES.CODCIDADE