SELECT
    PRODUTO.CODPROD AS CODIGO,
    PRODUTO.REFERENCIA AS BARRAS,
    PRODUTO.REFFABRICANTE AS COD_FABRICANTE,
    PRODUTO.DESCRICAO AS DESCRICAO,
    CLASFISC.CODIGONCM AS COD_NCM,
    PRODUTO.UNIDADESAIDA AS UND,
    PRODUTO.PRECO AS PRECO_VENDA,
    PRODUTODETALHE.CODCSOSN AS ST,
    PRODUTO.CODCEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN CLASFISC ON PRODUTO.CODCLASFIS = CLASFISC.CODCLASFIS
LEFT JOIN PRODUTODETALHE ON PRODUTO.CODPROD = PRODUTODETALHE.CODPROD