SELECT
P.CODIGO,
P.CNPJ AS CNPJ_CNPF,
P.IE AS IE_RG,
P.FANTASIA,
P.ENDERECO,
P.NUMERO,
P.COMPLEMENTO,
P.MUNICIPIO AS CIDADE,
P.BAIRRO,
P.UF,
P.CEP,
P.FONE1 AS TELEFONE,
P.FONE2 AS FAX,
P.CELULAR1 AS CELULAR,
P.EMAIL1 AS EMAIL,
P.OBS AS OBSERVACOES,
P.RAZAO AS NOME
FROM pessoa P
where P.FORN = 'S'
ORDER BY P.CODIGO;