SELECT CLIENTE.COD_CLI AS CODIGO,
CLIENTE.NOME_CLI AS NOME,
CLIENTE.ENDRES_CLI AS ENDERECO,
CLIENTE.BAIRES_CLI AS BAIRRO,
CLIENTE.CIDRES_CLI AS CIDADE,
CLIENTE.ESTRES_CLI AS UF,
CLIENTE.CEPRES_CLI AS CEP,
CLIENTE.TELRES_CLI AS TELEFONE,
CLIENTE.NUMRES_CLI AS NUMERO,
CLIENTE.CNPJ_CLI AS CNPJ_CNPF,
CLIENTE.DOC_CLI AS IE_RG,
CLIENTE.DATACADASTRO_CLI AS CADASTRO,
CLIENTE.CELULAR_CLI AS CELULAR,
CLIENTE.NOME_FANTASIA AS FANTASIA,
CLIENTE.CONTATO_CLI AS CONTATO,
CLIENTE.EMAIL_CLI AS EMAIL
FROM CLIENTE
WHERE CLIENTE.COD_CLI>0

