SELECT 
       PRODUTOS.CODIGO AS COD_FABRICANTE
      ,PRODUTOS.DESCRICAO
      ,PRODUTOS.PRECO AS PRECO_VENDA
      ,PRODUTOS.UN AS UND
      ,PRODUTOS.Cod_NCM AS COD_NCM
      ,PRODUTOS.CST AS ST
      ,PRODUTOS.UN_ENTRADA AS UND_COMPRA
      ,PRODUTOS.VALOR_COMPRA AS PRECO_CUSTO
      ,PRODUTOS.Codigo_CEST AS PERSONAL6
      ,TB_ESTOQUE.QD AS QTD
  FROM siac.dbo.PRODUTOS
LEFT JOIN siac.dbo.TB_ESTOQUE ON PRODUTOS.CODIGO = TB_ESTOQUE.CODIGO
