SELECT
    FORNECEDORES.CODIGO_FORNECEDOR AS CODIGO,
    FORNECEDORES.NOME AS NOME,
    FORNECEDORES.FANTASIA AS FANTASIA,
    FORNECEDORES.INSCRICAO AS IE_RG,
    FORNECEDORES.CNPJ AS CNPJ_CNPF,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.COMPLEMENTO AS COMPLEMENTO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.UF AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.FONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.NUMERO AS NUMERO
FROM FORNECEDORES
