SELECT
    PESSOA.ID AS CODIGO,
    PESSOA.NOME AS NOME,
    PESSOA.CONTATO AS CONTATO,
    case when PESSOA_FISICA.CPF = '' or PESSOA_FISICA.CPF is null then PESSOA_JURIDICA.CNPJ else PESSOA_FISICA.CPF END AS CNPJ_CNPF,
    PESSOA_JURIDICA.INSCRICAO_ESTADUAL,
    PESSOA.ENDERECO AS ENDERECO,
    PESSOA.NUM AS NUMERO,
    PESSOA.COMPLEMENTO AS COMPLEMENTO,
    PESSOA.BAIRRO AS BAIRRO,
    MUNICIPIO.NOME AS CIDADE,
    PESSOA.CEP AS CEP,
    UF.SIGLA AS UF,
    PESSOA.TELEFONE AS TELEFONE,
    PESSOA.EMAIL AS EMAIL,
    PESSOA.DATA_CADASTRO AS CADASTRO,
    PESSOA.CLI_FOR,
    PESSOA.OBSERVACAO AS OBSERVACOES
FROM PESSOA
LEFT JOIN PESSOA_FISICA ON PESSOA_FISICA.PESSOA_ID = PESSOA.ID
LEFT JOIN PESSOA_JURIDICA ON PESSOA_JURIDICA.PESSOA_ID = PESSOA.ID
LEFT JOIN MUNICIPIO ON MUNICIPIO.ID = PESSOA.MUNICIPIO_ID
LEFT JOIN UF ON UF.ID = PESSOA.UF_ID
WHERE PESSOA.CLI_FOR <> 'C' --FORNECEDORES
