SELECT
  codcli AS CODIGO,
  nomcli AS NOME,
  apecli AS FANTASIA,
  contato AS CONTATO,
  COALESCE(cgccli, cpfcli) AS CNPJ_CNPF,
  COALESCE(inscli, rgcli) AS IE_RG,
  endcli AS ENDERECO,
  numend AS NUMERO,
  compleendcli AS COMPLEMENTO,
  baicli AS BAIRRO,
  muncli AS CIDADE,
  estcli AS UF,
  cepcli AS CEP,
  foncli AS TELEFONE,
  celcli AS CELULAR,
  faxcli AS FAX,
  email AS EMAIL,
  salario AS RENDA,
  limite AS LIMITE_CREDITO,
  datcad AS CADASTRO,
  obscli AS OBSERVACOES,
  estciv AS EST_CIVIL,
  nompai AS PAI,
  nommae AS MAE,
  nacionalidade AS NATURALIDADE,
  desocu AS PROFISSAO,
  nomconj AS CONJUGE
FROM public.arqcli;