SELECT PESSOA.ID AS CODIGO,
PESSOA.RAZAO AS NOME,
MUNICIPIO.NOME AS CIDADE,
ESTADO.SIGLA AS UF,
PESSOA.FANTASIA,
PESSOA.CNPJCPF AS CNPJ_CNPF,
PESSOA.IE AS IE_RG,
PESSOA.CEP,
PESSOA.ENDERECO,
PESSOA.NUMERO,
PESSOA.COMPLEMENTO,
PESSOA.BAIRRO,
PESSOA.EMAIL,
PESSOA.FONE AS TELEFONE,
PESSOA.FAX,
PESSOA.CELULAR,
PESSOA.CONTATO,
CAST (PESSOA.CADASTRO AS DATE) AS CADASTRO
FROM PESSOA
LEFT JOIN MUNICIPIO ON PESSOA.ID_MUNICIPIO=MUNICIPIO.ID
LEFT JOIN ESTADO ON PESSOA.ID_ESTADO=ESTADO.ID
WHERE PESSOA.TIPO=0




