SELECT
    ACADPROD.CEMP,
    ACADPROD.NOME AS DESCRICAO,
    ACADPROD.CODIGO AS BARRAS,
    ACADPROD.UNIDADE AS UND,
    ACADPROD.SALDO_ATU AS QTD,
    ACADPROD.EST_MINIMO AS QTD_IDEAL,
    ACADPROD.PESO_LIQUI AS PESO,
    ACADFORN.RAZAO_SOCIAL AS FORNECEDOR,
    ACADGPRD.DESCRICAO AS GRUPO,
    ACADSGPR.DESCRICAO AS FAMILIA,
    ACADPROD.PRECO_CUST AS PRECO_CUSTO,
    ACADPROD.PRECO_VEND AS PRECO_VENDA,
    ACADPROD.PERC_LUCRO AS MARGEM_LUCRO,
    ACADPROD.PRECO_ATACADO AS PRECO_ATACADO,
    TRIBUTACAO.CST AS ST,
    ACADPROD.REFERENCIA AS COD_FABRICANTE,
    ACADPROD.DTCADASTRO AS DATA_CADASTRO,
    CAST (ACADPROD.DATA_ALTERACAO AS DATE) AS ALTERACAO_PRECO,
    ACADPROD.ULTM_COMPRA AS ULTIMA_COMPRA,
    ACADPROD.ULTM_VENDA AS ULTIMA_VENDA,
    ACADPROD.CODIGO_TRIBUTARIO,
    ACADPROD.NCM AS COD_NCM,
    ACADPROD.CEST AS PERSONAL6
FROM ACADPROD
LEFT JOIN ACADFORN ON ACADFORN.CODIGO = ACADPROD.CODIGO
LEFT JOIN ACADGPRD ON ACADGPRD.CODIGO = ACADPROD.GRUPO
LEFT JOIN ACADSGPR ON ACADSGPR.CODIGO = ACADPROD.SGRUPO
LEFT JOIN TRIBUTACAO ON TRIBUTACAO.CODIGO = ACADPROD.CODIGO
WHERE TRIBUTACAO.OPERACAO = '1'
