SELECT
    PESSOA.CODIGO AS CODIGO,
    PESSOA.NOME AS NOME,
    PESSOA.CPF_CNPJ AS CNPJ_CNPF,
    case when PESSOAFISICA.RG = '' or PESSOAFISICA.RG is null then PESSOA.IE else PESSOAFISICA.RG END AS IE_RG,
    PESSOA.IM AS IM,
    PESSOA.LOGRADOURO AS ENDERECO,
    PESSOA.NUMIMOVEL AS NUMERO,
    PESSOA.COMPENDERECO AS COMPLEMENTO,
    PESSOA.BAIRRO AS BAIRRO,
    PESSOA.CEP AS CEP,
    LOCALIDADE.NOME AS CIDADE,
    UF.SIGLA AS UF,
    PESSOA.TELEFONE AS TELEFONE,
    PESSOA.EMAIL AS EMAIL,
    PESSOA.OBS AS OBSERVACOES
FROM PESSOA
LEFT JOIN LOCALIDADE ON LOCALIDADE.ID = PESSOA.LOCALIDADE_ID
LEFT JOIN UF ON UF.CODIGO = LOCALIDADE.UF_ID
LEFT JOIN PESSOAFISICA ON PESSOAFISICA.PESSOA_ID = PESSOA.ID 
WHERE PESSOA.FORNECEDOR = '1'
