SELECT
    CODPESSOA AS CODIGO,
    PES_NOME AS NOME,
    PES_RAZAO_SOCIAL AS FANTASIA,
    PES_CPFCNPJ AS CNPJ_CNPF,
    PES_IE AS IE_RG,
    PES_ENDERECO AS ENDERECO,
    PES_ENDERECO_NUMERO AS NUMERO,
    PES_ENDERECO_COMPLEMENTO AS COMPLEMENTO,
    PES_BAIRRO AS BAIRRO,
    PES_CIDADE AS CIDADE,
    PES_UF AS UF,
    PES_CEP AS CEP,
    COALESCE (PES_TELEFONE_DDD, '') || COALESCE (PES_TELEFONE,'') AS TELEFONE,
    COALESCE (PES_CELULAR_DDD, '') || COALESCE (PES_CELULAR, '') AS CELULAR,
    PES_EMAIL
FROM PESSOA
