SELECT
	CODFOR AS CODIGO,
	NOMFOR AS NOME,
	ENDFOR AS ENDERECO,
	BAIFOR AS BAIRRO,
	CIDFOR AS CIDADE,
	ESTFOR AS UF,
	CEPFOR AS CEP,
	FONFOR AS TELEFONE,
	CNPJ AS CNPJ_CNPF,
	INSFOR AS IE_RG,
	EMAILF AS EMAIL,
	FAXFOR AS FAX,
	REPFOR AS CONTATO,
	FONREP AS CELULAR,
	OBSFOR AS OBSERVACOES
FROM
	TB104