 SELECT
  CLIENTES.CODIGO AS CODIGO,
  CLIENTES.RAZAOSOCIAL AS NOME,
  CLIENTES.FANTASIA AS FANTASIA,
  CLIENTES.DTCADASTRO AS CADASTRO,
  CLIENTES.INSCRICAO AS CNPJ_CNPF,
  case when CLIENTES.IE ='' then CLIENTES.IDENTIDADE else CLIENTES.IE  end as IE_RG,
  CLIENTES.IM AS IM,
  CLIENTES.CEP AS CEP,
  CLIENTES.BAIRRO AS BAIRRO,
  CLIENTES.ENDERECO AS ENDERECO,
  CLIENTES.NUMERO AS NUMERO,
  CLIENTES.COMPLEMENTO AS COMPLEMENTO,
  CLIENTES.LIMITEVENDA AS LIMITE_credito,
  CLIENTES.EMAIL AS EMAIL,
  CLIENTES.OBS AS OBSERVACOES,
  CLIENTES.PAI AS PAI,
  CLIENTES.MAE AS MAE,
  CLIENTES.DESCCIDADE AS CIDADE,
  CIDADES.UF AS UF,
  CLIENTES.CONTATO AS CONTATO
  FROM CLIENTES
  LEFT JOIN CIDADES ON CIDADES.CODIGO = CLIENTES.CODCIDADE 
