SELECT TAB_FORNECEDOR.COD_FORNECEDOR AS CODIGO,
TAB_FORNECEDOR.DES_FORNECEDOR AS NOME,
TAB_FORNECEDOR.DES_FANTASIA AS FANTASIA,
TAB_FORNECEDOR.NUM_CGC AS CNPJ_CNPF,
TAB_FORNECEDOR.NUM_INSC_EST AS IE_RG,
TAB_FORNECEDOR.DES_ENDERECO AS ENDERECO,
TAB_FORNECEDOR.DES_BAIRRO AS BAIRRO,
TAB_FORNECEDOR.NUM_CEP AS CEP,
TAB_CIDADE.DES_CIDADE AS CIDADE,
TAB_FORNECEDOR.DES_SIGLA AS UF,
TAB_FORNECEDOR.NUM_FONE AS TELEFONE,
TAB_FORNECEDOR.NUM_FAX AS FAX,
TAB_FORNECEDOR.DES_CONTATO AS CONTATO,
TAB_FORNECEDOR.DES_EMAIL AS EMAIL,
TAB_FORNECEDOR.NUM_ENDERECO AS ENDERECO,
TAB_FORNECEDOR.DES_OBSERVACAO AS OBSERVACOES
FROM TAB_FORNECEDOR
LEFT JOIN TAB_CIDADE ON TAB_FORNECEDOR.COD_CIDADE=TAB_CIDADE.COD_CIDADE

