SELECT 
       CDCLIE AS CODIGO
      ,NOMCLI AS NOME
      ,FANTAS AS FANTASIA
      ,RESPON AS CONTATO
      ,ENDERE AS ENDERECO
      ,REFERE AS COMPLEMENTO
      ,NUMERO AS NUMERO
      ,BAIRRO AS BAIRRO
      ,NUMCEP AS CEP
      ,CPFCGC AS CNPJ_CNPF
      ,NUMDRG AS IE_RG
      ,INSMUN AS IM
      ,CAST (DTNASC AS DATE) AS NASCIMENTO
      ,CAST (DTCADA AS DATE) AS CADASTRO
      ,TELEFO AS TELEFONE
      ,NUMFAX AS FAX
      ,CELULA AS CELULAR
      ,EMAILS AS EMAIL
      ,NATURA AS NATURALIDADE
      ,ESTCIV AS EST_CIVIL
      ,LIMCRE AS LIMITE_cREDITO
      ,OBSERV AS OBSERVACOES
  FROM EasySACDarlan.dbo.SAC311 ---CLIENTES
