SELECT
    CLIENTE.ID AS CODIGO,
    CLIENTE.NOME AS NOME,
    CLIENTE.FANTASIA AS FANTASIA,
    CLIENTE.CONTATO AS CONTATO,
    CLIENTE.EMAIL AS EMAIL,
    CLIENTE.CPF_CNPJ AS CNPJ_CNPF,
    case when CLIENTE.INSCRICAO_ESTADUAL = '' or CLIENTE.INSCRICAO_ESTADUAL is null then CLIENTE.RG else CLIENTE.INSCRICAO_ESTADUAL END AS IE_RG,
    CLIENTE.INSCRICAO_MUNICIPAL AS IM,
    CLIENTE.LOGRADOURO AS ENDERECO,
    CLIENTE.NUMERO AS NUMERO,
    CLIENTE.COMPLEMENTO AS COMPLEMENTO,
    CLIENTE.CEP AS CEP,
    CLIENTE.BAIRRO AS BAIRRO,
    CLIENTE.CIDADE AS CIDADE,
    CLIENTE.UF AS UF,
    CLIENTE.FONE1 AS TELEFONE,
    CLIENTE.CELULAR AS CELULAR,
    CLIENTE.OBS AS OBSERVACOES
FROM CLIENTE
WHERE CLIENTE.FORNECEDOR = 'S'