SELECT
       PESSOAS.OBSERVACAO AS OBSERVACOES
      ,PESSOAS.CODIGO AS CODIGO
      ,PESSOAS.NOME AS NOME
      ,PESSOAS.SEXO AS SEXO
      ,PESSOAS.FANTASIA AS FANTASIA
      ,PESSOAS.CONTATO AS CONTATO
      ,PESSOAS_COMPLEMENTO.ENDERECO AS ENDERECO
      ,PESSOAS_COMPLEMENTO.NUMERO AS NUMERO
      ,PESSOAS_COMPLEMENTO.COMPLEMENTO AS COMPLEMENTO
      ,PESSOAS_COMPLEMENTO.BAIRRO AS BAIRRO
      ,PESSOAS_COMPLEMENTO.CEP AS CEP
      ,CIDADES.NOME AS CIDADE
      ,UF.SIGLA AS UF
      ,PESSOAS_FONE.NUMERO_SEM_MASCARA AS TELEFONE
      ,PESSOAS.ESTADO_CIVIL AS EST_CIVIL
      ,PESSOAS.DT_NASCIMENTO AS NASCIMENTO
      ,PESSOAS.CGC_CPF AS CNPJ_CNPF
      ,case when PESSOAS.INSC = '' or PESSOAS.INSC is null then PESSOAS.RG else PESSOAS.INSC END as IE_RG
      ,PESSOAS.EMAIL_1 AS EMAIL
      ,PESSOAS.LIMITE_CREDITO AS LIMITE_CREDITO
      ,PESSOAS.INSCRICAO_MUNICIPAL AS IM
  FROM trade12.dbo.PESSOAS
  LEFT JOIN trade12.dbo.PESSOAS_COMPLEMENTO ON PESSOAS_COMPLEMENTO.PES_HANDLE = PESSOAS.HANDLE
  LEFT JOIN trade12.dbo.PESSOAS_FONE ON PESSOAS_FONE.PES_HANDLE = PESSOAS.HANDLE
  LEFT JOIN trade12.dbo.CIDADES ON CIDADES.HANDLE = PESSOAS_COMPLEMENTO.CID_HANDLE
  LEFT JOIN trade12.dbo.UF ON UF.Handle = CIDADES.UF_HANDLE
  WHERE trade12.dbo.PESSOAS.INDCLI = '1'
