SELECT
  CADASTRODESCRICAO.CODIGO AS CODIGO,
  CADASTRODESCRICAO.DESCRICAO AS DESCRICAO,
  CADASTRODESCRICAO.PRECO AS PRECO_VENDA,
  CADASTRODESCRICAO.CODIGOBARRAS AS BARRAS,
  CADASTRODESCRICAO.ESTOQUE AS QTD,
  CADASTRODESCRICAO.MARGEMLUCRO AS MARGEM_LUCRO,
  CADASTRODESCRICAO.PRECOCOMPRA AS PRECO_CUSTO,
  CADASTRODESCRICAO.ESTOQUEMINIMO AS QTD_IDEAL,
  CADASTRODESCRICAO.UN AS UND,
  CADASTRODESCRICAO.FORNECEDOR AS FORNECEDOR,
  CADASTRODESCRICAO.PESELIQUIDO AS PESO,
  CADASTRODESCRICAO.PRECOATACADO AS PRECO_ATACADO,
  CADASTRODESCRICAO.REFERENCIA AS COD_FABRICANTE,
  CADASTRODESCRICAO.CODIGOINTERNO AS CARACTERISTICA
FROM CADASTRODESCRICAO
