SELECT
    ID_CLIENTE AS CODIGO,
    CLIENTE AS NOME,
    APELIDO AS FANTASIA,
    NASCIMENTO AS NASCIMENTO,
    CPF AS CNPJ_CNPF,
    INDENTIDADE AS IE_RG,
    TEL1 AS TELEFONE,
    TEL2 AS CELULAR,
    CEP AS CEP,
    ENDERECO AS ENDERECO,
    NUMERO AS NUMERO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    EMAIL AS EMAIL
FROM CLIENTES
