SELECT
    ID_PRODUTO AS CODIGO,
    FORNECEDOR AS FORNECEDOR,
    COD_BARRA AS BARRAS,
    DESCRICAO_PRODUTO AS DESCRICAO,
    ESTOQUE AS QTD,
    DESCRICAO_FAMILIA AS GRUPO,
    EMB_COMPRA AS UND,
    PRECO_VENDA AS PRECO_VENDA,
    CUSTO AS PRECO_CUSTO
FROM PRODUTOS
