SELECT
  TGRUPOS_PRODUTOS.DESCRICAO AS GRUPO,
  TPRODUTOS.CODIGO AS COD_FABRICANTE,
  TPRODUTOS.CODIGO_BARRAS AS BARRAS,
  TPRODUTOS.DESCRICAO AS DESCRICAO,
  TPRODUTOS.OBSERVACAO AS OBSERVACOES,
  TPRODUTOS.ESTOQUE_MINIMO AS QTD_IDEAL,
  TPRODUTOS.ESTOQUE AS QTD,
  TPRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
  TPRODUTOS.PRECO_CUSTO AS PRECO_CUSTO,
  TPRODUTOS.PRECO_VENDA AS PRECO_VENDA,
  TPRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
  TPRODUTOS.UNIDADE AS UND,
  TPRODUTOS.NCM AS COD_NCM,
  TPRODUTOS.CSOSN AS ST,
  TPRODUTOS.CEST AS PERSONAL6
FROM TPRODUTOS
LEFT JOIN TGRUPOS_PRODUTOS ON TGRUPOS_PRODUTOS.ID_GRUPO_PRODUTO = TPRODUTOS.ID_GRUPO_PRODUTO
