SELECT
       PRODUTOS.CODIGO AS COD_FABRICANTE
      ,PRODUTOS.NOME AS DESCRICAO
      ,GRUPOS.NOME AS GRUPO
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.APLICACAO AS CARACTERISTICAS
      ,PRODUTOS.CBARRA AS BARRAS
      ,PRODUTOS.PESO_LIQ AS PESO
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.DATA_ALTERACAO ASALTERACAO_PRECO
      ,PRODUTOS.CODIGO_NCM as cod_ncm
      ,PRODUTOS.COD_CEST AS PERSONAL6
      ,CADFOR.NOME AS FORNECEDOR
      ,PRODLOJAS.EST_MINIM AS QTD_IDEAL
      ,PRODLOJAS.EST_ATUAL AS QTD
      ,PRODLOJAS.PCO_COMPRA AS PRECO_CUSTO
      ,PRODLOJAS.PCO_REMAR AS PRECO_VENDA
  FROM ESTANCELL.dbo.PRODUTOS
LEFT JOIN ESTANCELL.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = ESTANCELL.dbo.PRODUTOS.CODIGO
LEFT JOIN ESTANCELL.dbo.GRUPOS ON GRUPOS.CODIGO = ESTANCELL.dbo.PRODUTOS.GRUPO
LEFT JOIN ESTANCELL.dbo.CADFOR ON CADFOR.CODIGO = ESTANCELL.dbo.PRODLOJAS.FORNECEDOR