SELECT
	P.ID_PESSOA AS CODIGO,
	P.NOME AS NOME,
	P.ENDERECO AS ENDERECO,
	P.NUMERO AS NUMERO,
	P.BAIRRO AS BAIRRO,
	P.CEP AS CEP,
	C.NOME AS CIDADE,
	C.SIGLAESTADO AS UF,
	P.EMAIL AS EMAIL,
	P.COMPLEMENTO AS COMPLEMENTO
FROM PESSOA P
LEFT JOIN CIDADE C ON P.ID_CIDADE=C.ID_CIDADE 
WHERE P.EFORNECEDOR  = 'S'
