SELECT 
       PESSOAS_PESSOA.ID AS CODIGO
      ,PESSOAS_PESSOA.NOMERAZAOSOCIAL AS NOME
      ,PESSOAS_PESSOA.APELIDOFANTASIA AS FANTASIA
      ,PESSOAS_PESSOA.CPFCNPJ AS CNPJ_CNPF
      ,PESSOAS_PESSOA.RGIE AS IE_RG
      ,PESSOAS_PESSOA.INSCRICAOMUNICIPAL AS IM
      ,PESSOAS_PESSOA.SEXO AS SEXO
      ,PESSOAS_PESSOA.LOGRADOURO AS ENDERECO
      ,PESSOAS_PESSOA.PONTOREFERENCIA AS COMPLEMENTO
      ,PESSOAS_PESSOA.BAIRRO AS BAIRRO
      ,PESSOAS_PESSOA.NUMERO AS NUMERO
      ,Pessoas_Cidades.Descricao AS CIDADE
      ,Pessoas_Estados.UF AS UF
      ,PESSOAS_PESSOA.CEP AS CEP
      ,PESSOAS_PESSOA.TELEFONE1 AS TELEFONE
      ,PESSOAS_PESSOA.FAX AS FAX
      ,PESSOAS_PESSOA.CELULAR AS CELULAR
      ,PESSOAS_PESSOA.CONTATO1 AS CONTATO
      ,PESSOAS_PESSOA.EMAIL AS EMAIL
      ,PESSOAS_PESSOA.DATANASCIMENTO AS NASCIMENTO
      ,PESSOAS_PESSOA.ESTADOCIVIL AS EST_CIVIL
      ,PESSOAS_PESSOA.NOMEPAI AS PAI
      ,PESSOAS_PESSOA.NOMEMAE AS MAE
      ,PESSOAS_PESSOA.NOMECONJUGE AS CONJUGE
      ,PESSOAS_PESSOA.LIMITECREDITO AS LIMITE_CREDITO
      ,PESSOAS_PESSOA.OBSERVACAO AS OBSERVACOES
  FROM sis.dbo.PESSOAS_PESSOA
  LEFT JOIN sis.dbo.Pessoas_Cidades ON Pessoas_Cidades.ID = PESSOAS_PESSOA.CIDADEID
  LEFT JOIN sis.dbo.Pessoas_Estados ON Pessoas_Estados.ID = Pessoas_Cidades.EstadoID
  WHERE FLAGCLIENTE = '1'