SELECT 
    CADFOR.NUMERO AS CODIGO,
    CADFOR.NOME AS NOME,
    CADFOR.FANTASIA AS FANTASIA,
    CADFOR.CONTATO AS CONTATO,
    case when CADFOR.CPF = '' or CADFOR.CPF is null then CADFOR.CGC else CADFOR.CPF END AS CNPJ_CNPF,
    case when CADFOR.INSC = '' or CADFOR.INSC is null then CADFOR.CARTIND else CADFOR.INSC END AS IE_RG,  
    CADFOR.E_MAIL AS EMAIL,
    CADFOR.ENDERES AS ENDERECO,
    CADFOR.BAIRRO AS BAIRRO,
    CADFOR.CEP AS CEP,
    CADFOR.CIDADE AS CIDADE,
    CADFOR.UF AS UF,
    CADFOR.FONE1 AS TELEFONE,
    CADFOR.FONE2 AS CELULAR,
    CADFOR.OBS AS OBSERVACOES
FROM CADFOR
