SELECT
    APROD.COD AS CARACTERISTICAS,
    APROD.DESCRICAO AS DESCRICAO,
    APROD.UNID AS UND,
    CADGRU.nome AS GRUPO,
    APROD.CUSTOC AS PRECO_CUSTO,
    APROD.PRECOV AS PRECO_VENDA,
    APROD.ESTMIN AS QTD_IDEAL,
    APROD.PESO AS PESO,
    APROD.MARGEM1 AS MARGEM_LUCRO,
    APROD.CODIGO_FISCAL ||' - '|| APROD.CODCOM AS COD_FABRICANTE,
    APROD.CF_ANALITICA AS COD_NCM, 
    APROD.CST_SUPER_SIMPLES AS ST,
    APROD.CODIGO_CEAN AS BARRAS,
    APROD.CEST AS PERSONAL6
FROM APROD
LEFT JOIN CADGRU ON CADGRU.numero = APROD.GRUPO
