SELECT
    FORNECEDORES.CODIGO_FORNECEDOR AS CODIGO,
    FORNECEDORES.RAZAO_SOCIAL AS NOME,
    FORNECEDORES.NOME_FANTASIA AS FANTASIA,
    FORNECEDORES.CPF_CNPJ AS CNPJ_CNPF,
    FORNECEDORES.INSCRICAO_ESTADUAL AS IE_RG,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.ESTADO AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.TELEFONE AS TELEFONE,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.CELULAR AS CELULAR,
    FORNECEDORES.EMAIL AS EMAIL,
    FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES
