SELECT
    PRO.PRO_CODIGO AS BARRAS,
    GRP.GRP_DESCRICAO AS GRUPO,
    PRO.PRO_DESCRICAO AS DESCRICAO,
    UND.UND_DESCRICAO AS UND,
    PRO.PRO_ESTOQUE AS QTD,
    PRO.PRO_PRECO AS PRECO_VENDA,
    PRO.PRO_PRCCUSTO AS PRECO_CUSTO,
    PRO.PRO_STB AS ST

FROM PRO
LEFT JOIN GRP ON PRO.GRP_CODIGO = GRP.GRP_CODIGO
LEFT JOIN UND ON PRO.UND_CODIGO = UND.UND_CODIGO