select
  clientes.Codigo as codigo,
  clientes.Nome as nome,
  clientes.FantasiaApelido as fantasia,
  clientes.DtCadastro as cadastro,
  clientes.DtNascimento as nascimento,
  clientes.CNPJ_CPF as cnpj_cnpf,
  clientes.IE_RG as ie_rg,
  clientes.IM as im,
  clientes.Endereco as endereco,
  clientes.EndNumero as numero,
  clientes.EndComplemento as complemento,
  clientes.Bairro as bairro,
  clientes.Cidade as cidade,
  clientes.UF as uf,
  clientes.CEP as cep,
  clientes.NomeContato as contato,
  clientes.Telefone1 as telefone,
  clientes.Telefone2 as celular,
  clientes.Internet1 as email,
  clientes.Obs as observacoes,
  clientes.NomePai as pai,
  clientes.NomeMae as mae,
  clientes.NomeConjuge as conjuge
from clientes
