SELECT FORNECEDOR.`forn_cod` AS CODIGO,
FORNECEDOR.`forn_nomecurto` AS FANTASIA,
FORNECEDOR.`forn_nome` AS NOME,
FORNECEDOR.`forn_endereco` AS ENDERECO,
FORNECEDOR.`forn_numero` AS NUMERO,
FORNECEDOR.`forn_complemento` AS COMPLEMENTO,
`fornecedor`.`forn_bairro` AS BAIRRO,
CIDADE.`cid_nome` AS CIDADE,
UF.`uf_sigla` AS UF,
FORNECEDOR.FORN_CEP AS CEP,
FORNECEDOR.`forn_cnpj` AS CNPJ_CNPF,
FORNECEDOR.FORN_IE AS IE_RG,
FORNECEDOR.`forn_telefone` AS TELEFONE,
FORNECEDOR.FORN_FAX AS FAX,
FORNECEDOR.`forn_email` AS EMAIL,
FORNECEDOR.FORN_OBS AS OBSERVACOES,
FORNECEDOR.FORN_CONTATO AS CONTATO
FROM FORNECEDOR 
LEFT JOIN CIDADE ON FORNECEDOR.`forn_cidade`=`cidade`.`cid_cod`
LEFT JOIN UF ON FORNECEDOR.FORN_UF=UF.`uf_cod`
