
SELECT
    PRODUTOS.PRODUTO AS COD_FABRICANTE,
    PRODUTOS.EAN13 AS BARRAS,
    PRODUTOS.DESCRICAO,
    PRODUTOS.UNIDADEMEDIDA AS UND,
    ESTOQUE_PRODUTO.QUANTIDADE  AS QTD,
    GRUPOS_PRODUTOS.DESCRICAO AS GRUPO,
    PRODUTOS.NCM AS COD_NCM,
    PRODUTOS.PRECO_CUSTO,
    PRECO.VALOR AS PRECO_VENDA,
    PRODUTOS.REFERENCIA as PERSONAL1,
    PRODUTOS.ICMS_CST AS ST,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN PRECO ON PRODUTOS.PRODUTO = PRECO.PRODUTO
LEFT JOIN ESTOQUE_PRODUTO ON PRODUTOS.PRODUTO = ESTOQUE_PRODUTO.PRODUTO
LEFT JOIN GRUPOS_PRODUTOS ON PRODUTOS.GRUPOESTOQUE = GRUPOS_PRODUTOS.GRUPO
