select
    clientes.codigo as codigo,
    clientes.nome as nome,
    clientes.endereco as endereco,
    clientes.complemento as complemento,
    clientes.numero as numero,
    clientes.bairro as bairro,
    clientes.cep as cep,
    clientes.cidade as cidade,
    clientes.estado as uf,
    clientes.cpf as cnpj_cnpf,
    case when clientes.inscricao_estadual = '' or clientes.inscricao_estadual is null then clientes.rg else clientes.inscricao_estadual end as ir_rg,
    clientes.telefone as telefone,
    clientes.celular as celular,
    clientes.email as email,
    clientes.sexo as sexo,
    clientes.limite as limite_credito,
    clientes.saldodevedor as valor_em_atraso,
    clientes.estado_civil as est_civil,
    clientes.ultima_compra as ultima_venda,
    clientes.datanas as nascimento,
    clientes.datacadastro as cadastro,
    clientes.observacoes as observacoes
from clientes