SELECT
    ID AS CODIGO,
    DESCRICAO AS DESCRICAO,
    UNIDADE AS UND,
    VALORVENDA AS PRECO_VENDA,
    QUANTIDADE AS QTD,
    CUSTO AS PRECO_CUSTO,
    NCM AS COD_NCM,
    CEST AS PERSONAL6,
    CEAN AS BARRAS,
    PESO AS PESO
FROM PRODUTO
