SELECT 
       CLIENTES.CODIGO AS CODIGO
      ,CLIENTES.RAZAO AS NOME
      ,CLIENTES.NOME AS FANTASIA
      ,CLIENTES.CONTATO AS CONTATO
      ,CLIENTES.INS_RG AS IE_RG
      ,CLIENTES.CGC_CPF AS CNPJ_CNPF
      ,CLIENTES.INSC_MUNICIPAL AS IM
      ,CLIENTES.EMAIL AS EMAIL
      ,CLIENTES.ENDERECO AS ENDERECO
      ,CLIENTES.NUMERO_END AS NUMERO
      ,CLIENTES.CEP AS CEP
      ,CLIENTES.BAIRRO AS BAIRRO
      ,CLIENTES.CIDADE AS CIDADE
      ,CLIENTES.ESTADO AS UF
      ,CLIENTES.FONE AS TELEFONE
      ,CLIENTES.CELULAR AS CELULAR
      ,CLIENTES.FAX AS FAX
      ,CLIENTES.MOTIVO AS OBSERVACOES
      ,CLIENTES.N_PAI AS PAI
      ,CLIENTES.N_MAE AS MAE
      ,CAST (CLIENTES.DATA_NASC AS DATE) AS NASCIMENTO
      ,CAST (CLIENTES.DATA_CAD AS DATE) AS CADASTRO
      ,CLIENTES.EST_CIVIL AS EST_CIVIL
      ,CLIENTES.CONJUGE AS CONJUGE
      ,CLIENTES.LIMITE_CR AS LIMITE_CREDITO
      ,CAST (CLIENTES.ULT_MOV AS DATE) AS ULTIMA_VENDA
      ,CLIENTES.SEXO AS SEXO
  FROM PICINAS.dbo.CLIENTES
  WHERE CLIENTES.CODIGO <> '0'
