SELECT 
       --PRODUTOS.CODIGO AS CODIGO
       PRODUTOS.NOME AS DESCRICAO
      ,MARCAS.NOME AS CARACTERISTICAS
      ,GRUPOS.NOME AS GRUPO
      ,SUB_GRUPOS.NOME AS FAMILIA
      ,PRODUTOS.UNIDADE AS UND
      ,PRODUTOS.UNIDADE_COMPRA AS UND_COMPRA
      ,PRODUTOS.CBARRA AS BARRAS
      ,PRODUTOS.ORIGINAL AS COD_FABRICANTE
      ,PRODUTOS.PESO AS PESO
      ,PRODLOJAS.PCO_REMAR AS PRECO_VENDA
      ,PRODLOJAS.PCO_AREMAR AS PRECO_ATACADO
      ,PRODLOJAS.EST_ATUAL AS QTD 
      ,PRODUTOS.COD_CSTORIGEM AS OST
      ,PRODUTOS.COD_CSTTRIBICMS AS ST
      ,PRODUTOS.CODIGO_NCM AS COD_NCM
      ,CAST (PRODLOJAS.DAT_VENDA AS DATE) AS ULTIMA_VENDA
      ,CAST (PRODUTOS.DATA_ALTERACAO AS DATE) AS ALTERACAO_PRECO
      ,PRODUTOS.COD_CEST AS PERSONAL6
  FROM PICINAS.dbo.PRODUTOS
LEFT JOIN PICINAS.dbo.GRUPOS ON GRUPOS.CODIGO = PRODUTOS.GRUPO
LEFT JOIN PICINAS.dbo.SUB_GRUPOS ON SUB_GRUPOS.CODIGO = PRODUTOS.SUBG
LEFT JOIN PICINAS.dbo.MARCAS ON MARCAS.CODIGO = PRODUTOS.MARCA
LEFT JOIN PICINAS.dbo.PRODLOJAS ON PRODLOJAS.CODIGO = PRODUTOS.CODIGO
