SELECT FORNECEDOR.CODIGO,
FORNECEDOR.RAZAO AS NOME,
FORNECEDOR.ENDERECO,
FORNECEDOR.NUMERO,
FORNECEDOR.BAIRRO,
FORNECEDOR.CIDADE,
FORNECEDOR.ESTADO AS UF,
FORNECEDOR.CEP,
FORNECEDOR.FAX,
FORNECEDOR.TELEFONE1 AS TELEFONE,
FORNECEDOR.TELEFONE2 AS CELULAR,
FORNECEDOR.CNPJ AS CNPJ_CNPF,
FORNECEDOR.INSC AS IE_RG,
FORNECEDOR.NOME AS FANTASIA,
FORNECEDOR.EMAIL,
FORNECEDOR.OBSERVACAO AS OBSERVACOES
FROM FORNECEDOR

