SELECT
    ID_PRODUTO AS CODIGO,
    COD_PRODUTO AS BARRAS,
    PRODUTO AS DESCRICAO,
    ESTOQUE AS QTD,
    CUSTO AS PRECO_CUSTO,
    LUCRO AS MARGEM_LUCRO,
    VENDA AS PRECO_VENDA
FROM TB_PRODUTOS
