SELECT
 -- TBESTOQUE.Codigo AS CODIGO, 
  TBESTOQUE.CodigoBarra AS BARRAS,
  TBESTOQUE.Codigo AS COD_FABRICANTE,
  TBESTOQUE.Produto AS DESCRICAO,
  TBGRUPO.GRUPO AS GRUPO,
  TBESTOQUE.Fabricante AS CARACTERISTICAS,
  TBESTOQUE.PrecoCusto AS PRECO_CUSTO,
  TBESTOQUE.CustoMedio AS CUSTO_MEDIO,
  TBESTOQUE.PrecoVenda AS PRECO_VENDA,
  TBESTOQUE.Qtd AS QTD,
  TBESTOQUE.Unidade AS UND,
  substring(TBESTOQUE.cst from 1 for 1)as ost,
  substring(TBESTOQUE.cst from 2 for 4)as st,
  -- TBESTOQUE.cst AS ST,
  -- TBESTOQUE.SituacaoTribut AS ST,
  TBESTOQUE.CodNCM AS COD_NCM,
  TBESTOQUE.Marca AS FAMILIA,
  TBESTOQUE.NomeFornecedor AS FORNECEDOR,
  TBESTOQUE.CEST AS PERSONAL6
FROM TBESTOQUE
LEFT JOIN TBGRUPO ON TBESTOQUE.GRUPO = TBGRUPO.CONTROLE
