SELECT PRODUTO.IDPRODUTO AS CODIGO,
PRODUTO.UNIDADEMEDIDA AS UND,
PRODUTO.DESCRICAOPRODUTO AS DESCRICAO,
GRUPO.NOMEGRUPO AS GRUPO,
PRODUTO.CUSTO AS PRECO_CUSTO,
PRODUTO.CUSTOMEDIO AS CUSTO_MEDIO,
PRODUTO.SITUACAOTRIBUTARIA AS ST,
ESTOQUE.QTDES AS QTD,
PRODUTO.PRECOAVISTA AS PRECO_VENDA,
PRODUTO.EAN AS BARRAS,
PRODUTO.CODIGONCM AS COD_NCM,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.IDGRUPO=GRUPO.IDGRUPO
LEFT JOIN ESTOQUE ON PRODUTO.IDPRODUTO=ESTOQUE.IDPRODUTO
