SELECT
    IDCLIENTE AS CODIGO,
    RAZAOSOCIAL AS NOME,
    NOMEFANTASIA AS FANTASIA,
    case when RG_IE = '' or RG_IE is null then IE else RG_IE END AS IE_RG,
    CPF_CNPJ AS CNPJ_CNPF,
    FONE AS TELEFONE,
    FAX AS FAX,
    ENDERECO AS ENDERECO,
    NRO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    OBSERVACAO AS OBSERVACOES,
    CONTATO AS CONTATO,
    EMAIL AS EMAIL
FROM CLIENTES
