SELECT
    --CODIGO AS CODIGO,
    CODIGO AS BARRAS,
    EAN AS COD_FABRICANTE,
    DESCRICAO AS DESCRICAO,
    NCM AS COD_NCM,
    CUSTO AS PRECO_CUSTO,
    PRECO AS PRECO_VENDA,
    UN AS UND,
    --CST AS ST,
    PESOLIQ AS PESO,
    CSOSN AS ST,
    ESTOQUE AS QTD,
    CEST AS PERSONAL6,
    CFOP AS CF
FROM PRODUTOS
