SELECT
    PRODUTOS.ID AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.EAN13 AS BARRAS,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    PRODUTOS.UNIDADE AS UND,
    PRODUTOS.ESTOQUE AS QTD,
    PRODUTOS.PRECO_COMPRA AS PRECO_CUSTO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.MARGEM_LUCRO AS MARGEM_LUCRO,
    PRODUTOS.CODIGO_NCM AS COD_NCM,
    CAST (PRODUTOS.DATA_ESTOQUE AS DATE) AS DATA_CADASTRO,
    PRODUTOS.CST_INTERNO AS ST,
    PRODUTOS.COD_CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN GRUPO ON GRUPO.ID = PRODUTOS.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.ID = PRODUTOS.SUBGRUPO
