SELECT
	C.ID AS CODIGO,
	C.DATAINCLUSAO AS CADASTRO,
	C.DATANASCIMENTO AS NASCIMENTO,
	C.RAZAOSOCIAL AS NOME,
	C.FANTASIA,
	C.LOGRADOURO AS ENDERECO,
	C.NUMERO,
	C.BAIRRO,
	C.CEP,
	C.TELEFONE1 AS TELEFONE,
	C.TELEFONE2 AS CELULAR,
	C.TELEFONE3 AS FAX,
	C.EMAIL1 AS EMAIL,
	C.OBS AS OBSERVACOES,
	C.COMPLEMENTO,
	C.CPFCNPJ AS CNPJ_CNPF,
	CASE
		WHEN C.RG = ''
		OR C.RG IS NULL THEN C.IE
		ELSE C.RG
	END AS IE_RG,	
	CI.CIDADE,
	CI.UF
FROM
	CLIENTE C
LEFT JOIN CIDADE CI ON
	CI.CEP = C.CEP
