SELECT
	F.ID AS CODIGO,
	F.RAZAOSOCIAL AS NOME,
	F.FANTASIA,
	F.CPFCNPJ AS CNPJ_CNPF,
	F.RGINSCRICAOE AS IE_RG,
	F.LOGRADOURO AS ENDERECO,
	F.NUMERO,
	F.BAIRRO,
	F.CEP,
	F.TELEFONE1 AS TELEFONE,
	F.TELEFONE2 AS CELULAR,
	F.TELEFONE3 AS FAX,
	F.EMAIL1 AS EMAIL,
	F.CONTATOS AS CONTATO,
	F.OBS AS OBSERVACOES,
	CI.CIDADE,
	CI.UF
FROM
	FORNECEDOR F
LEFT JOIN CIDADE CI ON
	CI.CEP = F.CEP
