SELECT
    CLIENTES.CODIGO_CLI AS CODIGO,
    CLIENTES.RAZAOSOCIAL AS NOME,
    CLIENTES.FANTASIA AS FANTASIA,
    CLIENTES.CONTATO AS CONTATO,
    case when CLIENTES.CPF = '' or CLIENTES.CPF is null then CLIENTES.CNPJCPF else CLIENTES.CPF END AS CNPJ_CNPF,
    case when CLIENTES.IDENTIDADE = '' or CLIENTES.IDENTIDADE is null then CLIENTES.INSCRICAO else CLIENTES.IDENTIDADE END AS IE_RG,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.NUMERO AS NUMERO,
    CLIENTES.COMPLEMENTO_ENDERECO AS COMPLEMENTO,
    CLIENTES.BAIRRO AS BAIRRO,
    MUNICIPIOS_IBGE.MUNICIPIO AS CIDADE,
    UF_IBGE.SIGLA AS UF,
    CLIENTES.CEP AS CEP,
    CLIENTES.TELEFONE AS TELEFONE,
    CLIENTES.CELULAR AS CELULAR,
    CLIENTES.TELEFAX AS FAX,
    CLIENTES.EMAILL AS EMAIL,
    CLIENTES.OBSERVACAO AS OBSERVACOES,
    CLIENTES.LIMITE_CRED AS LIMITE_CREDITO,
    CLIENTES.FILIACAO_PAI AS PAI,
    CLIENTES.FILIACAO_MAE AS MAE,
    CLIENTES.CONJUGUE AS CONJUGE,
    CLIENTES.SEXO AS SEXO,
    CLIENTES.DATA_CADASTRO AS CADASTRO
FROM CLIENTES
LEFT JOIN MUNICIPIOS_IBGE ON MUNICIPIOS_IBGE.COD_MUNICIPIO_IBGE = CLIENTES.CODIGO_CID
LEFT JOIN UF_IBGE ON UF_IBGE.COD_UF = MUNICIPIOS_IBGE.COD_UF_IBGE
WHERE CLIENTES.DATA_CADASTRO IS NOT NULL