SELECT
    PRODUTOS.CODIGO_PRO AS CODIGO,
    PRODUTOS.CODIGO_EAN AS BARRAS,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.UNIDADE_ENTRADA AS UND_COMPRA,
    PRODUTOS.UNIDADE_VENDA AS UND,  
    PRODUTOS.MARCA AS CARACTERISTICAS,
    GRUPOS.GRUPO AS GRUPO,
    SUBGRUPOS.SUBGRUPO AS FAMILIA,
    PRODUTOS.PESO_LIQUIDO AS PESO,
    PRODUTOS.ESTOQUE AS QTD,
    SUBSTRING (SITUACAOTRIB.SITUACAO FROM 1 FOR 1) AS ST,
    PRODUTOS.CUSTO_UNITARIO AS PRECO_CUSTO,
    PRODUTOS.CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTOS.MARGEMLUCRO AS MARGEM_LUCRO,
    PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
    PRODUTOS.PRECO_FATURAMENTO AS PRECO_ATACADO,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.DATA_CADASTRO AS DATA_CADASTRO,
    PRODUTOS.DATA_ALTERACAO AS ALTERACAO_PRECO,
    PRODUTOS.COD_NCM AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN SITUACAOTRIB ON SITUACAOTRIB.CODIGO_SIT = PRODUTOS.CODIGO_SIT
LEFT JOIN GRUPOS ON GRUPOS.CODIGO_GRP = PRODUTOS.CODIGO_GRP
LEFT JOIN SUBGRUPOS ON SUBGRUPOS.CODIGO_SGP = PRODUTOS.CODIGO_SGP