SELECT
  FORNECEDORES.CODIGO AS CODIGO,
  FORNECEDORES.NOME AS NOME,
  FORNECEDORES.CONTATO AS CONTATO,
  FORNECEDORES.ENDERECO AS ENDERECO,
  FORNECEDORES.BAIRRO AS BAIRRO,
  FORNECEDORES.CEP AS CEP,
  CIDADES.CIDADE AS CIDADE,
  CIDADES.UF AS UF,
  FORNECEDORES.CNPJ AS CNPJ_CNPF,
  FORNECEDORES.TELEFONE AS TELEFONE,
  FORNECEDORES.FAX AS FAX,
  FORNECEDORES.IE AS IE_RG,
  FORNECEDORES.EMAIL AS EMAIL,
  FORNECEDORES.OBSERVACAO AS OBSERVACOES,
  FORNECEDORES.NUMERO AS NUMERO,
  FORNECEDORES.IM AS IM
FROM FORNECEDORES
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = FORNECEDORES.CODCIDADE
