SELECT
    PRODUTOS.ID_PRODUTO AS CODIGO,
    PRODUTOS.COD_BARRAS AS BARRAS,
    PRODUTOS.PRODUTO AS DESCRICAO,
    PRODUTOS.UN AS UND,
    PRODUTOS.MARCA AS CARACTERISTICAS,
    PRODUTOS.PESO_LIQUIDO AS PESO,
    PRODUTOS_AJUSTE_ESTOQ_ITENS.QTDE_ATUAL AS QTD,
    PRODUTOS_AJUSTE_ESTOQ_ITENS.PRECO_ATUAL AS PRECO_VENDA,
    SUBSTRING (PRODUTOS.SIT_TRIBUTARIA FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.SIT_TRIBUTARIA FROM 2 FOR 3) AS ST,
    PRODUTOS.REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.NCM_ENTRADA AS COD_NCM,
    PRODUTOS.OBS AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN PRODUTOS_AJUSTE_ESTOQ_ITENS  ON PRODUTOS_AJUSTE_ESTOQ_ITENS.ID_AJUST_EST_ITENS = PRODUTOS.ID_PRODUTO
