SELECT CLIENTES.ID_CLIENTE AS CODIGO,
CLIENTES.NOME_RAZAO AS NOME,
CLIENTES.CNPJ_CPF AS CNPJ_CNPF,
CLIENTES.IE_RG,
CAST(CLIENTES.DATA_CADASTRO AS DATE) AS CADASTRO,
CLIENTES.FONE AS TELEFONE,
CLIENTES.FAX,
CLIENTES.EMAIL,
CLIENTES.CONTATO,
CLIENTES.FAT_COMPL AS COMPLEMENTO,
CLIENTES.NOME_FANTASIA AS FANTASIA,
CLIENTES.FAT_ENDERECO AS ENDERECO,
CLIENTES.FAT_NUMERO AS NUMERO,
CLIENTES.FAT_BAIRRO AS BAIRRO,
CLIENTES.FAT_CIDADE AS CIDADE,
CLIENTES.FAT_CEP AS CEP,
CLIENTES.FAT_UF AS UF
FROM CLIENTES




