SELECT PRODUTOS.ID_PRODUTOS AS CODIGO,
PRODUTOS.CODIGO_COMERCIAL_PROD AS COD_FABRICANTE,
PRODUTOS.EAN AS BARRAS,
PRODUTOS.ID_CLASSIFICACAO AS COD_NCM,
PRODUTOS.SIT_TRIBUTARIA AS ST,
PRODUTOS.DESCRICAO,
PRODUTOS.PRECO_VENDA AS PRECO_VENDA,
PRODUTOS.QUANTIDADE AS QTD,
PRODUTOS.UNIDADE AS UND,
PRODUTOS.PRECO_CUSTO,
PRODUTOS.EAN AS BARRAS
FROM PRODUTOS

