SELECT 
  C.CODCLI AS CODIGO
, C.NOMCLI AS NOME
, C.NOMFAN AS FANTASIA
--, C.LIMITE AS LIMITE_CREDITO
, C.LIMITECRED AS LIMITE_CREDITO
, C.END1 AS ENDERECO
, C.NUMERO
, C.REF1 AS COMPLEMENTO
, C.CEP1 AS CEP
, C.BAIDADOS AS BAIRRO
, CASE WHEN C.CPF = '' OR C.CPF IS NULL THEN C.CGC ELSE C.CPF END AS CNPJ_CNPF
, CASE WHEN C.RG = '' OR C.RG IS NULL THEN C.IE1 ELSE C.RG END AS IE_RG
, C.INSCMUNICIPAL AS IM
, C.FON1 AS TELEFONE
, CAST (C.DTACAD AS DATE) AS CADASTRO
, C.FON2 AS CELULAR
, C.FAX
, C.EMAIL
, C.OBSCLIENTE AS OBSERVACOES
--, C.EST_CLI AS UF
--, C.SIGLAESTADO AS UF
, EM.MUNICIPIO AS CIDADE 
, E.UF 
FROM CLIENTES C
LEFT JOIN ESTADOSMUNICIPIOS EM ON EM.ID = C.CODCID 
LEFT JOIN ESTADOS E ON E.CODIGO = EM.CODEST 
