SELECT 
  F.CODFORN AS CODIGO
, F.RAZSOC AS NOME
, F.NOMFAN AS FANTASIA
, F.CGC AS CNPJ_CNPF
, F.INSCEST AS IE_RG
, F.END1 AS ENDERECO
, F.NUM AS NUMERO
, F.COMPL AS COMPLEMENTO
, F.BAIRRO
, F.CEP
, F.FONE AS TELEFONE
, F.FAX
, F.EMAIL
, EM.MUNICIPIO AS CIDADE 
, E.UF 
FROM FORNECEDOR F
LEFT JOIN ESTADOSMUNICIPIOS EM ON EM.ID = F.CODCID 
LEFT JOIN ESTADOS E ON E.CODIGO = EM.CODEST 
