SELECT
PEOPLE.ID AS CODIGO,
PEOPLE.NAME AS NOME,
PEOPLE.FANTASY AS FANTASIA,
PEOPLE.CONTACT AS CONTATO,
PEOPLE.CGC AS CNPJ_CNPF,
PEOPLE.IERG AS IE_RG,
PEOPLE.ADDRESS AS ENDERECO,
PEOPLE.NUMBER AS NUMERO,
PEOPLE.NEIGHBORHOOD AS BAIRRO,
PEOPLE.COMPLEMENT AS COMPLEMENTO,
PEOPLE.CEP AS CEP,
PEOPLE.ID_CITY,
PEOPLE.PHONE AS TELEFONE,
PEOPLE.CELL_PHONE AS CELULAR,
PEOPLE.EMAIL AS email,
PEOPLE.ADMISSION_DATE AS CADASTRO,
PEOPLE.OBSERVATION AS OBSERVACOES,
CITY.description AS CIDADE,
CITY.UF AS UF
FROM PEOPLE
LEFT JOIN CITY ON CITY.id = PEOPLE.ID_CITY
WHERE PEOPLE.KIND <> '4'




