SELECT
    TPRODUTOS. CODIGO AS CODIGO,
    TPRODUTOS. CODIGO_BARRAS AS BARRAS,
    TPRODUTOS. UNIDADE AS UND,
    TPRODUTOS. DESCRICAO AS DESCRICAO,
    TPRODUTOS. ID_GRUPO_PRODUTO,
    TPRODUTOS. OBSERVACAO AS OBSERVACOES,
    TPRODUTOS. ESTOQUE_MINIMO AS QTD_IDEAL,
    TPRODUTOS. ESTOQUE AS QTD,
    TPRODUTOS. CSOSN AS ST,
    TPRODUTOS. PRECO_CUSTO AS PRECO_CUSTO,
    TPRODUTOS. PRECO_VENDA AS PRECO_VENDA,
    TPRODUTOS. MARGEM_LUCRO AS MARGEM_LUCRO,
    TPRODUTOS. ID_REFERENCIA AS COD_FABRICANTE,
    TPRODUTOS. DATA_CADASTRO AS DATA_CADASTRO,
    TPRODUTOS. NCM AS COD_NCM,
    TPRODUTOS. CEST AS PERSONAL6
FROM TPRODUTOS
LEFT JOIN tgrupos_produtos ON tgrupos_produtos.id_grupo_produto = TPRODUTOS. ID_GRUPO_PRODUTO
