SELECT PRODUTO.COD_PRO AS CODIGO,
PRODUTO.VALOR_PRO AS PRECO_VENDA,
PRODUTO.NOME_PRO AS DESCRICAO,
PRODUTO.COD_NCM,
PRODUTO.COD_PRODUTO_ESTOQUE AS CODIGO,
PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
GRUPO_ICMS.CST AS ST,
PRODUTO.UNIDADE AS UND,
PRODUTO.PRECO_CUSTO,
PRODUTO.ESTOQUE AS QTD,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN GRUPO_ICMS ON PRODUTO.ICMS_CF_EST=GRUPO_ICMS.COD_GRP

