SELECT
    PRODUTO_ID AS CODIGO,
    NOMEPRO AS DESCRICAO,
    UNIDADE AS UND,
    PRECO_CUSTO,
    PRECO_VENDA,
    CODEAN AS BARRAS,
    ESTOQUE_ATUAL AS QTD,
    NCM AS COD_NCM,
    CEST AS PERSONAL6
FROM PRODUTOS
