SELECT
	PAR_PKN_CODIGO AS CODIGO,
	PAR_A_RAZAOSOCIAL AS NOME,
	PAR_A_NOME_FANTASIA AS FANTASIA,
	CONCAT (COALESCE(PAR_A_LOGRADOURO, ''),' ',COALESCE(PAR_A_ENDERECO, '')) AS ENDERECO,
	PAR_A_NUMERO AS NUMERO,
	PAR_A_COMPLEMENTO AS COMPLEMENTO,
	PAR_A_BAIRRO AS BAIRRO,
	PAR_A_CIDADE AS CIDADE,
	PAR_A_ESTADO AS UF,
	PAR_A_CEP AS CEP,
	CASE WHEN PAR_A_CPF = '' OR PAR_A_CPF IS NULL THEN PAR_A_CNPJ_CPF ELSE PAR_A_CPF END AS CNPJ_CNPF,
	CASE WHEN PAR_A_RG = '' OR PAR_A_RG IS NULL THEN PAR_A_CGF ELSE PAR_A_RG END AS IE_RG,
	PAR_INSC_MUNICIPAL AS IM,
	PAR_A_FONE1 AS TELEFONE,
	PAR_A_FONE2 AS CELULAR,
	PAR_A_FONE3 AS FAX,
	PAR_A_FONE4 AS PERSONAL2,
	PAR_A_CONTATO AS CONTATO,
	PAR_A_EMAIL AS EMAIL,
	PAR_A_OBS_FINANCEIRA AS OBSERVACOES
FROM
	TB_PAR_PARTICIPANTE
WHERE PAR_A_TIPO = 'FORNECEDOR'
