SELECT
    F.CRE_CODIGO AS CODIGO,
    F.CRE_NOME AS NOME,
    F.CRE_FANTASIA AS FANTASIA,
    F.CRE_CONTATO AS CONTATO,
    F.CRE_CNPJ AS CNPJ_CNPF,
    F.CRE_CGF AS IE_RG,
    F.CRE_ENDERECO AS ENDERECO,
    F.CRE_BAIRRO AS BAIRRO,
    F.CRE_COMPL_ENDERECO AS COMPLEMENTO,
    F.CRE_NUMERO AS NUMERO,
    F.CRE_CEP AS CEP,
    M.MUN_NOME AS CIDADE,
    F.CRE_UF AS UF,
    replace(F.CRE_FONE,'-','') AS TELEFONE,
    F.CRE_CELULAR AS CELULAR,
    F.CRE_FAX AS FAX,
    F.CRE_EMAIL AS EMAIL,
    F.CRE_OBS AS OBSERVACOES,
    case when F.CRE_SITUACAO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO
FROM CREDORES AS F
LEFT JOIN MUNICIPIOS M ON M.MUN_CODIGO = F.MUN_CODIGO
