SELECT
    PF.CODPRODFILHO,
    PF.CODPRODUTO AS CODIGO,
    PF.DESCRICAO AS DESCRICAO,
    PF.ESTQMIN AS QTD_IDEAL,
    PF.PRECOPRATICADO1 AS PRECO_VENDA,
    CAST (PF.DTULTMAVENDA AS DATE) AS ULTIMA_VENDA,
    CAST (PF.DTULTMACOMPRA AS DATE) AS ULTIMA_COMPRA,
    U.SIGLA AS UND,
    PF.ESTQATUAL AS QTD,
    PF.CODPESQ1 AS BARRAS,
    PF.CUSTOREPOSI AS PRECO_CUSTO,
    PF.CUSTOMEDIO AS CUSTO_MEDIO,
    --PF.TRIBUTADO,
    CAST (PF.DT_CADAST AS DATE) AS DATA_CADASTRO,
    CAST (PF.DT_MODIFI AS DATE) AS ALTERACAO_PRECO,
    PF.CLASSFISCAL AS COD_NCM,
    MAX (C.CODIGOCEST) AS PERSONAL6
FROM PRODFILHO AS PF
LEFT JOIN CEST C ON PF.CLASSFISCAL = C.CODIGONCM
LEFT JOIN UNIDADE U ON PF.CODUNIDADE = U.CODUNIDADE
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
