SELECT
    RAZAOSOCIAL AS NOME,
    NOMEFANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    NUMERO AS NUMERO,
    COMPLEMENTO AS COMPLEMENTO,
    TELEFONE AS TELEFONE,
    CELULAR AS CELULAR,
    EMAIL AS EMAIL,
    OBS1 AS OBSERVACOES
FROM CLIENTE
