SELECT
       CLIENTE.COD_CLIENTE AS CODIGO,
       CLIENTE.RAZAO_SOCIAL AS NOME,
       CLIENTE.FANTASIA AS FANTASIA,
       LOGRADOURO.DESCRICAO AS ENDERECO,
       ENDERECONEW.COMPLEMENTO AS COMPLEMENTO,
       BAIRRO.DESCRICAO AS BAIRRO,
       MUNICIPIO.DESCRICAO AS CIDADE,
       ESTADO.UF AS UF,
       ENDERECONEW.NUMERO AS NUMERO,
       ENDERECONEW.FONE_1 AS TELEFONE,
       ENDERECONEW.FAX AS FAX,
       ENDERECONEW.CELULAR AS CELULAR,
       ENDERECONEW.OBSERVACAO AS OBSERVACOES,
       case when ENDERECONEW.INSC_ESTADUAL = '' or  ENDERECONEW.INSC_ESTADUAL is null then ENDERECONEW.RG else ENDERECONEW.INSC_ESTADUAL END as IE_RG,
       ENDERECONEW.INSC_MUNICIPAL AS IM,
       ENDERECONEW.CEP AS CEP,
       ENDERECONEW.CONTATO AS CONTATO,
       ENDERECONEW.EMAIL_1 AS EMAIL,
       CLIENTE.DATA_CADASTRO AS CADASTRO,
       CLIENTE.DATA_NASCIMENTO AS NASCIMENTO,
       CLIENTE.CNPJ_CPF AS CNPJ_CNPF,
       CLIENTE.LIMITE_CREDITO AS LIMITE_CREDITO
FROM CLIENTE
JOIN ENDERECOnew ON ENDERECOnew.CODIGO = CLIENTE.COD_CLIENTE and endereconew.cadastro = 'CLI'
LEFT JOIN ESTADO ON ESTADO.COD_ESTADO = ENDERECONEW.COD_ESTADO
LEFT JOIN MUNICIPIO ON MUNICIPIO.COD_MUNICIPIO = ENDERECONEW.COD_MUNICIPIO AND ESTADO.COD_ESTADO=MUNICIPIO.COD_ESTADO
LEFT JOIN BAIRRO ON BAIRRO.COD_BAIRRO = ENDERECONEW.COD_BAIRRO AND MUNICIPIO.COD_MUNICIPIO = BAIRRO.COD_MUNICIPIO AND ESTADO.COD_ESTADO = BAIRRO.COD_ESTADO
LEFT JOIN LOGRADOURO ON LOGRADOURO.COD_LOGRADOURO = ENDERECONEW.COD_LOGRADOURO AND ESTADO.COD_ESTADO = LOGRADOURO.COD_ESTADO AND MUNICIPIO.COD_MUNICIPIO = LOGRADOURO.COD_MUNICIPIO AND BAIRRO.COD_BAIRRO = LOGRADOURO.COD_BAIRRO
