SELECT
    TB_PESSOA.PES_ID AS CODIGO,
    TB_PESSOA.PES_RSOCIAL_NOME AS NOME,
    TB_PESSOA.PES_FANTASIA_APELIDO AS FANTASIA,
    TB_PESSOA.PES_CNPJ_CPF AS CNPJ_CNPF,
    TB_PESSOA.PES_IE_RG AS IE_RG,
    TB_PESSOA.PES_ENDERECO AS ENDERECO,
    TB_PESSOA.PES_COMPLEMENTO AS COMPLEMENTO,
    TB_PESSOA.PES_NUMERO AS NUMERO,
    TB_PESSOA.PES_BAIRRO AS BAIRRO,
    TB_CIDADE.CID_NOME AS CIDADE,
    TB_ESTADO.est_sigla AS UF,
    TB_PESSOA.PES_CEP AS CEP,
    TB_PESSOA.PES_TELEFONE AS TELEFONE,
    TB_PESSOA.PES_CELULAR AS CELULAR,
    TB_PESSOA.PES_EMAIL AS EMAIL
FROM TB_PESSOA
LEFT JOIN TB_CIDADE ON TB_PESSOA.PES_CIDADE = TB_CIDADE.CID_ID
LEFT JOIN TB_ESTADO ON TB_ESTADO.est_id = TB_CIDADE.cid_estado
WHERE TB_PESSOA.PES_FORNECEDOR = 'S'
