SELECT
    TB_PRODUTO.PRD_ID AS CODIGO,
    TB_PRODUTO.PRD_DESCRICAO AS DESCRICAO,
    TB_PRODUTO_ESTOQUE.PRDE_ESTOQUE AS QTD,
    TB_PRODUTO.PRD_PRECO_CUSTO AS PRECO_CUSTO,
    TB_PRODUTO.PRD_UN_VENDA AS UND,
    TB_PESSOA.pes_rsocial_nome AS FORNECEDOR,
    TB_PRODUTO.PRD_LUCRO AS MARGEM_LUCRO,
    TB_PRODUTO.PRD_PRECO_VENDA AS PRECO_VENDA,
    TB_PRODUTO.prd_observacao AS OBSERVACOES,
    TB_PRODUTO.PRD_NCM AS COD_NCM,
    TB_PRODUTO_TRIBUTO.PRDT_CEST AS PERSONAL6,
    TB_PRODUTO_TRIBUTO.PRDT_ICMS_CSOSN AS ST,
    TB_PRODUTO_TRIBUTO.PRDT_CONFINS_CST_SAI AS COFINS_CODIGO,
    TB_PRODUTO_TRIBUTO.PRDT_PIS_CST_SAI AS PIS_CODIGO
FROM TB_PRODUTO
LEFT JOIN TB_PRODUTO_ESTOQUE ON TB_PRODUTO.PRD_ID = TB_PRODUTO_ESTOQUE.PRDE_PRODUTO
LEFT JOIN TB_PRODUTO_TRIBUTO ON TB_PRODUTO.PRD_ID = TB_PRODUTO_TRIBUTO.PRDT_PRODUTO
LEFT JOIN TB_PESSOA ON TB_PESSOA.pes_id = TB_PRODUTO.prd_fornecedor
