SELECT
  CONTAS_PAGAR.ID AS NUM_CONTA,
  CONTAS_PAGAR.ID_FORNECEDOR AS COD_FORNECEDOR,
  FORNECEDOR.RAZ_SOCIAL AS NOM_FORNECEDOR,
  CONTAS_PAGAR.DT_CONTA AS EMISSAO,
  CONTAS_PAGAR.DT_VENC AS VENCIMENTO,
  CONTAS_PAGAR.VLR_CONTA AS VALOR_DUP,
  CONTAS_PAGAR.VLR_DESCONTO AS VALOR_DES,
  CONTAS_PAGAR.VLR_JUROS AS VALOR_JUR,
  CONTAS_PAGAR.VLR_QUITACAO AS VAL_PAG,
  CONTAS_PAGAR.DT_QUITACAO AS PAGAMENTO,
  CONTAS_PAGAR.NUMERO_DOCUMENTO ||'-'|| CONTAS_PAGAR.ID  AS DOCUMENTO,
  CONTAS_PAGAR.PARCELA AS OBSERVACOES,
  CONTAS_PAGAR.TIPO_DOC AS TIPO_DOC,
  CONTAS_PAGAR.NRO_NF ||' -/- '|| CONTAS_PAGAR.HISTORICO AS HISTORICO,
  FORNECEDOR.CNPJ
  FROM CONTAS_PAGAR
  LEFT JOIN FORNECEDOR ON FORNECEDOR.ID_FORNECEDOR = CONTAS_PAGAR.ID_FORNECEDOR
