SELECT
  CLIENTES.ID_CLIENTE AS COD_CLIENTE,
  CLIENTES.RAZ_SOCIAL AS NOM_CLIENTE,
  CONTAS_RECEBER.DT_CONTA AS EMISSAO,
  CONTAS_RECEBER.DT_VENC AS VENCIMENTO,
  CONTAS_RECEBER.HISTORICO ||'-/-'|| CONTAS_RECEBER.PARCELA AS HISTORICO,
  CONTAS_RECEBER.TIPO_DOC AS TIPO_DOC,
  CONTAS_RECEBER.NOSSO_NUMERO AS NOSSO_NUM,
  CONTAS_RECEBER.NUMERO_DOCUMENTO ||' '|| CONTAS_RECEBER.ID AS DOCUMENTO,
  CONTAS_RECEBER.VLR_CONTA AS VALOR_DUP,
  CONTAS_RECEBER.VLR_DESCONTO AS VALOR_DES,
  CONTAS_RECEBER.VLR_JUROS AS VALOR_JUR,
  CONTAS_RECEBER.VLR_QUITACAO AS VALOR_REC,
  CONTAS_RECEBER.DT_QUITACAO AS RECEBIMENTO,
  CONTAS_RECEBER.NUMERO_PARCELA AS NUM_PARCELA,
  CONTAS_RECEBER.CENTRO_CUSTO AS CTO_CUSTO,
  0 AS BANCO,
  0 AS CONTA,
  CLIENTES.CPF_CNPJ AS CNPJ
FROM CONTAS_RECEBER
LEFT JOIN CLIENTES ON CLIENTES.ID_CLIENTE = CONTAS_RECEBER.ID_CLIENTE
