SELECT
  CLIENTE.CLIENTE AS NOME,
  CLIENTE.ENDERECO AS ENDERECO,
  CLIENTE.BAIRRO AS BAIRRO,
  CLIENTE.CEP AS CEP,
  CLIENTE.SEXO AS SEXO,
  CLIENTE.CELULAR AS CELULAR,
  CLIENTE.FONE AS TELEFONE,
  CLIENTE.EMAIL AS EMAIL,
  CLIENTE.ESTADO_CIVIL AS EST_CIVIL,
  CLIENTE.NASCIMENTO AS NASCIMENTO,
  CLIENTE.RG_IE AS IE_RG,
  CLIENTE.APELIDO AS CONTATO,
 cast( CLIENTE.CADASTRO AS date)as CADASTRO,
  CLIENTE.LIMITE_CREDITO AS LIMITE_CREDITO,
  CLIENTE.PAI AS PAI,
  CLIENTE.MAE AS MAE,
  CLIENTE.CONJUGE AS CONJUGE,
  CLIENTE.PROFISSAO AS PROFISSAO,
  CLIENTE.CNPJ_CPF AS CNPJ_CNPF,
  CLIENTE.CIDADE AS CIDADE,
  ESTADOS.uf AS UF
FROM CLIENTE
LEFT JOIN ESTADOS ON ESTADOS.ID_UF = CLIENTE.ID_UF
