SELECT
	CF.ID_FORNECEDOR AS CODIGO,
	CF.DESCRICAO AS NOME,
	CF.FANTASIA,	
	CF.ENDERECO,
	CF.CEP,
	CF.BAIRRO,
	CF.COMPLEMENTO,
	CF.NUMERO,
	CF.CPF_CNPJ AS CNPJ_CNPF,
	CASE WHEN CF.RG_NUM = '' OR CF.RG_NUM IS NULL THEN CF.IE ELSE CF.RG_NUM END AS IE_RG,
	CF.CONTATO,
	CF.FONE AS TELEFONE,
	CF.FAX,
	CF.CELULAR,
	CF.EMAIL,
	CF.FONE_FORNECEDOR AS PERSONAL1,
	CF.FONE2_FORNECEDOR AS PERSONAL2,
	CF.OBS AS OBSERVACOES,
	CF.EMAIL_FORNECEDOR AS PERSONAL3
FROM
	CAD_FORNECEDOR CF
LEFT JOIN CAD_MUNICIPIO CM ON CM.ID_MUNICIPIO = CF.ID_MUNICIPIO 