SELECT
	CP.ID_PRODUTO AS CODIGO,
	CP.DESCRICAO,
	CP.COD_BARRAS AS BARRAS,
	CP.REFERENCIA AS PERSONAL5, 
	CP.CODIGO_FORNECEDOR AS COD_FABRICANTE, 	
	CP.UNIDADE AS UND,
	CP.EST_MINIMO AS QTD_IDEAL,
	CASE CP.ATIVO WHEN '1' THEN 'Ativo' ELSE 'Inativo' END AS SITUACAO,
	CP.DT_CADASTRO AS DATA_CADASTRO,
	CP.PERC_LUCRO AS MARGEM_LUCRO,
	CP.CUSTO_TOTAL AS PRECO_CUSTO,
	CP.CUSTO_MEDIO,	
	CP.PERC_MARKUP_1 AS MARGEM_LUCRO,	
	CP.PRECO_AVISTA AS PRECO_VENDA,
	CP.PRECO_PRAZO AS PERSONAL1,
--	CP.PRECO3 AS PERSONAL2,
	CP.IPPT,
	CP.TIPO_ITEM AS PERSONAL4,
	REPLACE (CP.COD_CLAFISCAL,'.','') AS COD_NCM,
	CP.PESO_PRODUTO AS PESO,
	CP.PERC_COMISSAO AS COMISSAO,
	CP.OBS AS OBSERVACOES,
	CP.CEST AS PERSONAL6,
	CP.ANP AS COD_NCM,
	CP.DT_ULTIMA_ENTRADA AS ULTIMA_COMPRA,
	CP.DT_ULTIMA_SAIDA AS ULTIMA_VENDA,
	CP.BALANCA_DIAS_VALIDADE AS VALIDADE_DIAS,
	SE.QTDADE AS QTD,
	SE.VALOR AS PERSONAL2,
	CG.DESCRICAO AS GRUPO,
	CS.DESCRICAO AS FAMILIA,
	CM.DESCRICAO AS CARACTERISTICAS,
	LEFT (REPLACE (CST.CFOP_DENTRO,'.',''),3) AS ELO,
	CST.IPI_CST AS IPI_CODIGO_VENDA,
	CST.IPI_ALIQUOTA AS ALIQ_IPI_VENDA,	
	CST.PIS_CST AS PIS_CODIGO,
	CST.PIS_ALIQUOTA AS PIS_ALIQ_NOR,
	CST.COFINS_CST AS COFINS_CODIGO,
	CST.COFINS_ALIQUOTA AS COFINS_ALIQ_NOR,
	CI.COD_ST AS ST
FROM
	CAD_PRODUTO CP
LEFT JOIN SLD_ESTOQUE SE ON SE.ID_PRODUTO = CP.ID_PRODUTO 	
LEFT JOIN CAD_EMPRESA CE ON CE.ID_EMPRESA = SE.ID_EMPRESA
LEFT JOIN CAD_GRUPO CG ON CG.ID_GRUPO = CP.ID_GRUPO 
LEFT JOIN CAD_SUBGRUPO CS ON CS.ID_SUBGRUPO = CP.ID_SUBGRUPO AND CS.ID_GRUPO = CG.ID_GRUPO 
LEFT JOIN CAD_MARCA CM ON CM.ID_MARCA = CP.ID_MARCA 
LEFT JOIN CAD_SIT_TRIBUTARIA CST ON CST.ID_SIT_TRIBUTARIA = CP.ID_SIT_TRIB 
LEFT JOIN CAD_ICMS CI ON CI.ID_SIT_TRIBUTARIA = CST.ID_SIT_TRIBUTARIA AND CE.UF = CI.UF
