SELECT CLIENTES.CODIGO,
CLIENTES.NOME,
CLIENTES.NOMEFANTASIA AS FANTASIA,
CLIENTES.ENDERECOR AS ENDERECO,
CLIENTES.CIDADER AS CIDADE,
CLIENTES.BAIRROR AS BAIRRO,
CLIENTES.CEPR AS CEP,
CLIENTES.UFR AS UF,
CASE WHEN CLIENTES.CPF='' THEN CLIENTES.CNPJ
ELSE CLIENTES.CPF END AS CNPJ_CNPF,
CLIENTES.INSCRICAO AS IE_RG,
CLIENTES.FONERESIDENCIAL AS TELEFONE,
CLIENTES.FONEMOVEL AS CELULAR,
-- CAST(CLIENTES.DTCADASTRO AS DATE) AS CADASTRO,
CLIENTES.EMAIL1 AS EMAIL,
CLIENTES.CONTATO,
CLIENTES.NUMEROR AS NUMERO
FROM CLIENTES

