SELECT FORN.COD_FORN AS CODIGO,
FORN.RAZAO_SOCIAL AS NOME,
FORN.NOME_FANTASIA AS FANTASIA,
FORN.CNPJ AS CNPJ_CNPF,
FORN.INSC_ESTADUAL AS IE_RG,
FORN.ENDERECO,
FORN.COMPLEMENTO,
FORN.BAIRRO,
FORN.CIDADE,
FORN.UF,
FORN.TELEFONE,
FORN.FAX,
FORN.CEP,
FORN.EMAIL,
FORN.NUMERO
FROM FORN

