SELECT
	ESTOQUE.CODIGO,
	ESTOQUE.DESCRICAO,
	ESTOQUE.LABOR AS CARACTERISTICAS,
	ESTOQUE.QUANTIDADE AS QTD,
	ESTOQUE.PRECO AS PRECO_VENDA,
	ESTOQUE.DATACAD AS DATA_CADASTRO,
	ESTOQUE.MINIMO AS QTD_IDEAL,
	ESTOQUE.BARRA AS BARRAS,
	ESTOQUE.BARRA2 AS COD_FABRICANTE,
	ESTOQUE.CUSTO AS PRECO_CUSTO,
	ESTOQUE.CMEDIO AS CUSTO_MEDIO,
	ESTOQUE.VENDA AS ULTIMA_VENDA,
	ESTOQUE.COMPRA AS ULTIMA_COMPRA,
	ESTOQUE.COMISSAO,
	ESTOQUE.IPPT,
	ESTOQUE.NBM AS COD_NCM,
	ESTOQUE.PISCOFINS AS PIS_CODIGO,
	ESTOQUE.PISCOFINS AS COFINS_CODIGO,
	ESTOQUE.CSTICMSAI AS ST,
	CASE
		ESTOQUE.DESATIVADO WHEN '1' THEN 'Inativo'
		ELSE 'Ativo'
	END AS SITUACAO,
	--  ESTOQUE.CSOSN AS ST,
	--  ESTOQUE.CSTPISSAI AS PIS_CODIGO,
	ESTOQUE.CSTPISENT AS PISE_CODIGO,
	--  ESTOQUE.CSTCOFSAI AS COFINS_CODIGO,
	ESTOQUE.CSTCOFENT AS COFINSE_CODIGO,
	ESTOQUE.CEST AS PERSONAL6,
	LEFT (ESTOQUE.UNIDADE,6) AS UND,
	CATEGORIA.DESCRICAO AS FAMILIA,
	GRUPO.DESCRICAO AS GRUPO
FROM
	ESTOQUE
LEFT JOIN GRUPO ON ESTOQUE.GRUPO = GRUPO.CODIGO AND GRUPO.SR_DELETED <> 'T'
LEFT JOIN CATEGORIA ON CATEGORIA.CODIGO = ESTOQUE.CATEGPROD
WHERE ESTOQUE.CODIGO NOT IN ('XX-01', 'XX-02', 'XX-03', 'XX-04', 'XX-05', 'XX-06')