
SELECT
    PRODUTO.COD_PRO AS CODIGO,
    PRODUTO.NOME_PRO AS DESCRICAO,
    PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
    UNIDADE_MEDIDA.SIGLA AS UND,
    UNIDADE_MEDIDA.SIGLA AS UND_COMPRA,
    PRODUTO.PESOLIQUIDO AS PESO,
    PRODUTO.ESTOQUE_MINIMO_PRO AS QTD_IDEAL,
    ESTOQUE.ESTOQUE AS QTD,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO.PRECO_CUSTO_MEDIO AS CUSTO_MEDIO,
    PRODUTO.MARGEM_LUCRO_PRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_PRO AS PRECO_VENDA,
    PRODUTO.CST_CONT_EST AS ST,
    PRODUTO.CFOP_VENDAS_CONT_EST AS CF,
    PRODUTO.LOCALIZACAO_PRO AS OBSERVACOES,
    PRODUTO.REFERENCIA_PRO AS COD_FABRICANTE,
    PRODUTO.COD_NCM AS COD_NCM,
    MAX (TAB_CEST.cest) AS PERSONAL6,
    PRODUTO.DATA_CADASTRO AS DATA_CADASTRO
FROM PRODUTO
LEFT JOIN UNIDADE_MEDIDA ON UNIDADE_MEDIDA.CODIGO = PRODUTO.CODIGO_UNIDADE_SAIDA
LEFT JOIN ESTOQUE ON ESTOQUE.COD_PRO = PRODUTO.COD_PRO
LEFT JOIN TAB_CEST ON TAB_CEST.ncm = PRODUTO.COD_NCM
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19
