SELECT
  PRODUTOS.PRO_CODIGO_BARRA AS BARRAS,
  PRODUTOS.PRO_DESCRICAO AS DESCRICAO,
  FORNECEDOR.FOR_DESCRICAO AS FORNECEDOR,
  PRODUTOS.PRO_UNIDADE AS UND,
  PRODUTOS.PRO_PRECO_COMPRA AS PRECO_CUSTO,
  PRODUTOS.PRO_MARGEM_LUCRO AS MARGEM_LUCRO,
  PRODUTOS.PRO_PRECO_VENDA AS PRECO_VENDA,
  PRODUTOS.PRO_ESTOQUE_ATUAL AS QTD,
  PRODUTOS.PRO_ESTOQUE_MINIMO AS QTD_IDEAL,
  PRODUTOS.PRO_DATA_COMPA AS ULTIMA_COMPRA,
  PRODUTOS.PRO_DATA_VENDA AS ULTIMA_VENDA,
  PRODUTOS.PRO_DATA_AUTERACAO AS ALTERACAO_PRECO,
  GRUPO.GRU_DESC AS GRUPO,
  PRODUTOS.PRO_NCM AS COD_NCM,
  NCM_CEST.CESTCOD AS PERSONAL6,
  PRODUTOS.PRO_PESO AS PESO,
  PRODUTOS.PRO_OBS AS OBSERVACOES
FROM PRODUTOS
LEFT JOIN FORNECEDOR ON FORNECEDOR.FOR_CODIGO = PRODUTOS.PRO_FORNECEDOR
LEFT JOIN GRUPO ON GRUPO.GRU_COD = PRODUTOS.PRO_GRUPO
LEFT JOIN NCM_CEST ON NCM_CEST.NCMCOD = PRODUTOS.PRO_NCM
