SELECT
    ITENS.ID_ITEM AS CODIGO,
    GRUPOS.descricao AS GRUPO,
    ITENS.CODIGO AS COD_FABRICANTE,
    ITENS.DESCRICAO,
    ITENS.ESTOQUE AS QTD,
    ITENS.CODIGO_BARRAS AS BARRAS,
    ITENS.UNIDADE AS UND,
    ITENS.NCM AS COD_NCM,
    ITENS.CEST AS PERSONAL6,
    ITENS.PRECO_CUSTO,
    ITENS.PRECO_VENDA
    FROM ITENS
    LEFT JOIN GRUPOS ON ITENS.ID_GRUPO = GRUPOS.id_grupo
