SELECT PRODUTOS.PRO_COD AS CODIGO,
PRODUTOS.PRO_GTIN AS BARRAS,
PRODUTOS.PRO_DES AS DESCRICAO,
PRODUTOS.PRO_UNI_MED AS UND,
PRODUTOS.PRO_VAL_UNI AS PRECO_VENDA,
PRODUTOS.NCM  AS COD_NCM,
PRODUTOS.CST_ICMS AS ST,
PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS

