SELECT
  CADASTROS.ID_CADASTRO AS CODIGO,
  CADASTROS.NOME AS NOME,
  CADASTROS.ENDERECO AS ENDERECO,
  CADASTROS.BAIRRO AS BAIRRO,
  CADASTROS.CIDADE AS CIDADE,
  CADASTROS.ID_ESTADO AS UF,
  CADASTROS.CEP AS CEP,
  CADASTROS.FONE AS TELEFONE,
  CADASTROS.CELULAR AS CELULAR,
  CADASTROS.FAX AS FAX,
  case when CADASTROS_PF.CPF = '' or CADASTROS_PF.CPF is null then CADASTROS_PJ.CNPJ else CADASTROS_PF.CPF END AS CNPJ_CNPF,
  case when CADASTROS_PF.RG = '' or CADASTROS_PF.RG is null then CADASTROS_PJ.I_ESTADUAL else CADASTROS_PF.RG END AS IE_RG,
  CADASTROS_PJ.FANTASIA AS FANTASIA,
  CADASTROS_PJ.I_MUNICIPAL AS IM,
  CADASTROS.CLIENTE,
  CADASTROS.FORNECEDOR,
  CADASTROS.OBSERVACAO AS OBSERVACOES,
  CADASTROS.E_MAIL AS EMAIL,
  CADASTROS.NUMERO AS NUMERO,
  CADASTROS.COMPLEMENTO AS COMPLEMENTO
FROM CADASTROS
LEFT JOIN CADASTROS_PF ON CADASTROS_PF.ID_CADASTRO = CADASTROS.ID_CADASTRO
LEFT JOIN CADASTROS_PJ ON CADASTROS_PJ.ID_CADASTRO = CADASTROS.ID_CADASTRO
WHERE CADASTROS.FORNECEDOR = 'SIM'
