SELECT
  PRODUTOS.ID_PRODUTO AS CODIGO,
  SETORES.DESCRICAO AS GRUPO,
  PRODUTOS.DESCRICAO AS DESCRICAO,
  PRODUTOS_BARRAS.ID_PRODUTO_BARRA AS BARRAS,
  PRODUTOS_BARRAS.PRECO_1 AS PRECO_VENDA,
  PRODUTOS_BARRAS.MARGEM_1 AS MARGEM_LUCRO,
  PRODUTOS_BARRAS.CUSTO AS PRECO_CUSTO,
  PRODUTOS_EMPRESA.ESTOQUE AS QTD,
  PRODUTOS_EMPRESA.COMPRA AS ULTIMA_COMPRA,
  PRODUTOS_EMPRESA.VENDA AS ULTIMA_VENDA,
  PRODUTOS.REFERENCIA AS OBSERVACOES,
  PRODUTOS.ID_UNIDADE AS UND,
  PRODUTOS.CLASSIFICACAO AS COD_NCM,
  MIN (CEST.CEST) AS PERSONAL6,
  PRODUTOS.CST AS ST,
  PRODUTOS.PESO_LIQUIDO AS PESO,
  PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN PRODUTOS_BARRAS ON PRODUTOS_BARRAS.ID_PRODUTO = PRODUTOS.ID_PRODUTO
LEFT JOIN PRODUTOS_EMPRESA ON PRODUTOS_EMPRESA.ID_PRODUTO_BARRA = PRODUTOS_BARRAS.ID_PRODUTO_BARRA
LEFT JOIN SETORES ON SETORES.ID_SETOR = PRODUTOS.ID_SETOR
LEFT JOIN CEST ON CEST.NCM = PRODUTOS.CLASSIFICACAO
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17
