SELECT
    CLIENTE.CLIENTECODIGO AS CODIGO,
    CLIENTE.CLIENTENOME AS NOME,
    CLIENTE.CLIENTETELEFONE AS TELEFONE,
    CLIENTE.CLIENTEEMAIL AS EMAIL,
    CLIENTE.CLIENTECPF AS CNPJ_CNPF,
    CLIENTE.CLIENTEIE AS IE_RG,
    CLIENTE.CLIENTEFANTASIA AS FANTASIA,
    CLIENTEEND.CLIENTEENDRUA AS ENDERECO,
    CLIENTEEND.CLIENTEENDNUM AS NUMERO,
    CLIENTEEND.CLIENTEENDCOMP AS COMPLEMENTO,
    CLIENTEEND.CLIENTEENDCEP AS CEP,
    CLIENTEEND.CLIENTEENDBAIRRO AS BAIRRO,
    CIDADE.CIDADENOME AS CIDADE,
    CLIENTEEND.ESTADOCODIGO AS UF
FROM CLIENTE
LEFT JOIN CLIENTEEND ON CLIENTE.CLIENTECODIGO = CLIENTEEND.CLIENTECODIGO
LEFT JOIN CIDADE ON CLIENTEEND.CIDADECODIGO = CIDADE.CIDADECODIGO