SELECT
    FORNECEDOR.FORNECEDORCODIGO AS CODIGO,
    FORNECEDOR.FORNECEDORNOME AS NOME,
    FORNECEDOR.FORNECEDORFANTASIA AS FANTASIA,
    FORNECEDORFILIAL.FORNECEDORCNPJ AS CNPJ_CNPF,
    FORNECEDORFILIAL.FORNECEDORIE AS IE_RG,
    FORNECEDORFILIAL.FORNECEDORRUA AS ENDERECO,
    FORNECEDORFILIAL.FORNECEDORNUM AS NUMERO,
    FORNECEDORFILIAL.FORNECEDORCOMPLEMENTO AS COMPLEMENTO,
    FORNECEDORFILIAL.FORNECEDORCEP AS CEP,
    FORNECEDORFILIAL.FORNECEDORBAIRRO AS BAIRRO,
    CIDADE.CIDADENOME AS CIDADE,
    FORNECEDORFILIAL.ESTADOCODIGO AS UF,
    FORNECEDORFILIAL.FORNECEDOREMAIL AS EMAIL
FROM FORNECEDOR
LEFT JOIN FORNECEDORFILIAL ON FORNECEDOR.FORNECEDORCODIGO = FORNECEDORFILIAL.FORNECEDORCODIGO
LEFT JOIN CIDADE ON FORNECEDORFILIAL.CIDADECODIGO = CIDADE.CIDADECODIGO

WHERE FORNECEDOR.fornecedorcodigo > 0