SELECT
    PRODUTOCODIGO AS CODIGO,
    PRODUTONOME AS DESCRICAO,
    PRODUTOCODEAN AS BARRAS,
    UNIDADE.UNIDADESIGLA AS UND,
    PRODUTOSALDO AS QTD,
    PRODUTOCODORIGINAL AS COD_FABRICANTE,
    PRODUTOCUSTO AS PRECO_CUSTO,
    PRODUTOVALSAIDA AS PRECO_VENDA,
    PRODUTONCM AS COD_NCM,
    PRODUTOCEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN UNIDADE ON PRODUTO.UNIDADECODIGO = UNIDADE.UNIDADECODIGO
