SELECT PRODUTOS.`codigoint` AS CODIGO,
PRODUTOS.`codfabr` AS BARRAS,
PRODUTOS.`descricao`,
PRODUTOS.CUSTO AS PRECO_CUSTO,
PRODUTOS.`venda` AS PRECO_VENDA,
PRODUTOS.`quantidade` AS QTD,
PRODUTOS.`unidade` AS UND,
PRODUTOS.`CST2` AS ST,
PRODUTOS.`ClassFiscal` AS COD_NCM,
PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
