SELECT
    CODIGO_CLI AS CODIGO,
    NOME_CLI AS NOME,
    NOME_FAN AS FANTASIA,
    CGCCPF_CLI AS CNPJ_CNPF,
    INSCRI_CLI AS IE_RG,
    ENDERE_CLI AS ENDERECO,
    COMPLEMENTO_CLI AS COMPLEMENTO,
    BAIRRO_CLI AS BAIRRO,
    CIDADE_CLI AS CIDADE,
    ESTADO_CLI AS UF,
    CEP_CLI AS CEP,
    TELEFO_CLI AS TELEFONE,
    CELULAR_CLI AS CELULAR,
    FAX_CLI AS FAX,
    EMAIL_CLI AS EMAIL,
    NUMERO_CLI AS NUMERO
FROM CLIENTE
WHERE CODIGO_CLI > 0
