select
  PRODUTO.cod_prod as BARRAS,
  PRODUTO.cod_aux AS COD_FABRICANTE, 
  PRODUTO.desc_prod AS DESCRICAO,
  ESTOQUE.ESTOQUE_PROD AS QTD,
  GRUPO.NOME AS GRUPO, 
  PRODUTO.preco_cst_prod AS PRECO_CUSTO, 
  PRODUTO.preco_vnd_prod AS PRECO_VENDA,  
  PRODUTO.qtd_min_prod AS QTD_IDEAL, 
  PRODUTO.st_prod AS ST,
  PRODUTO.uni_prod AS UND,
  PRODUTO.ncm_codigo AS COD_NCM, 
  PRODUTO.cest AS PERSONAL6 
from produto
LEFT JOIN ESTOQUE ON PRODUTO.COD_PROD = ESTOQUE.COD_PROD
LEFT JOIN GRUPO ON PRODUTO.ID_GRUPO = GRUPO.ID
