SELECT
    PRODUTO.COD_PRO AS CODIGO,
    PRODUTO.CODIGO_BARRA_PRO AS BARRAS,
    PRODUTO.NOME_PRO AS DESCRICAO,
    UNIDADE_MEDIDA.DESCRICAO AS UND,
    PRODUTO.ESTOQUE_MINIMO_PRO AS QTD_IDEAL,
    ESTOQUE.ESTOQUE AS QTD,
    PRODUTO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO.MARGEM_LUCRO_PRO AS MARGEM_LUCRO,
    PRODUTO.VALOR_PRO AS PRECO_VENDA,
    PRODUTO.VALOR_ATACADO AS PRECO_ATACADO,
    PRODUTO.ORIG AS OST,
    PRODUTO.CSOSN AS ST,
    PRODUTO.REFERENCIA_PRO AS COD_FABRICANTE,
    PRODUTO.CFOP_VENDAS_CONT_EST AS CF,
    PRODUTO.COD_NCM AS COD_NCM,
    PRODUTO.OBS AS OBSERVACOES,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN UNIDADE_MEDIDA ON UNIDADE_MEDIDA.CODIGO = PRODUTO.CODIGO_UNIDADE_SAIDA
LEFT JOIN ESTOQUE ON ESTOQUE.COD_PRO = PRODUTO.COD_PRO
