SELECT
    PRODUTO.CODPRODUTO AS CODIGO,
    COLABORADOR.razao AS FORNECEDOR,
    UNIDADE_MEDIDA.sigla AS UND,
    GRUPO.grupo AS GRUPO,
    PRODUTO.CODBARRA AS BARRAS,
    PRODUTO.CODIGO_FABRICA AS COD_FABRICANTE,
    PRODUTO.DESCRICAO AS DESCRICAO,
    PRODUTO.DESCRICAOPDV AS CARACTERISTICA,
    PRODUTO.OBSERVACAO ||' -- '|| PRODUTO.APLICACAO AS OBSERVACOES,
    PRODUTO_PRECO.PRECO_CUSTO AS PRECO_CUSTO,
    PRODUTO_PRECO.PRECO_VENDA AS PRECO_VENDA,
    PRODUTO_PRECO.MARGEM AS MARGEM_LUCRO,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6,
    PRODUTO.DATA_CADASTRO AS DATA_CADASTRO,
    PRODUTO.DATA_ALTERACAO AS ALTERACAO_PRECO
FROM PRODUTO
LEFT JOIN GRUPO ON GRUPO.codgrupo = PRODUTO.codgrupo
LEFT JOIN COLABORADOR ON COLABORADOR.codcolaborador = PRODUTO.codcolaborador
LEFT JOIN PRODUTO_PRECO ON PRODUTO_PRECO.codproduto = PRODUTO.codproduto
LEFT JOIN UNIDADE_MEDIDA ON UNIDADE_MEDIDA.codunidademedida = PRODUTO.codunidadesaida
