SELECT
    FORNECEDORES.CODFORNEC AS CODIGO,
    FORNECEDORES.NOMEFORNEC AS NOME,
    FORNECEDORES.ENDERECO AS ENDERECO,
    FORNECEDORES.BAIRRO AS BAIRRO,
    FORNECEDORES.CIDADE AS CIDADE,
    FORNECEDORES.ESTADO AS UF,
    FORNECEDORES.CEP AS CEP,
    FORNECEDORES.FONE1 AS TELEFONE,
    FORNECEDORES.FONE2 AS CELULAR,
    case when FORNECEDORES.CPF = '' or FORNECEDORES.CPF is null then FORNECEDORES.CGC else FORNECEDORES.CPF END AS CNPJ_CNPF,
    case when FORNECEDORES.RG = '' or FORNECEDORES.RG is null then FORNECEDORES.INSC_ESTAD else FORNECEDORES.RG END AS IE_RG,
    FORNECEDORES.CONTATO AS CONTATO,
    FORNECEDORES.FAX AS FAX,
    FORNECEDORES.EMAIL AS EMAIL,
    case when FORNECEDORES.SITUACAO = 'A' then 'Ativo' else 'Inativo' end as SITUACAO,
    FORNECEDORES.NUMERO AS NUMERO,
    FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM FORNECEDORES