SELECT
       CADMATERIAL.CODIGOMATERIAL as codigo
      ,CADMATERIAL.DESCRICAO as descricao
      ,CADMATERIAL.UNIDADEENTRADA as und_compra
      ,CADMATERIAL.UNIDADESAIDA as und
      ,CADMATERIAL.PESOLIQUIDO as peso
      ,CADMATERIAL.CUSTOINFORMADO as preco_custo
      ,CADMATERIAL.PRECOVENDA1 as preco_venda
      ,TRIBUTACOES.csticms as st
      ,CADMATERIAL.CODIGOAUXILIAR as cod_fabricante
      ,CADMATERIAL.OBSERVACAO as observacoes
      ,CADMATERIAL.DATAULTIMOREAJUSTE as alteracao_preco
      ,CADMATERIAL.DATACADASTRO as data_cadastro
      ,CADMATERIAL.CODIGONCM as cod_ncm
      ,CADMATERIAL.CODIGOCEST as personal6
  FROM SantoAngelus.dbo.CADMATERIAL
  left join SantoAngelus.dbo.CADTIPOTRIBUTACAO on CADTIPOTRIBUTACAO.CODIGOTIPOTRIBUTACAO = CADMATERIAL.CODIGOTIPOTRIBUTACAO
  left join SantoAngelus.dbo.TRIBUTACOES on TRIBUTACOES.CODIGOTIPOTRIBUTACAO = CADTIPOTRIBUTACAO.CODIGOTIPOTRIBUTACAO