SELECT 
       C.CODIGO AS CODIGO
      ,CONCAT (C.NOME, ' ' , C.SOBRENOME) AS NOME 
      ,C.EMPNOME AS FANTASIA
      ,C.CPF AS CNPJ_CNPF
      ,C.RG AS IE_RG
      ,C.ENDERECO AS ENDERECO
      ,C.COMPLEMENTO AS COMPLEMENTO
      ,C.NUMERO AS NUMERO
      ,C.BAIRRO AS BAIRRO
      ,C.CIDADE AS CIDADE
      ,C.ESTADO AS UF
      ,C.CEP AS CEP
      ,C.TELEFONE1 AS TELEFONE
      ,C.TELEFONE2 AS CELULAR
      ,C.EMAIL AS EMAIL
      ,CONCAT (C.OBSERVACAO, ' / ' ,OBSERVACAO2) AS OBSERVACOES
      ,C.NOMEPAI AS PAI
      ,C.NOMEMAE AS MAE
      ,C.LIMITE AS LIMITE_CREDITO
      ,C.NATURALIDADE AS NATURALIDADE
      ,C.ESTCIVIL AS EST_CIVIL
      ,C.CONJUGE AS CONJUGE
      ,C.NASCIMENTO AS NASCIMENTO
      ,C.CADASTRO AS CADASTRO
      ,C.ULTCOMPRA AS ULTIMA_VENDA	
      ,C.TAMANHOCALCADO AS PERSONAL1
      ,C.TAMANHOROUPA AS PERSONAL4
  FROM LALESKA_10524.dbo.CLIENTE AS C
  where CADASTRO >= '13-08-2024'
