SELECT 
       CODIGO AS CODIGO
      ,RAZAO AS NOME
      ,ENDERECO AS ENDERECO
      ,NUMERO AS NUMERO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,ESTADO AS UF
      ,CEP AS CEP
      ,FAX AS FAX
      ,TELEFONE1 AS TELEFONE
      ,TELEFONE2 AS CELLULAR
      ,CNPJ AS CNPJ_CNPF
      ,INSC AS IE_RG
      ,EMAIL AS EMAIL
      ,OBSERVACAO AS OBSERVACOES
      ,COMPLEMENTO AS COMPLEMENTO
  FROM LALESKA_10524.dbo.FORNECEDOR
