SELECT 
       CP.CODIGO AS COD_FORNECEDOR
      ,F.RAZAO AS NOM_FORNECEDOR
      ,CP.VENCIMENTO AS VENCIMENTO
      ,CP.HISTORICO AS HISTORICO
      ,CP.VALOR AS VALOR_DUP
      ,MAX (CP.DUPLICATA) AS DOCUMENTO
      ,CP.DATEMI AS EMISSAO
      ,CP.DATAPAGTO AS PAGAMENTO
      ,CP.VALORPAGTO AS VALOR_PAG
      ,T.DESCRICAO AS TIPO_DOC
      ,CP.DESCONTO AS VALOR_DES
      ,CP.JUROS AS VALOR_JUR
      ,CP.CENTROCUSTO AS CTO_CUSTO
      ,CP.OBSERVACAO AS OBSERVACOES
  FROM LALESKA_10524.dbo.CONTAPAG AS CP
LEFT  JOIN FORNECEDOR F ON CP.CODIGO = F.CODIGO
LEFT JOIN TIPO T ON CP.TIPO = T.CODIGO
WHERE F.RAZAO <> '' --AND CP.CODIGO = '481'
GROUP BY
       CP.CODIGO
      ,F.RAZAO
      ,CP.VENCIMENTO
      ,CP.HISTORICO
      ,CP.VALOR
      ,CP.DATEMI
      ,CP.DATAPAGTO
      ,CP.VALORPAGTO
      ,T.DESCRICAO
      ,CP.DESCONTO
      ,CP.JUROS
      ,CP.CENTROCUSTO
      ,CP.OBSERVACAO
