SELECT 
       P.LOJA
      ,P.CODIGO AS CODIGO
      ,P.CODBARRA AS BARRAS
      ,P.DESCRICAO AS DESCRICAO
      ,U.DESCRICAO AS UND
      ,P.TAMANHO AS TAMANHO
      ,(select TOP 1 SALDO.ESTOQUE from SALDO where P.CODIGO = SALDO.PRODUTO order by DATULTALT desc) as QTD
      ,P.ESTOQUEIDEAL AS QTD_IDEAL
      ,(select TOP 1 ITEMVENDA.PRCVENDA from ITEMVENDA where P.CODIGO = ITEMVENDA.PRODUTO order by VENDADATA desc) as PRECO_VENDA
      ,(select TOP 1 ITEMVENDA.PRCCOMPRA from ITEMVENDA where P.CODIGO = ITEMVENDA.PRODUTO order by VENDADATA desc) as PRECO_CUSTO
      --,MIN (IPV.PRCVENDA) AS PRECO_VENDA
      --,MIN (IPC.PRCCOMPRA) AS PRECO_CUSTO
      ,SUBSTRING (P.SITTRIBUTARIA,1,1) AS OST
      ,SUBSTRING (P.SITTRIBUTARIA,2,3) AS ST
      ,P.SITTRIBUTARIAIPI AS IPI_CODIGO
      ,P.SITTRIBUTARIAPIS AS PIS_CODIGO
      ,P.SITTRIBUTARIACOFINS AS COFINS_CODIGO
      ,P.NCM AS COD_NCM
      ,P.CEST AS PERSONAL6
      ,P.DATULTCOMP AS ULTIMA_COMPRA
      ,P.DATACADASTRO AS DATA_CADASTRO
      ,CAST (P.DATULTALT AS DATE) AS ALTERACAO_PRECO
  FROM LALESKA_10524.dbo.PRODUTO AS P
LEFT JOIN UNIDADE U ON P.UNIDADE = U.CODIGO
--INNER JOIN ITEMVENDA IPV ON P.CODIGO = IPV.PRODUTO
--INNER JOIN ITEMVENDA IPC ON P.CODIGO = IPC.PRODUTO
  where DATACADASTRO >= '13-08-2024' --and p.codigo = '183868'--and loja = '1'
GROUP BY 
       P.LOJA
      ,P.CODIGO
      ,P.CODBARRA
      ,P.DESCRICAO
      ,U.DESCRICAO
      ,P.TAMANHO
      --,SALDO.ESTOQUE
      ,P.ESTOQUEIDEAL
      ,P.SITTRIBUTARIA
      ,P.SITTRIBUTARIAIPI
      ,P.SITTRIBUTARIAPIS
      ,P.SITTRIBUTARIACOFINS
      ,P.NCM
      ,P.CEST
      ,P.DATULTCOMP
      ,P.DATACADASTRO
      ,P.DATULTALT
