SELECT CLIENTEGERAL.CLI_NOME AS NOME,
CLIENTEGERAL.CLI_ENDERECOCIDADE AS CIDADE,
CLIENTEGERAL.CLI_ENDERECOUF AS UF,
CLIENTEGERAL.CLI_CEP CEP,
CLIENTEGERAL.CLI_CONJUGE AS CONJUGE,
CLIENTEGERAL.CLI_CREDITO AS LIMITE_CREDITO,
CLIENTEGERAL.CLI_FONE1 AS TELEFONE,
CLIENTEGERAL.CLI_FONE2 AS CELULAR,
CLIENTEGERAL.CLI_OBS AS OBSERVACOES,
CLIENTEGERAL.CLI_EMAIL AS EMAIL,
CLIENTEGERAL.CLI_DATACADASTRO AS CADASTRO,
CLIENTEGERAL.CLI_CPFCNPJNUMERO AS CNPJ_CNPF,
CLIENTEGERAL.CLI_RGINSCNUMERO AS IE_RG,
CLIENTEGERAL.CLI_LOCALTRABALHO AS LOCTRA,
CLIENTEBAIRRO.CLI_BAI_NOME AS BAIRRO,
CLIENTELOGRADOURO.CLI_LOG_DESCRICAO||' '||CLIENTEGERAL.CLI_ENDERECO AS ENDERECO,
CLIENTEGERAL.CLI_ENDERECONUMERO AS NUMERO
FROM CLIENTEGERAL
LEFT JOIN CLIENTEBAIRRO ON CLIENTEGERAL.CLI_ENDERECOBAIRROCODIGO=CLIENTEBAIRRO.CLI_BAI_CODIGO
LEFT JOIN CLIENTELOGRADOURO ON CLIENTEGERAL.CLI_ENDERECOLOGRADOURO=CLIENTELOGRADOURO.CLI_LOG_CODIGO



