SELECT FORNECEDORGERAL.FOR_RAZAOSOCIAL AS NOME,
FORNECEDORGERAL.FOR_NOMEFANTASIA AS FANTASIA,
FORNECEDORGERAL.FOR_CNPJ AS CNPJ_CNPF,
FORNECEDORGERAL.FOR_IE AS IE_RG,
FORNECEDORGERAL.FOR_FONE1 AS TELEFONE,
FORNECEDORGERAL.FOR_FONE2 AS CELULAR,
FORNECEDORGERAL.FOR_FAX AS FAX,
FORNECEDORGERAL.FOR_EMAIL AS EMAIL,
FORNECEDORGERAL.FOR_ENDERECO AS ENDERECO,
FORNECEDORGERAL.FOR_ENDERECOBAIRRO AS BAIRRO,
FORNECEDORGERAL.FOR_ENDERECOCIDADE AS CIDADE,
FORNECEDORGERAL.FOR_ENDERECOESTADO AS UF,
FORNECEDORGERAL.FOR_CEP AS CEP,
FORNECEDORGERAL.FOR_CONTATO AS CONTATO,
FORNECEDORGERAL.FOR_ENDERECONUMERO AS NUMERO
FROM FORNECEDORGERAL

