SELECT PRODUTOGRUPO.PRO_GRP_DESCRICAO AS GRUPO,
PRODUTOGERAL.PRO_DESCRICAO AS DESCRICAO,
PRODUTOGERAL.PRO_CUSTO AS PRECO_CUSTO,
PRODUTOGERAL.PRO_PRECO2 AS PRECO_VENDA,
PRODUTOGERAL.PRO_DATACADASTRO AS DATA_CADASTRO,
FORNECEDORGERAL.FOR_RAZAOSOCIAL AS FORNECEDOR,
PRODUTOGERAL.PRO_CEST AS PERSONAL6,
PRODUTOGERAL.PRO_NCM AS COD_NCM,
PRODUTOGERAL.PRO_UNIDADE AS UND,
PRODUTOGERAL.PRO_PCOFINS AS COFINS_ALIQ_NOR,
PRODUTOGERAL.PRO_PPIS AS PIS_ALIQ_NOR,
PRODUTOGERAL.PRO_CODIGO1 AS COD_FABRICANTE
FROM PRODUTOGERAL
LEFT JOIN PRODUTOGRUPO ON PRODUTOGERAL.PRO_CODGRUPO=PRODUTOGRUPO.PRO_GRP_CODIGO
LEFT JOIN FORNECEDORGERAL ON PRODUTOGERAL.PRO_FORNECEDOR=FORNECEDORGERAL.FOR_CODIGO

