SELECT
--    MATERIAL.MATERIAL AS CODIGO,
    MATERIAL.MATERIAL AS PERSONAL2,    
    MATERIAL.CODIGOBARRAS AS BARRAS,
    MATERIAL.DESCRICAO AS DESCRICAO,
    MATERIAL.UNIDADE AS UND,
    MATERIAL.VALORUNITARIO AS PRECO_VENDA,
    MATERIAL.ESTOQUEMINIMO AS QTD_IDEAL,
    MATERIAL.MARGEM AS MARGEM_LUCRO,
    MATERIAL.APLICACAO AS OBSERVACOES,
    MATERIAL.NCM AS COD_NCM,
    MATERIAL.REFERENCIA AS COD_FANBRICANTE,
    MATERIAL.CEST AS PERSONAL6,
    MATERIAL.COMISSAO,
    MATERIAL.LOCALPRODUTO AS PERSONAL1,
    MATERIAL.PESOBRUTO AS PESO,
    MATERIAL.SALDO AS QTD,
    --ESTOQUES.QUANTIDADE AS QTD,
    GRUPO.DESCRICAO AS GRUPO,
    SUBGRUPO.DESCRICAO AS FAMILIA,
    FIGURAFISCAL.PERCENTUALDOICMS AS ELO,
    FIGURAFISCAL.PERCENTUALDOIPI AS ALIQ_IPI_VENDA,
    FIGURAFISCAL.STB AS ST,
    FIGURAFISCAL.CST_IPI AS IPI_CODIGO_VENDA, 
    FIGURAFISCAL.CST_PIS AS PIS_CODIGO, 
    FIGURAFISCAL.CST_COFINS AS COFINS_CODIGO, 
    FIGURAFISCAL.PERC_PIS AS PIS_ALIQ_NOR, 
    FIGURAFISCAL.PERC_COFINS AS COFINS_ALIQ_NOR,     
    PACIENTES.DESCRICAO AS FORNECEDOR
FROM MATERIAL
--LEFT JOIN ESTOQUES ON ESTOQUES.MATERIAL = MATERIAL.MATERIAL AND estoques.LOTE = '0'
LEFT JOIN GRUPO ON GRUPO.GRUPO = MATERIAL.GRUPO
LEFT JOIN SUBGRUPO ON SUBGRUPO.SUBGRUPO = MATERIAL.SUBGRUPO
LEFT JOIN FIGURAFISCAL ON FIGURAFISCAL.FIGURA = MATERIAL.FIGURAFISCAL 
LEFT JOIN PACIENTES ON PACIENTES.CODIGO = MATERIAL.FORNECEDOR 
