SELECT CADASTRO.ID AS CODIGO,
CAST(CADASTRO.DATA_CADASTRO AS DATE) AS CADASTRO,
CADASTRO.RAZAO_SOCIAL AS NOME,
CADASTRO.CNPJ_CPF AS CNPJ_CNPF,
CADASTRO.INSCRICAO_RG AS IE_RG,
CADASTRO.FANTASIA,
CADASTRO.E_MAIL AS EMAIL,
CADASTRO.OBSERVACAO AS OBSERVACOES
FROM CADASTRO
WHERE CADASTRO.CHK_CLIENTE='S'


