SELECT
    CLICOD  AS CODIGO,
    CLINOM  AS NOME,
    CLIEST  AS UF,
    CLICAD  AS CADASTRO,
    CLIPAI  AS PAI,
    CLIMAE  AS MAE,
    CLIEND  AS ENDERECO,
    CLIBAI  AS BAIRRO,
    CLICOM  AS COMPLEMENTO,
    CLINAS  AS NASCIMENTO,
    CLICPF  AS CNPJ_CNPF,
    CLICEP  AS CEP,
    CLITEL AS TELEFONE,
    CLICEL AS CELULAR,
    CLIFAX  AS FAX,
    CLICID  AS CIDADE,
    CLIMSG  AS OBSERVACOES

FROM CLIENTES
