SELECT CLIENTE.CODIGO AS CODIGO
      ,CLIENTE.NOME AS NOME
      ,CLIENTE.ENDERECO AS ENDERECO
      ,CLIENTE.NUMERO AS NUMERO
      ,CLIENTE.COMPLEM AS COMPLEMENTO
      ,CLIENTE.BAIRRO AS BAIRRO
      ,CLIENTE.CEP AS CEP
      ,CLIENTE.FONE1 AS TELEFONE
      ,CLIENTE.FONE2 AS CELULAR
      ,CLIENTE.EMAIL AS EMAIL
      ,CLIENTE.CPFCGC AS CNPJ_CNPF
      ,CLIENTE.INSCESTRG AS IE_RG
      ,CIDADES.NOME AS CIDADE
      ,CIDADES.UF
  FROM HORTCOLHEITA.dbo.CLIENTE
  LEFT JOIN HORTCOLHEITA.dbo.CIDADES ON CLIENTE.MUNICIPIO = CIDADES.CODIGO
  WHERE TPCAD = 'C'
