SELECT ESTOQUE.CODIGO AS CODIGO
      ,ESTOQUE.NOME AS DESCRICAO
	  ,Min(ESTCOD.EAN) AS BARRAS
      ,SUBGRUPO.NOME AS GRUPO
      ,ESTOQUE.UN AS UND
      ,ESTOQUE.QUANTM AS QTD
      ,ESTOQUE.CUSTO AS PRECO_CUSTO
      ,ESTOQUE.LUCRO AS MARGEM_LUCRO
      ,ESTOQUE.VENDA AS PRECO_VENDA
      ,ESTOQUE.CODNCM AS COD_NCM
      ,ESTOQUE.CODCEST AS PERSONAL6
  FROM HORTCOLHEITA.dbo.ESTOQUE
  LEFT JOIN HORTCOLHEITA.dbo.SUBGRUPO ON ESTOQUE.SUBGRUPO = SUBGRUPO.CODIGO
  LEFT JOIN HORTCOLHEITA.dbo.ESTCOD ON ESTOQUE.CODIGO = ESTCOD.CODIGO
  GROUP BY 
   ESTOQUE.CODIGO 
      ,ESTOQUE.NOME 
      ,SUBGRUPO.NOME
      ,ESTOQUE.UN
      ,ESTOQUE.QUANTM
      ,ESTOQUE.CUSTO
      ,ESTOQUE.LUCRO
      ,ESTOQUE.VENDA
      ,ESTOQUE.CODNCM
      ,ESTOQUE.CODCEST
	  order by 1
