SELECT
    UNIDADE AS UND,
    CODPRODUTO AS CODIGO,
    CODEAN AS BARRAS,
    NOMEPRODUTO AS DESCRICAO,
    substring (produtos.tributacao from 1 for 2) as ST,
    QTDATUAL AS QTD,
    FORNECEDORES.RAZAO AS FORNECEDOR,
    PRECOCUSTO AS PRECO_CUSTO,
    PRECOVENDA AS PRECO_VENDA,
    CUSTOMEDIO AS CUSTO_MEDIO,
    NCM AS COD_NCM,
    CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON FORNECEDORES.CODIGO = PRODUTOS.CODFORNECEDOR
