SELECT
    PRODUTOS.CODIGOPRODUTO AS CODIGO,
    MIN (PRODUTOS_ESTOQUE.CODBARRAS) AS BARRAS,
    PRODUTOS.DESCRICPRODUTO AS DESCRICAO,
    MARCAS.DESCRICAO AS CARACTERISTICAS,
    FAM_PROD.DESCR_FAM AS FAMILIA,
    MAX (PRODUTOS_ESTOQUE.QTDEATUAL) AS QTD,
    PRODUTOS_EMP.PESOLIQUIDO AS PESO,
    PRODUTOS_EMP.PRCUSTOMEDIO AS CUSTO_MEDIO,
    PRODUTOS_EMP.PRCUSTOPRODUTO AS PRECO_CUSTO,
    PRODUTOS_EMP.PRECOSUGEREPRODUTO AS PRECO_VENDA,
    PRODUTOS_EMP.CODTRIBPRODUTO AS ST,
    PRODUTOS.REFERENCIAPRODUTO AS COD_FABRICANTE,
    PRODUTOS.CODNBMSH AS COD_NCM,
    PRODUTOS.CEST AS PERSONAL6,
    CAST (PRODUTOS.DATACADASTRO AS DATE) AS DATA_CADASTRO,
    CAST (PRODUTOS_EMP.DATAULTCOMPRA AS DATE) AS ULTIMA_COMPRA
FROM PRODUTOS
LEFT JOIN PRODUTOS_ESTOQUE ON PRODUTOS_ESTOQUE.CODIGOPRODUTO = PRODUTOS.CODIGOPRODUTO
LEFT JOIN PRODUTOS_EMP ON PRODUTOS_EMP.CODIGOPRODUTO = PRODUTOS.CODIGOPRODUTO
LEFT JOIN FAM_PROD ON FAM_PROD.COD_FAM = PRODUTOS.FAMILIA
LEFT JOIN MARCAS ON MARCAS.CODIGO = PRODUTOS.MARCAPRODUTO
GROUP BY 1,3,4,5,7,8,9,10,11,12,13,14,15,16