SELECT
    CAD_CLIENTES.C_CODCLI AS CODIGO,
    CAD_CLIENTES.C_NOMECLI AS NOME,
    CAD_CLIENTES.C_ENDERECO AS ENDERECO,
    CAD_CLIENTES.C_BAIRRO AS BAIRRO,
    CAD_CLIENTES.C_ESTADO AS UF,
    CAD_CLIENTES.C_CEP AS CEP,
    CAD_CLIENTES.C_CGC_CPF AS CNPJ_CNPF,
    CAD_CLIENTES.C_INS_RG AS IE_RG,
    CAD_CLIENTES.C_FONE AS TELEFONE,
    CAD_CLIENTES.C_EMAIL AS EMAIL,
    CAD_CLIENTES.C_CELULAR AS CELULAR,
    CAD_CIDADE.C_NOMECIDADE AS CIDADE,
    CAD_CLIENTES.C_NUMERO AS NUMERO
FROM CAD_CLIENTES
LEFT JOIN CAD_CIDADE ON CAD_CLIENTES.C_CODCIDADE = CAD_CIDADE.C_CODCIDADE
