SELECT
    PRODUTOS.C_CODPROD AS CODIGO,
    PRODUTOS.C_REFERENCIA AS COD_FABRICANTE,
    PRODUTOS.C_CODBARRA AS BARRAS,
    PRODUTOS.C_NOMEPROD AS DESCRICAO,
    PRODUTOS.C_UNIDADE AS UND,
    GR_PRODUTOS.C_NOMEGRUPO AS GRUPO,
    PRODUTOS.C_CLASSEFISCAL AS COD_NCM,
    PRODUTOS.C_CEST AS PERSONAL6,
    PRODUTOS.C_ST_ICMS_FE AS ST,
    ESTOQUE.C_QTDATU AS QTD,
    ESTOQUE.C_PRVENDA AS PRECO_VENDA,
    ESTOQUE.C_PRCUSTO AS PRECO_CUSTO
FROM PRODUTOS
LEFT JOIN ESTOQUE ON PRODUTOS.C_CODPROD = ESTOQUE.C_CODPROD
LEFT JOIN GR_PRODUTOS ON PRODUTOS.C_GRUPO = GR_PRODUTOS.C_CODGRUPO
