SELECT 
  RIGHT (P.PROCOD,6) as CODIGO
, P.PRODES as DESCRICAO
, P.TRBID as ELO
, P.PROUNID as UND
, E.ESTATU as QTD
, P.PROESTMIN as QTD_IDEAL
, P.PROPRCCST as PRECO_CUSTO
, P.PROMRG1 as MARGEM_LUCRO
, P.PROPRCVDAVAR as PRECO_VENDA
, G.GRPDES as GRUPO
, GE.GENDESCREDUZIDA as FAMILIA
, P.PROITEEMB as FAT_CONV
, P.PROPESBRT as PESO
, P.PROUNDCMP as UND_COMPRA
, P.PROIPPT as IPPT
, P.PROPRCCSTMED as CUSTO_MEDIO
, P.PRONCM as COD_NCM
, P.PROCEST as PERSONAL6
, MAX (PA.PROCODAUX) as COD_FABRICANTE
, MAX (RIGHT (LEFT (PA.PROCODAUX, 14),13)) as BARRAS
FROM PRODUTO P
LEFT JOIN GRUPO G ON G.GRPCOD = P.GRPCOD AND G.SECCOD = P.SECCOD
LEFT JOIN ESTOQUE E ON E.PROCOD = P.PROCOD 
LEFT JOIN GENERO GE ON GE.GENCODIGO = P.GENCODIGO 
LEFT JOIN PRODUTOAUX PA ON PA.PROCOD = P.PROCOD 
GROUP BY
  P.PROCOD
, P.PRODES
, P.TRBID
, P.PROUNID
, E.ESTATU
, P.PROESTMIN
, P.PROPRCCST
, P.PROMRG1
, P.PROPRCVDAVAR
, G.GRPDES
, GE.GENDESCREDUZIDA
, P.PROITEEMB
, P.PROPESBRT
, P.PROUNDCMP
, P.PROIPPT
, P.PROPRCCSTMED
, P.PRONCM 
, P.PROCEST