SELECT
    ID AS CODIGO,
    NOME AS NOME,
    FANTASIA AS FANTASIA,
    CONTATO AS CONTATO,
    case when CPF = '' or CPF is null then CNPJ_CPF else CPF END AS CNPJ_CNPF,
    case when RG = '' or RG is null then INSCR_EST else RG END AS IE_RG,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    COMPLEMENTO AS COMPLEMENTO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    EMAIL AS EMAIL,
    replace(FONE1,'-','') AS TELEFONE,
    CELULAR AS CELULAR,
    FAX AS FAX,
    OBS AS OBSERVACOES
FROM PESSOAS
WHERE PES_FORNECEDOR = 'True'
