SELECT
    MERCADORIAS.ID AS CODIGO,
    MERCADORIAS.CODIGO AS BARRAS,
    MERCADORIAS.DESCRICAO AS DESCRICAO,
    MARCA.MARCA AS CARACTERISTICAS,
    UNIDADE.UNIDADE AS UND,
    MERCADORIAS.QUANTID1 AS QTD,
    MERCADORIAS.PESO AS PESO,
    MERCADORIAS.LUCRO AS MARGEM_LUCRO,
    MERCADORIAS.PRECOV AS PRECO_VENDA,
    MERCADORIAS.CST AS ST,
    MERCADORIAS.NCM AS COD_NCM,
    MERCADORIAS. CEST AS PERSONAL6,
    MERCADORIAS.OBSERVACAO AS OBSERVACOES,
    MERCADORIAS.ULTENT AS ULTIMA_COMPRA,
    MERCADORIAS.ULTSAI AS ULTIMA_VENDA,
    MERCADORIAS.DATACAD AS DATA_CADASTRO
FROM MERCADORIAS
LEFT JOIN MARCA ON MARCA.ID = MERCADORIAS.MARCA
LEFT JOIN UNIDADE ON UNIDADE.ID = MERCADORIAS.UNIDADE
