SELECT
 -- PAGAR.DOCUMENTO AS DOCUMENTO
 -- PAGAR.documento || substring (PAGAR.registro from 2 for 5) AS DOCUMENTO
  PAGAR.documento || right (PAGAR.registro,3) AS DOCUMENTO
 ,PAGAR.HISTORICO
 ,CAST(cadastro.id_cadastro AS INTEGER) AS COD_FORNECEDOR
 ,cadastro.razao AS NOM_FORNECEDOR
 ,CADASTRO.CGC AS CNPJ
 ,PAGAR.EMISSAO
 ,PAGAR.VENCIMENTO
 ,PAGAR.VALOR_DUPL AS VALOR_DUP
 ,PAGAR.PAGAMENTO
 ,PAGAR.VALOR_PAGO AS VALOR_PAG
 ,PAGAR.PORTADOR AS PORTADOR
 ,PAGAR.CONTA AS NUM_CONTA
  ,PAGAR.obs AS OBSERVACOES
 ,PAGAR.REGISTRO AS BARRAS
 FROM PAGAR
 LEFT JOIN cadastro ON cadastro.id_cadastro = PAGAR.cadastro
WHERE cadastro.id_cadastro IS NOT NULL or cadastro.id_cadastro <> ''
