SELECT
    ID AS CODIGO,
    NOME AS NOME,
    DOC AS CNPJ_CNPF,
    RGIE AS IE_RG,
    LOG AS ENDERECO,
    NUM AS NUMERO,
    COMP AS COMPLEMENTO,
    BAIRRO AS BAIRRO,
    CEP AS CEP,
    CID AS CIDADE,
    UF AS UF,
    FONE AS TELEFONE,
    FAX AS FAX,
    CEL AS CELULAR,
    EMAIL AS EMAIL,
    OBS AS OBSERVACOES
FROM CAD
WHERE CLI <> 'S'  ---FORNECEDORES