SELECT
    ID AS CODIGO,
    NOME AS DESCRICAO,
    UN AS UND,
    COD AS BARRAS,
    QMIN AS QTD_IDEAL,
    CUSTO AS PRECO_CUSTO,
    MEDIO AS CUSTO_MEDIO,
    VL1 AS PRECO_VENDA,
    TRIB AS ST,
    OBS AS OBSERVACOES,
    REF AS COD_FABRICANTE,
    NCM AS COD_NCM,
    CEST AS PERSONAL6,
    DTI AS DATA_CADASTRO,
    DTA AS ALTERACAO_PRECO
FROM PROD