SELECT
    CLIENTE.CODCLIENTE AS CODIGO,
    CLIENTE.STRCLIENTE AS NOME,
    CLIENTE.STRAPELIDOFANTASIA AS FANTASIA,
    CLIENTE.STRCPFCNPJ AS CNPJ_CNPF,
    CLIENTE.STRRGINSCRICAO AS IE_RG,
    CLIENTE.STRENDERECO AS ENDERECO,
    CLIENTE.INTNUMERO AS NUMERO,
    CIDADE.STRCIDADE AS CIDADE,
    BAIRRO.STRBAIRRO AS BAIRRO,
    CLIENTE.STRCOMPLEMENTO AS COMPLEMENTO,
    CLIENTE.STRCEP AS CEP,
    CLIENTE.STRFONE1 AS TELEFONE,
    CLIENTE.STREMAIL AS EMAIL,
    CLIENTE.STRCELULAR AS CELULAR
FROM CLIENTE
LEFT JOIN CIDADE ON CLIENTE.CODCIDADE = CIDADE.CODCIDADE
LEFT JOIN BAIRRO ON CLIENTE.CODBAIRRO = BAIRRO.CODBAIRRO
