SELECT TBL_FORNECEDORES.CodEmp AS CODIGO,
TBL_FORNECEDORES.RAZAO AS NOME,
TBL_FORNECEDORES.FANTASIA,
CONCAT(TBL_FORNECEDORES.DescTipoLogradouro,' ',TBL_FORNECEDORES.LOGRADOURO) AS ENDERECO,
TBL_FORNECEDORES.NUMERO,
TBL_FORNECEDORES.COMPLEMENTO,
TBL_FORNECEDORES.CEP,
TBL_FORNECEDORES.TELEFONE,
TBL_FORNECEDORES.FAX,
TBL_FORNECEDORES.EMAIL,
COALESCE(TBL_FORNECEDORES.CNPJ,TBL_FORNECEDORES.CPF) AS CNPJ_CNPF,
TBL_FORNECEDORES.INSCESTAD AS IE_RG,
TBL_CIDADES.DESCCID AS CIDADE,
TBL_FORNECEDORES.CodEstado AS UF,
TBL_FORNECEDORES.OBSERVACAO AS OBSERVACOES
FROM TBL_FORNECEDORES
LEFT JOIN TBL_CIDADES ON TBL_FORNECEDORES.CodCid=TBL_CIDADES.CodCid

