SELECT 
PUBLIC.CLIENTE.IDCLIENTE AS CODIGO, 
PUBLIC.CLIENTE.NOME AS NOME, 
PUBLIC.CLIENTE.APELIDO AS FANTIASIA, 
PUBLIC.CLIENTE.ENDERECO AS ENDERECO, 
PUBLIC.CLIENTE.NUMERO AS NUMERO, 
PUBLIC.CLIENTE.COMPLEMENTO AS COMPLEMENTO, 
PUBLIC.CLIENTE.BAIRRO AS BAIRRO, 
CIDADE.NOME AS CIDADE,
CIDADE.FKESTADO AS UF,
PUBLIC.CLIENTE.CEP AS CEP,  
PUBLIC.CLIENTE.CNPJ_CPF AS CNPJ_CNPF, 
PUBLIC.CLIENTE.IE_RG AS IE_RG, 
PUBLIC.CLIENTE.TELEFONE AS TELEFONE, 
PUBLIC.CLIENTE.FAX AS FAX, 
PUBLIC.CLIENTE.CELULAR AS CELULAR, 
PUBLIC.CLIENTE.NASCIMENTO_FUNDACAO AS NASCIMENTO, 
PUBLIC.CLIENTE.E_MAIL AS EMAIL 
FROM PUBLIC.CLIENTE
LEFT JOIN CIDADE ON CIDADE.IDCIDADE = CLIENTE.FKCIDADE 