SELECT 
FORNECEDOR.IDFORNECEDOR AS CODIGO, 
FORNECEDOR.NOME AS NOME, 
FORNECEDOR.RAZAO_SOCIAL AS FANTASIA, 
FORNECEDOR.ENDERECO ENDERECO, 
FORNECEDOR.NUMERO AS NUMERO, 
FORNECEDOR.COMPLEMENTO AS COMPLEMENTO, 
CIDADE.NOME AS CIDADE,
CIDADE.FKESTADO AS UF,
FORNECEDOR.TELEFONE AS TELEFONE, 
FORNECEDOR.FAX AS FAX, 
FORNECEDOR.CELULAR AS CELULAR, 
FORNECEDOR.E_MAIL AS EMAIL, 
FORNECEDOR.CONTATO AS CONTATO, 
FORNECEDOR.CNPJ_CPF AS CNPJ_CNPF, 
FORNECEDOR.IE_RG AS IE_RG, 
FORNECEDOR.OBSERVACAO AS OBSERVACOES,  
FORNECEDOR.CEP AS CEP, 
FORNECEDOR.BAIRRO AS BAIRRO  
FROM PUBLIC.FORNECEDOR
LEFT JOIN CIDADE ON CIDADE.IDCIDADE = FORNECEDOR.FKCIDADE 