select CLIENTES.CLI_CODIGO AS CODIGO,
CLIENTES.CLI_NOME AS NOME,
CLIENTES.APELIDO AS FANTASIA,
CLIENTES.CONTATO,
CAST(CASE WHEN CLIENTES.CLI_CADASTRO IS NULL THEN CURRENT_TIMESTAMP
 ELSE CLIENTES.CLI_CADASTRO END AS DATE)  AS CADASTRO,
CASE WHEN CLIENTES.CPF IS NULL OR CLIENTES.CPF='' THEN CLIENTES.CNPJ ELSE CLIENTES.CPF END AS CNPJ_CNPF,
CLIENTES.INSCRICAO_ESTADUAL AS IE_RG,
CLIENTES.ENDERECO,
CLIENTES.BAIRRO,
CLIENTES.CIDADE,
CLIENTES.UF,
CLIENTES.CEP,
CLIENTES.NUMERO,
CLIENTES.TELEFONE_1 AS TELEFONE,
CLIENTES.FAX_1 AS FAX,
CLIENTES.OBSERVACAO AS OBSERVACOES,
CLIENTES.CLI_EMAIL AS EMAIL
FROM CLIENTES
WHERE CLIENTES.CLI_CODIGO>0


