SELECT 
PRODUTO.PRO_CODIGO AS CODIGO,
PRODUTO.PRO_REFERENCIA AS BARRAS,
PRODUTO.PRO_DESCRICAO AS DESCRICAO,
PRODUTO.PRO_MARCA AS CARACTERISTICAS,
GRUPOS.GRU_DESCRICAO AS GRUPO,
PRODUTO.UNI_CODIGO AS UND,
PRODUTO.PRO_QUANTIDADE AS QTD,
PRODUTO.PRO_VENDA AS PRECO_VENDA,
PRODUTO.PRO_CUSTO AS PRECO_CUSTA,
PRODUTO.PRO_CUSTO_MEDIO AS CUSTO_MEDIO,
PRODUTO.PRO_REF AS PERSONAL2,
PRODUTO.NCM AS COD_NCM,
substring(ALIQUOTA.NOME FROM 1 FOR 1) AS ST
FROM PRODUTO
LEFT JOIN GRUPOS ON PRODUTO.GRU_CODIGO=GRUPOS.GRU_CODIGO
LEFT JOIN ALIQUOTA ON PRODUTO.PRO_CODALIQUOTA=ALIQUOTA.CODIGO








