SELECT 
ESTGPRODUTO.id as COD_FABRICANTE,
ESTGPRODUTO.CODIGOBARRAS AS BARRAS,
ESTGPRODUTO.CUSTOCOMPRAGER AS PRECO_CUSTO,
ESTGPRODUTO.DESCRICAO,
ESTGPRODUTO.MARGEMLUCRO AS MARGEM_LUCRO,
ESTGPRODUTO.PRECOVENDA AS PRECO_VENDA,
ESTGPRODUTO.REFERENCIAFORNECEDOR AS CARACTERISTICAS,
ESTGGRUPO.DESCRICAO AS GRUPO,
ESTGNCM.NCM AS COD_NCM,
ESTGUNIDADE.DESCRICAOREDUZIDA AS UND,
ESTGSALDOPRODUTO.QUANTIDADE AS QTD

FROM estgproduto

LEFT JOIN ESTGGRUPO ON ESTGPRODUTO.GRUPOID = ESTGGRUPO.ID
LEFT JOIN ESTGNCM ON ESTGPRODUTO.NCMID = ESTGNCM.ID
LEFT JOIN ESTGUNIDADE ON ESTGPRODUTO.UNIDADEID = ESTGUNIDADE.ID
LEFT JOIN ESTGSALDOPRODUTO ON ESTGPRODUTO.ID = ESTGSALDOPRODUTO.PRODUTOID
