SELECT
    CLIENTES.ID AS CODIGO,
    CLIENTES.NOME AS NOME,
    CLIENTES.RAZAO_SOCIAL AS FANTASIA,
    CLIENTES.CONTATO AS CONTATO,
    case when CLIENTES.CPF = '' or CLIENTES.CPF is null then CLIENTES.CNPJ else CLIENTES.CPF END AS CNPJ_CNPF,
    case when CLIENTES.IDENTIDADE = '' or CLIENTES.IDENTIDADE is null then CLIENTES.INSC_EST else CLIENTES.IDENTIDADE END AS IE_RG,
    CLIENTES.ENDERECO AS ENDERECO,
    CLIENTES.END_NUMERO AS NUMERO,
    CLIENTES.END_COMPLEMENTO AS COMPLEMENTO,
    CLIENTES.BAIRRO AS BAIRRO,
    CLIENTES.CEP AS CEP,
    MUNICIPIOS.NOME_MUNICIPIO AS CIDADE,
    UF.UF AS UF,
    TELEFONES.NUMERO AS TELEFONE,
    CLIENTES.EMAIL AS EMAIL,
    CLIENTES.OBS AS OBSERVACOES,
    CLIENTES.LIMITE AS LIMITE_CREDITO,
    CLIENTES.DT_CADASTRO AS CADASTRO,
    CLIENTES.DT_NASCIMENTO AS NASCIMENTO
FROM CLIENTES
LEFT JOIN MUNICIPIOS ON MUNICIPIOS.ID = CLIENTES.ID_MUNICIPIO
LEFT JOIN UF ON UF.ID = CLIENTES.ID_UF
LEFT JOIN TELEFONES ON TELEFONES.ID = CLIENTES.ID
