SELECT CLI_CLIENTE.CLI_ID AS CODIGO,
CLI_CLIENTE.CLI_NOME AS NOME,
CLI_CLIENTE.CLI_EMAIL AS EMAIL,
CASE WHEN CLI_CLIENTE.CLI_CPF IS NULL THEN CLI_CLIENTE.CLI_CNPJ
ELSE CLI_CLIENTE.CLI_CPF END AS CNPJ_CNPF,
CLI_CLIENTE.CLI_INS_ESTADUAL AS IE_RG,
CLI_CLIENTE.CLI_APELIDO AS FANTASIA,
CLI_CLIENTE.CLI_DATA_CADASTRO AS CADASTRO,
END_ENDERECO.END_LOGRADOURO AS ENDERECO,
END_ENDERECO.END_COMPLEMENTO AS COMPLEMENTO,
END_ENDERECO.END_NR AS NUMERO,
END_ENDERECO.END_BAIRRO AS BAIRRO,
CID_CIDADE.CID_NOME AS CIDADE,
END_ENDERECO.END_UF AS UF,
END_ENDERECO.END_CEP AS CEP,
END_ENDERECO.END_TEL_RES AS TELEFONE,
END_ENDERECO.END_TEL_CEL AS CELULAR
FROM CLI_CLIENTE
LEFT JOIN END_ENDERECO ON CLI_CLIENTE.CLI_ID=END_ENDERECO.END_CLI_ID
LEFT JOIN CID_CIDADE ON END_ENDERECO.END_CID_ID=CID_CIDADE.CID_ID
WHERE CLI_CLIENTE.CLI_ID<>0 AND
 CLI_CLIENTE.CLI_TCL_ID=2








