SELECT 
  CLIEICOD AS CODIGO
, CASE WHEN CLIEA11CPF = '' OR CLIEA11CPF IS NULL THEN CLIEA14CGC ELSE CLIEA11CPF END AS CNPJ_CNPF
, CASE WHEN CLIEA10RG = '' OR CLIEA10RG IS NULL THEN CLIEA20IE ELSE CLIEA10RG END AS IE_RG
, CLIEA60RAZAOSOC AS NOME
, CLIEA60NOMEFANT AS FANTASIA
, CLIEA60CONTATO AS CONTATO
, CLIEA15FONE1 AS TELEFONE
, CLIEA15FONE2 AS CELULAR
, CLIEA15FAX AS FAX
, CLIEA60PROFISSAO AS PROFISSAO
, CLIEA60ENDRES AS ENDERECO
, CLIEA60COMPLEMENTO AS COMPLEMENTO
, CLIEA60BAIRES AS BAIRRO
, CLIEA60CIDRES AS CIDADE
, CLIEA2UFRES AS UF
, CLIEA8CEPRES AS CEP
, CLIEA60EMAIL AS EMAIL
, CLIEN2LIMITECRED AS LIMITE_CREDITO
, CLIEA60NOMEPAI AS PAI
, CLIEA60NOMEMAE AS MAE
, CAST (CLIEDNASC AS DATE) AS NASCIMENTO
, CLIECESTADOCIVIL AS EST_CIVIL
, CLIEA60CONJUGE AS CONJUGE
, CLIEA60EMPRESA AS LOCTRA
, CAST (CLIEDULTCOMPRA AS DATE) AS ULTIMA_VENDA
, CAST (REGISTRO AS DATE) AS CADASTRO
FROM CLIENTE
