SELECT
  PRODUTO.COD_BARRA AS BARRAS,
  PRODUTO.DESCRICAO AS DESCRICAO,
  PRODUTO.custo AS PRECO_CUSTO,
  PRODUTO.margem_lucro,
  PRODUTO.VR_UNIT AS PRECO_VENDA,
  PRODUTO.UNIDADE AS UND,
  PRODUTO.NCM AS COD_NCM,
  PRODUTO.CFOP AS CF,
  PRODUTO.CEST AS PERSONAL6, 
  PRODUTO.CODIGO_INTERNO AS COD_FABRICANTE,
  PRODUTO.ID_PRODUTO AS CARACTERISTICAS,
  PRODUTO.VR_ATACADO AS PRECO_ATACADO,
  ESTOQUE.qtd,
  ESTOQUE.qtd_min AS QTD_IDEAL
FROM PRODUTO
LEFT JOIN estoque ON ESTOQUE.id_produto = PRODUTO.id_produto