SELECT 
       GLOAGENTE.IDAGENTE AS CODIGO
      ,GLOAGENTE.IDGLOCATEGORIA
      ,GLOAGENTE.RAZAO AS NOME
      ,GLOAGENTE.FANTASIA AS FANTASIA
      ,case when GLOAGENTE.CPF = '' or GLOAGENTE.CPF is null then GLOAGENTE.CNPJ else GLOAGENTE.CPF END AS CNPJ_CNPF
      ,case when GLOAGENTE.CEI = '' or GLOAGENTE.CEI is null then GLOAGENTE.IE else GLOAGENTE.CEI END AS IE_RG
      ,GLOAGENTE.IM AS IM
      ,GLOAGENTE.ENDERECO AS ENDERECO
      ,GLOAGENTE.NUMERO AS NUMERO
      ,GLOAGENTE.BAIRRO AS BAIRRO
      ,GLOAGENTE.COMPLEMENTO AS COMPLEMENTO
      ,GLOMUNICIPIO.DESCRICAO AS CIDADE
      ,GLOUF.ABREVIATURA AS UF
      ,GLOAGENTE.CEP AS CEP
      ,CONCAT (GLOAGENTE.DDD,GLOAGENTE.TELEFONE) AS TELEFONE 
      ,GLOAGENTE.EMAIL AS EMAIL
      ,GLOAGENTE.OBS AS OBSERVACOES
  FROM ERPSystem.dbo.GLOAGENTE
LEFT JOIN ERPSystem.dbo.GLOMUNICIPIO ON GLOMUNICIPIO.IDMUNICIPIO = GLOAGENTE.IDCIDADE
LEFT JOIN ERPSystem.dbo.GLOUF ON GLOUF.IDUF = GLOAGENTE.IDUF
WHERE GLOAGENTE.IDGLOCATEGORIA = '2' --FORNECEDORES
