SELECT
    PROD_CODIGO AS CODIGO,
    PROD_CODFABRICACAO AS COD_FABRICANTE,
    PROD_DESCRICAO AS DESCRICAO,
    PROD_CODNCM AS COD_NCM,
    PROD_CODUNIDADE AS UND,
    PROD_CODCSTICMS AS ST,
    PROD_PRECOVISTA AS PRECO_VENDA,
    PROD_CUSTO AS PRECO_CUSTO,
    PROD_CUSTOMEDIO AS CUSTO_MEDIO,
    PROD_MARGEMLUCRO AS MARGEM_LUCRO,
    PROD_QUANTIDADEDISPONIVEL AS QTD,
    PROD_CODCEST AS PERSONAL6
FROM ESTPRODUTOS
