SELECT 
       PK AS CODIGO
      ,NOME_FANTASIA AS FANTASIA
      ,RAZAO_SOCIAL AS NOME
      ,ENDERECO AS ENDERECO
      ,ENDERECO_NUM AS NUMERO
      ,BAIRRO AS BAIRRO
      ,CIDADE AS CIDADE
      ,UF AS UF
      ,CEP AS CEP
      ,FONE AS TELEFONE
      ,EMAIL AS EMAIL
      ,CNPJ_CPF AS CNPJ_CNPF
      ,IE AS IE_RG
      ,IM AS IM
      ,OBS AS OBSERVACOES
      ,LIMITE_CREDITO AS LIMITE_CREDITO
      ,COMPLEMENTO AS COMPLEMENTO
      ,DATA_ANIVERSARIO AS NASCIMENTO
     -- ,DATA_CADASTRO AS CADASTRO
  FROM JJ_CONTRUCOES.dbo.CLIENTES
