SELECT
    RAZAO_SOCIAL AS NOME,
    NOME_FANTASIA AS FANTASIA,
    ENDERECO,
    BAIRRO,
    CIDADE,
    UF,
    CEP,
    FONE_1 AS TELEFONE,
    FAX,
    CELULAR,
    E_MAIL AS EMAIL,
    CNPJ AS CNPJ_CNPF,
    INSC_ESTADUAL AS IE_RG,
    NUMERO,
    COMPLEMENTO
FROM TB_FORNECEDOR