select CLIENTE.CODIGOCLIENTE AS CODIGO,
CLIENTE.NOMECLIENTE AS NOME,
CLIENTE.FANTASIACLIENTE AS FANTASIA,
CLIENTE.NOMEENDERECOCLIENTE AS ENDERECO,
CLIENTE.NUMEROCLIENTE AS NUMERO,
CLIENTE.COMPLEMENTOCLIENTE AS COMPLEMENTO,
CLIENTE.NOMEBAIRROCLIENTE AS BAIRRO,
CIDADE.DESCRICAOCIDADE AS CIDADE,
CLIENTE.ESTADOCLIENTE AS UF,
CLIENTE.CEPCLIENTE AS CEP,
CLIENTE.TELEFONECLIENTE AS TELEFONE,
CLIENTE.CELULARCLIENTE AS CELULAR,
CLIENTE.FAXCLIENTE AS FAX,
CLIENTE.E_MAILCLIENTE AS EMAIL,
CLIENTE.CNPJ_CPFCLIENTE AS CNPJ_CNPF,
CLIENTE.INSCRICAOCLIENTE AS IE_RG,
CLIENTE.CONTATOCLIENTE AS CONTATO,
CLIENTE.OBSERVACAOCLIENTE AS OBSERVACOES,
CLIENTE.DATA_CADASTROCLIENTE AS CADASTRO
FROM CLIENTE
LEFT JOIN CIDADE ON CLIENTE.CIDADECLIENTE=CIDADE.CODIGOCIDADE
WHERE CLIENTE.CODIGOCLIENTE>0 AND CLIENTE.FORNECEDORCLIENTE='S'


