select PRODUTO.CODIGOPRODUTO AS CODIGO,
GRUPO.DESCRICAOGRUPO AS GRUPO,
PRODUTO.NOMEPRODUTO AS DESCRICAO,
PRODUTO.UNIDADEESTOQUEPRODUTO AS UND,
PRODUTO.NBMPRODUTO AS COD_NCM,
CEST.CEST_CEST AS PERSONAL6,
DETALHEPRODUTO.SALDOATUALDETALHEPRODUTO AS QTD,
DETALHEPRODUTO.CUSTOCOMPRAREALDETALHEPRODUTO AS PRECO_CUSTO,
DETALHEPRODUTO.PRECOVENDADETALHEPRODUTO AS PRECO_VENDA,
DETALHEPRODUTO.CODBARRASDETALHEPRODUTO AS BARRAS
FROM PRODUTO
LEFT JOIN GRUPO ON PRODUTO.GRUPOPRODUTO=GRUPO.CODIGOGRUPO
LEFT JOIN CEST ON PRODUTO.CESTPRODUTO=CEST.CODIGO_CEST
LEFT JOIN DETALHEPRODUTO ON PRODUTO.CODIGOPRODUTO=DETALHEPRODUTO.PRODUTODETALHEPRODUTO AND DETALHEPRODUTO.EMPRESADETALHEPRODUTO=1
WHERE PRODUTO.CODIGOPRODUTO>0
