SELECT PRODUTO.ID AS CODIGO,
PRODUTO_UNIDADE.DESCRICAO AS UND,
PRODUTO.GTIN AS BARRAS,
PRODUTO.CODIGO_INTERNO AS COD_FABRICANTE,
PRODUTO.DESCRICAO,
PRODUTO.PRECO_VENDA,
PRODUTO.QTD_ESTOQUE AS QTD,
PRODUTO.NCM AS COD_NCM,
PRODUTO.CSOSN AS ST,
PRODUTO.PRECO_CUSTO,
PRODUTO.MARCA AS CARACTERISTICAS,
PRODUTO.GRUPO,
PRODUTO.SUBGRUPO AS FAMILIA,
PRODUTO.ORIGEM_MERCADORIA AS OST,
PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN PRODUTO_UNIDADE ON PRODUTO.UNIDADE_COMERCIAL_ID=PRODUTO_UNIDADE.ID
