SELECT 
  ENTIDADES.ENTI_CODIGO AS CODIGO
, ENTIDADES.ENTI_CPFCNPJ AS IE_RG
, CASE WHEN ENTIDADES.ENTI_INSCRICAOESTADUAL  = '' OR ENTIDADES.ENTI_INSCRICAOESTADUAL  = 'ISENTO' OR ENTIDADES.ENTI_INSCRICAOESTADUAL IS NULL THEN ENTIDADES.ENTI_RGIE ELSE ENTIDADES.ENTI_INSCRICAOESTADUAL  END AS IE_RG
, ENTIDADES.ENTI_NOMERAZAO AS NOME
, ENTIDADES.ENTI_FANTASIA AS FANTASIA
, ENTIDADES.ENTI_ENDERECO AS ENDERECO
, ENTIDADES.ENTI_BAIRRO AS BAIRRO
, ENTIDADES.ENTI_COMPLEMENTO AS COMPLEMENTO
, ENTIDADES.ENTI_NUMERO AS NUMERO
, ENTIDADES.ENTI_PONTOREFERENCIA AS PERSONAL1
, ENTIDADES.ENTI_CEP AS CEP
, ENTIDADES.ENTI_FONE1 AS TELEFONE
, ENTIDADES.ENTI_FONE2 AS FAX
, ENTIDADES.ENTI_CELULAR AS CELULAR
, ENTIDADES.ENTI_REFERENCIACOMERCIAL AS PERSONAL2
, ENTIDADES.ENTI_OBS AS OBSERVACOES
, ENTIDADES.ENTI_EMAIL AS EMAIL
, CIDADES.CIDA_UF_SIGLA AS UF
, CIDADES.CIDA_DISTRITO_DESCRICAO AS CIDADE
FROM ENTIDADES
LEFT JOIN CIDADES ON ENTIDADES.CIDA_CODIGO = CIDADES.CIDA_CODIGO
WHERE ((ENTIDADES.ENTI_CLIE_FOR = 'F') OR (COALESCE(ENTIDADES.ENTI_CLIE_FOR, 'A') = 'A'))
AND ENTIDADES.ENTI_CODIGO <> -1
