SELECT 
  PRODUTOS.PROD_CODIGO AS CODIGO 
, PRODUTOS.PROD_DESCRICAO AS DESCRICAO 
, PRODUTOS.PROD_UNIDADE AS UND
, PRODUTOS.PROD_CUSTO AS PRECO_CUSTO
, PRODUTOS.PROD_ESTOQUEMIN AS QTD_IDEAL
, PRODUTOS.PROD_MARGEM AS MARGEM_LUCRO
--, PRODUTOS.PROD_CST_ORIGEM AS OST
--, PRODUTOS.PROD_CST_TIPO_TRIB AS ST
--, PRODUTOS.CSOSN_CODIGO AS ST
, PRODUTOS.PROD_CODFABRICANTE AS PERSONAL1
, PRODUTOS.PROD_CODFABRICANTE_FORNECEDOR AS COD_FABRICANTE
, PRODUTOS.PROD_ALIQIPI AS ALIQ_IPI_VENDA
--, PRODUTOS.PROD_ALIQICMS AS ELO
, LEFT (PRODUTOS.CFOP_CODIGO_DENT_EST_VEND,3) AS ELO 
, PRODUTOS.CFOP_CODIGO_DENT_EST_VEND AS CF 
, PRODUTOS.PROD_MARCA AS CARACTERISTICAS
, PRODUTOS.NCMM_CODIGO AS COD_NCM
, CASE PRODUTOS.PROD_ATIVO WHEN 'S' THEN 'Ativo' ELSE 'INATIVO' END AS SITUACAO
, PRODUTOS.PROD_ALIQ_PIS_COMPRA AS PISE_ALIQ_NOR
--, PRODUTOS.PROD_ALIQ_PIS_VENDA AS PIS_ALIQ_NOR
, PRODUTOS.PROD_ALIQ_COFINS_COMPRA AS COFINSE_ALIQ_NOR
--, PRODUTOS.PROD_ALIQ_COFINS_VENDA AS COFINS_ALIQ_NOR
, PRODUTOS.PROD_PIS_CST_COMPRA AS PISE_CODIGO
--, PRODUTOS.PROD_PIS_CST_VENDA AS PIS_CODIGO
, PRODUTOS.PROD_COFINS_CST_COMPRA AS COFINSE_CODIGO
--, PRODUTOS.PROD_COFINS_CST_VENDA AS COFINS_CODIGO
, PRODUTOS.PROD_PAGACOMISSAO_ALIQ AS COMISSAO
, PRODUTOS.PROD_PESO_BRUTO AS PESO
, PRODUTOS.PROD_UNIDADE_FORNECEDOR AS UND_COMPRA
, PRODUTOS.PROD_DESCRICAO_ADICIONAL AS OBSERVACOES
, PRODUTOS_ESTOQUE.PRET_QTD AS QTD
, GRUPO_PRODUTOS.GPPR_DESCRICAO AS GRUPO
, PRODUTOS_SUBGRUPOS.SGPR_DESCRICAO AS FAMILIA
, PRODUTOS_CUSTOS.PRDC_CUSTO_MEDIO AS CUSTO_MEDIO
, PRODUTOS_PRECOS.PRPC_VALOR AS PRECO_VENDA
, RIGHT (PRODUTOS_TRIBUTACAO.PRTR_CST_CSOSN,3) AS ST
, LEFT (PRODUTOS_TRIBUTACAO.PRTR_CST_CSOSN,1) AS OST
, PRODUTOS_TRIBUTACAO.PRTR_ALIQ_PIS AS PIS_ALIQ_NOR
, PRODUTOS_TRIBUTACAO.PRTR_ALIQ_COFINS AS COFINS_ALIQ_NOR
, PRODUTOS_TRIBUTACAO.PRTR_CST_PIS AS PIS_CODIGO
, PRODUTOS_TRIBUTACAO.PRTR_CST_COFINS AS COFINS_CODIGO
, MAX (ENTIDADES.ENTI_NOMERAZAO) AS FORNECEDOR
FROM PRODUTOS
LEFT JOIN PRODUTOS_ESTOQUE ON (PRODUTOS.PROD_CODIGO = PRODUTOS_ESTOQUE.PROD_CODIGO)
LEFT JOIN GRUPO_PRODUTOS ON (PRODUTOS.GPPR_CODIGO = GRUPO_PRODUTOS.GPPR_CODIGO)
LEFT JOIN PRODUTOS_SUBGRUPOS ON (PRODUTOS.SGPR_CODIGO = PRODUTOS_SUBGRUPOS.SGPR_CODIGO)
LEFT JOIN PRODUTOS_CUSTOS ON (PRODUTOS.PROD_CODIGO = PRODUTOS_CUSTOS.PROD_CODIGO)
LEFT JOIN PRODUTOS_PRECOS ON (PRODUTOS.PROD_CODIGO = PRODUTOS_PRECOS.PROD_CODIGO)
LEFT JOIN PRODUTOS_TRIBUTACAO ON (PRODUTOS.PROD_CODIGO = PRODUTOS_TRIBUTACAO.PROD_CODIGO) AND PRODUTOS_TRIBUTACAO.OPER_CODIGO = 1 -- AQUI AJUSTA O TIPO DE TRIBUTO (SE NECESSARIO).
LEFT JOIN PRODUTOS_FORNECEDORES ON (PRODUTOS.PROD_CODIGO = PRODUTOS_FORNECEDORES.PROD_CODIGO)
LEFT JOIN PRODUTOS_CODIGO_FORNECEDOR ON (PRODUTOS.PROD_CODIGO = PRODUTOS_CODIGO_FORNECEDOR.PROD_CODIGO)
LEFT JOIN ENTIDADES ON (ENTIDADES.ENTI_CODIGO = PRODUTOS_CODIGO_FORNECEDOR.ENTI_CODIGO)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33
