SELECT
  CLIENTES.CODCLIENTE AS CODIGO,
  CLIENTES.NOME AS FANTASIA,
  CLIENTES.RAZAOSOCIAL AS NOME,
  CLIENTES.ENDERECO AS ENDERECO,
  CLIENTES.NUMERO AS NUMERO,
  CLIENTES.COMPLEMENTO AS COMPLEMENTO,
  BAIRROS.DESCRICAO AS BAIRRO,
  CIDADES.CIDADE AS CIDADE,
  CLIENTES.UF AS UF,
  CLIENTES.CEP AS CEP,
  CLIENTES.CPF_CNPJ AS CNPJ_CNPF,
  CLIENTES.IE_IDENTIDADE AS IE_RG,
  CLIENTES.INSCRICAO_MUNICIPAL AS IM,
  CLIENTES.ESTADO_CIVIL AS EST_CIVIL,
  CLIENTES.DT_NASCIMENTO AS NASCIMENTO,
  CLIENTES.NATURALIDADE AS NATURALIDADE,
  CLIENTES.TELEFONE1 AS TELEFONE,
  CLIENTES.TELEFAX AS FAX,
  CLIENTES.CELULAR AS CELULAR,
  CLIENTES.CONTATO AS CONTATO,
  CLIENTES.OBS AS OBSERVACOES,
  CLIENTES.EMAIL1 AS EMAIL,
  CLIENTES.PAI AS PAI,
  CLIENTES.MAE AS MAE,
  CLIENTES.VR_CREDITO AS LIMITE_CREDITO
FROM CLIENTES
LEFT JOIN BAIRROS ON BAIRROS.CODBAIRRO = CLIENTES.CODBAIRRO
LEFT JOIN CIDADES ON CIDADES.CODCIDADE = CLIENTES.CODCIDADE
