SELECT CLIENTES.CODIGO,
CLIENTES.NOME,
CLIENTES.APELIDO AS FANTASIA,
CLIENTES.CPFCLIEN AS CNPJ_CNPF,
CLIENTES.RGCLIEN AS IE_RG,
CLIENTES.FAX,
CLIENTES.CELULAR,
CLIENTES.ENDRESI AS ENDERECO,
CLIENTES.BAIRESI AS BAIRRO,
CLIENTES.CIDRESI AS CIDADE,
CLIENTES.UFRESID AS UF,
CLIENTES.CEP,
CLIENTES.EMAIL,
CLIENTES.NRO AS NUMERO
FROM CLIENTES
WHERE CLIENTES.CODIGO>0


