SELECT FORNEC.CODIGO,
FORNEC.FANTASIA,
FORNEC.RAZAOSOCIAL AS NOME,
FORNEC.CGC AS CNPJ_CNPF,
FORNEC.IE AS IE_RG,
FORNEC.FONE AS TELEFONE,
FORNEC.FAX,
FORNEC.ENDERECO,
FORNEC.BAIRRO,
FORNEC.CIDADE,
FORNEC.UF,
FORNEC.CEP,
FORNEC.CELULAR,
FORNEC.EMAIL,
FORNEC.NRO AS NUMERO
FROM FORNEC


