SELECT ACADPROD.CODIGO AS BARRAS,
ACADPROD.PROD AS DESCRICAO,
ACADPROD.UNID AS UND,
ACADPROD.ULTCOMPRA AS ULTIMA_COMPRA,
ACADPROD.ULTVENDA AS ULTIMA_VENDA,
ACADPROD.CUSTO AS PRECO_CUSTO,
ACADPROD.VENDA AS PRECO_VENDA,
ACADPROD.NOMEFORNEC AS FORNECEDOR,
ACADPROD.UNID_COMPRA AS UND_COMPRA,
ACADPROD.NCM AS COD_NCM,
ACADPROD.CSOSN AS ST,
ACADPROD.DT_CADASTRO AS DATA_CADASTRO,
ACADPROD.OBS AS OBSERVACOES,
ACADPROD.CEST AS PERSONAL6
FROM ACADPROD

