SELECT  
    PRODUTO.PRODUTOID AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    ESTOQUE.SALDO AS QTD,
    GRUPO.descricao AS grupo, 
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.CODIGO_BARRAS AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    PRODUTO.NCM AS COD_NCM,
    PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN ESTOQUE ON PRODUTO.PRODUTOID = ESTOQUE.PRODUTOID
LEFT JOIN GRUPO ON PRODUTO.grupoid = GRUPO.grupoid
