select
	CODIFOR as CODIGO,
	CNPJ as CNPJ_CNPF,
	NOME as NOME,
	FANTASIA as FANTASIA,
	CEP as CEP,
	ENDER as ENDERECO,
	BAIRRO as BAIRRO,
	CIDADE as CIDADE,
	EST as UF,
	FONE1 as TELEFONE,
	CELULAR as CELULAR,
	FAX as FAX,
	EMAIL as EMAIL,
	ISNCEST as IE_RG,
	COMPLEMENTO as COMPLEMENTO,
	OBS as OBSERVACOES
from fornecedor
