select
	P.CODI as CODIGO,
	P.CODALT as BARRAS,
	P.REFERENCIA as COD_FABRICANTE,
	P.DESCRICAO as DESCRICAO,
	P.FABRICANTE as FAMILIA,
	P.UN as UND,
	P.LINHA as CARACTERISTICAS,
	P.ESTMIN as QTD_IDEAL,
	P.VLRCUSTO as PRECO_CUSTO,
	P.VLRVENDA as PRECO_VENDA,
	P.VLRCUSTOMED as CUSTO_MEDIO,
	P.DTCADASTRO as DATA_CADASTRO,
	P.NCMSH as COD_NCM,
	P.SITTRIB as ELO,
	P.OBS as OBSERVACOES,
	SUBSTRING(P.CSOSN from 2 for 3) as ST,
	P.PRD_CEST as PERSONAL6,
	G.DESCRICAO as GRUPO,
	E.QNTPRD as QTD
from produto P
 left join GRUPO G on G.CODI = P.GRUPO
 left join ESTOQUE E on E.ID_PRODUTO = P.CODI 