SELECT
    PRODUTOS.CODPRODUTO AS CODIGO,
    PRODUTOS.DESCRICAO AS DESCRICAO,
    PRODUTOS.CODBARRAS AS BARRAS,
    PRODUTOS.CODORIGINAL AS COD_FABRICANTE,
    FORNECEDORES.RAZAOSOCIAL AS FORNECEDOR,
    GRUPOS.grupo AS GRUPO,
    SUBGRUPOS.SUBGRUPO AS FAMILIA,
    PRODUTOS.CODEMBALAGEM AS CARACTERISTICAS,
    ESTOQUE.estoque AS QTD,
    PRODUTOS.PRECOAQUISICAO AS PRECO_CUSTO,
    PRODUTOS.CMV AS CUSTO_MEDIO,
    PRODUTOS.PRECOCALC AS PRECO_VENDA,
    SUBSTRING (PRODUTOS.SITTRIB FROM 1 FOR 1) AS OST,
    SUBSTRING (PRODUTOS.SITTRIB FROM 2 FOR 4) AS ST,
    PRODUTOS.OBS AS OBSERVACOES,
    PRODUTOS.PESO AS PESO,
    PRODUTOS.NBM AS COD_NCM,
    PRODUTOS.DATACADASTRO AS DATA_CADASTRO,
    PRODUTOS.DATAATUALIZACAO AS ALTERACAO_PRECO,
    PRODUTOS.CEST AS PERSONAL6
FROM PRODUTOS
LEFT JOIN FORNECEDORES ON FORNECEDORES.codfornecedor = PRODUTOS.CODFORNECEDOR
LEFT JOIN grupos ON GRUPOS.codgrupo = PRODUTOS.CODGRUPO
LEFT JOIN subgrupos ON grupos.codgrupo = subgrupos.codgrupo and subgrupos.codsubgrupo = produtos.codsubgrupo
LEFT JOIN ESTOQUE ON ESTOQUE.codproduto = PRODUTOS.CODPRODUTO
