SELECT
    CLIENTES.CODCLIENTE AS CODIGO,
    CLIENTES.RAZAOSOCIAL AS NOME,
    CLIENTES.FANTASIA,
    CIDADES.CIDADE,
    CIDADES.UF,
    CLIENTES.CEP,
    CLIENTES.ENDERECO,
    CLIENTES.NUMERO,
    CLIENTES.COMPLEMENTO,
    CLIENTES.BAIRRO,
    CLIENTES.CNPJ AS CNPJ_CNPF,
    CLIENTES.INSCEST AS IE_RG,
    CLIENTES.EMAIL,
    CLIENTES.FONE1 AS TELEFONE,
    CLIENTES.CELULAR,
    CLIENTES.CONTATO
FROM CLIENTES
LEFT JOIN CIDADES ON CLIENTES.CODCIDADE = CIDADES.CODCIDADE
