SELECT
	F.CODIGO,
	F.NOME,
	F.FANTASIA,
	F.CPFCNPJ AS CNPJ_CNPF,
	F.RGIE AS IE_RG,
	F.ENDERECO,
	F.NUMEROENDERECO AS NUMERO,	
	F.COMPLEMENTO,
	F.BAIRRO,
	F.CEP,
	F.FONE AS TELEFONE,
	F.FAX,
	F.EMAIL,
	F.CONTATO,
	F.FONECONTATO AS CELULAR,
	F.FONECOMERVEND AS PERSONAL1,
	F.CELULARVEND AS PERSONAL2,
	F.EMAILVEND AS PERSONAL3,
	F.FONETELEVENDAS AS PERSONAL4,	
	F.OBSERVACAO ||' - '|| OBS AS OBSERVACOES,
	CI.NOME AS CIDADE,
	CI.ESTADO AS UF
FROM
	TPAGFORNECEDOR F
LEFT JOIN TGERCIDADE CI ON CI.CODIGO = F.CIDADE 