SELECT
	P.CODIGO,
	P.DESCRICAO,
	P.CODIGOBARRA AS BARRAS,
	P.CODIGOFABRICA AS COD_FABRICANTE,
	P.REFERENCIA AS PERSONAL1,
	P.EMBALAGEM AS UND,
	P.QTDEEMBALAGEM AS FAT_CONV,
	P.PESOBRUTO AS PESO,
	P.APLICACAO ||' - '|| OBSERVACAO ||' - '|| OBS AS OBSERVACOES,
	P.DATACADASTRO AS DATA_CADASTRO,
	P.DIASVALIDADE AS VALIDADE_DIAS,
	P.CLASSIFICACAOFISCAL AS COD_NCM,
	P.CODIGOCOMBUSTIVEL AS COD_ANP,
	P.IPI AS ALIQ_IPI_VENDA,
	P.TIPOIPIENTRADA AS IPI_CODIGO,
	P.TIPOIPISAIDA AS IPI_CODIGO_VENDA,
	P.CODIGOSITPIS AS PIS_CODIGO,
	P.ALIQPIS AS PIS_ALIQ_NOR,
	P.CODIGOSITCOFINS AS COFINS_CODIGO,
	P.ALIQCOFINS AS COFINS_ALIQ_NOR,
	P.CODIGOSITCOFINSENTRADA AS COFINSE_CODIGO,
	P.CODIGOSITPISENTRADA AS PISE_CODIGO,
	M.DESCRICAO AS FAMILIA,
	T.CSF AS ST,
	F.DESCRICAO AS CARACTERISTICAS,
	REPLACE(CE.CEST,'.','') AS PERSONAL6 ,
	ES.ESTDISPONIVEL AS QTD,
	ES.ESTIDEAL AS QTD_IDEAL,
	PV.PERCCOMISSAO AS COMISSAO,	
	PV.CUSTOFINAL AS PRECO_CUSTO,
	PV.CUSTOMEDIO AS CUSTO_MEDIO,
	PV.MARGEMLUCRO AS MARGEM_LUCRO,
	PV.PRPRATICADO AS PRECO_VENDA,
	PA.PRPRATICADO AS PRECO_ATACADO,
	PA.QTDEMINIMA AS QTD_PRECO_ATACADO 
FROM
	TESTPRODUTOGERAL P
LEFT JOIN TESTMARCA M ON M.CODIGO = P.MARCA 
LEFT JOIN TESTGRUPOICMS T ON T.CODIGOID = P.GRUPOICMS 
LEFT JOIN TESTFABRICANTE F ON F.CODIGO = P.FABRICANTE 
LEFT JOIN TESTCEST CE ON CE.IDCEST = P.IDCEST 
LEFT JOIN TESTESTOQUE ES ON ES.PRODUTO = P.CODIGO 
LEFT JOIN TESTTABELAPRECOPRODUTOS PV ON PV.PRODUTO =  P.CODIGO AND PV.IDTABELAPRECO = '1' -- PRECO DE VENDA
LEFT JOIN TESTTABELAPRECOPRODUTOS PA ON PA.PRODUTO =  P.CODIGO AND PA.IDTABELAPRECO = '2' -- PRECO DE ATACADO