SELECT
    PESSOA.ID_PESSOA AS CODIGO,
    MUNICIPIO.NOME AS CIDADE,
    UF.UF,
    PESSOA.NOME,
    PESSOA.DT_NASC_CRIACAO AS NASCIMENTO,
    PESSOA.CEP AS CEP,
    PESSOA.LOGRADOURO AS ENDERECO,
    PESSOA.NUMERO,
    PESSOA.BAIRRO,
    PESSOA.TELEFONE1 AS TELEFONE,
    PESSOA.EMAIL,
    PESSOA.RG AS IE_RG,
    PESSOA.COMPLEMENTO,
    PESSOA.DATA AS CADASTRO,
    PESSOA.CPF_CNPJ AS CNPJ_CNPF
FROM PESSOA
LEFT JOIN MUNICIPIO ON PESSOA.ID_MUNICIPIO = MUNICIPIO.ID_MUNICIPIO
LEFT JOIN UF ON PESSOA.ID_UF = UF.ID_UF
WHERE PESSOA.ID_PESSOA > 0
