SELECT
	P.CODIGOINTERNO AS CODIGO,
	P.IPPT,
	P.CODIGOCEST AS PERSONAL6,
	P.CODIGONCM AS COD_NCM,
	P.DATAULTIMACOMPRA AS ULTIMA_COMPRA,
	P.ESTOQUEATUAL AS QTD,
	P.ESTOQUEMINIMO AS QTD_IDEAL,
	P.GTIN AS BARRAS,
	P.MARKUP AS MARGEM_LUCRO,
	P.NOME AS DESCRICAO,	
	P.OBSERVACAO AS OBSERVACOES,
	P.PERCENTUALCOMISSAO AS COMISSAO,
	P.PESOBRUTO AS PESO,
	CASE P.PRODUTOINATIVO WHEN '0' THEN 'Ativo' WHEN '1' THEN 'Inativo' END AS SITUACAO,
	P.REFERENCIA AS COD_FAVRICANTE,
	P.VALIDADEDIAS AS VALIDADE_DIAS,
	P.VALORCUSTO AS PRECO_CUSTO,
	P.VALORVENDA AS PRECO_VENDA,
	P.CODIGOPRODUTOANP AS COD_ANP,
	P.VALORVENDAATACADO AS PRECO_ATACADO,
	P.QUANTIDADEENTRADAATACADO AS QTD_PRECO_ATACADO,
	G.NOME AS GRUPO,
	S.NOME AS FAMILIA,
	UN.DESCRICAO AS UND,
	A.ALIQUOTAIPI AS ALIQ_IPI_VENDA,
	A.ALIQUOTAPIS AS PIS_ALIQ_NOR,
	A.ALIQUOTACONFINS AS COFINS_ALIQ_NOR,
	A.IPICST AS IPI_CODIGO_VENDA,
	A.PISCST AS PIS_CODIGO,
	A.COFINSCST AS COFINS_CODIGO,
	A.ICMSCST AS ST,
	A.ICMSORIGEM AS OST,
	C.CFOP AS CF,
	LEFT (C.CFOP,3) AS ELO,
	PE.NOME AS FORNECEDOR
FROM
	PRODUOTOS P
LEFT JOIN GRUPOS G ON G.ID = P.IDGRUPO
LEFT JOIN SUBGRUPOS S ON S.ID = P.IDSUBGRUPO
LEFT JOIN UNIDADEMEDIDA UN ON UN.ID = P.IDUNIDADE
LEFT JOIN ALIQUOTAS A ON A.ID = P.IDFISCAL 
LEFT JOIN CFOP C ON C.ID = A.IDCFOPESTADUAL 
LEFT JOIN PESSOAS PE ON PE.ID = P.IDFORNECEDOR