SELECT
    --TPRODUTO.PROCODIGO AS CODIGO,
    TPRODUTO.PROCODIGO AS BARRAS,
    TPRODUTO.PRONOME AS DESCRICAO,
    TPRODUTO.PROREFERENCIA AS COD_FABRICANTE,
    TGRUPO.grunome AS GRUPO,
    TMARCA.marnome AS CARACTERISTICAS,
    substring (TTRIBUTACAO.trinome FROM 1 FOR 1) as ST,
    TUNIDADE.unisigla AS UND,
    TPRODUTO.PROCUSTOMEDIO AS CUSTO_MEDIO,
    TPRODUTO.PROESTMINIMO AS QTD_IDEAL,
    TPRODUTO.PROESTATUAL AS QTD,
    TPRODUTO.PROOBS AS OBSERVACOES,
    TPRODUTO.PROMARGEM AS MARGEM_LUCRO,
    TPRODUTO.PROPRECOVDA AS PRECO_VENDA,
    TPRODUTO.PRODATAULTCOMPRA AS ULTIMA_COMPRA,
    TPRODUTO.PROVALIDADEBAL AS VIDA_UTIL,
    case when TPRODUTO.PROCODIGOTIPI = '' or TPRODUTO.PROCODIGOTIPI is null then TPRODUTO.PRONCM else TPRODUTO.PROCODIGOTIPI END AS COD_NCM,
    TPRODUTO.PROCEST AS PERSONAL6
FROM TPRODUTO
LEFT JOIN TGRUPO ON TGRUPO.grucodigo = TPRODUTO.PROGRUPO
LEFT JOIN TUNIDADE ON TUNIDADE.unicodigo = TPRODUTO.PROUNIDADE
LEFT JOIN TMARCA ON TMARCA.marcodigo = TPRODUTO.PROMARCA
LEFT JOIN TTRIBUTACAO ON TTRIBUTACAO.tricodigo = TPRODUTO.PROTRIBUTACAO
