SELECT
   RIGHT (P.CEProCod, 6) AS CODIGO
, P.CEProCodBa as BARRAS
, P.CEProFab AS COD_FABRICANTE
, P.CEProDesCo AS DESCRICAO
, G.CEGrpDes  AS GRUPO
, S.CESgrDes AS FAMILIA
, P.CEProDtaCa AS DATA_CADASTRO
, P.CEProMrgLu AS MARGEM_LUCRO
, P.CEProUnd AS UND
, P.CEProNCM AS COD_NCM
, P.CEProAlqIP AS ALIQ_IPI_VENDA
, P.CEProCSTOu AS ST
, P.CEProPis AS PIS_CODIGO
, P.CEProCof AS COFINS_CODIGO
, CAST(P.CEProPerAl AS INTEGER) AS ELO
, P.CEProDesFo AS FORNECEDOR
, P.CEProQtdUl AS QTD
, p.CEProQtdPa AS FAT_CONV
, P.CEPro1Cus AS PRECO_CUSTO
, P.CEProVlrPa AS PRECO_VENDA
, P.CEProCusMe AS CUSTO_MEDIO
, P.CEProCSEPi AS PISE_CODIGO
, P.CEProCSECo AS COFINSE_CODIGO
--, P.CEProQtdV1
--, P.CEProPreCu
--, P.CEPro3Cus
--, P.CEProCusDo
--, P.CEPro2Cus
--, P.CEProCusFi
--, P.CEProCusCP
--, P.CEProPreTa
--, P.CEProPreVd
--, P.CEProPrcCo
--, P.CEProPre1T >>>PREÇO TOTAL (FAT_CONV * PRECO_VENDA)
FROM MSINFOR.dbo.CEPro P
LEFT JOIN CESgr S ON S.CESgrCod = P.CESgrCod AND S.CEGrpCod  = P.CEGrpCod 
LEFT JOIN CEGrp G ON G.CEGrpCod = S.CEGrpCod  