SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    ESTADO AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    CELULAR AS CELULAR,
    CONTATO AS CONTATO,
    CNPJ AS CNPJ_CNPF,
    IE AS IE_RG,
    EMAIL AS EMAIL,
    OBS AS OBSERVACOES,
    END_NUMERO AS NUMERO,
    FAX AS FAX,
    ENDER_COMPLEMENTO AS COMPLEMENTO
FROM FORN
