SELECT
    PROD.CODIGO AS CODIGO,
    PROD.DESCRICAO AS DESCRICAO,
    PROD.UN AS UND,
    GRUPO.DESCRICAO AS GRUPO,
    PROD.CUSTO AS PRECO_CUSTO,
    PROD.MARGEM AS MARGEM_LUCRO,
    PROD.PRECO AS PRECO_VENDA,
    PROD.SALDOA AS QTD,
    PROD.MINIMO AS QTD_IDEAL,
    PROD.CBARRA AS BARRAS,
    PROD.ULT_ALTERAP AS ALTERACAO_PRECO,
    SUBSTRING (PROD.SIT_TRIB FROM 1 FOR 1) AS OST,
    SUBSTRING (PROD.SIT_TRIB FROM 2 FOR 3) AS ST,
    PROD.DATA_CAD AS DATA_CADASTRO,
    PROD.NCM AS COD_NCM,
    PROD.COD_REFERENCIA AS COD_FABRICANTE,
    PROD.CEST AS PERSONAL6,
    PROD.GTIN,
    PROD.CUSTOMEDIO
FROM PROD
LEFT JOIN GRUPO ON GRUPO.CODIGO = PROD.GRUPO
