SELECT
    CODIGO AS CODIGO,
    NOME AS NOME,
    ENDERECO AS ENDERECO,
    BAIRRO AS BAIRRO,
    CIDADE AS CIDADE,
    UF AS UF,
    CEP AS CEP,
    TELEFONE AS TELEFONE,
    CELULAR AS CELULAR,
    CPF || CGC AS CNPJ_CNPF,
    RG || IE AS IE_RG,
    NUMERO AS NUMERO,
    EMAIL AS EMAIL
FROM CLIENTE
WHERE CODIGO > 0