SELECT  
    PRODUTO.PRODUTOID AS CODIGO,
    PRODUTO.DESCRICAO AS DESCRICAO,
    ESTOQUE.SALDO AS QTD,
    GRUPO.descricao AS grupo, 
    PRODUTO.REFERENCIA AS COD_FABRICANTE,
    PRODUTO.CODIGO_BARRAS AS BARRAS,
    PRODUTO.UNIDADE AS UND,
    MIN (CLASSIFICACAO_TRIBUTARIA.cst_saida) AS ST,
    POLITICA_PRECO.PRECO_COMPRA AS PRECO_CUSTO,
    POLITICA_PRECO.LUCRO_LIQUIDO AS MARGEM_LUCRO,
    POLITICA_PRECO.PRECO_AVISTA AS PRECO_VENDA,
    POLITICA_PRECO.UL_ALTERACAO AS ULTIMA_ALTERACAO,
    PRODUTO.NCM AS COD_NCM,
    SUBGRUPO.descricao AS CARACTERISTICAS
    --PRODUTO.CEST AS PERSONAL6
FROM PRODUTO
LEFT JOIN ESTOQUE ON PRODUTO.PRODUTOID = ESTOQUE.PRODUTOID and ESTOQUE.contaid = '1'
LEFT JOIN GRUPO ON PRODUTO.grupoid = GRUPO.grupoid and GRUPO.filial = '2' AND GRUPO.secaoid = 'C'
left join CLASSIFICACAO_TRIBUTARIA on CLASSIFICACAO_TRIBUTARIA.cstid = produto.cst
left join POLITICA_PRECO on POLITICA_PRECO.produtoid = PRODUTO.PRODUTOID AND politica_PRECO.tabelaid = '1'
left join subgrupo on subgrupo.subgrupoid = produto.subgrupoid and subgrupo.grupoid = grupo.grupoid and SUBGRUPO.filial = '2' AND SUBGRUPO.secaoid = 'C'
GROUP BY 1,2,3,4,5,6,7,9,10,11,12,13,14
